/**
 * ABox stable screen ID registry.
 *
 * Every SCR_ / UX_ ID from the IA Handoff Package and Module 1 V4
 * Reconciliation Packet is enumerated here so route files can annotate
 * their identity and phase posture in one place.
 *
 * Phase posture:
 *  - "m1"           → Active Module 1 build (do not disrupt)
 *  - "m1-align"     → Non-breaking IA alignment on top of Module 1
 *  - "phase1"       → Broader Phase 1 (Module 2 candidate / later Phase 1)
 *  - "future"       → Future seam only (stub, no build)
 */
export type PhasePosture = "m1" | "m1-align" | "phase1" | "future";

export interface ScreenMeta {
  id: string;
  name: string;
  workspace:
    | "marketplace"
    | "member"
    | "agent"
    | "agency"
    | "jet"
    | "carrier"
    | "employer"
    | "partner"
    | "system";
  phase: PhasePosture;
  purpose: string;
}

export const SCREENS: Record<string, ScreenMeta> = {
  // ----- Consumer Marketplace (Module 1) -----
  "UX-001": { id: "UX-001", name: "Marketplace Landing", workspace: "marketplace", phase: "m1",
    purpose: "Branded marketplace landing; lead-with-Health/IFP; product cards; ICHRA employer path; persistent help." },
  "UX-002": { id: "UX-002", name: "Product Selection & Path Choice", workspace: "marketplace", phase: "m1",
    purpose: "Choose Plan-AI guided vs Browse Myself after selecting product." },
  "UX-003": { id: "UX-003", name: "Quote Wizard — ZIP & Effective Date", workspace: "marketplace", phase: "m1",
    purpose: "ZIP input, county resolution, effective date default = 1st of next month." },
  "UX-004": { id: "UX-004", name: "Quote Wizard — Household Members", workspace: "marketplace", phase: "m1",
    purpose: "Primary DOB, sex, tobacco; add/remove family members with relationship." },
  "UX-005": { id: "UX-005", name: "Plan-AI — Goals & Usage", workspace: "marketplace", phase: "m1",
    purpose: "Priority ranking, expected usage, doctor match, Plan-AI worksheet." },
  "UX-006": { id: "UX-006", name: "Provider & Drug Optional Lookup", workspace: "marketplace", phase: "m1",
    purpose: "Optional provider and drug search; skip option; matched-results feedback." },
  "UX-007": { id: "UX-007", name: "Optional Subsidy Check", workspace: "marketplace", phase: "m1",
    purpose: "Estimated income, tax household size; skip subsidy option." },
  "UX-008": { id: "UX-008", name: "Subsidy Estimate & Education", workspace: "marketplace", phase: "m1",
    purpose: "Estimated APTC/CSR education, disclaimer, continue to plans." },
  "UX-009": { id: "UX-009", name: "Plan Results", workspace: "marketplace", phase: "m1",
    purpose: "Recommended plans, on/off-exchange toggle, filters, cart drawer entry." },
  "UX-010": { id: "UX-010", name: "Plan Detail", workspace: "marketplace", phase: "m1",
    purpose: "Benefits, costs, network + Rx, Plan-AI explanation, add to cart / compare." },
  "UX-011": { id: "UX-011", name: "Plan Comparison", workspace: "marketplace", phase: "m1",
    purpose: "Side-by-side comparison up to 5 plans; expandable detailed rows." },
  "UX-012": { id: "UX-012", name: "More Coverage & Ancillary Cards", workspace: "marketplace", phase: "m1",
    purpose: "Dental, vision, life, critical illness, accident, hospital indemnity cards." },
  "UX-013": { id: "UX-013", name: "Cart Drawer", workspace: "marketplace", phase: "m1",
    purpose: "Cart grouped by product type; effective term/plan/status; review & enroll." },
  "UX-014": { id: "UX-014", name: "Review & Enroll Gate", workspace: "marketplace", phase: "m1",
    purpose: "Review by product; per-product validation; next-step explanation and CTA." },
  "SCR_OFFEX_APPLICATION": { id: "SCR_OFFEX_APPLICATION", name: "Off-Exchange Application", workspace: "marketplace", phase: "phase1",
    purpose: "Lucie WS-04 off-exchange application runtime: fixed versioned application, typed consent, e-signature and carrier PDF or EDI output with state separation." },
  "UX-015": { id: "UX-015", name: "Registration / Login", workspace: "marketplace", phase: "m1",
    purpose: "Register with email+password or phone OTP; light consent." },
  "UX-016": { id: "UX-016", name: "Consumer Dashboard", workspace: "member", phase: "m1",
    purpose: "Saved quotes, carts, applications, tasks, messages; Plan-AI resume summary." },
  "UX-017": { id: "UX-017", name: "Agent Quick Quote — Start", workspace: "agent", phase: "m1",
    purpose: "Start anonymous prospect quote or find existing lead." },
  "UX-018": { id: "UX-018", name: "Agent Quick Quote — Workspace", workspace: "agent", phase: "m1",
    purpose: "Compact quote input, results panel, Plan-AI assist, send/add/request follow-up." },
  "UX-019": { id: "UX-019", name: "Agent Send Quote", workspace: "agent", phase: "m1",
    purpose: "Choose plans, channel, template preview, expiration default 7 days." },
  "UX-020": { id: "UX-020", name: "Shared Quote — Read-Only View", workspace: "marketplace", phase: "m1",
    purpose: "Tokenized shared quote; I'm interested; request call; no cart mutation without login." },
  "UX-021": { id: "UX-021", name: "Lead Timeline & Milestones", workspace: "agent", phase: "m1",
    purpose: "Lead timeline with filters; milestones; next action; duplicate detection." },
  "UX-022": { id: "UX-022", name: "Schedule Time / Request Call", workspace: "marketplace", phase: "m1",
    purpose: "Request call form; calendar slot picker; confirmation and task creation." },
  "UX-023": { id: "UX-023", name: "JET Handoff Confirmation", workspace: "marketplace", phase: "m1",
    purpose: "Selected plans; generate handoff packet; open JET marketplace new tab; cart status." },
  "UX-024": { id: "UX-024", name: "Module 1 Config — Branding & Products", workspace: "jet", phase: "m1",
    purpose: "Marketplace branding basics; product availability; ranking; disclosure text." },
  "UX-025": { id: "UX-025", name: "Module 1 Config — Routing & Notifications", workspace: "jet", phase: "m1",
    purpose: "Routing basics; channel/template basics; scheduling availability; Plan-AI on/off." },
  "UX-026": { id: "UX-026", name: "AI Review & Confirmation", workspace: "marketplace", phase: "m1",
    purpose: "Review AI-filled fields; confirm / edit; strict confirmation for sensitive next steps." },

  // ----- Broader Phase 1 (Module 2 candidates / later Phase 1) -----
  "SCR_APP_MY_WORK": { id: "SCR_APP_MY_WORK", name: "My Work", workspace: "agent", phase: "phase1",
    purpose: "Prioritized tasks, follow-ups, unread messages, hot leads for the signed-in operator." },
  "SCR_APP_DASHBOARD": { id: "SCR_APP_DASHBOARD", name: "Performance Dashboard", workspace: "agent", phase: "phase1",
    purpose: "Performance cards, funnel, quote activity, commission projection snapshot." },
  "SCR_APP_CUSTOMERS": { id: "SCR_APP_CUSTOMERS", name: "Customers & Leads", workspace: "agent", phase: "phase1",
    purpose: "Unified customer + lead list with segmentation, filters, saved views." },
  "SCR_APP_LEAD_DETAIL": { id: "SCR_APP_LEAD_DETAIL", name: "Lead / Customer Detail", workspace: "agent", phase: "phase1",
    purpose: "Object page with timeline, quotes, applications, communications, tasks." },
  "SCR_APP_COMMUNICATIONS": { id: "SCR_APP_COMMUNICATIONS", name: "Communications", workspace: "agent", phase: "phase1",
    purpose: "Unified inbox: email, SMS, in-app messages; templates and quick replies." },
  "SCR_APP_TASKS": { id: "SCR_APP_TASKS", name: "Tasks", workspace: "agent", phase: "phase1",
    purpose: "Manual and event-triggered tasks with assignments and SLA cues." },
  "SCR_APP_COMMISSIONS": { id: "SCR_APP_COMMISSIONS", name: "Commissions", workspace: "agent", phase: "phase1",
    purpose: "Agent statements, projected earnings, dispute submission." },
  "SCR_APP_OFF_EXCHANGE": { id: "SCR_APP_OFF_EXCHANGE", name: "Off-Exchange Enrollment", workspace: "agent", phase: "phase1",
    purpose: "Intake, dynamic application form, payment capture, submission status." },
  "SCR_AGENCY_SETUP": { id: "SCR_AGENCY_SETUP", name: "Agency & Entity Setup", workspace: "agency", phase: "phase1",
    purpose: "Agency records, relationship graph, master/child hierarchy, entity switching." },
  "SCR_AGENCY_PRODUCERS": { id: "SCR_AGENCY_PRODUCERS", name: "Producers & Licenses", workspace: "agency", phase: "phase1",
    purpose: "Producer records, license & appointment tracking, NIPR reconciliation posture." },
  "SCR_AGENCY_REVENUE": { id: "SCR_AGENCY_REVENUE", name: "Revenue Splits & Referrals", workspace: "agency", phase: "phase1",
    purpose: "Configure revenue splits, referral rewards, hierarchy overrides." },
  "SCR_AGENCY_STATEMENTS": { id: "SCR_AGENCY_STATEMENTS", name: "Agency Statements", workspace: "agency", phase: "phase1",
    purpose: "Statement periods, projected vs booked commissions, exports." },
  "SCR_JET_PRODUCTS": { id: "SCR_JET_PRODUCTS", name: "Product Catalog", workspace: "jet", phase: "phase1",
    purpose: "Registry of products (IFP, Medicare, dental, vision, ICHRA, life, etc.)." },
  "SCR_JET_PRODUCT_BUILDER": { id: "SCR_JET_PRODUCT_BUILDER", name: "Product Builder", workspace: "jet", phase: "phase1",
    purpose: "Configure product schemas, availability rules, versioning." },
  "SCR_JET_APPOINTMENTS": { id: "SCR_JET_APPOINTMENTS", name: "Carrier Appointments", workspace: "jet", phase: "phase1",
    purpose: "Carrier appointment records, state matrix, effective ranges." },
  "SCR_JET_FORM_CONFIG": { id: "SCR_JET_FORM_CONFIG", name: "Form Configurator", workspace: "jet", phase: "phase1",
    purpose: "Field builder, conditional logic, required docs, signature, versioning, preview." },
  "SCR_JET_NOTIFICATIONS": { id: "SCR_JET_NOTIFICATIONS", name: "Notification Scheduler", workspace: "jet", phase: "phase1",
    purpose: "Templates, event triggers, time-based schedules, recurring/delayed sends." },
  "SCR_JET_BRANDING": { id: "SCR_JET_BRANDING", name: "Branding & White-Label", workspace: "jet", phase: "phase1",
    purpose: "Tenant/agency branding tokens, logo, disclosures, live/demo mode." },
  "SCR_JET_ACL": { id: "SCR_JET_ACL", name: "ACL Configuration", workspace: "jet", phase: "phase1",
    purpose: "Global + local ACL policies, role templates, guardrail warnings." },
  "SCR_JET_AUDIT": { id: "SCR_JET_AUDIT", name: "Audit Log", workspace: "jet", phase: "phase1",
    purpose: "Immutable event log with filters, exports, compliance holds." },
  "SCR_PLATFORM_HOME": { id: "SCR_PLATFORM_HOME", name: "Platform Foundation (M00)", workspace: "jet", phase: "phase1",
    purpose: "Governed M00 baseline: registry counts, change control, environments, launch gates, risks, open items and governed screens." },
  "SCR_JET_AI_GOV": { id: "SCR_JET_AI_GOV", name: "AI / Plan-AI Governance", workspace: "jet", phase: "phase1",
    purpose: "Enable/disable per tenant/module/role; knowledge sources; disclaimers; escalation." },
  "SCR_JET_INTEGRATIONS": { id: "SCR_JET_INTEGRATIONS", name: "Integrations", workspace: "jet", phase: "phase1",
    purpose: "Carrier feeds, EDE, drug/provider directories, pay processors, webhook subscriptions." },
  "SCR_EMPLOYER_ICHRA": { id: "SCR_EMPLOYER_ICHRA", name: "Employer ICHRA Quote", workspace: "employer", phase: "phase1",
    purpose: "Group census, deep-quote foundation. Enrollment excluded from Phase 1." },
  "SCR_PARTNER_HOME": { id: "SCR_PARTNER_HOME", name: "Partner / Referral Home", workspace: "partner", phase: "phase1",
    purpose: "Referral submission, status, reward settings visibility." },
  "SCR_SYS_SETTINGS": { id: "SCR_SYS_SETTINGS", name: "Personal Settings", workspace: "system", phase: "phase1",
    purpose: "Profile, notification preferences, theme, security." },

  // ----- M05: Organization, Relationship and Multi-Tenant Model -----
  "SCR-M05-002": { id: "SCR-M05-002", name: "Root Agency Administration Home", workspace: "agency", phase: "phase1",
    purpose: "Operational summary and root quick actions for the tenant-owning root agency." },
  "SCR-M05-004": { id: "SCR-M05-004", name: "Organization Directory", workspace: "agency", phase: "phase1",
    purpose: "Authorized tenant-wide organization directory and filters." },
  "SCR-M05-006": { id: "SCR-M05-006", name: "Organization Profile", workspace: "agency", phase: "phase1",
    purpose: "Fixed profile sections — contacts, addresses, identifiers, settings, readiness, history." },
  "SCR-M05-007": { id: "SCR-M05-007", name: "Create Downline Agency: Identity", workspace: "agency", phase: "phase1",
    purpose: "Draft identity and duplicate preview." },
  "SCR-M05-008": { id: "SCR-M05-008", name: "Create Downline Agency: Legal and Identifiers", workspace: "agency", phase: "phase1",
    purpose: "Legal fields, evidence and identifiers." },
  "SCR-M05-009": { id: "SCR-M05-009", name: "Create Downline Agency: Contacts", workspace: "agency", phase: "phase1",
    purpose: "Required contact roles." },
  "SCR-M05-010": { id: "SCR-M05-010", name: "Create Downline Agency: Addresses and Offices", workspace: "agency", phase: "phase1",
    purpose: "Headquarters, mailing and offices." },
  "SCR-M05-011": { id: "SCR-M05-011", name: "Create Downline Agency: Settings", workspace: "agency", phase: "phase1",
    purpose: "Copied defaults and editable settings." },
  "SCR-M05-012": { id: "SCR-M05-012", name: "Create Downline Agency: Initial Administrator", workspace: "agency", phase: "phase1",
    purpose: "M00 invitation and membership readiness." },
  "SCR-M05-013": { id: "SCR-M05-013", name: "Create Downline Agency: Readiness Review", workspace: "agency", phase: "phase1",
    purpose: "Fixed control outcomes and blockers." },
  "SCR-M05-014": { id: "SCR-M05-014", name: "Create Downline Agency: Activation", workspace: "agency", phase: "phase1",
    purpose: "Activation confirmation and result." },
  "SCR-M05-015": { id: "SCR-M05-015", name: "Downline Context Banner", workspace: "agency", phase: "phase1",
    purpose: "Persistent actual-user, root and downline context." },
  "SCR-M05-001": { id: "SCR-M05-001", name: "JET Tenant and Organization Operations", workspace: "jet", phase: "phase1",
    purpose: "JET tenant and organization oversight and controlled actions." },
  "SCR-M05-003": { id: "SCR-M05-003", name: "Downline Administration Home", workspace: "agency", phase: "phase1",
    purpose: "Own-organization readiness, profile and next actions." },
  "SCR-M05-005": { id: "SCR-M05-005", name: "Organization Structure", workspace: "agency", phase: "phase1",
    purpose: "Root and direct-downline hierarchy with actions." },
  "SCR-M05-016": { id: "SCR-M05-016", name: "Organization Readiness", workspace: "agency", phase: "phase1",
    purpose: "Control-level readiness and next actions." },
  "SCR-M05-017": { id: "SCR-M05-017", name: "Organization Contacts", workspace: "agency", phase: "phase1",
    purpose: "Fixed contact roles and visibility." },
  "SCR-M05-018": { id: "SCR-M05-018", name: "Organization Addresses and Offices", workspace: "agency", phase: "phase1",
    purpose: "Address and office history." },
  "SCR-M05-019": { id: "SCR-M05-019", name: "Organization External Identifiers", workspace: "agency", phase: "phase1",
    purpose: "Masked identifier and verification history." },
  "SCR-M05-020": { id: "SCR-M05-020", name: "Organization Settings", workspace: "agency", phase: "phase1",
    purpose: "Downline-owned values and root overrides." },
  "SCR-M05-021": { id: "SCR-M05-021", name: "Organization Relationship History", workspace: "agency", phase: "phase1",
    purpose: "Effective relationship evidence." },
  "SCR-M05-022": { id: "SCR-M05-022", name: "Organization Activity and Change History", workspace: "agency", phase: "phase1",
    purpose: "Immutable actor and context before-and-after history." },
  "SCR-M05-023": { id: "SCR-M05-023", name: "Organization Imports", workspace: "agency", phase: "phase1",
    purpose: "Template, upload, validation, preview and commit." },
  "SCR-M05-024": { id: "SCR-M05-024", name: "Organization Import Result", workspace: "agency", phase: "phase1",
    purpose: "Row results, errors and committed outcome." },
  "SCR-M05-025": { id: "SCR-M05-025", name: "Root Defaults Bulk Application", workspace: "agency", phase: "phase1",
    purpose: "Review and apply selected values." },
  "SCR-M05-026": { id: "SCR-M05-026", name: "Organization Tasks and Exceptions", workspace: "agency", phase: "phase1",
    purpose: "Fixed M05 work types and escalation." },
  "SCR-M05-027": { id: "SCR-M05-027", name: "Organization Suspension and Reactivation", workspace: "agency", phase: "phase1",
    purpose: "Impact review and governed lifecycle command." },
  "SCR-M05-028": { id: "SCR-M05-028", name: "Organization Ending and Offboarding", workspace: "agency", phase: "phase1",
    purpose: "Individual continuity checklist." },
  "SCR-M05-029": { id: "SCR-M05-029", name: "Reference Organization Request", workspace: "agency", phase: "phase1",
    purpose: "Carrier and vendor reference request." },
  "SCR-M05-030": { id: "SCR-M05-030", name: "JET Override and Reconciliation", workspace: "jet", phase: "phase1",
    purpose: "Reason-coded override and propagation reconciliation." },

  // ----- M04: Marketplace Management and White Labeling -----
  "SCR-M04-001": { id: "SCR-M04-001", name: "JET Marketplace Operations", workspace: "jet", phase: "phase1",
    purpose: "JET cross-tenant marketplace operational overview and explicit-context actions." },
  "SCR-M04-002": { id: "SCR-M04-002", name: "Marketplace Administration Home", workspace: "agency", phase: "phase1",
    purpose: "Root operational summary, release status, blockers and quick actions." },
  "SCR-M04-003": { id: "SCR-M04-003", name: "Downline Marketplace Participation", workspace: "agency", phase: "phase1",
    purpose: "Own participation, support, referral links, readiness and correction requests." },
  "SCR-M04-004": { id: "SCR-M04-004", name: "Marketplace Identity and Brand", workspace: "agency", phase: "phase1",
    purpose: "Display identity, fixed assets, colors and accessible validation." },
  "SCR-M04-005": { id: "SCR-M04-005", name: "Marketplace Content and Language", workspace: "agency", phase: "phase1",
    purpose: "English and Spanish general and channel content and controlled legal assignments." },
  "SCR-M04-006": { id: "SCR-M04-006", name: "Marketplace Assets", workspace: "agency", phase: "phase1",
    purpose: "Upload, scan, validate, preview and retire fixed asset types." },
  "SCR-M04-007": { id: "SCR-M04-007", name: "Domains and Public Routes", workspace: "agency", phase: "phase1",
    purpose: "JET subdomain, custom-domain request, verification, activation and route continuity." },
  "SCR-M04-008": { id: "SCR-M04-008", name: "Custom Domain Request", workspace: "agency", phase: "phase1",
    purpose: "Fixed domain ownership, verification, preview and JET submission flow." },
  "SCR-M04-009": { id: "SCR-M04-009", name: "Channels and Product Availability", workspace: "agency", phase: "phase1",
    purpose: "State, product line, carrier and channel matrix with canonical blockers." },
  "SCR-M04-010": { id: "SCR-M04-010", name: "Availability Entry Detail", workspace: "agency", phase: "phase1",
    purpose: "Explain entitlement, product, carrier, geography, participant and integration readiness." },
  "SCR-M04-011": { id: "SCR-M04-011", name: "Participants", workspace: "agency", phase: "phase1",
    purpose: "Direct-downline participant status, channels, support, links and readiness." },
  "SCR-M04-012": { id: "SCR-M04-012", name: "Participant Detail", workspace: "agency", phase: "phase1",
    purpose: "Enable, suspend, end and review one participant without altering M05 lifecycle." },
  "SCR-M04-013": { id: "SCR-M04-013", name: "Referral Links", workspace: "agency", phase: "phase1",
    purpose: "View, create, copy, revoke and replace organization and agent links." },
  "SCR-M04-014": { id: "SCR-M04-014", name: "Referral Link Detail", workspace: "agency", phase: "phase1",
    purpose: "Link status, participant, channel, product, use history and readiness." },
  "SCR-M04-015": { id: "SCR-M04-015", name: "Routing and Support Identity", workspace: "agency", phase: "phase1",
    purpose: "Fixed routing posture, root fallback and contextual support." },
  "SCR-M04-016": { id: "SCR-M04-016", name: "Marketplace Readiness", workspace: "agency", phase: "phase1",
    purpose: "Fixed readiness controls, canonical owner and next action." },
  "SCR-M04-017": { id: "SCR-M04-017", name: "Draft versus Active Comparison", workspace: "agency", phase: "phase1",
    purpose: "Business-impact comparison across release components." },
  "SCR-M04-018": { id: "SCR-M04-018", name: "Marketplace Preview", workspace: "agency", phase: "phase1",
    purpose: "Private language, device, channel, product, participant, referral and scenario preview." },
  "SCR-M04-019": { id: "SCR-M04-019", name: "Publication Review", workspace: "agency", phase: "phase1",
    purpose: "Coordinated release scope, continuity, blockers and approval level." },
  "SCR-M04-020": { id: "SCR-M04-020", name: "Initial Activation Submission", workspace: "agency", phase: "phase1",
    purpose: "Submit first production release to JET and review status." },
  "SCR-M04-021": { id: "SCR-M04-021", name: "Scheduled Publication", workspace: "agency", phase: "phase1",
    purpose: "One future effective publication with readiness revalidation." },
  "SCR-M04-022": { id: "SCR-M04-022", name: "Marketplace Lifecycle", workspace: "agency", phase: "phase1",
    purpose: "Suspend, reactivate, request ending and review continuity." },
  "SCR-M04-023": { id: "SCR-M04-023", name: "Marketplace Tasks and Exceptions", workspace: "agency", phase: "phase1",
    purpose: "Fixed M04 tasks, exceptions, owner module and escalation." },
  "SCR-M04-024": { id: "SCR-M04-024", name: "Marketplace History", workspace: "agency", phase: "phase1",
    purpose: "Immutable release, domain, participant, link, routing and JET override history." },
  "SCR-M04-025": { id: "SCR-M04-025", name: "Marketplace Operational Health", workspace: "agency", phase: "phase1",
    purpose: "Current release, route, content, product, participant, propagation and delta health." },
  "SCR-M04-026": { id: "SCR-M04-026", name: "JET Marketplace Override and Reconciliation", workspace: "jet", phase: "phase1",
    purpose: "Reason-coded JET override, route intervention and propagation reconciliation." },
  "SCR-M04-027": { id: "SCR-M04-027", name: "Public Marketplace Home", workspace: "marketplace", phase: "phase1",
    purpose: "Marketplace brand, enabled pathway cards, support, language, attribution and sign-in." },
  "SCR-M04-028": { id: "SCR-M04-028", name: "Public Pathway Entry", workspace: "marketplace", phase: "phase1",
    purpose: "Validated fixed entry into an enabled governed pathway." },
  "SCR-M04-029": { id: "SCR-M04-029", name: "Referral Entry Confirmation", workspace: "marketplace", phase: "phase1",
    purpose: "Marketplace, agency, agent and new-journey confirmation without record access." },
  "SCR-M04-030": { id: "SCR-M04-030", name: "Existing Journey or New Journey Choice", workspace: "marketplace", phase: "phase1",
    purpose: "Explicit resume-original, start-new or governed transfer choice." },
  "SCR-M04-031": { id: "SCR-M04-031", name: "Named Agent Unavailable", workspace: "marketplace", phase: "phase1",
    purpose: "Explicit same-agency, another-agent, root, self-service or home alternatives." },
  "SCR-M04-032": { id: "SCR-M04-032", name: "No Ready Products", workspace: "marketplace", phase: "phase1",
    purpose: "Safe no-ready-product result and explicit approved next actions." },
  "SCR-M04-033": { id: "SCR-M04-033", name: "Marketplace Suspended", workspace: "marketplace", phase: "phase1",
    purpose: "New-start block with permitted sign-in or existing-record continuity." },
  "SCR-M04-034": { id: "SCR-M04-034", name: "Marketplace Route Unavailable", workspace: "marketplace", phase: "phase1",
    purpose: "Fail-closed unknown, invalid, suspended or retired route state." },
  "SCR-M04-035": { id: "SCR-M04-035", name: "Marketplace Deep-Link Unavailable", workspace: "marketplace", phase: "phase1",
    purpose: "Unavailable pathway with no silent fallback and explicit approved alternatives." },
  "SCR-M04-036": { id: "SCR-M04-036", name: "Marketplace Support", workspace: "marketplace", phase: "phase1",
    purpose: "One current primary support route for marketplace and responsible organization context." },
};
