/**
 * Reconciliation of the earlier project wireframe estate to Phase 1 IA v2.0
 * and the Lucie surface baseline.
 *
 * The /m1, /p1 and /hf sets were produced against Phase 1 IA v1.0 and the now
 * retired June 2026 sequencing pack. IA v2.0 controls IDs and placement, so
 * each legacy screen resolves to one of three dispositions:
 *
 *  - "reconciled"  — the legacy screen maps to live Lucie surface IDs.
 *  - "excluded"    — the capability sits behind an excluded module / protected
 *                    seam; the legacy screen is historical only and must never
 *                    be presented as implemented.
 *  - "out-of-scope" — inside ABox but outside Lucie delivery depth.
 */

export type Disposition = "reconciled" | "excluded" | "out-of-scope";

export interface ReconciliationEntry {
  legacyId: string;
  legacySet: "M1 low-fi" | "P1 low-fi" | "Higher fidelity";
  legacyName: string;
  legacyRoute: string;
  disposition: Disposition;
  surfaces: string[];
  seams: string[];
  note: string;
}

export const RECONCILIATION: ReconciliationEntry[] = [
  // ---------------------------------------------------------------- M1 low-fi
  {
    legacyId: "UX-001",
    legacySet: "M1 low-fi",
    legacyName: "Marketplace Landing",
    legacyRoute: "/m1/ux-001",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_CONS_LANDING"],
    seams: [],
    note: "Branded storefront context now comes from M04 marketplace configuration, not page-level copy.",
  },
  {
    legacyId: "UX-002",
    legacySet: "M1 low-fi",
    legacyName: "Product Selection & Path Choice",
    legacyRoute: "/m1/ux-002",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PRODUCT_SELECT"],
    seams: [],
    note: "Paths are IFP on/off exchange, dental, vision and ICHRA only.",
  },
  {
    legacyId: "UX-003",
    legacySet: "M1 low-fi",
    legacyName: "Quote Wizard: ZIP, County & Effective Date",
    legacyRoute: "/m1/ux-003",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_ELIGIBILITY_INTAKE"],
    seams: [],
    note: "IA v2.0 merges wizard steps into one governed intake surface.",
  },
  {
    legacyId: "UX-004",
    legacySet: "M1 low-fi",
    legacyName: "Quote Wizard: Household Members",
    legacyRoute: "/m1/ux-004",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_ELIGIBILITY_INTAKE"],
    seams: [],
    note: "Household composition is a step of the same intake surface.",
  },
  {
    legacyId: "UX-005",
    legacySet: "M1 low-fi",
    legacyName: "Plan-AI Goals & Usage",
    legacyRoute: "/m1/ux-005",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PLANO_GUIDED_INTAKE"],
    seams: [],
    note: "Stable ID retained; display label renamed Plan AI to PlanAI. Text-only in Lucie.",
  },
  {
    legacyId: "UX-006",
    legacySet: "M1 low-fi",
    legacyName: "Provider & Drug Optional Lookup",
    legacyRoute: "/m1/ux-006",
    disposition: "out-of-scope",
    surfaces: [],
    seams: [],
    note: "Module slice map, M01: no provider or drug lookup in Lucie unless separately approved.",
  },
  {
    legacyId: "UX-007",
    legacySet: "M1 low-fi",
    legacyName: "Optional Subsidy Check",
    legacyRoute: "/m1/ux-007",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_SUBSIDY_FPL_TOOLS"],
    seams: [],
    note: "FPL and subsidy tools are required production for IFP on-exchange (LUC-DEC-005).",
  },
  {
    legacyId: "UX-008",
    legacySet: "M1 low-fi",
    legacyName: "Subsidy Estimate & Education",
    legacyRoute: "/m1/ux-008",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_SUBSIDY_FPL_TOOLS"],
    seams: [],
    note: "Calculation version, inputs and disclaimers must be auditable.",
  },
  {
    legacyId: "UX-009",
    legacySet: "M1 low-fi",
    legacyName: "Plan Results",
    legacyRoute: "/m1/ux-009",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_QUOTE_RESULTS"],
    seams: [],
    note: "Results are pinned to an immutable quote snapshot; sellability affects progression, not the rate.",
  },
  {
    legacyId: "UX-010",
    legacySet: "M1 low-fi",
    legacyName: "Plan Detail Panel / Page",
    legacyRoute: "/m1/ux-010",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PLAN_DETAIL"],
    seams: [],
    note: "Benefit content comes from governed product data (M03), never page copy.",
  },
  {
    legacyId: "UX-011",
    legacySet: "M1 low-fi",
    legacyName: "Plan Comparison",
    legacyRoute: "/m1/ux-011",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PLAN_COMPARE"],
    seams: [],
    note: "PlanAI comparison summary carries evidence and the approved disclaimer.",
  },
  {
    legacyId: "UX-012",
    legacySet: "M1 low-fi",
    legacyName: "More Coverage / Ancillary Cards",
    legacyRoute: "/m1/ux-012",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_DV_QUOTE_INTAKE"],
    seams: ["LUC-SEAM-013"],
    note: "Dental and vision only. Cross-navigation does not instantiate an offer or bundle object (M17 excluded).",
  },
  {
    legacyId: "UX-013",
    legacySet: "M1 low-fi",
    legacyName: "Cart Drawer",
    legacyRoute: "/m1/ux-013",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_CART_REVIEW"],
    seams: [],
    note: "One product-agnostic cart spine (M02); no product-specific duplicate carts.",
  },
  {
    legacyId: "UX-014",
    legacySet: "M1 low-fi",
    legacyName: "Review & Enroll Gate",
    legacyRoute: "/m1/ux-014",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_APPLICATION_REVIEW", "LUC-SCR_EDE_HANDOFF_REVIEW"],
    seams: ["LUC-SEAM-006"],
    note: "Split by next path: fixed application review off-exchange, EDE handoff review on-exchange.",
  },
  {
    legacyId: "UX-015",
    legacySet: "M1 low-fi",
    legacyName: "Registration / Login Gate",
    legacyRoute: "/m1/ux-015",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_REGISTRATION"],
    seams: [],
    note: "Typed consent is captured here as a versioned record.",
  },
  {
    legacyId: "UX-016",
    legacySet: "M1 low-fi",
    legacyName: "Consumer Dashboard / Resume",
    legacyRoute: "/m1/ux-016",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_MEMBER_HOME", "LUC-SCR_MEMBER_SHOPPING"],
    seams: ["LUC-SEAM-011"],
    note: "Member workspace shows saved shopping and applications only; policy servicing (M18) is excluded.",
  },
  {
    legacyId: "UX-017",
    legacySet: "M1 low-fi",
    legacyName: "Agent Quick Quote Start",
    legacyRoute: "/m1/ux-017",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AGENT_QUICK_QUOTE"],
    seams: [],
    note: "Entry requires a permitted sellability decision for the selected product and state.",
  },
  {
    legacyId: "UX-018",
    legacySet: "M1 low-fi",
    legacyName: "Agent Quick Quote Workspace",
    legacyRoute: "/m1/ux-018",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AGENT_QUICK_QUOTE", "LUC-SCR_AGENT_QUOTE_DETAIL"],
    seams: [],
    note: "Quote detail is the governed record; the workspace is its working view.",
  },
  {
    legacyId: "UX-019",
    legacySet: "M1 low-fi",
    legacyName: "Agent Send Quote",
    legacyRoute: "/m1/ux-019",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AGENT_SHARED_QUOTES"],
    seams: [],
    note: "Delivery is consent-gated through Twilio/SendGrid with safe URL tokens.",
  },
  {
    legacyId: "UX-020",
    legacySet: "M1 low-fi",
    legacyName: "Shared Quote Read-Only View",
    legacyRoute: "/m1/ux-020",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_SHARED_QUOTE_VIEW", "LUC-SCR_SHARED_QUOTE_CONTINUE"],
    seams: [],
    note: "Public review versus authenticated continuation are separate surfaces in IA v2.0.",
  },
  {
    legacyId: "UX-021",
    legacySet: "M1 low-fi",
    legacyName: "Lead Timeline & Milestones",
    legacyRoute: "/m1/ux-021",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AGENT_LEAD_DETAIL", "LUC-SCR_AGENT_CUSTOMER_360"],
    seams: [],
    note: "Timeline is assembled from canonical events (M09), not page state.",
  },
  {
    legacyId: "UX-022",
    legacySet: "M1 low-fi",
    legacyName: "Schedule Time / Request Call",
    legacyRoute: "/m1/ux-022",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AGENT_TASKS"],
    seams: ["LUC-SEAM-009"],
    note: "Becomes a task plus canned notification. No calendar integration or dialer (M10 boundary, M16 excluded).",
  },
  {
    legacyId: "UX-023",
    legacySet: "M1 low-fi",
    legacyName: "JET / EDE Handoff Confirmation & Explanation",
    legacyRoute: "/m1/ux-023",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_EDE_HANDOFF_REVIEW", "LUC-SCR_SUBMISSION_STATUS"],
    seams: [],
    note: "Confirmation of handoff, never of enrollment (INV-03).",
  },
  {
    legacyId: "UX-024",
    legacySet: "M1 low-fi",
    legacyName: "Module 1 Config: Branding & Products",
    legacyRoute: "/m1/ux-024",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_STOREFRONT_EDITOR", "LUC-SCR_AGENCY_PRODUCT_ACCESS"],
    seams: [],
    note: "IA v2.0 separates storefront branding from product/offering access.",
  },
  {
    legacyId: "UX-025",
    legacySet: "M1 low-fi",
    legacyName: "Module 1 Config: Routing & Notifications",
    legacyRoute: "/m1/ux-025",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_COMMUNICATION_TEMPLATES", "LUC-SCR_CONSENT_POLICY"],
    seams: [],
    note: "Canned editable templates and fixed triggers only; no campaign studio.",
  },
  {
    legacyId: "UX-026",
    legacySet: "M1 low-fi",
    legacyName: "AI Review & Confirmation",
    legacyRoute: "/m1/ux-026",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PLANAI_CONFIG", "LUC-SCR_PLANO_GUIDED_INTAKE"],
    seams: [],
    note: "Evidence, disclaimers and deployment mode are governed configuration (M14/M15).",
  },

  // ----------------------------------------------------------- higher fidelity
  {
    legacyId: "HF-01",
    legacySet: "Higher fidelity",
    legacyName: "Internal platform shell",
    legacyRoute: "/hf/internal-shell",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PLATFORM_HOME", "LUC-SCR_WORKSPACE_CONFIG"],
    seams: [],
    note: "Shell structure is IA-owned; Lucie exposes six workspaces and six role templates.",
  },
  {
    legacyId: "HF-02",
    legacySet: "Higher fidelity",
    legacyName: "My Work",
    legacyRoute: "/hf/my-work",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AGENT_MY_WORK", "LUC-SCR_AGENCY_MY_WORK"],
    seams: [],
    note: "One pattern, two workspace instances with different scope.",
  },
  {
    legacyId: "HF-03",
    legacySet: "Higher fidelity",
    legacyName: "Dashboards & analytics",
    legacyRoute: "/hf/dashboard",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AGENT_REPORTS", "LUC-SCR_REPORT_CATALOG", "LUC-SCR_ANALYTICS_DATASETS"],
    seams: ["LUC-SEAM-014"],
    note: "Operational reporting only; no open-ended BI authoring (M24 boundary).",
  },
  {
    legacyId: "HF-04",
    legacySet: "Higher fidelity",
    legacyName: "Branded consumer marketplace landing",
    legacyRoute: "/hf/marketplace-landing",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_CONS_LANDING"],
    seams: [],
    note: "Limited white labeling: tokens, logo, disclosures within platform-owned layout.",
  },
  {
    legacyId: "HF-05",
    legacySet: "Higher fidelity",
    legacyName: "Product selection",
    legacyRoute: "/hf/product-selection",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PRODUCT_SELECT"],
    seams: [],
    note: "Visibility resolves from marketplace and agency product access.",
  },
  {
    legacyId: "HF-06",
    legacySet: "Higher fidelity",
    legacyName: "D2C quote wizard",
    legacyRoute: "/hf/quote-wizard",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_ELIGIBILITY_INTAKE"],
    seams: [],
    note: "Save and resume operates on the journey record, not browser state.",
  },
  {
    legacyId: "HF-07",
    legacySet: "Higher fidelity",
    legacyName: "Plan AI guided shopping",
    legacyRoute: "/hf/plan-o",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PLANO_GUIDED_INTAKE"],
    seams: [],
    note: "Relabel to PlanAI. Text-only; no voice (M15 boundary).",
  },
  {
    legacyId: "HF-08",
    legacySet: "Higher fidelity",
    legacyName: "Plan results",
    legacyRoute: "/hf/plan-results",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_QUOTE_RESULTS"],
    seams: [],
    note: "Real Ideon data is a production gate (LUC-GATE-02).",
  },
  {
    legacyId: "HF-09",
    legacySet: "Higher fidelity",
    legacyName: "Compare plans",
    legacyRoute: "/hf/plan-compare",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PLAN_COMPARE"],
    seams: [],
    note: "Comparison set is a canonical M02 object.",
  },
  {
    legacyId: "HF-10",
    legacySet: "Higher fidelity",
    legacyName: "Cart",
    legacyRoute: "/hf/cart",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_CART_REVIEW"],
    seams: ["LUC-SEAM-006"],
    note: "Item readiness, version and warning states are separate from payment posture.",
  },
  {
    legacyId: "HF-11",
    legacySet: "Higher fidelity",
    legacyName: "Registration / login gate",
    legacyRoute: "/hf/registration-gate",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_REGISTRATION"],
    seams: [],
    note: "Account attachment binds the anonymous journey to an identity.",
  },
  {
    legacyId: "HF-12",
    legacySet: "Higher fidelity",
    legacyName: "On-exchange EDE handoff explanation",
    legacyRoute: "/hf/ede-handoff",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_EDE_HANDOFF_REVIEW"],
    seams: [],
    note: "Legal role and disclosure copy are gated inputs (LUC-OQ-008, LUC-GATE-04).",
  },
  {
    legacyId: "HF-13",
    legacySet: "Higher fidelity",
    legacyName: "Shared quote (read-only)",
    legacyRoute: "/hf/shared-quote",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_SHARED_QUOTE_VIEW"],
    seams: [],
    note: "Safe URL control applies exactly as in Module 1.",
  },
  {
    legacyId: "HF-14",
    legacySet: "Higher fidelity",
    legacyName: "Agent quick quote",
    legacyRoute: "/hf/agent-quick-quote",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AGENT_QUICK_QUOTE"],
    seams: [],
    note: "Agent-assisted and takeover channels share one journey object.",
  },
  {
    legacyId: "HF-15",
    legacySet: "Higher fidelity",
    legacyName: "Lead detail with timeline",
    legacyRoute: "/hf/lead-detail",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AGENT_LEAD_DETAIL"],
    seams: [],
    note: "Fixed statuses and rules-based routing; no advanced CRM automation.",
  },
  {
    legacyId: "HF-16",
    legacySet: "Higher fidelity",
    legacyName: "Off-exchange enrollment intake",
    legacyRoute: "/hf/offex-intake",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_OFFEX_ENROLL_START"],
    seams: [],
    note: "Adapted safety surface: pathway mode is resolved before intake begins.",
  },
  {
    legacyId: "HF-17",
    legacySet: "Higher fidelity",
    legacyName: "Dynamic application form",
    legacyRoute: "/hf/dynamic-form",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_DYNAMIC_FORM", "LUC-SCR_FORM_TEMPLATE_LIBRARY"],
    seams: ["LUC-SEAM-005"],
    note: "Renamed to fixed application form runtime. Versioned fixed forms, no conditional authoring (LUC-DEC-008).",
  },
  {
    legacyId: "HF-18",
    legacySet: "Higher fidelity",
    legacyName: "Form configurator",
    legacyRoute: "/hf/form-configurator",
    disposition: "excluded",
    surfaces: ["LUC-SCR_FORM_TEMPLATE_LIBRARY"],
    seams: ["LUC-SEAM-005"],
    note: "Dynamic form authoring is excluded. Lucie administers a fixed form library; the configurator stays a protected seam.",
  },
  {
    legacyId: "HF-19",
    legacySet: "Higher fidelity",
    legacyName: "Product catalog",
    legacyRoute: "/hf/product-catalog",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PRODUCT_CATALOG", "LUC-SCR_PRODUCT_DETAIL"],
    seams: [],
    note: "Catalog is read-mostly: Ideon-loaded IFP plus canned dental/vision versions.",
  },
  {
    legacyId: "HF-20",
    legacySet: "Higher fidelity",
    legacyName: "Product builder",
    legacyRoute: "/hf/product-builder",
    disposition: "excluded",
    surfaces: ["LUC-SCR_PRODUCT_EDITOR", "LUC-SCR_PLAN_EDITOR", "LUC-SCR_CANNED_PLAN_LIBRARY"],
    seams: ["LUC-SEAM-004"],
    note: "No free-form product builder or formula studio. Fixed product/plan record administration only.",
  },
  {
    legacyId: "HF-21",
    legacySet: "Higher fidelity",
    legacyName: "Carrier appointment setup",
    legacyRoute: "/hf/appointment-setup",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_APPOINTMENTS", "LUC-SCR_CREDENTIAL_EXCEPTIONS"],
    seams: [],
    note: "NIPR verification behavior is a gated integration input (LUC-OQ-009).",
  },
  {
    legacyId: "HF-22",
    legacySet: "Higher fidelity",
    legacyName: "Paper access & revenue split configuration",
    legacyRoute: "/hf/paper-splits",
    disposition: "excluded",
    surfaces: [],
    seams: ["LUC-SEAM-003", "LUC-SEAM-007"],
    note: "M07 contract sharing and M12 revenue sharing are excluded. Attribution fields and module boundary are retained; no UI.",
  },
  {
    legacyId: "HF-23",
    legacySet: "Higher fidelity",
    legacyName: "Referral reward setup",
    legacyRoute: "/hf/referral-rewards",
    disposition: "excluded",
    surfaces: [],
    seams: ["LUC-SEAM-007", "LUC-SEAM-013"],
    note: "Rewards and incentive placements sit in excluded M12/M17 territory.",
  },
  {
    legacyId: "HF-24",
    legacySet: "Higher fidelity",
    legacyName: "Commission schedule setup",
    legacyRoute: "/hf/commission-schedule",
    disposition: "excluded",
    surfaces: [],
    seams: ["LUC-SEAM-007"],
    note: "No commission schedules, inheritance, splits or overrides in Lucie.",
  },
  {
    legacyId: "HF-25",
    legacySet: "Higher fidelity",
    legacyName: "Commission projection",
    legacyRoute: "/hf/commission-projection",
    disposition: "excluded",
    surfaces: [],
    seams: ["LUC-SEAM-007"],
    note: "No projections or projection statements.",
  },
  {
    legacyId: "HF-26",
    legacySet: "Higher fidelity",
    legacyName: "Agency statement",
    legacyRoute: "/hf/agency-statement",
    disposition: "excluded",
    surfaces: [],
    seams: ["LUC-SEAM-007"],
    note: "No statements or reconciliation. Agency financial truth is out of the four-month boundary.",
  },
  {
    legacyId: "HF-27",
    legacySet: "Higher fidelity",
    legacyName: "Agent statement",
    legacyRoute: "/hf/agent-statement",
    disposition: "excluded",
    surfaces: [],
    seams: ["LUC-SEAM-007"],
    note: "No producer payouts or statements.",
  },
  {
    legacyId: "HF-28",
    legacySet: "Higher fidelity",
    legacyName: "Notification scheduler",
    legacyRoute: "/hf/notification-scheduler",
    disposition: "reconciled",
    surfaces: [
      "LUC-SCR_COMMUNICATION_TEMPLATES",
      "LUC-SCR_CONSENT_POLICY",
      "LUC-SCR_TWILIO_CONFIG",
    ],
    seams: ["LUC-SEAM-009"],
    note: "Fixed workflow triggers and canned editable templates; unrestricted workflow authoring is excluded.",
  },
  {
    legacyId: "HF-29",
    legacySet: "Higher fidelity",
    legacyName: "Branding & white labeling settings",
    legacyRoute: "/hf/branding-settings",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_STOREFRONT_EDITOR", "LUC-SCR_STOREFRONT_PREVIEW"],
    seams: [],
    note: "Limited white labeling only; brand assets and defaults are a design dependency (LUC-OQ-015).",
  },
  {
    legacyId: "HF-30",
    legacySet: "Higher fidelity",
    legacyName: "ACL configuration",
    legacyRoute: "/hf/acl-config",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_ROLE_TEMPLATES", "LUC-SCR_AGENCY_ROLES"],
    seams: [],
    note: "Six role templates in Lucie; ACL decisions are enforced server-side per IA v2.0 ACL rules.",
  },
  {
    legacyId: "HF-31",
    legacySet: "Higher fidelity",
    legacyName: "Audit log",
    legacyRoute: "/hf/audit-log",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_AUDIT_EXPLORER"],
    seams: [],
    note: "Audit and evidence explorer is a protected Module 1 control surface.",
  },
];

/** Group-level disposition for the 70-screen broader Phase 1 low-fi set. */
export interface P1GroupDisposition {
  group: string;
  disposition: Disposition;
  surfaces: string[];
  seams: string[];
  note: string;
}

export const P1_GROUP_DISPOSITIONS: P1GroupDisposition[] = [
  {
    group: "Off-exchange enrollment",
    disposition: "reconciled",
    surfaces: [
      "LUC-SCR_OFFEX_ENROLL_START",
      "LUC-SCR_DYNAMIC_FORM",
      "LUC-SCR_APPLICATION_REVIEW",
      "LUC-SCR_ESIGN",
      "LUC-SCR_SUBMISSION_STATUS",
    ],
    seams: ["LUC-SEAM-005"],
    note: "Retained as Lucie WS-04, but with fixed forms and three pathway modes rather than open enrollment configuration.",
  },
  {
    group: "Form configurator",
    disposition: "excluded",
    surfaces: ["LUC-SCR_FORM_TEMPLATE_LIBRARY", "LUC-SCR_PATHWAY_BUILDER"],
    seams: ["LUC-SEAM-005"],
    note: "Replaced by a fixed form library and fixed pathway definition administration.",
  },
  {
    group: "Products, plans & rates",
    disposition: "reconciled",
    surfaces: [
      "LUC-SCR_PRODUCT_CATALOG",
      "LUC-SCR_PRODUCT_EDITOR",
      "LUC-SCR_PLAN_EDITOR",
      "LUC-SCR_IDEON_LOADER",
      "LUC-SCR_VALIDATION_QUEUE",
    ],
    seams: ["LUC-SEAM-004"],
    note: "Fixed Ideon mapping plus canned dental/vision versions; no formula studio or carrier self-service.",
  },
  {
    group: "Agency & agent management",
    disposition: "reconciled",
    surfaces: [
      "LUC-SCR_AGENCY_HOME",
      "LUC-SCR_AGENT_ROSTER",
      "LUC-SCR_AGENT_ONBOARDING",
      "LUC-SCR_ORGANIZATION_PROFILE",
      "LUC-SCR_AGENCY_ROLES",
    ],
    seams: ["LUC-SEAM-001", "LUC-SEAM-002"],
    note: "One-parent/downline view and one primary active affiliation; canonical relationship boundary retained.",
  },
  {
    group: "Appointments, paper, referrals & splits",
    disposition: "excluded",
    surfaces: ["LUC-SCR_APPOINTMENTS", "LUC-SCR_LICENSES", "LUC-SCR_CAPTIVE_CONSTRAINTS"],
    seams: ["LUC-SEAM-003", "LUC-SEAM-007"],
    note: "Appointments and licensing are in scope; paper sharing, referrals and splits are excluded seams with no UI.",
  },
  {
    group: "Commissions & revenue",
    disposition: "excluded",
    surfaces: [],
    seams: ["LUC-SEAM-007"],
    note: "Entirely excluded from Lucie. Attribution fields only.",
  },
  {
    group: "Notifications, comms & scheduling",
    disposition: "reconciled",
    surfaces: [
      "LUC-SCR_COMMUNICATION_TEMPLATES",
      "LUC-SCR_CONSENT_POLICY",
      "LUC-SCR_TWILIO_CONFIG",
      "LUC-SCR_AGENT_NOTIFICATIONS",
    ],
    seams: ["LUC-SEAM-009"],
    note: "Twilio/SendGrid, canned templates, fixed triggers, notification center and help drawer.",
  },
  {
    group: "Outputs, documents & reporting",
    disposition: "reconciled",
    surfaces: [
      "LUC-SCR_OUTPUT_TEMPLATE_LIBRARY",
      "LUC-SCR_DOCUMENT_TEMPLATE",
      "LUC-SCR_REPORT_CATALOG",
      "LUC-SCR_ANALYTICS_DATASETS",
    ],
    seams: ["LUC-SEAM-014"],
    note: "Controlled outputs and operational reporting; no output studio or BI authoring.",
  },
  {
    group: "AI, Plan-AI & governance",
    disposition: "reconciled",
    surfaces: ["LUC-SCR_PLANAI_CONFIG", "LUC-SCR_PLANO_GUIDED_INTAKE"],
    seams: [],
    note: "Relabel Plan-AI to PlanAI. Single text-only profile; no autonomous business agents.",
  },
  {
    group: "Admin, configuration, integrations & audit",
    disposition: "reconciled",
    surfaces: [
      "LUC-SCR_TENANTS",
      "LUC-SCR_WORKSPACE_CONFIG",
      "LUC-SCR_FEATURE_FLAGS",
      "LUC-SCR_AUDIT_EXPLORER",
      "LUC-SCR_WEBHOOK_MONITOR",
      "LUC-SCR_SUPPORT_ACCESS",
    ],
    seams: [],
    note: "Simplified administration is permitted; production-grade controls are not optional.",
  },
];
