/** Lucie IA surface baseline (111), keyed to Phase 1 IA v2.0 screen IDs. */
export interface LucieSurface {
  lucieSurfaceId: string;
  upstreamIaScreenId: string;
  surfaceName: string;
  workspaceId: string;
  canonicalModules: string;
  luciePosture: string;
  purpose: string;
  routePattern: string;
  lucieAdaptation: string;
  wireframeRequired: string;
  upstreamStableIdStatus: string;
}

export const SURFACES: LucieSurface[] = [
  {
    "lucieSurfaceId": "LUC-SCR_APPLICATION_REVIEW",
    "upstreamIaScreenId": "SCR_APPLICATION_REVIEW",
    "surfaceName": "Application Review and Attestation",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M26",
    "luciePosture": "Adapted safety surface",
    "purpose": "Review answers, documents, signatures, payment and readiness before submission.",
    "routePattern": "/consumer-marketplace/application-review",
    "lucieAdaptation": "Review answers, signatures and pathway readiness. Payment simulation is nonproduction only; production may show external or pending status.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_CART_REVIEW",
    "upstreamIaScreenId": "SCR_CART_REVIEW",
    "surfaceName": "Cart and Readiness Review",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M02,M26,M11",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Review mixed-product cart, item readiness, versions, warnings and independent next paths.",
    "routePattern": "/consumer-marketplace/cart-review",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_CONS_LANDING",
    "upstreamIaScreenId": "SCR_CONS_LANDING",
    "surfaceName": "Consumer Marketplace Landing",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M04,M01",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Branded marketplace entry with products, help, attribution and disclosure context.",
    "routePattern": "/consumer-marketplace/cons-landing",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_DOC_UPLOAD",
    "upstreamIaScreenId": "SCR_DOC_UPLOAD",
    "surfaceName": "Application Document Upload",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M26,M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Collect, classify, replace and verify required supporting documents.",
    "routePattern": "/consumer-marketplace/doc-upload",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_DV_QUOTE_INTAKE",
    "upstreamIaScreenId": "",
    "surfaceName": "Dental and Vision Quote Intake",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M02,M21",
    "luciePosture": "Required production",
    "purpose": "Collect fixed product-specific rating inputs for dental and vision quotes.",
    "routePattern": "/consumer-marketplace/dental-vision-quote",
    "lucieAdaptation": "Uses canned product schemas and rating rules.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New Lucie surface; M02/M21 ownership retained."
  },
  {
    "lucieSurfaceId": "LUC-SCR_DYNAMIC_FORM",
    "upstreamIaScreenId": "SCR_DYNAMIC_FORM",
    "surfaceName": "Fixed Application Form Runtime",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M26",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Render the approved fixed application version and its preconfigured logic.",
    "routePattern": "/consumer-marketplace/dynamic-form",
    "lucieAdaptation": "No dynamic form authoring; only approved fixed forms and editable disclaimers.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_EDE_HANDOFF_REVIEW",
    "upstreamIaScreenId": "SCR_EDE_HANDOFF_REVIEW",
    "surfaceName": "JET EDE Handoff Review",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M01,M02,M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Confirm on-exchange selection, required acknowledgements, refreshed quote and opaque-token handoff.",
    "routePattern": "/consumer-marketplace/ede-handoff-review",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ELIGIBILITY_INTAKE",
    "upstreamIaScreenId": "SCR_ELIGIBILITY_INTAKE",
    "surfaceName": "Basic Eligibility and Quote Intake",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M02,M01",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Capture geography, effective date, household and product-specific minimum quote inputs.",
    "routePattern": "/consumer-marketplace/eligibility-intake",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ESIGN",
    "upstreamIaScreenId": "SCR_ESIGN",
    "surfaceName": "Electronic Signature",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M26,M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Execute the JET E-Signature flow and retain signer, document and completion evidence.",
    "routePattern": "/consumer-marketplace/esign",
    "lucieAdaptation": "JET E-Signature only; DocuSign is outside Lucie.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_OFFEX_ENROLL_START",
    "upstreamIaScreenId": "SCR_OFFEX_ENROLL_START",
    "surfaceName": "Off-Exchange Enrollment Start",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M26,M03",
    "luciePosture": "Adapted safety surface",
    "purpose": "Confirm configured off-exchange pathway, required parties, documents, signature and payment expectations.",
    "routePattern": "/consumer-marketplace/offex-enroll-start",
    "lucieAdaptation": "Nonproduction simulation only; production shows external/pending/completed-externally status without collecting real credentials.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PAYMENT_CAPTURE",
    "upstreamIaScreenId": "SCR_PAYMENT_CAPTURE",
    "surfaceName": "Payment Simulation and External Status",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M11,M26",
    "luciePosture": "Adapted safety surface",
    "purpose": "Run synthetic payment scenarios outside production and record external payment posture in production.",
    "routePattern": "/consumer-marketplace/payment-capture",
    "lucieAdaptation": "No real card or ACH credentials, no authorization, no funds movement, and no paid state without provider evidence.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PLANO_GUIDED_INTAKE",
    "upstreamIaScreenId": "SCR_PLANO_GUIDED_INTAKE",
    "surfaceName": "PlanAI Guided Intake",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M15,M14,M02",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Collect goals, expected usage and product-specific preference context for text-only PlanAI guidance.",
    "routePattern": "/consumer-marketplace/plano-guided-intake",
    "lucieAdaptation": "Text-only PlanAI; no provider or medication collection, voice, or autonomous transaction action.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 ID; display label renamed from Plan AI to PlanAI"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PLAN_COMPARE",
    "upstreamIaScreenId": "SCR_PLAN_COMPARE",
    "surfaceName": "Plan Comparison",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M02,M15",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Compare selected plans with product-configurable attributes, tradeoffs and PlanAI summary.",
    "routePattern": "/consumer-marketplace/plan-compare",
    "lucieAdaptation": "Text-only PlanAI with approved knowledge, evidence, disclaimers and no autonomous transaction actions.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PLAN_DETAIL",
    "upstreamIaScreenId": "SCR_PLAN_DETAIL",
    "surfaceName": "Plan and Offering Detail",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M02,M03,M15",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Present plan benefits, rates, network, documents, warnings, provenance and next actions.",
    "routePattern": "/consumer-marketplace/plan-detail",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PRODUCT_SELECT",
    "upstreamIaScreenId": "SCR_PRODUCT_SELECT",
    "surfaceName": "Product and Path Selection",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M04,M03,M21,M20",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Select an available product line and enter the configured quote, handoff or employer path.",
    "routePattern": "/consumer-marketplace/product-select",
    "lucieAdaptation": "Limit to employer account, census, contribution strategy, quote, proposal and routed interest; no enrollment administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_QUOTE_RESULTS",
    "upstreamIaScreenId": "SCR_QUOTE_RESULTS",
    "surfaceName": "Quote Results",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M02,M03,M08,M15",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Show quote results with certainty, provenance, availability, sellability, filtering and explanation.",
    "routePattern": "/consumer-marketplace/quote-results",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_REGISTRATION",
    "upstreamIaScreenId": "SCR_REGISTRATION",
    "surfaceName": "Registration and Login",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M00,M09",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Create or authenticate a consumer account while attaching anonymous journey, lead and cart state.",
    "routePattern": "/consumer-marketplace/registration",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_SHARED_QUOTE_CONTINUE",
    "upstreamIaScreenId": "SCR_SHARED_QUOTE_CONTINUE",
    "surfaceName": "Authenticated Shared Quote Continuation",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M02,M09",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Revalidate and adopt selected quote items into the consumer journey after authentication.",
    "routePattern": "/consumer-marketplace/shared-quote-continue",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_SHARED_QUOTE_VIEW",
    "upstreamIaScreenId": "SCR_SHARED_QUOTE_VIEW",
    "surfaceName": "Shared Quote Public Review",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M02,M10",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Read-only tokenized quote review with interest, help and schedule actions and no direct cart mutation.",
    "routePattern": "/consumer-marketplace/shared-quote-view",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_SUBMISSION_STATUS",
    "upstreamIaScreenId": "SCR_SUBMISSION_STATUS",
    "surfaceName": "Application and Submission Status",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M26",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Display submission attempts, acknowledgements, failures, returned outcomes and next actions.",
    "routePattern": "/consumer-marketplace/submission-status",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_SUBSIDY_FPL_TOOLS",
    "upstreamIaScreenId": "",
    "surfaceName": "FPL and Subsidy Calculator Tools",
    "workspaceId": "WS_CONSUMER_MARKETPLACE",
    "canonicalModules": "M01,M02",
    "luciePosture": "Required production",
    "purpose": "Provide standalone and in-journey FPL, APTC and CSR estimate tools with disclosures and saved context.",
    "routePattern": "/consumer-marketplace/subsidy-tools",
    "lucieAdaptation": "Estimate only; Exchange or EDE makes the official determination.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New Lucie surface; submit upstream IA delta if retained later."
  },
  {
    "lucieSurfaceId": "LUC-SCR_MEMBER_APPLICATION_DETAIL",
    "upstreamIaScreenId": "SCR_MEMBER_APPLICATION_DETAIL",
    "surfaceName": "Application Detail",
    "workspaceId": "WS_MEMBER",
    "canonicalModules": "M26,M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Application answers, version, documents, signatures, submission and history.",
    "routePattern": "/member/member-application-detail",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_MEMBER_HOME",
    "upstreamIaScreenId": "SCR_MEMBER_HOME",
    "surfaceName": "Member Home",
    "workspaceId": "WS_MEMBER",
    "canonicalModules": "M09,M18,M10",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Saved shopping, carts, applications, messages and next actions for the registered consumer.",
    "routePattern": "/member/member-home",
    "lucieAdaptation": "No policy or member-servicing experience in Lucie.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "Retained v1 stable ID"
  },
  {
    "lucieSurfaceId": "LUC-SCR_MEMBER_MESSAGES",
    "upstreamIaScreenId": "SCR_MEMBER_MESSAGES",
    "surfaceName": "Messages and Notifications",
    "workspaceId": "WS_MEMBER",
    "canonicalModules": "M10",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Unified consumer-visible communication threads, system notifications and delivery context.",
    "routePattern": "/member/member-messages",
    "lucieAdaptation": "Use Twilio/SendGrid plus native in-app; canned templates and fixed workflow triggers.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_MEMBER_PREFERENCES",
    "upstreamIaScreenId": "SCR_MEMBER_PREFERENCES",
    "surfaceName": "Member Preferences",
    "workspaceId": "WS_MEMBER",
    "canonicalModules": "M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Language, accessibility, notification and permitted landing preferences.",
    "routePattern": "/member/member-preferences",
    "lucieAdaptation": "Use Twilio/SendGrid plus native in-app; canned templates and fixed workflow triggers.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_MEMBER_SHOPPING",
    "upstreamIaScreenId": "SCR_MEMBER_SHOPPING",
    "surfaceName": "Saved Shopping and Carts",
    "workspaceId": "WS_MEMBER",
    "canonicalModules": "M02",
    "luciePosture": "Inherited or simplified production",
    "purpose": "List saved journeys, quote sessions, comparisons and carts with freshness status.",
    "routePattern": "/member/member-shopping",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_AFFILIATIONS",
    "upstreamIaScreenId": "SCR_AGENT_AFFILIATIONS",
    "surfaceName": "My Affiliations",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M06,M05",
    "luciePosture": "Inherited or simplified production",
    "purpose": "View the agent’s one active Lucie agency affiliation and historical context.",
    "routePattern": "/agent/agent-affiliations",
    "lucieAdaptation": "Concurrent active affiliations remain a protected future seam.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_APPLICATIONS",
    "upstreamIaScreenId": "SCR_AGENT_APPLICATIONS",
    "surfaceName": "Applications Queue",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M26",
    "luciePosture": "Adapted safety surface",
    "purpose": "In-progress, review-required, signature, payment and submission application work.",
    "routePattern": "/agent/agent-applications",
    "lucieAdaptation": "Nonproduction simulation only; production shows external/pending/completed-externally status without collecting real credentials.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_APPLICATION_DETAIL",
    "upstreamIaScreenId": "SCR_AGENT_APPLICATION_DETAIL",
    "surfaceName": "Agent Application Detail",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M26",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Application provenance, consumer confirmations, documents, signatures, readiness and submission.",
    "routePattern": "/agent/agent-application-detail",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_CREDENTIALS",
    "upstreamIaScreenId": "SCR_AGENT_CREDENTIALS",
    "surfaceName": "My Licenses and Credentials",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Producer licenses, lines, appointments, E&O, training and documents.",
    "routePattern": "/agent/agent-credentials",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_CUSTOMER_360",
    "upstreamIaScreenId": "SCR_AGENT_CUSTOMER_360",
    "surfaceName": "Customer 360",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M09",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Household or employer account, product opportunities, quotes, carts, applications, tasks, communications and documents.",
    "routePattern": "/agent/agent-customer-360",
    "lucieAdaptation": "No policy servicing or full case management.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_HOME",
    "upstreamIaScreenId": "SCR_AGENT_HOME",
    "surfaceName": "Agent Home",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M06,M09",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Daily selling readiness, work queues, appointments, pipeline and next actions.",
    "routePattern": "/agent/agent-home",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_JOURNEYS",
    "upstreamIaScreenId": "SCR_AGENT_JOURNEYS",
    "surfaceName": "Shopping Journeys",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M02",
    "luciePosture": "Inherited or simplified production",
    "purpose": "View consumer and agent-created shopping journeys and resume context.",
    "routePattern": "/agent/agent-journeys",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_LEADS",
    "upstreamIaScreenId": "SCR_AGENT_LEADS",
    "surfaceName": "Leads and Opportunities",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M09",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Search and manage leads and product opportunities.",
    "routePattern": "/agent/agent-leads",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_LEAD_DETAIL",
    "upstreamIaScreenId": "SCR_AGENT_LEAD_DETAIL",
    "surfaceName": "Lead Detail",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M09",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Lead profile, product pursuits, source, consent eligibility, timeline and next actions.",
    "routePattern": "/agent/agent-lead-detail",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_MY_WORK",
    "upstreamIaScreenId": "SCR_AGENT_MY_WORK",
    "surfaceName": "Agent My Work",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M00,M09,M10,M18",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Assigned leads, applications, tasks, messages and operational exceptions.",
    "routePattern": "/agent/agent-my-work",
    "lucieAdaptation": "No policy servicing or service-case queues.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_NOTIFICATIONS",
    "upstreamIaScreenId": "SCR_AGENT_NOTIFICATIONS",
    "surfaceName": "Agent Notifications",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M10",
    "luciePosture": "Inherited or simplified production",
    "purpose": "System alerts, delivery failures, assignments and expiring credential notices.",
    "routePattern": "/agent/agent-notifications",
    "lucieAdaptation": "Use Twilio/SendGrid plus native in-app; canned templates and fixed workflow triggers.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_OUTPUTS",
    "upstreamIaScreenId": "SCR_AGENT_OUTPUTS",
    "surfaceName": "Agent Output Center",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Generate and retrieve quote, comparison, application and coverage outputs.",
    "routePattern": "/agent/agent-outputs",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_PREFERENCES",
    "upstreamIaScreenId": "SCR_AGENT_PREFERENCES",
    "surfaceName": "Agent Preferences",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Manage landing, notification, availability and permitted display preferences.",
    "routePattern": "/agent/agent-preferences",
    "lucieAdaptation": "No external calendar integration in Lucie.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_PROFILE",
    "upstreamIaScreenId": "SCR_AGENT_PROFILE",
    "surfaceName": "Agent Profile",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M06",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Canonical profile, contacts, languages, availability, routing attributes and visibility.",
    "routePattern": "/agent/agent-profile",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_QUICK_QUOTE",
    "upstreamIaScreenId": "SCR_AGENT_QUICK_QUOTE",
    "surfaceName": "Agent Quick Quote",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M01,M02,M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Quote for a new prospect or existing customer with authority enforcement and prefill warnings.",
    "routePattern": "/agent/agent-quick-quote",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_QUOTE_DETAIL",
    "upstreamIaScreenId": "SCR_AGENT_QUOTE_DETAIL",
    "surfaceName": "Quote Detail",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M02",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Quote inputs, result snapshots, comparison, cart and version history.",
    "routePattern": "/agent/agent-quote-detail",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_READINESS",
    "upstreamIaScreenId": "SCR_AGENT_READINESS",
    "surfaceName": "Selling Readiness",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M08,M06",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Current licenses, appointments, certifications, contract paths, restrictions and remediation.",
    "routePattern": "/agent/agent-readiness",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_REPORTS",
    "upstreamIaScreenId": "SCR_AGENT_REPORTS",
    "surfaceName": "Agent Performance",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M24",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Personal funnel, activity, response, application and projected revenue metrics.",
    "routePattern": "/agent/agent-reports",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_SHARED_QUOTES",
    "upstreamIaScreenId": "SCR_AGENT_SHARED_QUOTES",
    "surfaceName": "Shared Quote Manager",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M02,M10",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Create, expire, revoke and review shared quote engagement.",
    "routePattern": "/agent/agent-shared-quotes",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_TASKS",
    "upstreamIaScreenId": "SCR_AGENT_TASKS",
    "surfaceName": "Tasks and Follow-Ups",
    "workspaceId": "WS_AGENT",
    "canonicalModules": "M00,M09",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Personal and assigned tasks with SLA, priority and escalation.",
    "routePattern": "/agent/agent-tasks",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_AGENT_DETAIL",
    "upstreamIaScreenId": "SCR_AGENCY_AGENT_DETAIL",
    "surfaceName": "Agency Agent Detail",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M06,M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Profile, affiliations, roles, captivity, readiness, work and history in organization context.",
    "routePattern": "/agency/agency-agent-detail",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_COMPLIANCE",
    "upstreamIaScreenId": "SCR_AGENCY_COMPLIANCE",
    "surfaceName": "Agency Compliance Readiness",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Coverage matrix for agency and producer licenses, appointments, credentials and exceptions.",
    "routePattern": "/agency/agency-compliance",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_HOME",
    "upstreamIaScreenId": "SCR_AGENCY_HOME",
    "surfaceName": "Agency and Network Home",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M05,M06,M09",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Operational health, onboarding, readiness, pipeline, exceptions, projected revenue and next actions.",
    "routePattern": "/agency/agency-home",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_LOCATIONS",
    "upstreamIaScreenId": "SCR_AGENCY_LOCATIONS",
    "surfaceName": "Locations and Service Areas",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M06",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Maintain addresses, service areas, business hours and basic routing availability.",
    "routePattern": "/agency/agency-locations",
    "lucieAdaptation": "No complex territory or capacity optimization.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_MARKETPLACES",
    "upstreamIaScreenId": "SCR_AGENCY_MARKETPLACES",
    "surfaceName": "Marketplaces",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M04",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Agency-owned and participating marketplaces, status, products, channels and performance.",
    "routePattern": "/agency/agency-marketplaces",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_MARKETPLACE_DETAIL",
    "upstreamIaScreenId": "SCR_AGENCY_MARKETPLACE_DETAIL",
    "surfaceName": "Marketplace Detail",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M04",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Brand, participants, products, routing, disclosure, attribution and connector context.",
    "routePattern": "/agency/agency-marketplace-detail",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_MY_WORK",
    "upstreamIaScreenId": "SCR_AGENCY_MY_WORK",
    "surfaceName": "Agency My Work",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M00,M06,M07,M08,M09,M18",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Agency-wide onboarding, credential, lead, application and exception queues.",
    "routePattern": "/agency/agency-my-work",
    "lucieAdaptation": "No contract-sharing or policy-service queues.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_OUTPUTS",
    "upstreamIaScreenId": "SCR_AGENCY_OUTPUTS",
    "surfaceName": "Agency Quote and Application Outputs",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Generate permitted quote, comparison and application outputs for agency records.",
    "routePattern": "/agency/agency-outputs",
    "lucieAdaptation": "Limited fixed outputs only.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_PRODUCT_ACCESS",
    "upstreamIaScreenId": "SCR_AGENCY_PRODUCT_ACCESS",
    "surfaceName": "Product and Offering Access",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M03,M04,M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "View available products, marketplace enablement, quoteability, sellability and pathway readiness.",
    "routePattern": "/agency/agency-product-access",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENCY_ROLES",
    "upstreamIaScreenId": "SCR_AGENCY_ROLES",
    "surfaceName": "Agency Roles and Permission Templates",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M00,M06",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Clone controlled role templates and assign organization-scoped permissions.",
    "routePattern": "/agency/agency-roles",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_ONBOARDING",
    "upstreamIaScreenId": "SCR_AGENT_ONBOARDING",
    "surfaceName": "Agent Onboarding",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M06,M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Invite, collect profile, affiliate, credential, contract and marketplace prerequisites.",
    "routePattern": "/agency/agent-onboarding",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AGENT_ROSTER",
    "upstreamIaScreenId": "SCR_AGENT_ROSTER",
    "surfaceName": "Agent and User Roster",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M06",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Search users, producers, affiliations, statuses, readiness and assignments.",
    "routePattern": "/agency/agent-roster",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_APPOINTMENTS",
    "upstreamIaScreenId": "SCR_APPOINTMENTS",
    "surfaceName": "Carrier Appointments",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Carrier appointment matrix and lifecycle by organization, producer, product and jurisdiction.",
    "routePattern": "/agency/appointments",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_CAPTIVE_CONSTRAINTS",
    "upstreamIaScreenId": "SCR_CAPTIVE_CONSTRAINTS",
    "surfaceName": "Captive and Exclusivity Constraints",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M06,M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Effective-dated agency, network, carrier, product, state, marketplace and channel restrictions.",
    "routePattern": "/agency/captive-constraints",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_COMMUNICATION_TEMPLATES",
    "upstreamIaScreenId": "SCR_COMMUNICATION_TEMPLATES",
    "surfaceName": "Communication Templates",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M10,M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Approved email, SMS, notification and schedule templates with inheritance and locked content.",
    "routePattern": "/agency/communication-templates",
    "lucieAdaptation": "Use Twilio/SendGrid plus native in-app; canned templates and fixed workflow triggers.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_CREDENTIAL_EXCEPTIONS",
    "upstreamIaScreenId": "SCR_CREDENTIAL_EXCEPTIONS",
    "surfaceName": "Credential and Authority Exceptions",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Missing, expiring, conflicting and failed selling-authority evidence.",
    "routePattern": "/agency/credential-exceptions",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_LICENSES",
    "upstreamIaScreenId": "SCR_LICENSES",
    "surfaceName": "Licenses and Lines of Authority",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Agency and producer license records, source, status, effective and expiration dates.",
    "routePattern": "/agency/licenses",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ORGANIZATION_PROFILE",
    "upstreamIaScreenId": "SCR_ORGANIZATION_PROFILE",
    "surfaceName": "Organization Profile",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M05,M06",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Legal and operating identity, contacts, locations, service areas, status and documents.",
    "routePattern": "/agency/organization-profile",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ROSTER_IMPORT",
    "upstreamIaScreenId": "SCR_ROSTER_IMPORT",
    "surfaceName": "Roster Import and Validation",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M06",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Bulk user, producer and affiliation import with validation and exception resolution.",
    "routePattern": "/agency/roster-import",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_STOREFRONT_EDITOR",
    "upstreamIaScreenId": "SCR_STOREFRONT_EDITOR",
    "surfaceName": "Storefront and Branding Editor",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M04",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Configure logo, colors, copy, contact, domain and approved content within locks.",
    "routePattern": "/agency/storefront-editor",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_STOREFRONT_PREVIEW",
    "upstreamIaScreenId": "SCR_STOREFRONT_PREVIEW",
    "surfaceName": "Storefront Preview",
    "workspaceId": "WS_AGENCY",
    "canonicalModules": "M04",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Preview branded marketplace by device, product, geography and effective date.",
    "routePattern": "/agency/storefront-preview",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_EMPLOYER_COMMUNICATIONS",
    "upstreamIaScreenId": "SCR_EMPLOYER_COMMUNICATIONS",
    "surfaceName": "Employer Communications",
    "workspaceId": "WS_EMPLOYER_GROUP",
    "canonicalModules": "M10",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Messages, appointments and proposal activity.",
    "routePattern": "/employer-group/employer-communications",
    "lucieAdaptation": "Limit to employer account, census, contribution strategy, quote, proposal and routed interest; no enrollment administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_EMPLOYER_PROFILE",
    "upstreamIaScreenId": "SCR_EMPLOYER_PROFILE",
    "surfaceName": "Employer Profile",
    "workspaceId": "WS_EMPLOYER_GROUP",
    "canonicalModules": "M09,M20",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Employer identity, contacts, locations, quote context and assigned agency.",
    "routePattern": "/employer-group/employer-profile",
    "lucieAdaptation": "Limit to employer account, census, contribution strategy, quote, proposal and routed interest; no enrollment administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ICHRA_CENSUS",
    "upstreamIaScreenId": "",
    "surfaceName": "ICHRA Group and Member Census",
    "workspaceId": "WS_EMPLOYER_GROUP",
    "canonicalModules": "M20",
    "luciePosture": "Required production",
    "purpose": "Enter or upload employer census members, household attributes and eligibility inputs needed for quoting.",
    "routePattern": "/employer-group/ichra-census",
    "lucieAdaptation": "Quote context only; no employee enrollment or ongoing administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New Lucie surface; M20 ownership retained."
  },
  {
    "lucieSurfaceId": "LUC-SCR_ICHRA_CONTRIBUTION",
    "upstreamIaScreenId": "",
    "surfaceName": "ICHRA Contribution Strategy",
    "workspaceId": "WS_EMPLOYER_GROUP",
    "canonicalModules": "M20",
    "luciePosture": "Required production",
    "purpose": "Model fixed contribution strategies and evaluate employer and member affordability scenarios.",
    "routePattern": "/employer-group/ichra-contribution",
    "lucieAdaptation": "No reimbursement administration or ongoing contribution operations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New Lucie surface; M20 ownership retained."
  },
  {
    "lucieSurfaceId": "LUC-SCR_ICHRA_ENTRY",
    "upstreamIaScreenId": "SCR_ICHRA_ENTRY",
    "surfaceName": "ICHRA Employer Entry",
    "workspaceId": "WS_EMPLOYER_GROUP",
    "canonicalModules": "M20,M04",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Branded employer entry, program explanation and quote start.",
    "routePattern": "/employer-group/ichra-entry",
    "lucieAdaptation": "Limit to employer account, census, contribution strategy, quote, proposal and routed interest; no enrollment administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ICHRA_PROPOSAL",
    "upstreamIaScreenId": "SCR_ICHRA_PROPOSAL",
    "surfaceName": "ICHRA Proposal",
    "workspaceId": "WS_EMPLOYER_GROUP",
    "canonicalModules": "M20,M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Branded employer quote proposal and assumptions.",
    "routePattern": "/employer-group/ichra-proposal",
    "lucieAdaptation": "Limit to employer account, census, contribution strategy, quote, proposal and routed interest; no enrollment administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ICHRA_QUOTE",
    "upstreamIaScreenId": "SCR_ICHRA_QUOTE",
    "surfaceName": "ICHRA Quote Setup",
    "workspaceId": "WS_EMPLOYER_GROUP",
    "canonicalModules": "M20,M02",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Employer contribution and census-based quote inputs.",
    "routePattern": "/employer-group/ichra-quote",
    "lucieAdaptation": "Limit to employer account, census, contribution strategy, quote, proposal and routed interest; no enrollment administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ICHRA_RESULTS",
    "upstreamIaScreenId": "SCR_ICHRA_RESULTS",
    "surfaceName": "ICHRA Quote and Comparison Results",
    "workspaceId": "WS_EMPLOYER_GROUP",
    "canonicalModules": "M20,M02",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Employer proposal comparison and explanation.",
    "routePattern": "/employer-group/ichra-results",
    "lucieAdaptation": "Limit to employer account, census, contribution strategy, quote, proposal and routed interest; no enrollment administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ICHRA_ROUTING",
    "upstreamIaScreenId": "SCR_ICHRA_ROUTING",
    "surfaceName": "ICHRA Agency Routing",
    "workspaceId": "WS_EMPLOYER_GROUP",
    "canonicalModules": "M20,M09,M08",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Route employer opportunity to eligible agency and agent.",
    "routePattern": "/employer-group/ichra-routing",
    "lucieAdaptation": "Limit to employer account, census, contribution strategy, quote, proposal and routed interest; no enrollment administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ANALYTICS_DATASETS",
    "upstreamIaScreenId": "SCR_ANALYTICS_DATASETS",
    "surfaceName": "Governed Analytics Datasets",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M24",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Curated datasets, dimensions, lineage, refresh and consumer access.",
    "routePattern": "/platform-admin/analytics-datasets",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_APPLICATION_EXCEPTION_QUEUE",
    "upstreamIaScreenId": "SCR_APPLICATION_EXCEPTION_QUEUE",
    "surfaceName": "Application and Submission Exceptions",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M26",
    "luciePosture": "Adapted safety surface",
    "purpose": "Review missing data, documents, signatures, payment, adapter and acknowledgement issues.",
    "routePattern": "/platform-admin/application-exception-queue",
    "lucieAdaptation": "Nonproduction simulation only; production shows external/pending/completed-externally status without collecting real credentials.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_AUDIT_EXPLORER",
    "upstreamIaScreenId": "SCR_AUDIT_EXPLORER",
    "surfaceName": "Audit and Evidence Explorer",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Immutable reconstruction across user, system, integration, AI and configuration actions.",
    "routePattern": "/platform-admin/audit-explorer",
    "lucieAdaptation": "Text-only PlanAI with approved knowledge, evidence, disclaimers and no autonomous transaction actions.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_BENEFIT_EDITOR",
    "upstreamIaScreenId": "SCR_BENEFIT_EDITOR",
    "surfaceName": "Canned Benefit Data Administration",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Maintain plan-type-specific benefit fields within approved canned schemas.",
    "routePattern": "/platform-admin/benefit-editor",
    "lucieAdaptation": "No configurable benefit model builder.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_CANNED_PLAN_LIBRARY",
    "upstreamIaScreenId": "",
    "surfaceName": "Dental and Vision Canned Plan Library",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03,M21",
    "luciePosture": "Required production administration",
    "purpose": "Maintain versioned canned dental and vision plans, rates, benefits, geography and effective dates.",
    "routePattern": "/platform-admin/canned-plan-library",
    "lucieAdaptation": "Only approved plan-type schemas are supported.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New Lucie surface; canonical M03/M21 ownership retained."
  },
  {
    "lucieSurfaceId": "LUC-SCR_CARRIER_PATHWAY_SETTINGS",
    "upstreamIaScreenId": "",
    "surfaceName": "Carrier Enrollment Pathway Settings",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03,M26",
    "luciePosture": "Required production administration",
    "purpose": "Set the supported pathway by carrier, product, state and effective period and manage editable disclaimers.",
    "routePattern": "/platform-admin/carrier-pathway-settings",
    "lucieAdaptation": "Exactly quote only, application plus PDF, application plus EDI, or JET EDE handoff.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New Lucie surface; upstream pathway boundary retained."
  },
  {
    "lucieSurfaceId": "LUC-SCR_COMMERCIAL_ENTITLEMENTS",
    "upstreamIaScreenId": "",
    "surfaceName": "Agency Commercial Activation and Entitlements",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00,M05,M06",
    "luciePosture": "Required production administration",
    "purpose": "Activate agencies, assign Lucie product lines, seats, features and usage visibility for contract-based monetization.",
    "routePattern": "/platform-admin/commercial-entitlements",
    "lucieAdaptation": "Manual contracts and invoicing; no subscription billing engine.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New Lucie surface; platform control ownership retained."
  },
  {
    "lucieSurfaceId": "LUC-SCR_CONSENT_POLICY",
    "upstreamIaScreenId": "SCR_CONSENT_POLICY",
    "surfaceName": "Consent and Contact Policy",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00,M10",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Configure typed consent, state rules, quiet hours, frequency caps and evidence requirements.",
    "routePattern": "/platform-admin/consent-policy",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_DOCUMENT_TEMPLATE",
    "upstreamIaScreenId": "SCR_DOCUMENT_TEMPLATE",
    "surfaceName": "Document and Output Template",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Create versioned branded output templates with locked content.",
    "routePattern": "/platform-admin/document-template",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_FEATURE_FLAGS",
    "upstreamIaScreenId": "SCR_FEATURE_FLAGS",
    "surfaceName": "Feature Flags and Rollout",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Environment, tenant, marketplace, workspace and cohort feature activation with approval.",
    "routePattern": "/platform-admin/feature-flags",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_FORM_TEMPLATE_LIBRARY",
    "upstreamIaScreenId": "SCR_FORM_TEMPLATE_LIBRARY",
    "surfaceName": "Fixed Application Form Library",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M26",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Manage approved fixed application assets by product, carrier, state and effective date.",
    "routePattern": "/platform-admin/form-template-library",
    "lucieAdaptation": "Upload/version/activate fixed forms only; no field or layout authoring.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_HELP_CONTENT",
    "upstreamIaScreenId": "SCR_HELP_CONTENT",
    "surfaceName": "Help, FAQ and Page Guidance",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Configure global and local contextual help, FAQs and workflow guidance.",
    "routePattern": "/platform-admin/help-content",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_IDEON_LOADER",
    "upstreamIaScreenId": "",
    "surfaceName": "Ideon Fixed Plan Loader",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03",
    "luciePosture": "Required production administration",
    "purpose": "Configure source files or API, map the fixed IFP schema, validate loads, view errors and publish approved versions.",
    "routePattern": "/platform-admin/ideon-loader",
    "lucieAdaptation": "Fixed mapping only; no general ingestion designer.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New Lucie surface; canonical M03 ownership retained."
  },
  {
    "lucieSurfaceId": "LUC-SCR_JET_ESIGN_CONFIG",
    "upstreamIaScreenId": "SCR_JET_ESIGN_CONFIG",
    "surfaceName": "JET E-Signature Configuration",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M13,M26",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Configure default signature evidence, templates and operational controls.",
    "routePattern": "/platform-admin/jet-esign-config",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_LAUNCH_GATES",
    "upstreamIaScreenId": "SCR_LAUNCH_GATES",
    "surfaceName": "Launch Gate Control Center",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Product, legal, security, data, operational and commercial gate evidence and approval.",
    "routePattern": "/platform-admin/launch-gates",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_MARKETPLACE_ADMIN",
    "upstreamIaScreenId": "SCR_MARKETPLACE_ADMIN",
    "surfaceName": "Marketplace Registry",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M04",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Administer marketplace owners, participants, branding, products, routes, disclosures and status.",
    "routePattern": "/platform-admin/marketplace-admin",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_OUTPUT_TEMPLATE_LIBRARY",
    "upstreamIaScreenId": "SCR_OUTPUT_TEMPLATE_LIBRARY",
    "surfaceName": "Fixed Output Template Library",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M13",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Manage fixed quote, comparison and application PDF templates.",
    "routePattern": "/platform-admin/output-template-library",
    "lucieAdaptation": "No general Output Studio or agency free-form authoring.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PATHWAY_BINDINGS",
    "upstreamIaScreenId": "SCR_PATHWAY_BINDINGS",
    "surfaceName": "Carrier and Product Pathway Settings",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03,M26",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Assign the approved Lucie pathway to each carrier, product and plan version.",
    "routePattern": "/platform-admin/pathway-bindings",
    "lucieAdaptation": "Exactly quote only, application plus PDF, application plus EDI, or JET EDE handoff as applicable; no workflow designer.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PATHWAY_BUILDER",
    "upstreamIaScreenId": "SCR_PATHWAY_BUILDER",
    "surfaceName": "Fixed Pathway Definition Administration",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M26,M03",
    "luciePosture": "Adapted safety surface",
    "purpose": "Administer the fixed Lucie pathway definitions and status transitions.",
    "routePattern": "/platform-admin/pathway-builder",
    "lucieAdaptation": "No free-form pathway builder; JET manages a fixed controlled set.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PAYMENT_SIMULATION_LAB",
    "upstreamIaScreenId": "",
    "surfaceName": "Payment Simulation Test Lab",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M11",
    "luciePosture": "Nonproduction only",
    "purpose": "Test synthetic card and ACH success, failure, retry and cancellation scenarios.",
    "routePattern": "/platform-admin/payment-simulation",
    "lucieAdaptation": "Unavailable in production; real credentials cannot be entered or stored.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New Lucie test surface; M11 provider seam retained."
  },
  {
    "lucieSurfaceId": "LUC-SCR_PLANAI_CONFIG",
    "upstreamIaScreenId": "SCR_PLANAI_CONFIG",
    "surfaceName": "PlanAI Configuration",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M15,M14",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Configure approved deployment mode, knowledge, prompts, disclosures, escalation and guardrails.",
    "routePattern": "/platform-admin/planai-config",
    "lucieAdaptation": "Text-only PlanAI with approved knowledge, evidence, disclaimers and no autonomous transaction actions.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PLAN_EDITOR",
    "upstreamIaScreenId": "SCR_PLAN_EDITOR",
    "surfaceName": "Canned Plan Version Administration",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Maintain approved canned dental and vision plan fields, rates, benefits and effective versions.",
    "routePattern": "/platform-admin/plan-editor",
    "lucieAdaptation": "Use fixed plan-type schemas only.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PLATFORM_HOME",
    "upstreamIaScreenId": "SCR_PLATFORM_HOME",
    "surfaceName": "JET Platform Home",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00,M24",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Platform health, launch gates, critical exceptions, integrations, security and operating readiness.",
    "routePattern": "/platform-admin/platform-home",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PRODUCT_CATALOG",
    "upstreamIaScreenId": "SCR_PRODUCT_CATALOG",
    "surfaceName": "Product Catalog",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Search the fixed Lucie product lines, carriers, plan versions and publication status.",
    "routePattern": "/platform-admin/product-catalog",
    "lucieAdaptation": "No carrier self-service or unrestricted product creation.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PRODUCT_DETAIL",
    "upstreamIaScreenId": "SCR_PRODUCT_DETAIL",
    "surfaceName": "Product Detail",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03",
    "luciePosture": "Inherited or simplified production",
    "purpose": "View fixed product hierarchy, versions, source, plans, pathways and availability.",
    "routePattern": "/platform-admin/product-detail",
    "lucieAdaptation": "Read-mostly with controlled JET administration.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PRODUCT_EDITOR",
    "upstreamIaScreenId": "SCR_PRODUCT_EDITOR",
    "surfaceName": "Fixed Product Record Administration",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Maintain controlled product metadata and pathway bindings for the fixed Lucie product set.",
    "routePattern": "/platform-admin/product-editor",
    "lucieAdaptation": "No free-form product type creation or formula authoring.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_PRODUCT_PREVIEW",
    "upstreamIaScreenId": "SCR_PRODUCT_PREVIEW",
    "surfaceName": "Product and Marketplace Preview",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03,M04",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Preview by marketplace, geography, channel, agent context and effective date.",
    "routePattern": "/platform-admin/product-preview",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_REPORT_CATALOG",
    "upstreamIaScreenId": "SCR_REPORT_CATALOG",
    "surfaceName": "Report Catalog",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M24",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Approved operational reports, audiences, schedules and export permissions.",
    "routePattern": "/platform-admin/report-catalog",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_ROLE_TEMPLATES",
    "upstreamIaScreenId": "SCR_ROLE_TEMPLATES",
    "surfaceName": "Global Role Templates",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "JET-controlled role templates and non-overridable security limits.",
    "routePattern": "/platform-admin/role-templates",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_SUPPORT_ACCESS",
    "upstreamIaScreenId": "SCR_SUPPORT_ACCESS",
    "surfaceName": "Support and Impersonation Access",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Reason-coded, time-limited and audited support access.",
    "routePattern": "/platform-admin/support-access",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_TENANTS",
    "upstreamIaScreenId": "SCR_TENANTS",
    "surfaceName": "Tenant Registry",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00,M05",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Create, classify, activate, suspend and review tenant boundaries and legal posture.",
    "routePattern": "/platform-admin/tenants",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_TWILIO_CONFIG",
    "upstreamIaScreenId": "SCR_TWILIO_CONFIG",
    "surfaceName": "Twilio and SendGrid Configuration",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M10,M16",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Configure, test and activate Twilio SMS and SendGrid email sender settings and delivery webhooks.",
    "routePattern": "/platform-admin/twilio-config",
    "lucieAdaptation": "No voice, dialer or alternate provider in Lucie.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_VALIDATION_QUEUE",
    "upstreamIaScreenId": "SCR_VALIDATION_QUEUE",
    "surfaceName": "Product Validation Queue",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M03",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Resolve product, rate, benefit, source and publishing exceptions.",
    "routePattern": "/platform-admin/validation-queue",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_WEBHOOK_MONITOR",
    "upstreamIaScreenId": "SCR_WEBHOOK_MONITOR",
    "surfaceName": "Webhook and Callback Monitor",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Inspect validated webhook deliveries without exposing secrets or prohibited data.",
    "routePattern": "/platform-admin/webhook-monitor",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  },
  {
    "lucieSurfaceId": "LUC-SCR_WORKSPACE_CONFIG",
    "upstreamIaScreenId": "SCR_WORKSPACE_CONFIG",
    "surfaceName": "Workspace Configuration",
    "workspaceId": "WS_PLATFORM_ADMIN",
    "canonicalModules": "M00",
    "luciePosture": "Inherited or simplified production",
    "purpose": "Configure workspace availability, landing, menu, labels and permitted feature set.",
    "routePattern": "/platform-admin/workspace-config",
    "lucieAdaptation": "Use the Phase 1 IA surface with Lucie scope and fixed configurations.",
    "wireframeRequired": "Yes",
    "upstreamStableIdStatus": "New in v2.0"
  }
];
