/**
 * Phase 6 — future canonical component map.
 *
 * DOCUMENTATION ONLY.
 *
 * Read every row as two separate statements:
 *   `currentName` / `currentSource` / the measured fields  = CURRENT IMPLEMENTATION
 *   `canonical` / `normalization` / `migration` / `figma`  = FUTURE CANONICAL TARGET
 *
 * A canonical name is a PROPOSAL. No component has been renamed, aliased,
 * moved or created. Nothing in this file is imported by production code.
 *
 * Consumers: /design-system, /design-guide.
 */
import type { CanonicalComponentEntry } from "./types";

export const CANONICAL_COMPONENT_MAP: CanonicalComponentEntry[] = [
  /* ---------------- Actions ---------------- */
  {
    canonical: "Core / Actions / Button",
    currentName: "Button",
    currentSource: "src/components/ui/button.tsx",
    taxonomy: "action",
    tier: "ABox Core",
    classification: "primitive",
    consumers: "22 direct",
    usage: "Direct in 22 files; indirect through Dialog, Sheet, Drawer and route-local wrappers.",
    variants: "default, destructive, outline, secondary, ghost, link",
    sizes: "default h-9, sm h-8, lg h-10, icon, icon-sm",
    states: "default, hover, focus-visible, disabled; no loading state",
    anatomy: "root button → optional leading icon → label → optional trailing icon",
    responsive: "No internal breakpoints; the consumer decides stacking.",
    dependencies: "class-variance-authority, Radix Slot, foundation tokens",
    relationships: "Consumed by dialogs, sheets, forms and toolbars.",
    related: "ACTION_PILL, m06 Btn, m08 action helpers",
    duplication:
      "OBSERVED OVERLAP — three action paths coexist: Button, ACTION_PILL class strings and m06 Btn.",
    accessibility: "Owns focus-visible ring and disabled pointer-events; icon-only needs a label.",
    typography: "text-sm font-medium",
    spacing: "px-3 / px-4 by size, gap-2 between icon and label",
    iconography: "Base rule sizes any child SVG to 16px.",
    tokens: "--primary, --destructive, --secondary, --accent, --ring",
    normalization:
      "FUTURE CANONICAL TARGET — one action component with a pill appearance option, so ACTION_PILL and Button stop being separate paths. Not decided, not applied.",
    migration: "Would require touching 35 ACTION_PILL files; visual diffing mandatory.",
    figma: "Component with Variant, Size, Icon and State properties.",
    label: "FUTURE CANONICAL TARGET",
    phase: "Phase 5 — components, variants, states",
  },
  {
    canonical: "Core / Actions / ActionPill",
    currentName: "ACTION_PILL",
    currentSource: "src/components/abox/action-pill.ts",
    taxonomy: "action",
    tier: "ABox Core",
    classification: "pattern",
    consumers: "35 files, 82 references",
    usage: "Direct only. Applied to both <button> and <Link>, which is why it is not a component.",
    variants: "primary, outline",
    sizes: "xs h-8, sm h-9, smCard h-9, md h-10, lg h-11",
    states: "default, hover; focus depends on the element the class is applied to.",
    anatomy: "Class string only — no root element, no slots, no DOM contract.",
    responsive: "None.",
    dependencies: "Foundation tokens only.",
    relationships: "Applied by routes directly; not composed by any component.",
    related: "Button",
    duplication:
      "OBSERVED OVERLAP — overlaps Button in purpose while differing in shape (rounded-full) and height ramp.",
    accessibility:
      "FUTURE OPPORTUNITY — no focus-visible ring is included in the class strings; the underlying element supplies it.",
    typography: "text-xs / text-sm font-medium",
    spacing: "px-3 / px-4 / px-5 / px-6 by size; gap-1 to gap-1.5",
    iconography: "Consumers place lucide icons manually.",
    tokens: "--primary, --primary-foreground, --border, --accent, --card",
    normalization:
      "FUTURE CANONICAL TARGET — either fold into the action component or formalise as a documented appearance token set.",
    migration: "Low structural risk, high visual-diff surface.",
    figma: "Component with Variant and Size properties, or a Button appearance property.",
    label: "FUTURE DECISION",
    phase: "Phase 5 — components, variants, states",
  },
  {
    canonical: "Core / Actions / SaveContinueButton",
    currentName: "SaveContinueButton",
    currentSource: "src/components/abox/save-continue-button.tsx",
    taxonomy: "action",
    tier: "ABox Core",
    classification: "component",
    consumers: "3 direct",
    usage: "Direct, in downline wizard steps.",
    variants: "single appearance",
    sizes: "single",
    states: "idle, saving, saved — the only production component with a real loading state",
    anatomy: "root button → state label → optional state icon",
    responsive: "None.",
    dependencies: "Button or pill classes, lucide icons",
    relationships: "Used inside wizard step screens.",
    related: "Button, DownlineWizardStepper",
    duplication: "None found.",
    accessibility:
      "FUTURE OPPORTUNITY — the saving/saved transition is visual; no live-region announcement.",
    typography: "text-sm font-medium",
    spacing: "Inherits the action spacing ramp.",
    iconography: "Check icon on the saved state.",
    tokens: "--primary, --sage",
    normalization:
      "FUTURE CANONICAL TARGET — its state machine is the reference model for a general action loading state.",
    migration: "Extract the state model before generalising anything.",
    figma: "Component with a State property: idle / saving / saved.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },

  /* ---------------- Forms ---------------- */
  {
    canonical: "Core / Forms / TextField",
    currentName: "Input + Label (composed per screen)",
    currentSource: "src/components/ui/input.tsx, src/components/ui/label.tsx",
    taxonomy: "form-control",
    tier: "ABox Core",
    classification: "pattern",
    consumers: "Input 7 direct, Label 5 direct",
    usage: "Direct; every screen wires label, input, hint and error itself.",
    variants: "single appearance",
    sizes: "h-9 default",
    states: "default, focus, disabled, aria-invalid",
    anatomy: "label → control → optional hint → optional error message (assembled by the consumer)",
    responsive: "Consumer-driven.",
    dependencies: "Foundation tokens",
    relationships: "Composed ad hoc; the Form primitive is installed but unused.",
    related: "m06 Field/TextInput/TextArea, m08 field helpers, lucie-app Field",
    duplication:
      "OBSERVED DUPLICATE — at least four field systems exist: raw ui composition and three route-local kits.",
    accessibility:
      "CURRENT IMPLEMENTATION — aria-invalid is honoured; label association is left to the consumer.",
    typography: "text-sm control, text-xs error",
    spacing: "gap-2 between label and control",
    iconography: "Optional leading icon in some screens only.",
    tokens: "--input, --ring, --destructive, --muted-foreground",
    normalization:
      "FUTURE CANONICAL TARGET — one field component owning label, control, hint, error and required marker.",
    migration:
      "High risk: four systems, many screens, and form semantics. Requires its own migration phase.",
    figma: "Component with State and Required properties, plus hint and error slots.",
    label: "OBSERVED DUPLICATE",
    phase: "Phase 5 — components, variants, states",
  },
  {
    canonical: "Core / Forms / Select",
    currentName: "Select",
    currentSource: "src/components/ui/select.tsx",
    taxonomy: "form-control",
    tier: "ABox Core",
    classification: "primitive",
    consumers: "7 direct",
    usage: "Direct, including the plan results sort control.",
    variants: "single",
    sizes: "default; trigger heights vary by consumer",
    states: "closed, open, selected, disabled, keyboard navigation",
    anatomy: "trigger → value → chevron → content → items",
    responsive: "Radix handles positioning.",
    dependencies: "Radix Select",
    relationships: "Used in toolbars and forms.",
    related: "m06 Picker",
    duplication: "OBSERVED OVERLAP — m06 Picker is a separate select implementation.",
    accessibility: "Radix-owned keyboard and ARIA behaviour.",
    typography: "text-sm",
    spacing: "px-3, gap-2",
    iconography: "ChevronDown, Check",
    tokens: "--input, --popover, --accent, --ring",
    normalization: "FUTURE OPPORTUNITY — align trigger height with the control-height ramp.",
    migration: "Low risk, but heights differ per consumer today.",
    figma: "Component with Open, Selected and Disabled states.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },

  /* ---------------- Display ---------------- */
  {
    canonical: "Core / Display / StatusBadge",
    currentName: "StatusBadge",
    currentSource: "src/components/abox/status-badge.tsx",
    taxonomy: "display",
    tier: "ABox Core",
    classification: "component",
    consumers: "89 direct",
    usage: "The widest-reach component in the system; also used inside filters and tables.",
    variants: "tones sage, primary, warning, muted, destructive, info",
    sizes: "single",
    states: "static; selection is expressed by the consumer, not the badge",
    anatomy: "root span → tone dot → label",
    responsive: "None.",
    dependencies: "Foundation tone tokens, color-mix",
    relationships: "Composed inside DataTable cells, PlanCard, filter chips, KPI rows.",
    related: "MetalBadge, ui/Badge, m06 StatusTag, lucie-app StatusChip",
    duplication:
      "OBSERVED DUPLICATE — four status vocabularies coexist: StatusBadge tones, ui/Badge variants, m06 StatusTag and lucie-app StatusChip.",
    accessibility:
      "Colour is paired with a text label everywhere it appears, so tone is never the only signal.",
    typography: "text-xs font-medium",
    spacing: "px-2.5 py-0.5, gap-1.5",
    iconography: "A dot, not an icon.",
    tokens: "--sage, --primary, --warning, --muted, --destructive, --info",
    normalization:
      "FUTURE CANONICAL TARGET — one status vocabulary shared by Core and route-local kits.",
    migration:
      "Requires a semantic mapping exercise first; tone names differ in meaning between kits.",
    figma: "Component with a Tone property.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },
  {
    canonical: "Core / Commerce / MetalBadge",
    currentName: "MetalBadge",
    currentSource: "src/components/abox/metal-badge.tsx",
    taxonomy: "commerce",
    tier: "ABox Core",
    classification: "component",
    consumers: "4 direct",
    usage: "Direct plus indirect through PlanCard and the plans filter rail.",
    variants: "Bronze, Expanded Bronze, Silver, Gold, Platinum, Catastrophic",
    sizes: "single",
    states: "static; solid fill at full opacity in both listings and filters",
    anatomy: "root span → tier label",
    responsive: "None.",
    dependencies: "Metal tier tokens with paired foregrounds",
    relationships: "Used inside PlanCard and the filter rail.",
    related: "StatusBadge",
    duplication: "None. Tier colour is owned in one place.",
    accessibility: "Foreground is chosen per tier for contrast against the solid fill.",
    typography: "text-xs font-medium",
    spacing: "px-2.5 py-0.5",
    iconography: "None.",
    tokens: "Six metal tier tokens plus their foreground pairs",
    normalization:
      "GOVERNANCE RULE — tier colours are product meaning and must not be normalized into the generic tone scale.",
    migration: "Not a migration candidate.",
    figma: "Component with a Tier property bound to the metal variables.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },
  {
    canonical: "Core / Data / KpiCard",
    currentName: "KpiCard",
    currentSource: "src/components/abox/kpi-card.tsx",
    taxonomy: "data",
    tier: "ABox Core",
    classification: "compound component",
    consumers: "18 direct",
    usage: "Direct, almost entirely in Dashboard/Admin routes.",
    variants: "tones default, primary, sage, warning",
    sizes: "single; the grid decides the footprint",
    states: "default, hover lift with brackets and sheen",
    anatomy: "root card → icon → label → value (CountUp) → optional delta → optional hint",
    responsive: "Sits in a responsive grid owned by the page.",
    dependencies: "motion CountUp, lucide icons, card tokens",
    relationships: "Consumes motion; consumed by dashboard pages.",
    related: "Surface card pattern",
    duplication: "OBSERVED OVERLAP — route-local StatCard implementations exist in the Lucie kits.",
    accessibility:
      "FUTURE OPPORTUNITY — animated counting is visual only; the final value is what screen readers read.",
    typography: "Large tabular numeric value, small uppercase label",
    spacing: "p-5, gap-2",
    iconography: "One lucide icon per card, decorative.",
    tokens: "--card, --primary, --sage, --warning",
    normalization: "FUTURE CANONICAL TARGET — absorb the route-local StatCards.",
    migration: "Medium risk; the kits have different props and densities.",
    figma: "Component with Tone, Delta and Hint properties.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },

  /* ---------------- Containers & data ---------------- */
  {
    canonical: "Core / Containers / SurfaceCard",
    currentName: "— no component owner —",
    currentSource: "Repeated route markup",
    taxonomy: "container",
    tier: "ABox Core",
    classification: "pattern",
    consumers: "Not reliably countable — appears across most routes",
    usage: "Copied markup, not an import.",
    variants: "static, hoverable, bracketed",
    sizes: "p-4, p-5 and p-6 all occur",
    states: "default, hover on the interactive variant",
    anatomy: "root div → optional header row → body → optional footer actions",
    responsive: "Page-driven.",
    dependencies: "Foundation tokens",
    relationships: "Wraps nearly every other component at some point.",
    related: "ui/Card, KpiCard, PlanCard",
    duplication:
      "OBSERVED VARIATION — border token alternates between `border` and `hairline`; radius between rounded-xl and rounded-2xl.",
    accessibility: "Generic container; semantics come from the content.",
    typography: "Inherited.",
    spacing: "p-5 is the most common at 187 occurrences.",
    iconography: "Optional header icon.",
    tokens: "--card, --border, --hairline, --radius",
    normalization:
      "FUTURE CANONICAL TARGET — one card surface component. Centralizing today would change rendered borders and padding, so it is deferred.",
    migration: "High visual-diff surface; needs per-route screenshots.",
    figma: "Component with Padding, Border and Interactive properties.",
    label: "UNOWNED AREA",
    phase: "Phase 2 — spacing, layout, responsive",
  },
  {
    canonical: "Core / Data / DataTable",
    currentName: "DataTable",
    currentSource: "src/components/abox/data-table.tsx",
    taxonomy: "data",
    tier: "ABox Core",
    classification: "compound component",
    consumers: "20 direct",
    usage: "Direct, mostly Dashboard/Admin.",
    variants: "single appearance; alignment per column",
    sizes: "min-w-[640px], px-5 py-4 cells",
    states: "rows, empty row, hover with ember left border, clickable row",
    anatomy:
      "scroll wrapper → table → sr-only caption → uppercase serial head → rows → per-cell alignment → empty row",
    responsive: "Owns its own horizontal scroll below the min width.",
    dependencies: "cn utility, foundation tokens",
    relationships: "Consumed by admin and agency screens; composes StatusBadge in cells.",
    related: "ui/Table (unused), lucie table, lucie-app DataTable, m06 tables",
    duplication:
      "OBSERVED DUPLICATE — four table implementations coexist; ui/Table has no production consumer.",
    accessibility:
      "scope=col headers and an sr-only caption; row click has no keyboard equivalent.",
    typography: "text-sm body, 10px uppercase tracked head",
    spacing: "px-5 py-4 cells",
    iconography: "Supplied by cell content.",
    tokens: "--card, --hairline, --panel, --primary",
    normalization: "FUTURE CANONICAL TARGET — one table with a Density property.",
    migration: "Medium-high risk; the kits differ in density and features.",
    figma: "Component with Density, Alignment and Empty properties.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },
  {
    canonical: "Core / Display / PageHeader",
    currentName: "PageHeader",
    currentSource: "src/components/abox/page-header.tsx",
    taxonomy: "display",
    tier: "ABox Core",
    classification: "compound component",
    consumers: "25 direct",
    usage: "Direct across all three experiences.",
    variants: "default, compact",
    sizes: "Title size differs between the two variants.",
    states: "static",
    anatomy:
      "root → optional eyebrow → optional SCR id → optional icon → title → optional description → optional action area",
    responsive: "Actions wrap below the title on narrow widths.",
    dependencies: "motion FadeRise, lucide icons",
    relationships: "Consumes motion; consumed by screens; often paired with ACTION_PILL rows.",
    related: "m06 page head, lucie page head, lucie-app PageHeader",
    duplication: "OBSERVED DUPLICATE — four page-header implementations across Core and the kits.",
    accessibility: "Renders the page's heading element; icon is decorative.",
    typography: "Heading ramp plus muted description",
    spacing: "gap-2 internal, generous bottom margin",
    iconography: "One optional leading icon.",
    tokens: "--foreground, --muted-foreground",
    normalization: "FUTURE CANONICAL TARGET — one page header with a Density property.",
    migration: "Medium risk; heading sizes were tuned by hand and must be diffed.",
    figma: "Component with Density, Eyebrow, Icon, Description and Actions properties.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },

  /* ---------------- Feedback ---------------- */
  {
    canonical: "Core / Feedback / EmptyState",
    currentName: "EmptyState",
    currentSource: "src/components/abox/empty-state.tsx",
    taxonomy: "feedback",
    tier: "ABox Core",
    classification: "component",
    consumers: "10 direct",
    usage: "Direct across shopping and admin.",
    variants: "single",
    sizes: "single",
    states: "static; optional action",
    anatomy: "root → optional decor → optional icon → title → optional body → optional action",
    responsive: "Centred; inherits container width.",
    dependencies: "decor, lucide icons",
    relationships: "Consumes decor; consumed by list and result screens.",
    related: "DataTable empty row, m06 StateBlock, lucie-app EmptyState",
    duplication: "OBSERVED DUPLICATE — at least three empty-state implementations.",
    accessibility: "Text-first; the icon is decorative.",
    typography: "Title plus muted body",
    spacing: "Generous vertical padding",
    iconography: "One optional lucide icon.",
    tokens: "--muted-foreground, --card",
    normalization: "FUTURE CANONICAL TARGET — one empty state with a Size property.",
    migration: "Low-medium risk.",
    figma: "Component with Icon, Body and Action properties.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },
  {
    canonical: "Core / Feedback / Toast",
    currentName: "Sonner Toaster",
    currentSource: "src/components/ui/sonner.tsx, mounted in src/routes/__root.tsx",
    taxonomy: "feedback",
    tier: "ABox Core",
    classification: "component",
    consumers: "1 mount, triggered from the cart store",
    usage: "Indirect — screens trigger it through the store, not by importing it.",
    variants: "default toast with description",
    sizes: "library default",
    states: "enter, visible, dismiss",
    anatomy: "portal → toast → title → description",
    responsive: "Library-owned.",
    dependencies: "sonner",
    relationships: "Mounted once at the root.",
    related: "m06 Toast",
    duplication: "OBSERVED DUPLICATE — the M06 kit has its own toast.",
    accessibility: "Library-provided live region.",
    typography: "text-sm",
    spacing: "Library default.",
    iconography: "None by default.",
    tokens: "Themed through the sonner wrapper.",
    normalization: "FUTURE CANONICAL TARGET — one notification channel.",
    migration: "Low risk once the M06 kit's usage is understood.",
    figma: "Component with Tone and Description properties.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },

  /* ---------------- Commerce ---------------- */
  {
    canonical: "Commerce / PlanCard",
    currentName: "PlanCard",
    currentSource: "src/components/abox/plan-card.tsx",
    taxonomy: "commerce",
    tier: "Experience-specific",
    classification: "compound component",
    consumers: "6 direct",
    usage: "Direct in plans, compare and cart surfaces.",
    variants: "stacked, horizontal, best-match, in-cart, subsidised price",
    sizes: "Two layout footprints.",
    states: "default, hover, in cart, in compare, saved, best match",
    anatomy:
      "root card → CarrierMark → carrier and plan name (OverflowText) → MetalBadge → status badges → price block → action row",
    responsive: "Horizontal layout collapses to stacked on narrow widths.",
    dependencies: "CarrierMark, MetalBadge, StatusBadge, OverflowText, ACTION_PILL",
    relationships: "The densest composition in the product.",
    related: "SurfaceCard pattern, cart line item",
    duplication: "None.",
    accessibility: "Long names truncate with a hover/focus reveal through OverflowText.",
    typography: "Tabular price figures, text-sm body",
    spacing: "p-5, gap-2 / gap-3",
    iconography: "CarrierMark monogram plus status icons.",
    tokens: "Metal tier tokens, status tones, card tokens",
    normalization:
      "GOVERNANCE RULE — stays experience-specific. It is the clearest example of a Shopping pattern built from Core parts.",
    migration: "Not a consolidation candidate.",
    figma: "Component with Layout, Tier, BestMatch and InCart properties.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },
  {
    canonical: "Commerce / CarrierMark",
    currentName: "CarrierMark",
    currentSource: "src/components/abox/carrier-mark.tsx",
    taxonomy: "brand",
    tier: "Experience-specific",
    classification: "component",
    consumers: "3 direct",
    usage: "Direct plus indirect through PlanCard and the cart.",
    variants: "deterministic monogram, neutral fallback",
    sizes: "Sizeable by prop.",
    states: "static",
    anatomy: "root → coloured disc → monogram letters",
    responsive: "None.",
    dependencies: "Foundation tokens, a deterministic hash of the carrier name",
    relationships: "Composed inside PlanCard and cart lines.",
    related: "AboxMark",
    duplication: "None.",
    accessibility: "Decorative; the carrier name is always rendered as text alongside it.",
    typography: "Uppercase monogram",
    spacing: "Fixed disc dimensions",
    iconography: "Typographic, not an icon.",
    tokens: "Neutral surface and foreground tokens",
    normalization:
      "GOVERNANCE RULE — illustrative only. Real carrier logos would be runtime assets owned by asset management, not by the design system.",
    migration: "Not a migration candidate.",
    figma: "Component with a Fallback property; no real logos in the library.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 4 — iconography & assets",
  },

  /* ---------------- Shell & brand ---------------- */
  {
    canonical: "Core / Shell / ApplicationShell",
    currentName: "InternalShell, MarketplaceShell, MemberShell",
    currentSource: "src/components/abox/*-shell.tsx",
    taxonomy: "shell",
    tier: "ABox Core",
    classification: "compound component",
    consumers: "89 + 30 + 4 = 123 routes",
    usage: "Direct; every application route sits inside exactly one shell.",
    variants: "Three families, each with its own navigation model.",
    sizes: "Rail expanded/collapsed, 88rem content width on web experiences.",
    states: "rail expanded, rail collapsed, mobile sheet, sticky header, signed in / signed out",
    anatomy: "skip link → header → navigation → main → optional rail or footer",
    responsive: "Rail becomes a Sheet below the lg breakpoint.",
    dependencies: "Sheet, nav-config, Logo, auth session, lucide icons",
    relationships: "The root composition for every screen.",
    related: "ui/Sidebar (installed, unused)",
    duplication:
      "OBSERVED OVERLAP — three shells share header, skip-link and container concerns without a shared base.",
    accessibility: "Skip link, landmark structure, 44px mobile touch targets.",
    typography: "Navigation text-sm",
    spacing: "max-w-[88rem] content, sticky header offsets",
    iconography: "One lucide icon per navigation item.",
    tokens: "--sidebar, --background, --card, --hairline",
    normalization:
      "FUTURE OPPORTUNITY — a shared shell base for header, skip link and container. The three navigation models stay separate.",
    migration: "High risk: every route renders through a shell.",
    figma: "Three frame templates plus one shared header component.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 5 — components, variants, states",
  },
  {
    canonical: "Core / Brand / Logo",
    currentName: "AboxMark, AboxWordmark",
    currentSource: "src/components/abox/logo.tsx",
    taxonomy: "brand",
    tier: "ABox Core",
    classification: "component",
    consumers: "5 direct",
    usage: "Direct in shells, auth and the landing page.",
    variants: "4 tones",
    sizes: "Sizeable by prop.",
    states: "static",
    anatomy: "inline SVG mark → optional wordmark text",
    responsive: "Wordmark hides on the narrowest widths in some shells.",
    dependencies: "Foundation tokens only — the mark is code-drawn, not a file.",
    relationships: "Consumed by the shells.",
    related: "favicon.ico, runtime white-label branding",
    duplication: "None.",
    accessibility: "Paired with an accessible name in the shells.",
    typography: "Wordmark uses the display family.",
    spacing: "Shell-driven.",
    iconography: "Its own SVG geometry.",
    tokens: "--primary, --foreground",
    normalization:
      "GOVERNANCE RULE — the product mark is a Core foundation; per-marketplace logos stay runtime configuration.",
    migration: "Not a migration candidate.",
    figma: "Brand assets frame with tone variants.",
    label: "CURRENT IMPLEMENTATION",
    phase: "Phase 4 — iconography & assets",
  },
];

/** Counts used by the reference pages. Derived, never hand-maintained twice. */
export const CANONICAL_SUMMARY = {
  candidates: CANONICAL_COMPONENT_MAP.length,
  core: CANONICAL_COMPONENT_MAP.filter((c) => c.tier === "ABox Core").length,
  experience: CANONICAL_COMPONENT_MAP.filter((c) => c.tier === "Experience-specific").length,
  patterns: CANONICAL_COMPONENT_MAP.filter((c) => c.classification === "pattern").length,
} as const;
