/**
 * Phase 11 — canonical candidate register.
 *
 * DOCUMENTATION ONLY. A candidate is an area that COULD become canonical in a
 * future approved phase. A candidate is NOT a selected winner. The list carries
 * no order, no rank, no score and no "best". Where several implementations
 * exist, all are named with their real consumers and the decision is left open.
 */
import type { CanonicalCandidate } from "./canonical-readiness-types";

export const CANONICAL_CANDIDATES: CanonicalCandidate[] = [
  {
    id: "cand.action-pill",
    area: "Action pills",
    currentImplementation: "ACTION_PILL class string centralised in src/components/abox/action-pill.ts.",
    observedVariation: "Hero pills render at h-11 while the shared pill height is used elsewhere.",
    potentialCanonicalTarget: "A single pill component with the height difference expressed as a variant, if approved.",
    requiredDecision: "Whether the hero height is a variant of the shared pill or a marketing-only treatment.",
    evidence: "35 files, 82 references; hero classes in src/routes/index.tsx.",
    consumers: "35 files",
    blocker: "no blocker",
    readiness: "READY FOR FUTURE DECISION",
    status: "FUTURE CANONICAL TARGET",
  },
  {
    id: "cand.button",
    area: "Buttons and actions",
    currentImplementation: "Button primitive with its existing variants.",
    observedVariation: "Control height differs between 36px and 40px depending on surface.",
    potentialCanonicalTarget: "A settled size scale for interactive controls.",
    requiredDecision: "Which heights are legitimate sizes and which are historical drift.",
    evidence: "22 consumers; heights measured in Phase 2 and Phase 7.",
    consumers: "22 files",
    blocker: "insufficient evidence",
    readiness: "NEEDS DESIGN DECISION",
    status: "FUTURE CANONICAL TARGET",
  },
  {
    id: "cand.page-header",
    area: "Page headers",
    currentImplementation: "PageHeader with default and compact variants.",
    observedVariation: "Marketing section headings and the internal shell masthead both open a screen without using PageHeader.",
    potentialCanonicalTarget: "One screen-opening pattern covering all three placements.",
    requiredDecision: "Whether marketing headings and the shell masthead should be the same thing as PageHeader.",
    evidence: "PageHeader in 25 files; landing headings in src/routes/index.tsx; internal-shell.tsx lines 114-119.",
    consumers: "25 files plus two unowned placements",
    blocker: "duplicate implementation",
    readiness: "BLOCKED BY DUPLICATE",
    status: "FUTURE CANONICAL TARGET",
  },
  {
    id: "cand.section-header",
    area: "Section headers",
    currentImplementation: "Written inline per marketing section; no component owns it.",
    observedVariation: "Heading level, eyebrow presence and spacing differ per section.",
    potentialCanonicalTarget: "A section header component, if an owner is assigned.",
    requiredDecision: "Who owns marketing section structure.",
    evidence: "Phase 10 records marketing section headers as unowned.",
    consumers: "landing sections only",
    blocker: "no owner",
    readiness: "NEEDS OWNER",
    status: "UNOWNED AREA",
  },
  {
    id: "cand.surface",
    area: "Cards and surfaces",
    currentImplementation: "Card primitive plus rounded-2xl border-hairline bg-card written directly in many places.",
    observedVariation: "Card padding is p-5 in some surfaces and p-6 in others.",
    potentialCanonicalTarget: "A surface role with a settled padding scale.",
    requiredDecision: "Whether p-5 and p-6 are two densities or one unintended split.",
    evidence: "p-5 measured 187 times, p-6 present alongside it; Card primitive has 6 consumers.",
    consumers: "6 direct, many literal",
    blocker: "insufficient evidence",
    readiness: "NEEDS DESIGN DECISION",
    status: "OBSERVED VARIATION",
  },
  {
    id: "cand.form-field",
    area: "Form fields",
    currentImplementation: "Input, Label and Select primitives, plus independent field compositions in the M06 and M08 kits.",
    observedVariation: "Label placement, help and error text and validation wiring differ between the three.",
    potentialCanonicalTarget: "One field composition covering label, control, help and error.",
    requiredDecision: "Whether the governed module kits adopt a shared field or stay independent.",
    evidence: "Input 7 consumers, Select 7, Label 5; M06 and M08 kits written per module.",
    consumers: "primitives plus two route kits",
    blocker: "duplicate implementation",
    readiness: "BLOCKED BY DUPLICATE",
    status: "OBSERVED DUPLICATE",
  },
  {
    id: "cand.status-badge",
    area: "Status badges and tone vocabulary",
    currentImplementation: "StatusBadge with tone tokens; MetalBadge with per-tier tokens and accessible foreground selection.",
    observedVariation: "None material — filter chips reuse the same badge treatments as listings.",
    potentialCanonicalTarget: "Status and tier badges as one component set with a kind property.",
    requiredDecision: "Whether tier is a variant of status or a separate component.",
    evidence: "StatusBadge in 89 files; metal tokens including Expanded Bronze.",
    consumers: "89 files",
    blocker: "no blocker",
    readiness: "READY FOR FUTURE DECISION",
    status: "FUTURE CANONICAL TARGET",
  },
  {
    id: "cand.table",
    area: "Tables and data presentation",
    currentImplementation: "DataTable, the table primitive and route-local tables all render records.",
    observedVariation: "Cell padding, minimum width, empty-row handling and aria labelling differ.",
    potentialCanonicalTarget: "One table pattern with density as a property.",
    requiredDecision: "Which of the three implementations future screens should use, and what happens to the others.",
    evidence: "DataTable in 20 files at min-w-[640px] px-5 py-4; primitive and route-local tables elsewhere.",
    consumers: "20 files plus route-local",
    blocker: "duplicate implementation",
    readiness: "BLOCKED BY DUPLICATE",
    status: "OBSERVED DUPLICATE",
  },
  {
    id: "cand.kpi",
    area: "KPI and metric groups",
    currentImplementation: "KpiCard with default, primary, sage and warning tones inside a grid.",
    observedVariation: "Grid column counts differ by screen; the card itself is consistent.",
    potentialCanonicalTarget: "A metric card component plus a documented grid.",
    requiredDecision: "Whether the grid is part of the pattern or left to each screen.",
    evidence: "KpiCard in 18 files.",
    consumers: "18 files",
    blocker: "no blocker",
    readiness: "READY FOR FUTURE DECISION",
    status: "FUTURE CANONICAL TARGET",
  },
  {
    id: "cand.navigation",
    area: "Navigation",
    currentImplementation: "Three independent shells: InternalShell, MarketplaceShell, MemberShell.",
    observedVariation: "Rail versus floating header, different collapse breakpoints, different account controls.",
    potentialCanonicalTarget: "Shared navigation primitives beneath three deliberately different shells.",
    requiredDecision: "Whether the shells are intentionally separate products or should share a base.",
    evidence: "89, 30 and member-route consumers respectively.",
    consumers: "three shells",
    blocker: "experience variation",
    readiness: "BLOCKED BY EXPERIENCE VARIATION",
    status: "OBSERVED OVERLAP",
  },
  {
    id: "cand.overlay",
    area: "Dialogs and drawers",
    currentImplementation: "Dialog primitive, plus a route-local filter overlay on the plans route.",
    observedVariation: "Focus trapping, close affordance and animation differ.",
    potentialCanonicalTarget: "One overlay surface with dialog and drawer variants.",
    requiredDecision: "Whether the plans filter overlay adopts the primitive.",
    evidence: "Dialog in 4 files; src/routes/plans.index.tsx line 374.",
    consumers: "4 files plus one route",
    blocker: "duplicate implementation",
    readiness: "BLOCKED BY DUPLICATE",
    status: "OBSERVED VARIATION",
  },
  {
    id: "cand.empty",
    area: "Empty states",
    currentImplementation: "EmptyState with icon, title, body and action.",
    observedVariation: "Some screens write an inline empty message instead.",
    potentialCanonicalTarget: "EmptyState as the single absent-content surface.",
    requiredDecision: "Whether inline empty messages adopt the component.",
    evidence: "EmptyState in 10 files.",
    consumers: "10 files",
    blocker: "no blocker",
    readiness: "READY FOR FUTURE DECISION",
    status: "FUTURE CANONICAL TARGET",
  },
  {
    id: "cand.loading",
    area: "Loading and error presentation",
    currentImplementation: "Skeleton blocks in 4 files; error presentation written per route.",
    observedVariation: "No shared treatment exists for either.",
    potentialCanonicalTarget: "Loading and error surfaces alongside the existing empty state.",
    requiredDecision: "Who owns loading and error presentation.",
    evidence: "Phase 10 records this area as unowned.",
    consumers: "4 files for skeletons; error ad hoc",
    blocker: "no owner",
    readiness: "NEEDS OWNER",
    status: "UNOWNED AREA",
  },
  {
    id: "cand.plan-presentation",
    area: "Plan and product presentation",
    currentImplementation: "PlanCard with the metal badge, exchange status, plan id, premium formatting and carrier mark.",
    observedVariation: "Two tile variants exist, both carrying the same required facts.",
    potentialCanonicalTarget: "One plan tile with a layout variant.",
    requiredDecision: "Whether the two variants are one component or two.",
    evidence: "PlanCard in 6 files; both variants show exchange status and plan id.",
    consumers: "6 files",
    blocker: "no blocker",
    readiness: "READY FOR FUTURE DECISION",
    status: "FUTURE CANONICAL TARGET",
  },
  {
    id: "cand.result-toolbar",
    area: "Result toolbars",
    currentImplementation: "Compact PageHeader with count and sort control on the plans route.",
    observedVariation: "Other result surfaces do not use a toolbar at all.",
    potentialCanonicalTarget: "A result toolbar pattern covering count, sort and applied filters.",
    requiredDecision: "Whether a single route is enough evidence for a pattern.",
    evidence: "Only the plans route implements it.",
    consumers: "one route",
    blocker: "insufficient evidence",
    readiness: "NEEDS EVIDENCE",
    status: "FUTURE DECISION",
  },
  {
    id: "cand.icon-container",
    area: "Icon containers",
    currentImplementation: "Rounded icon tiles written inline in headers and cards.",
    observedVariation: "Tile size and radius differ between surfaces.",
    potentialCanonicalTarget: "An icon tile component with a size property.",
    requiredDecision: "Whether the differences are sizes or drift.",
    evidence: "Phase 4 iconography records; 149 distinct lucide icons across 144 files.",
    consumers: "inline only",
    blocker: "no owner",
    readiness: "NEEDS OWNER",
    status: "UNOWNED AREA",
  },
  {
    id: "cand.typography-roles",
    area: "Typography roles",
    currentImplementation: "Heading, body, description, eyebrow and serial treatments expressed largely through literal classes.",
    observedVariation: "Several heading sizes and five uppercase tracking values; .story-link used 89 times with no definition.",
    potentialCanonicalTarget: "Named type roles bound to the existing values.",
    requiredDecision: "Whether the existing sizes collapse into fewer roles, which would change rendered output.",
    evidence: "text-sm 779 uses, font-medium 406; Phase 3 measurements.",
    consumers: "application-wide",
    blocker: "insufficient evidence",
    readiness: "NEEDS DESIGN DECISION",
    status: "OBSERVED VARIATION",
  },
  {
    id: "cand.spacing-roles",
    area: "Spacing roles",
    currentImplementation: "Literal Tailwind spacing with clear favourites.",
    observedVariation: "gap-1.5 and gap-2 both appear in equivalent positions.",
    potentialCanonicalTarget: "Named spacing roles mapped to the measured values.",
    requiredDecision: "Whether near-identical gaps are unified, which changes pixels.",
    evidence: "gap-2 316, px-3 238, gap-1 232, p-5 187, gap-3 173, px-4 154, gap-4 133, max-w-[88rem] 23.",
    consumers: "application-wide",
    blocker: "insufficient evidence",
    readiness: "NEEDS DESIGN DECISION",
    status: "OBSERVED VARIATION",
  },
  {
    id: "cand.control-sizing",
    area: "Control sizing",
    currentImplementation: "36px and 40px controls coexist by surface.",
    observedVariation: "The same kind of control differs in height between shells and marketing.",
    potentialCanonicalTarget: "A control size scale with a documented default.",
    requiredDecision: "Which height is the default, knowing either answer changes existing screens.",
    evidence: "Phase 2 and Phase 7 measurements; density records in Phase 10.",
    consumers: "application-wide",
    blocker: "insufficient evidence",
    readiness: "NEEDS DESIGN DECISION",
    status: "OBSERVED VARIATION",
  },
  {
    id: "cand.pagination",
    area: "Pagination",
    currentImplementation: "The pagination primitive is installed and has no consumer.",
    observedVariation: "None to observe.",
    potentialCanonicalTarget: "Cannot be established from the code.",
    requiredDecision: "Whether pagination is a product need at all.",
    evidence: "No production consumer found.",
    consumers: "none",
    blocker: "insufficient evidence",
    readiness: "NEEDS EVIDENCE",
    status: "INSTALLED BUT UNUSED",
    note: "FUTURE DECISION — insufficient implementation evidence.",
  },
];

export const CANDIDATE_RULES: string[] = [
  "GOVERNANCE RULE — a candidate is an area open for a future decision, never a chosen implementation.",
  "GOVERNANCE RULE — this register is unordered. There is no rank, score, tier or priority, because any of those would imply a winner.",
  "GOVERNANCE RULE — consumer counts describe reach only. The most used implementation is not thereby the correct one.",
  "GOVERNANCE RULE — a candidate becomes canonical only through an explicit approval recorded in the decision register.",
  "FUTURE OPPORTUNITY — nothing in this register has been acted on; production is unchanged.",
];
