/**
 * Phase 11 — future change process.
 * DOCUMENTATION ONLY. Describes how a change at each layer should be handled in
 * a future approved phase. No build step enforces it and nothing shipping today
 * depends on it.
 */
import type { GovernanceLayerRule } from "./canonical-readiness-types";

export const CHANGE_GOVERNANCE: GovernanceLayerRule[] = [
  {
    layer: "Foundation",
    owner: "design-system",
    evidenceRequired: "The current value, every semantic role bound to it, and the Phase 9 reach of those roles.",
    mayChangeIndependently: "Nothing. A foundation value reaches the whole application.",
    consumersToCheck: "All semantic roles bound to the value, then every component consuming those roles.",
    visualRegression: true,
    accessibilityReview: true,
    responsiveReview: false,
    productApproval: true,
    migrationApproval: true,
    status: "GOVERNANCE RULE",
  },
  {
    layer: "Semantic role",
    owner: "design-system",
    evidenceRequired: "Which foundation value the role points at and which components read the role.",
    mayChangeIndependently: "A role may be added without touching existing ones. Repointing an existing role is not independent.",
    consumersToCheck: "Every component reading the role, across all four experiences.",
    visualRegression: true,
    accessibilityReview: true,
    responsiveReview: false,
    productApproval: false,
    migrationApproval: true,
    status: "GOVERNANCE RULE",
  },
  {
    layer: "Core component",
    owner: "design-system",
    evidenceRequired: "The component's measured consumer count and its anatomy, variants and states.",
    mayChangeIndependently: "A new variant or size, when existing consumers keep their current rendering.",
    consumersToCheck: "Direct consumers from the Phase 9 graph, plus compounds and patterns above it.",
    visualRegression: true,
    accessibilityReview: true,
    responsiveReview: true,
    productApproval: false,
    migrationApproval: true,
    status: "GOVERNANCE RULE",
  },
  {
    layer: "Compound",
    owner: "design-system",
    evidenceRequired: "The components it composes and the patterns that use it.",
    mayChangeIndependently: "Internal arrangement, provided the public props and rendered output are unchanged.",
    consumersToCheck: "Patterns and screens that render the compound.",
    visualRegression: true,
    accessibilityReview: false,
    responsiveReview: true,
    productApproval: false,
    migrationApproval: true,
    status: "GOVERNANCE RULE",
  },
  {
    layer: "Pattern",
    owner: "design-system",
    evidenceRequired: "Anatomy, states, responsive behaviour and density from the Phase 10 records, plus the screens using it.",
    mayChangeIndependently: "Documentation of the pattern. The rendered arrangement is not independent.",
    consumersToCheck: "Every experience pattern derived from it and every screen listed against it.",
    visualRegression: true,
    accessibilityReview: true,
    responsiveReview: true,
    productApproval: true,
    migrationApproval: true,
    status: "GOVERNANCE RULE",
  },
  {
    layer: "Experience pattern",
    owner: "business",
    evidenceRequired: "The core pattern anatomy plus the specific composition, density or wording this experience applies.",
    mayChangeIndependently: "Composition, density and wording inside the core anatomy.",
    consumersToCheck: "Screens in that experience only.",
    visualRegression: true,
    accessibilityReview: false,
    responsiveReview: true,
    productApproval: true,
    migrationApproval: false,
    status: "GOVERNANCE RULE",
  },
  {
    layer: "Screen",
    owner: "business",
    evidenceRequired: "The patterns the screen composes and any controlled identifiers the screen carries.",
    mayChangeIndependently: "Content and arrangement within the patterns it uses.",
    consumersToCheck: "Nothing downstream. A screen is a leaf.",
    visualRegression: false,
    accessibilityReview: false,
    responsiveReview: true,
    productApproval: true,
    migrationApproval: false,
    status: "GOVERNANCE RULE",
  },
  {
    layer: "Runtime branding and marketplace assets",
    owner: "runtime",
    evidenceRequired: "The slot the value fills.",
    mayChangeIndependently: "Tenant configuration, at any time, without design-system involvement.",
    consumersToCheck: "Surfaces that render the slot, to confirm the slot still accepts the value.",
    visualRegression: false,
    accessibilityReview: false,
    responsiveReview: false,
    productApproval: false,
    migrationApproval: false,
    status: "CURRENT IMPLEMENTATION",
  },
];

export const ESCALATION_RULES: string[] = [
  "GOVERNANCE RULE — the lower the layer, the wider the reach. A foundation change is the widest change possible in this system.",
  "GOVERNANCE RULE — reach is established from the Phase 9 graph before a change is estimated, never guessed.",
  "GOVERNANCE RULE — where the graph cannot answer a reach question, the change waits for evidence rather than proceeding.",
  "GOVERNANCE RULE — a change that alters rendered output needs the regression contract satisfied before and after.",
  "GOVERNANCE RULE — governed module screens carrying controlled identifiers need module revalidation on top of design approval.",
];
