/**
 * Phase 7 — colour foundation inventory.
 *
 * DOCUMENTATION ONLY. Every value below is copied verbatim from
 * `src/styles.css`. Nothing here changes a value, and nothing here may be
 * imported by application screens.
 */
import type { TokenSpec, TokenSpecGroup } from "./types";

const P1 = "Phase 1 — foundations" as const;
const SRC = "src/styles.css";

function t(spec: Omit<TokenSpec, "source" | "phase"> & { source?: string }): TokenSpec {
  return { source: spec.source ?? SRC, phase: P1, ...spec } as TokenSpec;
}

const CANVAS: TokenSpec[] = [
  t({
    token: "--background",
    value: "oklch(1 0 0)",
    darkValue: "oklch(0.165 0.030 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Page canvas behind every experience.",
    consumers: "body background, aurora utility, marketplace and internal shells.",
    usage: "149 `bg-background` occurrences in production files.",
    foreground: "--foreground",
    contrast: "Pure white in light mode; navy ink foreground gives a high contrast pair.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "Semantic role `surface/canvas`.",
    figma: "Color variable ABox Core / Color / Surface / Canvas, modes Light + Dark.",
    migration: "Direct one-to-one mapping. No consumer change needed.",
  }),
  t({
    token: "--foreground",
    value: "oklch(0.22 0.025 265)",
    darkValue: "oklch(0.95 0.006 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Default body ink.",
    consumers: "body colour, StatusBadge `muted` tone, most text.",
    usage: "Inherited globally; StatusBadge maps tone `muted` to it.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "Semantic role `content/primary`.",
    figma: "Color variable / Content / Primary.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--surface",
    value: "oklch(0.968 0.003 265)",
    darkValue: "oklch(0.195 0.035 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Recessed surface one step off the canvas.",
    consumers: "Section bands, filter rails, toolbars.",
    usage: "79 `bg-surface` occurrences.",
    foreground: "--surface-foreground",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "Semantic role `surface/sunken`.",
    figma: "Color variable / Surface / Sunken.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--surface-foreground",
    value: "oklch(0.22 0.025 265)",
    darkValue: "oklch(0.95 0.006 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Ink used on the sunken surface.",
    consumers: "Paired with --surface.",
    usage: "Declared; rarely referenced directly because it equals --foreground.",
    status: "OBSERVED OVERLAP",
    futureRole: "Either keep as an explicit pair or resolve to `content/primary`.",
    figma: "Color variable / Surface / Sunken foreground.",
    migration: "FUTURE DECISION — keeping the explicit pair costs nothing but duplicates a value.",
    note: "Identical to --foreground in both modes.",
  }),
  t({
    token: "--panel",
    value: "oklch(0.945 0.004 265)",
    darkValue: "oklch(0.225 0.040 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Deepest neutral plane, one step below surface.",
    consumers: "Panels and inset blocks.",
    usage: "3 `bg-panel` occurrences.",
    status: "POSSIBLY UNUSED",
    futureRole: "Semantic role `surface/inset`.",
    figma: "Color variable / Surface / Inset.",
    migration: "Low consumer count; a future phase should confirm the role before promoting it.",
  }),
  t({
    token: "--card",
    value: "oklch(1 0 0)",
    darkValue: "oklch(0.205 0.036 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Raised content container.",
    consumers: "Card, PlanCard, KpiCard, DataTable shell, reference tables, glass utility.",
    usage: "264 `bg-card` occurrences.",
    foreground: "--card-foreground",
    contrast: "Equal to --background in light mode; separation comes from border and shadow.",
    status: "OBSERVED OVERLAP",
    futureRole: "Semantic role `surface/raised`.",
    figma: "Color variable / Surface / Raised.",
    migration:
      "Light mode card and canvas share a value, so a Figma mode cannot express the difference through colour alone; border and elevation carry it.",
  }),
  t({
    token: "--card-foreground",
    value: "oklch(0.22 0.025 265)",
    darkValue: "oklch(0.95 0.006 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Ink on raised containers.",
    consumers: "Card primitive.",
    usage: "Consumed through the Card primitive's class string.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`content/on-raised`.",
    figma: "Color variable / Content / On raised.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--popover / --popover-foreground",
    value: "oklch(1 0 0) / oklch(0.22 0.025 265)",
    darkValue: "oklch(0.215 0.038 265) / oklch(0.95 0.006 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Floating overlay surface and its ink.",
    consumers: "Popover, Select content, Dropdown menu, Command.",
    usage: "Consumed by the shadcn overlay primitives.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`surface/overlay` and `content/on-overlay`.",
    figma: "Color variable / Surface / Overlay.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--ink",
    value: "oklch(0.22 0.025 265)",
    darkValue: "oklch(0.95 0.006 265)",
    modes: "different",
    kind: "alias",
    purpose: "Named ink alias declared alongside the surface family.",
    consumers: "No Tailwind colour utility is generated for it; not referenced in @theme inline.",
    usage: "Declared in :root and .dark only.",
    status: "POSSIBLY UNUSED",
    futureRole: "FUTURE DECISION — keep as a documented alias of `content/primary` or retire it.",
    figma: "Not a separate variable; would alias Content / Primary.",
    migration: "No consumers found; still not removed in this phase.",
  }),
];

const BRAND: TokenSpec[] = [
  t({
    token: "--primary",
    value: "oklch(0.31 0.090 265)",
    darkValue: "oklch(0.68 0.125 255)",
    modes: "different",
    kind: "semantic",
    purpose: "Primary action and brand navy.",
    consumers: "Button default, links, ember-underline, card-brackets, selection, chart-1, ring.",
    usage: "229 `bg-primary`, 268 `text-primary` occurrences.",
    foreground: "--primary-foreground",
    contrast: "Deep navy on white in light mode; lifts to a brighter azure in dark mode.",
    status: "OBSERVED OVERLAP",
    futureRole:
      "Split into `brand/primary` (identity) and `action/primary` (interaction) — one value today serves both.",
    figma: "Color variable / Brand / Primary, aliased by Action / Primary.",
    migration: "Splitting is a naming change only; both would resolve to the same value initially.",
  }),
  t({
    token: "--primary-foreground",
    value: "oklch(0.99 0.002 265)",
    darkValue: "oklch(0.16 0.045 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Ink on primary surfaces.",
    consumers: "Button default label, selection text.",
    usage: "Paired wherever bg-primary is used.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`action/primary-on`.",
    figma: "Color variable / Action / Primary on.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--primary-soft",
    value: "oklch(0.945 0.020 265)",
    darkValue: "oklch(0.30 0.070 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Low-emphasis primary tint for chips and selected rows.",
    consumers: "Soft primary backgrounds across shopping and admin surfaces.",
    usage: "Consumed via `bg-primary-soft` utilities.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`action/primary-subtle`.",
    figma: "Color variable / Action / Primary subtle.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--secondary / --secondary-foreground",
    value: "oklch(0.955 0.004 265) / oklch(0.24 0.025 265)",
    darkValue: "oklch(0.255 0.040 265) / oklch(0.95 0.006 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Secondary action surface.",
    consumers: "Button secondary, Badge secondary.",
    usage: "Consumed through primitive variants.",
    status: "OBSERVED DUPLICATE",
    futureRole: "`action/secondary` and `action/secondary-on`.",
    figma: "Color variable / Action / Secondary.",
    migration:
      "Shares its exact value with --muted and --accent in both modes; a future phase must decide whether three names for one value are intentional.",
  }),
  t({
    token: "--sage / --sage-foreground / --sage-soft",
    value: "oklch(0.55 0.085 195) / oklch(0.99 0.004 195) / oklch(0.945 0.030 195)",
    darkValue: "oklch(0.74 0.090 195) / oklch(0.16 0.035 195) / oklch(0.30 0.055 195)",
    modes: "different",
    kind: "semantic",
    purpose: "Refined teal accent used for positive and confirming states.",
    consumers: "StatusBadge `sage`, MaturityCallout current, chart-2.",
    usage: "28 `bg-sage`, 41 `text-sage` occurrences.",
    status: "OBSERVED OVERLAP",
    futureRole: "FUTURE DECISION — brand accent, or the positive status role, or both.",
    figma: "Color variable / Brand / Sage, with a soft step.",
    migration:
      "--success exists separately, so sage and success both express positive meaning. Neither is retired here.",
  }),
  t({
    token: "--muted / --muted-foreground",
    value: "oklch(0.955 0.004 265) / oklch(0.50 0.018 265)",
    darkValue: "oklch(0.235 0.036 265) / oklch(0.73 0.015 265)",
    modes: "different",
    kind: "semantic",
    purpose: "De-emphasised surface and supporting text.",
    consumers: "Supporting copy everywhere, eyebrow and serial utilities, placeholders.",
    usage: "716 `text-muted-foreground`, 39 `bg-muted` occurrences.",
    contrast:
      "muted-foreground on card is the most used text pair in the product; any change is high risk.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`surface/muted` and `content/secondary`.",
    figma: "Color variable / Content / Secondary.",
    migration: "Direct mapping; highest blast radius of any colour token.",
  }),
  t({
    token: "--accent / --accent-foreground",
    value: "oklch(0.955 0.004 265) / oklch(0.24 0.025 265)",
    darkValue: "oklch(0.255 0.040 265) / oklch(0.95 0.006 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Hover surface for ghost and outline controls.",
    consumers: "Button ghost/outline hover, menu item hover, tabs.",
    usage: "Consumed through primitive hover states.",
    status: "OBSERVED DUPLICATE",
    futureRole: "`state/hover-surface`.",
    figma: "Color variable / State / Hover surface.",
    migration:
      "Identical in value to --secondary and --muted. Renaming it to a state role would clarify intent without changing pixels.",
  }),
  t({
    token: "--ai / --ai-foreground",
    value: "oklch(0.52 0.115 292) / oklch(0.99 0.004 292)",
    darkValue: "oklch(0.70 0.120 292) / oklch(0.16 0.035 292)",
    modes: "different",
    kind: "semantic",
    purpose: "Assistant / PlanAI identity tone in the compatibility layer.",
    consumers: "Exposed as --color-ai; no `bg-ai` class occurrence found in production files.",
    usage: "0 direct `bg-ai` occurrences.",
    status: "POSSIBLY UNUSED",
    futureRole: "`brand/assistant`.",
    figma: "Color variable / Brand / Assistant.",
    migration: "Confirm consumers before promoting or retiring. Not removed here.",
  }),
  t({
    token: "--brand-accent",
    value: "var(--primary)",
    modes: "same",
    kind: "alias",
    purpose: "Compatibility alias kept for governance surfaces.",
    consumers: "3 occurrences.",
    usage: "3 occurrences of `brand-accent`.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "Documented alias of `brand/primary`.",
    figma: "Not a variable; recorded as an alias note.",
    migration: "Alias is retained. Removing it would touch governed surfaces.",
  }),
  t({
    token: "--surface-1 / --surface-2 / --surface-3",
    value: "var(--card) / var(--surface) / var(--panel)",
    modes: "same",
    kind: "alias",
    purpose: "Numbered surface aliases from the target-app compatibility layer.",
    consumers: "4 occurrences each.",
    usage: "4 occurrences each.",
    status: "OBSERVED OVERLAP",
    futureRole:
      "Documented aliases of `surface/raised`, `surface/sunken`, `surface/inset`. Two vocabularies describe one ladder.",
    figma: "Not separate variables; recorded as aliases.",
    migration: "Retained. A future phase may pick one vocabulary — this phase does not.",
  }),
];

const STATUS: TokenSpec[] = [
  t({
    token: "--destructive / --destructive-foreground",
    value: "oklch(0.55 0.185 25) / oklch(0.99 0.004 25)",
    darkValue: "unchanged in .dark",
    modes: "same",
    kind: "semantic",
    purpose: "Errors and destructive actions.",
    consumers: "Button destructive, form errors, StatusBadge `destructive`.",
    usage: "19 `bg-destructive`, 47 `text-destructive` occurrences.",
    status: "OBSERVED VARIATION",
    futureRole: "`status/danger` with a paired `on` and `subtle` step.",
    figma: "Color variable / Status / Danger.",
    migration:
      "Not redefined in .dark, so the same value serves both modes while its neighbours shift.",
  }),
  t({
    token: "--warning / --warning-foreground",
    value: "oklch(0.72 0.125 75) / oklch(0.22 0.045 75)",
    darkValue: "oklch(0.78 0.115 75) / unchanged",
    modes: "different",
    kind: "semantic",
    purpose: "Caution, pending and review states.",
    consumers: "StatusBadge `warning`, MaturityCallout opportunity, chart-4.",
    usage: "24 `bg-warning` occurrences.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`status/caution`.",
    figma: "Color variable / Status / Caution.",
    migration: "Foreground is not redefined in dark mode; record before any change.",
  }),
  t({
    token: "--info / --info-foreground",
    value: "oklch(0.55 0.120 250) / oklch(0.99 0.004 250)",
    darkValue: "oklch(0.70 0.115 250) / unchanged",
    modes: "different",
    kind: "semantic",
    purpose: "Informational emphasis, on-exchange status.",
    consumers: "StatusBadge `info`, exchange status chips.",
    usage: "1 direct `bg-info` occurrence; mostly consumed through StatusBadge tone mixing.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`status/info`.",
    figma: "Color variable / Status / Info.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--success / --success-foreground",
    value: "oklch(0.55 0.100 160) / oklch(0.99 0.004 160)",
    darkValue: "oklch(0.70 0.095 160) / unchanged",
    modes: "different",
    kind: "semantic",
    purpose: "Positive confirmation.",
    consumers: "1 direct `bg-success` occurrence.",
    usage: "1 occurrence.",
    status: "OBSERVED OVERLAP",
    futureRole: "`status/positive`.",
    figma: "Color variable / Status / Positive.",
    migration:
      "StatusBadge has no `success` tone; positive meaning is expressed through `sage`. Both are kept.",
  }),
];

const LINES: TokenSpec[] = [
  t({
    token: "--border",
    value: "oklch(0.30 0.04 265 / 0.10)",
    darkValue: "oklch(1 0 0 / 0.09)",
    modes: "different",
    kind: "semantic",
    purpose: "Default border, applied globally by the base layer.",
    consumers: "`* { border-color: var(--color-border) }`, every bordered element.",
    usage: "497 `border-border` occurrences plus the global default.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`line/default`.",
    figma: "Color variable / Line / Default.",
    migration: "Alpha-based value maps cleanly to a Figma colour with opacity baked in.",
  }),
  t({
    token: "--border-strong",
    value: "oklch(0.30 0.04 265 / 0.24)",
    darkValue: "oklch(1 0 0 / 0.20)",
    modes: "different",
    kind: "semantic",
    purpose: "Emphasised divider or selected outline.",
    consumers: "Selected states and heavier separators.",
    usage: "Consumed via `border-border-strong`.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`line/strong`.",
    figma: "Color variable / Line / Strong.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--hairline",
    value: "oklch(0.30 0.04 265 / 0.11)",
    darkValue: "oklch(1 0 0 / 0.11)",
    modes: "different",
    kind: "semantic",
    purpose: "Editorial hairline used by cards, tables and dividers.",
    consumers: "glass, ring-pill, divider-warm, reference tables, ABox cards.",
    usage: "98 `border-hairline` occurrences.",
    status: "OBSERVED OVERLAP",
    futureRole: "FUTURE DECISION — `line/hairline` or an alias of `line/default`.",
    figma: "Color variable / Line / Hairline.",
    migration:
      "Light-mode hairline (0.11 alpha) and border (0.10 alpha) differ by one hundredth; the visual difference is near zero but both are used deliberately.",
  }),
  t({
    token: "--input",
    value: "oklch(0.30 0.04 265 / 0.16)",
    darkValue: "oklch(1 0 0 / 0.12)",
    modes: "different",
    kind: "semantic",
    purpose: "Form control border.",
    consumers: "Input, Textarea, Select trigger, Button outline.",
    usage: "Consumed through `border-input`.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`line/control`.",
    figma: "Color variable / Line / Control.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--ring",
    value: "oklch(0.31 0.090 265)",
    darkValue: "oklch(0.68 0.125 255)",
    modes: "different",
    kind: "semantic",
    purpose: "Focus ring colour.",
    consumers: "Every focus-visible ring in the primitive layer.",
    usage: "68 `ring-ring` occurrences, 69 `focus-visible:` occurrences.",
    contrast: "Equals --primary in both modes, so focus and brand share one hue.",
    status: "OBSERVED OVERLAP",
    futureRole: "`state/focus-ring`, defined independently of brand.",
    figma: "Color variable / State / Focus ring.",
    migration: "Would start as an alias of Brand / Primary, so no pixel changes.",
  }),
];

const DATAVIZ: TokenSpec[] = [
  t({
    token: "--chart-1",
    value: "oklch(0.31 0.090 265)",
    darkValue: "oklch(0.68 0.125 255)",
    modes: "different",
    kind: "semantic",
    purpose: "First data series.",
    consumers: "Charts in admin surfaces.",
    usage: "26 `chart-` occurrences across production files.",
    status: "OBSERVED OVERLAP",
    futureRole: "`dataviz/series-1`.",
    figma: "Color variable / Dataviz / Series 1.",
    migration:
      "Equals --primary; a future phase decides whether series 1 should be brand-coloured.",
  }),
  t({
    token: "--chart-2",
    value: "oklch(0.55 0.085 195)",
    darkValue: "oklch(0.74 0.090 195)",
    modes: "different",
    kind: "semantic",
    purpose: "Second data series.",
    consumers: "Charts.",
    usage: "Part of the 26 chart occurrences.",
    status: "OBSERVED OVERLAP",
    futureRole: "`dataviz/series-2`.",
    figma: "Color variable / Dataviz / Series 2.",
    migration: "Equals --sage.",
  }),
  t({
    token: "--chart-3",
    value: "oklch(0.60 0.115 250)",
    darkValue: "oklch(0.62 0.110 250)",
    modes: "different",
    kind: "primitive",
    purpose: "Third data series.",
    consumers: "Charts.",
    usage: "Part of the 26 chart occurrences.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`dataviz/series-3`.",
    figma: "Color variable / Dataviz / Series 3.",
    migration: "Only chart token with no semantic twin elsewhere.",
  }),
  t({
    token: "--chart-4",
    value: "oklch(0.72 0.125 75)",
    darkValue: "oklch(0.78 0.115 75)",
    modes: "different",
    kind: "semantic",
    purpose: "Fourth data series.",
    consumers: "Charts.",
    usage: "Part of the 26 chart occurrences.",
    status: "OBSERVED OVERLAP",
    futureRole: "`dataviz/series-4`.",
    figma: "Color variable / Dataviz / Series 4.",
    migration: "Equals --warning, so a caution meaning can leak into a neutral series.",
  }),
  t({
    token: "--chart-5",
    value: "oklch(0.62 0.020 265)",
    darkValue: "oklch(0.70 0.020 265)",
    modes: "different",
    kind: "primitive",
    purpose: "Fifth, near-neutral data series.",
    consumers: "Charts.",
    usage: "Part of the 26 chart occurrences.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`dataviz/series-5`.",
    figma: "Color variable / Dataviz / Series 5.",
    migration: "Direct mapping.",
  }),
];

const SIDEBAR: TokenSpec[] = [
  t({
    token: "--sidebar / --sidebar-foreground",
    value: "oklch(0.235 0.060 265) / oklch(0.95 0.006 265)",
    darkValue: "oklch(0.135 0.030 265) / oklch(0.92 0.006 265)",
    modes: "different",
    kind: "semantic",
    purpose: "Navy navigation rail and its ink.",
    consumers: "InternalShell rail and the sidebar primitive.",
    usage: "163 `sidebar` occurrences.",
    contrast: "Rail is dark in both modes, so it is effectively a fixed inverse region.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`navigation/rail-surface` and `navigation/rail-content`.",
    figma: "Color variable group / Navigation.",
    migration:
      "Represents an inverse context; Figma would model it as a scoped group rather than a third mode.",
  }),
  t({
    token: "--sidebar-primary / --sidebar-primary-foreground",
    value: "oklch(0.66 0.120 250) / oklch(0.16 0.045 265)",
    darkValue: "oklch(0.68 0.125 255) / unchanged",
    modes: "different",
    kind: "semantic",
    purpose: "Active navigation item.",
    consumers: "Sidebar active state.",
    usage: "Part of the 163 sidebar occurrences.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`navigation/active`.",
    figma: "Color variable / Navigation / Active.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--sidebar-accent / --sidebar-accent-foreground",
    value: "oklch(0.29 0.065 265) / oklch(0.95 0.006 265)",
    darkValue: "oklch(0.235 0.040 265) / unchanged",
    modes: "different",
    kind: "semantic",
    purpose: "Navigation hover surface.",
    consumers: "Sidebar hover state.",
    usage: "Part of the 163 sidebar occurrences.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`navigation/hover`.",
    figma: "Color variable / Navigation / Hover.",
    migration: "Direct mapping.",
  }),
  t({
    token: "--sidebar-border / --sidebar-ring",
    value: "oklch(1 0 0 / 0.09) / oklch(0.66 0.120 250)",
    darkValue: "oklch(1 0 0 / 0.08) / oklch(0.68 0.125 255)",
    modes: "different",
    kind: "semantic",
    purpose: "Rail separators and focus ring inside the inverse rail.",
    consumers: "Sidebar primitive.",
    usage: "Part of the 163 sidebar occurrences.",
    status: "CURRENT IMPLEMENTATION",
    futureRole: "`navigation/line` and `navigation/focus-ring`.",
    figma: "Color variable / Navigation / Line.",
    migration:
      "Proves that focus ring colour is context-dependent; a single global ring variable cannot serve the rail.",
  }),
];

export const COLOR_FOUNDATION: TokenSpecGroup[] = [
  {
    id: "cf-canvas",
    title: "Canvas, surfaces and ink",
    summary:
      "The neutral ladder: canvas, sunken surface, inset panel, raised card, overlay, and the ink paired with each.",
    tokens: CANVAS,
  },
  {
    id: "cf-brand",
    title: "Brand, action and accent",
    summary:
      "Primary navy, its soft and foreground pairs, secondary, sage accent, muted, hover accent and the compatibility aliases.",
    tokens: BRAND,
  },
  {
    id: "cf-status",
    title: "Status colours",
    summary:
      "Destructive, warning, info and success as declared. Two of the four are not redefined for dark mode.",
    tokens: STATUS,
  },
  {
    id: "cf-lines",
    title: "Lines, controls and focus",
    summary: "Border, strong border, hairline, input border and focus ring.",
    tokens: LINES,
  },
  {
    id: "cf-dataviz",
    title: "Chart colours",
    summary: "Five data-series tokens, three of which duplicate a semantic token's value.",
    tokens: DATAVIZ,
  },
  {
    id: "cf-sidebar",
    title: "Navigation rail",
    summary:
      "The sidebar family behaves as a self-contained inverse context with its own surface, ink, active, hover, line and ring.",
    tokens: SIDEBAR,
  },
];

export const COLOR_TOKEN_COUNT = COLOR_FOUNDATION.reduce((n, g) => n + g.tokens.length, 0);
