/**
 * Phase 5 — complete component inventory.
 *
 * DOCUMENTATION ONLY. Nothing here is imported by application screens or
 * business logic; `/design-system` and `/design-guide` are the only readers.
 *
 * Every consumer count was measured by import path across `src/` with the
 * component's own folder and the two reference pages excluded. Where a count
 * cannot be established reliably the entry says so instead of guessing.
 */
import type { AnatomyEntry, ComponentGroup, FoundationCategory, RelationshipGroup } from "./types";

/* ---------------------------------------------------------------- taxonomy */

export const COMPONENT_TAXONOMY: FoundationCategory = {
  id: "component-taxonomy",
  title: "Component taxonomy",
  summary:
    "Fifteen categories. Each discovered component is filed under exactly one. Where the category is genuinely arguable the entry records the ambiguity rather than forcing a choice.",
  entries: [
    {
      name: "FOUNDATION PRIMITIVE",
      value: "Low-level control with no product meaning",
      source: "src/components/ui/*",
      consumers: "Separator, Skeleton, Spinner, Slot-based Button base",
      ownership: "primitive",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "FORM CONTROL",
      value: "Collects or edits a value",
      source: "src/components/ui/*, route-local field kits",
      consumers: "Input, Textarea, Select, Checkbox, RadioGroup, Switch, Slider, Label",
      ownership: "primitive",
      shared: "source-of-truth",
      maturity: "current",
      note: "OBSERVED OVERLAP — m06/kit.tsx and lucie-app/ui.tsx each define their own Field/TextInput/Picker.",
    },
    {
      name: "ACTION",
      value: "Triggers something",
      source: "ui/button.tsx, abox/action-pill.ts, abox/save-continue-button.tsx",
      consumers: "Button, ButtonGroup, ACTION_PILL class set, SaveContinueButton",
      ownership: "primitive",
      shared: "source-of-truth",
      maturity: "current",
      note: "ACTION_PILL is class strings only — no element or DOM contract.",
    },
    {
      name: "DISPLAY",
      value: "Presents a value or label, non-interactive",
      source: "abox/status-badge.tsx, abox/metal-badge.tsx, ui/badge.tsx, abox/overflow-text.tsx",
      consumers: "StatusBadge, MetalBadge, Badge, OverflowText",
      ownership: "business",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "CONTAINER",
      value: "Surface that holds other content",
      source: "ui/card.tsx plus recurring route markup",
      consumers: "Card family; the rounded-2xl border bg-card surface has no component owner",
      ownership: "pattern",
      shared: "convention",
      maturity: "current",
      note: "UNOWNED AREA — the dominant card surface is markup, not a component.",
    },
    {
      name: "DATA",
      value: "Renders a record set or a measured number",
      source: "abox/data-table.tsx, abox/kpi-card.tsx, ui/chart.tsx",
      consumers: "DataTable, KpiCard; Chart is installed with no consumer",
      ownership: "business",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "NAVIGATION",
      value: "Moves between destinations",
      source: "the three shells, abox/module-tabs.tsx, ui/tabs.tsx",
      consumers: "Shell rails and headers, ModuleTabs, Tabs",
      ownership: "business",
      shared: "source-of-truth",
      maturity: "current",
      note: "Breadcrumb, Pagination and NavigationMenu primitives exist with no consumer.",
    },
    {
      name: "OVERLAY",
      value: "Renders above the page in a layer",
      source: "ui/dialog.tsx, sheet.tsx, drawer.tsx, popover.tsx, tooltip.tsx, dropdown-menu.tsx",
      consumers: "Dialog, Sheet, DropdownMenu, Tooltip, Popover, HoverCard, Command",
      ownership: "primitive",
      shared: "source-of-truth",
      maturity: "current",
      note: "OBSERVED OVERLAP — m06/kit.tsx exports its own Sheet alongside ui/sheet.tsx.",
    },
    {
      name: "FEEDBACK",
      value: "Reports state of the system to the person",
      source:
        "ui/sonner.tsx, skeleton.tsx, progress.tsx, spinner.tsx, alert.tsx, abox/empty-state.tsx",
      consumers: "Toaster, Skeleton, Progress, Spinner, Alert, EmptyState",
      ownership: "primitive",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "COMMERCE",
      value: "Plan, product, cart and marketplace UI",
      source:
        "abox/plan-card.tsx, product-switcher.tsx, shopping-path-bar.tsx, quote-edit-panel.tsx",
      consumers: "Shopping and marketplace routes only",
      ownership: "business",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "BRAND",
      value: "Identity marks",
      source: "abox/logo.tsx, abox/carrier-mark.tsx",
      consumers: "AboxMark, AboxWordmark, CarrierMark",
      ownership: "business",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "SHELL",
      value: "Whole-page frame: header, rail, main region",
      source: "abox/internal-shell.tsx, member-shell.tsx, marketplace-shell.tsx",
      consumers: "123 route files across the three experiences",
      ownership: "business",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "PATTERN",
      value: "Recognisable multi-component composition",
      source: "route markup and the m06/m08 screen kits",
      consumers: "Filter rail, results toolbar, wizard, meta rail, trace rail",
      ownership: "pattern",
      shared: "convention",
      maturity: "current",
    },
    {
      name: "SPECIALIZED",
      value: "Deliberately application-specific, not a system candidate",
      source: "abox/downline-wizard-stepper.tsx, suspended-marketplace-notice.tsx, m08/*",
      consumers: "One flow or one module each",
      ownership: "local",
      shared: "one-off",
      maturity: "current",
    },
    {
      name: "REFERENCE ONLY",
      value: "Documentation rendering, never shipped in a product screen",
      source: "src/components/design/reference-kit.tsx",
      consumers: "/design-system and /design-guide only",
      ownership: "local",
      shared: "one-off",
      maturity: "current",
      note: "GOVERNANCE RULE — reference-kit must never be imported by an application screen.",
    },
  ],
};

/* --------------------------------------------------------- abox inventory */

export const ABOX_COMPONENTS: ComponentGroup = {
  id: "abox-components",
  title: "ABox business components",
  summary:
    "27 modules under src/components/abox plus the decor folder. Each is the single owner of its pattern; screens compose these rather than re-implementing them.",
  entries: [
    {
      name: "InternalShell",
      source: "abox/internal-shell.tsx",
      category: "shell",
      kind: "composition",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "89",
      consumerDetail: "Direct: every /app, /agency, /marketplace/admin and /platform route.",
      experience: "Dashboard / Admin",
      dependencies: "Sheet, DropdownMenu, Link, AboxMark, decor, nav-config",
      children: "Rail, header, search control, skip link, account menu, main region",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "StatusBadge",
      source: "abox/status-badge.tsx",
      category: "display",
      kind: "component",
      layer: "production",
      scope: "core-shared",
      consumers: "89",
      consumerDetail:
        "Direct: routes across all three experiences. Indirect: PlanCard, filter rail, DataTable cells.",
      experience: "Multi-experience",
      dependencies: "cn, colour-mix on --tone",
      children: "Dot + label",
      maturity: "CENTRALIZED",
      status: "in-use",
      note: "The most widely shared non-shell component in the product.",
    },
    {
      name: "ACTION_PILL",
      source: "abox/action-pill.ts",
      category: "action",
      kind: "layout-helper",
      layer: "production",
      scope: "core-shared",
      consumers: "35",
      consumerDetail: "Direct: 35 files, 82 measured key references.",
      experience: "Multi-experience",
      dependencies: "None — plain class strings",
      children: "None; the consumer supplies the element",
      maturity: "PARTIALLY CENTRALIZED",
      status: "in-use",
      note: "OBSERVED OVERLAP with the Button primitive: both express a filled and a bordered action.",
    },
    {
      name: "MarketplaceShell",
      source: "abox/marketplace-shell.tsx",
      category: "shell",
      kind: "composition",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "30",
      consumerDetail: "Direct: landing, plans, cart, compare, coverage, apply, review, auth.",
      experience: "Web / Marketing + Shopping",
      dependencies: "Link, AboxMark, DropdownMenu, product icons, cart-store",
      children: "Full-width header, product nav, cart control, account control, footer",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "PageHeader",
      source: "abox/page-header.tsx",
      category: "navigation",
      kind: "component",
      layer: "production",
      scope: "multi-experience",
      consumers: "25",
      consumerDetail: "Direct: admin and shopping routes.",
      experience: "Dashboard / Admin + Shopping",
      dependencies: "FadeRise (motion), Lucide icon prop",
      children: "Eyebrow, SCR id, icon, title, description, actions slot, hairline rule",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "DataTable",
      source: "abox/data-table.tsx",
      category: "data",
      kind: "component",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "20",
      consumerDetail: "Direct: admin and agency list screens.",
      experience: "Dashboard / Admin",
      dependencies: "cn only",
      children: "Wrapper, caption, head, row, cell, empty row, hover edge",
      maturity: "CENTRALIZED",
      status: "in-use",
      note: "OBSERVED DUPLICATE — lucie/ui.tsx Table and lucie-app/ui.tsx DataTable are separate implementations of the same idea.",
    },
    {
      name: "KpiCard",
      source: "abox/kpi-card.tsx",
      category: "data",
      kind: "component",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "18",
      consumerDetail: "Direct: dashboards and module landing screens.",
      experience: "Dashboard / Admin",
      dependencies: "CountUp (motion), Lucide icon prop",
      children: "Label, metric, delta, hint, icon, bracket decoration, sheen",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "EmptyState",
      source: "abox/empty-state.tsx",
      category: "feedback",
      kind: "component",
      layer: "production",
      scope: "multi-experience",
      consumers: "10",
      consumerDetail: "Direct: list and result screens in both admin and shopping.",
      experience: "Multi-experience",
      dependencies: "decor, Lucide icon prop",
      children: "Icon frame, title, body, action slot",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "DownlineWizardStepper",
      source: "abox/downline-wizard-stepper.tsx",
      category: "specialized",
      kind: "component",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "8",
      consumerDetail: "Direct: the eight agency/downlines/new steps.",
      experience: "Dashboard / Admin",
      dependencies: "downline-wizard-store, Link",
      children: "Step marker, label, connector",
      maturity: "EXPERIENCE-SPECIFIC",
      status: "in-use",
    },
    {
      name: "PlanCard",
      source: "abox/plan-card.tsx",
      category: "commerce",
      kind: "composition",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "6",
      consumerDetail: "Direct: plans, compare, coverage, select.",
      experience: "Shopping / Marketplace",
      dependencies: "CarrierMark, StatusBadge, MetalBadge, OverflowText, Button",
      children: "Mark, title, badges, price, actions; stacked and horizontal layouts",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "DownlineContextBanner",
      source: "abox/downline-context-banner.tsx",
      category: "feedback",
      kind: "component",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "6",
      consumerDetail: "Direct: downline wizard steps.",
      experience: "Dashboard / Admin",
      dependencies: "downline-wizard-store",
      children: "Context line, present/absent states",
      maturity: "EXPERIENCE-SPECIFIC",
      status: "in-use",
    },
    {
      name: "Logo (AboxMark, AboxWordmark)",
      source: "abox/logo.tsx",
      category: "brand",
      kind: "component",
      layer: "production",
      scope: "core-shared",
      consumers: "5 direct + 1 internal",
      consumerDetail: "Direct: all three shells, landing, branding screen. Internal: quote screen.",
      experience: "Multi-experience",
      dependencies: "None — inline token-driven SVG",
      children: "Disc mark, optional wordmark",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "MetalBadge",
      source: "abox/metal-badge.tsx",
      category: "commerce",
      kind: "component",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "4",
      consumerDetail: "Direct: plans filter rail, cart, compare. Indirect: PlanCard.",
      experience: "Shopping / Marketplace",
      dependencies: "Metal tier tokens",
      children: "Solid fill + paired foreground",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "MemberShell",
      source: "abox/member-shell.tsx",
      category: "shell",
      kind: "composition",
      layer: "production",
      scope: "multi-experience",
      consumers: "4",
      consumerDetail: "Direct: the /member routes.",
      experience: "Member portal",
      dependencies: "Link, AboxMark, Lucide icons",
      children: "Full-width header, icon nav with connecting arc, 88rem content region",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "CarrierMark",
      source: "abox/carrier-mark.tsx",
      category: "brand",
      kind: "component",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "3",
      consumerDetail: "Direct: cart, plan tiles. Indirect: PlanCard.",
      experience: "Shopping / Marketplace",
      dependencies: "Deterministic hue derivation",
      children: "Tinted disc + initial monogram",
      maturity: "CENTRALIZED",
      status: "in-use",
      note: "Documented as an illustrative placeholder, not a real carrier logo system.",
    },
    {
      name: "SaveContinueButton",
      source: "abox/save-continue-button.tsx",
      category: "action",
      kind: "component",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "3",
      consumerDetail: "Direct: wizard and settings screens.",
      experience: "Dashboard / Admin",
      dependencies: "Button",
      children: "Label with idle / saving / saved states",
      maturity: "SHARED",
      status: "in-use",
    },
    {
      name: "SuspendedMarketplaceNotice",
      source: "abox/suspended-marketplace-notice.tsx",
      category: "feedback",
      kind: "component",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "2",
      consumerDetail: "Direct: unavailable routes.",
      experience: "Shopping / Marketplace",
      dependencies: "marketplace-store",
      children: "Single state notice",
      maturity: "EXPERIENCE-SPECIFIC",
      status: "in-use",
    },
    {
      name: "ShoppingPathBar",
      source: "abox/shopping-path-bar.tsx",
      category: "commerce",
      kind: "component",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "2",
      consumerDetail: "Direct: plans and journey routes.",
      experience: "Shopping / Marketplace",
      dependencies: "shopping-mode store",
      children: "Guide me / Browse myself selection",
      maturity: "EXPERIENCE-SPECIFIC",
      status: "in-use",
    },
    {
      name: "ModuleTabs",
      source: "abox/module-tabs.tsx",
      category: "navigation",
      kind: "component",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "2",
      consumerDetail: "Direct: module landing screens.",
      experience: "Dashboard / Admin",
      dependencies: "Link",
      children: "Tab list, active and inactive item",
      maturity: "SHARED",
      status: "in-use",
      note: "OBSERVED OVERLAP with the installed ui/tabs.tsx primitive.",
    },
    {
      name: "QuoteEditPanel",
      source: "abox/quote-edit-panel.tsx",
      category: "commerce",
      kind: "composition",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "1",
      consumerDetail: "Direct: shared quote surface used by plans and cart.",
      experience: "Shopping / Marketplace",
      dependencies: "quote-store, Input, Select, Button",
      children: "Open/closed panel, fields, apply and cancel",
      maturity: "SHARED",
      status: "in-use",
    },
    {
      name: "ProductSwitcher",
      source: "abox/product-switcher.tsx",
      category: "commerce",
      kind: "component",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "1",
      consumerDetail: "Direct: the shopping product strip.",
      experience: "Shopping / Marketplace",
      dependencies: "product-store, products.ts icon map, cart-store",
      children: "Product chips with icons, active state",
      maturity: "SHARED",
      status: "in-use",
    },
    {
      name: "FadeRise / Stagger / StaggerItem / CountUp",
      source: "abox/motion.tsx",
      category: "foundation-primitive",
      kind: "wrapper",
      layer: "production",
      scope: "core-shared",
      consumers: "1 direct",
      consumerDetail: "Indirect: reaches most screens through PageHeader and KpiCard.",
      experience: "Multi-experience",
      dependencies: "framer-motion",
      children: "Motion wrapper around arbitrary children",
      maturity: "CENTRALIZED",
      status: "in-use",
      note: "Direct import count understates reach — this is an indirect-consumer component.",
    },
    {
      name: "OverflowText",
      source: "abox/overflow-text.tsx",
      category: "display",
      kind: "component",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "1",
      consumerDetail: "Indirect: reaches the plan list and cart through PlanCard.",
      experience: "Shopping / Marketplace",
      dependencies: "ResizeObserver",
      children: "Truncated label with hover/focus reveal",
      maturity: "SHARED",
      status: "internal-only",
    },
    {
      name: "Decor (Aurora, DotField, OrbitalRings, RadialTicks, CoverageWeave, BlueprintGrid and ~14 more)",
      source: "abox/decor/index.tsx",
      category: "display",
      kind: "component",
      layer: "production",
      scope: "web-marketing",
      consumers: "1 file",
      consumerDetail:
        "Direct: src/routes/index.tsx only. Indirect: EmptyState and the shells use a small subset.",
      experience: "Web / Marketing",
      dependencies: "None — inline SVG",
      children: "Background decoration",
      maturity: "PARTIALLY CENTRALIZED",
      status: "in-use",
      note: "POSSIBLY UNUSED — several exports (CornerCrop, TickerRule, MarqueeSerial, IsoStack, GlassPanel, PolicyLines, FamilySilhouette) have no located consumer; HairlineGrid, ConcentricArcs and DiagonalWeave are compatibility aliases of other exports.",
    },
    {
      name: "ThemeToggle",
      source: "abox/theme-toggle.tsx",
      category: "action",
      kind: "component",
      layer: "production",
      scope: "specialized-local",
      consumers: "0",
      consumerDetail: "No located consumer.",
      experience: "—",
      dependencies: "Button, Lucide icons",
      children: "Light / dark toggle",
      maturity: "INSTALLED BUT UNUSED",
      status: "installed-unused",
      note: "The toggle was intentionally removed from the UI; the file remains. Do not delete in this phase.",
    },
    {
      name: "PlanAiAssistant",
      source: "abox/planai-assistant.tsx",
      category: "commerce",
      kind: "composition",
      layer: "production",
      scope: "specialized-local",
      consumers: "0",
      consumerDetail: "No located route consumer. Sole importer of src/components/ai-elements/*.",
      experience: "Shopping / Marketplace",
      dependencies: "ai-elements conversation, message, prompt-input, shimmer",
      children: "Thread, composer, open/closed panel",
      maturity: "POSSIBLY UNUSED",
      status: "possibly-unused",
      note: "OBSERVED DUPLICATE — coexists with plan-o-assistant.tsx. Consolidation is behavioural, not styling; deferred.",
    },
    {
      name: "PlanOAssistant",
      source: "abox/plan-o-assistant.tsx",
      category: "commerce",
      kind: "composition",
      layer: "production",
      scope: "specialized-local",
      consumers: "0",
      consumerDetail: "No located route consumer.",
      experience: "Shopping / Marketplace",
      dependencies: "Button, Input, Lucide icons",
      children: "Thread, composer, open/closed panel",
      maturity: "POSSIBLY UNUSED",
      status: "possibly-unused",
      note: "Second implementation of the same conceptual assistant.",
    },
    {
      name: "PlaceholderScreen",
      source: "abox/placeholder-screen.tsx",
      category: "feedback",
      kind: "component",
      layer: "production",
      scope: "specialized-local",
      consumers: "0",
      consumerDetail: "No located consumer.",
      experience: "—",
      dependencies: "AboxMark",
      children: "Single state",
      maturity: "INSTALLED BUT UNUSED",
      status: "installed-unused",
    },
  ],
};

/* ----------------------------------------------------- primitive inventory */

export const UI_PRIMITIVES: ComponentGroup = {
  id: "ui-primitives",
  title: "shadcn/UI primitive inventory",
  summary:
    "49 primitives under src/components/ui. 29 have at least one production consumer; 20 are installed with none. Counts exclude the two reference pages, which import a further handful for demonstration only.",
  entries: [
    {
      name: "Button",
      source: "ui/button.tsx",
      category: "action",
      kind: "primitive",
      layer: "production",
      scope: "core-shared",
      consumers: "22",
      consumerDetail: "Direct: routes and ABox components across all experiences.",
      experience: "Multi-experience",
      dependencies: "cva, Radix Slot",
      children: "Icon slot via [&_svg]:size-4, label",
      maturity: "CENTRALIZED",
      status: "in-use",
      note: "Owns focus ring, disabled behaviour and icon sizing for every action that uses it.",
    },
    {
      name: "Select",
      source: "ui/select.tsx",
      category: "form-control",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "7",
      consumerDetail: "Direct: sort controls, quote fields, admin filters.",
      experience: "Shopping + Dashboard",
      dependencies: "Radix Select",
      children: "Trigger, value, content, item",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "Input",
      source: "ui/input.tsx",
      category: "form-control",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "7",
      consumerDetail: "Direct: quote panel, auth, admin forms.",
      experience: "Shopping + Dashboard",
      dependencies: "cn",
      children: "Single control; aria-invalid styling",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "Card family",
      source: "ui/card.tsx",
      category: "container",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "6",
      consumerDetail: "Direct: a small set of screens.",
      experience: "Dashboard + Shopping",
      dependencies: "cn",
      children: "Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter",
      maturity: "PARTIALLY CENTRALIZED",
      status: "in-use",
      note: "OBSERVED VARIATION — most surfaces use raw rounded-2xl border bg-card markup instead of this primitive.",
    },
    {
      name: "Label",
      source: "ui/label.tsx",
      category: "form-control",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "5",
      consumerDetail: "Direct: form screens.",
      experience: "Dashboard + Shopping",
      dependencies: "Radix Label",
      children: "Text with peer-disabled handling",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "Skeleton",
      source: "ui/skeleton.tsx",
      category: "feedback",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "4",
      consumerDetail: "Direct: loading regions.",
      experience: "Dashboard + Shopping",
      dependencies: "cn, animate-shimmer",
      children: "Block",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "Dialog",
      source: "ui/dialog.tsx",
      category: "overlay",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "4",
      consumerDetail: "Direct: confirmation and detail overlays.",
      experience: "Dashboard + Shopping",
      dependencies: "Radix Dialog",
      children: "Overlay, content, header, title, description, footer, close",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "Tooltip",
      source: "ui/tooltip.tsx",
      category: "overlay",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "4",
      consumerDetail: "Direct: icon-adjacent explanations.",
      experience: "Dashboard + Shopping",
      dependencies: "Radix Tooltip",
      children: "Provider, trigger, content",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "Tabs",
      source: "ui/tabs.tsx",
      category: "navigation",
      kind: "primitive",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "3",
      consumerDetail: "Direct: admin detail screens.",
      experience: "Dashboard / Admin",
      dependencies: "Radix Tabs",
      children: "List, trigger, content",
      maturity: "SHARED",
      status: "in-use",
      note: "OBSERVED OVERLAP with abox/module-tabs.tsx.",
    },
    {
      name: "Textarea",
      source: "ui/textarea.tsx",
      category: "form-control",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "3",
      consumerDetail: "Direct: note and message fields.",
      experience: "Dashboard + Shopping",
      dependencies: "cn",
      children: "Single control",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "Sheet",
      source: "ui/sheet.tsx",
      category: "overlay",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "3",
      consumerDetail: "Direct: mobile navigation rail, filter drawer.",
      experience: "Dashboard + Shopping",
      dependencies: "Radix Dialog",
      children: "Side panel, overlay, header, close with sr-only label",
      maturity: "CENTRALIZED",
      status: "in-use",
      note: "OBSERVED DUPLICATE — m06/kit.tsx exports an unrelated component also named Sheet.",
    },
    {
      name: "DropdownMenu",
      source: "ui/dropdown-menu.tsx",
      category: "overlay",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "3",
      consumerDetail: "Direct: account control in the shells.",
      experience: "Multi-experience",
      dependencies: "Radix DropdownMenu",
      children: "Trigger, content, item, separator, label",
      maturity: "CENTRALIZED",
      status: "in-use",
    },
    {
      name: "Separator",
      source: "ui/separator.tsx",
      category: "foundation-primitive",
      kind: "primitive",
      layer: "production",
      scope: "multi-experience",
      consumers: "2",
      consumerDetail: "Direct: two screens. Most rules are border-hairline markup instead.",
      experience: "Dashboard",
      dependencies: "Radix Separator",
      children: "Rule",
      maturity: "PARTIALLY CENTRALIZED",
      status: "in-use",
    },
    {
      name: "Switch, Drawer, Checkbox, Alert, Toggle, Spinner, Sonner, Slider, RadioGroup, Progress, Popover, InputGroup, HoverCard, Command, ButtonGroup, Badge",
      source: "ui/*",
      category: "foundation-primitive",
      kind: "primitive",
      layer: "production",
      scope: "specialized-local",
      consumers: "1 each",
      consumerDetail: "Each has exactly one production consumer today.",
      experience: "Varies by consumer",
      dependencies: "Radix or local",
      children: "Primitive defaults",
      maturity: "SHARED",
      status: "in-use",
      note: "Sonner is mounted once in routes/__root.tsx and triggered from cart-store.",
    },
    {
      name: "Accordion, AlertDialog, AspectRatio, Avatar, Breadcrumb, Calendar, Carousel, Chart, Collapsible, ContextMenu, Form, InputOTP, Menubar, NavigationMenu, Pagination, Resizable, ScrollArea, Sidebar, Table, ToggleGroup",
      source: "ui/*",
      category: "foundation-primitive",
      kind: "primitive",
      layer: "production",
      scope: "specialized-local",
      consumers: "0",
      consumerDetail: "No production consumer located for any of these 20.",
      experience: "—",
      dependencies: "Radix or local",
      children: "Primitive defaults",
      maturity: "INSTALLED BUT UNUSED",
      status: "installed-unused",
      note: "Installed, themed and ready. Table is unused because tables render through ABox DataTable. Chart is unused although chart-1…5 tokens exist. No deletion in this phase.",
    },
  ],
};

/* ---------------------------------------------- shells, icons, route-local */

export const SHELL_AND_LOCAL_COMPONENTS: ComponentGroup = {
  id: "shell-local-components",
  title: "Shell, icon and route-local component inventory",
  summary:
    "The three page frames, the one icon component, and the reusable kits that live outside src/components/ui and src/components/abox. The kits are real reusable components — they are simply owned by a module rather than by the design system.",
  entries: [
    {
      name: "Three shells (Internal, Marketplace, Member)",
      source: "abox/internal-shell.tsx, marketplace-shell.tsx, member-shell.tsx",
      category: "shell",
      kind: "composition",
      layer: "production",
      scope: "core-shared",
      consumers: "123 combined",
      consumerDetail: "Every route renders inside exactly one of the three.",
      experience: "All",
      dependencies: "Link, AboxMark, DropdownMenu, Sheet, nav-config, decor",
      children: "Header, navigation, account control, main region, skip link",
      maturity: "CENTRALIZED",
      status: "in-use",
      note: "The page frame is the single most consumed pattern in the product.",
    },
    {
      name: "ToothIcon",
      source: "components/icons/tooth-icon.tsx",
      category: "display",
      kind: "wrapper",
      layer: "production",
      scope: "shopping-marketplace",
      consumers: "1 direct",
      consumerDetail:
        "Direct: src/lib/products.ts icon map. Indirect: every product chip, header and plate that renders the dental product.",
      experience: "Shopping / Marketplace",
      dependencies: "@tabler/icons-react IconDental",
      children: "forwardRef SVG with aria-hidden",
      maturity: "SHARED",
      status: "in-use",
      note: "The only file importing @tabler/icons-react — see the Phase 4 iconography findings.",
    },
    {
      name: "M06 kit (StatusTag, Btn, Field, TextInput, TextArea, Picker, StateBlock, QueryBlock, Sheet, MetaRail, Toast and helpers)",
      source: "components/m06/kit.tsx",
      category: "pattern",
      kind: "composition",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "M06 screens and routes",
      consumerDetail:
        "Direct: the m06/screens modules and the agency workforce routes. Not imported outside M06.",
      experience: "Dashboard / Admin",
      dependencies: "cn, local Tone type",
      children: "Its own field, button, tag, sheet and state primitives",
      maturity: "EXPERIENCE-SPECIFIC",
      status: "in-use",
      note: "OBSERVED OVERLAP — Btn overlaps Button and ACTION_PILL, StatusTag overlaps StatusBadge, Sheet overlaps ui/sheet.tsx, Field/TextInput/Picker overlap the form primitives.",
    },
    {
      name: "M08 kit (OutcomeTag, DimensionStrip, ProvenanceChip, ContextRibbon, BlockerCard, TraceRail, ReviewModeBanner, M13Dependency, LoadingRows, EmptyRows, M08Section, LanguageToggle)",
      source: "components/m08/kit.tsx",
      category: "specialized",
      kind: "composition",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "M08 screens",
      consumerDetail: "Direct: m08/screens.tsx and m08/selling-setup.tsx.",
      experience: "Dashboard / Admin",
      dependencies: "m08 model and strings, local locale context",
      children: "Governed outcome, dimension, provenance and trace UI",
      maturity: "EXPERIENCE-SPECIFIC",
      status: "in-use",
      note: "Genuinely module-specific: the four controlled outcomes and status dimensions are governed concepts, not generic display.",
    },
    {
      name: "Lucie kit (Id, IdList, Tag, PostureTag, Section, PageHead, Stat, KV, Table, Toolbar, Select, Search, Note)",
      source: "components/lucie/ui.tsx",
      category: "pattern",
      kind: "composition",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "Lucie traceability screens",
      consumerDetail: "Direct: the Lucie spine routes.",
      experience: "Dashboard / Admin",
      dependencies: "cn, local Tone type",
      children: "Its own table, toolbar, select and search",
      maturity: "DUPLICATED",
      status: "in-use",
      note: "OBSERVED DUPLICATE — Table duplicates DataTable, PageHead duplicates PageHeader, Select duplicates ui/select.tsx.",
    },
    {
      name: "Lucie-app kit (PageHeader, Section, StatCard, StatusChip, DataTable, EmptyState, LoadingRows, Stepper, Field, Money, NotPermitted)",
      source: "components/lucie-app/ui.tsx, frames.tsx",
      category: "pattern",
      kind: "composition",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "Lucie prototype walkthrough screens",
      consumerDetail: "Direct: the lucie-app frames and steps.",
      experience: "Dashboard / Admin",
      dependencies: "lucie-app store and data",
      children: "Its own header, table, stat card, chip, stepper, empty and loading states",
      maturity: "DUPLICATED",
      status: "in-use",
      note: "OBSERVED DUPLICATE — the clearest parallel implementation set: PageHeader, DataTable, EmptyState and StatCard all duplicate ABox components by name and by purpose.",
    },
    {
      name: "M06 screen common (PersonPicker, FilterBar, TextFilter, DefinitionCard, CategoryTag, useProfiles, useTextFilter)",
      source: "components/m06/screens/common.tsx",
      category: "pattern",
      kind: "composition",
      layer: "production",
      scope: "dashboard-admin",
      consumers: "M06 screen modules",
      consumerDetail: "Direct: roster, access, lifecycle, dataops, readiness, structure.",
      experience: "Dashboard / Admin",
      dependencies: "m06 kit",
      children: "Filter bar, person picker, definition card",
      maturity: "EXPERIENCE-SPECIFIC",
      status: "in-use",
      note: "PATTERN CANDIDATE — the filter bar recurs outside M06 as route markup with no owner.",
    },
    {
      name: "AI elements (PromptInput family, Conversation, Message, Shimmer)",
      source: "components/ai-elements/*",
      category: "specialized",
      kind: "composition",
      layer: "production",
      scope: "specialized-local",
      consumers: "1",
      consumerDetail:
        "Direct: abox/planai-assistant.tsx only, which itself has no located route consumer.",
      experience: "Shopping / Marketplace",
      dependencies: "Radix, ui primitives",
      children: "Composer, attachments, action menu, submit, thread",
      maturity: "POSSIBLY UNUSED",
      status: "possibly-unused",
      note: "Reachable only through a component with no located consumer — flagged, not removed.",
    },
    {
      name: "Reference kit (RefPage, RefContainer, RefSection, RefBlock, RefStage, RefToc, Swatch, MetaChip, OwnershipChip and the audit tables)",
      source: "components/design/reference-kit.tsx",
      category: "reference-only",
      kind: "composition",
      layer: "reference",
      scope: "reference-only",
      consumers: "2",
      consumerDetail: "Reference-only: /design-system and /design-guide.",
      experience: "Reference layer",
      dependencies: "Production tokens and a few ui primitives for live examples",
      children: "Documentation layout and table renderers",
      maturity: "CENTRALIZED",
      status: "reference-only",
      note: "GOVERNANCE RULE — never import this from an application screen.",
    },
  ],
};

export const COMPONENT_GROUPS: ComponentGroup[] = [
  ABOX_COMPONENTS,
  UI_PRIMITIVES,
  SHELL_AND_LOCAL_COMPONENTS,
];

/* ------------------------------------------------------------- consumer map */

export const CONSUMER_MAP: RelationshipGroup = {
  id: "consumer-map",
  title: "Consumer map",
  summary:
    "Measured by import path across src/, excluding each component's own folder and the two reference pages. Direct means the file imports it; indirect means it renders through another component.",
  entries: [
    {
      pair: "InternalShell → routes",
      observed: "89 direct route consumers across /app, /agency, /marketplace/admin, /platform",
      source: "abox/internal-shell.tsx",
      consistency: "consistent",
    },
    {
      pair: "StatusBadge → routes and components",
      observed: "89 direct files; indirect through PlanCard, the plans filter rail and table cells",
      source: "abox/status-badge.tsx",
      consistency: "consistent",
    },
    {
      pair: "ACTION_PILL → routes",
      observed: "35 direct files, 82 key references; primaryMd (21) and outlineXs (11) dominate",
      source: "abox/action-pill.ts",
      consistency: "consistent",
    },
    {
      pair: "Button → routes and ABox components",
      observed: "22 direct files; also the icon-size contract for every icon inside it",
      source: "ui/button.tsx",
      consistency: "consistent",
    },
    {
      pair: "Motion → screens",
      observed: "1 direct import, but indirect reach through PageHeader (25) and KpiCard (18)",
      source: "abox/motion.tsx",
      consistency: "consistent",
      note: "A direct count alone would misrepresent this component.",
    },
    {
      pair: "OverflowText → plan surfaces",
      observed: "0 route imports; reaches the plan list and cart only through PlanCard",
      source: "abox/overflow-text.tsx",
      consistency: "consistent",
    },
    {
      pair: "ToothIcon → product surfaces",
      observed: "1 direct import (products.ts); indirect on every dental product chip",
      source: "components/icons/tooth-icon.tsx",
      consistency: "consistent",
    },
    {
      pair: "Reference kit → pages",
      observed: "Reference-only: 2 consumers, both documentation routes",
      source: "components/design/reference-kit.tsx",
      consistency: "consistent",
    },
    {
      pair: "Module kits → module screens",
      observed:
        "M06, M08, Lucie and Lucie-app kits are each imported only within their own module tree",
      source: "components/m06, m08, lucie, lucie-app",
      consistency: "consistent",
      note: "Module-scoped by construction, which is why the duplication was never noticed at runtime.",
    },
    {
      pair: "Unused primitives → nothing",
      observed: "20 of 49 ui primitives have no located production import",
      source: "src/components/ui",
      consistency: "varies",
      note: "INSTALLED BUT UNUSED — confidence is high; the search covered every import spelling used in this codebase.",
    },
  ],
};

/* ----------------------------------------------------------------- anatomy */

export const COMPONENT_ANATOMY: AnatomyEntry[] = [
  {
    component: "Button",
    source: "ui/button.tsx",
    parts: [
      "Interaction area — h-9 default, h-8 sm, h-10 lg, h-9 w-9 icon, h-8 w-8 icon-sm",
      "Optional leading or trailing SVG, forced to size-4 and pointer-events-none",
      "Label at text-sm font-medium (text-xs at sm)",
      "Focus ring — focus-visible:ring-1 ring-ring",
      "No loading part: loading is expressed by the consumer, not the primitive",
    ],
  },
  {
    component: "PageHeader",
    source: "abox/page-header.tsx",
    parts: [
      "Eyebrow / masthead label",
      "Optional SCR identifier",
      "Optional leading icon",
      "Title",
      "Optional description",
      "Actions slot",
      "Hairline underline",
      "FadeRise entrance wrapper",
    ],
    note: "Compact variant shrinks the block; the title size was raised in an earlier approved change.",
  },
  {
    component: "KpiCard",
    source: "abox/kpi-card.tsx",
    parts: [
      "Label",
      "Metric, rolled in with CountUp",
      "Optional delta indicator",
      "Optional hint",
      "Optional icon",
      "Hover lift, corner brackets and edge sheen decoration",
    ],
  },
  {
    component: "DataTable",
    source: "abox/data-table.tsx",
    parts: [
      "Rounded hairline wrapper with horizontal scroll",
      "sr-only caption",
      "Uppercase serial header row",
      "Body rows with hairline dividers",
      "Cells with left / right / center alignment, right using tabular-nums",
      "Empty row spanning all columns",
      "Ember left-border that scales in on row hover",
    ],
    note: "No toolbar and no pagination part — toolbars are route markup and nothing is paginated today.",
  },
  {
    component: "PlanCard",
    source: "abox/plan-card.tsx",
    parts: [
      "CarrierMark (36px stacked, 34px horizontal, 30px compact)",
      "Plan title with OverflowText",
      "MetalBadge",
      "StatusBadge row — network, exchange, HSA",
      "Plan identifier",
      "Price block",
      "Action row — details, save, compare, add",
      "Optional best-match indicator and subsidised price",
    ],
  },
  {
    component: "StatusBadge",
    source: "abox/status-badge.tsx",
    parts: [
      "aria-hidden dot, 6px, filled with --tone",
      "Label text at 88% tone mixed with foreground",
      "Border at 34% tone",
      "Background at 12% tone over card",
    ],
    note: "Always rendered at full opacity — a deliberate earlier decision.",
  },
  {
    component: "EmptyState",
    source: "abox/empty-state.tsx",
    parts: [
      "h-12 w-12 rounded-md hairline icon frame on background",
      "h-5 w-5 primary glyph, aria-hidden",
      "Title",
      "Optional body",
      "Optional action",
    ],
  },
  {
    component: "Card family",
    source: "ui/card.tsx",
    parts: ["Card", "CardHeader", "CardTitle", "CardDescription", "CardContent", "CardFooter"],
    note: "OBSERVED VARIATION — most product surfaces skip this and write the card markup inline.",
  },
  {
    component: "Dialog",
    source: "ui/dialog.tsx",
    parts: [
      "Overlay",
      "Content",
      "Header → Title → Description",
      "Body",
      "Footer",
      "Close with an sr-only label",
    ],
  },
  {
    component: "Form field (as actually assembled)",
    source: "ui/label.tsx + ui/input.tsx + route markup",
    parts: [
      "Label",
      "Control",
      "Optional helper text",
      "Error text at text-xs text-destructive",
      "aria-invalid on the control",
    ],
    note: "UNOWNED AREA — there is no Field component in the shared layer; ui/form.tsx is installed but unused and the module kits each define their own Field.",
  },
  {
    component: "Shell navigation",
    source: "abox/internal-shell.tsx",
    parts: [
      "Shell frame",
      "Nav group",
      "Nav item → icon + label",
      "Active state",
      "Collapsed rail / expanded rail / mobile Sheet",
      "Sticky header with search and account control",
      "Skip link",
    ],
    note: "No badge part on nav items today.",
  },
];

/* ------------------------------------- composition vs component classification */

export const COMPOSITION_CLASSIFICATION: RelationshipGroup = {
  id: "composition-classification",
  title: "Composition vs component classification",
  summary:
    "Important for a future Figma architecture: not everything reusable should become a Figma component, and not everything repeated should become a production component.",
  entries: [
    {
      pair: "REUSABLE COMPONENT",
      observed:
        "StatusBadge, MetalBadge, CarrierMark, KpiCard, DataTable, EmptyState, PageHeader, ModuleTabs, SaveContinueButton, OverflowText",
      source: "src/components/abox",
      consistency: "consistent",
    },
    {
      pair: "PRIMITIVE",
      observed: "The 49 shadcn modules — they own focus, keyboard and disabled behaviour",
      source: "src/components/ui",
      consistency: "consistent",
    },
    {
      pair: "WRAPPER",
      observed: "ToothIcon around Tabler IconDental; FadeRise / Stagger around framer-motion",
      source: "components/icons, abox/motion.tsx",
      consistency: "consistent",
    },
    {
      pair: "LAYOUT HELPER",
      observed: "ACTION_PILL — class strings with no element contract",
      source: "abox/action-pill.ts",
      consistency: "consistent",
    },
    {
      pair: "REUSABLE COMPOSITION",
      observed: "PlanCard, QuoteEditPanel, the three shells, the M06/M08/Lucie kits",
      source: "abox and module kits",
      consistency: "consistent",
    },
    {
      pair: "REPEATED MARKUP",
      observed:
        "The rounded-2xl border bg-card surface, the section heading block, the results toolbar, the filter chip row",
      source: "route files",
      consistency: "varies",
      note: "PATTERN CANDIDATE — centralising any of these would risk visual change, so all are deferred.",
    },
    {
      pair: "PAGE-LOCAL",
      observed: "The plans filter rail and results toolbar, the compare column layout",
      source: "src/routes/plans.index.tsx, compare.tsx",
      consistency: "consistent",
      note: "Single consumer each; intentionally local.",
    },
    {
      pair: "PATTERN",
      observed: "Page frame, page title block, action pill row, wizard, empty state",
      source: "Documented in the Phase 1 pattern inventory",
      consistency: "consistent",
    },
  ],
};

/* ------------------------------------------------- duplication and overlap */

export const DUPLICATION_FINDINGS = [
  "OBSERVED DUPLICATE — Table implementations: abox/data-table.tsx, lucie/ui.tsx Table and lucie-app/ui.tsx DataTable are three separate renderers of the same concept. They differ in column API, density and empty-state handling, so none is a drop-in replacement for another. No winner is chosen here.",
  "OBSERVED DUPLICATE — PageHeader: abox/page-header.tsx, lucie/ui.tsx PageHead and lucie-app/ui.tsx PageHeader. The ABox version carries the eyebrow, SCR id and FadeRise entrance the others lack.",
  "OBSERVED DUPLICATE — EmptyState: abox/empty-state.tsx and lucie-app/ui.tsx EmptyState. The ABox version has the icon frame; the Lucie-app version is text-only.",
  "OBSERVED DUPLICATE — Assistant: abox/planai-assistant.tsx and abox/plan-o-assistant.tsx are two implementations of the same conceptual panel, and neither has a located route consumer.",
  "OBSERVED DUPLICATE — Sheet: ui/sheet.tsx (Radix side panel) and m06/kit.tsx Sheet (a module-local panel) share a name but not a purpose. The name collision is the finding, not the behaviour.",
  "OBSERVED OVERLAP — Action treatment: ui/button.tsx and abox/action-pill.ts both express a filled and a bordered action. Button is rounded-md, the pill is rounded-full; they are visually distinct and both are intentional today.",
  "OBSERVED OVERLAP — Status vocabulary: StatusBadge accepts sage, primary, warning, muted, destructive, info; m06/kit.tsx Tone accepts neutral, good, warn, stop, info; lucie-app/ui.tsx ChipTone is a third vocabulary. Fifteen distinct tone values were measured across the codebase for what is conceptually one scale.",
  "OBSERVED OVERLAP — Tabs: ui/tabs.tsx and abox/module-tabs.tsx. ModuleTabs is link-based navigation; Tabs is in-page panel switching. The overlap is visual, not behavioural.",
  "OBSERVED OVERLAP — Form fields: ui/input.tsx + ui/label.tsx, m06/kit.tsx Field/TextInput/TextArea/Picker, and lucie-app/ui.tsx Field are three field systems. ui/form.tsx is installed and used by none of them.",
  "POSSIBLE LEGACY — abox/theme-toggle.tsx and abox/placeholder-screen.tsx have no located consumer; the theme toggle was intentionally removed from the UI.",
  "POSSIBLE LEGACY — decor exports HairlineGrid, ConcentricArcs and DiagonalWeave are aliases of other exports, which reads as backwards compatibility from an earlier iteration.",
  "FUTURE CONSOLIDATION OPPORTUNITY — every item above is recorded only. Consolidating any of them would re-render live screens and is out of scope for an inventory phase.",
];

export const UNUSED_FINDINGS = [
  "INSTALLED BUT UNUSED (high confidence) — 20 of 49 ui primitives have no production import: Accordion, AlertDialog, AspectRatio, Avatar, Breadcrumb, Calendar, Carousel, Chart, Collapsible, ContextMenu, Form, InputOTP, Menubar, NavigationMenu, Pagination, Resizable, ScrollArea, Sidebar, Table, ToggleGroup.",
  "INSTALLED BUT UNUSED (high confidence) — abox/theme-toggle.tsx and abox/placeholder-screen.tsx.",
  "POSSIBLY UNUSED (medium confidence) — abox/planai-assistant.tsx, abox/plan-o-assistant.tsx and the whole src/components/ai-elements tree, which is reachable only through PlanAiAssistant. These may be intentionally parked for a future release rather than dead.",
  "POSSIBLY UNUSED (medium confidence) — several decor exports: CornerCrop, TickerRule, MarqueeSerial, IsoStack, GlassPanel, PolicyLines, FamilySilhouette. They are exported from a barrel file, so a missed dynamic reference cannot be fully ruled out.",
  "INSTALLED BUT UNUSED variants — Button variant 'default' is never written explicitly (it is the default), and no measured consumer passes size='default'. Badge is imported once and its secondary, destructive and outline variants have no located consumer.",
  "INSTALLED BUT UNUSED states — DataTable supports onRowClick and a caption; both are used by only a small subset of consumers. KpiCard's warning tone has no located consumer.",
  "FUTURE OPPORTUNITY — chart-1…5 tokens exist with no chart; Breadcrumb, Pagination and Avatar primitives exist with no screen that needs them yet. These are capability gaps waiting on a feature, not defects.",
];

export const COMPONENT_MATURITY = [
  {
    area: "Page frame",
    state: "CENTRALIZED",
    detail: "Three shells cover 123 routes. No route builds its own header or rail.",
  },
  {
    area: "Status display",
    state: "CENTRALIZED in the shared layer, DUPLICATED at module level",
    detail:
      "StatusBadge owns the shared treatment; M06, M08 and Lucie each ship a parallel tag with a different tone vocabulary.",
  },
  {
    area: "Actions",
    state: "PARTIALLY CENTRALIZED",
    detail:
      "Button owns behaviour, ACTION_PILL owns the pill treatment, and m06/kit.tsx Btn is a third path.",
  },
  {
    area: "Data tables",
    state: "DUPLICATED",
    detail: "Three implementations, each with its own column API.",
  },
  {
    area: "Card surface",
    state: "UNOWNED",
    detail:
      "The dominant surface is inline markup; ui/card.tsx has six consumers and the border token varies between border and hairline.",
  },
  {
    area: "Form fields",
    state: "UNOWNED",
    detail: "No shared Field component; ui/form.tsx is installed but unused.",
  },
  {
    area: "Commerce UI",
    state: "CENTRALIZED",
    detail:
      "PlanCard, MetalBadge, CarrierMark, ProductSwitcher and ShoppingPathBar each own their pattern.",
  },
  {
    area: "Brand marks",
    state: "CENTRALIZED",
    detail: "AboxMark, AboxWordmark and CarrierMark are the only mark implementations.",
  },
  {
    area: "Overlays",
    state: "SHARED",
    detail: "Radix-backed, primitive-owned, consistent focus and keyboard behaviour.",
  },
  {
    area: "Feedback",
    state: "PARTIALLY CENTRALIZED",
    detail:
      "EmptyState and Skeleton are shared; loading has no single convention and each module kit ships its own LoadingRows.",
  },
  {
    area: "Navigation beyond the shells",
    state: "REPEATED",
    detail: "ModuleTabs and Tabs coexist; breadcrumbs and pagination have no consumer at all.",
  },
  {
    area: "Module kits",
    state: "EXPERIENCE-SPECIFIC and UNDOCUMENTED until now",
    detail:
      "M06, M08, Lucie and Lucie-app kits were never part of the documented component layer. Phase 5 records them.",
  },
  {
    area: "Reference layer",
    state: "CENTRALIZED",
    detail: "reference-kit.tsx is the single renderer for both documentation pages.",
  },
];
