/**
 * Phase 5 — variant and size inventory.
 *
 * DOCUMENTATION ONLY. Variant names are recorded exactly as written in
 * production code. Nothing here renames, normalizes or consolidates a variant.
 * Usage figures were measured by prop occurrence across `src/`, excluding the
 * defining file and the two reference pages.
 */
import type { DimensionEntry, VariantEntry } from "./types";

export const COMPONENT_VARIANTS: VariantEntry[] = [
  {
    component: "Button",
    property: "variant",
    values: "default, destructive, outline, secondary, ghost, link",
    used: "outline (18), ghost (11), secondary (2), destructive (2), link (1)",
    unused: "default is never written explicitly — it is the cva default and is applied implicitly",
    consumers: "22 files across all three experiences",
    source: "ui/button.tsx",
    note: "OBSERVED VARIATION — outline and ghost carry most of the load; the filled default arrives implicitly, so a variant audit by prop alone under-reports it.",
  },
  {
    component: "Button",
    property: "size",
    values: "default (h-9), sm (h-8), lg (h-10), icon (h-9 w-9), icon-sm (h-8 w-8)",
    used: "sm (12), icon (5), icon-sm (3), lg (1)",
    unused: "default is never passed explicitly",
    consumers: "22 files",
    source: "ui/button.tsx",
    note: "Cross-reference Phase 2: h-8/h-9/h-10 are the same control ladder the pills use.",
  },
  {
    component: "ACTION_PILL",
    property: "key (class string, not a prop)",
    values:
      "primaryXs, primaryMd, primaryLg, outlineXs, outlineSm, outlineSmCard, outlineMd, outlineLg",
    used: "primaryMd (21), outlineXs (11), primaryLg (10), outlineLg (8), outlineSmCard (7), outlineSm (7), outlineMd (6), primaryXs (4)",
    unused: "None — every key has at least four consumers",
    consumers: "35 files, 82 key references",
    source: "abox/action-pill.ts",
    note: "The only ABox export where every declared variant is genuinely in use.",
  },
  {
    component: "StatusBadge",
    property: "tone",
    values: "sage, primary, warning, muted, destructive, info",
    used: "primary (34), muted (31), warning (29), sage (27), info (16), destructive (4)",
    unused: "None",
    consumers: "89 files",
    source: "abox/status-badge.tsx",
    note: "OBSERVED OVERLAP — a further nine tone values (warn, good, neutral, stop, bad, hairline, sidebar, foreground, default) belong to the module kits and the reference Swatch, not to StatusBadge.",
  },
  {
    component: "MetalBadge",
    property: "tier",
    values: "Bronze, Expanded Bronze, Silver, Gold, Platinum, Catastrophic",
    used: "All six render from live plan data",
    unused: "None",
    consumers: "4 direct + PlanCard",
    source: "abox/metal-badge.tsx",
    note: "Each tier is a solid token fill with a paired accessible foreground token. Preserved exactly — not a candidate for normalisation.",
  },
  {
    component: "KpiCard",
    property: "tone",
    values: "default, primary, sage, warning",
    used: "default, primary and sage appear on dashboards",
    unused: "POSSIBLY UNUSED — no located consumer passes warning",
    consumers: "18 files",
    source: "abox/kpi-card.tsx",
  },
  {
    component: "PageHeader",
    property: "variant",
    values: "default, compact",
    used: "Both; compact is the shopping results header",
    unused: "None",
    consumers: "25 files",
    source: "abox/page-header.tsx",
  },
  {
    component: "PageHeader",
    property: "optional slots",
    values: "eyebrow, scrId, icon, description, actions",
    used: "eyebrow and title on nearly every consumer; scrId on governed module screens",
    unused: "None, though scrId is module-specific",
    consumers: "25 files",
    source: "abox/page-header.tsx",
  },
  {
    component: "PlanCard",
    property: "layout and state flags",
    values:
      "compact, horizontal, inCart, inCompare, saved, isBestMatch, matchScore, subsidizedPrice",
    used: "All eight appear in the plans, compare and coverage screens",
    unused: "None",
    consumers: "6 files",
    source: "abox/plan-card.tsx",
    note: "Boolean flags rather than a single variant prop — an OBSERVED VARIATION against the cva pattern used by the primitives.",
  },
  {
    component: "Badge (primitive)",
    property: "variant",
    values: "default, secondary, destructive, outline",
    used: "Only the single importer's usage",
    unused: "POSSIBLY UNUSED — secondary, destructive and outline have no located consumer",
    consumers: "1 file",
    source: "ui/badge.tsx",
    note: "Product badges go through StatusBadge and MetalBadge instead.",
  },
  {
    component: "DataTable",
    property: "column align",
    values: "left (default), right, center",
    used: "left and right (right adds tabular-nums); center is rare",
    unused: "None confirmed unused",
    consumers: "20 files",
    source: "abox/data-table.tsx",
  },
  {
    component: "DataTable",
    property: "optional behaviour",
    values: "caption, empty, onRowClick, ariaLabel",
    used: "empty is common; onRowClick and caption are used by a subset",
    unused: "None",
    consumers: "20 files",
    source: "abox/data-table.tsx",
  },
  {
    component: "CarrierMark",
    property: "size",
    values: "Numeric pixel prop — 36 stacked, 34 horizontal, 30 compact",
    used: "All three within PlanCard and the cart",
    unused: "None",
    consumers: "3 direct + PlanCard",
    source: "abox/carrier-mark.tsx",
    note: "OBSERVED VARIATION — a numeric prop rather than a named size scale.",
  },
  {
    component: "AboxMark",
    property: "tone and size",
    values: "Four tones; size as a numeric prop, default 36",
    used: "Header, rail and landing usages",
    unused: "Not every tone has a located consumer",
    consumers: "5 files",
    source: "abox/logo.tsx",
  },
  {
    component: "M06 kit StatusTag",
    property: "tone (derived, not passed)",
    values: "neutral, good, warn, stop, info",
    used: "Derived from a value by statusTone()",
    unused: "None",
    consumers: "M06 screens and routes",
    source: "components/m06/kit.tsx",
    note: "OBSERVED OVERLAP with StatusBadge tone — a parallel vocabulary for the same idea.",
  },
  {
    component: "M08 kit OutcomeTag",
    property: "outcome",
    values: "Allowed, More Information Needed, Not Allowed, Not Applicable",
    used: "All four",
    unused: "None",
    consumers: "M08 screens",
    source: "components/m08/kit.tsx",
    note: "A governed enumeration, not a styling variant. Must not be folded into a generic tone scale.",
  },
];

export const COMPONENT_SIZES: DimensionEntry[] = [
  {
    element: "Button default",
    value: "h-9 (36px), px-4 py-2, text-sm",
    occurrences: "Implicit default on every Button without a size prop",
    source: "ui/button.tsx",
    ownership: "primitive",
  },
  {
    element: "Button sm",
    value: "h-8 (32px), px-3, text-xs",
    occurrences: "12 measured",
    source: "ui/button.tsx",
    ownership: "primitive",
  },
  {
    element: "Button lg",
    value: "h-10 (40px), px-8",
    occurrences: "1 measured",
    source: "ui/button.tsx",
    ownership: "primitive",
  },
  {
    element: "Button icon / icon-sm",
    value: "h-9 w-9 (36px) / h-8 w-8 (32px) square",
    occurrences: "5 / 3 measured",
    source: "ui/button.tsx",
    ownership: "primitive",
  },
  {
    element: "Icon inside any Button",
    value: "size-4 (16px), enforced by [&_svg]:size-4",
    occurrences: "Every Button consumer",
    source: "ui/button.tsx",
    ownership: "primitive",
    note: "Cross-reference Phase 4: h-4 w-4 is the dominant icon size product-wide (281 occurrences).",
  },
  {
    element: "ACTION_PILL heights",
    value: "xs h-8, sm h-9, md h-10, lg h-11",
    occurrences: "82 key references",
    source: "abox/action-pill.ts",
    ownership: "business",
    note: "OBSERVED VARIATION — the pill ladder reaches h-11 (44px); the Button ladder stops at h-10.",
  },
  {
    element: "ACTION_PILL padding and gap",
    value: "xs px-3 gap-1, sm px-3 gap-1.5, md px-4 gap-1.5, lg px-5/px-6 gap-1.5",
    occurrences: "82",
    source: "abox/action-pill.ts",
    ownership: "business",
    note: "primaryLg uses px-6 while outlineLg uses px-5 — recorded, not reconciled.",
  },
  {
    element: "StatusBadge dot",
    value: "h-1.5 w-1.5 (6px)",
    occurrences: "Every StatusBadge",
    source: "abox/status-badge.tsx",
    ownership: "business",
  },
  {
    element: "EmptyState icon frame / glyph",
    value: "h-12 w-12 (48px) frame, h-5 w-5 (20px) glyph",
    occurrences: "10 consumers",
    source: "abox/empty-state.tsx",
    ownership: "business",
  },
  {
    element: "CarrierMark",
    value: "36 / 34 / 30 px discs",
    occurrences: "PlanCard stacked, horizontal and compact",
    source: "abox/carrier-mark.tsx",
    ownership: "business",
  },
  {
    element: "AboxMark",
    value: "36px default",
    occurrences: "All shells",
    source: "abox/logo.tsx",
    ownership: "business",
    note: "36px is the shared control-and-mark footprint across the product.",
  },
  {
    element: "DataTable cell padding",
    value: "px-5 py-4; empty row px-5 py-10",
    occurrences: "20 consumers",
    source: "abox/data-table.tsx",
    ownership: "business",
    note: "Cross-reference Phase 2: two table densities were observed across the product.",
  },
  {
    element: "DataTable minimum width",
    value: "min-w-[640px] inside a horizontal scroll region",
    occurrences: "Every DataTable",
    source: "abox/data-table.tsx",
    ownership: "business",
  },
  {
    element: "Content container",
    value: "max-w-[88rem] centred on web-experience pages",
    occurrences: "23 measured",
    source: "Route markup and MemberShell",
    ownership: "pattern",
    note: "Cross-reference Phase 2. Dashboard pages were intentionally excluded from this width.",
  },
  {
    element: "Mobile touch target",
    value: "min-height 44px on buttons and links below 640px",
    occurrences: "Global rule",
    source: "src/styles.css",
    ownership: "foundation",
  },
];
