/**
 * Phase 11 — content readiness.
 * DOCUMENTATION ONLY. No product copy is changed. This records whether each
 * subject has a content model complete enough for a future component library.
 */
import type { ContentReadinessRecord } from "./canonical-readiness-types";

export const CONTENT_READINESS: ContentReadinessRecord[] = [
  {
    subject: "PageHeader",
    requiredContent: "Title.",
    optionalContent: "Eyebrow, description, icon, actions.",
    longTextBehavior: "Not specified; long titles are untested in the records.",
    emptyContent: "Not applicable — a header always has a title.",
    errorContent: "Not applicable.",
    loadingContent: "Not specified.",
    numericContent:
      "Counts appear in compact headers, for example the exact phrase Plan available.",
    bilingualNote: "Titles are translated; the compact count phrasing is fixed wording.",
    readiness: "READY FOR FUTURE DECISION",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    subject: "KpiCard",
    requiredContent: "Label and value.",
    optionalContent: "Delta, hint, icon.",
    longTextBehavior: "Not specified for long labels.",
    emptyContent: "No empty treatment recorded.",
    errorContent: "None.",
    loadingContent: "None; skeletons are applied by the screen where used.",
    numericContent: "Values and deltas are numeric and locale-sensitive.",
    bilingualNote: "Labels translated; numeric formatting follows the screen.",
    readiness: "READY FOR FUTURE DECISION",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    subject: "EmptyState",
    requiredContent: "Title.",
    optionalContent: "Icon, body, action.",
    longTextBehavior: "Body wraps; no truncation recorded.",
    emptyContent: "This is the empty treatment.",
    errorContent: "Not covered — error is a separate, unowned case.",
    loadingContent: "Not covered.",
    numericContent: "None.",
    bilingualNote: "Fully translated.",
    readiness: "READY FOR FUTURE DECISION",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    subject: "DataTable",
    requiredContent: "Column headers and rows.",
    optionalContent: "Empty message.",
    longTextBehavior:
      "Minimum width 640px with horizontal scroll; cells do not wrap into a card layout.",
    emptyContent: "Handled by the component.",
    errorContent: "Not covered.",
    loadingContent: "Not covered.",
    numericContent: "Numeric columns are common and alignment is set per screen.",
    bilingualNote: "Headers translated; column widths are not re-measured for longer translations.",
    readiness: "BLOCKED BY DUPLICATE",
    status: "OBSERVED DUPLICATE",
  },
  {
    subject: "PlanCard",
    requiredContent: "Plan name, carrier, metal tier, exchange status, plan id, premium.",
    optionalContent: "HSA marker, network type, carrier mark.",
    longTextBehavior: "Long plan names, carriers and ids truncate with an overflow affordance.",
    emptyContent: "Not applicable.",
    errorContent: "Not covered.",
    loadingContent: "Not covered.",
    numericContent: "Premiums formatted as $#,##0.00.",
    bilingualNote: "Labels translated; ICHRA is uppercase and premium formatting is fixed.",
    readiness: "READY FOR FUTURE DECISION",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    subject: "Cart summary",
    requiredContent: "Coverage rows and total.",
    optionalContent: "Add-ons section, continue action.",
    longTextBehavior: "Overflow handled on names, carriers and ids.",
    emptyContent: "Empty cart treatment exists.",
    errorContent: "Not covered.",
    loadingContent: "Not covered.",
    numericContent:
      "Total uses the same premium formatting; the word Illustrative was removed from it.",
    bilingualNote: "Cart and Cart · N are fixed label forms.",
    readiness: "READY FOR FUTURE DECISION",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    subject: "Form fields",
    requiredContent: "Label and control.",
    optionalContent: "Help text, error text.",
    longTextBehavior: "Not specified.",
    emptyContent: "Placeholder behaviour varies between the primitives and the route kits.",
    errorContent: "Error text exists in the route kits but not as a shared model.",
    loadingContent: "Not covered.",
    numericContent: "Numeric filters persist across navigation in shopping.",
    bilingualNote: "Governed module wording is controlled and must not be paraphrased.",
    readiness: "BLOCKED BY DUPLICATE",
    status: "OBSERVED DUPLICATE",
  },
  {
    subject: "Status and tier badges",
    requiredContent: "Label.",
    optionalContent: "None.",
    longTextBehavior: "Labels are short by convention; no truncation recorded.",
    emptyContent: "Not applicable.",
    errorContent: "Not applicable.",
    loadingContent: "Not applicable.",
    numericContent: "None.",
    bilingualNote: "Tier names such as Expanded Bronze are product terms.",
    readiness: "READY FOR FUTURE DECISION",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    subject: "Loading and error surfaces",
    requiredContent: "Unknown — no shared surface exists.",
    optionalContent: "Unknown.",
    longTextBehavior: "Unknown.",
    emptyContent: "Covered separately by EmptyState.",
    errorContent: "Written per route today.",
    loadingContent: "Skeleton blocks in 4 files.",
    numericContent: "None.",
    bilingualNote: "Per-route error wording is not centrally governed.",
    readiness: "NEEDS OWNER",
    status: "UNOWNED AREA",
  },
  {
    subject: "Marketing sections",
    requiredContent: "Heading and body.",
    optionalContent: "Icon, cards, entry pills.",
    longTextBehavior:
      "Headline sizes were deliberately reduced across pages in earlier approved work.",
    emptyContent: "Not applicable.",
    errorContent: "Not applicable.",
    loadingContent: "Not applicable.",
    numericContent: "Carrier counts are dynamic.",
    bilingualNote: "Fully translated; ICHRA stays uppercase.",
    readiness: "NEEDS OWNER",
    status: "UNOWNED AREA",
  },
];

export const CONTENT_RULES: string[] = [
  "GOVERNANCE RULE — no product copy is changed by this audit.",
  "GOVERNANCE RULE — fixed wording recorded here, such as Cart · N and Plan available, is a preserved product decision and not open for tidying.",
  "GOVERNANCE RULE — where long-text behaviour is unspecified, that is recorded rather than invented.",
  "GOVERNANCE RULE — governed module wording carries controlled identifiers and may not be paraphrased by a design change.",
  "GOVERNANCE RULE — a content model is complete when required, optional, empty, error, loading and long-text behaviour are all known.",
];
