/**
 * Phase 10 — experience patterns.
 * DOCUMENTATION ONLY. Experience ids come from the Phase 9 experience nodes;
 * this module adds the specification detail the graph did not carry.
 */
import type { ExperiencePatternSpec } from "./pattern-spec-types";
import { EXPERIENCE_NODES } from "./graph-experiences";

export const EXPERIENCES = EXPERIENCE_NODES;

export const EXPERIENCE_PATTERNS: ExperiencePatternSpec[] = [
  {
    experienceId: "exp.web",
    patternId: "pat.hero",
    purpose: "Open the public site with one claim and one obvious next step.",
    composition: "Viewport-aware centred section, split into copy and an illustrative panel.",
    variations: ["Headline steps across four breakpoints", "Hero action pills sit at h-11 rather than the standard pill height"],
    responsive: "Stacks at lg; the panel centres rather than right-aligning below md.",
    screens: ["/"],
    ownership: "Web / Marketing",
    status: "CURRENT IMPLEMENTATION",
    note: "The larger display typography is intentional, not a deviation to correct.",
  },
  {
    experienceId: "exp.web",
    patternId: "pat.section-header",
    purpose: "Signpost long marketing pages.",
    composition: "Eyebrow, h2 at text-4xl md:text-5xl, optional lead paragraph.",
    variations: ["Some sections use md:text-6xl instead"],
    responsive: "Type steps at md; no structural change.",
    screens: ["/"],
    ownership: "Unowned — repeated inline, no component",
    status: "UNOWNED AREA",
  },
  {
    experienceId: "exp.web",
    patternId: "pat.navigation",
    purpose: "Give visitors a light header with product entry points.",
    composition: "Sticky glass rounded-full header with brand, product links, cart and account.",
    variations: ["Links hide below md", "Cart shows a total only from sm"],
    responsive: "Links collapse at md; account label truncates from sm.",
    screens: ["/"],
    ownership: "Web / Marketing",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    experienceId: "exp.shop",
    patternId: "pat.filter-results",
    purpose: "Let a shopper narrow plans without leaving the results.",
    composition: "Compact header, w-64 filter rail, single-column results grid.",
    variations: ["Exchange filters deliberately show no selection ring", "Filter chips reuse the listing badge treatments"],
    responsive: "Rail becomes a dialog below lg.",
    screens: ["/plans"],
    ownership: "Shopping / Commerce",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    experienceId: "exp.shop",
    patternId: "pat.results-toolbar",
    purpose: "Keep the count and sorting above the results without pushing them down.",
    composition: "PageHeader compact variant carrying the count, sort and quote edit entry.",
    variations: ["Uses the compact header rather than a bespoke toolbar"],
    responsive: "Title steps at md; controls wrap.",
    screens: ["/plans"],
    ownership: "Shopping / Commerce",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    experienceId: "exp.shop",
    patternId: "pat.cart-summary",
    purpose: "Show selection and cost together.",
    composition: "Main column of coverage rows and add-ons beside a 360px summary.",
    variations: ["Add-ons block is visually strengthened relative to the surrounding rows"],
    responsive: "Stacks at lg; the header row stacks below sm.",
    screens: ["/cart"],
    ownership: "Shopping / Commerce",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    experienceId: "exp.shop",
    patternId: "pat.status-tier",
    purpose: "Make plan tier and exchange status readable at a glance.",
    composition: "Solid metal and status badges on tiles, in the cart and in filters.",
    variations: ["Expanded Bronze exists only in this experience"],
    responsive: "No change.",
    screens: ["/plans", "/cart"],
    ownership: "Shopping / Commerce",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    experienceId: "exp.shop",
    patternId: "pat.comparison",
    purpose: "Place selected plans side by side.",
    composition: "Route-local markup rather than the shared plan card.",
    variations: ["Does not reuse the plan card"],
    responsive: "Route-local.",
    screens: ["/compare"],
    ownership: "Shopping / Commerce",
    status: "OBSERVED VARIATION",
  },
  {
    experienceId: "exp.shop",
    patternId: "pat.assistant",
    purpose: "Offer guided shopping beside the plan results.",
    composition: "PlanAI surface with session-persisted state.",
    variations: ["Other assistant surfaces exist elsewhere with different composition"],
    responsive: "Route-local.",
    screens: ["/plans"],
    ownership: "Shopping / Commerce",
    status: "OBSERVED DUPLICATE",
  },
  {
    experienceId: "exp.dash",
    patternId: "pat.table-screen",
    purpose: "Present administrative records as comparable rows.",
    composition: "Page header, optional KPI row, then a table.",
    variations: ["Three table implementations", "Densities differ between them"],
    responsive: "Horizontal scroll rather than restructuring.",
    screens: ["/agency/my-organization"],
    ownership: "Dashboard / Admin",
    status: "OBSERVED DUPLICATE",
  },
  {
    experienceId: "exp.dash",
    patternId: "pat.kpi-grid",
    purpose: "Open a dashboard with headline numbers.",
    composition: "Grid of metric cards above the main content.",
    variations: ["Column counts differ by screen"],
    responsive: "Grid columns reduce with width.",
    screens: ["/agency/my-organization"],
    ownership: "Dashboard / Admin",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    experienceId: "exp.dash",
    patternId: "pat.wizard",
    purpose: "Guide a multi-step administrative task.",
    composition: "Step chips above the step content.",
    variations: [],
    responsive: "Chips wrap.",
    screens: ["/agency/my-organization"],
    ownership: "Dashboard / Admin",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    experienceId: "exp.dash",
    patternId: "pat.navigation",
    purpose: "Keep deep navigation permanently available to operators.",
    composition: "Fixed collapsible left rail with a sticky glass top bar and inline search.",
    variations: ["Rail collapses between 292px and 104px", "Search appears only from lg"],
    responsive: "Rail replaced by an 'Open navigation' button below lg.",
    screens: ["/agency/my-organization", "/app/jet/branding", "/marketplace/admin/assets"],
    ownership: "Dashboard / Admin",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    experienceId: "exp.member",
    patternId: "pat.settings-section",
    purpose: "Group account preferences inside a single panel.",
    composition: "Member header, vertical icon navigation, then a card panel of sections.",
    variations: ["Content sits at 88rem like the rest of the web experience"],
    responsive: "Navigation becomes a scrollable row below md.",
    screens: ["/member/settings"],
    ownership: "Member / Account",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    experienceId: "exp.member",
    patternId: "pat.navigation",
    purpose: "Offer a short list of account destinations.",
    composition: "Centred header plus an icon rail joined by a connecting arc.",
    variations: ["The arc is drawn through the centre of the 36px icon circles"],
    responsive: "Rail becomes a horizontally scrollable row below md.",
    screens: ["/member/settings"],
    ownership: "Member / Account",
    status: "CURRENT IMPLEMENTATION",
  },
];
