/**
 * Phase 9 — route-local kit and shell integration.
 * DOCUMENTATION ONLY. No kit or shell is modified, merged or rewritten.
 */
import type { DependencyEdge, DependencyNode, SpecLabel } from "./graph-types";

export const KIT_NODES: DependencyNode[] = [
  {
    id: "kit.m06",
    layer: "experience-pattern",
    name: "M06 kit",
    source: "src/components/m06",
    ownership: "local",
    status: "OBSERVED DUPLICATE",
    evidence: "Agency and agent profile screens",
  },
  {
    id: "kit.m06-common",
    layer: "experience-pattern",
    name: "M06 screen-common",
    source: "src/components/m06",
    ownership: "local",
    status: "OBSERVED DUPLICATE",
    evidence: "Shared blocks inside M06 only",
  },
  {
    id: "kit.m08",
    layer: "experience-pattern",
    name: "M08 kit",
    source: "src/components/m08",
    ownership: "local",
    status: "OBSERVED DUPLICATE",
    evidence: "Licensing and selling authority screens",
  },
  {
    id: "kit.lucie",
    layer: "experience-pattern",
    name: "Lucie kit",
    source: "src/components/lucie",
    ownership: "local",
    status: "OBSERVED DUPLICATE",
    evidence: "Traceability surfaces",
  },
  {
    id: "kit.lucie-app",
    layer: "experience-pattern",
    name: "Lucie app kit",
    source: "src/components/lucie-app",
    ownership: "local",
    status: "OBSERVED DUPLICATE",
    evidence: "Lucie application screens",
  },
  {
    id: "kit.ai",
    layer: "experience-pattern",
    name: "ai-elements",
    source: "src/components/ai-elements",
    ownership: "local",
    status: "FUTURE OPPORTUNITY",
    evidence: "Shared AI building blocks",
  },
];

export const SHELL_NODES: DependencyNode[] = [
  {
    id: "shell.internal",
    layer: "experience-pattern",
    name: "InternalShell",
    source: "src/components/abox/internal-shell.tsx",
    ownership: "business",
    status: "CURRENT IMPLEMENTATION",
    evidence: "89 files",
  },
  {
    id: "shell.marketplace",
    layer: "experience-pattern",
    name: "MarketplaceShell",
    source: "src/components/abox/marketplace-shell.tsx",
    ownership: "business",
    status: "CURRENT IMPLEMENTATION",
    evidence: "30 files",
  },
  {
    id: "shell.member",
    layer: "experience-pattern",
    name: "MemberShell",
    source: "src/components/abox/member-shell.tsx",
    ownership: "business",
    status: "CURRENT IMPLEMENTATION",
    evidence: "Member routes",
  },
];

export const KIT_EDGES: DependencyEdge[] = [
  {
    from: "kit.m06",
    to: "exp.dash",
    relation: "extends",
    status: "OBSERVED DUPLICATE",
    evidence: "M06 screens sit inside the internal experience",
    ownership: "Route-local",
  },
  {
    from: "kit.m06-common",
    to: "kit.m06",
    relation: "composes",
    status: "OBSERVED DUPLICATE",
    evidence: "Shared inside M06 only",
    ownership: "Route-local",
  },
  {
    from: "kit.m08",
    to: "exp.dash",
    relation: "extends",
    status: "OBSERVED DUPLICATE",
    evidence: "Governed credential screens",
    ownership: "Route-local",
  },
  {
    from: "kit.m08",
    to: "exp.shop",
    relation: "extends",
    status: "CURRENT IMPLEMENTATION",
    evidence: "Selling setup surfaces embedded in agent profiles",
    ownership: "Route-local",
    note: "Recorded because the module spans both experiences.",
  },
  {
    from: "kit.lucie",
    to: "exp.dash",
    relation: "extends",
    status: "OBSERVED DUPLICATE",
    evidence: "Lucie surfaces",
    ownership: "Route-local",
  },
  {
    from: "kit.lucie-app",
    to: "exp.dash",
    relation: "extends",
    status: "OBSERVED DUPLICATE",
    evidence: "Lucie application shell",
    ownership: "Route-local",
  },
  {
    from: "kit.ai",
    to: "pat.assistant",
    relation: "composes",
    status: "FUTURE OPPORTUNITY",
    evidence: "Shared AI blocks without a contract",
    ownership: "Route-local",
  },
  {
    from: "cmp.status-badge",
    to: "kit.m08",
    relation: "consumes",
    status: "CURRENT IMPLEMENTATION",
    evidence: "Governed status presentation uses shared badges",
    ownership: "ABox",
  },
  {
    from: "shell.internal",
    to: "exp.dash",
    relation: "owns",
    status: "CURRENT IMPLEMENTATION",
    evidence: "89 files",
    ownership: "Shell",
  },
  {
    from: "shell.marketplace",
    to: "exp.shop",
    relation: "owns",
    status: "CURRENT IMPLEMENTATION",
    evidence: "30 files",
    ownership: "Shell",
  },
  {
    from: "shell.member",
    to: "exp.member",
    relation: "owns",
    status: "CURRENT IMPLEMENTATION",
    evidence: "Member routes",
    ownership: "Shell",
  },
  {
    from: "role.container",
    to: "shell.marketplace",
    relation: "consumes",
    status: "CURRENT IMPLEMENTATION",
    evidence: "Full-width header, 88rem content",
    ownership: "Shell",
  },
  {
    from: "role.container",
    to: "shell.member",
    relation: "consumes",
    status: "CURRENT IMPLEMENTATION",
    evidence: "Full-width header, 88rem content",
    ownership: "Shell",
  },
  {
    from: "role.surface",
    to: "shell.internal",
    relation: "consumes",
    status: "CURRENT IMPLEMENTATION",
    evidence: "Sidebar and canvas surfaces",
    ownership: "Shell",
  },
  {
    from: "pat.navigation",
    to: "shell.internal",
    relation: "composes",
    status: "OBSERVED OVERLAP",
    evidence: "Own sidebar rather than the primitive",
    ownership: "Shell",
  },
  {
    from: "pat.navigation",
    to: "shell.marketplace",
    relation: "composes",
    status: "OBSERVED OVERLAP",
    evidence: "Own header navigation",
    ownership: "Shell",
  },
  {
    from: "pat.navigation",
    to: "shell.member",
    relation: "composes",
    status: "OBSERVED OVERLAP",
    evidence: "36px icon circles on a centred arc",
    ownership: "Shell",
  },
];

export const KIT_ARCHITECTURE_RULES: { rule: string; status: SpecLabel }[] = [
  {
    rule: "ABox Core → experience extension → route-local kit. Dependencies point one way; core never imports from a kit.",
    status: "FUTURE CANONICAL TARGET",
  },
  {
    rule: "Route-local kits are legitimate. Local is not a defect; it becomes one only when the same thing is rebuilt a third time.",
    status: "GOVERNANCE RULE",
  },
  {
    rule: "Kits stay exactly as they ship. Nothing is merged, moved or rewritten by this graph.",
    status: "GOVERNANCE RULE",
  },
  {
    rule: "A kit that already consumes a shared component keeps that edge visible, so partial sharing is not mistaken for full duplication.",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    rule: "Shells stay separate. A shared shell contract would describe landmarks, header height and content offset only.",
    status: "FUTURE CANONICAL TARGET",
  },
];
