/**
 * Phase 9 — component role → implementation edges, and the consumer graph.
 * DOCUMENTATION ONLY. Consumer counts are reused verbatim from the Phase 5
 * measurements. Nothing is estimated, and reference-page usage is never
 * counted as production consumption.
 */
import type { ConsumerReference, DependencyEdge, DependencyNode } from "./graph-types";

export const COMPONENT_NODES: DependencyNode[] = [
  { id: "cmp.button", layer: "core-component", name: "Button", source: "src/components/ui/button.tsx", ownership: "primitive", status: "CURRENT IMPLEMENTATION", evidence: "22 direct files" },
  { id: "cmp.action-pill", layer: "core-component", name: "ACTION_PILL", source: "src/components/abox/action-pill.ts", ownership: "business", status: "OBSERVED OVERLAP", evidence: "35 files, 82 references" },
  { id: "cmp.m06-btn", layer: "core-component", name: "Route-local action helper", source: "src/components/m06", ownership: "local", status: "OBSERVED OVERLAP", evidence: "M06 screens" },
  { id: "cmp.input", layer: "core-component", name: "Input", source: "src/components/ui/input.tsx", ownership: "primitive", status: "CURRENT IMPLEMENTATION", evidence: "7 direct files" },
  { id: "cmp.select", layer: "core-component", name: "Select", source: "src/components/ui/select.tsx", ownership: "primitive", status: "CURRENT IMPLEMENTATION", evidence: "7 direct files" },
  { id: "cmp.label", layer: "core-component", name: "Label", source: "src/components/ui/label.tsx", ownership: "primitive", status: "CURRENT IMPLEMENTATION", evidence: "5 direct files" },
  { id: "cmp.form", layer: "core-component", name: "Form field set", source: "src/components/ui/form.tsx", ownership: "primitive", status: "OBSERVED DUPLICATE", evidence: "react-hook-form screens" },
  { id: "cmp.card", layer: "core-component", name: "Card", source: "src/components/ui/card.tsx", ownership: "primitive", status: "CURRENT IMPLEMENTATION", evidence: "6 direct files" },
  { id: "cmp.status-badge", layer: "core-component", name: "StatusBadge", source: "src/components/abox/status-badge.tsx", ownership: "business", status: "CURRENT IMPLEMENTATION", evidence: "89 files" },
  { id: "cmp.badge", layer: "core-component", name: "Badge", source: "src/components/ui/badge.tsx", ownership: "primitive", status: "OBSERVED OVERLAP", evidence: "Primitive with limited direct use" },
  { id: "cmp.metal-badge", layer: "core-component", name: "MetalBadge", source: "src/components/abox/metal-badge.tsx", ownership: "business", status: "CURRENT IMPLEMENTATION", evidence: "Tiles, detail and filters" },
  { id: "cmp.table", layer: "core-component", name: "Table primitive", source: "src/components/ui/table.tsx", ownership: "primitive", status: "OBSERVED DUPLICATE", evidence: "Used directly by some screens" },
  { id: "cmp.data-table", layer: "core-component", name: "DataTable", source: "src/components/abox/data-table.tsx", ownership: "business", status: "OBSERVED DUPLICATE", evidence: "20 files" },
  { id: "cmp.page-header", layer: "core-component", name: "PageHeader", source: "src/components/abox/page-header.tsx", ownership: "business", status: "OBSERVED DUPLICATE", evidence: "25 files" },
  { id: "cmp.dialog", layer: "core-component", name: "Dialog", source: "src/components/ui/dialog.tsx", ownership: "primitive", status: "CURRENT IMPLEMENTATION", evidence: "4 direct files" },
  { id: "cmp.sheet", layer: "core-component", name: "Sheet", source: "src/components/ui/sheet.tsx", ownership: "primitive", status: "OBSERVED OVERLAP", evidence: "Name collides with the product term; overlaps Drawer" },
  { id: "cmp.alert", layer: "core-component", name: "Alert", source: "src/components/ui/alert.tsx", ownership: "primitive", status: "CURRENT IMPLEMENTATION", evidence: "Primitive" },
  { id: "cmp.toast", layer: "core-component", name: "Toaster", source: "src/components/ui/sonner.tsx", ownership: "primitive", status: "CURRENT IMPLEMENTATION", evidence: "Mounted once in the root route" },
  { id: "cmp.empty-state", layer: "core-component", name: "EmptyState", source: "src/components/abox/empty-state.tsx", ownership: "business", status: "OBSERVED DUPLICATE", evidence: "10 files" },
  { id: "cmp.skeleton", layer: "core-component", name: "Skeleton", source: "src/components/ui/skeleton.tsx", ownership: "primitive", status: "CURRENT IMPLEMENTATION", evidence: "4 direct files" },
  { id: "cmp.kpi-card", layer: "core-component", name: "KpiCard", source: "src/components/abox/kpi-card.tsx", ownership: "business", status: "CURRENT IMPLEMENTATION", evidence: "18 files" },
  { id: "cmp.plan-card", layer: "core-component", name: "PlanCard", source: "src/components/abox/plan-card.tsx", ownership: "business", status: "CURRENT IMPLEMENTATION", evidence: "6 files" },
  { id: "cmp.carrier-mark", layer: "core-component", name: "CarrierMark", source: "src/components/abox/carrier-mark.tsx", ownership: "business", status: "OBSERVED VARIATION", evidence: "Deterministic illustrative monogram" },
  { id: "cmp.tabs", layer: "core-component", name: "Tabs", source: "src/components/ui/tabs.tsx", ownership: "primitive", status: "OBSERVED OVERLAP", evidence: "ModuleTabs provides a second presentation" },
  { id: "cmp.module-tabs", layer: "core-component", name: "ModuleTabs", source: "src/components/abox/module-tabs.tsx", ownership: "business", status: "OBSERVED OVERLAP", evidence: "Module screens" },
  { id: "cmp.button-group", layer: "core-component", name: "ButtonGroup", source: "src/components/ui/button-group.tsx", ownership: "primitive", status: "POSSIBLY UNUSED", evidence: "Available primitive with few direct consumers" },
  { id: "cmp.context-menu", layer: "core-component", name: "ContextMenu", source: "src/components/ui/context-menu.tsx", ownership: "primitive", status: "POSSIBLY UNUSED", evidence: "Primitive present, little adoption" },
  { id: "cmp.sidebar", layer: "core-component", name: "Sidebar primitive", source: "src/components/ui/sidebar.tsx", ownership: "primitive", status: "POSSIBLY UNUSED", evidence: "Shells implement their own navigation" },
  { id: "cmp.tooth-icon", layer: "core-component", name: "ToothIcon", source: "src/components/icons", ownership: "business", status: "OBSERVED VARIATION", evidence: "Only Tabler import in the codebase" },
  { id: "cmp.fontawesome", layer: "core-component", name: "Font Awesome", source: "package.json", ownership: "none", status: "INSTALLED BUT UNUSED", evidence: "Zero imports" },
];

export const COMPONENT_EDGES: DependencyEdge[] = [
  { from: "crole.primary-action", to: "cmp.button", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "22 direct files", ownership: "Primitive" },
  { from: "crole.primary-action", to: "cmp.action-pill", relation: "implements", status: "OBSERVED OVERLAP", evidence: "35 files, 82 references", ownership: "ABox", note: "A second implementation of the same role. Recorded, not ranked." },
  { from: "crole.primary-action", to: "cmp.m06-btn", relation: "implements", status: "OBSERVED OVERLAP", evidence: "M06 screens", ownership: "Route-local" },
  { from: "crole.secondary-action", to: "cmp.button", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "outline and secondary variants", ownership: "Primitive" },
  { from: "crole.destructive-action", to: "cmp.button", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "destructive variant", ownership: "Primitive" },
  { from: "crole.input-control", to: "cmp.input", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "7 direct files", ownership: "Primitive" },
  { from: "crole.input-control", to: "cmp.select", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "7 direct files", ownership: "Primitive" },
  { from: "crole.field-label", to: "cmp.label", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "5 direct files", ownership: "Primitive" },
  { from: "crole.field-label", to: "cmp.form", relation: "implements", status: "OBSERVED DUPLICATE", evidence: "form.tsx FormLabel", ownership: "Primitive" },
  { from: "crole.status-indicator", to: "cmp.status-badge", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "89 files", ownership: "ABox" },
  { from: "crole.status-indicator", to: "cmp.badge", relation: "implements", status: "OBSERVED OVERLAP", evidence: "Primitive badge variants", ownership: "Primitive" },
  { from: "crole.tier-indicator", to: "cmp.metal-badge", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "Tiles, detail and filters", ownership: "ABox" },
  { from: "crole.card-surface", to: "cmp.card", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "6 direct files", ownership: "Primitive" },
  { from: "crole.card-surface", to: "cmp.kpi-card", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "18 files", ownership: "ABox" },
  { from: "crole.data-surface", to: "cmp.table", relation: "implements", status: "OBSERVED DUPLICATE", evidence: "Primitive table markup", ownership: "Primitive" },
  { from: "crole.data-surface", to: "cmp.data-table", relation: "implements", status: "OBSERVED DUPLICATE", evidence: "20 files", ownership: "ABox" },
  { from: "crole.overlay-surface", to: "cmp.dialog", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "4 direct files", ownership: "Primitive" },
  { from: "crole.overlay-surface", to: "cmp.sheet", relation: "implements", status: "OBSERVED OVERLAP", evidence: "Overlaps Drawer in purpose", ownership: "Primitive" },
  { from: "crole.feedback-surface", to: "cmp.alert", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "Primitive", ownership: "Primitive" },
  { from: "crole.feedback-surface", to: "cmp.toast", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "Root route toaster", ownership: "Primitive" },
  { from: "crole.nav-surface", to: "cmp.tabs", relation: "implements", status: "OBSERVED OVERLAP", evidence: "Primitive tabs", ownership: "Primitive" },
  { from: "crole.nav-surface", to: "cmp.module-tabs", relation: "implements", status: "OBSERVED OVERLAP", evidence: "Module screens", ownership: "ABox" },
  { from: "crole.nav-surface", to: "cmp.sidebar", relation: "implements", status: "POSSIBLY UNUSED", evidence: "Shells do not consume it", ownership: "Primitive" },
  { from: "crole.loading-surface", to: "cmp.skeleton", relation: "implements", status: "CURRENT IMPLEMENTATION", evidence: "4 direct files", ownership: "Primitive" },
  { from: "crole.glyph-slot", to: "cmp.tooth-icon", relation: "implements", status: "OBSERVED VARIATION", evidence: "Single Tabler wrapper", ownership: "ABox" },
  { from: "crole.glyph-slot", to: "cmp.fontawesome", relation: "implements", status: "INSTALLED BUT UNUSED", evidence: "Installed, imported nowhere", ownership: "None" },
];

export const CONSUMER_GRAPH: ConsumerReference[] = [
  { component: "StatusBadge", source: "src/components/abox/status-badge.tsx", kind: "direct", measured: "89 files", status: "CURRENT IMPLEMENTATION" },
  { component: "InternalShell", source: "src/components/abox/internal-shell.tsx", kind: "direct", measured: "89 files", status: "CURRENT IMPLEMENTATION" },
  { component: "ACTION_PILL", source: "src/components/abox/action-pill.ts", kind: "direct", measured: "35 files, 82 references", status: "CURRENT IMPLEMENTATION" },
  { component: "MarketplaceShell", source: "src/components/abox/marketplace-shell.tsx", kind: "direct", measured: "30 files", status: "CURRENT IMPLEMENTATION" },
  { component: "PageHeader", source: "src/components/abox/page-header.tsx", kind: "direct", measured: "25 files", status: "CURRENT IMPLEMENTATION" },
  { component: "Button", source: "src/components/ui/button.tsx", kind: "direct", measured: "22 files", status: "CURRENT IMPLEMENTATION" },
  { component: "Button", source: "dialog.tsx, sheet.tsx, drawer.tsx", kind: "indirect", measured: "Reached through overlay primitives", status: "CURRENT IMPLEMENTATION", note: "Not added to the direct count." },
  { component: "DataTable", source: "src/components/abox/data-table.tsx", kind: "direct", measured: "20 files", status: "CURRENT IMPLEMENTATION" },
  { component: "KpiCard", source: "src/components/abox/kpi-card.tsx", kind: "direct", measured: "18 files", status: "CURRENT IMPLEMENTATION" },
  { component: "EmptyState", source: "src/components/abox/empty-state.tsx", kind: "direct", measured: "10 files", status: "CURRENT IMPLEMENTATION" },
  { component: "Input", source: "src/components/ui/input.tsx", kind: "direct", measured: "7 files", status: "CURRENT IMPLEMENTATION" },
  { component: "Select", source: "src/components/ui/select.tsx", kind: "direct", measured: "7 files", status: "CURRENT IMPLEMENTATION" },
  { component: "Card", source: "src/components/ui/card.tsx", kind: "direct", measured: "6 files", status: "CURRENT IMPLEMENTATION" },
  { component: "PlanCard", source: "src/components/abox/plan-card.tsx", kind: "direct", measured: "6 files", status: "CURRENT IMPLEMENTATION" },
  { component: "Label", source: "src/components/ui/label.tsx", kind: "direct", measured: "5 files", status: "CURRENT IMPLEMENTATION" },
  { component: "Skeleton", source: "src/components/ui/skeleton.tsx", kind: "direct", measured: "4 files", status: "CURRENT IMPLEMENTATION" },
  { component: "Dialog", source: "src/components/ui/dialog.tsx", kind: "direct", measured: "4 files", status: "CURRENT IMPLEMENTATION" },
  { component: "lucide-react", source: "npm package", kind: "direct", measured: "144 files, 149 distinct icons", status: "CURRENT IMPLEMENTATION" },
  { component: "M06 kit", source: "src/components/m06", kind: "route-local", measured: "Its own screens", status: "OBSERVED DUPLICATE" },
  { component: "M08 kit", source: "src/components/m08", kind: "route-local", measured: "Its own screens", status: "OBSERVED DUPLICATE" },
  { component: "Lucie and Lucie app kits", source: "src/components/lucie, lucie-app", kind: "route-local", measured: "Their own screens", status: "OBSERVED DUPLICATE" },
  { component: "ai-elements", source: "src/components/ai-elements", kind: "route-local", measured: "Assistant surfaces", status: "OBSERVED DUPLICATE" },
  { component: "Reference kit", source: "src/components/design/reference-kit.tsx", kind: "reference-only", measured: "2 unlisted routes", status: "GOVERNANCE RULE", note: "Never counted as production consumption." },
  { component: "Font Awesome", source: "package.json", kind: "reference-only", measured: "0 imports", status: "INSTALLED BUT UNUSED" },
];
