/**
 * Phase 4 — iconography audit.
 *
 * DOCUMENTATION ONLY. Every record below describes the production code as it
 * exists today. Nothing here is imported by an application screen, and no icon,
 * size, stroke or colour was changed to produce this audit.
 *
 * Consumers: `/design-system` and `/design-guide` only.
 *
 * Usage figures are import-site counts measured across `src/routes` and
 * `src/components` (reference-layer files excluded). They indicate relative
 * weight, not exact render counts — a single import can render many times.
 */
import type { FoundationCategory, IconCategory, SpacingGroup } from "./types";

/* ------------------------------------------------------------------
 * 1. Icon sources — what actually ships.
 * ------------------------------------------------------------------ */

export const ICON_SOURCES: FoundationCategory = {
  id: "icon-sources",
  title: "Icon sources",
  summary:
    "Three icon packages are installed. One carries the product, one covers a single gap, and one has no consumer at all. Inline SVG covers the brand mark and the decorative artwork.",
  entries: [
    {
      name: "lucide-react",
      value:
        "Named ES imports, e.g. import { ArrowRight } from \"lucide-react\". 149 distinct icons across 144 files. Rendered as SVG with currentColor and the library's default 2px stroke.",
      source: "package.json — lucide-react ^0.575.0",
      consumers:
        "Every experience: marketing landing, marketplace shell, plan and cart screens, all three shells, admin tables, dialogs, empty states.",
      ownership: "primitive",
      shared: "source-of-truth",
      maturity: "current",
      note: "CURRENT IMPLEMENTATION — the de facto icon system. Any icon governance starts here.",
    },
    {
      name: "@tabler/icons-react",
      value:
        "One import: IconDental, wrapped by the local Tooth component. Chosen because Lucide has no tooth glyph.",
      source: "package.json ^3.46.0 → src/components/icons/tooth-icon.tsx",
      consumers: "src/lib/products.ts — the Dental product icon, rendered wherever that product appears.",
      ownership: "business",
      shared: "one-off",
      maturity: "current",
      note: "OBSERVED VARIATION — a second icon library carried for a single glyph. Deliberate; the gap is real.",
    },
    {
      name: "@fortawesome/free-solid-svg-icons",
      value: "Declared as a dependency. No file under src imports @fortawesome.",
      source: "package.json ^7.3.1",
      consumers: "None found.",
      ownership: "foundation",
      shared: "one-off",
      maturity: "opportunity",
      note: "INSTALLED BUT UNUSED — a leftover from an earlier dental-icon attempt. Removal is a dependency change, not a design change; deferred.",
    },
    {
      name: "Inline SVG — brand mark",
      value:
        "Hand-authored <svg viewBox=\"0 0 40 40\"> inside AboxMark: disc, inner ring, dashed mid ring, orbital dot, chevron A. All fills and strokes read CSS variables.",
      source: "src/components/abox/logo.tsx",
      consumers: "All three shells, the landing page, the quote screen, both assistants, placeholder screens, the branding screen.",
      ownership: "business",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "Inline SVG — decorative primitives",
      value:
        "Roughly 20 exported components drawing rings, grids, tick fields, weaves, shields and silhouettes. The only place explicit strokeWidth values appear (0.75, 1, 1.25, 1.75).",
      source: "src/components/abox/decor/index.tsx",
      consumers: "src/routes/index.tsx only — six primitives are used there.",
      ownership: "business",
      shared: "convention",
      maturity: "current",
      note: "POSSIBLY UNUSED — most exports in this file have no consumer. See the unused findings.",
    },
    {
      name: "Inline SVG — auth screen",
      value: "Local decorative markup inside the auth route.",
      source: "src/routes/auth.tsx",
      consumers: "That route only.",
      ownership: "local",
      shared: "one-off",
      maturity: "current",
    },
    {
      name: "Icon fonts / glyphs / CSS icons",
      value: "None. No icon font is loaded, and no ::before glyph or CSS-drawn icon convention exists.",
      source: "src/styles.css, src/routes/__root.tsx",
      consumers: "—",
      ownership: "foundation",
      shared: "convention",
      maturity: "current",
      note: "CURRENT IMPLEMENTATION — worth recording: the product has no icon-font layer at all.",
    },
    {
      name: "Image-based icons",
      value: "None. There is no <img> element anywhere in src and no raster icon asset in the repository.",
      source: "src/**",
      consumers: "—",
      ownership: "foundation",
      shared: "convention",
      maturity: "current",
    },
  ],
};

/* ------------------------------------------------------------------
 * 2. Semantic icon inventory.
 * Representative records per category rather than all 149 icons.
 * ------------------------------------------------------------------ */

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: "icons-navigation",
    title: "Navigation, arrows & chevrons",
    summary:
      "The heaviest category in the product. ArrowLeft and ArrowRight alone account for 60 import sites — back links and forward CTAs are everywhere.",
    entries: [
      {
        name: "ArrowLeft",
        library: "lucide-react",
        role: "Back / return to previous step",
        usage: 32,
        where: "Every wizard step, detail screen and sub-page back link",
        size: "h-4 w-4 (h-3.5 w-3.5 in compact bars)",
        treatment: "currentColor, inherits the link or button foreground",
        interactive: "both",
        semantics: "decorative",
        experience: "All",
      },
      {
        name: "ArrowRight",
        library: "lucide-react",
        role: "Forward action / primary CTA affordance",
        usage: 28,
        where: "Landing CTAs, action pills, plan tiles, wizard continue buttons",
        size: "h-4 w-4",
        treatment: "currentColor; often animates on group hover",
        interactive: "both",
        semantics: "decorative",
        experience: "All",
      },
      {
        name: "ChevronRight / ChevronDown",
        library: "lucide-react",
        role: "Disclosure and menu direction",
        usage: 12,
        where: "Dropdown triggers, accordions, the account control, sidebar groups",
        size: "h-4 w-4, h-3.5 w-3.5 next to small labels",
        treatment: "text-muted-foreground; rotates on open in some triggers",
        interactive: "static",
        semantics: "decorative",
        experience: "All",
      },
      {
        name: "ArrowUpRight",
        library: "lucide-react",
        role: "External or outbound navigation",
        usage: 4,
        where: "Outbound links and cross-workspace jumps",
        size: "h-3.5 w-3.5",
        treatment: "currentColor at muted weight",
        interactive: "static",
        semantics: "decorative",
        experience: "Web, Admin",
      },
      {
        name: "Compass",
        library: "lucide-react",
        role: "Guided / explore affordance",
        usage: 4,
        where: "Guide-me shopping mode, discovery entry points",
        size: "h-4 w-4",
        treatment: "text-primary",
        interactive: "static",
        semantics: "decorative",
        experience: "Shopping",
      },
    ],
  },
  {
    id: "icons-status",
    title: "Status, validation & assurance",
    summary:
      "The second heaviest cluster. Status icons always sit beside a word — colour and glyph reinforce the label, they never replace it.",
    entries: [
      {
        name: "ShieldCheck",
        library: "lucide-react",
        role: "Verified / protected / coverage assurance",
        usage: 21,
        where: "Trust strips, coverage summaries, credential and verification screens",
        size: "h-4 w-4, h-5 w-5 in feature plates",
        treatment: "text-primary or text-sage",
        interactive: "static",
        semantics: "decorative",
        experience: "All",
        note: "Doubles as a trust motif in marketing and a verification state in admin — the same glyph, two contexts.",
      },
      {
        name: "CheckCircle2",
        library: "lucide-react",
        role: "Success / complete / allowed",
        usage: 16,
        where: "Wizard completion, eligibility outcomes, confirmation panels",
        size: "h-4 w-4",
        treatment: "text-success or text-sage",
        interactive: "static",
        semantics: "meaningful",
        experience: "All",
      },
      {
        name: "Check",
        library: "lucide-react",
        role: "Selected / included item",
        usage: 20,
        where: "Benefit lists, checkbox and select primitives, feature ticks",
        size: "h-4 w-4, h-3.5 w-3.5 in dense lists",
        treatment: "text-primary or text-sage",
        interactive: "static",
        semantics: "decorative",
        experience: "All",
      },
      {
        name: "AlertTriangle",
        library: "lucide-react",
        role: "Warning / needs attention",
        usage: 11,
        where: "Deficiency notices, review banners, blocking explanations",
        size: "h-4 w-4",
        treatment: "text-warning",
        interactive: "static",
        semantics: "meaningful",
        experience: "Shopping, Admin",
      },
      {
        name: "XCircle / Ban / ShieldAlert / PauseCircle",
        library: "lucide-react",
        role: "Blocked, not allowed, suspended",
        usage: 21,
        where: "Authority outcomes, enforcement states, suspended roster rows",
        size: "h-4 w-4",
        treatment: "text-destructive; PauseCircle uses muted or warning",
        interactive: "static",
        semantics: "meaningful",
        experience: "Admin",
        note: "OBSERVED VARIATION — four distinct glyphs cover the negative-state space with no single mapping rule.",
      },
      {
        name: "Circle",
        library: "lucide-react",
        role: "Neutral / pending / not-applicable marker",
        usage: 4,
        where: "Step indicators and status dots",
        size: "h-3 w-3",
        treatment: "text-muted-foreground",
        interactive: "static",
        semantics: "decorative",
        experience: "Admin",
      },
    ],
  },
  {
    id: "icons-actions",
    title: "Actions — create, edit, delete, manage",
    summary:
      "Action icons are small and almost always paired with either a text label or an aria-label. Trash2 is the only destructive glyph in use.",
    entries: [
      {
        name: "Plus",
        library: "lucide-react",
        role: "Create / add",
        usage: 17,
        where: "Add roster member, add plan, add row, new record buttons",
        size: "h-4 w-4, h-3.5 w-3.5 on small buttons",
        treatment: "currentColor inside the button",
        interactive: "both",
        semantics: "decorative",
        experience: "Shopping, Admin",
      },
      {
        name: "Pencil / Settings / Settings2",
        library: "lucide-react",
        role: "Edit and configure",
        usage: 8,
        where: "Edit quote, table row actions, settings entry points",
        size: "h-3.5 w-3.5 in tables, h-4 w-4 elsewhere",
        treatment: "text-muted-foreground, hover to foreground",
        interactive: "interactive",
        semantics: "meaningful",
        experience: "Shopping, Admin",
        note: "OBSERVED VARIATION — Settings and Settings2 both appear for configuration entry points.",
      },
      {
        name: "Trash2",
        library: "lucide-react",
        role: "Delete / retire / remove",
        usage: 5,
        where: "Cart removal, asset retire, roster removal",
        size: "h-3.5 w-3.5",
        treatment: "text-muted-foreground, hover:text-destructive",
        interactive: "interactive",
        semantics: "meaningful",
        experience: "Shopping, Admin",
        note: "The consistent destructive convention: muted at rest, destructive on hover, always with an aria-label when icon-only.",
      },
      {
        name: "RotateCw / History",
        library: "lucide-react",
        role: "Refresh, reset, audit history",
        usage: 10,
        where: "Filter reset, renewal cycles, audit trails",
        size: "h-3.5 w-3.5 / h-4 w-4",
        treatment: "text-muted-foreground",
        interactive: "both",
        semantics: "decorative",
        experience: "Shopping, Admin",
      },
      {
        name: "MoreHorizontal",
        library: "lucide-react",
        role: "Overflow menu",
        usage: 2,
        where: "Table row menus",
        size: "h-4 w-4",
        treatment: "text-muted-foreground",
        interactive: "interactive",
        semantics: "meaningful",
        experience: "Admin",
      },
      {
        name: "X",
        library: "lucide-react",
        role: "Dismiss / close",
        usage: 9,
        where: "Dialog and sheet close buttons, removable filter chips, banners",
        size: "h-4 w-4, h-3 w-3 on chips",
        treatment: "text-muted-foreground with a hover opacity change",
        interactive: "interactive",
        semantics: "meaningful",
        experience: "All",
        note: "Dialog and Sheet pair it with an sr-only \"Close\" label — the cleanest icon-only pattern in the codebase.",
      },
    ],
  },
  {
    id: "icons-finding",
    title: "Search, filter & sort",
    summary: "A small, stable set. Search icons sit inside inputs at a fixed offset; filter and sort glyphs sit on controls.",
    entries: [
      {
        name: "Search",
        library: "lucide-react",
        role: "Search affordance inside an input",
        usage: 7,
        where: "Admin command search, roster search, marketplace search",
        size: "h-4 w-4",
        treatment: "text-muted-foreground, absolutely positioned inside the field",
        interactive: "static",
        semantics: "decorative",
        experience: "Shopping, Admin",
      },
      {
        name: "SlidersHorizontal / Filter",
        library: "lucide-react",
        role: "Filter controls",
        usage: 3,
        where: "Plan results filter rail, table filter bars",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "both",
        semantics: "decorative",
        experience: "Shopping, Admin",
      },
      {
        name: "ArrowUpDown / ChevronsUpDown",
        library: "lucide-react",
        role: "Sort affordance",
        usage: 3,
        where: "Sortable table headers, sort selects",
        size: "h-3.5 w-3.5",
        treatment: "text-muted-foreground",
        interactive: "both",
        semantics: "decorative",
        experience: "Shopping, Admin",
      },
    ],
  },
  {
    id: "icons-identity",
    title: "Account, organization & people",
    summary:
      "Users is both a people glyph and the ICHRA product icon — a deliberate reuse recorded here so it is not mistaken for drift.",
    entries: [
      {
        name: "Users",
        library: "lucide-react",
        role: "People, teams, and the ICHRA product mark",
        usage: 15,
        where: "Header ICHRA link, landing product chips, employer plate, roster screens",
        size: "h-4 w-4 in nav, h-5 w-5 on plates",
        treatment: "currentColor / text-primary",
        interactive: "both",
        semantics: "both",
        experience: "All",
        note: "CURRENT IMPLEMENTATION — chosen as the ICHRA icon by explicit decision. Both roles share one glyph.",
      },
      {
        name: "Building2",
        library: "lucide-react",
        role: "Agency, organization, employer",
        usage: 14,
        where: "Organization screens, downline tree, agency workspace, employer surfaces",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "static",
        semantics: "decorative",
        experience: "Admin, Web",
      },
      {
        name: "User / UserCheck / Shield",
        library: "lucide-react",
        role: "Account control, verified agent, life product",
        usage: 8,
        where: "Header profile trigger, credential rows, the Life product icon",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "both",
        semantics: "both",
        experience: "All",
        note: "OBSERVED VARIATION — Shield is both a security glyph and the Life product mark.",
      },
      {
        name: "GitBranch / ListTree",
        library: "lucide-react",
        role: "Downline hierarchy and structure",
        usage: 11,
        where: "Organization structure, downline wizard",
        size: "h-4 w-4",
        treatment: "text-muted-foreground",
        interactive: "static",
        semantics: "decorative",
        experience: "Admin",
      },
      {
        name: "LogIn / LogOut",
        library: "lucide-react",
        role: "Session entry and exit",
        usage: 4,
        where: "Auth screen, account dropdown",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "static",
        semantics: "decorative",
        experience: "All",
      },
    ],
  },
  {
    id: "icons-commerce",
    title: "Commerce, products & plans",
    summary:
      "Product icons are centrally mapped in src/lib/products.ts, which is the single source of truth for which glyph represents which product.",
    entries: [
      {
        name: "ShoppingCart / ShoppingBag",
        library: "lucide-react",
        role: "Cart and shopping entry",
        usage: 8,
        where: "Header cart control, cart page heading, shop strip",
        size: "h-4 w-4, h-5 w-5 beside the cart heading",
        treatment: "currentColor; the header control tints when the cart is non-empty",
        interactive: "both",
        semantics: "meaningful",
        experience: "Shopping",
        note: "OBSERVED VARIATION — two commerce glyphs; the header treatment was deliberately aligned with the cart page heading.",
      },
      {
        name: "Store",
        library: "lucide-react",
        role: "Shop plans / marketplace entry",
        usage: 6,
        where: "Header Shop plans link, marketplace surfaces",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "static",
        semantics: "decorative",
        experience: "Web, Shopping",
      },
      {
        name: "HeartPulse",
        library: "lucide-react",
        role: "Health product (also the product fallback icon)",
        usage: 3,
        where: "src/lib/products.ts, product chips, plan surfaces",
        size: "h-4 w-4 / h-5 w-5",
        treatment: "text-primary",
        interactive: "static",
        semantics: "meaningful",
        experience: "Web, Shopping",
      },
      {
        name: "Tooth (IconDental)",
        library: "@tabler/icons-react via src/components/icons/tooth-icon.tsx",
        role: "Dental product",
        usage: 1,
        where: "src/lib/products.ts",
        size: "Inherits the product-chip icon size",
        treatment: "currentColor; the wrapper forces aria-hidden",
        interactive: "static",
        semantics: "decorative",
        experience: "Web, Shopping",
        note: "The only local icon wrapper in the codebase. It exists because Lucide has no tooth glyph.",
      },
      {
        name: "Eye / Activity / Ambulance / BedDouble",
        library: "lucide-react",
        role: "Vision, Critical Illness, Accident and Hospital Indemnity products",
        usage: 14,
        where: "src/lib/products.ts and every product chip or tile derived from it",
        size: "h-4 w-4 / h-5 w-5",
        treatment: "currentColor",
        interactive: "static",
        semantics: "meaningful",
        experience: "Web, Shopping",
        note: "Eye also serves as the generic visibility/preview glyph elsewhere — one glyph, two meanings.",
      },
      {
        name: "DollarSign / Percent / Receipt",
        library: "lucide-react",
        role: "Price, contribution and billing",
        usage: 10,
        where: "Pricing panels, cart totals, commission surfaces",
        size: "h-4 w-4, h-3.5 w-3.5 inline",
        treatment: "text-muted-foreground or text-primary",
        interactive: "static",
        semantics: "decorative",
        experience: "Shopping, Admin",
      },
    ],
  },
  {
    id: "icons-communication",
    title: "Communication & support",
    summary: "Contact affordances across marketing, support and admin messaging.",
    entries: [
      {
        name: "Mail / Phone / Send",
        library: "lucide-react",
        role: "Email, call and submit",
        usage: 24,
        where: "Support screens, contact rows, share and invite flows",
        size: "h-4 w-4, h-3.5 w-3.5 inline",
        treatment: "text-muted-foreground or currentColor in buttons",
        interactive: "both",
        semantics: "both",
        experience: "Web, Admin",
      },
      {
        name: "MessageSquare / Headset / LifeBuoy",
        library: "lucide-react",
        role: "Chat, live support, help",
        usage: 10,
        where: "Support entry points, assistant surfaces, help links",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "both",
        semantics: "decorative",
        experience: "Web, Shopping",
      },
      {
        name: "Bell",
        library: "lucide-react",
        role: "Notifications",
        usage: 4,
        where: "Shell headers, notification preferences",
        size: "h-4 w-4",
        treatment: "text-muted-foreground",
        interactive: "interactive",
        semantics: "meaningful",
        experience: "Admin",
      },
    ],
  },
  {
    id: "icons-data",
    title: "Documents, data & dashboard",
    summary: "Records, uploads, time and analytics glyphs, concentrated in the admin experience.",
    entries: [
      {
        name: "FileText",
        library: "lucide-react",
        role: "Document / record",
        usage: 9,
        where: "Credential documents, policy records, audit entries",
        size: "h-4 w-4",
        treatment: "text-muted-foreground",
        interactive: "static",
        semantics: "decorative",
        experience: "Admin",
      },
      {
        name: "Upload / Download",
        library: "lucide-react",
        role: "File transfer",
        usage: 8,
        where: "Asset management, document upload, export actions",
        size: "h-3.5 w-3.5 / h-4 w-4",
        treatment: "currentColor",
        interactive: "interactive",
        semantics: "meaningful",
        experience: "Admin",
      },
      {
        name: "Calendar / Clock",
        library: "lucide-react",
        role: "Dates, effective periods, renewals",
        usage: 8,
        where: "Enrollment windows, renewal rows, timelines",
        size: "h-3.5 w-3.5",
        treatment: "text-muted-foreground",
        interactive: "static",
        semantics: "decorative",
        experience: "Shopping, Admin",
      },
      {
        name: "CheckSquare / ListChecks / ListTodo",
        library: "lucide-react",
        role: "Task and checklist state",
        usage: 11,
        where: "Onboarding checklists, requirement lists, wizards",
        size: "h-4 w-4",
        treatment: "text-primary or muted",
        interactive: "static",
        semantics: "decorative",
        experience: "Admin",
      },
      {
        name: "Activity / TrendingUp",
        library: "lucide-react",
        role: "Metrics and trend direction",
        usage: 5,
        where: "KPI deltas, operational dashboards",
        size: "h-3.5 w-3.5",
        treatment: "text-success or text-destructive by direction",
        interactive: "static",
        semantics: "meaningful",
        experience: "Admin",
      },
    ],
  },
  {
    id: "icons-decorative",
    title: "Decorative, brand & atmosphere",
    summary:
      "Glyphs used for tone rather than meaning. Sparkles is the PlanAI motif and the most-used purely decorative icon in the product.",
    entries: [
      {
        name: "Sparkles",
        library: "lucide-react",
        role: "PlanAI / assisted content / highlight",
        usage: 17,
        where: "PlanAI assistant, AI-assisted panels, the cart add-ons banner, marketing highlights",
        size: "h-4 w-4, h-3.5 w-3.5 inline",
        treatment: "text-ai or text-primary",
        interactive: "static",
        semantics: "decorative",
        experience: "All",
        note: "The closest thing to a sub-brand glyph — it consistently signals AI assistance.",
      },
      {
        name: "Star",
        library: "lucide-react",
        role: "Emphasis, ratings, best-match marker",
        usage: 4,
        where: "Plan highlights, marketing proof points",
        size: "h-3.5 w-3.5",
        treatment: "text-warning or text-primary",
        interactive: "static",
        semantics: "decorative",
        experience: "Web, Shopping",
      },
      {
        name: "Globe / MapPin / Landmark",
        library: "lucide-react",
        role: "Geography, location, state authority",
        usage: 9,
        where: "State selection, licensing geography, marketing coverage",
        size: "h-4 w-4",
        treatment: "text-muted-foreground",
        interactive: "static",
        semantics: "decorative",
        experience: "All",
      },
      {
        name: "Stethoscope / Pill / Palette / Monitor",
        library: "lucide-react",
        role: "Care, pharmacy, branding, device context",
        usage: 11,
        where: "Benefit explanations, branding screens, responsive previews",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "static",
        semantics: "decorative",
        experience: "All",
      },
    ],
  },
  {
    id: "icons-ambiguous",
    title: "Ambiguous or dual-purpose",
    summary:
      "UNOWNED AREA — these glyphs carry more than one meaning depending on where they appear. Recorded rather than resolved, because assigning one meaning would change icon selection somewhere.",
    entries: [
      {
        name: "Eye",
        library: "lucide-react",
        role: "Vision product AND generic preview/visibility",
        usage: 7,
        where: "src/lib/products.ts; preview and show-details controls",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "both",
        semantics: "both",
        experience: "Web, Shopping, Admin",
        note: "UNOWNED AREA — a product mark and a utility action share one glyph.",
      },
      {
        name: "Shield",
        library: "lucide-react",
        role: "Life product AND security/protection",
        usage: 2,
        where: "src/lib/products.ts; security and permission surfaces",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "static",
        semantics: "both",
        experience: "Web, Shopping, Admin",
        note: "UNOWNED AREA — sits alongside ShieldCheck and ShieldAlert, which mean verification and blocking.",
      },
      {
        name: "Users",
        library: "lucide-react",
        role: "ICHRA product AND people/teams",
        usage: 15,
        where: "Header, landing chips, roster and organization screens",
        size: "h-4 w-4",
        treatment: "currentColor",
        interactive: "both",
        semantics: "both",
        experience: "All",
        note: "Intentional — the ICHRA icon was explicitly chosen as Users. Recorded so it is not later 'corrected'.",
      },
      {
        name: "Activity",
        library: "lucide-react",
        role: "Critical Illness product AND metrics/trend",
        usage: 3,
        where: "src/lib/products.ts; operational dashboards",
        size: "h-3.5 w-3.5 / h-4 w-4",
        treatment: "currentColor",
        interactive: "static",
        semantics: "both",
        experience: "Shopping, Admin",
      },
    ],
  },
];

/* ------------------------------------------------------------------
 * 3. Size audit.
 * ------------------------------------------------------------------ */

export const ICON_SIZES: SpacingGroup = {
  id: "icon-size-audit",
  title: "Icon size ladder as measured",
  summary:
    "Four sizes carry almost everything. h-4 w-4 is the default and appears more than four times as often as the next size. Two syntaxes coexist: the h-/w- pair and Tailwind's size- shorthand.",
  entries: [
    {
      value: "h-4 w-4",
      computed: "16px",
      occurrences: 281,
      purpose: "The default icon size — buttons, nav items, inline labels, status rows, dialogs",
      where: "Everywhere; also enforced by the Button primitive via [&_svg]:size-4",
      frequency: "recurring",
      consistency: "consistent",
      source: "components/ui/button.tsx and every route",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "high",
      note: "CURRENT IMPLEMENTATION — the single most load-bearing dimension in the product.",
    },
    {
      value: "size-4",
      computed: "16px",
      occurrences: 31,
      purpose: "Identical to h-4 w-4, written in the newer shorthand",
      where: "shadcn primitives and newer components",
      frequency: "recurring",
      consistency: "variable",
      source: "components/ui/*",
      ownership: "primitive",
      centralizable: "safe",
      risk: "low",
      note: "OBSERVED VARIATION — same value, two syntaxes. Cosmetic only; not converged.",
    },
    {
      value: "h-3.5 w-3.5",
      computed: "14px",
      occurrences: 68,
      purpose: "Dense contexts — table row actions, chips, inline meta, compact bars",
      where: "DataTable actions, filter chips, cart line items, metadata rows",
      frequency: "recurring",
      consistency: "consistent",
      source: "Routes and abox components",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "medium",
    },
    {
      value: "h-3 w-3",
      computed: "12px",
      occurrences: 34,
      purpose: "Micro icons beside 10–11px labels, status dots, chip dismiss",
      where: "Badges, serial rows, removable chips",
      frequency: "recurring",
      consistency: "consistent",
      source: "abox badges and chips",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "medium",
    },
    {
      value: "h-5 w-5",
      computed: "20px",
      occurrences: 32,
      purpose: "Emphasis icons — feature plates, section leads, empty-state glyph",
      where: "EmptyState, marketing plates, cart heading",
      frequency: "recurring",
      consistency: "consistent",
      source: "abox/empty-state.tsx and marketing sections",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "medium",
    },
    {
      value: "h-6 w-6 / size-5",
      computed: "24px / 20px",
      occurrences: 6,
      purpose: "Occasional larger inline emphasis",
      where: "A handful of marketing and dialog surfaces",
      frequency: "occasional",
      consistency: "variable",
      source: "Routes",
      ownership: "local",
      centralizable: "unsafe",
      risk: "low",
    },
    {
      value: "h-8 w-8",
      computed: "32px",
      occurrences: 18,
      purpose: "Icon container / avatar-scale disc, not the glyph itself",
      where: "Circular icon wrappers in lists and plates",
      frequency: "recurring",
      consistency: "consistent",
      source: "Routes and abox components",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "medium",
      note: "A wrapper dimension — the glyph inside is usually h-4 w-4.",
    },
    {
      value: "h-9 w-9",
      computed: "36px",
      occurrences: 14,
      purpose: "Icon-button and brand-mark footprint, matching the 36px control height",
      where: "Icon-only buttons, AboxMark default, CarrierMark default",
      frequency: "recurring",
      consistency: "consistent",
      source: "components/ui/button.tsx icon size, abox/logo.tsx, abox/carrier-mark.tsx",
      ownership: "primitive",
      centralizable: "conditional",
      risk: "medium",
      note: "CURRENT IMPLEMENTATION — 36px is the shared control/mark footprint across the product.",
    },
    {
      value: "h-10 w-10 / h-12 w-12",
      computed: "40px / 48px",
      occurrences: 9,
      purpose: "Large containers — feature tiles and the EmptyState glyph frame",
      where: "EmptyState uses h-12 w-12 around an h-5 w-5 glyph",
      frequency: "occasional",
      consistency: "consistent",
      source: "abox/empty-state.tsx and marketing tiles",
      ownership: "business",
      centralizable: "conditional",
      risk: "low",
    },
  ],
};

/* ------------------------------------------------------------------
 * 4. Stroke, fill and visual treatment.
 * ------------------------------------------------------------------ */

export const ICON_TREATMENT: FoundationCategory = {
  id: "icon-treatment",
  title: "Stroke, fill & colour treatment",
  summary:
    "Icons inherit. Almost nothing about a Lucide icon is set explicitly — no stroke override, no fill, no hard-coded colour. The decorative SVG primitives are the only exception.",
  entries: [
    {
      name: "Stroke width",
      value:
        "Never overridden on a Lucide icon anywhere in the application. Every icon renders at the library default (2).",
      source: "src/routes, src/components",
      consumers: "All 149 icons in use",
      ownership: "primitive",
      shared: "source-of-truth",
      maturity: "current",
      note: "CURRENT IMPLEMENTATION — the strongest single convention found in this audit.",
    },
    {
      name: "Decorative stroke widths",
      value: "0.75, 1, 1.25 and 1.75 — used only inside the hand-authored decorative primitives.",
      source: "src/components/abox/decor/index.tsx",
      consumers: "The landing page",
      ownership: "business",
      shared: "one-off",
      maturity: "current",
      note: "Intentionally lighter than icon strokes so the artwork reads as background texture.",
    },
    {
      name: "Stroke vs. fill",
      value:
        "Lucide icons are outline-only; no filled icon variant is used. The brand mark and CarrierMark are the only filled shapes.",
      source: "lucide-react, abox/logo.tsx, abox/carrier-mark.tsx",
      consumers: "All",
      ownership: "pattern",
      shared: "convention",
      maturity: "current",
    },
    {
      name: "currentColor",
      value:
        "The default. Icons take their colour from the surrounding button, link or text element rather than declaring one.",
      source: "lucide-react defaults",
      consumers: "The large majority of icon usages",
      ownership: "primitive",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "Explicit colour",
      value:
        "Always a semantic token class — text-primary, text-muted-foreground, text-sage, text-success, text-warning, text-destructive, text-ai. No hex or arbitrary colour appears on an icon.",
      source: "Routes and abox components",
      consumers: "Status, product and emphasis icons",
      ownership: "pattern",
      shared: "convention",
      maturity: "current",
      note: "GOVERNANCE RULE candidate — already true in practice, so it costs nothing to state.",
    },
    {
      name: "Muted treatment",
      value: "text-muted-foreground is the resting state for supporting and utility icons; hover promotes to foreground.",
      source: "Tables, meta rows, search fields",
      consumers: "Admin and shopping surfaces",
      ownership: "pattern",
      shared: "convention",
      maturity: "current",
    },
    {
      name: "Opacity",
      value:
        "Not used to tone icons down — colour tokens do that job. Opacity appears only on decorative artwork (opacity-30 to opacity-80) and the disabled-button rule (opacity-50).",
      source: "routes/index.tsx, components/ui/button.tsx",
      consumers: "Landing artwork, disabled controls",
      ownership: "pattern",
      shared: "convention",
      maturity: "current",
    },
    {
      name: "Circular icon container",
      value:
        "rounded-full with a hairline or token border and a surface fill, sized h-8 w-8 or h-9 w-9 around a 14–16px glyph. Roughly 104 rounded bordered wrappers exist across the product.",
      source: "Routes and abox components",
      consumers: "Lists, plates, brand and carrier marks, status discs",
      ownership: "pattern",
      shared: "convention",
      maturity: "current",
      note: "UNOWNED AREA — the most repeated icon container in the product has no component.",
    },
    {
      name: "Square icon container",
      value: "rounded-md with border-hairline and bg-background — the EmptyState frame at h-12 w-12.",
      source: "src/components/abox/empty-state.tsx",
      consumers: "Every empty state",
      ownership: "business",
      shared: "source-of-truth",
      maturity: "current",
    },
    {
      name: "Shadows and effects on icons",
      value: "None. Icons carry no shadow, glow or filter anywhere in the product.",
      source: "src/**",
      consumers: "—",
      ownership: "pattern",
      shared: "convention",
      maturity: "current",
    },
  ],
};
