/**
 * Phase 2 — layout system audit.
 *
 * DOCUMENTATION ONLY. Records the container, grid, flex and structural
 * behaviour that ships today. No new universal container is proposed and no
 * existing layout is normalized. Consumers: `/design-system`, `/design-guide`.
 */
import type { ContainerEntry, DimensionEntry, LayoutPattern, RelationshipGroup } from "./types";

export const CONTAINERS: ContainerEntry[] = [
  {
    name: "Web-experience container",
    widthBehavior: "Fluid up to a fixed ceiling, centred with mx-auto.",
    maxWidth: "max-w-[88rem] (1408px)",
    gutters: "px-4 → md:px-8",
    alignment: "Centred",
    responsive: "Single breakpoint step at md (768px); no further change above.",
    consumers:
      "index.tsx, plans.index.tsx, plans.$planId.tsx, cart.tsx, coverage.tsx, select.tsx, ichra, apply/review, auth, shared-link routes, member-shell content, marketplace footer — 23 occurrences.",
    source: "Repeated class string at each call site.",
    shared: "shared",
    variations:
      "OBSERVED VARIATION — repeated literally rather than owned by a component. Vertical padding differs per surface (marketing py-16/24, shopping pt-4 pb-8).",
  },
  {
    name: "Admin / internal shell container",
    widthBehavior: "Fluid up to a wider ceiling, centred inside the rail offset.",
    maxWidth: "max-w-[1500px]",
    gutters: "px-4 → md:px-8 (content), px-3 → sm:px-4 → lg:px-8 (topbar)",
    alignment: "Centred within the left-rail offset",
    responsive: "Rail offset lg:pl-[292px], collapsing to lg:pl-[104px]; no rail below lg.",
    consumers: "components/abox/internal-shell.tsx — every /app and /agency route.",
    source: "components/abox/internal-shell.tsx",
    shared: "shared",
    variations:
      "OBSERVED VARIATION — 1500px ceiling and a three-step topbar gutter, both different from the web experience. Intentional: admin has a rail eating horizontal space.",
  },
  {
    name: "Floating glass header",
    widthBehavior: "Full width of the page gutter, not width-capped.",
    maxWidth: "none",
    gutters: "px-4 → md:px-8",
    alignment: "sticky top-4 (top-6 on landing), z-30",
    responsive: "Nav items hide progressively; brand tagline hidden below md.",
    consumers: "marketplace-shell.tsx, member-shell.tsx",
    source: "components/abox/marketplace-shell.tsx, member-shell.tsx",
    shared: "shared",
    variations:
      "CURRENT IMPLEMENTATION — header is deliberately full-bleed while content is capped at 88rem. Landing offsets the sticky origin by 8px.",
  },
  {
    name: "Shopping split (results)",
    widthBehavior: "Flex row: fixed filter rail plus fluid results column.",
    maxWidth: "inherits the 88rem container",
    gutters: "gap-6 between rail and results",
    alignment: "Top-aligned",
    responsive: "Rail is hidden below lg; a filter trigger button appears instead.",
    consumers: "routes/plans.index.tsx",
    source: "routes/plans.index.tsx",
    shared: "local",
    variations: "Rail width is a literal w-64 shrink-0.",
  },
  {
    name: "Detail split (content + sticky summary)",
    widthBehavior: "CSS grid with a fluid main column and a fixed summary column.",
    maxWidth: "inherits the 88rem container",
    gutters: "gap-6 (plan detail), gap-5 (cart)",
    alignment: "Summary column uses sticky top-24",
    responsive: "Collapses to one column below lg.",
    consumers:
      "plans.$planId.tsx (lg:grid-cols-[1fr_320px]), cart.tsx (lg:grid-cols-[minmax(0,1fr)_360px])",
    source: "route files",
    shared: "local",
    variations:
      "OBSERVED VARIATION — two different summary widths (320px, 360px) and two gaps (6, 5) for the same structural pattern.",
  },
  {
    name: "Member settings shell",
    widthBehavior: "Flex column on mobile, icon rail plus content on md+.",
    maxWidth: "max-w-[88rem]",
    gutters: "px-4 → md:px-8, pb-8 → md:pb-12, pt-10 → md:pt-14",
    alignment: "Centred; nav becomes a horizontal scroller on mobile",
    responsive: "md:flex-row switches the nav from a scrolling strip to a vertical rail.",
    consumers: "components/abox/member-shell.tsx",
    source: "components/abox/member-shell.tsx",
    shared: "shared",
    variations: "Nav gap changes from gap-1 (horizontal) to md:gap-3 (vertical).",
  },
  {
    name: "Overlay containers",
    widthBehavior: "Dialog is width-capped and centred; Sheet is edge-anchored.",
    maxWidth: "Dialog max-w-lg; Sheet w-3/4 with sm:max-w-sm; mobile nav sheet w-[300px]",
    gutters: "p-6 interior, gap-4 between regions",
    alignment: "Dialog fixed at 50%/50% with translate; Sheet inset to an edge",
    responsive: "Dialog rounds corners only at sm+; Sheet caps its width at sm+.",
    consumers: "components/ui/dialog.tsx, components/ui/sheet.tsx, internal-shell mobile nav",
    source: "components/ui/dialog.tsx, components/ui/sheet.tsx",
    shared: "shared",
    variations: "internal-shell overrides the sheet to w-[300px] p-0 for the nav drawer.",
  },
];

export const GRID_FLEX_RELATIONSHIPS: RelationshipGroup = {
  id: "grid-flex",
  title: "Grid and flex structures",
  summary:
    "Grids are declared per call site with explicit responsive column counts. The dominant progression is 1 → 2 → 3/4 columns via sm/md/lg. Asymmetric fraction grids are used for editorial and split layouts.",
  entries: [
    {
      pair: "Card grid → columns",
      observed: "grid gap-4/5 with sm:grid-cols-2 (53 uses) then md/lg:grid-cols-3 or 4.",
      source: "index.tsx, agency/* dashboards, app/* pages",
      consistency: "consistent",
      note: "sm:grid-cols-2 is the single most common responsive grid step in the app.",
    },
    {
      pair: "KPI row → columns",
      observed: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4 wrapping KpiCard.",
      source: "app/* dashboards, agency dashboards",
      consistency: "consistent",
    },
    {
      pair: "Plan results grid → item",
      observed: "grid gap-4 — single column at every breakpoint; plan tiles are full-width rows.",
      source: "routes/plans.index.tsx",
      consistency: "consistent",
    },
    {
      pair: "Hero → columns",
      observed: "grid items-center gap-12 lg:grid-cols-[1.15fr_1fr] lg:gap-14.",
      source: "routes/index.tsx",
      consistency: "varies",
      note: "OBSERVED VARIATION — each marketing section tunes its own fraction ratio (1.15fr/1fr, 1fr/1.1fr, 1.2fr/1fr).",
    },
    {
      pair: "Footer → columns",
      observed: "grid gap-14 md:grid-cols-[1.4fr_1fr_1fr_1fr] px-6 py-16 md:px-12 md:py-20.",
      source: "components/abox/marketplace-shell.tsx",
      consistency: "consistent",
    },
    {
      pair: "Toolbar → items",
      observed:
        "flex flex-wrap items-center justify-between gap-3, with an ml-auto trailing cluster.",
      source: "plans.index.tsx results toolbar, admin page toolbars",
      consistency: "consistent",
      note: "ml-auto rather than a spacer element is the standard trailing-group technique.",
    },
    {
      pair: "Control → icon + label",
      observed: "inline-flex items-center gap-1.5 or gap-2 with an h-4 w-4 icon.",
      source: "action-pill.ts, marketplace-shell nav, buttons",
      consistency: "varies",
      note: "OBSERVED VARIATION — gap-1.5 and gap-2 both appear for the same icon/label relationship.",
    },
    {
      pair: "Flex child sizing",
      observed:
        "min-w-0 flex-1 for fluid children; shrink-0 for icons, rails and trailing actions.",
      source: "internal-shell, marketplace-shell, cart line items",
      consistency: "consistent",
      note: "min-w-0 is applied consistently to allow truncation inside flex rows.",
    },
    {
      pair: "Wrapping convention",
      observed:
        "flex-wrap on header/action rows; flex-col → sm:flex-row for stacked-to-inline blocks.",
      source: "cart.tsx add-ons banner, page headers",
      consistency: "mostly consistent" as unknown as "varies",
    },
  ],
};

export const DIMENSIONS: DimensionEntry[] = [
  {
    element: "Button height (default)",
    value: "h-9 (36px), px-4 py-2",
    occurrences: "Primitive default; 46 direct h-9 uses elsewhere",
    source: "components/ui/button.tsx",
    ownership: "primitive",
  },
  {
    element: "Button height (sm / lg / icon)",
    value: "sm h-8 px-3 text-xs · lg h-10 px-8 · icon h-9 w-9 · icon-sm h-8 w-8",
    occurrences: "Primitive variants",
    source: "components/ui/button.tsx",
    ownership: "primitive",
  },
  {
    element: "Input / select height",
    value: "h-9 px-3 py-1",
    occurrences: "Primitive default",
    source: "components/ui/input.tsx",
    ownership: "primitive",
  },
  {
    element: "Pill / marketplace control height",
    value: "h-10 (40px) — 142 uses, the most common explicit height in the app",
    occurrences: "142",
    source: "call sites, action-pill.ts",
    ownership: "pattern",
    note: "OBSERVED VARIATION — marketplace controls run 40px while primitive buttons run 36px. Both ship intentionally; the marketplace surface is deliberately larger.",
  },
  {
    element: "Large touch control",
    value: "h-11 (44px) — 69 uses; min-h-11 on 16 controls, min-h-10 on 3",
    occurrences: "69",
    source: "call sites",
    ownership: "pattern",
    note: "min-h-11 is the effective touch-target floor where it is applied; it is not applied universally.",
  },
  {
    element: "Icon button / small circle",
    value: "h-8 w-8, h-9 w-9",
    occurrences: "43 / 46",
    source: "internal-shell orb buttons, primitives",
    ownership: "pattern",
  },
  {
    element: "Icon size",
    value: "h-4 w-4 inline, h-5 w-5 nav/affordance, h-8 w-8 KPI glyph",
    occurrences: "Dominant across all surfaces",
    source: "call sites",
    ownership: "pattern",
  },
  {
    element: "Table cell height",
    value: "ABox DataTable px-5 py-4 (content-driven); shadcn table head h-10 px-2",
    occurrences: "2 implementations",
    source: "components/abox/data-table.tsx, components/ui/table.tsx",
    ownership: "business",
    note: "OBSERVED VARIATION — two table densities coexist.",
  },
  {
    element: "Filter rail width",
    value: "w-64 (256px) shrink-0, hidden below lg",
    occurrences: "1",
    source: "routes/plans.index.tsx",
    ownership: "local",
  },
  {
    element: "Summary column width",
    value: "320px (plan detail) · 360px (cart)",
    occurrences: "2",
    source: "route files",
    ownership: "local",
    note: "OBSERVED VARIATION.",
  },
  {
    element: "Admin navigation rail",
    value: "292px expanded · 104px collapsed (as left padding offset)",
    occurrences: "1",
    source: "components/abox/internal-shell.tsx",
    ownership: "business",
  },
  {
    element: "Dialog width",
    value: "w-full max-w-lg (512px)",
    occurrences: "Primitive default",
    source: "components/ui/dialog.tsx",
    ownership: "primitive",
  },
  {
    element: "Drawer width",
    value: "w-3/4 sm:max-w-sm (384px); mobile nav override w-[300px]",
    occurrences: "Primitive default plus one override",
    source: "components/ui/sheet.tsx, internal-shell.tsx",
    ownership: "primitive",
  },
  {
    element: "Viewport-relative sizing",
    value:
      "min-h-[calc(100svh-5.25rem)] hero · min-h-dvh shells · h-[min(620px,calc(100dvh-7rem))] and h-[min(560px,calc(100dvh-10rem))] panels · h-[80vh]",
    occurrences: "6",
    source: "routes/index.tsx, shells, assistant panels",
    ownership: "local",
    note: "svh/dvh used deliberately for mobile browser chrome.",
  },
  {
    element: "Reading-width caps",
    value: "max-w-3xl (15) for prose and headers · max-w-2xl (14) · max-w-md (11) · max-w-xs (7)",
    occurrences: "47 combined",
    source: "call sites",
    ownership: "pattern",
  },
];

export const LAYOUT_PATTERNS: LayoutPattern[] = [
  {
    name: "Marketplace page shell",
    purpose:
      "Public and shopping surfaces: floating glass header, fluid main, dark rounded footer.",
    anatomy: "skip link → sticky glass header → main flex-1 → footer in a rounded inset card",
    examples: "index.tsx, plans.index.tsx, cart.tsx, select.tsx, coverage.tsx",
    responsive: "Header nav items and brand tagline hide below md; footer grid collapses below md.",
    spacing:
      "Header sticky top-4 px-4/md:px-8; footer mx-4/md:mx-8 with px-6 py-16 → md:px-12 md:py-20.",
    shared: "shared",
    source: "components/abox/marketplace-shell.tsx",
    ownership: "business",
    maturity: "current",
  },
  {
    name: "Internal / admin shell",
    purpose: "Authenticated operational surfaces with a collapsible navigation rail.",
    anatomy:
      "rail → content offset → sticky glass topbar → optional masthead card → main + gap-6 row",
    examples: "all /app and /agency routes",
    responsive:
      "Rail hidden below lg and replaced by a Sheet drawer; topbar search hidden below lg.",
    spacing:
      "Topbar px-3/sm:px-4/lg:px-8 py-3; content px-4/md:px-8 pb-10/md:pb-16; masthead px-6 pt-6 pb-10 → md:px-12.",
    shared: "shared",
    source: "components/abox/internal-shell.tsx",
    ownership: "business",
    maturity: "current",
  },
  {
    name: "Member shell",
    purpose: "Account/settings surface with an icon rail linked by a decorative arc.",
    anatomy: "glass header → 88rem flex container → icon nav → content column",
    examples: "/member/settings",
    responsive: "Nav is a horizontal scroller on mobile, a vertical rail at md+.",
    spacing: "gap-8 between nav and content; pt-10 → md:pt-14 content offset.",
    shared: "shared",
    source: "components/abox/member-shell.tsx",
    ownership: "business",
    maturity: "current",
  },
  {
    name: "Page header",
    purpose: "Title, eyebrow/SCR label, optional icon plate and trailing actions.",
    anatomy: "FadeRise header → flex-wrap items-end justify-between → title stack + actions",
    examples: "shopping and member routes",
    responsive: "Icon aligns to start below md, centre at md+; actions wrap.",
    spacing: "mb-12 default, mb-6 compact; gap-4 between title stack and actions.",
    shared: "shared",
    source: "components/abox/page-header.tsx",
    ownership: "business",
    maturity: "current",
  },
  {
    name: "Results toolbar",
    purpose: "Count, mobile filter trigger and sort controls above a result list.",
    anatomy: "flex flex-wrap items-center justify-between gap-3 with ml-auto control cluster",
    examples: "routes/plans.index.tsx",
    responsive: "Filter trigger appears below lg; controls wrap on narrow widths.",
    spacing: "mb-4 to the results; inner gap-2 between sort controls.",
    shared: "local",
    source: "routes/plans.index.tsx",
    ownership: "local",
    maturity: "current",
    opportunity:
      "FUTURE OPPORTUNITY — the toolbar markup recurs in shape across shopping and admin lists but has no owning component.",
  },
  {
    name: "Filter rail",
    purpose: "Persistent faceted filters alongside results.",
    anatomy:
      "aside w-64 shrink-0 hidden lg:block → space-y-6 card → chip groups (flex flex-wrap gap-1.5)",
    examples: "routes/plans.index.tsx",
    responsive: "Hidden below lg; same filters surface through a trigger.",
    spacing: "rounded-2xl border p-4 with space-y-6 groups.",
    shared: "local",
    source: "routes/plans.index.tsx",
    ownership: "local",
    maturity: "current",
  },
  {
    name: "Card grid",
    purpose: "Equal-weight content or product cards.",
    anatomy: "grid gap-4/5 → sm:grid-cols-2 → md/lg:grid-cols-3|4",
    examples: "index.tsx feature grids, agency dashboards, app dashboards",
    responsive: "One column on mobile, two at sm, three or four at md/lg.",
    spacing: "gap-4 (product/admin), gap-5 (marketing), gap-6 (wide sections).",
    shared: "shared",
    source: "recurring call-site pattern",
    ownership: "pattern",
    maturity: "current",
    opportunity:
      "FUTURE OPPORTUNITY — genuinely recurring but unowned; a grid pattern could be documented as a class recipe.",
  },
  {
    name: "KPI row",
    purpose: "Dashboard metric summary.",
    anatomy: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4 → KpiCard",
    examples: "app dashboards, agency dashboards",
    responsive: "2-up at sm, 4-up at lg.",
    spacing: "gap-4; card interior p-5 with gap-3 between label stack and glyph.",
    shared: "shared",
    source: "components/abox/kpi-card.tsx plus call-site grid",
    ownership: "business",
    maturity: "current",
  },
  {
    name: "Data table",
    purpose: "Operational record lists.",
    anatomy: "overflow-x-auto → table → px-5 py-4 cells → hairline row borders",
    examples: "agency and app list routes",
    responsive: "Horizontal scroll rather than column collapse.",
    spacing: "px-5 py-4 cells; px-5 py-10 empty row.",
    shared: "shared",
    source: "components/abox/data-table.tsx",
    ownership: "business",
    maturity: "current",
  },
  {
    name: "Detail split with sticky summary",
    purpose: "Long content beside a persistent decision panel.",
    anatomy:
      "grid lg:grid-cols-[1fr_320px] (or [minmax(0,1fr)_360px]) → main space-y-6 → aside sticky top-24",
    examples: "plans.$planId.tsx, cart.tsx",
    responsive: "Collapses to a single column below lg; summary drops below content.",
    spacing: "gap-6 (detail), gap-5 (cart); aside space-y-4.",
    shared: "local",
    source: "route files",
    ownership: "pattern",
    maturity: "current",
    opportunity: "FUTURE OPPORTUNITY — same structure, two different widths and gaps.",
  },
  {
    name: "Empty state",
    purpose: "Zero-result and not-yet-configured surfaces.",
    anatomy: "dashed-border panel → 48px icon plate → display title → max-w-md body → action",
    examples: "shared across admin and shopping",
    responsive: "Centred at all widths; no breakpoint change.",
    spacing: "px-6 py-14 with gap-4 between elements.",
    shared: "shared",
    source: "components/abox/empty-state.tsx",
    ownership: "business",
    maturity: "current",
  },
  {
    name: "Dialog",
    purpose: "Focused confirmation and short forms.",
    anatomy: "overlay → fixed centred grid → header (space-y-1.5) → body → footer",
    examples: "primitive-driven across the app",
    responsive: "Full-width with rounded corners from sm up.",
    spacing: "p-6 with gap-4 between regions; close button at right-4 top-4.",
    shared: "shared",
    source: "components/ui/dialog.tsx",
    ownership: "primitive",
    maturity: "current",
  },
  {
    name: "Drawer / sheet",
    purpose: "Edge-anchored navigation and secondary panels.",
    anatomy: "overlay → edge-inset panel → optional custom header",
    examples: "internal-shell mobile navigation",
    responsive: "w-3/4 on mobile, capped at sm:max-w-sm above.",
    spacing: "p-6 default; nav drawer overrides to p-0 with px-5 py-5 header.",
    shared: "shared",
    source: "components/ui/sheet.tsx",
    ownership: "primitive",
    maturity: "current",
  },
  {
    name: "Wizard / stepper",
    purpose: "Multi-step downline onboarding.",
    anatomy: "stepper header → step content card → footer actions",
    examples: "agency.downlines.new.* routes",
    responsive: "Stepper scrolls horizontally on mobile.",
    spacing: "Inherits admin shell spacing; step cards use p-5.",
    shared: "shared",
    source: "components/abox/downline-wizard-stepper.tsx",
    ownership: "business",
    maturity: "current",
  },
  {
    name: "Mobile stacked layout",
    purpose: "Default single-column behaviour below sm.",
    anatomy: "All grids collapse to one column; rails hide; toolbars wrap.",
    examples: "every route",
    responsive: "Base styles are mobile; breakpoints add structure upward.",
    spacing: "px-4 gutter, gap-4 stacking.",
    shared: "shared",
    source: "mobile-first convention across the codebase",
    ownership: "pattern",
    maturity: "current",
  },
];
