/**
 * Phase 10 — pattern anatomy.
 * DOCUMENTATION ONLY. Every part below was read from the file named in its
 * evidence field. Where a slot has no owning component the record says so
 * rather than naming a component that does not exist.
 */
import type { PatternAnatomyRecord, PatternSpec } from "./pattern-spec-types";

/** The pattern taxonomy. Ids match the Phase 9 graph nodes exactly. */
export const PATTERN_SPECS: PatternSpec[] = [
  {
    id: "pat.page-header",
    name: "Page header",
    category: "page-structure",
    purpose: "Open a screen with its name, context and primary actions.",
    problem: "A reader arriving on a screen needs to know where they are before anything else.",
    contentModel: ["eyebrow or SCR id", "title", "optional description", "optional icon tile", "optional actions"],
    interaction: "Static. Actions are ordinary controls placed in the actions slot.",
    accessibility: "Renders as <header> with a single <h1>; the icon tile is aria-hidden.",
    ownership: "pattern",
    evidence: "src/components/abox/page-header.tsx, used in 25 files",
    experiences: ["exp.shop", "exp.dash", "exp.member"],
    screens: ["/plans", "/cart", "/agency/my-organization"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.results-toolbar",
    name: "Results toolbar",
    category: "selection-and-filtering",
    purpose: "Summarise how many results matched and let the reader reorder them.",
    problem: "A result set needs a count and a sort without pushing the results below the fold.",
    contentModel: ["result count line", "sort control", "quote edit entry point"],
    interaction: "Sorting re-orders the result list in place; the count follows the active filters.",
    accessibility: "The count is live text; the sort is a labelled select.",
    ownership: "pattern",
    evidence: "src/routes/plans.index.tsx with PageHeader variant=\"compact\"",
    experiences: ["exp.shop"],
    screens: ["/plans"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.filter-results",
    name: "Filter and results layout",
    category: "selection-and-filtering",
    purpose: "Show a filter rail beside a result collection.",
    problem: "A large result set needs narrowing without leaving the results.",
    contentModel: ["filter rail", "results toolbar", "result collection", "empty state"],
    interaction: "Filters apply immediately; counts update; selections persist across the session.",
    accessibility: "The rail is an <aside aria-label=\"Filters\">; below lg it becomes a dialog with aria-modal.",
    ownership: "pattern",
    evidence: "src/routes/plans.index.tsx lines 210-380",
    experiences: ["exp.shop"],
    screens: ["/plans"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.kpi-grid",
    name: "KPI grouping",
    category: "data-presentation",
    purpose: "Present a small set of headline metrics together.",
    problem: "A dashboard opens with numbers that must be scannable in one pass.",
    contentModel: ["metric label", "value", "optional delta", "optional icon", "optional hint"],
    interaction: "Hover lifts the card; values count up on mount.",
    accessibility: "Icons are aria-hidden; the label and value are plain text.",
    ownership: "pattern",
    evidence: "src/components/abox/kpi-card.tsx, used in 18 files",
    experiences: ["exp.dash"],
    screens: ["/agency/my-organization"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.table-screen",
    name: "List and table screen",
    category: "data-presentation",
    purpose: "Present rows of records with column headers and row actions.",
    problem: "Administrative work needs comparable rows, not cards.",
    contentModel: ["column headers", "rows", "empty row message", "optional row actions"],
    interaction: "Rows are read-only unless a route supplies actions.",
    accessibility: "DataTable takes an aria-label; the table has a 640px minimum width and scrolls.",
    ownership: "pattern",
    evidence: "src/components/abox/data-table.tsx in 20 files, alongside the primitive table and route-local tables",
    experiences: ["exp.dash"],
    screens: ["/agency/my-organization"],
    status: "OBSERVED DUPLICATE",
    note: "Three table implementations produce this pattern. No winner is chosen here.",
  },
  {
    id: "pat.detail-page",
    name: "Detail page layout",
    category: "page-structure",
    purpose: "Present one record: header, summary, then sectioned content.",
    problem: "A single record needs hierarchy, not a flat list of fields.",
    contentModel: ["page header", "summary block", "content sections"],
    interaction: "Sections are static; some routes add tabs.",
    accessibility: "One h1 from the page header; sections use their own headings.",
    ownership: "pattern",
    evidence: "Plan detail and governed record screens",
    experiences: ["exp.dash", "exp.shop"],
    screens: ["/plans/$planId"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.cart-summary",
    name: "Cart and quote summary",
    category: "commerce",
    purpose: "Show the selected coverage, the add-ons and the total together.",
    problem: "A buyer needs their selection and its cost visible at the same moment.",
    contentModel: ["selected coverage rows", "add-ons section", "total", "continue action"],
    interaction: "Editing the quote reopens the shared edit panel; removing a row updates the total.",
    accessibility: "Long plan names use the shared overflow text treatment with a title.",
    ownership: "pattern",
    evidence: "src/routes/cart.tsx, grid lg:grid-cols-[minmax(0,1fr)_360px]",
    experiences: ["exp.shop"],
    screens: ["/cart"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.hero",
    name: "Marketing hero",
    category: "page-structure",
    purpose: "Open the public site with a claim, supporting text and entry points.",
    problem: "A first-time visitor needs one clear statement and one obvious next step.",
    contentModel: ["display headline", "supporting paragraph", "product entry pills", "illustrative panel"],
    interaction: "Entry pills route into the shopping experience.",
    accessibility: "One h1; the decorative panel is not announced.",
    ownership: "local",
    evidence: "src/routes/index.tsx line 71, min-h-[calc(100svh-5.25rem)]",
    experiences: ["exp.web"],
    screens: ["/"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.settings-section",
    name: "Settings section",
    category: "input",
    purpose: "Group related preferences under one heading inside a panel.",
    problem: "Account preferences need grouping and space, not a dense form.",
    contentModel: ["section heading", "description", "fields or switches"],
    interaction: "Controls save through the route's own handlers.",
    accessibility: "Each control is labelled; the panel is the main landmark's child.",
    ownership: "pattern",
    evidence: "src/routes/member.settings.tsx inside MemberShell",
    experiences: ["exp.member"],
    screens: ["/member/settings"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.form-layout",
    name: "Form layout",
    category: "input",
    purpose: "Lay out labelled fields, help text and a submit row.",
    problem: "Data entry needs consistent label, control and error placement.",
    contentModel: ["label", "control", "help text", "error text", "submit row"],
    interaction: "Validation and submission are owned by each route.",
    accessibility: "Primitive inputs carry aria-invalid; route-local field systems vary.",
    ownership: "pattern",
    evidence: "Settings and governed module forms; three field systems produce it",
    experiences: ["exp.dash", "exp.member"],
    screens: ["/member/settings"],
    status: "OBSERVED DUPLICATE",
  },
  {
    id: "pat.empty-loading-error",
    name: "Empty, loading and error presentation",
    category: "feedback",
    purpose: "Tell the reader why a region has nothing in it.",
    problem: "An absent result must be explained, not left blank.",
    contentModel: ["icon", "title", "body", "optional action"],
    interaction: "The action, when present, is the recovery route.",
    accessibility: "Empty state is plain text with an aria-hidden icon.",
    ownership: "pattern",
    evidence: "src/components/abox/empty-state.tsx in 10 files; Skeleton in 4; error markup written per route",
    experiences: ["exp.shop", "exp.dash"],
    screens: ["/plans"],
    status: "UNOWNED AREA",
    note: "Empty has an owner. Loading and error do not.",
  },
  {
    id: "pat.status-tier",
    name: "Status and tier presentation",
    category: "data-presentation",
    purpose: "Show a record's standing or a plan's metal tier as a solid badge.",
    problem: "Standing must be readable at a glance and keep its contrast on any background.",
    contentModel: ["tone", "label"],
    interaction: "Static. In filters the same treatment doubles as a toggle.",
    accessibility: "Foreground is chosen against the badge background; filters use aria-pressed.",
    ownership: "pattern",
    evidence: "src/components/abox/status-badge.tsx (89 files) and metal-badge.tsx",
    experiences: ["exp.shop", "exp.dash"],
    screens: ["/plans"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.comparison",
    name: "Comparison layout",
    category: "commerce",
    purpose: "Place selected plans side by side against the same attributes.",
    problem: "A buyer comparing plans needs attributes aligned on one row.",
    contentModel: ["attribute rows", "one column per plan"],
    interaction: "Plans are chosen before entering the comparison.",
    accessibility: "Route-local markup; no shared contract.",
    ownership: "local",
    evidence: "src/routes/compare.tsx composes its own markup rather than the plan card",
    experiences: ["exp.shop"],
    screens: ["/compare"],
    status: "OBSERVED VARIATION",
  },
  {
    id: "pat.navigation",
    name: "Shell navigation",
    category: "navigation",
    purpose: "Give each experience its own persistent way to move around.",
    problem: "Three audiences need three different navigation models.",
    contentModel: ["brand", "primary destinations", "account control", "context actions"],
    interaction: "Internal uses a collapsible left rail; marketplace and member use a floating header.",
    accessibility: "Internal exposes an 'Open navigation' button below lg; member turns its rail into a scrollable row.",
    ownership: "business",
    evidence: "internal-shell.tsx (89 files), marketplace-shell.tsx (30), member-shell.tsx",
    experiences: ["exp.web", "exp.shop", "exp.dash", "exp.member"],
    screens: ["/", "/plans", "/agency/my-organization", "/member/settings"],
    status: "OBSERVED OVERLAP",
    note: "Each shell implements navigation independently. That is recorded, not corrected.",
  },
  {
    id: "pat.wizard",
    name: "Stepped wizard",
    category: "navigation",
    purpose: "Break a long task into numbered steps with visible progress.",
    problem: "A multi-step task needs a sense of where the reader is.",
    contentModel: ["numbered steps", "done marks", "current step", "step content"],
    interaction: "Completed steps show a check; upcoming steps are dimmed.",
    accessibility: "Rendered as an <ol>; the check icon is aria-hidden.",
    ownership: "business",
    evidence: "src/components/abox/downline-wizard-stepper.tsx",
    experiences: ["exp.dash"],
    screens: ["/agency/my-organization"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.assistant",
    name: "Assistant surface",
    category: "conversation",
    purpose: "Offer guided help alongside the task the reader is doing.",
    problem: "A shopper or operator may want guidance without leaving the screen.",
    contentModel: ["message list", "composer", "suggested prompts"],
    interaction: "State persists for the session; the surface can be opened from shopping screens.",
    accessibility: "Varies by implementation; no single contract.",
    ownership: "local",
    evidence: "planai-assistant.tsx, plan-o-assistant.tsx and the ai-elements route kit",
    experiences: ["exp.shop", "exp.dash"],
    screens: ["/plans"],
    status: "OBSERVED DUPLICATE",
  },
  {
    id: "pat.card-collection",
    name: "Card collection",
    category: "data-presentation",
    purpose: "Present comparable records as a responsive grid of cards.",
    problem: "Records with mixed content read better as cards than as rows.",
    contentModel: ["card grid", "card per record"],
    interaction: "Cards may be selectable; the plan results grid is single column.",
    accessibility: "Each card is a normal container; interactive cards expose their own control.",
    ownership: "pattern",
    evidence: "src/routes/index.tsx grid md:grid-cols-3; src/routes/plans.index.tsx grid gap-4",
    experiences: ["exp.web", "exp.shop"],
    screens: ["/", "/plans"],
    status: "OBSERVED VARIATION",
    note: "Column counts differ by route. Both are kept.",
  },
  {
    id: "pat.split-layout",
    name: "Split layout",
    category: "page-structure",
    purpose: "Pair a main column with a narrower supporting column.",
    problem: "A summary must stay visible beside the primary content.",
    contentModel: ["main column", "supporting column"],
    interaction: "Below lg the columns stack.",
    accessibility: "Source order puts the main column first.",
    ownership: "pattern",
    evidence: "src/routes/cart.tsx lg:grid-cols-[minmax(0,1fr)_360px]; index.tsx lg:grid-cols-[1.15fr_1fr]",
    experiences: ["exp.web", "exp.shop"],
    screens: ["/", "/cart"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.dialog-drawer",
    name: "Dialog and drawer composition",
    category: "feedback",
    purpose: "Move a secondary surface over the page when space runs out.",
    problem: "The filter rail has nowhere to live on a narrow screen.",
    contentModel: ["overlay", "panel", "close control", "panel content"],
    interaction: "Opens from a control; closes on the close button or the overlay.",
    accessibility: "role=\"dialog\" with aria-modal and an accessible name.",
    ownership: "pattern",
    evidence: "src/routes/plans.index.tsx line 374, plus the dialog primitive in 4 files",
    experiences: ["exp.shop", "exp.dash"],
    screens: ["/plans"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.section-header",
    name: "Section header",
    category: "page-structure",
    purpose: "Introduce a block inside a page without competing with the page title.",
    problem: "Long pages need internal signposts.",
    contentModel: ["eyebrow", "heading", "optional lead paragraph"],
    interaction: "Static.",
    accessibility: "Uses h2 inside a section element.",
    ownership: "none",
    evidence: "Repeated inline in src/routes/index.tsx; no shared component owns it",
    experiences: ["exp.web"],
    screens: ["/"],
    status: "UNOWNED AREA",
  },
  {
    id: "pat.action-group",
    name: "Action group",
    category: "navigation",
    purpose: "Place related actions together with consistent shape and spacing.",
    problem: "Actions scattered at different sizes read as unrelated.",
    contentModel: ["primary action", "secondary actions"],
    interaction: "Ordinary controls; the shared pill class string sets the shape.",
    accessibility: "Each action is a real button or link.",
    ownership: "pattern",
    evidence: "ACTION_PILL in 35 files, 82 references",
    experiences: ["exp.web", "exp.shop", "exp.dash", "exp.member"],
    screens: ["/", "/plans", "/cart"],
    status: "CURRENT IMPLEMENTATION",
  },
  {
    id: "pat.canonical-data",
    name: "Canonical data screen",
    category: "data-presentation",
    purpose: "Proposed single contract covering toolbar, filters, table, summary and pagination.",
    problem: "Not established.",
    contentModel: ["proposed only"],
    interaction: "Not established.",
    accessibility: "Not established.",
    ownership: "none",
    evidence: "Nothing implements this.",
    experiences: [],
    screens: [],
    status: "FUTURE CANONICAL TARGET",
    futureTarget: "Would replace the three table implementations with one contract.",
    migrationNote: "No migration has been started and no first consumer has been named.",
  },
  {
    id: "pat.pagination",
    name: "Pagination",
    category: "data-presentation",
    purpose: "Not established from the current code.",
    problem: "Not established.",
    contentModel: [],
    interaction: "Not established.",
    accessibility: "Not established.",
    ownership: "none",
    evidence: "The pagination primitive is installed but no production route consumes it.",
    experiences: [],
    screens: [],
    status: "FUTURE DECISION",
    note: "FUTURE DECISION — insufficient implementation evidence.",
  },
];

export const PATTERN_ANATOMY: PatternAnatomyRecord[] = [
  {
    patternId: "pat.page-header",
    name: "Page header",
    order: "eyebrow → icon tile + title → description → actions → hairline rule",
    status: "CURRENT IMPLEMENTATION",
    parts: [
      { part: "Eyebrow / SCR id", filledBy: "text-eyebrow paragraph", required: false, evidence: "page-header.tsx line 29", status: "CURRENT IMPLEMENTATION", note: "Hidden in the compact variant." },
      { part: "Icon tile", filledBy: "rounded-2xl bordered tile, h-12 w-12 (h-9 compact)", required: false, evidence: "page-header.tsx lines 32-38", status: "CURRENT IMPLEMENTATION" },
      { part: "Title", filledBy: "h1, text-display text-3xl md:text-4xl (text-xl md:text-2xl compact)", required: true, evidence: "page-header.tsx lines 39-46", status: "CURRENT IMPLEMENTATION" },
      { part: "Description", filledBy: "muted paragraph, text-lg (text-xs compact)", required: false, evidence: "page-header.tsx line 49", status: "CURRENT IMPLEMENTATION" },
      { part: "Actions", filledBy: "flex-wrap action group", required: false, evidence: "page-header.tsx line 54", status: "CURRENT IMPLEMENTATION" },
      { part: "Hairline rule", filledBy: "animated 1px rule", required: false, evidence: "page-header.tsx line 57", status: "CURRENT IMPLEMENTATION", note: "Default variant only." },
    ],
  },
  {
    patternId: "pat.filter-results",
    name: "Filter and results layout",
    order: "compact header → filter rail beside results → result collection → empty state",
    status: "CURRENT IMPLEMENTATION",
    parts: [
      { part: "Filter rail", filledBy: "aside w-64, hidden below lg", required: true, evidence: "plans.index.tsx line 244", status: "CURRENT IMPLEMENTATION" },
      { part: "Filter trigger", filledBy: "rounded-full button, lg:hidden", required: true, evidence: "plans.index.tsx line 279", status: "CURRENT IMPLEMENTATION" },
      { part: "Filter dialog", filledBy: "fixed overlay with role=dialog", required: true, evidence: "plans.index.tsx line 374", status: "CURRENT IMPLEMENTATION" },
      { part: "Results toolbar", filledBy: "PageHeader variant=compact", required: true, evidence: "plans.index.tsx", status: "CURRENT IMPLEMENTATION" },
      { part: "Result collection", filledBy: "grid gap-4 of plan cards", required: true, evidence: "plans.index.tsx line 345", status: "CURRENT IMPLEMENTATION" },
      { part: "Empty state", filledBy: "EmptyState", required: false, evidence: "EmptyState in 10 files", status: "CURRENT IMPLEMENTATION" },
    ],
  },
  {
    patternId: "pat.kpi-grid",
    name: "KPI grouping",
    order: "label → value → delta chip, with a corner icon tile",
    status: "CURRENT IMPLEMENTATION",
    parts: [
      { part: "Label", filledBy: "text-eyebrow", required: true, evidence: "kpi-card.tsx line 44", status: "CURRENT IMPLEMENTATION" },
      { part: "Value", filledBy: "tabular numeric with count-up", required: true, evidence: "kpi-card.tsx CountUp", status: "CURRENT IMPLEMENTATION" },
      { part: "Delta chip", filledBy: "pill", required: false, evidence: "kpi-card.tsx delta prop", status: "CURRENT IMPLEMENTATION" },
      { part: "Icon tile", filledBy: "tone-tinted corner tile", required: false, evidence: "kpi-card.tsx TONE map", status: "CURRENT IMPLEMENTATION" },
      { part: "Hint", filledBy: "muted caption", required: false, evidence: "kpi-card.tsx hint prop", status: "CURRENT IMPLEMENTATION" },
    ],
  },
  {
    patternId: "pat.table-screen",
    name: "List and table screen",
    order: "column headers → rows → empty row message",
    status: "OBSERVED DUPLICATE",
    parts: [
      { part: "Header cells", filledBy: "px-5 py-4 font-semibold", required: true, evidence: "data-table.tsx line 38", status: "CURRENT IMPLEMENTATION" },
      { part: "Body cells", filledBy: "px-5 py-4", required: true, evidence: "data-table.tsx line 70", status: "CURRENT IMPLEMENTATION" },
      { part: "Empty row", filledBy: "px-5 py-10 centred muted text", required: false, evidence: "data-table.tsx line 52", status: "CURRENT IMPLEMENTATION" },
      { part: "Minimum width", filledBy: "min-w-[640px] with horizontal scroll", required: true, evidence: "data-table.tsx line 29", status: "CURRENT IMPLEMENTATION" },
      { part: "Pagination", filledBy: "no owner", required: false, evidence: "No production route paginates a DataTable", status: "FUTURE DECISION", note: "FUTURE DECISION — insufficient implementation evidence." },
    ],
  },
  {
    patternId: "pat.cart-summary",
    name: "Cart and quote summary",
    order: "selected coverage → add-ons → total → continue",
    status: "CURRENT IMPLEMENTATION",
    parts: [
      { part: "Selected coverage rows", filledBy: "card rows with overflow text", required: true, evidence: "cart.tsx", status: "CURRENT IMPLEMENTATION" },
      { part: "Add-ons section", filledBy: "tinted bordered block with Sparkles icon", required: true, evidence: "cart.tsx add-ons block", status: "CURRENT IMPLEMENTATION" },
      { part: "Summary column", filledBy: "360px fixed column above lg", required: true, evidence: "cart.tsx line 84", status: "CURRENT IMPLEMENTATION" },
      { part: "Total", filledBy: "formatted $#,##0.00", required: true, evidence: "cart.tsx", status: "CURRENT IMPLEMENTATION" },
    ],
  },
  {
    patternId: "pat.empty-loading-error",
    name: "Empty, loading and error presentation",
    order: "icon tile → title → body → action",
    status: "UNOWNED AREA",
    parts: [
      { part: "Icon tile", filledBy: "h-12 w-12 bordered tile", required: false, evidence: "empty-state.tsx line 18", status: "CURRENT IMPLEMENTATION" },
      { part: "Title", filledBy: "text-display text-2xl", required: true, evidence: "empty-state.tsx line 23", status: "CURRENT IMPLEMENTATION" },
      { part: "Body", filledBy: "max-w-md text-sm muted", required: false, evidence: "empty-state.tsx line 24", status: "CURRENT IMPLEMENTATION" },
      { part: "Action", filledBy: "caller-supplied node", required: false, evidence: "empty-state.tsx line 25", status: "CURRENT IMPLEMENTATION" },
      { part: "Loading equivalent", filledBy: "Skeleton, no shared composition", required: false, evidence: "Skeleton in 4 files", status: "UNOWNED AREA" },
      { part: "Error equivalent", filledBy: "written per route", required: false, evidence: "No error component exists", status: "UNOWNED AREA" },
    ],
  },
  {
    patternId: "pat.navigation",
    name: "Shell navigation",
    order: "brand → destinations → search → account, per shell",
    status: "OBSERVED OVERLAP",
    parts: [
      { part: "Internal left rail", filledBy: "fixed rail, lg:flex, collapsible to 104px", required: true, evidence: "internal-shell.tsx lines 63, 160", status: "CURRENT IMPLEMENTATION" },
      { part: "Internal mobile trigger", filledBy: "h-9 w-9 button, lg:hidden", required: true, evidence: "internal-shell.tsx line 74", status: "CURRENT IMPLEMENTATION" },
      { part: "Marketplace floating header", filledBy: "glass rounded-full header, sticky top-4", required: true, evidence: "marketplace-shell.tsx lines 57-58", status: "CURRENT IMPLEMENTATION" },
      { part: "Member side nav", filledBy: "aside md:w-60 with a scrollable row below md", required: true, evidence: "member-shell.tsx lines 97-101", status: "CURRENT IMPLEMENTATION" },
      { part: "Account control", filledBy: "name plus chevron, no button chrome", required: true, evidence: "marketplace-shell.tsx line 105", status: "CURRENT IMPLEMENTATION" },
    ],
  },
  {
    patternId: "pat.hero",
    name: "Marketing hero",
    order: "headline → paragraph → entry pills, beside an illustrative panel",
    status: "CURRENT IMPLEMENTATION",
    parts: [
      { part: "Viewport frame", filledBy: "min-h-[calc(100svh-5.25rem)] centred", required: true, evidence: "index.tsx line 71", status: "CURRENT IMPLEMENTATION" },
      { part: "Headline", filledBy: "text-4xl sm:text-5xl md:text-6xl lg:text-7xl", required: true, evidence: "index.tsx line 76", status: "CURRENT IMPLEMENTATION" },
      { part: "Paragraph", filledBy: "text-lg md:text-xl muted", required: true, evidence: "index.tsx line 85", status: "CURRENT IMPLEMENTATION" },
      { part: "Entry pills", filledBy: "action pills with product icons", required: true, evidence: "index.tsx product chips", status: "CURRENT IMPLEMENTATION" },
      { part: "Illustrative panel", filledBy: "aspect-square code-drawn decor", required: false, evidence: "index.tsx line 116", status: "CURRENT IMPLEMENTATION" },
    ],
  },
  {
    patternId: "pat.wizard",
    name: "Stepped wizard",
    order: "numbered step chips in an ordered list → step content",
    status: "CURRENT IMPLEMENTATION",
    parts: [
      { part: "Step list", filledBy: "ol flex-wrap gap-1.5", required: true, evidence: "downline-wizard-stepper.tsx line 35", status: "CURRENT IMPLEMENTATION" },
      { part: "Step chip", filledBy: "rounded-full px-2.5 py-1.5 text-xs", required: true, evidence: "downline-wizard-stepper.tsx line 47", status: "CURRENT IMPLEMENTATION" },
      { part: "Done mark", filledBy: "Check icon h-3 w-3", required: false, evidence: "downline-wizard-stepper.tsx line 51", status: "CURRENT IMPLEMENTATION" },
      { part: "Upcoming step", filledBy: "muted chip at 50% foreground", required: false, evidence: "downline-wizard-stepper.tsx line 55", status: "CURRENT IMPLEMENTATION" },
    ],
  },
  {
    patternId: "pat.dialog-drawer",
    name: "Dialog and drawer composition",
    order: "overlay → panel → close → content",
    status: "CURRENT IMPLEMENTATION",
    parts: [
      { part: "Overlay", filledBy: "fixed inset-0 z-40", required: true, evidence: "plans.index.tsx line 374", status: "CURRENT IMPLEMENTATION" },
      { part: "Panel", filledBy: "route-local panel, or the dialog primitive", required: true, evidence: "plans.index.tsx; dialog primitive in 4 files", status: "OBSERVED VARIATION" },
      { part: "Accessible name", filledBy: "aria-label on the dialog container", required: true, evidence: "plans.index.tsx line 374", status: "CURRENT IMPLEMENTATION" },
    ],
  },
];
