/**
 * Phase 10 — observed pattern variants.
 * DOCUMENTATION ONLY. Every entry is a difference that really exists in the
 * code. No winner is chosen, nothing is ranked or scored, and the most common
 * form is never treated as canonical for that reason alone.
 */
import type { PatternVariantRecord } from "./pattern-spec-types";

export const PATTERN_VARIANTS: PatternVariantRecord[] = [
  {
    patternId: "pat.page-header",
    variant: "Default",
    difference:
      "Eyebrow shown, h-12/h-14 icon tile, text-3xl md:text-4xl display title, mb-12, closing hairline rule.",
    seenIn: "Most PageHeader consumers",
    keptBecause: "It is the opening header for a full screen.",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.page-header",
    variant: "Compact",
    difference:
      "No eyebrow, h-9 icon tile, text-xl md:text-2xl title, mb-6, no hairline rule, text-xs description.",
    seenIn: "Plan results header",
    keptBecause: "A results screen must keep the results near the top.",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.table-screen",
    variant: "DataTable",
    difference: "px-5 py-4 cells, min-w-[640px], built-in empty row, aria-label required.",
    seenIn: "20 files",
    keptBecause: "It is the shared administrative table.",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.table-screen",
    variant: "Primitive table",
    difference: "Unopinionated table primitive with per-route cell padding.",
    seenIn: "Route-local admin screens",
    keptBecause: "Some screens need cell control the shared table does not offer.",
    status: "OBSERVED DUPLICATE",
  },
  {
    patternId: "pat.table-screen",
    variant: "Route-local tables",
    difference: "Markup written inside the route with its own density.",
    seenIn: "Governed module screens",
    keptBecause: "Recorded as it is; changing it is a production change.",
    status: "OBSERVED DUPLICATE",
  },
  {
    patternId: "pat.card-collection",
    variant: "Three-column marketing grid",
    difference: "grid gap-5 md:grid-cols-3.",
    seenIn: "src/routes/index.tsx line 183",
    keptBecause: "Marketing cards are short and read well in threes.",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.card-collection",
    variant: "Single-column results list",
    difference: "grid gap-4, one plan card per row at every width.",
    seenIn: "src/routes/plans.index.tsx line 345",
    keptBecause: "Plan cards carry too much detail to sit side by side.",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.split-layout",
    variant: "Cart split",
    difference: "lg:grid-cols-[minmax(0,1fr)_360px] with a fixed summary column.",
    seenIn: "src/routes/cart.tsx line 84",
    keptBecause: "The summary needs a stable width.",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.split-layout",
    variant: "Hero split",
    difference: "lg:grid-cols-[1.15fr_1fr] with proportional columns and gap-12/lg:gap-14.",
    seenIn: "src/routes/index.tsx line 74",
    keptBecause: "The hero panel scales with the viewport rather than holding a width.",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.split-layout",
    variant: "Member split",
    difference: "md:flex-row with a md:w-60 rail, stacking below md rather than lg.",
    seenIn: "src/components/abox/member-shell.tsx line 95",
    keptBecause: "The member rail is narrow enough to survive at md.",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.navigation",
    variant: "Internal left rail",
    difference:
      "Fixed rail from lg, collapsible between 292px and 104px, with a sticky glass top bar.",
    seenIn: "internal-shell.tsx",
    keptBecause: "Operators need deep navigation always in view.",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.navigation",
    variant: "Marketplace floating header",
    difference: "Sticky rounded-full glass bar, links hidden below md.",
    seenIn: "marketplace-shell.tsx lines 57, 197",
    keptBecause: "Shoppers need a light header, not a rail.",
    status: "OBSERVED OVERLAP",
  },
  {
    patternId: "pat.navigation",
    variant: "Member header plus side list",
    difference: "Centred header with a scrollable horizontal nav below md.",
    seenIn: "member-shell.tsx lines 68, 101",
    keptBecause: "The member area has few destinations.",
    status: "OBSERVED OVERLAP",
  },
  {
    patternId: "pat.action-group",
    variant: "Hero pills at h-11",
    difference: "Larger call-to-action height on the landing hero.",
    seenIn: "src/routes/index.tsx",
    keptBecause: "Intentional marketing prominence.",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.action-group",
    variant: "Shared pill class string",
    difference: "One centralised class string used in 35 files, 82 references.",
    seenIn: "src/components/abox/action-pill.ts",
    keptBecause: "Already centralised in an earlier phase without changing output.",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.form-layout",
    variant: "Primitive fields",
    difference: "Input, Label and Select primitives with h-9 controls.",
    seenIn: "Settings and simple forms",
    keptBecause: "Shared primitive behaviour.",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.form-layout",
    variant: "Route-local field systems",
    difference: "Governed module kits render their own label, control and help arrangement.",
    seenIn: "M06 and M08 route kits",
    keptBecause: "The governed modules own their own field contracts.",
    status: "OBSERVED DUPLICATE",
  },
  {
    patternId: "pat.dialog-drawer",
    variant: "Route-local filter overlay",
    difference: "fixed inset-0 panel written in the route rather than the dialog primitive.",
    seenIn: "src/routes/plans.index.tsx line 374",
    keptBecause: "It predates and differs from the primitive; both are kept.",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.assistant",
    variant: "PlanAI, Plan-O and the ai-elements kit",
    difference: "Three conversational surfaces with separate composition and state handling.",
    seenIn: "planai-assistant.tsx, plan-o-assistant.tsx, ai-elements",
    keptBecause: "Each serves a different experience; no consolidation is approved.",
    status: "OBSERVED DUPLICATE",
  },
];
