/**
 * Phase 10 — pattern density modes.
 * DOCUMENTATION ONLY. Differences between modes are preserved exactly as the
 * code has them, including the 36px versus 40px control question that earlier
 * phases left open.
 */
import type { PatternDensityRecord } from "./pattern-spec-types";

export const PATTERN_DENSITY: PatternDensityRecord[] = [
  {
    patternId: "pat.page-header",
    mode: "Default header",
    controlHeight: "Actions use the shared pill height",
    padding: "mb-12 below the header, mt-10 above the hairline",
    gap: "gap-4 between title block and actions",
    typography: "text-display text-3xl md:text-4xl title, text-lg description",
    iconSize: "h-6 w-6 md:h-7 w-7 inside an h-12/h-14 tile",
    evidence: "page-header.tsx lines 27-57",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.page-header",
    mode: "Compact header",
    controlHeight: "Same action height as the default",
    padding: "mb-6, no hairline",
    gap: "gap-4",
    typography: "text-xl md:text-2xl title, text-xs description",
    iconSize: "h-4 w-4 inside an h-9 tile",
    evidence: "page-header.tsx isCompact branches",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.table-screen",
    mode: "DataTable standard",
    controlHeight: "n/a",
    padding: "px-5 py-4 in header and body cells; py-10 for the empty row",
    gap: "n/a — cell padding carries the rhythm",
    typography: "text-sm body, font-semibold headers",
    iconSize: "Row icons follow the caller",
    evidence: "data-table.tsx lines 29-70",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.table-screen",
    mode: "Route-local tables",
    controlHeight: "n/a",
    padding: "Varies by route",
    gap: "Varies by route",
    typography: "Varies by route",
    iconSize: "Varies by route",
    evidence: "Governed module screens write their own cells",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.kpi-grid",
    mode: "Metric card",
    controlHeight: "n/a",
    padding: "p-6",
    gap: "gap-3 between label block and icon tile",
    typography: "text-eyebrow label, large tabular numeric value",
    iconSize: "Large corner tile",
    evidence: "kpi-card.tsx line 38",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.empty-loading-error",
    mode: "Empty state",
    controlHeight: "Action follows the caller",
    padding: "px-6 py-14",
    gap: "gap-4",
    typography: "text-display text-2xl title, text-sm body",
    iconSize: "h-5 w-5 in an h-12 tile",
    evidence: "empty-state.tsx lines 14-25",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.wizard",
    mode: "Step chips",
    controlHeight: "Chip height from px-2.5 py-1.5",
    padding: "px-2.5 py-1.5",
    gap: "gap-1.5",
    typography: "text-xs font-medium",
    iconSize: "h-3 w-3 check mark",
    evidence: "downline-wizard-stepper.tsx lines 35-55",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.navigation",
    mode: "Internal top bar",
    controlHeight: "h-9 icon buttons, h-10 account control",
    padding: "px-3 py-3 sm:px-4 lg:px-8 around a px-2 py-2 sm:px-3 glass bar",
    gap: "gap-2 sm:gap-3, gap-0.5 sm:gap-1 in the right cluster",
    typography: "text-sm",
    iconSize: "Icon buttons at h-9 w-9",
    evidence: "internal-shell.tsx lines 66-99, 353",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.navigation",
    mode: "Marketplace header",
    controlHeight: "Links at px-4 py-2",
    padding: "pl-3 pr-2 py-2 md:pl-4",
    gap: "gap-2 in the bar, gap-1.5 inside a link",
    typography: "text-sm font-medium",
    iconSize: "Product icons beside the label",
    evidence: "marketplace-shell.tsx lines 58, 197",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.navigation",
    mode: "Member navigation",
    controlHeight: "36px icon circles with a centred connecting arc",
    padding: "p-6 md:p-10 in the main panel",
    gap: "gap-1 below md, md:gap-3 in the vertical rail",
    typography: "text-sm",
    iconSize: "36px circles",
    evidence: "member-shell.tsx lines 95-136",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.action-group",
    mode: "Standard pill",
    controlHeight: "Shared pill class string, 82 references across 35 files",
    padding: "From the shared class string",
    gap: "gap-2 between actions",
    typography: "text-sm font-medium",
    iconSize: "Leading icon at the pill's own size",
    evidence: "src/components/abox/action-pill.ts",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.action-group",
    mode: "Hero pill",
    controlHeight: "h-11",
    padding: "Wider than the standard pill",
    gap: "gap-2",
    typography: "Larger label",
    iconSize: "Product icon",
    evidence: "src/routes/index.tsx hero pills",
    status: "OBSERVED VARIATION",
  },
];

export const DENSITY_OPEN_QUESTIONS: string[] = [
  "OBSERVED VARIATION — control heights of 36px and 40px both exist. Neither has been declared correct.",
  "OBSERVED VARIATION — card padding is p-5 in some patterns and p-6 in the metric card.",
  "OBSERVED VARIATION — gap-1.5 and gap-2 are both used for the same kind of inline grouping.",
  "OBSERVED VARIATION — table density differs between the shared table and route-local tables.",
  "FUTURE DECISION — no density scale has been declared; these are observations, not a system.",
  "FUTURE OPPORTUNITY — settling any of the above changes production spacing and is out of scope for this phase.",
];
