/**
 * Phase 10 — pattern responsive behaviour.
 * DOCUMENTATION ONLY. Transcribed from the Tailwind classes the code already
 * carries. No breakpoint is introduced and no behaviour is normalised.
 */
import type { PatternResponsiveRecord } from "./pattern-spec-types";

export const PATTERN_RESPONSIVE: PatternResponsiveRecord[] = [
  {
    patternId: "pat.filter-results",
    breakpoint: "lg (1024px)",
    structuralChange:
      "The filter rail leaves the layout and becomes a modal dialog opened from a trigger.",
    desktop: "w-64 aside beside the results.",
    tablet: "No rail; a rounded-full 'Filters' trigger sits above the results.",
    mobile: "Same as tablet; the dialog fills the viewport.",
    reorders: true,
    controlsCollapse: true,
    columnsStack: true,
    densityChanges: false,
    evidence:
      "plans.index.tsx lines 244 (hidden lg:block), 279 (lg:hidden), 374 (fixed inset-0 lg:hidden)",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.page-header",
    breakpoint: "md (768px)",
    structuralChange:
      "Title and icon tile step up a size; alignment changes from items-start to items-center.",
    desktop: "text-4xl default title, h-14 icon tile.",
    tablet: "text-4xl from md; icon tile h-14.",
    mobile: "text-3xl title, h-12 icon tile, icon top-aligned to the title.",
    reorders: false,
    controlsCollapse: false,
    columnsStack: false,
    densityChanges: true,
    evidence: "page-header.tsx lines 31, 34, 41",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.cart-summary",
    breakpoint: "lg (1024px)",
    structuralChange: "The 360px summary column drops below the main column.",
    desktop: "Two columns, summary fixed at 360px.",
    tablet: "Single column, summary after the coverage rows.",
    mobile: "Single column; the header row switches from sm:flex-row to stacked.",
    reorders: false,
    controlsCollapse: false,
    columnsStack: true,
    densityChanges: true,
    evidence: "cart.tsx lines 35, 62, 84",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.hero",
    breakpoint: "lg (1024px) with type steps at sm and md",
    structuralChange:
      "The illustrative panel moves below the copy; the headline steps down four sizes.",
    desktop: "lg:grid-cols-[1.15fr_1fr], text-7xl headline, gap-14.",
    tablet: "Single column, text-6xl headline, gap-12.",
    mobile: "Single column, text-4xl headline, panel centred rather than right-aligned.",
    reorders: true,
    controlsCollapse: false,
    columnsStack: true,
    densityChanges: true,
    evidence: "index.tsx lines 71, 74, 76, 116",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.card-collection",
    breakpoint: "md (768px)",
    structuralChange:
      "Marketing card grids drop from three columns to one. The plan results grid does not change.",
    desktop: "md:grid-cols-3 for marketing; one column for plan results.",
    tablet: "Three columns from md.",
    mobile: "One column.",
    reorders: false,
    controlsCollapse: false,
    columnsStack: true,
    densityChanges: false,
    evidence: "index.tsx line 183; plans.index.tsx line 345",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.navigation",
    breakpoint: "lg for internal, md for marketplace and member, sm for label truncation",
    structuralChange: "Each shell collapses differently; there is no shared rule.",
    desktop:
      "Internal fixed rail with 292px content offset; marketplace shows its full link row; member shows a vertical rail with the connecting arc.",
    tablet:
      "Internal switches to an 'Open navigation' button; marketplace hides its links; member keeps the vertical rail from md.",
    mobile:
      "Member nav becomes a horizontally scrollable row; marketplace keeps only the brand, cart and account; account labels truncate from sm.",
    reorders: true,
    controlsCollapse: true,
    columnsStack: true,
    densityChanges: true,
    evidence:
      "internal-shell.tsx lines 63, 74, 89, 359; marketplace-shell.tsx lines 61, 92, 197; member-shell.tsx lines 72, 89, 95, 100, 101",
    status: "OBSERVED OVERLAP",
  },
  {
    patternId: "pat.table-screen",
    breakpoint: "None declared",
    structuralChange:
      "The table does not restructure. It keeps a 640px minimum width and scrolls horizontally.",
    desktop: "Full-width table.",
    tablet: "Horizontal scroll once the container is under 640px.",
    mobile: "Horizontal scroll; no card fallback exists.",
    reorders: false,
    controlsCollapse: false,
    columnsStack: false,
    densityChanges: false,
    evidence: "data-table.tsx line 29",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.split-layout",
    breakpoint: "lg for cart and hero, md for member",
    structuralChange: "Columns stack. The breakpoint differs by route.",
    desktop: "Two columns.",
    tablet: "Member stacks at md; cart and hero are still two columns until lg.",
    mobile: "Single column everywhere.",
    reorders: false,
    controlsCollapse: false,
    columnsStack: true,
    densityChanges: false,
    evidence: "cart.tsx line 84; index.tsx line 74; member-shell.tsx line 95",
    status: "OBSERVED VARIATION",
  },
  {
    patternId: "pat.wizard",
    breakpoint: "None declared",
    structuralChange: "Step chips wrap onto further lines rather than collapsing.",
    desktop: "One row of chips.",
    tablet: "Chips wrap.",
    mobile: "Chips wrap; no numeric-only fallback.",
    reorders: false,
    controlsCollapse: false,
    columnsStack: false,
    densityChanges: false,
    evidence: "downline-wizard-stepper.tsx line 35 (flex-wrap)",
    status: "CURRENT IMPLEMENTATION",
  },
  {
    patternId: "pat.dialog-drawer",
    breakpoint: "lg for the filter overlay",
    structuralChange: "The overlay exists only below lg; above it the content lives in the layout.",
    desktop: "Not rendered.",
    tablet: "Full-screen overlay.",
    mobile: "Full-screen overlay.",
    reorders: false,
    controlsCollapse: true,
    columnsStack: false,
    densityChanges: false,
    evidence: "plans.index.tsx line 374",
    status: "CURRENT IMPLEMENTATION",
  },
];

export const RESPONSIVE_PATTERN_NOTES: string[] = [
  "CURRENT IMPLEMENTATION — the codebase uses the default Tailwind breakpoints; sm, md and lg carry almost all structural change.",
  "OBSERVED VARIATION — the stacking breakpoint is not consistent: cart and hero stack at lg, member stacks at md.",
  "OBSERVED VARIATION — tables do not restructure at all; they scroll. No card fallback exists on any screen.",
  "UNOWNED AREA — no shared rule states which breakpoint a split layout should stack at.",
  "FUTURE OPPORTUNITY — aligning stacking breakpoints would change production layout and is therefore out of scope.",
];
