/**
 * Phase 2 — spacing source-of-truth audit.
 *
 * DOCUMENTATION ONLY. Every entry records what the production code already
 * does. Nothing here is imported by application screens, shells, business
 * components, UI primitives or business logic. Consumers: `/design-system`
 * and `/design-guide`.
 *
 * Occurrence counts were measured across `src/routes` and `src/components`
 * (reference pages excluded) and are approximate — they describe scale, not
 * an exact contract.
 */
import type { SpacingGroup } from "./types";

export const SPACING_SCALE: SpacingGroup = {
  id: "spacing-scale",
  title: "Observed spacing scale",
  summary:
    "The application uses Tailwind's default 0.25rem step scale. No custom spacing token exists in src/styles.css — spacing is expressed entirely through utility classes at the call site. These are the values that actually ship.",
  entries: [
    {
      value: "gap-1",
      computed: "0.25rem / 4px",
      occurrences: 232,
      purpose: "Tightest inline grouping — icon clusters, pill rows, inline meta separators.",
      where: "marketplace-shell nav, plan tile meta rows, badge clusters",
      frequency: "recurring",
      consistency: "consistent",
      source: "call site (Tailwind utility)",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "medium",
      note: "Frequently paired with gap-1.5 in the same region; both are in active use.",
    },
    {
      value: "gap-2",
      computed: "0.5rem / 8px",
      occurrences: 316,
      purpose: "Default icon-to-text and control-to-control gap. Most used spacing value in the app.",
      where: "buttons, nav links, filter chips, badge rows, toolbars",
      frequency: "recurring",
      consistency: "consistent",
      source: "call site; also baked into button.tsx base class",
      ownership: "pattern",
      centralizable: "safe",
      risk: "medium",
      note: "Button primitive hard-codes gap-2 in its base variant, making it the de-facto control gap.",
    },
    {
      value: "gap-3",
      computed: "0.75rem / 12px",
      occurrences: 173,
      purpose: "Grouping of small composite blocks — avatar/icon plus text stacks, header action clusters.",
      where: "internal-shell topbar, cart line items, KPI internals",
      frequency: "recurring",
      consistency: "mostly-consistent",
      source: "call site",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "medium",
    },
    {
      value: "gap-4",
      computed: "1rem / 16px",
      occurrences: 133,
      purpose: "Card-grid gutter and medium block separation.",
      where: "plan results grid (grid gap-4), plan detail stat grids, cart blocks",
      frequency: "recurring",
      consistency: "consistent",
      source: "call site",
      ownership: "pattern",
      centralizable: "safe",
      risk: "medium",
    },
    {
      value: "gap-5",
      computed: "1.25rem / 20px",
      occurrences: 10,
      purpose: "Wider card-grid gutter used in marketing and cart split layouts.",
      where: "landing feature grid, cart main/aside split",
      frequency: "occasional",
      consistency: "mostly-consistent",
      source: "call site",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "low",
    },
    {
      value: "gap-6",
      computed: "1.5rem / 24px",
      occurrences: 52,
      purpose: "Major region separation — filter rail to results, main column to sidebar.",
      where: "plans.index.tsx (flex gap-6), plans.$planId.tsx, internal-shell content row",
      frequency: "recurring",
      consistency: "consistent",
      source: "call site",
      ownership: "pattern",
      centralizable: "safe",
      risk: "high",
      note: "Controls the shopping split layout rhythm; changing it shifts every results page.",
    },
    {
      value: "gap-8 / gap-10 / gap-12 / gap-14",
      computed: "2rem – 3.5rem",
      occurrences: 21,
      purpose: "Marketing-scale separation between hero columns, footer columns and editorial blocks.",
      where: "index.tsx hero (gap-12, lg:gap-14), marketplace-shell footer (gap-14)",
      frequency: "occasional",
      consistency: "variable",
      source: "call site",
      ownership: "local",
      centralizable: "unsafe",
      risk: "high",
      note: "OBSERVED VARIATION — marketing sections tune these individually by composition.",
    },
  ],
};

export const SPACING_PADDING: SpacingGroup = {
  id: "spacing-padding",
  title: "Padding conventions",
  summary:
    "Padding splits into three families: page gutters (px-4 / md:px-8), card interiors (p-4, p-5, p-6) and control interiors (px-3/px-4 with py-2). The card family is the least uniform.",
  entries: [
    {
      value: "px-4 md:px-8",
      computed: "1rem → 2rem",
      occurrences: 154,
      purpose: "Standard page horizontal gutter for web-experience and member pages.",
      where: "index.tsx sections, plans.index.tsx, cart.tsx, member-shell, marketplace-shell header/footer",
      frequency: "recurring",
      consistency: "consistent",
      source: "call site, paired with max-w-[88rem]",
      ownership: "pattern",
      centralizable: "safe",
      risk: "high",
      note: "CURRENT IMPLEMENTATION — the closest thing the app has to a container contract, but it is repeated per page rather than owned by a component.",
    },
    {
      value: "px-3 sm:px-4 lg:px-8",
      computed: "0.75rem → 2rem",
      occurrences: 1,
      purpose: "Admin shell topbar gutter — tighter on mobile than the web experience.",
      where: "internal-shell.tsx topbar",
      frequency: "one-off",
      consistency: "one-off",
      source: "components/abox/internal-shell.tsx",
      ownership: "business",
      centralizable: "unsafe",
      risk: "medium",
      note: "OBSERVED VARIATION — admin uses a three-step gutter, web experience uses two.",
    },
    {
      value: "px-4 md:px-8 (admin content)",
      computed: "1rem → 2rem",
      occurrences: 1,
      purpose: "Admin shell content gutter, paired with max-w-[1500px].",
      where: "internal-shell.tsx content wrapper",
      frequency: "one-off",
      consistency: "one-off",
      source: "components/abox/internal-shell.tsx",
      ownership: "business",
      centralizable: "conditional",
      risk: "high",
    },
    {
      value: "p-5",
      computed: "1.25rem / 20px",
      occurrences: 187,
      purpose: "Most common card and panel interior padding across admin and shopping surfaces.",
      where: "KPI cards, filter panels, admin section cards, summary panels",
      frequency: "recurring",
      consistency: "mostly-consistent",
      source: "call site",
      ownership: "pattern",
      centralizable: "safe",
      risk: "high",
      note: "CURRENT IMPLEMENTATION — the de-facto card padding, but not owned by Card; the shadcn Card primitive uses p-6.",
    },
    {
      value: "p-6 (Card primitive)",
      computed: "1.5rem / 24px",
      occurrences: 48,
      purpose: "shadcn Card header/content/footer padding.",
      where: "components/ui/card.tsx, dialog.tsx, sheet.tsx",
      frequency: "recurring",
      consistency: "consistent",
      source: "components/ui/card.tsx, dialog.tsx, sheet.tsx",
      ownership: "primitive",
      centralizable: "safe",
      risk: "high",
      note: "OBSERVED VARIATION — primitive cards are p-6 while hand-rolled ABox cards are p-5 or p-4. Both ship today; neither is wrong.",
    },
    {
      value: "p-4",
      computed: "1rem / 16px",
      occurrences: 77,
      purpose: "Compact card / inline notice interior.",
      where: "plan results guidance banner, filter panels, admin sub-cards",
      frequency: "recurring",
      consistency: "mostly-consistent",
      source: "call site",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "medium",
    },
    {
      value: "p-3",
      computed: "0.75rem / 12px",
      occurrences: 70,
      purpose: "Dense strip / toolbar container padding.",
      where: "plans.index.tsx sort bar, product strips, compact chips containers",
      frequency: "recurring",
      consistency: "mostly-consistent",
      source: "call site",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "medium",
    },
    {
      value: "px-3 py-2 / px-4 py-2",
      computed: "0.75–1rem × 0.5rem",
      occurrences: 238 + 129,
      purpose: "Control interior padding for pills, chips, nav links and buttons.",
      where: "action-pill.ts, marketplace-shell nav, filter chips, dropdown items",
      frequency: "recurring",
      consistency: "consistent",
      source: "components/abox/action-pill.ts (centralized in Phase 1) plus call sites",
      ownership: "pattern",
      centralizable: "safe",
      risk: "medium",
    },
    {
      value: "px-5 py-4 (table cell)",
      computed: "1.25rem × 1rem",
      occurrences: 1,
      purpose: "Data table header and body cell padding.",
      where: "components/abox/data-table.tsx",
      frequency: "recurring",
      consistency: "consistent",
      source: "components/abox/data-table.tsx",
      ownership: "business",
      centralizable: "safe",
      risk: "medium",
      note: "OBSERVED VARIATION — the shadcn table primitive uses h-10 px-2 cells, a denser convention than the ABox DataTable.",
    },
    {
      value: "px-6 py-14 (empty state)",
      computed: "1.5rem × 3.5rem",
      occurrences: 1,
      purpose: "Empty-state vertical breathing room.",
      where: "components/abox/empty-state.tsx",
      frequency: "recurring",
      consistency: "consistent",
      source: "components/abox/empty-state.tsx",
      ownership: "business",
      centralizable: "safe",
      risk: "low",
    },
  ],
};

export const SPACING_RHYTHM: SpacingGroup = {
  id: "spacing-rhythm",
  title: "Vertical rhythm and stack spacing",
  summary:
    "Vertical rhythm is expressed with space-y-* inside blocks and py-* between sections. Marketing sections use a much larger vertical scale than product and admin surfaces.",
  entries: [
    {
      value: "space-y-1 / space-y-1.5",
      computed: "0.25–0.375rem",
      occurrences: 36,
      purpose: "Label-to-value and summary-row stacking inside cards.",
      where: "plan detail summary rows, cart totals, Card header (space-y-1.5)",
      frequency: "recurring",
      consistency: "consistent",
      source: "call site; components/ui/card.tsx header",
      ownership: "pattern",
      centralizable: "safe",
      risk: "low",
    },
    {
      value: "space-y-2 / space-y-3",
      computed: "0.5–0.75rem",
      occurrences: 57 + 33,
      purpose: "Field-to-field and list-item stacking.",
      where: "forms, filter groups, plan detail lists",
      frequency: "recurring",
      consistency: "mostly-consistent",
      source: "call site",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "medium",
    },
    {
      value: "space-y-4 / space-y-5 / space-y-6",
      computed: "1–1.5rem",
      occurrences: 35 + 42 + 16,
      purpose: "Block-to-block stacking inside a page column.",
      where: "cart main column (space-y-4), filter rail (space-y-6), admin sections (space-y-5)",
      frequency: "recurring",
      consistency: "variable",
      source: "call site",
      ownership: "pattern",
      centralizable: "conditional",
      risk: "high",
      note: "OBSERVED VARIATION — three adjacent values serve the same structural role in different routes.",
    },
    {
      value: "py-16 md:py-24",
      computed: "4rem → 6rem",
      occurrences: 7,
      purpose: "Standard marketing section vertical rhythm.",
      where: "index.tsx feature and closing sections",
      frequency: "recurring",
      consistency: "consistent",
      source: "routes/index.tsx",
      ownership: "local",
      centralizable: "conditional",
      risk: "high",
    },
    {
      value: "py-24 md:py-32",
      computed: "6rem → 8rem",
      occurrences: 9,
      purpose: "Emphasis marketing section — larger rhythm for narrative blocks.",
      where: "routes/index.tsx",
      frequency: "occasional",
      consistency: "consistent",
      source: "routes/index.tsx",
      ownership: "local",
      centralizable: "unsafe",
      risk: "high",
      note: "OBSERVED VARIATION — two marketing rhythms coexist intentionally (standard vs emphasis).",
    },
    {
      value: "pb-8 pt-4 md:pb-10 md:pt-6",
      computed: "asymmetric page padding",
      occurrences: 4,
      purpose: "Shopping page vertical padding — tight top, looser bottom.",
      where: "plans.index.tsx, plans.$planId.tsx, cart.tsx, coverage.tsx",
      frequency: "recurring",
      consistency: "consistent",
      source: "call site",
      ownership: "pattern",
      centralizable: "safe",
      risk: "medium",
      note: "CURRENT IMPLEMENTATION — the shopping surfaces share this exact string; an unowned but genuinely repeated pattern.",
    },
    {
      value: "pt-10 md:pt-14 (member)",
      computed: "2.5rem → 3.5rem",
      occurrences: 1,
      purpose: "Member settings content offset below the floating header.",
      where: "components/abox/member-shell.tsx",
      frequency: "one-off",
      consistency: "one-off",
      source: "components/abox/member-shell.tsx",
      ownership: "business",
      centralizable: "unsafe",
      risk: "medium",
      note: "Deliberate: compensates for the sticky top-4 glass header.",
    },
    {
      value: "mb-6 / mb-12 (PageHeader)",
      computed: "1.5rem / 3rem",
      occurrences: 2,
      purpose: "Header-to-content spacing — compact vs default PageHeader variants.",
      where: "components/abox/page-header.tsx",
      frequency: "recurring",
      consistency: "consistent",
      source: "components/abox/page-header.tsx",
      ownership: "business",
      centralizable: "safe",
      risk: "medium",
      note: "CURRENT IMPLEMENTATION — the one header-to-content relationship that is genuinely component-owned.",
    },
  ],
};

export const SPACING_GROUPS: SpacingGroup[] = [SPACING_SCALE, SPACING_PADDING, SPACING_RHYTHM];
