/**
 * Phase 7 — spacing foundation and spacing relationships.
 * DOCUMENTATION ONLY, built on the Phase 2 measurements. No `gap-*`,
 * `p-*` or `px-*` utility is replaced anywhere in production.
 */
import type { BlueprintRow } from "./types";

const P2 = "Phase 2 — spacing, layout, responsive" as const;

/** Evidence-derived candidate scale. Every step is a measured production value. */
export const SPACING_SCALE_SPEC: BlueprintRow[] = [
  {
    item: "4px — gap-1",
    source: "232 occurrences",
    current: "Tightest pairing: icon to micro label, badge dot to text, chip internals.",
    future: "Number variable Space / 100 = 4. Semantic purpose: bonded pair.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "6px — gap-1.5",
    source: "Used alongside gap-1 and gap-2 for the same purpose",
    current: "An intermediate step used in badges and inline groups.",
    future:
      "FUTURE DECISION — keep as Space / 150 or record as a variation of the 4px and 8px steps. Both readings fit the evidence.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "8px — gap-2",
    source: "316 occurrences — the most used spacing value in the product",
    current: "Default gap between related inline elements, buttons in a row, chips in a rail.",
    future: "Number variable Space / 200 = 8. The default inline gap.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "12px — gap-3 / px-3",
    source: "173 gap-3, 238 px-3 occurrences",
    current: "Control padding and the standard gap between grouped blocks.",
    future: "Number variable Space / 300 = 12. Control horizontal padding.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "16px — gap-4 / px-4",
    source: "133 gap-4, 154 px-4 occurrences",
    current: "Page gutter at the base width and the gap between cards in a grid.",
    future: "Number variable Space / 400 = 16. Mobile page gutter.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "20px — p-5",
    source: "187 occurrences",
    current: "The dominant card padding across ABox components and reference tables.",
    future: "Number variable Space / 500 = 20. Card padding.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
    note: "p-4 and p-6 also appear as card padding; the variation is preserved.",
  },
  {
    item: "24px — p-6 / gap-6",
    source: "Recurring in wider cards and section stacks",
    current: "Roomier card padding and the gap between sections inside a page block.",
    future: "Number variable Space / 600 = 24.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "32px — px-8 / py-8",
    source: "Desktop gutter, e.g. RefContainer px-4 md:px-8",
    current: "Page gutter from md upward.",
    future: "Number variable Space / 800 = 32. Desktop page gutter.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "40px / 48px / 56px — py-10, py-12, py-14",
    source: "Section rhythm on reference and web pages",
    current: "Vertical section separation, often expressed as py-10 md:py-14.",
    future: "Space / 1000, 1200, 1400 as section rhythm steps.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "Sub-4px values",
    source: "px-0.5, py-0.5 in badges",
    current: "2px padding inside pills and badges.",
    future: "Number variable Space / 050 = 2, scoped to micro components.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
];

export const SPACING_RELATIONSHIP_SPEC: BlueprintRow[] = [
  {
    item: "Page edge → content",
    source: "RefContainer, MarketplaceShell, web pages",
    current: "px-4 at base, px-8 from md. Consistent across web-experience pages.",
    future: "Rule: gutter = Space / 400 mobile, Space / 800 desktop.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "Header → content",
    source: "Member shell, marketplace shell",
    current:
      "Top spacing was added between the member header and the settings content; other shells set their own value.",
    future: "One header-to-content rule per shell family, recorded rather than unified.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "Section → section",
    source: "RefSection py-12; route sections py-10 md:py-14",
    current: "Vertical separation of 40 to 56px depending on surface.",
    future: "Two rules: dense sections and marketing sections.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "Title → supporting text",
    source: "PageHeader, RefSection, card headers",
    current: "mt-1 for tight pairs, mt-3 or mt-4 where the title is a display size.",
    future: "Rule scaled to the title role: micro titles use 4px, display titles use 12px.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "Heading → body",
    source: "Marketing and reference sections",
    current: "mt-3 to mt-4 below a heading before the first paragraph.",
    future: "Rule: Space / 300 minimum below any heading.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "Label → control",
    source: "Form fields across admin and shopping",
    current: "Label sits directly above with a 4 to 8px gap, applied per call site.",
    future: "A field pattern owning the label-to-control distance.",
    label: "UNOWNED AREA",
    phase: P2,
    note: "No shared form-field component owns this relationship today.",
  },
  {
    item: "Control → helper / error",
    source: "Form surfaces",
    current: "Helper and error text follow with a small top margin set at the call site.",
    future: "Part of the same future field pattern.",
    label: "UNOWNED AREA",
    phase: P2,
  },
  {
    item: "Field → field",
    source: "Forms",
    current: "space-y-4 is the common rhythm; space-y-3 and space-y-6 also occur.",
    future: "One field rhythm per density mode.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "Icon → text",
    source: "Buttons, nav links, badges, action pills",
    current:
      "gap-2 inside buttons and nav links; gap-1.5 inside badges; gap-1 for micro labels.",
    future: "Rule tied to text size: 8px at body, 6px at label, 4px at micro.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "Card edge → card content",
    source: "187 p-5, plus p-4 and p-6 instances",
    current: "20px dominates; 16px and 24px appear on denser and roomier cards.",
    future: "Card padding as a density-aware rule with three named steps.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "Card title → description",
    source: "RefBlock, KpiCard, PlanCard",
    current: "mt-1 with the description in a smaller muted size.",
    future: "Rule: Space / 100 between component title and its description.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "Content → action",
    source: "Cards with a footer action, dialogs",
    current: "mt-4 to mt-6 before the action row.",
    future: "Rule: Space / 400 minimum before a committing action.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
  {
    item: "Toolbar → results",
    source: "/plans results header, admin tables",
    current: "The compact results header sits directly above the list with a small gap.",
    future: "A results-toolbar pattern owning the distance.",
    label: "UNOWNED AREA",
    phase: P2,
  },
  {
    item: "Filter → results",
    source: "/plans two-column layout",
    current: "Filter rail and results column are separated by the grid gap, not by a margin.",
    future: "Rule expressed as a layout gap rather than per-element spacing.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "Table header → body",
    source: "DataTable, reference tables",
    current: "px-5 py-4 head, matching cell padding, separated by a hairline rule.",
    future: "Table density rule with head and cell padding in one record.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "Navigation rhythm",
    source: "InternalShell rail, marketplace header",
    current:
      "Rail items use a consistent vertical rhythm; the member shell draws a connecting arc through 36px icon circles.",
    future: "A navigation rhythm rule per shell family.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "Dialog / drawer sections",
    source: "Dialog and Drawer primitives",
    current: "Header, body and footer padding come from the shadcn defaults.",
    future: "Overlay spacing recorded as inherited from the primitive layer.",
    label: "CURRENT IMPLEMENTATION",
    phase: P2,
  },
  {
    item: "Grid / column gaps",
    source: "Card grids, KPI rows, two-column layouts",
    current: "gap-4 and gap-6 dominate; md:grid-cols-2 and lg:grid-cols-3 are the common shapes.",
    future: "Two grid gap steps, dense and roomy.",
    label: "OBSERVED VARIATION",
    phase: P2,
  },
];
