/**
 * Phase 2 — structural relationships, responsive behaviour and density audit.
 *
 * DOCUMENTATION ONLY. Records what production code does today. Consistency
 * is reported as found; nothing is normalized. Consumers: `/design-system`,
 * `/design-guide`.
 */
import type { DensityEntry, RelationshipGroup, ResponsivePattern } from "./types";

export const STRUCTURAL_RELATIONSHIPS: RelationshipGroup = {
  id: "structural-relationships",
  title: "Structural spacing relationships",
  summary:
    "Each row is a measured relationship between two adjacent structural elements, taken from the shipping implementation.",
  entries: [
    {
      pair: "Page edge → content edge",
      observed: "px-4 on mobile, md:px-8 from 768px. Admin topbar starts at px-3.",
      source: "web-experience routes, internal-shell.tsx",
      consistency: "consistent",
      note: "OBSERVED VARIATION — admin topbar uses a third step (px-3 → sm:px-4 → lg:px-8).",
    },
    {
      pair: "Container → first section",
      observed: "Shopping pt-4 → md:pt-6; marketing sections carry their own py-16/24.",
      source: "plans.index.tsx, cart.tsx, index.tsx",
      consistency: "varies",
    },
    {
      pair: "Section → section",
      observed: "py-16 md:py-24 standard; py-24 md:py-32 for emphasis sections.",
      source: "routes/index.tsx",
      consistency: "varies",
      note: "Two intentional marketing rhythms.",
    },
    {
      pair: "Section heading → supporting text",
      observed: "mt-3 with max-w-3xl on the supporting paragraph.",
      source: "reference and marketing sections, PageHeader description",
      consistency: "consistent",
    },
    {
      pair: "Supporting text → content",
      observed: "mt-8 in section wrappers; mt-4 in cards.",
      source: "section composition across routes",
      consistency: "varies",
    },
    {
      pair: "Header → content",
      observed: "PageHeader mb-12 default, mb-6 compact.",
      source: "components/abox/page-header.tsx",
      consistency: "consistent",
      note: "The only header-to-content relationship owned by a component.",
    },
    {
      pair: "Card edge → card content",
      observed: "p-5 on ABox cards, p-6 on shadcn Card, p-4 on compact cards, p-3 on strips.",
      source: "call sites, components/ui/card.tsx",
      consistency: "varies",
      note: "OBSERVED VARIATION — four interior paddings coexist for card-like surfaces.",
    },
    {
      pair: "Card content → action area",
      observed: "mt-4 / mt-5 before the action row; Card footer uses p-6 pt-0.",
      source: "cart summary, plan detail, components/ui/card.tsx",
      consistency: "varies",
    },
    {
      pair: "Grid → grid item",
      observed: "Gap only; grid items carry no outer margin.",
      source: "all grids",
      consistency: "consistent",
    },
    {
      pair: "Grid item → grid item",
      observed: "gap-4 product/admin, gap-5 marketing cards, gap-6 wide sections.",
      source: "call sites",
      consistency: "varies",
    },
    {
      pair: "Toolbar → filters",
      observed:
        "Toolbar sits above results with mb-4; the filter rail is a sibling column at gap-6.",
      source: "routes/plans.index.tsx",
      consistency: "consistent",
    },
    {
      pair: "Filters → results",
      observed: "flex gap-6 between the w-64 rail and the results column.",
      source: "routes/plans.index.tsx",
      consistency: "consistent",
    },
    {
      pair: "Sidebar → main content",
      observed:
        "Admin uses a padding offset (lg:pl-[292px] / lg:pl-[104px]) rather than a flex gap.",
      source: "components/abox/internal-shell.tsx",
      consistency: "consistent",
    },
    {
      pair: "Navigation → content",
      observed:
        "Member shell gap-8 between the icon rail and content; admin nav offset via padding.",
      source: "member-shell.tsx, internal-shell.tsx",
      consistency: "varies",
    },
    {
      pair: "Form field → form field",
      observed: "space-y-4 in forms; space-y-2/space-y-3 inside grouped field sets.",
      source: "agency wizard routes, settings forms",
      consistency: "varies",
    },
    {
      pair: "Label → control",
      observed:
        "Label sits directly above with the parent space-y-1.5 or space-y-2 governing the gap.",
      source: "form composition across routes",
      consistency: "mostly consistent" as unknown as "varies",
    },
    {
      pair: "Control → helper / error",
      observed: "mt-1 or mt-1.5 with text-xs text-muted-foreground.",
      source: "form composition across routes",
      consistency: "varies",
    },
    {
      pair: "Icon → text",
      observed: "gap-1.5 or gap-2 with an h-4 w-4 icon inside inline-flex items-center.",
      source: "action-pill.ts, nav links, buttons",
      consistency: "varies",
      note: "Both gaps are in active use; button.tsx bakes in gap-2.",
    },
    {
      pair: "Text → action",
      observed: "mt-4 / mt-5 / mt-6 before an inline-flex action, depending on surface.",
      source: "cart, marketing blocks, empty state",
      consistency: "varies",
    },
    {
      pair: "Table header → table body",
      observed: "border-b hairline separator; no additional spacing.",
      source: "components/abox/data-table.tsx",
      consistency: "consistent",
    },
    {
      pair: "Table row → table row",
      observed: "border-b border-hairline/60 with px-5 py-4 cell padding; last row border removed.",
      source: "components/abox/data-table.tsx",
      consistency: "consistent",
    },
    {
      pair: "Dialog header → body → footer",
      observed: "gap-4 grid regions; header internal space-y-1.5.",
      source: "components/ui/dialog.tsx",
      consistency: "consistent",
    },
    {
      pair: "Drawer sections",
      observed:
        "gap-4 panel regions; the admin nav drawer overrides to p-0 with a px-5 py-5 brand header.",
      source: "components/ui/sheet.tsx, internal-shell.tsx",
      consistency: "varies",
    },
    {
      pair: "Empty-state elements",
      observed: "gap-4 between icon plate, title, body and action; body capped at max-w-md.",
      source: "components/abox/empty-state.tsx",
      consistency: "consistent",
    },
    {
      pair: "Plan tile → plan tile",
      observed: "grid gap-4, single column at all widths.",
      source: "routes/plans.index.tsx",
      consistency: "consistent",
    },
    {
      pair: "Cart item → cart item",
      observed:
        "space-y-4 in the main column; action row indented with pl-[56px] to align under content.",
      source: "routes/cart.tsx",
      consistency: "consistent",
      note: "pl-[56px] is a deliberate optical alignment to the 40px icon plus gap-3.",
    },
  ],
};

export const RESPONSIVE_PATTERNS: ResponsivePattern[] = [
  {
    name: "Page gutter step",
    trigger: "md (768px)",
    desktop: "px-8",
    tablet: "px-8 from 768px up",
    mobile: "px-4",
    source: "web-experience routes, shells",
    consumers: "23 containers using max-w-[88rem] px-4 md:px-8",
    variations: "Admin topbar adds an sm step (px-3 → sm:px-4 → lg:px-8).",
  },
  {
    name: "Card grid columns",
    trigger: "sm (640px), md (768px), lg (1024px)",
    desktop: "3 or 4 columns",
    tablet: "2 columns",
    mobile: "1 column",
    source: "call sites",
    consumers: "sm:grid-cols-2 (53), md:grid-cols-2 (31), lg:grid-cols-4 (14), md:grid-cols-3 (11)",
    variations: "Some sections jump straight from 1 to 3 at md.",
  },
  {
    name: "Navigation rail",
    trigger: "lg (1024px)",
    desktop: "Persistent rail, content offset by 292px (104px collapsed)",
    tablet: "No rail — hamburger opens a Sheet drawer",
    mobile: "Sheet drawer at w-[300px]",
    source: "components/abox/internal-shell.tsx",
    consumers: "all /app and /agency routes",
    variations: "Collapse state is user-controlled and persists within the session.",
  },
  {
    name: "Filter rail",
    trigger: "lg (1024px)",
    desktop: "aside w-64 visible beside results",
    tablet: "Hidden; filter trigger button shown",
    mobile: "Hidden; filter trigger button shown",
    source: "routes/plans.index.tsx",
    consumers: "plan results",
    variations: "The trigger button itself is lg:hidden — the inverse of the rail.",
  },
  {
    name: "Split layout collapse",
    trigger: "lg (1024px)",
    desktop: "Two columns with a fixed summary (320px / 360px)",
    tablet: "Single column, summary below content",
    mobile: "Single column",
    source: "plans.$planId.tsx, cart.tsx",
    consumers: "plan detail, cart",
    variations: "OBSERVED VARIATION — two different summary widths.",
  },
  {
    name: "Member navigation orientation",
    trigger: "md (768px)",
    desktop: "Vertical icon rail, gap-3",
    tablet: "Vertical icon rail from 768px",
    mobile: "Horizontal scrolling strip, gap-1, overflow-x-auto",
    source: "components/abox/member-shell.tsx",
    consumers: "/member/settings",
    variations: "None.",
  },
  {
    name: "Header content reduction",
    trigger: "md, sm, lg, xl",
    desktop: "Brand tagline, search field, ⌘K hint and full price summary all visible",
    tablet: "Search and ⌘K hint hidden; tagline visible from md",
    mobile: "Icon-only affordances; cart shows count without the monthly figure",
    source: "marketplace-shell.tsx, internal-shell.tsx",
    consumers: "all shells",
    variations: "Username truncates at max-w-[10ch], widening to sm:max-w-[16ch].",
  },
  {
    name: "Typography step-up",
    trigger: "md",
    desktop: "text-display at md:text-3xl / md:text-6xl in mastheads",
    tablet: "Same as desktop from 768px",
    mobile: "text-2xl / text-4xl base sizes",
    source: "page-header.tsx, internal-shell.tsx, reference sections",
    consumers: "headers across the app",
    variations: "Each surface declares its own pair rather than using a shared heading class.",
  },
  {
    name: "Stacked-to-inline blocks",
    trigger: "sm (640px)",
    desktop: "flex-row with items-center justify-between",
    tablet: "flex-row from 640px",
    mobile: "flex-col with gap-4",
    source: "cart add-ons banner, page action rows",
    consumers: "banners, headers, summary rows",
    variations: "Some rows use flex-wrap instead of a breakpoint switch.",
  },
  {
    name: "Overflow strategy",
    trigger: "content width, not a breakpoint",
    desktop: "Tables sit inside overflow-x-auto wrappers",
    tablet: "Horizontal scroll",
    mobile: "Horizontal scroll; nav strips use overflow-x-auto with hidden scrollbars",
    source: "data-table.tsx, member-shell.tsx, internal-shell nav",
    consumers: "tables, nav strips",
    variations: "Columns are never dropped or reflowed — scrolling is the single strategy.",
  },
];

export const DENSITY_MODES: DensityEntry[] = [
  {
    mode: "Primitive (compact)",
    context: "shadcn forms, dialogs, dropdowns",
    controlHeight: "h-9 (36px); sm variant h-8",
    padding: "px-4 py-2 buttons, px-3 py-1 inputs",
    gap: "gap-2",
    typography: "text-sm (text-xs on sm buttons)",
    iconSize: "16px ([&_svg]:size-4)",
    source: "components/ui/button.tsx, input.tsx",
    note: "CURRENT IMPLEMENTATION — the densest control family in the app.",
  },
  {
    mode: "Marketplace (comfortable)",
    context: "Public, shopping and member surfaces",
    controlHeight: "h-10 (40px), min-h-10/min-h-11 on key actions",
    padding: "px-4 py-2 pills, px-5 on emphasis actions",
    gap: "gap-1.5 to gap-2",
    typography: "text-sm font-medium / font-semibold",
    iconSize: "16px",
    source: "action-pill.ts, marketplace-shell.tsx, route call sites",
    note: "OBSERVED VARIATION — 40px marketplace controls vs 36px primitives. Deliberate, not an error.",
  },
  {
    mode: "Card comfortable",
    context: "ABox panels, KPI cards, filter panels",
    controlHeight: "n/a",
    padding: "p-5",
    gap: "gap-3 internal, gap-4 between cards",
    typography: "text-eyebrow labels, text-sm body",
    iconSize: "20–32px glyphs",
    source: "kpi-card.tsx and call sites",
  },
  {
    mode: "Card spacious",
    context: "shadcn Card, dialogs, sheets",
    controlHeight: "n/a",
    padding: "p-6",
    gap: "gap-4 / space-y-1.5 header",
    typography: "text-sm",
    iconSize: "16px",
    source: "components/ui/card.tsx, dialog.tsx, sheet.tsx",
  },
  {
    mode: "Card compact",
    context: "Inline notices, sort strips, chip containers",
    controlHeight: "n/a",
    padding: "p-3 / p-4",
    gap: "gap-1.5 to gap-3",
    typography: "text-xs / text-sm",
    iconSize: "16px",
    source: "plans.index.tsx and admin strips",
  },
  {
    mode: "Table dense",
    context: "Operational record lists",
    controlHeight: "Content-driven rows",
    padding: "px-5 py-4 (ABox) · h-10 px-2 (shadcn head)",
    gap: "n/a",
    typography: "text-sm, uppercase tracking header",
    iconSize: "16px",
    source: "data-table.tsx, components/ui/table.tsx",
    note: "OBSERVED VARIATION — two table densities ship.",
  },
  {
    mode: "Navigation dense",
    context: "Admin rail, member rail, header nav",
    controlHeight: "h-9/h-10 targets",
    padding: "px-2 py-2 (member), px-1/px-3 (admin rail)",
    gap: "gap-1 horizontal, gap-3 vertical",
    typography: "text-sm",
    iconSize: "16–20px",
    source: "internal-shell.tsx, member-shell.tsx, marketplace-shell.tsx",
  },
  {
    mode: "Marketing spacious",
    context: "Landing and narrative sections",
    controlHeight: "h-10/h-11 calls to action",
    padding: "py-16 md:py-24 or py-24 md:py-32 sections",
    gap: "gap-10 to gap-14",
    typography: "text-display up to md:text-6xl",
    iconSize: "16–24px",
    source: "routes/index.tsx, marketplace-shell footer",
  },
];
