/**
 * Phase 7 — future token naming system and the primitive → semantic map.
 * DOCUMENTATION ONLY. No production token is renamed.
 */
import type { NamingRule, RoleChainEntry } from "./types";

export const TOKEN_NAMING_RULES: NamingRule[] = [
  {
    subject: "Primitive colour",
    convention: "color/<family>/<step> — family is a hue name, step is a lightness index.",
    example: "color/navy/600 = oklch(0.31 0.090 265)",
    codebaseFit:
      "No primitive layer exists today; primitives would be added beneath the current variables without touching them.",
    figmaFit:
      "Maps directly to a Color variable in a Primitives collection, hidden from consumers.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Semantic colour",
    convention: "<role-group>/<role>[-on|-subtle|-strong] — role first, value never in the name.",
    example: "surface/raised, content/secondary, action/primary-on, status/caution-subtle",
    codebaseFit:
      "Most current names already follow this shape: --card, --muted-foreground, --primary-foreground.",
    figmaFit: "Slash-separated names become Figma variable groups automatically.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Tier colour",
    convention: "tier/<tier-name> and tier/<tier-name>-on — kept in a group of its own.",
    example: "tier/expanded-bronze, tier/gold-on",
    codebaseFit: "Matches --metal-expanded-bronze and --metal-gold-fg with a clearer suffix.",
    figmaFit: "A dedicated Tier group prevents accidental reuse as status.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Typography",
    convention: "type/<role>[/<size-step>] for styles; font/<family> and weight/<name> for atoms.",
    example: "type/body, type/display/l, font/display, weight/semibold",
    codebaseFit:
      "text-display, text-eyebrow and text-serial already name roles rather than sizes; the rest is set at call sites.",
    figmaFit:
      "Roles become Text Styles. Font family and weight can be variables; composite styles cannot.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Spacing",
    convention:
      "space/<number> where the number is the pixel value times 25, matching the 4px base.",
    example: "space/100 = 4px, space/200 = 8px, space/500 = 20px",
    codebaseFit:
      "The Tailwind ladder already supplies these values; the token names sit alongside, not instead.",
    figmaFit: "Number variables, usable in auto-layout gaps and padding.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Spacing relationship",
    convention: "rhythm/<from>-<to> for relational rules that are not a single raw value.",
    example: "rhythm/title-supporting, rhythm/field-field",
    codebaseFit: "No equivalent exists; relationships live implicitly in markup.",
    figmaFit: "Documentation metadata; Figma has no relationship primitive.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Radius",
    convention: "radius/<role> for semantic use, radius/<step> for raw steps.",
    example: "radius/card, radius/control, radius/full",
    codebaseFit: "The seven --radius-* steps already exist and stay unchanged.",
    figmaFit: "Number variables bound to corner radius.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Border",
    convention: "line/<role> for colour, border/<name> for width.",
    example: "line/hairline, line/control, border/hairline = 1",
    codebaseFit: "Current names mix the two: --border is a colour, not a width.",
    figmaFit: "Colour variables plus a number variable for stroke weight.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Elevation",
    convention: "elevation/<role>, never elevation/<number>.",
    example: "elevation/card, elevation/drawer, elevation/glow",
    codebaseFit: "Matches --shadow-card, --shadow-drawer and --shadow-glow.",
    figmaFit: "Effect styles, not variables — multi-layer shadows cannot be variables.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Opacity",
    convention: "opacity/<role> expressed as a decimal.",
    example: "opacity/disabled = 0.5, opacity/scrim = 0.4, opacity/tint = 0.1",
    codebaseFit: "Currently written as Tailwind suffixes at the call site.",
    figmaFit: "Number variables bound to layer opacity.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Icon size",
    convention: "icon/<pixel×25> matching the spacing numbering.",
    example: "icon/300 = 12, icon/400 = 16, icon/500 = 20",
    codebaseFit: "Two class spellings exist for 16px; the token name is neutral between them.",
    figmaFit: "Number variables bound to icon component width and height.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Motion",
    convention: "motion/<role> for duration, motion/easing/<name> for curves.",
    example: "motion/standard = 320ms, motion/easing/standard",
    codebaseFit: "One shared cubic-bezier already behaves as motion/easing/standard.",
    figmaFit: "Number variables for duration; easing is documentation metadata.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Breakpoint",
    convention: "breakpoint/<tailwind-name>, values unchanged.",
    example: "breakpoint/md = 768",
    codebaseFit: "Tailwind defaults; no rename implied.",
    figmaFit: "Documentation metadata and frame widths, not variables.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Density",
    convention: "control/<density> for heights, density/<surface> for padding modes.",
    example: "control/compact = 36, control/standard = 40, density/table-dense",
    codebaseFit: "Both 36 and 40 exist in production; the naming accommodates both.",
    figmaFit: "Number variables plus a component property named Density.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "Component semantic role",
    convention: "<component>/<slot> referencing a foundation role, never a raw value.",
    example: "button/surface → action/primary",
    codebaseFit: "Bindings exist inside class strings; naming them makes them reviewable.",
    figmaFit: "Component properties and bound variables.",
    label: "FUTURE CANONICAL TARGET",
  },
  {
    subject: "White-label boundary",
    convention: "Tenant-configurable tokens carry a brand/ prefix; nothing else may be overridden.",
    example: "brand/primary and brand/logo are configurable; status/danger is not.",
    codebaseFit:
      "Runtime branding already configures a narrow set; the prefix makes the boundary explicit.",
    figmaFit: "A Brand collection separate from ABox Core.",
    label: "GOVERNANCE RULE",
  },
];

/** primitive → semantic → component role → experience, across categories. */
export const PRIMITIVE_SEMANTIC_MAP: RoleChainEntry[] = [
  {
    primitive: "space/200 = 8px",
    semantic: "rhythm/inline-default",
    componentRole: "button/icon-gap, nav-link/icon-gap, chip/internal-gap",
    experience: "All three",
    evidence: "316 gap-2 occurrences",
    label: "CURRENT IMPLEMENTATION",
  },
  {
    primitive: "space/500 = 20px",
    semantic: "density/card-padding",
    componentRole: "card/padding, table-cell/padding",
    experience: "All three",
    evidence: "187 p-5 occurrences",
    label: "CURRENT IMPLEMENTATION",
  },
  {
    primitive: "radius/700 = 36px and full",
    semantic: "radius/pill",
    componentRole: "badge/radius, action-pill/radius, avatar/radius",
    experience: "All three",
    evidence: "297 rounded-full occurrences",
    label: "CURRENT IMPLEMENTATION",
  },
  {
    primitive: "radius/500 = 22px",
    semantic: "radius/card",
    componentRole: "card/radius, table-shell/radius",
    experience: "All three",
    evidence: "264 rounded-2xl occurrences",
    label: "CURRENT IMPLEMENTATION",
  },
  {
    primitive: "icon/400 = 16px",
    semantic: "icon/default",
    componentRole: "button/icon, nav-link/icon, table-cell/icon",
    experience: "All three",
    evidence: "274 h-4 w-4 plus 28 size-4 occurrences",
    label: "OBSERVED VARIATION",
    note: "Two class spellings for one semantic size.",
  },
  {
    primitive: "border/hairline = 1px",
    semantic: "line/default",
    componentRole: "card/border, table/row-rule, divider",
    experience: "All three",
    evidence: "Global `* { border-color: var(--color-border) }` plus 497 border-border occurrences",
    label: "CURRENT IMPLEMENTATION",
  },
  {
    primitive: "opacity 0.5",
    semantic: "opacity/disabled",
    componentRole: "button/disabled, input/disabled",
    experience: "All three",
    evidence: "disabled:opacity-50 in the primitive layer",
    label: "CURRENT IMPLEMENTATION",
  },
  {
    primitive: "cubic-bezier(0.2, 0.7, 0.2, 1)",
    semantic: "motion/easing/standard",
    componentRole: "Every entrance animation and decorative hover transition",
    experience: "All three",
    evidence: "Used by fade-rise, hairline, card-brackets, edge-sheen and ember-underline",
    label: "CURRENT IMPLEMENTATION",
  },
  {
    primitive: "control 36px",
    semantic: "control/compact",
    componentRole: "button/height default, input/height",
    experience: "All three",
    evidence: "Button and Input both declare h-9",
    label: "OBSERVED VARIATION",
    note: "143 h-10 occurrences at call sites express a 40px standard alongside it.",
  },
  {
    primitive: "1408px",
    semantic: "container/web",
    componentRole: "page/container",
    experience: "Web and shopping",
    evidence: "23 max-w-[88rem] occurrences",
    label: "CURRENT IMPLEMENTATION",
    note: "Dashboard surfaces deliberately do not use it.",
  },
  {
    primitive: "0.6875rem uppercase",
    semantic: "type/eyebrow",
    componentRole: "section/eyebrow, kpi/label",
    experience: "All three",
    evidence: "225 text-eyebrow occurrences",
    label: "CURRENT IMPLEMENTATION",
  },
  {
    primitive: "14px body",
    semantic: "type/body",
    componentRole: "card/body, table/cell, form/value",
    experience: "All three",
    evidence: "779 text-sm occurrences",
    label: "CURRENT IMPLEMENTATION",
  },
];
