/**
 * Phase 3 — typography source-of-truth audit.
 *
 * DOCUMENTATION ONLY. Every value below was measured from `src/styles.css`,
 * `src/routes/__root.tsx`, `src/routes/*` and `src/components/*`. Nothing here
 * is imported by application screens, shells, business components, UI
 * primitives or business logic. Consumers: `/design-system`, `/design-guide`.
 *
 * Occurrence counts are approximate and describe scale, not a contract.
 */
import type { FoundationEntry, SpacingEntry, RelationshipGroup } from "./types";

/* ------------------------------------------------------------------
 * 1. Font architecture
 * ------------------------------------------------------------------ */

export const FONT_FAMILIES: FoundationEntry[] = [
  {
    name: "--font-sans (UI text)",
    value:
      '"Inter Tight", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif. Applied to html in @layer base with antialiasing and optimizeLegibility.',
    source: "src/styles.css @theme inline; loaded in src/routes/__root.tsx",
    consumers: "Every screen — the default family for all body, control and data text.",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
    note: 'body sets font-feature-settings: "ss01", "cv11".',
  },
  {
    name: "--font-display (headings)",
    value:
      '"Bricolage Grotesque", "Inter Tight", ui-sans-serif, system-ui, sans-serif. Applied to h1, h2, h3 and .font-display at weight 600, letter-spacing -0.028em, font-variation-settings "wdth" 102 / "opsz" 32.',
    source: "src/styles.css @theme inline + @layer base",
    consumers: "All h1–h3 elements and the .text-display utility (194 uses).",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
  },
  {
    name: "--font-serif (alias)",
    value: "Aliases the display stack — Bricolage Grotesque first. There is no serif face.",
    source: "src/styles.css",
    consumers: "No direct consumer found; kept as a compatibility alias.",
    ownership: "foundation",
    shared: "convention",
    maturity: "current",
    note: "OBSERVED VARIATION — the token name implies a serif that does not exist.",
  },
  {
    name: "--font-mono (alias)",
    value: "Aliases the sans stack — Inter Tight first. There is no monospace face.",
    source: "src/styles.css",
    consumers: ".text-eyebrow (229 uses) and .text-serial (46 uses) both reference it.",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
    note: "OBSERVED VARIATION — eyebrow and serial text read as 'mono' semantically but render in Inter Tight. Monospacing is achieved through uppercase, tracking and font-variant-numeric, not a mono face.",
  },
  {
    name: "JetBrains Mono (loaded, unused)",
    value:
      "Requested in the Google Fonts link at weights 400 and 500, but referenced by no token, utility or class anywhere in src.",
    source: "src/routes/__root.tsx font link",
    consumers: "None.",
    ownership: "foundation",
    shared: "one-off",
    maturity: "opportunity",
    note: "FUTURE OPPORTUNITY — either bind it to --font-mono (would change the look of every eyebrow and serial) or drop it from the font request (a network-only change). Neither was applied.",
  },
];

export const FONT_WEIGHTS: FoundationEntry[] = [
  {
    name: "400 — Regular",
    value:
      "Loaded for both families. Used explicitly via font-normal (10 uses) and as the body default.",
    source: "Font link + browser default",
    consumers: "Body copy, paragraph text, most muted descriptions.",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
  },
  {
    name: "500 — Medium",
    value: "font-medium — 406 uses, the most explicit weight in the application.",
    source: "Call sites, button.tsx, label.tsx",
    consumers: "Buttons, labels, nav links, chips, table headers, emphasis text.",
    ownership: "pattern",
    shared: "source-of-truth",
    maturity: "current",
    note: ".text-eyebrow also declares weight 500.",
  },
  {
    name: "600 — Semibold",
    value: "font-semibold — 125 uses; also the declared weight of h1–h3 and .text-display.",
    source: "src/styles.css base layer and .text-display; call sites",
    consumers: "Headings, card titles, plan names, status and metal badges, emphasis actions.",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
  },
  {
    name: "700 — Bold",
    value: "Loaded for both families but used once (font-bold, in the 404 numeral).",
    source: "Font link; src/routes/__root.tsx 404 view",
    consumers: "One.",
    ownership: "local",
    shared: "one-off",
    maturity: "current",
    note: "OBSERVED VARIATION — 700 is loaded for two families to serve a single element.",
  },
  {
    name: "Variable axes",
    value:
      'Bricolage Grotesque is loaded as a variable font (opsz 12..96). font-variation-settings "wdth" 102 with "opsz" 32 on headings and "opsz" 48 on .text-display.',
    source: "src/styles.css",
    consumers: "All display type.",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
    note: "The only place the application tunes optical sizing.",
  },
];

/* ------------------------------------------------------------------
 * 2. Type scale as measured
 * ------------------------------------------------------------------ */

export const TYPE_SCALE: SpacingEntry[] = [
  {
    value: "text-sm",
    computed: "0.875rem / 14px",
    occurrences: 779,
    purpose: "Default body and control size. The application's real base size.",
    where: "Body copy, buttons, inputs, table cells, nav links, card descriptions",
    frequency: "recurring",
    consistency: "consistent",
    source: "call site; also primitive defaults (button, input, table)",
    ownership: "pattern",
    centralizable: "safe",
    risk: "high",
    note: "CURRENT IMPLEMENTATION — text-base (16px) is rare; 14px is the effective body size.",
  },
  {
    value: "text-xs",
    computed: "0.75rem / 12px",
    occurrences: 464,
    purpose: "Secondary body, metadata, helper text, dense chrome.",
    where: "Card meta rows, helper text, hints, chips, footnotes",
    frequency: "recurring",
    consistency: "consistent",
    source: "call site",
    ownership: "pattern",
    centralizable: "safe",
    risk: "high",
  },
  {
    value: "text-xl",
    computed: "1.25rem / 20px",
    occurrences: 94,
    purpose: "Section heading and compact page title.",
    where: "Admin section headings, PageHeader compact variant, 404 subtitle",
    frequency: "recurring",
    consistency: "mostly-consistent",
    source: "call site",
    ownership: "pattern",
    centralizable: "conditional",
    risk: "high",
  },
  {
    value: "text-2xl",
    computed: "1.5rem / 24px",
    occurrences: 61,
    purpose: "Larger section heading, empty-state title, plan price.",
    where: "EmptyState title, plan card price, reference section headings",
    frequency: "recurring",
    consistency: "variable",
    source: "call site",
    ownership: "pattern",
    centralizable: "conditional",
    risk: "high",
    note: "OBSERVED VARIATION — section headings appear at text-base, text-xl and text-2xl across routes.",
  },
  {
    value: "text-lg",
    computed: "1.125rem / 18px",
    occurrences: 29,
    purpose: "Page subtitle and lead paragraph.",
    where: "PageHeader description, marketing lead copy",
    frequency: "occasional",
    consistency: "mostly-consistent",
    source: "call site",
    ownership: "pattern",
    centralizable: "conditional",
    risk: "medium",
  },
  {
    value: "text-base",
    computed: "1rem / 16px",
    occurrences: 29,
    purpose: "Card and block headings — rarely used for body.",
    where: "Card titles, reference block headings",
    frequency: "occasional",
    consistency: "variable",
    source: "call site",
    ownership: "pattern",
    centralizable: "conditional",
    risk: "medium",
    note: "OBSERVED VARIATION — 16px is a heading size here, not the body size.",
  },
  {
    value: "text-3xl",
    computed: "1.875rem / 30px",
    occurrences: 20,
    purpose: "Page title at desktop.",
    where: "PageHeader default (text-display text-3xl md:text-4xl)",
    frequency: "occasional",
    consistency: "consistent",
    source: "components/abox/page-header.tsx and call sites",
    ownership: "business",
    centralizable: "safe",
    risk: "high",
  },
  {
    value: "text-4xl",
    computed: "2.25rem / 36px",
    occurrences: 19,
    purpose: "Masthead title at mobile, page title at desktop.",
    where: "internal-shell masthead (text-4xl md:text-6xl), PageHeader md step",
    frequency: "occasional",
    consistency: "consistent",
    source: "shells and call sites",
    ownership: "business",
    centralizable: "safe",
    risk: "high",
  },
  {
    value: "text-5xl",
    computed: "3rem / 48px",
    occurrences: 7,
    purpose: "KPI value and large marketing headline step.",
    where: "components/abox/kpi-card.tsx (text-display text-5xl tabular-nums leading-none)",
    frequency: "occasional",
    consistency: "consistent",
    source: "kpi-card.tsx, routes/index.tsx",
    ownership: "business",
    centralizable: "conditional",
    risk: "high",
  },
  {
    value: "text-6xl",
    computed: "3.75rem / 60px",
    occurrences: 7,
    purpose: "Masthead and hero headline at md and above.",
    where: "internal-shell masthead, routes/index.tsx hero, 404 numeral",
    frequency: "occasional",
    consistency: "consistent",
    source: "shells, routes/index.tsx",
    ownership: "business",
    centralizable: "conditional",
    risk: "high",
  },
  {
    value: "text-7xl",
    computed: "4.5rem / 72px",
    occurrences: 1,
    purpose: "Largest hero step at lg.",
    where: "routes/index.tsx (lg:text-7xl)",
    frequency: "one-off",
    consistency: "one-off",
    source: "routes/index.tsx",
    ownership: "local",
    centralizable: "unsafe",
    risk: "high",
  },
  {
    value: "text-[10px]",
    computed: "10px",
    occurrences: 34,
    purpose: "Badge, chip and table-header micro type.",
    where: "StatusBadge, MetalBadge, reference table headers, dense chrome",
    frequency: "recurring",
    consistency: "consistent",
    source: "components/abox/status-badge.tsx, metal-badge.tsx, call sites",
    ownership: "business",
    centralizable: "safe",
    risk: "high",
    note: "CURRENT IMPLEMENTATION — a sub-scale literal because Tailwind's scale stops at 12px.",
  },
  {
    value: "text-[11px]",
    computed: "11px",
    occurrences: 23,
    purpose: "Dense metadata just above badge size.",
    where: "Plan card meta, token swatch captions, compact chrome",
    frequency: "recurring",
    consistency: "mostly-consistent",
    source: "call sites",
    ownership: "pattern",
    centralizable: "conditional",
    risk: "medium",
  },
  {
    value: "text-[0.8rem] / text-[10.5px] / text-[9px]",
    computed: "12.8px / 10.5px / 9px",
    occurrences: 8,
    purpose: "One-off optical adjustments in dense chrome.",
    where: "Scattered internal chrome",
    frequency: "one-off",
    consistency: "one-off",
    source: "call sites",
    ownership: "local",
    centralizable: "unsafe",
    risk: "medium",
    note: "OBSERVED VARIATION — three additional sub-scale literals; text-[9px] is the smallest text in the app.",
  },
];

export const LINE_HEIGHT_AND_TRACKING: FoundationEntry[] = [
  {
    name: "Heading tracking",
    value: "letter-spacing -0.028em on h1–h3 and .font-display; -0.032em on .text-display.",
    source: "src/styles.css",
    consumers: "All headings and display text.",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
  },
  {
    name: "tracking-tight",
    value: "-0.025em — 10 uses.",
    source: "call sites",
    consumers: "Brand wordmark, a few dense headings.",
    ownership: "pattern",
    shared: "convention",
    maturity: "current",
  },
  {
    name: "tracking-widest / tracking-[0.18em]",
    value: "0.1em (18 uses) and 0.18em (12 uses) on uppercase micro labels.",
    source: "call sites; reference table headers use 0.18em",
    consumers: "Uppercase section labels and table headers.",
    ownership: "pattern",
    shared: "convention",
    maturity: "current",
    note: "OBSERVED VARIATION — four uppercase tracking values coexist: 0.08em, 0.12em, 0.14em, 0.18em, plus tracking-widest.",
  },
  {
    name: "tracking-[0.12em]",
    value: "0.12em — 8 uses; the badge standard.",
    source: "components/abox/status-badge.tsx, metal-badge.tsx",
    consumers: "StatusBadge, MetalBadge, meta chips.",
    ownership: "business",
    shared: "source-of-truth",
    maturity: "current",
  },
  {
    name: ".text-display line height",
    value: "line-height 1.02 — the only line height declared in a utility.",
    source: "src/styles.css @utility text-display",
    consumers: "All display type (194 uses).",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
  },
  {
    name: "leading-relaxed",
    value: "1.625 — 20 uses on long-form paragraphs.",
    source: "call sites",
    consumers: "Marketing copy, explanatory body text.",
    ownership: "pattern",
    shared: "convention",
    maturity: "current",
  },
  {
    name: "leading-none / leading-tight / leading-snug",
    value: "1 (16 uses), 1.25 (4), 1.375 (3).",
    source: "call sites",
    consumers: "KPI values, brand lockups, plan names, stacked labels.",
    ownership: "pattern",
    shared: "convention",
    maturity: "current",
  },
  {
    name: "leading-[0.98] / leading-[0.96] / leading-4",
    value: "Optical one-offs on the largest headlines and one dense chip.",
    source: "internal-shell masthead, routes/index.tsx",
    consumers: "3 sites.",
    ownership: "local",
    shared: "one-off",
    maturity: "current",
  },
];

/* ------------------------------------------------------------------
 * 3. Typography utilities
 * ------------------------------------------------------------------ */

export const TYPOGRAPHY_UTILITIES: FoundationEntry[] = [
  {
    name: ".text-display",
    value:
      'font-family var(--font-display); font-weight 600; letter-spacing -0.032em; line-height 1.02; font-variation-settings "wdth" 102, "opsz" 48. Size is NOT declared — each call site adds its own.',
    source: "src/styles.css @utility",
    consumers: "194 uses — page titles, mastheads, KPI values, empty-state titles, plan prices.",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
    note: "OBSERVED VARIATION — because size is unbound, the same utility appears at text-lg through text-7xl.",
  },
  {
    name: ".text-eyebrow",
    value:
      "font-family var(--font-mono); font-size 0.6875rem (11px); font-weight 500; letter-spacing 0; text-transform uppercase; color var(--muted-foreground).",
    source: "src/styles.css @utility",
    consumers:
      "229 uses — the most-used typography utility. Section labels, KPI labels, SCR context lines.",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
    note: "Fully bound: size, weight, transform and colour are all fixed by the utility.",
  },
  {
    name: ".text-serial",
    value:
      "font-family var(--font-mono); font-size 0.625rem (10px); letter-spacing 0; text-transform uppercase; color var(--muted-foreground); font-variant-numeric tabular-nums.",
    source: "src/styles.css @utility",
    consumers: "46 uses — identifiers, file paths, token names, plan IDs, taglines.",
    ownership: "foundation",
    shared: "source-of-truth",
    maturity: "current",
    note: "The only utility that sets font-variant-numeric.",
  },
  {
    name: ".ember-underline",
    value:
      "Pseudo-element underline: 2px primary bar at bottom -2px, scaleX(0) from the right, revealed on hover/focus.",
    source: "src/styles.css @utility",
    consumers: "4 uses — reference page table-of-contents links.",
    ownership: "foundation",
    shared: "convention",
    maturity: "current",
  },
  {
    name: ".story-link",
    value: "Referenced 89 times but NOT defined in src/styles.css or any other stylesheet.",
    source: "Call sites only — no definition found",
    consumers: "89 inline links across routes.",
    ownership: "pattern",
    shared: "one-off",
    maturity: "opportunity",
    note: "OBSERVED VARIATION — a dead class name. It renders nothing today, so those links rely on their sibling utilities (text-primary, hover states) for affordance. FUTURE OPPORTUNITY: either define it or remove it; defining it would change how 89 links look.",
  },
  {
    name: ".sr-only",
    value: "Tailwind's screen-reader-only utility.",
    source: "Tailwind",
    consumers: "22 uses — skip links, icon-button labels, live-region labels.",
    ownership: "primitive",
    shared: "source-of-truth",
    maturity: "current",
  },
];

/* ------------------------------------------------------------------
 * 4. Semantic typography hierarchy
 * ------------------------------------------------------------------ */

export const SEMANTIC_TYPOGRAPHY: RelationshipGroup = {
  id: "semantic-typography",
  title: "Semantic typography roles",
  summary:
    "Each role as actually implemented. Where two surfaces use different values for the same role, that is recorded rather than resolved.",
  entries: [
    {
      pair: "Display / masthead",
      observed: "text-display text-4xl md:text-6xl leading-[0.98]",
      source: "internal-shell.tsx masthead, routes/index.tsx hero",
      consistency: "consistent",
    },
    {
      pair: "Page title",
      observed: "text-display text-3xl md:text-4xl (compact variant: text-xl md:text-2xl)",
      source: "components/abox/page-header.tsx",
      consistency: "consistent",
      note: "The one page-title definition owned by a component.",
    },
    {
      pair: "Page subtitle",
      observed: "text-lg text-muted-foreground; compact variant drops to text-xs",
      source: "components/abox/page-header.tsx",
      consistency: "consistent",
    },
    {
      pair: "Section heading",
      observed: "text-base, text-xl or text-2xl font-semibold depending on the route",
      source: "route markup",
      consistency: "varies",
      note: "OBSERVED VARIATION — no SectionHeading component exists; three sizes serve one role.",
    },
    {
      pair: "Card title",
      observed: "text-sm or text-base font-semibold",
      source: "route cards; components/ui/card.tsx title",
      consistency: "varies",
    },
    {
      pair: "Card supporting text",
      observed: "text-xs text-muted-foreground (text-sm in shadcn CardDescription)",
      source: "route cards, components/ui/card.tsx",
      consistency: "varies",
    },
    {
      pair: "Body text",
      observed: "text-sm, default weight, text-foreground",
      source: "everywhere",
      consistency: "consistent",
    },
    {
      pair: "Secondary body",
      observed: "text-sm text-muted-foreground — 803 uses of the muted colour token overall",
      source: "everywhere",
      consistency: "consistent",
    },
    {
      pair: "Label",
      observed: "text-sm font-medium (Label primitive); text-xs font-medium in dense forms",
      source: "components/ui/label.tsx, route forms",
      consistency: "varies",
    },
    {
      pair: "Caption / metadata",
      observed: "text-xs or text-[11px] text-muted-foreground",
      source: "plan cards, cart rows, admin meta lines",
      consistency: "mostly consistent" as unknown as "varies",
    },
    {
      pair: "Helper text",
      observed: "text-xs text-muted-foreground below the control",
      source: "route forms",
      consistency: "mostly consistent" as unknown as "varies",
    },
    {
      pair: "Error text",
      observed: "text-xs text-destructive",
      source: "route forms",
      consistency: "consistent",
    },
    {
      pair: "Eyebrow",
      observed: ".text-eyebrow — 11px, weight 500, uppercase, muted",
      source: "src/styles.css utility",
      consistency: "consistent",
      note: "229 uses; fully bound by the utility.",
    },
    {
      pair: "Button label",
      observed: "text-sm font-medium (text-xs on the sm size)",
      source: "components/ui/button.tsx",
      consistency: "consistent",
      note: "Action pills use font-semibold instead — a deliberate marketing weight.",
    },
    {
      pair: "Navigation label",
      observed: "text-sm, font-medium on emphasis links",
      source: "marketplace-shell.tsx, internal-shell.tsx, member-shell.tsx",
      consistency: "consistent",
    },
    {
      pair: "Table header",
      observed: "text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground",
      source: "components/abox/data-table.tsx",
      consistency: "consistent",
    },
    {
      pair: "Table body",
      observed: "text-sm, muted for secondary columns",
      source: "components/abox/data-table.tsx",
      consistency: "consistent",
    },
    {
      pair: "KPI value",
      observed: "text-display text-5xl tabular-nums leading-none",
      source: "components/abox/kpi-card.tsx",
      consistency: "consistent",
    },
    {
      pair: "KPI label",
      observed: ".text-eyebrow above the value",
      source: "components/abox/kpi-card.tsx",
      consistency: "consistent",
    },
    {
      pair: "Plan name",
      observed: "text-display with leading-tight; carrier and meta at text-xs / text-[11px]",
      source: "components/abox/plan-card.tsx",
      consistency: "consistent",
    },
    {
      pair: "Price",
      observed: "text-display text-2xl tabular-nums with a smaller /mo suffix",
      source: "components/abox/plan-card.tsx, cart.tsx",
      consistency: "consistent",
    },
    {
      pair: "Badge / status",
      observed: "text-[10px] font-semibold uppercase tracking-[0.12em]",
      source: "components/abox/status-badge.tsx, metal-badge.tsx",
      consistency: "consistent",
      note: "The single most tightly governed typography role in the app.",
    },
    {
      pair: "Serial / identifier",
      observed: ".text-serial — 10px, uppercase, muted, tabular-nums",
      source: "src/styles.css utility",
      consistency: "consistent",
    },
    {
      pair: "Empty-state title",
      observed: "text-display text-2xl with a max-w-md text-sm body",
      source: "components/abox/empty-state.tsx",
      consistency: "consistent",
    },
  ],
};

/* ------------------------------------------------------------------
 * 5. Numeric and data typography
 * ------------------------------------------------------------------ */

export const NUMERIC_TYPOGRAPHY: RelationshipGroup = {
  id: "numeric-typography",
  title: "Numeric and data typography",
  summary:
    "tabular-nums appears 90 times and is the application's one numeric alignment convention. There is no monospace face — figures align through tabular figures in Inter Tight.",
  entries: [
    {
      pair: "Plan premium",
      observed: "text-display text-2xl tabular-nums, formatted $#,##0.00, with a muted /mo suffix",
      source: "components/abox/plan-card.tsx, routes/cart.tsx",
      consistency: "consistent",
    },
    {
      pair: "Cart total",
      observed: "text-display tabular-nums with a supporting muted basis line",
      source: "routes/cart.tsx",
      consistency: "consistent",
    },
    {
      pair: "Deductible / out-of-pocket",
      observed: "text-sm tabular-nums in a labelled stat grid",
      source: "plan-card.tsx, plans.$planId.tsx",
      consistency: "consistent",
    },
    {
      pair: "KPI figure",
      observed: "text-display text-5xl tabular-nums leading-none",
      source: "components/abox/kpi-card.tsx",
      consistency: "consistent",
    },
    {
      pair: "KPI delta",
      observed: "text-xs font-medium tabular-nums in a chip, coloured sage or destructive by sign",
      source: "components/abox/kpi-card.tsx",
      consistency: "consistent",
    },
    {
      pair: "Cart count in header",
      observed:
        "tabular-nums inline span — '· N' and '· $X/mo', the monthly figure hidden below sm",
      source: "components/abox/marketplace-shell.tsx",
      consistency: "consistent",
    },
    {
      pair: "Table figures",
      observed: "text-sm tabular-nums, right-aligned where numeric",
      source: "components/abox/data-table.tsx and call sites",
      consistency: "mostly consistent" as unknown as "varies",
    },
    {
      pair: "Identifiers (plan ID, SCR, NPN)",
      observed: ".text-serial — 10px uppercase muted with tabular-nums built in",
      source: "src/styles.css utility",
      consistency: "consistent",
    },
    {
      pair: "Dates and times",
      observed: "text-xs text-muted-foreground; no dedicated numeric treatment",
      source: "admin lists, history views",
      consistency: "varies",
      note: "OBSERVED VARIATION — dates do not use tabular-nums even in column layouts.",
    },
    {
      pair: "Percentages",
      observed: "tabular-nums where they sit beside other figures; plain text-sm elsewhere",
      source: "KPI deltas, admin readiness views",
      consistency: "varies",
    },
    {
      pair: "Struck-through price",
      observed: "line-through on the superseded figure (3 uses)",
      source: "shopping surfaces",
      consistency: "consistent",
    },
  ],
};
