/**
 * Governed sample data for M08 Increment 1.
 *
 * These records exist to exercise the controlled screen states. No production
 * credential is created, changed or enforced from this module.
 */

import type { CredentialSubject, SellingContext } from "./model";

const NOW = "2026-03-18T14:05:00Z";

export const M08_SUBJECTS: CredentialSubject[] = [
  {
    person_id: "WFP-000241",
    display_name: "Dana Ortiz",
    npn: { npn: "8123456", subject_type: "INDIVIDUAL", subject_name: "Dana Ortiz", status: "ACTIVE" },
    affiliation: {
      agency_name: "Northlight Benefits Group",
      agency_npn: "6600321",
      affiliation_status: "ACTIVE",
      operational_readiness: "READY",
      captivity: "NON_CAPTIVE",
      effective_from: "2024-07-01",
    },
    as_of: NOW,
    licenses: [
      {
        license_id: "LIC-TX-88214",
        state_code: "TX",
        license_number: "TX-2288-4410",
        resident: true,
        status: "ACTIVE",
        effective_from: "2023-02-01",
        effective_to: "2027-01-31",
        lines: [
          { line_of_authority_id: "LOA-1", code: "HEALTH", name_key: "Health", status: "ACTIVE", effective_from: "2023-02-01", effective_to: null },
          { line_of_authority_id: "LOA-2", code: "LIFE", name_key: "Life", status: "ACTIVE", effective_from: "2023-02-01", effective_to: null },
        ],
        provenance: { source: "AGENT_ATTESTED", supplied_by: "Dana Ortiz", recorded_at: "2023-02-04T16:20:00Z" },
        verification: "VERIFIED",
        verified_at: "2025-11-02T09:10:00Z",
      },
      {
        license_id: "LIC-CA-51907",
        state_code: "CA",
        license_number: "CA-0K91-227",
        resident: false,
        status: "ACTIVE",
        effective_from: "2024-05-15",
        effective_to: "2026-05-14",
        lines: [
          { line_of_authority_id: "LOA-3", code: "HEALTH", name_key: "Health", status: "ACTIVE", effective_from: "2024-05-15", effective_to: null },
        ],
        provenance: { source: "AGENCY_ATTESTED", supplied_by: "Northlight Benefits Group", recorded_at: "2024-05-16T11:02:00Z" },
        verification: "NOT_VERIFIED",
        verification_note_key: "note.verificationOptional",
      },
      {
        license_id: "LIC-FL-30442",
        state_code: "FL",
        license_number: "FL-W441-908",
        resident: false,
        status: "EXPIRED",
        effective_from: "2022-03-01",
        effective_to: "2025-02-28",
        lines: [
          { line_of_authority_id: "LOA-4", code: "HEALTH", name_key: "Health", status: "EXPIRED", effective_from: "2022-03-01", effective_to: "2025-02-28" },
        ],
        provenance: { source: "MIGRATED", supplied_by: "Legacy roster import", recorded_at: "2024-07-01T08:00:00Z" },
        verification: "SUPERSEDED",
      },
    ],
    appointments: [
      {
        appointment_id: "APT-TX-AET-01",
        carrier_id: "CAR-AETNA",
        carrier_name: "Aetna",
        state_code: "TX",
        product_family_key: "Individual health",
        timing: "REQUIRED_BEFORE_SALE",
        status: "ACTIVE",
        effective_from: "2024-08-01",
        effective_to: null,
        writing_number: "WR-44120",
        provenance: { source: "AGENCY_ATTESTED", supplied_by: "Northlight Benefits Group", recorded_at: "2024-08-01T13:44:00Z" },
        verification: "NOT_VERIFIED",
      },
      {
        appointment_id: "APT-TX-AMB-01",
        carrier_id: "CAR-AMBETTER",
        carrier_name: "Ambetter",
        state_code: "TX",
        product_family_key: "Individual health",
        timing: "JUST_IN_TIME",
        status: "ACTIVE",
        effective_from: "2025-01-05",
        effective_to: null,
        writing_number: null,
        provenance: { source: "JET_ATTESTED", supplied_by: "JET compliance", recorded_at: "2025-01-05T10:15:00Z" },
        verification: "VERIFIED",
      },
      {
        appointment_id: "APT-CA-CIG-01",
        carrier_id: "CAR-CIGNA",
        carrier_name: "Cigna",
        state_code: "CA",
        product_family_key: "Individual health",
        timing: "REQUIRED_BEFORE_SALE",
        status: "EXPIRED",
        effective_from: "2024-06-01",
        effective_to: "2026-01-31",
        writing_number: "WR-90210",
        provenance: { source: "AGENCY_ATTESTED", supplied_by: "Northlight Benefits Group", recorded_at: "2024-06-01T09:00:00Z" },
        verification: "NOT_VERIFIED",
      },
    ],
    authority: [
      {
        grant_id: "GRT-AET-TX",
        carrier_id: "CAR-AETNA",
        carrier_name: "Aetna",
        product_scope_key: "Individual health",
        states: ["TX"],
        basis: "AGENCY_SPONSORED",
        sponsor_name: "Northlight Benefits Group",
        inherited_from: "Agency master contract NB-2024-11",
        status: "ACTIVE",
        effective_from: "2024-08-01",
        effective_to: null,
        provenance: { source: "AGENCY_ATTESTED", supplied_by: "Northlight Benefits Group", recorded_at: "2024-08-01T13:46:00Z" },
      },
      {
        grant_id: "GRT-AMB-TX",
        carrier_id: "CAR-AMBETTER",
        carrier_name: "Ambetter",
        product_scope_key: "Individual health",
        states: ["TX"],
        basis: "JUST_IN_TIME",
        sponsor_name: null,
        inherited_from: null,
        status: "ACTIVE",
        effective_from: "2025-01-05",
        effective_to: null,
        provenance: { source: "JET_ATTESTED", supplied_by: "JET compliance", recorded_at: "2025-01-05T10:16:00Z" },
      },
      {
        grant_id: "GRT-CIG-CA",
        carrier_id: "CAR-CIGNA",
        carrier_name: "Cigna",
        product_scope_key: "Individual health",
        states: ["CA"],
        basis: "AGENCY_SPONSORED",
        sponsor_name: "Northlight Benefits Group",
        inherited_from: "Agency master contract NB-2024-04",
        status: "EXPIRED",
        effective_from: "2024-06-01",
        effective_to: "2026-01-31",
        provenance: { source: "AGENCY_ATTESTED", supplied_by: "Northlight Benefits Group", recorded_at: "2024-06-01T09:02:00Z" },
      },
    ],
    eo: [
      {
        eo_id: "EO-GRP-NB-2026",
        kind: "AGENCY_GROUP",
        carrier_name: "Hanover Professional",
        policy_number: "HP-GRP-77401",
        per_claim_limit: 1000000,
        aggregate_limit: 3000000,
        currency: "USD",
        status: "ACTIVE",
        effective_from: "2026-01-01",
        effective_to: "2026-12-31",
        roster_member: true,
        provenance: { source: "AGENCY_ATTESTED", supplied_by: "Northlight Benefits Group", recorded_at: "2025-12-14T15:30:00Z" },
      },
    ],
    training: [
      {
        training_id: "TRN-AET-2026",
        carrier_name: "Aetna",
        requirement_key: "Carrier product training 2026",
        disposition: "REQUIRED",
        status: "ACTIVE",
        completed_on: "2026-01-12",
        expires_on: "2026-12-31",
        provenance: { source: "AGENT_ATTESTED", supplied_by: "Dana Ortiz", recorded_at: "2026-01-12T18:40:00Z" },
      },
      {
        training_id: "TRN-CIG-2026",
        carrier_name: "Cigna",
        requirement_key: "Carrier product training 2026",
        disposition: "REQUIRED",
        status: "NOT_STARTED",
        completed_on: null,
        expires_on: null,
        provenance: null,
      },
      {
        training_id: "TRN-MKT-2026",
        carrier_name: null,
        requirement_key: "Marketplace training",
        disposition: "OPTIONAL",
        status: "EXPIRED",
        completed_on: "2024-10-02",
        expires_on: "2025-10-01",
        provenance: { source: "AGENT_ATTESTED", supplied_by: "Dana Ortiz", recorded_at: "2024-10-02T12:00:00Z" },
      },
    ],
    marketplace: {
      marketplace_info_id: "MKT-000241",
      status: "INFORMATIONAL_EXPIRED",
      plan_year: "2025",
      recorded_on: "2024-10-02",
      provenance: { source: "AGENT_ATTESTED", supplied_by: "Dana Ortiz", recorded_at: "2024-10-02T12:01:00Z" },
    },
    documents: [
      {
        reference_id: "DOCREF-0091",
        m13_document_id: "M13-DOC-77120",
        title_key: "Texas resident licence certificate",
        linked_record_id: "LIC-TX-88214",
        linked_record_label_key: "Licence TX-2288-4410",
        uploaded_on: "2023-02-04",
        availability: "DEPENDENCY_UNAVAILABLE",
      },
      {
        reference_id: "DOCREF-0114",
        m13_document_id: "M13-DOC-88301",
        title_key: "Agency E&O certificate 2026",
        linked_record_id: "EO-GRP-NB-2026",
        linked_record_label_key: "E&O HP-GRP-77401",
        uploaded_on: "2025-12-14",
        availability: "DEPENDENCY_UNAVAILABLE",
      },
      {
        reference_id: "DOCREF-0120",
        m13_document_id: "M13-DOC-90044",
        title_key: "California non-resident licence",
        linked_record_id: "LIC-CA-51907",
        linked_record_label_key: "Licence CA-0K91-227",
        uploaded_on: "2024-05-16",
        availability: "PENDING",
      },
    ],
    holds: [
      {
        hold_id: "HLD-2025-0042",
        owner: "AGENCY",
        reason_key: "Roster audit — documentation review",
        scope_key: "California individual health",
        placed_on: "2025-09-01",
        released_on: "2025-09-19",
      },
    ],
    npn_roles: [
      {
        role: "ACTING_PRODUCER",
        npn: "8123456",
        subject_name: "Dana Ortiz",
        subject_type: "INDIVIDUAL",
        policy_source_key: "Person performing the work",
        target_type: "ACTING_PRODUCER",
        locked: true,
      },
      {
        role: "ATTRIBUTION",
        npn: "6600321",
        subject_name: "Northlight Benefits Group",
        subject_type: "BUSINESS_ENTITY",
        policy_source_key: "Agency default attribution policy",
        target_type: "AGENCY",
        locked: false,
      },
      {
        role: "MARKETPLACE_SUBMISSION",
        npn: "6600321",
        subject_name: "Northlight Benefits Group",
        subject_type: "BUSINESS_ENTITY",
        policy_source_key: "Agency default attribution policy",
        target_type: "AGENCY",
        locked: false,
      },
      {
        role: "CARRIER_CREDIT",
        npn: "6600321",
        subject_name: "Northlight Benefits Group",
        subject_type: "BUSINESS_ENTITY",
        policy_source_key: "Carrier hierarchy on record",
        target_type: "AGENCY",
        locked: true,
      },
      {
        role: "SERVICING",
        npn: "8123456",
        subject_name: "Dana Ortiz",
        subject_type: "INDIVIDUAL",
        policy_source_key: "Servicing assignment (internal)",
        target_type: "DESIGNATED_PRODUCER",
        locked: false,
      },
      {
        role: "PRODUCER_OF_RECORD",
        npn: "8123456",
        subject_name: "Dana Ortiz",
        subject_type: "INDIVIDUAL",
        policy_source_key: "External record — changes complete outside ABox",
        target_type: "DESIGNATED_PRODUCER",
        locked: true,
      },
    ],
  },
  {
    person_id: "WFP-000318",
    display_name: "Marcus Bell",
    npn: { npn: "8455102", subject_type: "INDIVIDUAL", subject_name: "Marcus Bell", status: "ACTIVE" },
    affiliation: {
      agency_name: "Northlight Benefits Group",
      agency_npn: "6600321",
      affiliation_status: "PENDING_AGENCY_APPROVAL",
      operational_readiness: "NOT_READY",
      captivity: "CAPTIVE",
      effective_from: "2026-03-02",
    },
    as_of: NOW,
    licenses: [],
    appointments: [],
    authority: [],
    eo: [],
    training: [],
    marketplace: {
      marketplace_info_id: "MKT-000318",
      status: "NOT_TRACKED",
      plan_year: null,
      recorded_on: null,
      provenance: null,
    },
    documents: [],
    holds: [],
    npn_roles: [
      {
        role: "ACTING_PRODUCER",
        npn: "8455102",
        subject_name: "Marcus Bell",
        subject_type: "INDIVIDUAL",
        policy_source_key: "Person performing the work",
        target_type: "ACTING_PRODUCER",
        locked: true,
      },
    ],
  },
];

export const M08_CONTEXTS: SellingContext[] = [
  {
    state_code: "TX",
    carrier_id: "CAR-AETNA",
    carrier_name: "Aetna",
    product_scope_key: "Individual health",
    market: "ON_EXCHANGE",
    pathway: "JET_EDE",
    transaction: "NEW_SALE",
    effective_date: "2026-05-01",
  },
  {
    state_code: "TX",
    carrier_id: "CAR-AMBETTER",
    carrier_name: "Ambetter",
    product_scope_key: "Individual health",
    market: "OFF_EXCHANGE",
    pathway: "IFP",
    transaction: "NEW_SALE",
    effective_date: "2026-05-01",
  },
  {
    state_code: "CA",
    carrier_id: "CAR-CIGNA",
    carrier_name: "Cigna",
    product_scope_key: "Individual health",
    market: "OFF_EXCHANGE",
    pathway: "IFP",
    transaction: "NEW_SALE",
    effective_date: "2026-05-01",
  },
  {
    state_code: "FL",
    carrier_id: "CAR-AETNA",
    carrier_name: "Aetna",
    product_scope_key: "Individual health",
    market: "OFF_EXCHANGE",
    pathway: "QUOTE_ONLY",
    transaction: "NEW_SALE",
    effective_date: "2026-05-01",
  },
  {
    state_code: "TX",
    carrier_id: "CAR-AETNA",
    carrier_name: "Aetna",
    product_scope_key: "Individual health",
    market: "OFF_EXCHANGE",
    pathway: "IFP",
    transaction: "SERVICING",
    effective_date: "2026-05-01",
  },
];

export function subjectById(id: string) {
  return M08_SUBJECTS.find((s) => s.person_id === id) ?? M08_SUBJECTS[0];
}
