// Concatenates the protected B0-B10 tokens, additive current-app tokens and plugin logic into code.js.
// Figma plugins have no module loader, so the source files are joined.
// Run: node tools/figma-plugin/build.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const read = (f) => readFileSync(join(here, f), "utf8");

const out = [
  "// GENERATED by tools/figma-plugin/build.mjs — edit source token files / plugin.js instead.",
  read("tokens.js").replace(/\nif \(typeof module[\s\S]*$/, "\n"),
  read("tokens-b1.js"),
  read("tokens-b2.js"),
  read("tokens-b3.js"),
  read("tokens-b4.js"),
  read("tokens-b5.js"),
  read("tokens-b6.js"),
  read("tokens-b7.js"),
  read("tokens-b8.js"),
  read("tokens-b9.js"),
  read("tokens-b10.js"),
  read("tokens-current-app.js"),
  read("plugin.js"),
].join("\n");

writeFileSync(join(here, "code.js"), out);
console.log("wrote code.js (" + out.length + " bytes)");
console.log("next: node tools/figma-plugin/check-globals.mjs && node tools/figma-plugin/check-current-app-mobile.mjs");
