// Concatenates tokens.js + tokens-b1.js + tokens-b2.js + tokens-b3.js + tokens-b4.js + tokens-b5.js + tokens-b6.js + plugin.js into code.js (the manifest entry point).
// Figma plugins have no module loader, so the two source files are joined.
// Run: node tools/figma-plugin/build.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const read = (f) => readFileSync(join(here, f), "utf8");

const out = [
  "// GENERATED by tools/figma-plugin/build.mjs — edit tokens.js / tokens-b1.js / tokens-b2.js / tokens-b3.js / plugin.js instead.",
  read("tokens.js").replace(/\nif \(typeof module[\s\S]*$/, "\n"),
  read("tokens-b1.js"),
  read("tokens-b2.js"),
  read("tokens-b3.js"),
  read("tokens-b4.js"),
  read("tokens-b5.js"),
  read("tokens-b6.js"),
  read("plugin.js"),
].join("\n");

writeFileSync(join(here, "code.js"), out);
console.log("wrote code.js (" + out.length + " bytes)");
