// GENERATED by tools/figma-plugin/extract-b8.mjs — do not hand-edit.
var ABOX_B8 = {
  "meta": {
    "batch": "Phase 55 / Batch B8 — experiences & journey compositions",
    "page": "04 Experiences",
    "generatedBy": "tools/figma-plugin/extract-b8.mjs",
    "protects": [
      "B1",
      "B2",
      "B3",
      "B4",
      "B5",
      "B6",
      "B7"
    ]
  },
  "counts": {
    "experiences": 5,
    "topLevelFrames": 5,
    "b1Collections": 9,
    "b1Variables": 200,
    "b2Variables": 19,
    "b3Styles": 79,
    "b4Sets": 11,
    "b4Standalone": 3,
    "b5Variants": 56,
    "b5Physical": 59,
    "b5NonVariant": 19,
    "b5Exposed": 1,
    "b6TopLevel": 3,
    "b6PhysicalNodes": 4,
    "b7TopLevel": 3,
    "b7PhysicalNodes": 4,
    "newVariables": 0,
    "newStyles": 0,
    "newComponents": 0,
    "newComponentSets": 0,
    "newPatterns": 0,
    "newProperties": 0,
    "prototypes": 0
  },
  "page": "04 Experiences",
  "layout": {
    "frameWidth": 1440,
    "frameXGap": 1600,
    "startX": 0,
    "startY": 0
  },
  "experiences": [
    {
      "name": "ABox/Experience/Internal/DownlineAgencyCreation",
      "kind": "FRAME",
      "type": "Flow",
      "shell": {
        "name": "ABox/Shell/Internal",
        "overrides": {
          "pageTitle": "Create downline agency",
          "eyebrow": "Contacts · SCR-M05-009",
          "entity": "Cedar Grove Insurance"
        }
      },
      "patterns": [
        {
          "name": "ABox/Pattern/WizardStepper",
          "variant": null
        }
      ],
      "components": [
        {
          "name": "ABox/Header/PageHeader"
        },
        {
          "name": "ABox/Action/ActionPill"
        },
        {
          "name": "ABox/Status/StatusBadge"
        },
        {
          "name": "ABox/Form/LabeledField"
        },
        {
          "name": "ABox/Form/Input"
        }
      ],
      "states": [
        "identity",
        "contacts",
        "readiness",
        "activation"
      ],
      "signature": "ABox/Experience/Internal/DownlineAgencyCreation|FRAME|shell=Internal|states=identity,contacts,readiness,activation|patterns=WizardStepper|props=none|prototypes=0",
      "sources": [
        "src/routes/agency.downlines.new.identity.tsx:67-125",
        "src/routes/agency.downlines.new.contacts.tsx:43-113",
        "src/routes/agency.downlines.new.readiness.tsx:43-89",
        "src/routes/agency.downlines.new.activate.tsx:105-154",
        "src/components/abox/downline-wizard-stepper.tsx:18-63",
        "tools/figma-plugin/tokens-b6.js:241-381"
      ],
      "sequence": [
        {
          "title": "Identity",
          "body": "Legal name, NPN, parent assignment, duplicate warning",
          "source": "src/routes/agency.downlines.new.identity.tsx:103"
        },
        {
          "title": "Contacts",
          "body": "Primary business contact, email, telephone, preferred language",
          "source": "src/routes/agency.downlines.new.contacts.tsx:47"
        },
        {
          "title": "Readiness review",
          "body": "PASS / WARNING / FAIL controls before activation",
          "source": "src/routes/agency.downlines.new.readiness.tsx:11"
        },
        {
          "title": "Activation",
          "body": "Activation result and organization profile handoff",
          "source": "src/routes/agency.downlines.new.activate.tsx:118"
        }
      ],
      "limitations": [
        "Field groups are route-local composition; no new B8 form-group foundation is created."
      ]
    },
    {
      "name": "ABox/Experience/Internal/MarketplaceActivationGovernance",
      "kind": "FRAME",
      "type": "Journey slice",
      "shell": {
        "name": "ABox/Shell/Internal",
        "overrides": {
          "pageTitle": "Marketplace administration",
          "eyebrow": "Marketplace · MKT-001",
          "entity": "Cedar Grove Insurance"
        }
      },
      "patterns": [
        {
          "name": "ABox/Pattern/KpiRow",
          "variant": {
            "columns": "4"
          }
        }
      ],
      "components": [
        {
          "name": "ABox/Header/PageHeader"
        },
        {
          "name": "ABox/Card/KpiCard"
        },
        {
          "name": "ABox/Action/ActionPill"
        },
        {
          "name": "ABox/Status/StatusBadge"
        }
      ],
      "states": [
        "admin",
        "readiness",
        "activation"
      ],
      "signature": "ABox/Experience/Internal/MarketplaceActivationGovernance|FRAME|shell=Internal|states=admin,readiness,activation|patterns=KpiRow-4|props=none|prototypes=0",
      "sources": [
        "src/routes/marketplace.admin.index.tsx:66-155",
        "src/routes/marketplace.admin.readiness.tsx:25-61",
        "src/routes/marketplace.admin.activation.tsx:25-73",
        "tools/figma-plugin/tokens-b6.js:32-52"
      ],
      "sequence": [
        {
          "title": "Operational hub",
          "body": "Lifecycle, readiness, enabled participants, open issues",
          "source": "src/routes/marketplace.admin.index.tsx:93"
        },
        {
          "title": "Readiness controls",
          "body": "Canonical owner, next action, recalculation",
          "source": "src/routes/marketplace.admin.readiness.tsx:3"
        },
        {
          "title": "Initial activation",
          "body": "Submit to JET and pending review",
          "source": "src/routes/marketplace.admin.activation.tsx:69"
        }
      ],
      "limitations": [
        "Quick action rail and table-like rows remain route composition; no B8 navigation or data-table foundation is created."
      ]
    },
    {
      "name": "ABox/Experience/Marketplace/PlanAIShoppingPath",
      "kind": "FRAME",
      "type": "Flow",
      "shell": {
        "name": "ABox/Shell/Marketplace",
        "overrides": {
          "variant": "flow",
          "showProducts": true,
          "showAssistant": true,
          "product": "ifp"
        }
      },
      "patterns": [],
      "components": [
        {
          "name": "ABox/Header/PageHeader"
        },
        {
          "name": "ABox/Status/StatusBadge"
        },
        {
          "name": "ABox/Action/ActionPill"
        },
        {
          "name": "ABox/Feedback/EmptyState"
        }
      ],
      "states": [
        "select",
        "quote-final",
        "ranked-results"
      ],
      "signature": "ABox/Experience/Marketplace/PlanAIShoppingPath|FRAME|shell=Marketplace-flow|states=select,quote-final,ranked-results|patterns=none|props=none|prototypes=0",
      "sources": [
        "src/routes/select.tsx:31-95",
        "src/routes/quote.tsx:378-545",
        "src/routes/quote.tsx:1235-1363",
        "src/routes/plans.index.tsx:47-190",
        "src/routes/plans.index.tsx:276-369",
        "src/components/abox/product-switcher.tsx:20-78"
      ],
      "sequence": [
        {
          "title": "Path choice",
          "body": "Guide me with PlanAI or browse myself",
          "source": "src/routes/select.tsx:51"
        },
        {
          "title": "Quote outcome",
          "body": "Six-step quote summary and estimated monthly subsidy",
          "source": "src/routes/quote.tsx:1282"
        },
        {
          "title": "Ranked results",
          "body": "PlanAI explanation, filters, compare bar, plan results",
          "source": "src/routes/plans.index.tsx:307"
        }
      ],
      "limitations": [
        "Quote stepper, ShoppingPathBar and PlanCard are not B6/B4 foundations; they stay editable route composition inside this frame."
      ]
    },
    {
      "name": "ABox/Experience/Marketplace/EnrollmentReviewAndSubmission",
      "kind": "FRAME",
      "type": "Journey slice with documented branch",
      "shell": {
        "name": "ABox/Shell/Marketplace",
        "overrides": {
          "variant": "flow",
          "showProducts": true,
          "showAssistant": false,
          "product": "ifp"
        }
      },
      "patterns": [],
      "components": [
        {
          "name": "ABox/Header/PageHeader"
        },
        {
          "name": "ABox/Status/StatusBadge"
        },
        {
          "name": "ABox/Action/ActionPill"
        },
        {
          "name": "ABox/Feedback/EmptyState"
        }
      ],
      "states": [
        "cart",
        "review",
        "handoff",
        "offexchange-application"
      ],
      "signature": "ABox/Experience/Marketplace/EnrollmentReviewAndSubmission|FRAME|shell=Marketplace-flow|states=cart,review,handoff,offexchange-application|patterns=none|props=none|prototypes=0",
      "sources": [
        "src/routes/cart.tsx:36-199",
        "src/routes/review.tsx:36-136",
        "src/routes/handoff.tsx:27-119",
        "src/routes/apply.tsx:38-292",
        "src/routes/apply.tsx:296-313",
        "src/lib/cart-store.ts:1-131"
      ],
      "sequence": [
        {
          "title": "Cart",
          "body": "Grouped selections, add-ons, total, review transition",
          "source": "src/routes/cart.tsx:183"
        },
        {
          "title": "Review",
          "body": "Quote, cart and account checklist",
          "source": "src/routes/review.tsx:57"
        },
        {
          "title": "Handoff",
          "body": "On-exchange handoff packet and off-exchange continuation",
          "source": "src/routes/handoff.tsx:46"
        },
        {
          "title": "Application",
          "body": "Readiness, typed signature, PDF/EDI generation, pending carrier",
          "source": "src/routes/apply.tsx:309"
        }
      ],
      "limitations": [
        "Application stepper, checklist and handoff packet are route-specific structures; B8 does not promote them to reusable patterns."
      ]
    },
    {
      "name": "ABox/Experience/Member/ContinuationWorkspace",
      "kind": "FRAME",
      "type": "Continuation composition",
      "shell": {
        "name": "ABox/Shell/Member",
        "overrides": {}
      },
      "patterns": [
        {
          "name": "ABox/Pattern/KpiRow",
          "variant": {
            "columns": "3"
          }
        }
      ],
      "components": [
        {
          "name": "ABox/Header/PageHeader"
        },
        {
          "name": "ABox/Card/KpiCard"
        },
        {
          "name": "ABox/Status/StatusBadge"
        },
        {
          "name": "ABox/Feedback/EmptyState"
        }
      ],
      "states": [
        "dashboard",
        "saved-quotes",
        "messages"
      ],
      "signature": "ABox/Experience/Member/ContinuationWorkspace|FRAME|shell=Member|states=dashboard,saved-quotes,messages|patterns=KpiRow-3|props=none|prototypes=0",
      "sources": [
        "src/routes/member.index.tsx:28-110",
        "src/routes/member.quotes.tsx:19-46",
        "src/routes/member.messages.tsx:15-37",
        "src/routes/member.settings.tsx:39-103"
      ],
      "sequence": [
        {
          "title": "Dashboard",
          "body": "Welcome back, cart KPIs, quote resume, tasks",
          "source": "src/routes/member.index.tsx:31"
        },
        {
          "title": "Saved quotes",
          "body": "Saved plan count and add-to-cart continuation",
          "source": "src/routes/member.quotes.tsx:20"
        },
        {
          "title": "Messages",
          "body": "Agent messages with unread state",
          "source": "src/routes/member.messages.tsx:29"
        }
      ],
      "limitations": [
        "Saved plan cards and member message rows remain route content; no PlanCard or message-list foundation is created."
      ]
    }
  ],
  "placement": [
    {
      "name": "ABox/Experience/Internal/DownlineAgencyCreation",
      "x": 0,
      "y": 0
    },
    {
      "name": "ABox/Experience/Internal/MarketplaceActivationGovernance",
      "x": 1600,
      "y": 0
    },
    {
      "name": "ABox/Experience/Marketplace/PlanAIShoppingPath",
      "x": 3200,
      "y": 0
    },
    {
      "name": "ABox/Experience/Marketplace/EnrollmentReviewAndSubmission",
      "x": 4800,
      "y": 0
    },
    {
      "name": "ABox/Experience/Member/ContinuationWorkspace",
      "x": 6400,
      "y": 0
    }
  ],
  "limitations": [
    "Offline/plugin-layer execution is not real Figma Desktop creation; native editable-object evidence requires running the plugin in Figma Desktop.",
    "B8 creates top-level FRAME reference compositions only, not Components or Component Sets, to avoid creating a second design-system foundation layer.",
    "No component properties, variants, responsive variants, prototype links, variables, styles, shells, patterns or primitives are created in B8.",
    "Content is not inserted into B7 shell placeholder slots; where Figma cannot faithfully slot content into a live shell instance, representative route content is a sibling region with metadata.",
    "ShoppingPathBar, PlanCard, data tables, overlays, checklists, application steppers and route-local field groups remain editable route composition because prior batches explicitly did not establish them as reusable foundations.",
    "Marketplace showProducts continues to follow B7's asymmetric rule: only flow has the product-switcher target; landing receives no synthetic placeholder."
  ]
};
