// GENERATED by tools/figma-plugin/extract-b7.mjs — do not hand-edit.
var ABOX_B7 = {
  "meta": {
    "batch": "Phase 54 / Batch B7 — shells",
    "page": "03 Shells",
    "generatedBy": "tools/figma-plugin/extract-b7.mjs",
    "protects": [
      "B1",
      "B2",
      "B3",
      "B4",
      "B5",
      "B6"
    ]
  },
  "counts": {
    "shellAssets": 3,
    "componentSets": 1,
    "standaloneComponents": 2,
    "variantComponentNodes": 2,
    "physicalComponentNodes": 4,
    "topLevelObjects": 3,
    "b1Collections": 9,
    "b1Variables": 200,
    "b2Variables": 19,
    "b3Styles": 79,
    "b4Sets": 11,
    "b4Standalone": 3,
    "b5Variants": 56,
    "b5Physical": 59,
    "b5NonVariant": 19,
    "b6TopLevel": 3,
    "b6PhysicalNodes": 4,
    "textProperties": 3,
    "booleanProperties": 2,
    "slots": 0,
    "prototypes": 0
  },
  "page": "03 Shells",
  "shells": [
    {
      "name": "ABox/Shell/Internal",
      "kind": "COMPONENT",
      "source": "source: src/components/abox/internal-shell.tsx:30-140, rail :146-237, mobile nav :294-331, top-bar controls :342-501",
      "construction": {
        "workspaceKey": "agency",
        "workspaceLabel": "Agency Workspace",
        "entity": "Cedar Grove Insurance",
        "pageTitle": "Performance",
        "eyebrow": "Dashboard",
        "activeNavSample": "Dashboard"
      },
      "properties": [
        {
          "name": "pageTitle",
          "type": "TEXT",
          "field": "characters",
          "target": "page-header/title",
          "value": "Performance",
          "source": "src/components/abox/internal-shell.tsx:119-121"
        },
        {
          "name": "eyebrow",
          "type": "TEXT",
          "field": "characters",
          "target": "page-header/eyebrow",
          "value": "Dashboard",
          "source": "src/components/abox/internal-shell.tsx:117"
        },
        {
          "name": "entity",
          "type": "TEXT",
          "field": "characters",
          "target": "workspace-pill/entity-label",
          "value": "Cedar Grove Insurance",
          "source": "src/components/abox/internal-shell.tsx:359"
        }
      ],
      "deferredProperties": [
        {
          "name": "actions",
          "reason": "ReactNode actions require faithful SLOT support; if unsupported, only actions-region placeholder is created.",
          "source": "src/components/abox/internal-shell.tsx:124"
        },
        {
          "name": "railCollapsed",
          "reason": "local shell state; canonical construction is expanded and collapsed behaviour is metadata.",
          "source": "src/components/abox/internal-shell.tsx:43"
        },
        {
          "name": "workspace",
          "reason": "runtime navigation/data choice, not a finite shell variant axis.",
          "source": "src/components/abox/internal-shell.tsx:32"
        }
      ],
      "requiredInstances": [
        "ABox/Brand/AboxMark"
      ],
      "signature": "ABox/Shell/Internal|component|desktop-rail,top-bar,page-header,content-region,assistant-launcher-region|text:pageTitle,eyebrow,entity|actions-deferred"
    },
    {
      "name": "ABox/Shell/Marketplace",
      "kind": "COMPONENT_SET",
      "property": "variant",
      "values": [
        "flow",
        "landing"
      ],
      "source": "source: src/components/abox/marketplace-shell.tsx:26-190; product rail src/components/abox/product-switcher.tsx:20-78",
      "variants": [
        {
          "value": "flow",
          "hasProductRegion": true,
          "topOffset": "top-4",
          "navAddsShopPlans": false,
          "construction": {
            "showProducts": true,
            "showAssistant": true,
            "product": "ifp"
          },
          "signature": "ABox/Shell/Marketplace|variant=flow|header,nav,product-switcher-region,content-region,footer,assistant-launcher-region|showProducts-flow-bound"
        },
        {
          "value": "landing",
          "hasProductRegion": false,
          "topOffset": "top-6",
          "navAddsShopPlans": true,
          "construction": {
            "showAssistant": true,
            "product": "metadata-only"
          },
          "signature": "ABox/Shell/Marketplace|variant=landing|header,nav,content-region,footer,assistant-launcher-region|showProducts-no-target"
        }
      ],
      "properties": [
        {
          "name": "showProducts",
          "type": "BOOLEAN",
          "field": "visible",
          "target": "variant=flow/product-switcher-region",
          "landing": "no target",
          "value": true,
          "source": "src/components/abox/marketplace-shell.tsx:32,38,140"
        },
        {
          "name": "showAssistant",
          "type": "BOOLEAN",
          "field": "visible",
          "target": "assistant-launcher-region",
          "value": true,
          "source": "src/components/abox/marketplace-shell.tsx:29,188"
        }
      ],
      "productKeys": [
        "ifp",
        "dental",
        "vision",
        "life",
        "critical",
        "accident",
        "hospital",
        "ichra"
      ],
      "requiredInstances": [
        "ABox/Brand/AboxMark"
      ]
    },
    {
      "name": "ABox/Shell/Member",
      "kind": "COMPONENT",
      "source": "source: src/components/abox/member-shell.tsx:35-145; nav src/lib/nav-config.ts:251-257",
      "construction": {
        "activeNavSample": "My Dashboard",
        "navItems": [
          "My Dashboard",
          "Quotes",
          "Messages",
          "Settings",
          "Support"
        ]
      },
      "properties": [],
      "deferredProperties": [
        {
          "name": "children",
          "reason": "structural content-region only; no generic React children property is invented.",
          "source": "src/components/abox/member-shell.tsx:138"
        }
      ],
      "requiredInstances": [
        "ABox/Brand/AboxMark"
      ],
      "signature": "ABox/Shell/Member|component|header,member-nav,content-region,assistant-launcher-region|metadata-only"
    }
  ],
  "apiAudit": [
    "Internal.pageTitle -> TEXT characters on page-header/title",
    "Internal.eyebrow -> TEXT characters on page-header/eyebrow",
    "Internal.entity -> TEXT characters on workspace-pill/entity-label",
    "Internal.actions -> SLOT-or-limitation; no detached property",
    "Internal.railCollapsed -> expanded construction + metadata",
    "Marketplace.variant -> Component Set axis flow|landing",
    "Marketplace.showProducts -> flow visible binding only; landing no target and no placeholder",
    "Marketplace.showAssistant -> BOOLEAN visible on assistant launcher regions",
    "Marketplace.product -> runtime/sample metadata only",
    "Member.children -> structural content region only"
  ],
  "responsive": [
    "Internal: desktop rail represented; mobile sheet trigger/sheet and collapsed rail documented as metadata only.",
    "Marketplace: flow/landing source variant represented; breakpoint visibility documented, no responsive variant.",
    "Member: desktop member rail represented; mobile horizontal nav documented, no responsive variant."
  ],
  "interactions": [
    "Internal: route-driven nav, rail collapse, menus, theme and assistant are metadata; no prototype destinations.",
    "Marketplace: auth/cart/product/assistant states are metadata except showAssistant visibility; no prototype destinations.",
    "Member: auth redirect, active nav, sign out, theme and assistant are metadata; no prototype destinations."
  ],
  "limitations": [
    "Figma ids printed by an offline/mock harness are not real evidence; real ids require Figma Desktop execution.",
    "InternalShell actions accepts arbitrary ReactNode values across 24 render sites; no instance-swap is invented from call-site similarity.",
    "Marketplace showProducts is asymmetric: the flow variant has a product-switcher target; the landing variant intentionally has no synthetic target.",
    "Marketplace runtime branding remains runtime-owned; B7 uses sample brand text only and does not transfer white-label data into foundations.",
    "Route-driven navigation and overlay open states have no B7 prototype destinations and are recorded as metadata.",
    "CSS-only responsive breakpoints, fixed/sticky positioning, glass blur, dot fields, gradients and motion are recorded rather than approximated as new primitives.",
    "The observed invalid MarketplaceShell variant=compact call site is an audit finding only; B7 creates only the declared flow|landing axis."
  ]
};
