// GENERATED by tools/figma-plugin/extract-b5.mjs — do not hand-edit.
var ABOX_B5 = {
  "variantAxis": {
    "set": "ABox/Card/KpiCard",
    "existingProperty": "tone",
    "property": "deltaSign",
    "values": [
      "positive",
      "negative"
    ],
    "tones": [
      "default",
      "primary",
      "sage",
      "warning"
    ],
    "source": "src/components/abox/kpi-card.tsx:78",
    "positive": {
      "characters": "▲ 4.2%",
      "note": "existing B4 construction text, left untouched"
    },
    "negative": {
      "characters": "▼ 4.2%",
      "colorStyle": "ABox/Semantic/destructive",
      "source": "src/components/abox/kpi-card.tsx:81"
    },
    "positiveStyleByTone": {
      "default": "ABox/Status/primary",
      "primary": "ABox/Status/primary",
      "sage": "ABox/Status/sage",
      "warning": "ABox/Status/warning"
    }
  },
  "bindings": [
    {
      "component": "ABox/Action/ActionPill",
      "owner": "SET",
      "property": "label",
      "type": "TEXT",
      "source": "src/components/abox/action-pill-component.tsx:26",
      "target": {
        "textIndex": 0,
        "expect": "Action",
        "name": "label"
      },
      "reference": "characters",
      "value": "Action"
    },
    {
      "component": "ABox/Action/Button",
      "owner": "SET",
      "property": "label",
      "type": "TEXT",
      "source": "src/components/ui/button.tsx:35",
      "target": {
        "textIndex": 0,
        "expect": "Button",
        "name": "label"
      },
      "reference": "characters",
      "value": "Button"
    },
    {
      "component": "ABox/Status/StatusBadge",
      "owner": "SET",
      "property": "label",
      "type": "TEXT",
      "source": "src/components/abox/status-badge.tsx:3",
      "target": {
        "textIndex": 0,
        "expect": "Status",
        "name": "label"
      },
      "reference": "characters",
      "value": "Status"
    },
    {
      "component": "ABox/Status/MetalBadge",
      "owner": "SET",
      "property": "label",
      "type": "TEXT",
      "source": "src/components/abox/metal-badge.tsx:3",
      "target": {
        "textIndex": 0,
        "expect": "Bronze",
        "name": "label"
      },
      "reference": "characters",
      "value": "Bronze"
    },
    {
      "component": "ABox/Card/KpiCard",
      "owner": "SET",
      "property": "label",
      "type": "TEXT",
      "source": "src/components/abox/kpi-card.tsx:10",
      "target": {
        "textIndex": 0,
        "expect": "METRIC",
        "name": "label"
      },
      "reference": "characters",
      "value": "METRIC"
    },
    {
      "component": "ABox/Card/KpiCard",
      "owner": "SET",
      "property": "value",
      "type": "TEXT",
      "source": "src/components/abox/kpi-card.tsx:11",
      "target": {
        "textIndex": 1,
        "expect": "1,280",
        "name": "value"
      },
      "reference": "characters",
      "value": "1,280"
    },
    {
      "component": "ABox/Header/PageHeader",
      "owner": "SET",
      "property": "eyebrow",
      "type": "TEXT",
      "source": "src/components/abox/page-header.tsx:11",
      "target": {
        "textIndex": 0,
        "expect": "SECTION",
        "name": "eyebrow"
      },
      "reference": "characters",
      "value": "SECTION"
    },
    {
      "component": "ABox/Header/PageHeader",
      "owner": "SET",
      "property": "title",
      "type": "TEXT",
      "source": "src/components/abox/page-header.tsx:13",
      "target": {
        "textIndex": 1,
        "expect": "Page title",
        "name": "title"
      },
      "reference": "characters",
      "value": "Page title"
    },
    {
      "component": "ABox/Header/PageHeader",
      "owner": "SET",
      "property": "description",
      "type": "TEXT",
      "source": "src/components/abox/page-header.tsx:14",
      "target": {
        "textIndex": 2,
        "expect": "Supporting description.",
        "name": "description"
      },
      "reference": "characters",
      "value": "Supporting description."
    },
    {
      "component": "ABox/Nav/ModuleTab",
      "owner": "SET",
      "property": "label",
      "type": "TEXT",
      "source": "src/components/abox/module-tabs.tsx:9",
      "target": {
        "textIndex": 0,
        "expect": "Section",
        "name": "label"
      },
      "reference": "characters",
      "value": "Section"
    },
    {
      "component": "ABox/Nav/WizardStep",
      "owner": "SET",
      "property": "label",
      "type": "TEXT",
      "source": "src/components/abox/downline-wizard-stepper.tsx:14",
      "target": {
        "textIndex": 0,
        "expect": "Identity",
        "name": "label"
      },
      "reference": "characters",
      "value": "Identity"
    },
    {
      "component": "ABox/Feedback/EmptyState",
      "owner": "COMPONENT",
      "property": "title",
      "type": "TEXT",
      "source": "src/components/abox/empty-state.tsx:7",
      "target": {
        "textIndex": 0,
        "expect": "Nothing here yet",
        "name": "title"
      },
      "reference": "characters",
      "value": "Nothing here yet"
    },
    {
      "component": "ABox/Feedback/EmptyState",
      "owner": "COMPONENT",
      "property": "body",
      "type": "TEXT",
      "source": "src/components/abox/empty-state.tsx:8",
      "target": {
        "textIndex": 1,
        "expect": "Supporting copy.",
        "name": "body"
      },
      "reference": "characters",
      "value": "Supporting copy."
    },
    {
      "component": "ABox/Form/LabeledField",
      "owner": "COMPONENT",
      "property": "label",
      "type": "TEXT",
      "source": "src/components/abox/field.tsx:6",
      "target": {
        "textIndex": 0,
        "expect": "LABEL",
        "name": "label"
      },
      "reference": "characters",
      "value": "LABEL"
    },
    {
      "component": "ABox/Form/Input",
      "owner": "COMPONENT",
      "property": "placeholder",
      "type": "TEXT",
      "source": "src/components/ui/input.tsx:11",
      "target": {
        "textIndex": 0,
        "expect": "Placeholder",
        "name": "placeholder"
      },
      "reference": "characters",
      "value": "Placeholder"
    },
    {
      "component": "ABox/Card/KpiCard",
      "owner": "SET",
      "property": "hasDelta",
      "type": "BOOLEAN",
      "source": "src/components/abox/kpi-card.tsx:74",
      "target": {
        "textIndex": 2,
        "expect": "▲ 4.2%",
        "name": "delta"
      },
      "reference": "visible",
      "value": true
    },
    {
      "component": "ABox/Header/PageHeader",
      "owner": "SET",
      "property": "hasEyebrow",
      "type": "BOOLEAN",
      "source": "src/components/abox/page-header.tsx:29",
      "target": {
        "textIndex": 0,
        "expect": "SECTION",
        "name": "eyebrow"
      },
      "reference": "visible",
      "value": true
    },
    {
      "component": "ABox/Header/PageHeader",
      "owner": "SET",
      "property": "hasDescription",
      "type": "BOOLEAN",
      "source": "src/components/abox/page-header.tsx:49",
      "target": {
        "textIndex": 2,
        "expect": "Supporting description.",
        "name": "description"
      },
      "reference": "visible",
      "value": true
    },
    {
      "component": "ABox/Feedback/EmptyState",
      "owner": "COMPONENT",
      "property": "hasBody",
      "type": "BOOLEAN",
      "source": "src/components/abox/empty-state.tsx:23",
      "target": {
        "textIndex": 1,
        "expect": "Supporting copy.",
        "name": "body"
      },
      "reference": "visible",
      "value": true
    }
  ],
  "exposed": {
    "component": "ABox/Form/LabeledField",
    "of": "ABox/Control/Control",
    "name": "control",
    "source": "src/components/abox/field.tsx:9"
  },
  "deferred": [
    {
      "component": "ABox/Card/KpiCard",
      "property": "hasIcon",
      "type": "BOOLEAN",
      "missing": "no icon tile layer",
      "source": "src/components/abox/kpi-card.tsx:48"
    },
    {
      "component": "ABox/Card/KpiCard",
      "property": "hasHint",
      "type": "BOOLEAN",
      "missing": "no hint layer",
      "source": "src/components/abox/kpi-card.tsx:85"
    },
    {
      "component": "ABox/Card/KpiCard",
      "property": "hasDeltaLabel",
      "type": "BOOLEAN",
      "missing": "no delta-label TEXT layer",
      "source": "src/components/abox/kpi-card.tsx:84"
    },
    {
      "component": "ABox/Card/KpiCard",
      "property": "deltaLabel",
      "type": "TEXT",
      "missing": "no delta-label TEXT layer",
      "source": "src/components/abox/kpi-card.tsx:84"
    },
    {
      "component": "ABox/Header/PageHeader",
      "property": "hasIcon",
      "type": "BOOLEAN",
      "missing": "no icon layer",
      "source": "src/components/abox/page-header.tsx:15"
    },
    {
      "component": "ABox/Header/PageHeader",
      "property": "hasActions",
      "type": "BOOLEAN",
      "missing": "no actions wrapper layer",
      "source": "src/components/abox/page-header.tsx:55"
    },
    {
      "component": "ABox/Header/PageHeader",
      "property": "actions",
      "type": "INSTANCE_SWAP",
      "missing": "no nested instance in the actions region",
      "source": "src/components/abox/page-header.tsx:16"
    },
    {
      "component": "ABox/Feedback/EmptyState",
      "property": "hasIcon",
      "type": "BOOLEAN",
      "missing": "no icon layer",
      "source": "src/components/abox/empty-state.tsx:6"
    },
    {
      "component": "ABox/Feedback/EmptyState",
      "property": "hasAction",
      "type": "BOOLEAN",
      "missing": "no action region",
      "source": "src/components/abox/empty-state.tsx:9"
    },
    {
      "component": "ABox/Feedback/EmptyState",
      "property": "action",
      "type": "SLOT",
      "missing": "no action region to attach or convert",
      "source": "src/components/abox/empty-state.tsx:24"
    }
  ],
  "counts": {
    "boolean": 4,
    "text": 15,
    "instanceSwap": 0,
    "slot": 0,
    "nonVariant": 19,
    "exposedInstances": 1,
    "newVariantAxes": 1,
    "newVariantNodes": 4,
    "variantsBefore": 52,
    "variantsAfter": 56,
    "axesBefore": 16,
    "axesAfter": 17,
    "sets": 11,
    "standalone": 3,
    "physicalNodes": 59,
    "deferred": 10,
    "target": 29
  },
  "limitations": [
    "src/components/ui/button.tsx:8 \"disabled:pointer-events-none disabled:opacity-50 disabled:cursor-not-allowed\", used at src/components/abox/plan-card.tsx:116 (size=\"sm\" disabled={inCart}) — not converted to a Figma variant or property: a set-wide state axis would require a production-backed value for the other eight Button combinations, and production names none; pointer-events and cursor have no Figma representation.",
    "src/components/abox/kpi-card.tsx:19,73,78 — with hasDelta = false the hidden delta layer still carries a deltaSign value, because Figma requires every variant to hold a value for every axis of its set; recorded rather than resolved by invention.",
    "src/components/abox/kpi-card.tsx:19,73,78 — one production prop delta? carries both presence and sign; Figma cannot express both in a single property, so it is split into hasDelta and deltaSign, and the production prop name delta is used for neither.",
    "src/components/abox/kpi-card.tsx:81 — the delta chip text \"{delta.pct >= 0 ? \\\"▲\\\" : \\\"▼\\\"} {Math.abs(delta.pct).toFixed(1)}%\" is computed from the numeric pct and is not exposed as a Text property; the static chip text authored per variant is sample/construction content and the computation is recorded rather than reproduced.",
    "src/components/abox/kpi-card.tsx:78 — no negative pct literal occurs at any production call site; deltaSign=negative is included on the strength of the source branch and this absence is recorded.",
    "src/components/abox/kpi-card.tsx:78 — B4 bound the positive delta chip to the per-tone status style (ABox/Status/primary | sage | warning), while production declares text-sage for every positive delta independent of tone. B5 does not rewrite those existing B4 bindings; the deviation is recorded here and left for a B4 amendment decision.",
    "src/components/ui/input.tsx:11 disabled:cursor-not-allowed disabled:opacity-50 — declared, never used in production; not converted.",
    "src/components/abox/control.tsx:11-12 — disabled variants are explicitly consumer-owned; no canonical definition exists to convert.",
    "src/components/abox/page-header.tsx:33 — eyebrow is suppressed in compact; the combination is not created.",
    "src/components/abox/page-header.tsx:15 / kpi-card.tsx:20 / empty-state.tsx:6 — icon?: ComponentType<{className?: string}> cannot become an Instance Swap because B4 created no icon Component and no icon layer; only the recorded intent survives, and no placeholder component is invented.",
    "src/components/abox/empty-state.tsx:9,24 — production passes raw inline <Link>/<button> elements styled with pill classes rather than any B4 component, so action cannot be an INSTANCE_SWAP (that type requires a default component, and nominating ActionPill on class similarity would be value-equality inference). A SLOT also cannot be created: the audited B4 EmptyState contains no action region to attach or convert, so SLOT creation is 0 regardless of runtime SLOT support, which is still detected read-only and printed.",
    "Hover / focus / active / transition rules in src/components/ui/button.tsx:8, action-pill.ts, surface.tsx, control.tsx, module-tabs.tsx:28, kpi-card.tsx:41,62 — CSS pseudo-classes, not reusable design-system states; not converted.",
    "Motion: CountUp, FadeRise, animate-hairline, group-hover:-rotate-6 group-hover:scale-105 — no reusable resting state beyond what already exists; not converted.",
    "Responsive md:/xl: rules (page-header.tsx:37,44,46, kpi-card.tsx, ui/input.tsx:11) — layout composition, not component-level states; deferred to B7/B8.",
    "color-mix() tints and oklch() source literals, as already recorded in B3/B4.",
    "b4Build() assigns no name to any sublayer, so every B5 target is resolved structurally (TEXT-descendant index + exact characters) and then named; naming an existing layer changes no geometry, style, variant or id, and is the only B5 mutation of B4 node metadata."
  ],
  "excluded": [
    {
      "candidate": "ABox/Action/Button state axis",
      "reason": "src/components/ui/button.tsx:8 styles the native disabled attribute; production names no non-disabled counterpart, so a set-wide axis would need an invented value."
    },
    {
      "candidate": "hover / group-hover / focus-visible / focus / active",
      "reason": "CSS pseudo-classes; production treats them as interaction behaviour, not reusable states."
    },
    {
      "candidate": "ABox/Form/Input disabled",
      "reason": "src/components/ui/input.tsx:11 declares it with no production call site; adding it would convert a standalone component into a set."
    },
    {
      "candidate": "ABox/Control/Control disabled",
      "reason": "src/components/abox/control.tsx:11-12 leaves it consumer-owned."
    },
    {
      "candidate": "error / validation / aria-invalid",
      "reason": "only present in the reference routes design-system.tsx and design-guide.tsx."
    },
    {
      "candidate": "loading / checked / open / expanded / success",
      "reason": "no production definition on any B4 object."
    },
    {
      "candidate": "dialog, sheet, popover, tooltip, dropdown-menu, tabs states",
      "reason": "behavioural primitives — B6."
    },
    {
      "candidate": "responsive md:/xl: branches",
      "reason": "layout composition — B7/B8."
    }
  ]
};
