// GENERATED by tools/figma-plugin/extract-b1.mjs — edit the extractor or src/styles.css, not this file.
const ABOX_B1 = {
  "meta": {
    "phase": "52/B1",
    "generatedBy": "tools/figma-plugin/extract-b1.mjs",
    "source": "src/styles.css",
    "note": "Colours are oklch [L, C, h] (+alpha); converted to sRGB at run time. Recorded Figma limitation, never a production change."
  },
  "collections": [
    {
      "name": "ABox/Color/Primitive",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Color/Semantic",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Status",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Spacing",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Radius",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Border",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Elevation",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Layout",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Control sizing",
      "modes": [
        "Light",
        "Dark"
      ]
    }
  ],
  "primitives": [
    {
      "name": "background",
      "role": "background",
      "light": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.165,
        "C": 0.03,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--background: oklch(1 0 0)",
        "dark": "--background: oklch(0.165 0.03 265)  (.dark)"
      }
    },
    {
      "name": "foreground",
      "role": "foreground",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--foreground: oklch(0.22 0.025 265)",
        "dark": "--foreground: oklch(0.95 0.006 265)  (.dark)"
      }
    },
    {
      "name": "surface",
      "role": "surface",
      "light": {
        "L": 0.968,
        "C": 0.003,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.195,
        "C": 0.035,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--surface: oklch(0.968 0.003 265)",
        "dark": "--surface: oklch(0.195 0.035 265)  (.dark)"
      }
    },
    {
      "name": "surface-foreground",
      "role": "surface-foreground",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--surface-foreground: oklch(0.22 0.025 265)",
        "dark": "--surface-foreground: oklch(0.95 0.006 265)  (.dark)"
      }
    },
    {
      "name": "panel",
      "role": "panel",
      "light": {
        "L": 0.945,
        "C": 0.004,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.225,
        "C": 0.04,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--panel: oklch(0.945 0.004 265)",
        "dark": "--panel: oklch(0.225 0.04 265)  (.dark)"
      }
    },
    {
      "name": "ink",
      "role": "ink",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--ink: oklch(0.22 0.025 265)",
        "dark": "--ink: oklch(0.95 0.006 265)  (.dark)"
      }
    },
    {
      "name": "card",
      "role": "card",
      "light": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.205,
        "C": 0.036,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--card: oklch(1 0 0)",
        "dark": "--card: oklch(0.205 0.036 265)  (.dark)"
      }
    },
    {
      "name": "card-foreground",
      "role": "card-foreground",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--card-foreground: oklch(0.22 0.025 265)",
        "dark": "--card-foreground: oklch(0.95 0.006 265)  (.dark)"
      }
    },
    {
      "name": "popover",
      "role": "popover",
      "light": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.215,
        "C": 0.038,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--popover: oklch(1 0 0)",
        "dark": "--popover: oklch(0.215 0.038 265)  (.dark)"
      }
    },
    {
      "name": "popover-foreground",
      "role": "popover-foreground",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--popover-foreground: oklch(0.22 0.025 265)",
        "dark": "--popover-foreground: oklch(0.95 0.006 265)  (.dark)"
      }
    },
    {
      "name": "primary",
      "role": "primary",
      "light": {
        "L": 0.31,
        "C": 0.09,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--primary: oklch(0.31 0.09 265)",
        "dark": "--primary: oklch(0.68 0.125 255)  (.dark)"
      }
    },
    {
      "name": "primary-foreground",
      "role": "primary-foreground",
      "light": {
        "L": 0.99,
        "C": 0.002,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.16,
        "C": 0.045,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--primary-foreground: oklch(0.99 0.002 265)",
        "dark": "--primary-foreground: oklch(0.16 0.045 265)  (.dark)"
      }
    },
    {
      "name": "primary-soft",
      "role": "primary-soft",
      "light": {
        "L": 0.945,
        "C": 0.02,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.3,
        "C": 0.07,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--primary-soft: oklch(0.945 0.02 265)",
        "dark": "--primary-soft: oklch(0.3 0.07 265)  (.dark)"
      }
    },
    {
      "name": "secondary",
      "role": "secondary",
      "light": {
        "L": 0.955,
        "C": 0.004,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.255,
        "C": 0.04,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--secondary: oklch(0.955 0.004 265)",
        "dark": "--secondary: oklch(0.255 0.04 265)  (.dark)"
      }
    },
    {
      "name": "secondary-foreground",
      "role": "secondary-foreground",
      "light": {
        "L": 0.24,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--secondary-foreground: oklch(0.24 0.025 265)",
        "dark": "--secondary-foreground: oklch(0.95 0.006 265)  (.dark)"
      }
    },
    {
      "name": "sage",
      "role": "sage",
      "light": {
        "L": 0.55,
        "C": 0.085,
        "h": 195,
        "a": 1
      },
      "dark": {
        "L": 0.74,
        "C": 0.09,
        "h": 195,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sage: oklch(0.55 0.085 195)",
        "dark": "--sage: oklch(0.74 0.09 195)  (.dark)"
      }
    },
    {
      "name": "sage-foreground",
      "role": "sage-foreground",
      "light": {
        "L": 0.99,
        "C": 0.004,
        "h": 195,
        "a": 1
      },
      "dark": {
        "L": 0.16,
        "C": 0.035,
        "h": 195,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sage-foreground: oklch(0.99 0.004 195)",
        "dark": "--sage-foreground: oklch(0.16 0.035 195)  (.dark)"
      }
    },
    {
      "name": "sage-soft",
      "role": "sage-soft",
      "light": {
        "L": 0.945,
        "C": 0.03,
        "h": 195,
        "a": 1
      },
      "dark": {
        "L": 0.3,
        "C": 0.055,
        "h": 195,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sage-soft: oklch(0.945 0.03 195)",
        "dark": "--sage-soft: oklch(0.3 0.055 195)  (.dark)"
      }
    },
    {
      "name": "muted",
      "role": "muted",
      "light": {
        "L": 0.955,
        "C": 0.004,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.235,
        "C": 0.036,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--muted: oklch(0.955 0.004 265)",
        "dark": "--muted: oklch(0.235 0.036 265)  (.dark)"
      }
    },
    {
      "name": "muted-foreground",
      "role": "muted-foreground",
      "light": {
        "L": 0.5,
        "C": 0.018,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.73,
        "C": 0.015,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--muted-foreground: oklch(0.5 0.018 265)",
        "dark": "--muted-foreground: oklch(0.73 0.015 265)  (.dark)"
      }
    },
    {
      "name": "accent",
      "role": "accent",
      "light": {
        "L": 0.955,
        "C": 0.004,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.255,
        "C": 0.04,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--accent: oklch(0.955 0.004 265)",
        "dark": "--accent: oklch(0.255 0.04 265)  (.dark)"
      }
    },
    {
      "name": "accent-foreground",
      "role": "accent-foreground",
      "light": {
        "L": 0.24,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--accent-foreground: oklch(0.24 0.025 265)",
        "dark": "--accent-foreground: oklch(0.95 0.006 265)  (.dark)"
      }
    },
    {
      "name": "destructive",
      "role": "destructive",
      "light": {
        "L": 0.55,
        "C": 0.185,
        "h": 25,
        "a": 1
      },
      "dark": {
        "L": 0.55,
        "C": 0.185,
        "h": 25,
        "a": 1
      },
      "darkOverridden": false,
      "source": {
        "light": "--destructive: oklch(0.55 0.185 25)",
        "dark": "--destructive: oklch(0.55 0.185 25)  (no .dark override — Light duplicated)"
      }
    },
    {
      "name": "destructive-foreground",
      "role": "destructive-foreground",
      "light": {
        "L": 0.99,
        "C": 0.004,
        "h": 25,
        "a": 1
      },
      "dark": {
        "L": 0.99,
        "C": 0.004,
        "h": 25,
        "a": 1
      },
      "darkOverridden": false,
      "source": {
        "light": "--destructive-foreground: oklch(0.99 0.004 25)",
        "dark": "--destructive-foreground: oklch(0.99 0.004 25)  (no .dark override — Light duplicated)"
      }
    },
    {
      "name": "warning",
      "role": "warning",
      "light": {
        "L": 0.72,
        "C": 0.125,
        "h": 75,
        "a": 1
      },
      "dark": {
        "L": 0.78,
        "C": 0.115,
        "h": 75,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--warning: oklch(0.72 0.125 75)",
        "dark": "--warning: oklch(0.78 0.115 75)  (.dark)"
      }
    },
    {
      "name": "warning-foreground",
      "role": "warning-foreground",
      "light": {
        "L": 0.22,
        "C": 0.045,
        "h": 75,
        "a": 1
      },
      "dark": {
        "L": 0.22,
        "C": 0.045,
        "h": 75,
        "a": 1
      },
      "darkOverridden": false,
      "source": {
        "light": "--warning-foreground: oklch(0.22 0.045 75)",
        "dark": "--warning-foreground: oklch(0.22 0.045 75)  (no .dark override — Light duplicated)"
      }
    },
    {
      "name": "info",
      "role": "info",
      "light": {
        "L": 0.55,
        "C": 0.12,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.7,
        "C": 0.115,
        "h": 250,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--info: oklch(0.55 0.12 250)",
        "dark": "--info: oklch(0.7 0.115 250)  (.dark)"
      }
    },
    {
      "name": "info-foreground",
      "role": "info-foreground",
      "light": {
        "L": 0.99,
        "C": 0.004,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.99,
        "C": 0.004,
        "h": 250,
        "a": 1
      },
      "darkOverridden": false,
      "source": {
        "light": "--info-foreground: oklch(0.99 0.004 250)",
        "dark": "--info-foreground: oklch(0.99 0.004 250)  (no .dark override — Light duplicated)"
      }
    },
    {
      "name": "success",
      "role": "success",
      "light": {
        "L": 0.55,
        "C": 0.1,
        "h": 160,
        "a": 1
      },
      "dark": {
        "L": 0.7,
        "C": 0.095,
        "h": 160,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--success: oklch(0.55 0.1 160)",
        "dark": "--success: oklch(0.7 0.095 160)  (.dark)"
      }
    },
    {
      "name": "success-foreground",
      "role": "success-foreground",
      "light": {
        "L": 0.99,
        "C": 0.004,
        "h": 160,
        "a": 1
      },
      "dark": {
        "L": 0.99,
        "C": 0.004,
        "h": 160,
        "a": 1
      },
      "darkOverridden": false,
      "source": {
        "light": "--success-foreground: oklch(0.99 0.004 160)",
        "dark": "--success-foreground: oklch(0.99 0.004 160)  (no .dark override — Light duplicated)"
      }
    },
    {
      "name": "metal/bronze",
      "role": "metal-bronze",
      "light": {
        "L": 0.56,
        "C": 0.105,
        "h": 58,
        "a": 1
      },
      "dark": {
        "L": 0.72,
        "C": 0.105,
        "h": 58,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-bronze: oklch(0.56 0.105 58)",
        "dark": "--metal-bronze: oklch(0.72 0.105 58)  (.dark)"
      }
    },
    {
      "name": "metal/expanded-bronze",
      "role": "metal-expanded-bronze",
      "light": {
        "L": 0.52,
        "C": 0.09,
        "h": 58,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.095,
        "h": 58,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-expanded-bronze: oklch(0.52 0.09 58)",
        "dark": "--metal-expanded-bronze: oklch(0.68 0.095 58)  (.dark)"
      }
    },
    {
      "name": "metal/silver",
      "role": "metal-silver",
      "light": {
        "L": 0.58,
        "C": 0.018,
        "h": 255,
        "a": 1
      },
      "dark": {
        "L": 0.78,
        "C": 0.02,
        "h": 255,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-silver: oklch(0.58 0.018 255)",
        "dark": "--metal-silver: oklch(0.78 0.02 255)  (.dark)"
      }
    },
    {
      "name": "metal/gold",
      "role": "metal-gold",
      "light": {
        "L": 0.66,
        "C": 0.13,
        "h": 92,
        "a": 1
      },
      "dark": {
        "L": 0.82,
        "C": 0.13,
        "h": 92,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-gold: oklch(0.66 0.13 92)",
        "dark": "--metal-gold: oklch(0.82 0.13 92)  (.dark)"
      }
    },
    {
      "name": "metal/platinum",
      "role": "metal-platinum",
      "light": {
        "L": 0.56,
        "C": 0.075,
        "h": 205,
        "a": 1
      },
      "dark": {
        "L": 0.76,
        "C": 0.075,
        "h": 205,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-platinum: oklch(0.56 0.075 205)",
        "dark": "--metal-platinum: oklch(0.76 0.075 205)  (.dark)"
      }
    },
    {
      "name": "metal/catastrophic",
      "role": "metal-catastrophic",
      "light": {
        "L": 0.56,
        "C": 0.15,
        "h": 25,
        "a": 1
      },
      "dark": {
        "L": 0.7,
        "C": 0.12,
        "h": 25,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-catastrophic: oklch(0.56 0.15 25)",
        "dark": "--metal-catastrophic: oklch(0.7 0.12 25)  (.dark)"
      }
    },
    {
      "name": "metal/bronze-fg",
      "role": "metal-bronze-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.02,
        "h": 58,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-bronze-fg: oklch(0.99 0 0)",
        "dark": "--metal-bronze-fg: oklch(0.14 0.02 58)  (.dark)"
      }
    },
    {
      "name": "metal/expanded-bronze-fg",
      "role": "metal-expanded-bronze-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.02,
        "h": 58,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-expanded-bronze-fg: oklch(0.99 0 0)",
        "dark": "--metal-expanded-bronze-fg: oklch(0.14 0.02 58)  (.dark)"
      }
    },
    {
      "name": "metal/silver-fg",
      "role": "metal-silver-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.01,
        "h": 255,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-silver-fg: oklch(0.99 0 0)",
        "dark": "--metal-silver-fg: oklch(0.14 0.01 255)  (.dark)"
      }
    },
    {
      "name": "metal/gold-fg",
      "role": "metal-gold-fg",
      "light": {
        "L": 0.16,
        "C": 0.02,
        "h": 92,
        "a": 1
      },
      "dark": {
        "L": 0.16,
        "C": 0.02,
        "h": 92,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-gold-fg: oklch(0.16 0.02 92)",
        "dark": "--metal-gold-fg: oklch(0.16 0.02 92)  (.dark)"
      }
    },
    {
      "name": "metal/platinum-fg",
      "role": "metal-platinum-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.02,
        "h": 205,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-platinum-fg: oklch(0.99 0 0)",
        "dark": "--metal-platinum-fg: oklch(0.14 0.02 205)  (.dark)"
      }
    },
    {
      "name": "metal/catastrophic-fg",
      "role": "metal-catastrophic-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.02,
        "h": 25,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--metal-catastrophic-fg: oklch(0.99 0 0)",
        "dark": "--metal-catastrophic-fg: oklch(0.14 0.02 25)  (.dark)"
      }
    },
    {
      "name": "border",
      "role": "border",
      "light": {
        "L": 0.3,
        "C": 0.04,
        "h": 265,
        "a": 0.1
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.09
      },
      "darkOverridden": true,
      "source": {
        "light": "--border: oklch(0.3 0.04 265 / 0.1)",
        "dark": "--border: oklch(1 0 0 / 0.09)  (.dark)"
      }
    },
    {
      "name": "border-strong",
      "role": "border-strong",
      "light": {
        "L": 0.3,
        "C": 0.04,
        "h": 265,
        "a": 0.24
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.2
      },
      "darkOverridden": true,
      "source": {
        "light": "--border-strong: oklch(0.3 0.04 265 / 0.24)",
        "dark": "--border-strong: oklch(1 0 0 / 0.2)  (.dark)"
      }
    },
    {
      "name": "hairline",
      "role": "hairline",
      "light": {
        "L": 0.3,
        "C": 0.04,
        "h": 265,
        "a": 0.11
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.11
      },
      "darkOverridden": true,
      "source": {
        "light": "--hairline: oklch(0.3 0.04 265 / 0.11)",
        "dark": "--hairline: oklch(1 0 0 / 0.11)  (.dark)"
      }
    },
    {
      "name": "input",
      "role": "input",
      "light": {
        "L": 0.3,
        "C": 0.04,
        "h": 265,
        "a": 0.16
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.12
      },
      "darkOverridden": true,
      "source": {
        "light": "--input: oklch(0.3 0.04 265 / 0.16)",
        "dark": "--input: oklch(1 0 0 / 0.12)  (.dark)"
      }
    },
    {
      "name": "ring",
      "role": "ring",
      "light": {
        "L": 0.31,
        "C": 0.09,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--ring: oklch(0.31 0.09 265)",
        "dark": "--ring: oklch(0.68 0.125 255)  (.dark)"
      }
    },
    {
      "name": "chart/1",
      "role": "chart-1",
      "light": {
        "L": 0.31,
        "C": 0.09,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--chart-1: oklch(0.31 0.09 265)",
        "dark": "--chart-1: oklch(0.68 0.125 255)  (.dark)"
      }
    },
    {
      "name": "chart/2",
      "role": "chart-2",
      "light": {
        "L": 0.55,
        "C": 0.085,
        "h": 195,
        "a": 1
      },
      "dark": {
        "L": 0.74,
        "C": 0.09,
        "h": 195,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--chart-2: oklch(0.55 0.085 195)",
        "dark": "--chart-2: oklch(0.74 0.09 195)  (.dark)"
      }
    },
    {
      "name": "chart/3",
      "role": "chart-3",
      "light": {
        "L": 0.6,
        "C": 0.115,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.62,
        "C": 0.11,
        "h": 250,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--chart-3: oklch(0.6 0.115 250)",
        "dark": "--chart-3: oklch(0.62 0.11 250)  (.dark)"
      }
    },
    {
      "name": "chart/4",
      "role": "chart-4",
      "light": {
        "L": 0.72,
        "C": 0.125,
        "h": 75,
        "a": 1
      },
      "dark": {
        "L": 0.78,
        "C": 0.115,
        "h": 75,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--chart-4: oklch(0.72 0.125 75)",
        "dark": "--chart-4: oklch(0.78 0.115 75)  (.dark)"
      }
    },
    {
      "name": "chart/5",
      "role": "chart-5",
      "light": {
        "L": 0.62,
        "C": 0.02,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.7,
        "C": 0.02,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--chart-5: oklch(0.62 0.02 265)",
        "dark": "--chart-5: oklch(0.7 0.02 265)  (.dark)"
      }
    },
    {
      "name": "sidebar",
      "role": "sidebar",
      "light": {
        "L": 0.235,
        "C": 0.06,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.135,
        "C": 0.03,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sidebar: oklch(0.235 0.06 265)",
        "dark": "--sidebar: oklch(0.135 0.03 265)  (.dark)"
      }
    },
    {
      "name": "sidebar/foreground",
      "role": "sidebar-foreground",
      "light": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.92,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sidebar-foreground: oklch(0.95 0.006 265)",
        "dark": "--sidebar-foreground: oklch(0.92 0.006 265)  (.dark)"
      }
    },
    {
      "name": "sidebar/primary",
      "role": "sidebar-primary",
      "light": {
        "L": 0.66,
        "C": 0.12,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sidebar-primary: oklch(0.66 0.12 250)",
        "dark": "--sidebar-primary: oklch(0.68 0.125 255)  (.dark)"
      }
    },
    {
      "name": "sidebar/primary-foreground",
      "role": "sidebar-primary-foreground",
      "light": {
        "L": 0.16,
        "C": 0.045,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.16,
        "C": 0.045,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sidebar-primary-foreground: oklch(0.16 0.045 265)",
        "dark": "--sidebar-primary-foreground: oklch(0.16 0.045 265)  (.dark)"
      }
    },
    {
      "name": "sidebar/accent",
      "role": "sidebar-accent",
      "light": {
        "L": 0.29,
        "C": 0.065,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.235,
        "C": 0.04,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sidebar-accent: oklch(0.29 0.065 265)",
        "dark": "--sidebar-accent: oklch(0.235 0.04 265)  (.dark)"
      }
    },
    {
      "name": "sidebar/accent-foreground",
      "role": "sidebar-accent-foreground",
      "light": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sidebar-accent-foreground: oklch(0.95 0.006 265)",
        "dark": "--sidebar-accent-foreground: oklch(0.95 0.006 265)  (.dark)"
      }
    },
    {
      "name": "sidebar/border",
      "role": "sidebar-border",
      "light": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.09
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.08
      },
      "darkOverridden": true,
      "source": {
        "light": "--sidebar-border: oklch(1 0 0 / 0.09)",
        "dark": "--sidebar-border: oklch(1 0 0 / 0.08)  (.dark)"
      }
    },
    {
      "name": "sidebar/ring",
      "role": "sidebar-ring",
      "light": {
        "L": 0.66,
        "C": 0.12,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--sidebar-ring: oklch(0.66 0.12 250)",
        "dark": "--sidebar-ring: oklch(0.68 0.125 255)  (.dark)"
      }
    },
    {
      "name": "ai",
      "role": "ai",
      "light": {
        "L": 0.52,
        "C": 0.115,
        "h": 292,
        "a": 1
      },
      "dark": {
        "L": 0.7,
        "C": 0.12,
        "h": 292,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--ai: oklch(0.52 0.115 292)",
        "dark": "--ai: oklch(0.7 0.12 292)  (.dark)"
      }
    },
    {
      "name": "ai-foreground",
      "role": "ai-foreground",
      "light": {
        "L": 0.99,
        "C": 0.004,
        "h": 292,
        "a": 1
      },
      "dark": {
        "L": 0.16,
        "C": 0.035,
        "h": 292,
        "a": 1
      },
      "darkOverridden": true,
      "source": {
        "light": "--ai-foreground: oklch(0.99 0.004 292)",
        "dark": "--ai-foreground: oklch(0.16 0.035 292)  (.dark)"
      }
    }
  ],
  "semantics": [
    {
      "name": "background",
      "css": "--color-background: var(--background);",
      "aliasLight": "background",
      "aliasDark": "background",
      "chainLight": "--background",
      "chainDark": "--background"
    },
    {
      "name": "foreground",
      "css": "--color-foreground: var(--foreground);",
      "aliasLight": "foreground",
      "aliasDark": "foreground",
      "chainLight": "--foreground",
      "chainDark": "--foreground"
    },
    {
      "name": "surface",
      "css": "--color-surface: var(--surface);",
      "aliasLight": "surface",
      "aliasDark": "surface",
      "chainLight": "--surface",
      "chainDark": "--surface"
    },
    {
      "name": "surface-foreground",
      "css": "--color-surface-foreground: var(--surface-foreground);",
      "aliasLight": "surface-foreground",
      "aliasDark": "surface-foreground",
      "chainLight": "--surface-foreground",
      "chainDark": "--surface-foreground"
    },
    {
      "name": "panel",
      "css": "--color-panel: var(--panel);",
      "aliasLight": "panel",
      "aliasDark": "panel",
      "chainLight": "--panel",
      "chainDark": "--panel"
    },
    {
      "name": "card",
      "css": "--color-card: var(--card);",
      "aliasLight": "card",
      "aliasDark": "card",
      "chainLight": "--card",
      "chainDark": "--card"
    },
    {
      "name": "card-foreground",
      "css": "--color-card-foreground: var(--card-foreground);",
      "aliasLight": "card-foreground",
      "aliasDark": "card-foreground",
      "chainLight": "--card-foreground",
      "chainDark": "--card-foreground"
    },
    {
      "name": "popover",
      "css": "--color-popover: var(--popover);",
      "aliasLight": "popover",
      "aliasDark": "popover",
      "chainLight": "--popover",
      "chainDark": "--popover"
    },
    {
      "name": "popover-foreground",
      "css": "--color-popover-foreground: var(--popover-foreground);",
      "aliasLight": "popover-foreground",
      "aliasDark": "popover-foreground",
      "chainLight": "--popover-foreground",
      "chainDark": "--popover-foreground"
    },
    {
      "name": "primary",
      "css": "--color-primary: var(--primary);",
      "aliasLight": "primary",
      "aliasDark": "primary",
      "chainLight": "--primary",
      "chainDark": "--primary"
    },
    {
      "name": "primary-foreground",
      "css": "--color-primary-foreground: var(--primary-foreground);",
      "aliasLight": "primary-foreground",
      "aliasDark": "primary-foreground",
      "chainLight": "--primary-foreground",
      "chainDark": "--primary-foreground"
    },
    {
      "name": "primary-soft",
      "css": "--color-primary-soft: var(--primary-soft);",
      "aliasLight": "primary-soft",
      "aliasDark": "primary-soft",
      "chainLight": "--primary-soft",
      "chainDark": "--primary-soft"
    },
    {
      "name": "secondary",
      "css": "--color-secondary: var(--secondary);",
      "aliasLight": "secondary",
      "aliasDark": "secondary",
      "chainLight": "--secondary",
      "chainDark": "--secondary"
    },
    {
      "name": "secondary-foreground",
      "css": "--color-secondary-foreground: var(--secondary-foreground);",
      "aliasLight": "secondary-foreground",
      "aliasDark": "secondary-foreground",
      "chainLight": "--secondary-foreground",
      "chainDark": "--secondary-foreground"
    },
    {
      "name": "sage",
      "css": "--color-sage: var(--sage);",
      "aliasLight": "sage",
      "aliasDark": "sage",
      "chainLight": "--sage",
      "chainDark": "--sage"
    },
    {
      "name": "sage-foreground",
      "css": "--color-sage-foreground: var(--sage-foreground);",
      "aliasLight": "sage-foreground",
      "aliasDark": "sage-foreground",
      "chainLight": "--sage-foreground",
      "chainDark": "--sage-foreground"
    },
    {
      "name": "sage-soft",
      "css": "--color-sage-soft: var(--sage-soft);",
      "aliasLight": "sage-soft",
      "aliasDark": "sage-soft",
      "chainLight": "--sage-soft",
      "chainDark": "--sage-soft"
    },
    {
      "name": "muted",
      "css": "--color-muted: var(--muted);",
      "aliasLight": "muted",
      "aliasDark": "muted",
      "chainLight": "--muted",
      "chainDark": "--muted"
    },
    {
      "name": "muted-foreground",
      "css": "--color-muted-foreground: var(--muted-foreground);",
      "aliasLight": "muted-foreground",
      "aliasDark": "muted-foreground",
      "chainLight": "--muted-foreground",
      "chainDark": "--muted-foreground"
    },
    {
      "name": "accent",
      "css": "--color-accent: var(--accent);",
      "aliasLight": "accent",
      "aliasDark": "accent",
      "chainLight": "--accent",
      "chainDark": "--accent"
    },
    {
      "name": "accent-foreground",
      "css": "--color-accent-foreground: var(--accent-foreground);",
      "aliasLight": "accent-foreground",
      "aliasDark": "accent-foreground",
      "chainLight": "--accent-foreground",
      "chainDark": "--accent-foreground"
    },
    {
      "name": "destructive",
      "css": "--color-destructive: var(--destructive);",
      "aliasLight": "destructive",
      "aliasDark": "destructive",
      "chainLight": "--destructive",
      "chainDark": "--destructive"
    },
    {
      "name": "destructive-foreground",
      "css": "--color-destructive-foreground: var(--destructive-foreground);",
      "aliasLight": "destructive-foreground",
      "aliasDark": "destructive-foreground",
      "chainLight": "--destructive-foreground",
      "chainDark": "--destructive-foreground"
    },
    {
      "name": "warning",
      "css": "--color-warning: var(--warning);",
      "aliasLight": "warning",
      "aliasDark": "warning",
      "chainLight": "--warning",
      "chainDark": "--warning"
    },
    {
      "name": "warning-foreground",
      "css": "--color-warning-foreground: var(--warning-foreground);",
      "aliasLight": "warning-foreground",
      "aliasDark": "warning-foreground",
      "chainLight": "--warning-foreground",
      "chainDark": "--warning-foreground"
    },
    {
      "name": "info",
      "css": "--color-info: var(--info);",
      "aliasLight": "info",
      "aliasDark": "info",
      "chainLight": "--info",
      "chainDark": "--info"
    },
    {
      "name": "info-foreground",
      "css": "--color-info-foreground: var(--info-foreground);",
      "aliasLight": "info-foreground",
      "aliasDark": "info-foreground",
      "chainLight": "--info-foreground",
      "chainDark": "--info-foreground"
    },
    {
      "name": "success",
      "css": "--color-success: var(--success);",
      "aliasLight": "success",
      "aliasDark": "success",
      "chainLight": "--success",
      "chainDark": "--success"
    },
    {
      "name": "success-foreground",
      "css": "--color-success-foreground: var(--success-foreground);",
      "aliasLight": "success-foreground",
      "aliasDark": "success-foreground",
      "chainLight": "--success-foreground",
      "chainDark": "--success-foreground"
    },
    {
      "name": "border",
      "css": "--color-border: var(--border);",
      "aliasLight": "border",
      "aliasDark": "border",
      "chainLight": "--border",
      "chainDark": "--border"
    },
    {
      "name": "border-strong",
      "css": "--color-border-strong: var(--border-strong);",
      "aliasLight": "border-strong",
      "aliasDark": "border-strong",
      "chainLight": "--border-strong",
      "chainDark": "--border-strong"
    },
    {
      "name": "hairline",
      "css": "--color-hairline: var(--hairline);",
      "aliasLight": "hairline",
      "aliasDark": "hairline",
      "chainLight": "--hairline",
      "chainDark": "--hairline"
    },
    {
      "name": "input",
      "css": "--color-input: var(--input);",
      "aliasLight": "input",
      "aliasDark": "input",
      "chainLight": "--input",
      "chainDark": "--input"
    },
    {
      "name": "ring",
      "css": "--color-ring: var(--ring);",
      "aliasLight": "ring",
      "aliasDark": "ring",
      "chainLight": "--ring",
      "chainDark": "--ring"
    },
    {
      "name": "ring-offset-background",
      "css": "--color-ring-offset-background: var(--background);",
      "aliasLight": "background",
      "aliasDark": "background",
      "chainLight": "--background",
      "chainDark": "--background"
    },
    {
      "name": "chart/1",
      "css": "--color-chart-1: var(--chart-1);",
      "aliasLight": "chart/1",
      "aliasDark": "chart/1",
      "chainLight": "--chart-1",
      "chainDark": "--chart-1"
    },
    {
      "name": "chart/2",
      "css": "--color-chart-2: var(--chart-2);",
      "aliasLight": "chart/2",
      "aliasDark": "chart/2",
      "chainLight": "--chart-2",
      "chainDark": "--chart-2"
    },
    {
      "name": "chart/3",
      "css": "--color-chart-3: var(--chart-3);",
      "aliasLight": "chart/3",
      "aliasDark": "chart/3",
      "chainLight": "--chart-3",
      "chainDark": "--chart-3"
    },
    {
      "name": "chart/4",
      "css": "--color-chart-4: var(--chart-4);",
      "aliasLight": "chart/4",
      "aliasDark": "chart/4",
      "chainLight": "--chart-4",
      "chainDark": "--chart-4"
    },
    {
      "name": "chart/5",
      "css": "--color-chart-5: var(--chart-5);",
      "aliasLight": "chart/5",
      "aliasDark": "chart/5",
      "chainLight": "--chart-5",
      "chainDark": "--chart-5"
    },
    {
      "name": "sidebar",
      "css": "--color-sidebar: var(--sidebar);",
      "aliasLight": "sidebar",
      "aliasDark": "sidebar",
      "chainLight": "--sidebar",
      "chainDark": "--sidebar"
    },
    {
      "name": "sidebar/foreground",
      "css": "--color-sidebar-foreground: var(--sidebar-foreground);",
      "aliasLight": "sidebar/foreground",
      "aliasDark": "sidebar/foreground",
      "chainLight": "--sidebar-foreground",
      "chainDark": "--sidebar-foreground"
    },
    {
      "name": "sidebar/primary",
      "css": "--color-sidebar-primary: var(--sidebar-primary);",
      "aliasLight": "sidebar/primary",
      "aliasDark": "sidebar/primary",
      "chainLight": "--sidebar-primary",
      "chainDark": "--sidebar-primary"
    },
    {
      "name": "sidebar/primary-foreground",
      "css": "--color-sidebar-primary-foreground: var(--sidebar-primary-foreground);",
      "aliasLight": "sidebar/primary-foreground",
      "aliasDark": "sidebar/primary-foreground",
      "chainLight": "--sidebar-primary-foreground",
      "chainDark": "--sidebar-primary-foreground"
    },
    {
      "name": "sidebar/accent",
      "css": "--color-sidebar-accent: var(--sidebar-accent);",
      "aliasLight": "sidebar/accent",
      "aliasDark": "sidebar/accent",
      "chainLight": "--sidebar-accent",
      "chainDark": "--sidebar-accent"
    },
    {
      "name": "sidebar/accent-foreground",
      "css": "--color-sidebar-accent-foreground: var(--sidebar-accent-foreground);",
      "aliasLight": "sidebar/accent-foreground",
      "aliasDark": "sidebar/accent-foreground",
      "chainLight": "--sidebar-accent-foreground",
      "chainDark": "--sidebar-accent-foreground"
    },
    {
      "name": "sidebar/border",
      "css": "--color-sidebar-border: var(--sidebar-border);",
      "aliasLight": "sidebar/border",
      "aliasDark": "sidebar/border",
      "chainLight": "--sidebar-border",
      "chainDark": "--sidebar-border"
    },
    {
      "name": "sidebar/ring",
      "css": "--color-sidebar-ring: var(--sidebar-ring);",
      "aliasLight": "sidebar/ring",
      "aliasDark": "sidebar/ring",
      "chainLight": "--sidebar-ring",
      "chainDark": "--sidebar-ring"
    },
    {
      "name": "ai",
      "css": "--color-ai: var(--ai);",
      "aliasLight": "ai",
      "aliasDark": "ai",
      "chainLight": "--ai",
      "chainDark": "--ai"
    },
    {
      "name": "ai-foreground",
      "css": "--color-ai-foreground: var(--ai-foreground);",
      "aliasLight": "ai-foreground",
      "aliasDark": "ai-foreground",
      "chainLight": "--ai-foreground",
      "chainDark": "--ai-foreground"
    },
    {
      "name": "surface-1",
      "css": "--color-surface-1: var(--surface-1);",
      "aliasLight": "card",
      "aliasDark": "card",
      "chainLight": "--surface-1 -> --card",
      "chainDark": "--surface-1 -> --card"
    },
    {
      "name": "surface-2",
      "css": "--color-surface-2: var(--surface-2);",
      "aliasLight": "surface",
      "aliasDark": "surface",
      "chainLight": "--surface-2 -> --surface",
      "chainDark": "--surface-2 -> --surface"
    },
    {
      "name": "surface-3",
      "css": "--color-surface-3: var(--surface-3);",
      "aliasLight": "panel",
      "aliasDark": "panel",
      "chainLight": "--surface-3 -> --panel",
      "chainDark": "--surface-3 -> --panel"
    },
    {
      "name": "brand-accent",
      "css": "--color-brand-accent: var(--brand-accent);",
      "aliasLight": "primary",
      "aliasDark": "primary",
      "chainLight": "--brand-accent -> --primary",
      "chainDark": "--brand-accent -> --primary"
    }
  ],
  "tones": [
    {
      "name": "sage",
      "alias": "sage",
      "source": "src/components/abox/status-badge.tsx — tones.sage: \"[--tone:var(--sage)]\""
    },
    {
      "name": "primary",
      "alias": "primary",
      "source": "src/components/abox/status-badge.tsx — tones.primary: \"[--tone:var(--primary)]\""
    },
    {
      "name": "warning",
      "alias": "warning",
      "source": "src/components/abox/status-badge.tsx — tones.warning: \"[--tone:var(--warning)]\""
    },
    {
      "name": "muted",
      "alias": "foreground",
      "source": "src/components/abox/status-badge.tsx — tones.muted: \"[--tone:var(--foreground)]\""
    },
    {
      "name": "destructive",
      "alias": "destructive",
      "source": "src/components/abox/status-badge.tsx — tones.destructive: \"[--tone:var(--destructive)]\""
    },
    {
      "name": "info",
      "alias": "info",
      "source": "src/components/abox/status-badge.tsx — tones.info: \"[--tone:var(--info)]\""
    }
  ],
  "metals": [
    {
      "name": "metal/bronze",
      "alias": "metal/bronze",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-bronze)]"
    },
    {
      "name": "metal/expanded-bronze",
      "alias": "metal/expanded-bronze",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-expanded-bronze)]"
    },
    {
      "name": "metal/silver",
      "alias": "metal/silver",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-silver)]"
    },
    {
      "name": "metal/gold",
      "alias": "metal/gold",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-gold)]"
    },
    {
      "name": "metal/platinum",
      "alias": "metal/platinum",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-platinum)]"
    },
    {
      "name": "metal/catastrophic",
      "alias": "metal/catastrophic",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-catastrophic)]"
    },
    {
      "name": "metal/bronze-fg",
      "alias": "metal/bronze-fg",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-bronze-fg)]"
    },
    {
      "name": "metal/expanded-bronze-fg",
      "alias": "metal/expanded-bronze-fg",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-expanded-bronze-fg)]"
    },
    {
      "name": "metal/silver-fg",
      "alias": "metal/silver-fg",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-silver-fg)]"
    },
    {
      "name": "metal/gold-fg",
      "alias": "metal/gold-fg",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-gold-fg)]"
    },
    {
      "name": "metal/platinum-fg",
      "alias": "metal/platinum-fg",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-platinum-fg)]"
    },
    {
      "name": "metal/catastrophic-fg",
      "alias": "metal/catastrophic-fg",
      "source": "src/components/abox/metal-badge.tsx — [--tone:var(--metal-catastrophic-fg)]"
    }
  ],
  "spacing": {
    "surface/none": 0,
    "surface/sm": 16,
    "surface/md": 20,
    "surface/lg": 24
  },
  "radius": {
    "sm": 6,
    "md": 10,
    "lg": 14,
    "xl": 18,
    "2xl": 22,
    "3xl": 28,
    "4xl": 36,
    "base": 14,
    "full": 9999
  },
  "border": {
    "hairline": 1,
    "ring": 2
  },
  "shadows": {
    "card": [
      {
        "index": 1,
        "x": 0,
        "y": 1,
        "blur": 0,
        "spread": 0,
        "tint": {
          "L": 0.3,
          "C": 0.05,
          "h": 265,
          "a": 0.04
        },
        "tintCss": "oklch(0.3 0.05 265 / 0.04)"
      },
      {
        "index": 2,
        "x": 0,
        "y": 12,
        "blur": 24,
        "spread": -18,
        "tint": {
          "L": 0.3,
          "C": 0.05,
          "h": 265,
          "a": 0.2
        },
        "tintCss": "oklch(0.3 0.05 265 / 0.2)"
      }
    ],
    "elevated": [
      {
        "index": 1,
        "x": 0,
        "y": 1,
        "blur": 0,
        "spread": 0,
        "tint": {
          "L": 0.3,
          "C": 0.05,
          "h": 265,
          "a": 0.06
        },
        "tintCss": "oklch(0.3 0.05 265 / 0.06)"
      },
      {
        "index": 2,
        "x": 0,
        "y": 24,
        "blur": 44,
        "spread": -22,
        "tint": {
          "L": 0.3,
          "C": 0.05,
          "h": 265,
          "a": 0.26
        },
        "tintCss": "oklch(0.3 0.05 265 / 0.26)"
      }
    ],
    "drawer": [
      {
        "index": 1,
        "x": -20,
        "y": 0,
        "blur": 60,
        "spread": -30,
        "tint": {
          "L": 0.3,
          "C": 0.05,
          "h": 265,
          "a": 0.3
        },
        "tintCss": "oklch(0.3 0.05 265 / 0.3)"
      }
    ],
    "plate": [
      {
        "index": 1,
        "x": 0,
        "y": 0,
        "blur": 0,
        "spread": 1,
        "tint": {
          "L": 0.3,
          "C": 0.05,
          "h": 265,
          "a": 0.06
        },
        "tintCss": "oklch(0.3 0.05 265 / 0.06)"
      },
      {
        "index": 2,
        "x": 0,
        "y": 20,
        "blur": 40,
        "spread": -24,
        "tint": {
          "L": 0.3,
          "C": 0.05,
          "h": 265,
          "a": 0.22
        },
        "tintCss": "oklch(0.3 0.05 265 / 0.22)"
      }
    ],
    "glow": [
      {
        "index": 1,
        "x": 0,
        "y": 1,
        "blur": 0,
        "spread": 0,
        "tint": {
          "L": 0.31,
          "C": 0.09,
          "h": 265,
          "a": 0.32
        },
        "tintCss": "oklch(0.31 0.09 265 / 0.32)"
      },
      {
        "index": 2,
        "x": 0,
        "y": 10,
        "blur": 20,
        "spread": -14,
        "tint": {
          "L": 0.24,
          "C": 0.07,
          "h": 265,
          "a": 0.55
        },
        "tintCss": "oklch(0.24 0.07 265 / 0.55)"
      }
    ]
  },
  "layout": {
    "container/wide": 1408,
    "container/shell": 1500
  },
  "control": {
    "height/md": 40,
    "height/lg": 44,
    "padding-x": 12,
    "min-touch-target": 44
  },
  "limitations": [
    "StatusBadge colour/background/border use color-mix(in oklch, var(--tone) …, …) (src/components/abox/status-badge.tsx): runtime-computed, no static Figma variable created.",
    "Composite box-shadow is not a Figma variable type: --shadow-* is decomposed into x/y/blur/spread/tint variables. Effect Styles are a later batch.",
    "oklch() has no Figma equivalent: values are stored as sRGB and the original oklch literal is preserved in each variable description.",
    "Production declares no .dark override for --shadow-*: the Light value is duplicated into Dark because Figma has no CSS cascade."
  ]
};
