// GENERATED by tools/figma-plugin/extract-b1.mjs — edit the extractor or src/styles.css, not this file.
const ABOX_B1 = {
  "meta": {
    "phase": "52/B1",
    "generatedBy": "tools/figma-plugin/extract-b1.mjs",
    "source": "src/styles.css",
    "note": "Colours are oklch [L, C, h] (+alpha); converted to sRGB at run time. Recorded Figma limitation, never a production change."
  },
  "collections": [
    {
      "name": "ABox/Color/Primitive",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Color/Semantic",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Status",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Spacing",
      "modes": [
        "Default"
      ]
    },
    {
      "name": "ABox/Radius",
      "modes": [
        "Default"
      ]
    },
    {
      "name": "ABox/Border",
      "modes": [
        "Default"
      ]
    },
    {
      "name": "ABox/Elevation",
      "modes": [
        "Light",
        "Dark"
      ]
    },
    {
      "name": "ABox/Layout",
      "modes": [
        "Default"
      ]
    },
    {
      "name": "ABox/Control sizing",
      "modes": [
        "Default"
      ]
    }
  ],
  "primitives": [
    {
      "name": "background",
      "role": "background",
      "light": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.165,
        "C": 0.03,
        "h": 265,
        "a": 1
      },
      "css": "--background",
      "source": {
        "light": "oklch(1 0 0)",
        "dark": "oklch(0.165 0.03 265)"
      }
    },
    {
      "name": "foreground",
      "role": "foreground",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "css": "--foreground",
      "source": {
        "light": "oklch(0.22 0.025 265)",
        "dark": "oklch(0.95 0.006 265)"
      }
    },
    {
      "name": "surface",
      "role": "surface",
      "light": {
        "L": 0.968,
        "C": 0.003,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.195,
        "C": 0.035,
        "h": 265,
        "a": 1
      },
      "css": "--surface",
      "source": {
        "light": "oklch(0.968 0.003 265)",
        "dark": "oklch(0.195 0.035 265)"
      }
    },
    {
      "name": "surface/foreground",
      "role": "surface-foreground",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "css": "--surface-foreground",
      "source": {
        "light": "oklch(0.22 0.025 265)",
        "dark": "oklch(0.95 0.006 265)"
      }
    },
    {
      "name": "panel",
      "role": "panel",
      "light": {
        "L": 0.945,
        "C": 0.004,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.225,
        "C": 0.04,
        "h": 265,
        "a": 1
      },
      "css": "--panel",
      "source": {
        "light": "oklch(0.945 0.004 265)",
        "dark": "oklch(0.225 0.04 265)"
      }
    },
    {
      "name": "ink",
      "role": "ink",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "css": "--ink",
      "source": {
        "light": "oklch(0.22 0.025 265)",
        "dark": "oklch(0.95 0.006 265)"
      }
    },
    {
      "name": "card",
      "role": "card",
      "light": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.205,
        "C": 0.036,
        "h": 265,
        "a": 1
      },
      "css": "--card",
      "source": {
        "light": "oklch(1 0 0)",
        "dark": "oklch(0.205 0.036 265)"
      }
    },
    {
      "name": "card/foreground",
      "role": "card-foreground",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "css": "--card-foreground",
      "source": {
        "light": "oklch(0.22 0.025 265)",
        "dark": "oklch(0.95 0.006 265)"
      }
    },
    {
      "name": "popover",
      "role": "popover",
      "light": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.215,
        "C": 0.038,
        "h": 265,
        "a": 1
      },
      "css": "--popover",
      "source": {
        "light": "oklch(1 0 0)",
        "dark": "oklch(0.215 0.038 265)"
      }
    },
    {
      "name": "popover/foreground",
      "role": "popover-foreground",
      "light": {
        "L": 0.22,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "css": "--popover-foreground",
      "source": {
        "light": "oklch(0.22 0.025 265)",
        "dark": "oklch(0.95 0.006 265)"
      }
    },
    {
      "name": "primary",
      "role": "primary",
      "light": {
        "L": 0.31,
        "C": 0.09,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "css": "--primary",
      "source": {
        "light": "oklch(0.31 0.09 265)",
        "dark": "oklch(0.68 0.125 255)"
      }
    },
    {
      "name": "primary/foreground",
      "role": "primary-foreground",
      "light": {
        "L": 0.99,
        "C": 0.002,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.16,
        "C": 0.045,
        "h": 265,
        "a": 1
      },
      "css": "--primary-foreground",
      "source": {
        "light": "oklch(0.99 0.002 265)",
        "dark": "oklch(0.16 0.045 265)"
      }
    },
    {
      "name": "primary/soft",
      "role": "primary-soft",
      "light": {
        "L": 0.945,
        "C": 0.02,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.3,
        "C": 0.07,
        "h": 265,
        "a": 1
      },
      "css": "--primary-soft",
      "source": {
        "light": "oklch(0.945 0.02 265)",
        "dark": "oklch(0.3 0.07 265)"
      }
    },
    {
      "name": "secondary",
      "role": "secondary",
      "light": {
        "L": 0.955,
        "C": 0.004,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.255,
        "C": 0.04,
        "h": 265,
        "a": 1
      },
      "css": "--secondary",
      "source": {
        "light": "oklch(0.955 0.004 265)",
        "dark": "oklch(0.255 0.04 265)"
      }
    },
    {
      "name": "secondary/foreground",
      "role": "secondary-foreground",
      "light": {
        "L": 0.24,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "css": "--secondary-foreground",
      "source": {
        "light": "oklch(0.24 0.025 265)",
        "dark": "oklch(0.95 0.006 265)"
      }
    },
    {
      "name": "sage",
      "role": "sage",
      "light": {
        "L": 0.55,
        "C": 0.085,
        "h": 195,
        "a": 1
      },
      "dark": {
        "L": 0.74,
        "C": 0.09,
        "h": 195,
        "a": 1
      },
      "css": "--sage",
      "source": {
        "light": "oklch(0.55 0.085 195)",
        "dark": "oklch(0.74 0.09 195)"
      }
    },
    {
      "name": "sage/foreground",
      "role": "sage-foreground",
      "light": {
        "L": 0.99,
        "C": 0.004,
        "h": 195,
        "a": 1
      },
      "dark": {
        "L": 0.16,
        "C": 0.035,
        "h": 195,
        "a": 1
      },
      "css": "--sage-foreground",
      "source": {
        "light": "oklch(0.99 0.004 195)",
        "dark": "oklch(0.16 0.035 195)"
      }
    },
    {
      "name": "sage/soft",
      "role": "sage-soft",
      "light": {
        "L": 0.945,
        "C": 0.03,
        "h": 195,
        "a": 1
      },
      "dark": {
        "L": 0.3,
        "C": 0.055,
        "h": 195,
        "a": 1
      },
      "css": "--sage-soft",
      "source": {
        "light": "oklch(0.945 0.03 195)",
        "dark": "oklch(0.3 0.055 195)"
      }
    },
    {
      "name": "muted",
      "role": "muted",
      "light": {
        "L": 0.955,
        "C": 0.004,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.235,
        "C": 0.036,
        "h": 265,
        "a": 1
      },
      "css": "--muted",
      "source": {
        "light": "oklch(0.955 0.004 265)",
        "dark": "oklch(0.235 0.036 265)"
      }
    },
    {
      "name": "muted/foreground",
      "role": "muted-foreground",
      "light": {
        "L": 0.5,
        "C": 0.018,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.73,
        "C": 0.015,
        "h": 265,
        "a": 1
      },
      "css": "--muted-foreground",
      "source": {
        "light": "oklch(0.5 0.018 265)",
        "dark": "oklch(0.73 0.015 265)"
      }
    },
    {
      "name": "accent",
      "role": "accent",
      "light": {
        "L": 0.955,
        "C": 0.004,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.255,
        "C": 0.04,
        "h": 265,
        "a": 1
      },
      "css": "--accent",
      "source": {
        "light": "oklch(0.955 0.004 265)",
        "dark": "oklch(0.255 0.04 265)"
      }
    },
    {
      "name": "accent/foreground",
      "role": "accent-foreground",
      "light": {
        "L": 0.24,
        "C": 0.025,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "css": "--accent-foreground",
      "source": {
        "light": "oklch(0.24 0.025 265)",
        "dark": "oklch(0.95 0.006 265)"
      }
    },
    {
      "name": "destructive",
      "role": "destructive",
      "light": {
        "L": 0.55,
        "C": 0.185,
        "h": 25,
        "a": 1
      },
      "dark": {
        "L": 0.55,
        "C": 0.185,
        "h": 25,
        "a": 1
      },
      "css": "--destructive",
      "source": {
        "light": "oklch(0.55 0.185 25)",
        "dark": "oklch(0.55 0.185 25)"
      }
    },
    {
      "name": "destructive/foreground",
      "role": "destructive-foreground",
      "light": {
        "L": 0.99,
        "C": 0.004,
        "h": 25,
        "a": 1
      },
      "dark": {
        "L": 0.99,
        "C": 0.004,
        "h": 25,
        "a": 1
      },
      "css": "--destructive-foreground",
      "source": {
        "light": "oklch(0.99 0.004 25)",
        "dark": "oklch(0.99 0.004 25)"
      }
    },
    {
      "name": "warning",
      "role": "warning",
      "light": {
        "L": 0.72,
        "C": 0.125,
        "h": 75,
        "a": 1
      },
      "dark": {
        "L": 0.78,
        "C": 0.115,
        "h": 75,
        "a": 1
      },
      "css": "--warning",
      "source": {
        "light": "oklch(0.72 0.125 75)",
        "dark": "oklch(0.78 0.115 75)"
      }
    },
    {
      "name": "warning/foreground",
      "role": "warning-foreground",
      "light": {
        "L": 0.22,
        "C": 0.045,
        "h": 75,
        "a": 1
      },
      "dark": {
        "L": 0.22,
        "C": 0.045,
        "h": 75,
        "a": 1
      },
      "css": "--warning-foreground",
      "source": {
        "light": "oklch(0.22 0.045 75)",
        "dark": "oklch(0.22 0.045 75)"
      }
    },
    {
      "name": "info",
      "role": "info",
      "light": {
        "L": 0.55,
        "C": 0.12,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.7,
        "C": 0.115,
        "h": 250,
        "a": 1
      },
      "css": "--info",
      "source": {
        "light": "oklch(0.55 0.12 250)",
        "dark": "oklch(0.7 0.115 250)"
      }
    },
    {
      "name": "info/foreground",
      "role": "info-foreground",
      "light": {
        "L": 0.99,
        "C": 0.004,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.99,
        "C": 0.004,
        "h": 250,
        "a": 1
      },
      "css": "--info-foreground",
      "source": {
        "light": "oklch(0.99 0.004 250)",
        "dark": "oklch(0.99 0.004 250)"
      }
    },
    {
      "name": "success",
      "role": "success",
      "light": {
        "L": 0.55,
        "C": 0.1,
        "h": 160,
        "a": 1
      },
      "dark": {
        "L": 0.7,
        "C": 0.095,
        "h": 160,
        "a": 1
      },
      "css": "--success",
      "source": {
        "light": "oklch(0.55 0.1 160)",
        "dark": "oklch(0.7 0.095 160)"
      }
    },
    {
      "name": "success/foreground",
      "role": "success-foreground",
      "light": {
        "L": 0.99,
        "C": 0.004,
        "h": 160,
        "a": 1
      },
      "dark": {
        "L": 0.99,
        "C": 0.004,
        "h": 160,
        "a": 1
      },
      "css": "--success-foreground",
      "source": {
        "light": "oklch(0.99 0.004 160)",
        "dark": "oklch(0.99 0.004 160)"
      }
    },
    {
      "name": "border",
      "role": "border",
      "light": {
        "L": 0.3,
        "C": 0.04,
        "h": 265,
        "a": 0.1
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.09
      },
      "css": "--border",
      "source": {
        "light": "oklch(0.3 0.04 265 / 0.1)",
        "dark": "oklch(1 0 0 / 0.09)"
      }
    },
    {
      "name": "border-strong",
      "role": "border-strong",
      "light": {
        "L": 0.3,
        "C": 0.04,
        "h": 265,
        "a": 0.24
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.2
      },
      "css": "--border-strong",
      "source": {
        "light": "oklch(0.3 0.04 265 / 0.24)",
        "dark": "oklch(1 0 0 / 0.2)"
      }
    },
    {
      "name": "hairline",
      "role": "hairline",
      "light": {
        "L": 0.3,
        "C": 0.04,
        "h": 265,
        "a": 0.11
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.11
      },
      "css": "--hairline",
      "source": {
        "light": "oklch(0.3 0.04 265 / 0.11)",
        "dark": "oklch(1 0 0 / 0.11)"
      }
    },
    {
      "name": "input",
      "role": "input",
      "light": {
        "L": 0.3,
        "C": 0.04,
        "h": 265,
        "a": 0.16
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.12
      },
      "css": "--input",
      "source": {
        "light": "oklch(0.3 0.04 265 / 0.16)",
        "dark": "oklch(1 0 0 / 0.12)"
      }
    },
    {
      "name": "ring",
      "role": "ring",
      "light": {
        "L": 0.31,
        "C": 0.09,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "css": "--ring",
      "source": {
        "light": "oklch(0.31 0.09 265)",
        "dark": "oklch(0.68 0.125 255)"
      }
    },
    {
      "name": "chart/1",
      "role": "chart-1",
      "light": {
        "L": 0.31,
        "C": 0.09,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "css": "--chart-1",
      "source": {
        "light": "oklch(0.31 0.09 265)",
        "dark": "oklch(0.68 0.125 255)"
      }
    },
    {
      "name": "chart/2",
      "role": "chart-2",
      "light": {
        "L": 0.55,
        "C": 0.085,
        "h": 195,
        "a": 1
      },
      "dark": {
        "L": 0.74,
        "C": 0.09,
        "h": 195,
        "a": 1
      },
      "css": "--chart-2",
      "source": {
        "light": "oklch(0.55 0.085 195)",
        "dark": "oklch(0.74 0.09 195)"
      }
    },
    {
      "name": "chart/3",
      "role": "chart-3",
      "light": {
        "L": 0.6,
        "C": 0.115,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.62,
        "C": 0.11,
        "h": 250,
        "a": 1
      },
      "css": "--chart-3",
      "source": {
        "light": "oklch(0.6 0.115 250)",
        "dark": "oklch(0.62 0.11 250)"
      }
    },
    {
      "name": "chart/4",
      "role": "chart-4",
      "light": {
        "L": 0.72,
        "C": 0.125,
        "h": 75,
        "a": 1
      },
      "dark": {
        "L": 0.78,
        "C": 0.115,
        "h": 75,
        "a": 1
      },
      "css": "--chart-4",
      "source": {
        "light": "oklch(0.72 0.125 75)",
        "dark": "oklch(0.78 0.115 75)"
      }
    },
    {
      "name": "chart/5",
      "role": "chart-5",
      "light": {
        "L": 0.62,
        "C": 0.02,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.7,
        "C": 0.02,
        "h": 265,
        "a": 1
      },
      "css": "--chart-5",
      "source": {
        "light": "oklch(0.62 0.02 265)",
        "dark": "oklch(0.7 0.02 265)"
      }
    },
    {
      "name": "sidebar",
      "role": "sidebar",
      "light": {
        "L": 0.235,
        "C": 0.06,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.135,
        "C": 0.03,
        "h": 265,
        "a": 1
      },
      "css": "--sidebar",
      "source": {
        "light": "oklch(0.235 0.06 265)",
        "dark": "oklch(0.135 0.03 265)"
      }
    },
    {
      "name": "sidebar/foreground",
      "role": "sidebar-foreground",
      "light": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.92,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "css": "--sidebar-foreground",
      "source": {
        "light": "oklch(0.95 0.006 265)",
        "dark": "oklch(0.92 0.006 265)"
      }
    },
    {
      "name": "sidebar/primary",
      "role": "sidebar-primary",
      "light": {
        "L": 0.66,
        "C": 0.12,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "css": "--sidebar-primary",
      "source": {
        "light": "oklch(0.66 0.12 250)",
        "dark": "oklch(0.68 0.125 255)"
      }
    },
    {
      "name": "sidebar/primary-foreground",
      "role": "sidebar-primary-foreground",
      "light": {
        "L": 0.16,
        "C": 0.045,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.16,
        "C": 0.045,
        "h": 265,
        "a": 1
      },
      "css": "--sidebar-primary-foreground",
      "source": {
        "light": "oklch(0.16 0.045 265)",
        "dark": "oklch(0.16 0.045 265)"
      }
    },
    {
      "name": "sidebar/accent",
      "role": "sidebar-accent",
      "light": {
        "L": 0.29,
        "C": 0.065,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.235,
        "C": 0.04,
        "h": 265,
        "a": 1
      },
      "css": "--sidebar-accent",
      "source": {
        "light": "oklch(0.29 0.065 265)",
        "dark": "oklch(0.235 0.04 265)"
      }
    },
    {
      "name": "sidebar/accent-foreground",
      "role": "sidebar-accent-foreground",
      "light": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "dark": {
        "L": 0.95,
        "C": 0.006,
        "h": 265,
        "a": 1
      },
      "css": "--sidebar-accent-foreground",
      "source": {
        "light": "oklch(0.95 0.006 265)",
        "dark": "oklch(0.95 0.006 265)"
      }
    },
    {
      "name": "sidebar/border",
      "role": "sidebar-border",
      "light": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.09
      },
      "dark": {
        "L": 1,
        "C": 0,
        "h": 0,
        "a": 0.08
      },
      "css": "--sidebar-border",
      "source": {
        "light": "oklch(1 0 0 / 0.09)",
        "dark": "oklch(1 0 0 / 0.08)"
      }
    },
    {
      "name": "sidebar/ring",
      "role": "sidebar-ring",
      "light": {
        "L": 0.66,
        "C": 0.12,
        "h": 250,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.125,
        "h": 255,
        "a": 1
      },
      "css": "--sidebar-ring",
      "source": {
        "light": "oklch(0.66 0.12 250)",
        "dark": "oklch(0.68 0.125 255)"
      }
    },
    {
      "name": "metal/bronze",
      "role": "metal-bronze",
      "light": {
        "L": 0.56,
        "C": 0.105,
        "h": 58,
        "a": 1
      },
      "dark": {
        "L": 0.72,
        "C": 0.105,
        "h": 58,
        "a": 1
      },
      "css": "--metal-bronze",
      "source": {
        "light": "oklch(0.56 0.105 58)",
        "dark": "oklch(0.72 0.105 58)"
      }
    },
    {
      "name": "metal/expanded-bronze",
      "role": "metal-expanded-bronze",
      "light": {
        "L": 0.52,
        "C": 0.09,
        "h": 58,
        "a": 1
      },
      "dark": {
        "L": 0.68,
        "C": 0.095,
        "h": 58,
        "a": 1
      },
      "css": "--metal-expanded-bronze",
      "source": {
        "light": "oklch(0.52 0.09 58)",
        "dark": "oklch(0.68 0.095 58)"
      }
    },
    {
      "name": "metal/silver",
      "role": "metal-silver",
      "light": {
        "L": 0.58,
        "C": 0.018,
        "h": 255,
        "a": 1
      },
      "dark": {
        "L": 0.78,
        "C": 0.02,
        "h": 255,
        "a": 1
      },
      "css": "--metal-silver",
      "source": {
        "light": "oklch(0.58 0.018 255)",
        "dark": "oklch(0.78 0.02 255)"
      }
    },
    {
      "name": "metal/gold",
      "role": "metal-gold",
      "light": {
        "L": 0.66,
        "C": 0.13,
        "h": 92,
        "a": 1
      },
      "dark": {
        "L": 0.82,
        "C": 0.13,
        "h": 92,
        "a": 1
      },
      "css": "--metal-gold",
      "source": {
        "light": "oklch(0.66 0.13 92)",
        "dark": "oklch(0.82 0.13 92)"
      }
    },
    {
      "name": "metal/platinum",
      "role": "metal-platinum",
      "light": {
        "L": 0.56,
        "C": 0.075,
        "h": 205,
        "a": 1
      },
      "dark": {
        "L": 0.76,
        "C": 0.075,
        "h": 205,
        "a": 1
      },
      "css": "--metal-platinum",
      "source": {
        "light": "oklch(0.56 0.075 205)",
        "dark": "oklch(0.76 0.075 205)"
      }
    },
    {
      "name": "metal/catastrophic",
      "role": "metal-catastrophic",
      "light": {
        "L": 0.56,
        "C": 0.15,
        "h": 25,
        "a": 1
      },
      "dark": {
        "L": 0.7,
        "C": 0.12,
        "h": 25,
        "a": 1
      },
      "css": "--metal-catastrophic",
      "source": {
        "light": "oklch(0.56 0.15 25)",
        "dark": "oklch(0.7 0.12 25)"
      }
    },
    {
      "name": "metal/bronze-fg",
      "role": "metal-bronze-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.02,
        "h": 58,
        "a": 1
      },
      "css": "--metal-bronze-fg",
      "source": {
        "light": "oklch(0.99 0 0)",
        "dark": "oklch(0.14 0.02 58)"
      }
    },
    {
      "name": "metal/expanded-bronze-fg",
      "role": "metal-expanded-bronze-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.02,
        "h": 58,
        "a": 1
      },
      "css": "--metal-expanded-bronze-fg",
      "source": {
        "light": "oklch(0.99 0 0)",
        "dark": "oklch(0.14 0.02 58)"
      }
    },
    {
      "name": "metal/silver-fg",
      "role": "metal-silver-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.01,
        "h": 255,
        "a": 1
      },
      "css": "--metal-silver-fg",
      "source": {
        "light": "oklch(0.99 0 0)",
        "dark": "oklch(0.14 0.01 255)"
      }
    },
    {
      "name": "metal/gold-fg",
      "role": "metal-gold-fg",
      "light": {
        "L": 0.16,
        "C": 0.02,
        "h": 92,
        "a": 1
      },
      "dark": {
        "L": 0.16,
        "C": 0.02,
        "h": 92,
        "a": 1
      },
      "css": "--metal-gold-fg",
      "source": {
        "light": "oklch(0.16 0.02 92)",
        "dark": "oklch(0.16 0.02 92)"
      }
    },
    {
      "name": "metal/platinum-fg",
      "role": "metal-platinum-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.02,
        "h": 205,
        "a": 1
      },
      "css": "--metal-platinum-fg",
      "source": {
        "light": "oklch(0.99 0 0)",
        "dark": "oklch(0.14 0.02 205)"
      }
    },
    {
      "name": "metal/catastrophic-fg",
      "role": "metal-catastrophic-fg",
      "light": {
        "L": 0.99,
        "C": 0,
        "h": 0,
        "a": 1
      },
      "dark": {
        "L": 0.14,
        "C": 0.02,
        "h": 25,
        "a": 1
      },
      "css": "--metal-catastrophic-fg",
      "source": {
        "light": "oklch(0.99 0 0)",
        "dark": "oklch(0.14 0.02 25)"
      }
    }
  ],
  "semantics": [
    {
      "name": "background",
      "alias": "background",
      "css": "--color-background"
    },
    {
      "name": "foreground",
      "alias": "foreground",
      "css": "--color-foreground"
    },
    {
      "name": "surface",
      "alias": "surface",
      "css": "--color-surface"
    },
    {
      "name": "surface/foreground",
      "alias": "surface/foreground",
      "css": "--color-surface-foreground"
    },
    {
      "name": "panel",
      "alias": "panel",
      "css": "--color-panel"
    },
    {
      "name": "ink",
      "alias": "ink",
      "css": "--color-ink"
    },
    {
      "name": "card",
      "alias": "card",
      "css": "--color-card"
    },
    {
      "name": "card/foreground",
      "alias": "card/foreground",
      "css": "--color-card-foreground"
    },
    {
      "name": "popover",
      "alias": "popover",
      "css": "--color-popover"
    },
    {
      "name": "popover/foreground",
      "alias": "popover/foreground",
      "css": "--color-popover-foreground"
    },
    {
      "name": "primary",
      "alias": "primary",
      "css": "--color-primary"
    },
    {
      "name": "primary/foreground",
      "alias": "primary/foreground",
      "css": "--color-primary-foreground"
    },
    {
      "name": "primary/soft",
      "alias": "primary/soft",
      "css": "--color-primary-soft"
    },
    {
      "name": "secondary",
      "alias": "secondary",
      "css": "--color-secondary"
    },
    {
      "name": "secondary/foreground",
      "alias": "secondary/foreground",
      "css": "--color-secondary-foreground"
    },
    {
      "name": "sage",
      "alias": "sage",
      "css": "--color-sage"
    },
    {
      "name": "sage/foreground",
      "alias": "sage/foreground",
      "css": "--color-sage-foreground"
    },
    {
      "name": "sage/soft",
      "alias": "sage/soft",
      "css": "--color-sage-soft"
    },
    {
      "name": "muted",
      "alias": "muted",
      "css": "--color-muted"
    },
    {
      "name": "muted/foreground",
      "alias": "muted/foreground",
      "css": "--color-muted-foreground"
    },
    {
      "name": "accent",
      "alias": "accent",
      "css": "--color-accent"
    },
    {
      "name": "accent/foreground",
      "alias": "accent/foreground",
      "css": "--color-accent-foreground"
    },
    {
      "name": "destructive",
      "alias": "destructive",
      "css": "--color-destructive"
    },
    {
      "name": "destructive/foreground",
      "alias": "destructive/foreground",
      "css": "--color-destructive-foreground"
    },
    {
      "name": "warning",
      "alias": "warning",
      "css": "--color-warning"
    },
    {
      "name": "warning/foreground",
      "alias": "warning/foreground",
      "css": "--color-warning-foreground"
    },
    {
      "name": "info",
      "alias": "info",
      "css": "--color-info"
    },
    {
      "name": "info/foreground",
      "alias": "info/foreground",
      "css": "--color-info-foreground"
    },
    {
      "name": "success",
      "alias": "success",
      "css": "--color-success"
    },
    {
      "name": "success/foreground",
      "alias": "success/foreground",
      "css": "--color-success-foreground"
    },
    {
      "name": "border",
      "alias": "border",
      "css": "--color-border"
    },
    {
      "name": "border-strong",
      "alias": "border-strong",
      "css": "--color-border-strong"
    },
    {
      "name": "hairline",
      "alias": "hairline",
      "css": "--color-hairline"
    },
    {
      "name": "input",
      "alias": "input",
      "css": "--color-input"
    },
    {
      "name": "ring",
      "alias": "ring",
      "css": "--color-ring"
    },
    {
      "name": "chart/1",
      "alias": "chart/1",
      "css": "--color-chart-1"
    },
    {
      "name": "chart/2",
      "alias": "chart/2",
      "css": "--color-chart-2"
    },
    {
      "name": "chart/3",
      "alias": "chart/3",
      "css": "--color-chart-3"
    },
    {
      "name": "chart/4",
      "alias": "chart/4",
      "css": "--color-chart-4"
    },
    {
      "name": "chart/5",
      "alias": "chart/5",
      "css": "--color-chart-5"
    },
    {
      "name": "sidebar",
      "alias": "sidebar",
      "css": "--color-sidebar"
    },
    {
      "name": "sidebar/foreground",
      "alias": "sidebar/foreground",
      "css": "--color-sidebar-foreground"
    },
    {
      "name": "sidebar/primary",
      "alias": "sidebar/primary",
      "css": "--color-sidebar-primary"
    },
    {
      "name": "sidebar/primary-foreground",
      "alias": "sidebar/primary-foreground",
      "css": "--color-sidebar-primary-foreground"
    },
    {
      "name": "sidebar/accent",
      "alias": "sidebar/accent",
      "css": "--color-sidebar-accent"
    },
    {
      "name": "sidebar/accent-foreground",
      "alias": "sidebar/accent-foreground",
      "css": "--color-sidebar-accent-foreground"
    },
    {
      "name": "sidebar/border",
      "alias": "sidebar/border",
      "css": "--color-sidebar-border"
    },
    {
      "name": "sidebar/ring",
      "alias": "sidebar/ring",
      "css": "--color-sidebar-ring"
    }
  ],
  "tones": [
    {
      "name": "tone/sage",
      "alias": "sage"
    },
    {
      "name": "tone/primary",
      "alias": "primary"
    },
    {
      "name": "tone/warning",
      "alias": "warning"
    },
    {
      "name": "tone/muted",
      "alias": "foreground"
    },
    {
      "name": "tone/destructive",
      "alias": "destructive"
    },
    {
      "name": "tone/info",
      "alias": "info"
    }
  ],
  "metalAliases": [
    {
      "name": "metal/bronze",
      "alias": "metal/bronze"
    },
    {
      "name": "metal/expanded-bronze",
      "alias": "metal/expanded-bronze"
    },
    {
      "name": "metal/silver",
      "alias": "metal/silver"
    },
    {
      "name": "metal/gold",
      "alias": "metal/gold"
    },
    {
      "name": "metal/platinum",
      "alias": "metal/platinum"
    },
    {
      "name": "metal/catastrophic",
      "alias": "metal/catastrophic"
    },
    {
      "name": "metal/bronze-fg",
      "alias": "metal/bronze-fg"
    },
    {
      "name": "metal/expanded-bronze-fg",
      "alias": "metal/expanded-bronze-fg"
    },
    {
      "name": "metal/silver-fg",
      "alias": "metal/silver-fg"
    },
    {
      "name": "metal/gold-fg",
      "alias": "metal/gold-fg"
    },
    {
      "name": "metal/platinum-fg",
      "alias": "metal/platinum-fg"
    },
    {
      "name": "metal/catastrophic-fg",
      "alias": "metal/catastrophic-fg"
    }
  ],
  "spacing": {
    "surface/none": 0,
    "surface/sm": 16,
    "surface/md": 20,
    "surface/lg": 24
  },
  "radius": {
    "sm": 6,
    "md": 10,
    "lg": 14,
    "xl": 18,
    "2xl": 22,
    "3xl": 28,
    "4xl": 36,
    "base": 14,
    "full": 9999
  },
  "border": {
    "hairline": 1,
    "ring": 2
  },
  "shadows": {
    "card": [],
    "elevated": [],
    "drawer": [],
    "plate": [],
    "glow": []
  },
  "layout": {
    "container/wide": 1408,
    "container/shell": 1500
  },
  "control": {
    "height/md": 40,
    "height/lg": 44,
    "padding-x": 12,
    "min-touch-target": 44
  }
};
