// GENERATED by tools/figma-plugin/extract-b2.mjs from src/styles.css — do not edit.
const ABOX_B2 = {
  "meta": {
    "generated": "tools/figma-plugin/extract-b2.mjs",
    "source": "src/styles.css",
    "note": "Production-derived. Light and Dark values are intentionally identical: production declares no .dark typography override."
  },
  "collection": {
    "name": "ABox/Typography",
    "modes": [
      "Light",
      "Dark"
    ]
  },
  "families": [
    {
      "name": "family/sans",
      "token": "--font-sans",
      "value": "\"Inter Tight\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", sans-serif",
      "source": "src/styles.css:27 — --font-sans: \"Inter Tight\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", sans-serif"
    },
    {
      "name": "family/display",
      "token": "--font-display",
      "value": "\"Bricolage Grotesque\", \"Inter Tight\", ui-sans-serif, system-ui, sans-serif",
      "source": "src/styles.css:28 — --font-display: \"Bricolage Grotesque\", \"Inter Tight\", ui-sans-serif, system-ui, sans-serif"
    },
    {
      "name": "family/serif",
      "token": "--font-serif",
      "value": "\"Bricolage Grotesque\", \"Inter Tight\", ui-sans-serif, system-ui, sans-serif",
      "source": "src/styles.css:29 — --font-serif: \"Bricolage Grotesque\", \"Inter Tight\", ui-sans-serif, system-ui, sans-serif"
    },
    {
      "name": "family/mono",
      "token": "--font-mono",
      "value": "\"Inter Tight\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", sans-serif",
      "source": "src/styles.css:30 — --font-mono: \"Inter Tight\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", sans-serif"
    }
  ],
  "roleFamilies": [
    {
      "name": "role/base/family",
      "alias": "family/sans",
      "source": "src/styles.css:244 — font-family: var(--font-sans)",
      "role": "base"
    },
    {
      "name": "role/heading/family",
      "alias": "family/display",
      "source": "src/styles.css:258 — font-family: var(--font-display)",
      "role": "heading"
    },
    {
      "name": "role/display/family",
      "alias": "family/display",
      "source": "src/styles.css:283 — font-family: var(--font-display)",
      "role": "display"
    },
    {
      "name": "role/eyebrow/family",
      "alias": "family/mono",
      "source": "src/styles.css:291 — font-family: var(--font-mono)",
      "role": "eyebrow"
    },
    {
      "name": "role/serial/family",
      "alias": "family/mono",
      "source": "src/styles.css:300 — font-family: var(--font-mono)",
      "role": "serial"
    }
  ],
  "floats": [
    {
      "name": "role/heading/weight",
      "value": 600,
      "source": "src/styles.css:259 — font-weight: 600"
    },
    {
      "name": "role/heading/letter-spacing",
      "value": -2.8,
      "source": "src/styles.css:260 — letter-spacing: -0.028em (em converted to Figma percentage)"
    },
    {
      "name": "role/display/weight",
      "value": 600,
      "source": "src/styles.css:284 — font-weight: 600"
    },
    {
      "name": "role/display/letter-spacing",
      "value": -3.2,
      "source": "src/styles.css:285 — letter-spacing: -0.032em (em converted to Figma percentage)"
    },
    {
      "name": "role/display/line-height",
      "value": 1.02,
      "source": "src/styles.css:286 — line-height: 1.02"
    },
    {
      "name": "role/eyebrow/size",
      "value": 11,
      "source": "src/styles.css:292 — font-size: 0.6875rem (rem converted to px at the 16px root)"
    },
    {
      "name": "role/eyebrow/weight",
      "value": 500,
      "source": "src/styles.css:293 — font-weight: 500"
    },
    {
      "name": "role/eyebrow/letter-spacing",
      "value": 0,
      "source": "src/styles.css:294 — letter-spacing: 0 (em converted to Figma percentage)"
    },
    {
      "name": "role/serial/size",
      "value": 10,
      "source": "src/styles.css:301 — font-size: 0.625rem (rem converted to px at the 16px root)"
    },
    {
      "name": "role/serial/letter-spacing",
      "value": 0,
      "source": "src/styles.css:302 — letter-spacing: 0 (em converted to Figma percentage)"
    }
  ],
  "limitations": [
    "h1, h2, h3, .font-display: font-variation-settings: \"wdth\" 102, \"opsz\" 32 (src/styles.css:261) — Figma exposes variable-font axes per text node, not as variables; recorded, no variable created.",
    "@utility text-display: font-variation-settings: \"wdth\" 102, \"opsz\" 48 (src/styles.css:287) — Figma exposes variable-font axes per text node, not as variables; recorded, no variable created.",
    "body: font-feature-settings: \"ss01\", \"cv11\" (src/styles.css:254) — OpenType feature settings have no Figma variable type; recorded, no variable created.",
    "@utility text-serial: font-variant-numeric: tabular-nums (src/styles.css:305) — OpenType numeric feature; no Figma variable type; recorded, no variable created.",
    "@utility text-eyebrow: text-transform: uppercase (src/styles.css:295) — text-node property, not variable-bindable; recorded.",
    "@utility text-serial: text-transform: uppercase (src/styles.css:303) — text-node property, not variable-bindable; recorded.",
    "eyebrow/serial color: var(--muted-foreground) is already a B1 semantic variable; not duplicated into ABox/Typography.",
    "Font-family values are CSS fallback stacks. Figma has no fallback concept: the full stack is stored as the STRING value and only the first family renders when bound.",
    "JetBrains Mono is loaded in src/routes/__root.tsx but referenced by no production token (--font-mono resolves to Inter Tight); no variable created.",
    "Tailwind's built-in size/leading/tracking utilities are library-owned defaults, not ABox tokens; not imported.",
    "No Text Styles in B2: text styles, effect styles, components, component sets, variants and page content are out of scope for this batch."
  ]
};
