// GENERATED by tools/figma-plugin/extract-b4.mjs — do not edit by hand.
const ABOX_B4 = {
  "meta": {
    "batch": "B4",
    "source": "src/components/abox/action-pill.ts, src/components/abox/action-pill-component.tsx, src/components/abox/status-badge.tsx, src/components/abox/metal-badge.tsx, src/components/ui/button.tsx, src/components/ui/input.tsx, src/components/abox/surface.tsx, src/components/abox/control.tsx, src/components/abox/field.tsx, src/components/abox/kpi-card.tsx, src/components/abox/page-header.tsx, src/components/abox/empty-state.tsx, src/components/abox/module-tabs.tsx, src/components/abox/downline-wizard-stepper.tsx, src/components/abox/logo.tsx",
    "generated": "tools/figma-plugin/extract-b4.mjs"
  },
  "counts": {
    "sets": 11,
    "components": 3,
    "objects": 14,
    "fixedVariants": 38,
    "enumeratedVariants": 14,
    "totalVariants": 52
  },
  "sets": [
    {
      "name": "ABox/Action/ActionPill",
      "property": "variant",
      "source": "source: src/components/abox/action-pill.ts:15",
      "textProps": [
        {
          "name": "label",
          "default": "Action"
        }
      ],
      "values": [
        {
          "value": "primaryXs",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.primaryXs = \"inline-flex h-8 items-center gap-1 rounded-full bg-primary px-3 text-xs font-medium text-primary-foreground hover:bg-primary/90\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 32,
            "px": 12,
            "py": 0,
            "gap": 4,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/primary",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/primary-foreground"
              }
            ]
          }
        },
        {
          "value": "primaryMd",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.primaryMd = \"inline-flex h-10 items-center gap-1.5 rounded-full bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/90\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 40,
            "px": 16,
            "py": 0,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/primary",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/primary-foreground"
              }
            ]
          }
        },
        {
          "value": "primaryLg",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.primaryLg = \"inline-flex h-11 items-center gap-1.5 rounded-full bg-primary px-6 text-sm font-medium text-primary-foreground hover:bg-primary/90\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 44,
            "px": 24,
            "py": 0,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/primary",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/primary-foreground"
              }
            ]
          }
        },
        {
          "value": "outlineXs",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.outlineXs = \"inline-flex h-8 items-center gap-1 rounded-full border border-border px-3 text-xs font-medium hover:bg-accent\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 32,
            "px": 12,
            "py": 0,
            "gap": 4,
            "radius": 9999,
            "fillStyle": null,
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "outlineSm",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.outlineSm = \"inline-flex h-9 items-center gap-1.5 rounded-full border border-border px-3 text-sm font-medium hover:bg-accent\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 36,
            "px": 12,
            "py": 0,
            "gap": 6,
            "radius": 9999,
            "fillStyle": null,
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "outlineSmCard",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.outlineSmCard = \"inline-flex h-9 items-center gap-1.5 rounded-full border border-border bg-card px-3 text-sm font-medium hover:bg-accent\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 36,
            "px": 12,
            "py": 0,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "outlineMd",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.outlineMd = \"inline-flex h-10 items-center gap-1.5 rounded-full border border-border px-4 text-sm font-medium hover:bg-accent\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 40,
            "px": 16,
            "py": 0,
            "gap": 6,
            "radius": 9999,
            "fillStyle": null,
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "outlineLg",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.outlineLg = \"inline-flex h-11 items-center gap-1.5 rounded-full border border-border px-5 text-sm font-medium hover:bg-accent\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 44,
            "px": 20,
            "py": 0,
            "gap": 6,
            "radius": 9999,
            "fillStyle": null,
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "outlineMdPlain",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.outlineMdPlain = \"inline-flex h-10 items-center rounded-full border border-border px-4 text-sm hover:bg-accent\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 40,
            "px": 16,
            "py": 0,
            "gap": 0,
            "radius": 9999,
            "fillStyle": null,
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 14,
                "weight": 400,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "primaryLgPlain",
          "source": "source: src/components/abox/action-pill.ts ACTION_PILL.primaryLgPlain = \"inline-flex h-11 items-center rounded-full bg-primary px-5 text-sm font-medium text-primary-foreground\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "h": 44,
            "px": 20,
            "py": 0,
            "gap": 0,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/primary",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Action",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/primary-foreground"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Action/Button",
      "properties": [
        "variant",
        "size"
      ],
      "source": "source: src/components/ui/button.tsx:7",
      "defaults": {
        "variant": "default",
        "size": "default"
      },
      "textProps": [
        {
          "name": "label",
          "default": "Button"
        }
      ],
      "values": [
        {
          "value": "variant=default, size=default",
          "variant": "default",
          "size": "default",
          "source": "source: src/components/ui/button.tsx:7 (cva) — enumerated from production call sites: src/components/abox/planai-assistant.tsx:88, src/routes/app.employer.census.tsx:163, src/routes/app.employer.contribution.tsx:138, src/routes/app.employer.proposal.tsx:94, src/routes/app.employer.results.tsx:91, src/routes/app.index.tsx:67 (+2 more)",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "justify": "CENTER",
            "h": 36,
            "w": null,
            "px": 16,
            "py": 0,
            "gap": 8,
            "radius": 6,
            "fillStyle": "ABox/Semantic/primary",
            "strokeStyle": null,
            "strokeWeight": 0,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "Button",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/primary-foreground"
              }
            ]
          }
        },
        {
          "value": "variant=default, size=sm",
          "variant": "default",
          "size": "sm",
          "source": "source: src/components/ui/button.tsx:7 (cva) — enumerated from production call sites: src/components/abox/plan-card.tsx:116, src/routes/app.employer.census.tsx:155, src/routes/app.jet.exceptions.tsx:136",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "justify": "CENTER",
            "h": 32,
            "w": null,
            "px": 12,
            "py": 0,
            "gap": 8,
            "radius": 6,
            "fillStyle": "ABox/Semantic/primary",
            "strokeStyle": null,
            "strokeWeight": 0,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "Button",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/primary-foreground"
              }
            ]
          }
        },
        {
          "value": "variant=ghost, size=default",
          "variant": "ghost",
          "size": "default",
          "source": "source: src/components/ui/button.tsx:7 (cva) — enumerated from production call sites: src/routes/app.employer.proposal.tsx:106, src/routes/app.index.tsx:80, src/routes/app.index.tsx:163",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "justify": "CENTER",
            "h": 36,
            "w": null,
            "px": 16,
            "py": 0,
            "gap": 8,
            "radius": 6,
            "fillStyle": null,
            "strokeStyle": null,
            "strokeWeight": 0,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "Button",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "variant=ghost, size=icon",
          "variant": "ghost",
          "size": "icon",
          "source": "source: src/components/ui/button.tsx:7 (cva) — enumerated from production call sites: src/routes/app.employer.census.tsx:101",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "justify": "CENTER",
            "h": 36,
            "w": 36,
            "px": 0,
            "py": 0,
            "gap": 8,
            "radius": 6,
            "fillStyle": null,
            "strokeStyle": null,
            "strokeWeight": 0,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "＋",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "variant=ghost, size=icon-sm",
          "variant": "ghost",
          "size": "icon-sm",
          "source": "source: src/components/ui/button.tsx:7 (cva) — enumerated from production call sites: src/components/abox/planai-assistant.tsx:44, src/components/ai-elements/message.tsx:264, src/components/ai-elements/message.tsx:287",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "justify": "CENTER",
            "h": 32,
            "w": 32,
            "px": 0,
            "py": 0,
            "gap": 8,
            "radius": 6,
            "fillStyle": null,
            "strokeStyle": null,
            "strokeWeight": 0,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "＋",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "variant=ghost, size=sm",
          "variant": "ghost",
          "size": "sm",
          "source": "source: src/components/ui/button.tsx:7 (cva) — enumerated from production call sites: src/components/abox/plan-card.tsx:99, src/routes/app.jet.entitlements.tsx:83",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "justify": "CENTER",
            "h": 32,
            "w": null,
            "px": 12,
            "py": 0,
            "gap": 8,
            "radius": 6,
            "fillStyle": null,
            "strokeStyle": null,
            "strokeWeight": 0,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "Button",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "variant=outline, size=default",
          "variant": "outline",
          "size": "default",
          "source": "source: src/components/ui/button.tsx:7 (cva) — enumerated from production call sites: src/routes/app.employer.census.tsx:75, src/routes/app.employer.proposal.tsx:51, src/routes/app.employer.results.tsx:42, src/routes/app.index.tsx:64, src/routes/app.jet.products.tsx:138",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "justify": "CENTER",
            "h": 36,
            "w": null,
            "px": 16,
            "py": 0,
            "gap": 8,
            "radius": 6,
            "fillStyle": "ABox/Semantic/background",
            "strokeStyle": "ABox/Semantic/input",
            "strokeWeight": 1,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "Button",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "variant=outline, size=icon",
          "variant": "outline",
          "size": "icon",
          "source": "source: src/components/ui/button.tsx:7 (cva) — enumerated from production call sites: src/components/ai-elements/conversation.tsx:86, src/components/ai-elements/conversation.tsx:154",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "justify": "CENTER",
            "h": 36,
            "w": 36,
            "px": 0,
            "py": 0,
            "gap": 8,
            "radius": 6,
            "fillStyle": "ABox/Semantic/background",
            "strokeStyle": "ABox/Semantic/input",
            "strokeWeight": 1,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "＋",
                "fontSize": 14,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "variant=outline, size=sm",
          "variant": "outline",
          "size": "sm",
          "source": "source: src/components/ui/button.tsx:7 (cva) — enumerated from production call sites: src/components/abox/plan-card.tsx:106, src/components/abox/plan-card.tsx:111, src/components/m06/kit.tsx:337, src/routes/app.jet.products.tsx:79",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "justify": "CENTER",
            "h": 32,
            "w": null,
            "px": 12,
            "py": 0,
            "gap": 8,
            "radius": 6,
            "fillStyle": "ABox/Semantic/background",
            "strokeStyle": "ABox/Semantic/input",
            "strokeWeight": 1,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "Button",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Status/StatusBadge",
      "property": "tone",
      "source": "source: src/components/abox/status-badge.tsx:4",
      "textProps": [
        {
          "name": "label",
          "default": "Status"
        }
      ],
      "values": [
        {
          "value": "sage",
          "source": "source: src/components/abox/status-badge.tsx tones.sage = \"[--tone:var(--sage)]\" — pill colour/background/border are color-mix() at runtime; the tone variable is bound and the expression recorded verbatim.",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Status/sage",
            "strokeWeight": 1,
            "children": [
              {
                "type": "ELLIPSE",
                "w": 6,
                "h": 6,
                "fillStyle": "ABox/Status/sage"
              },
              {
                "type": "TEXT",
                "characters": "Status",
                "textStyle": null,
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Status/sage"
              }
            ]
          }
        },
        {
          "value": "primary",
          "source": "source: src/components/abox/status-badge.tsx tones.primary = \"[--tone:var(--primary)]\" — pill colour/background/border are color-mix() at runtime; the tone variable is bound and the expression recorded verbatim.",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Status/primary",
            "strokeWeight": 1,
            "children": [
              {
                "type": "ELLIPSE",
                "w": 6,
                "h": 6,
                "fillStyle": "ABox/Status/primary"
              },
              {
                "type": "TEXT",
                "characters": "Status",
                "textStyle": null,
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Status/primary"
              }
            ]
          }
        },
        {
          "value": "warning",
          "source": "source: src/components/abox/status-badge.tsx tones.warning = \"[--tone:var(--warning)]\" — pill colour/background/border are color-mix() at runtime; the tone variable is bound and the expression recorded verbatim.",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Status/warning",
            "strokeWeight": 1,
            "children": [
              {
                "type": "ELLIPSE",
                "w": 6,
                "h": 6,
                "fillStyle": "ABox/Status/warning"
              },
              {
                "type": "TEXT",
                "characters": "Status",
                "textStyle": null,
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Status/warning"
              }
            ]
          }
        },
        {
          "value": "muted",
          "source": "source: src/components/abox/status-badge.tsx tones.muted = \"[--tone:var(--foreground)]\" — pill colour/background/border are color-mix() at runtime; the tone variable is bound and the expression recorded verbatim.",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Status/muted",
            "strokeWeight": 1,
            "children": [
              {
                "type": "ELLIPSE",
                "w": 6,
                "h": 6,
                "fillStyle": "ABox/Status/muted"
              },
              {
                "type": "TEXT",
                "characters": "Status",
                "textStyle": null,
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Status/muted"
              }
            ]
          }
        },
        {
          "value": "destructive",
          "source": "source: src/components/abox/status-badge.tsx tones.destructive = \"[--tone:var(--destructive)]\" — pill colour/background/border are color-mix() at runtime; the tone variable is bound and the expression recorded verbatim.",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Status/destructive",
            "strokeWeight": 1,
            "children": [
              {
                "type": "ELLIPSE",
                "w": 6,
                "h": 6,
                "fillStyle": "ABox/Status/destructive"
              },
              {
                "type": "TEXT",
                "characters": "Status",
                "textStyle": null,
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Status/destructive"
              }
            ]
          }
        },
        {
          "value": "info",
          "source": "source: src/components/abox/status-badge.tsx tones.info = \"[--tone:var(--info)]\" — pill colour/background/border are color-mix() at runtime; the tone variable is bound and the expression recorded verbatim.",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Status/info",
            "strokeWeight": 1,
            "children": [
              {
                "type": "ELLIPSE",
                "w": 6,
                "h": 6,
                "fillStyle": "ABox/Status/info"
              },
              {
                "type": "TEXT",
                "characters": "Status",
                "textStyle": null,
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Status/info"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Status/MetalBadge",
      "property": "tier",
      "source": "source: src/components/abox/metal-badge.tsx:9",
      "textProps": [
        {
          "name": "label",
          "default": "Tier"
        }
      ],
      "values": [
        {
          "value": "Bronze",
          "source": "source: src/components/abox/metal-badge.tsx TIER_VAR[\"Bronze\"] = \"[--tone:var(--metal-bronze)] [--tone-fg:var(--metal-bronze-fg)]\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 0,
            "radius": 9999,
            "fillStyle": "ABox/Metal/bronze",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Bronze",
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Metal/bronze-fg"
              }
            ]
          }
        },
        {
          "value": "Expanded Bronze",
          "source": "source: src/components/abox/metal-badge.tsx TIER_VAR[\"Expanded Bronze\"] = \"[--tone:var(--metal-expanded-bronze)] [--tone-fg:var(--metal-expanded-bronze-fg)]\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 0,
            "radius": 9999,
            "fillStyle": "ABox/Metal/expanded-bronze",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Expanded Bronze",
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Metal/expanded-bronze-fg"
              }
            ]
          }
        },
        {
          "value": "Silver",
          "source": "source: src/components/abox/metal-badge.tsx TIER_VAR[\"Silver\"] = \"[--tone:var(--metal-silver)] [--tone-fg:var(--metal-silver-fg)]\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 0,
            "radius": 9999,
            "fillStyle": "ABox/Metal/silver",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Silver",
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Metal/silver-fg"
              }
            ]
          }
        },
        {
          "value": "Gold",
          "source": "source: src/components/abox/metal-badge.tsx TIER_VAR[\"Gold\"] = \"[--tone:var(--metal-gold)] [--tone-fg:var(--metal-gold-fg)]\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 0,
            "radius": 9999,
            "fillStyle": "ABox/Metal/gold",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Gold",
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Metal/gold-fg"
              }
            ]
          }
        },
        {
          "value": "Platinum",
          "source": "source: src/components/abox/metal-badge.tsx TIER_VAR[\"Platinum\"] = \"[--tone:var(--metal-platinum)] [--tone-fg:var(--metal-platinum-fg)]\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 0,
            "radius": 9999,
            "fillStyle": "ABox/Metal/platinum",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Platinum",
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Metal/platinum-fg"
              }
            ]
          }
        },
        {
          "value": "Catastrophic",
          "source": "source: src/components/abox/metal-badge.tsx TIER_VAR[\"Catastrophic\"] = \"[--tone:var(--metal-catastrophic)] [--tone-fg:var(--metal-catastrophic-fg)]\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 2,
            "gap": 0,
            "radius": 9999,
            "fillStyle": "ABox/Metal/catastrophic",
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Catastrophic",
                "fontSize": 10,
                "weight": 600,
                "letterSpacingPercent": 12,
                "textCase": "UPPER",
                "colorStyle": "ABox/Metal/catastrophic-fg"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Surface/Surface",
      "properties": [
        "padding",
        "elevated",
        "interactiveHover",
        "decor"
      ],
      "source": "source: src/components/abox/surface.tsx:26",
      "defaults": {
        "padding": "md",
        "elevated": "false",
        "interactiveHover": "false",
        "decor": "false"
      },
      "values": [
        {
          "value": "padding=lg, elevated=false, interactiveHover=false, decor=false",
          "props": {
            "padding": "lg",
            "elevated": "false",
            "interactiveHover": "false",
            "decor": "false"
          },
          "source": "source: src/components/abox/surface.tsx SURFACE_BASE + SURFACE_PADDING.lg — enumerated from production call sites: src/routes/accessibility.tsx:57, src/routes/accessibility.tsx:73, src/routes/accessibility.tsx:83, src/routes/agency.downlines.new.activate.tsx:133, src/routes/agency.downlines.new.administrator.tsx:49, src/routes/agency.downlines.new.contacts.tsx:46 (+11 more)",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 320,
            "px": 24,
            "py": 24,
            "gap": 0,
            "radius": 16,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "Surface",
                "fontSize": 14,
                "weight": 400,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "padding=md, elevated=false, interactiveHover=false, decor=false",
          "props": {
            "padding": "md",
            "elevated": "false",
            "interactiveHover": "false",
            "decor": "false"
          },
          "source": "source: src/components/abox/surface.tsx SURFACE_BASE + SURFACE_PADDING.md — enumerated from production call sites: src/components/abox/surface.tsx:7, src/components/abox/surface.tsx:40, src/routes/accessibility.tsx:47, src/routes/agency.marketplace-participation.tsx:57, src/routes/agency.marketplace-participation.tsx:67, src/routes/agency.marketplace-participation.tsx:76 (+115 more)",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 320,
            "px": 20,
            "py": 20,
            "gap": 0,
            "radius": 16,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "Surface",
                "fontSize": 14,
                "weight": 400,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "padding=md, elevated=true, interactiveHover=false, decor=false",
          "props": {
            "padding": "md",
            "elevated": "true",
            "interactiveHover": "false",
            "decor": "false"
          },
          "source": "source: src/components/abox/surface.tsx SURFACE_BASE + SURFACE_PADDING.md — enumerated from production call sites: src/routes/coverage.tsx:51, src/routes/quote.tsx:499",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 320,
            "px": 20,
            "py": 20,
            "gap": 0,
            "radius": 16,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "effectStyle": "ABox/Elevation/card",
            "children": [
              {
                "type": "TEXT",
                "characters": "Surface",
                "fontSize": 14,
                "weight": 400,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        },
        {
          "value": "padding=sm, elevated=false, interactiveHover=false, decor=false",
          "props": {
            "padding": "sm",
            "elevated": "false",
            "interactiveHover": "false",
            "decor": "false"
          },
          "source": "source: src/components/abox/surface.tsx SURFACE_BASE + SURFACE_PADDING.sm — enumerated from production call sites: src/routes/agency.organization-work.tsx:56, src/routes/agent-unavailable.tsx:29, src/routes/agent-unavailable.tsx:30, src/routes/app.customers.index.tsx:84, src/routes/app.jet.integrations.tsx:28, src/routes/app.tasks.tsx:99 (+6 more)",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 320,
            "px": 16,
            "py": 16,
            "gap": 0,
            "radius": 16,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "effectStyle": null,
            "children": [
              {
                "type": "TEXT",
                "characters": "Surface",
                "fontSize": 14,
                "weight": 400,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Control/Control",
      "properties": [
        "height",
        "focusRing"
      ],
      "source": "source: src/components/abox/control.tsx:21",
      "defaults": {
        "height": "md",
        "focusRing": "false"
      },
      "values": [
        {
          "value": "height=lg, focusRing=true",
          "props": {
            "height": "lg",
            "focusRing": "true"
          },
          "source": "source: src/components/abox/control.tsx CONTROL_HEIGHT.lg + CONTROL_BASE + CONTROL_FOCUS_RING — enumerated from production call sites: src/routes/auth.tsx:195, src/routes/auth.tsx:209, src/routes/auth.tsx:241, src/routes/schedule.tsx:88, src/routes/schedule.tsx:93, src/routes/schedule.tsx:97",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "w": 280,
            "h": 44,
            "px": 12,
            "py": 0,
            "gap": 0,
            "radius": 8,
            "fillStyle": "ABox/Semantic/background",
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Value",
                "fontSize": 14,
                "weight": 400,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Card/KpiCard",
      "property": "tone",
      "source": "source: src/components/abox/kpi-card.tsx:26",
      "defaults": {
        "tone": "default"
      },
      "textProps": [
        {
          "name": "label",
          "default": "Metric"
        },
        {
          "name": "value",
          "default": "1,280"
        }
      ],
      "boolProps": [
        "icon",
        "delta",
        "hint"
      ],
      "values": [
        {
          "value": "default",
          "source": "source: src/components/abox/kpi-card.tsx TONE.default — text/tile tone token var(--primary)",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 320,
            "px": 24,
            "py": 24,
            "gap": 32,
            "radius": 16,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Semantic/hairline",
            "strokeWeight": 1,
            "effectStyle": "ABox/Elevation/card",
            "children": [
              {
                "type": "TEXT",
                "characters": "METRIC",
                "textStyle": "ABox/Text/eyebrow",
                "colorStyle": "ABox/Semantic/muted-foreground"
              },
              {
                "type": "TEXT",
                "characters": "1,280",
                "fontSize": 48,
                "weight": 600,
                "colorStyle": "ABox/Semantic/foreground"
              },
              {
                "type": "TEXT",
                "characters": "▲ 4.2%",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Status/primary"
              }
            ]
          }
        },
        {
          "value": "primary",
          "source": "source: src/components/abox/kpi-card.tsx TONE.primary — text/tile tone token var(--primary)",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 320,
            "px": 24,
            "py": 24,
            "gap": 32,
            "radius": 16,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Semantic/hairline",
            "strokeWeight": 1,
            "effectStyle": "ABox/Elevation/card",
            "children": [
              {
                "type": "TEXT",
                "characters": "METRIC",
                "textStyle": "ABox/Text/eyebrow",
                "colorStyle": "ABox/Semantic/muted-foreground"
              },
              {
                "type": "TEXT",
                "characters": "1,280",
                "fontSize": 48,
                "weight": 600,
                "colorStyle": "ABox/Semantic/foreground"
              },
              {
                "type": "TEXT",
                "characters": "▲ 4.2%",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Status/primary"
              }
            ]
          }
        },
        {
          "value": "sage",
          "source": "source: src/components/abox/kpi-card.tsx TONE.sage — text/tile tone token var(--sage)",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 320,
            "px": 24,
            "py": 24,
            "gap": 32,
            "radius": 16,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Semantic/hairline",
            "strokeWeight": 1,
            "effectStyle": "ABox/Elevation/card",
            "children": [
              {
                "type": "TEXT",
                "characters": "METRIC",
                "textStyle": "ABox/Text/eyebrow",
                "colorStyle": "ABox/Semantic/muted-foreground"
              },
              {
                "type": "TEXT",
                "characters": "1,280",
                "fontSize": 48,
                "weight": 600,
                "colorStyle": "ABox/Semantic/foreground"
              },
              {
                "type": "TEXT",
                "characters": "▲ 4.2%",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Status/sage"
              }
            ]
          }
        },
        {
          "value": "warning",
          "source": "source: src/components/abox/kpi-card.tsx TONE.warning — text/tile tone token var(--warning)",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 320,
            "px": 24,
            "py": 24,
            "gap": 32,
            "radius": 16,
            "fillStyle": "ABox/Semantic/card",
            "strokeStyle": "ABox/Semantic/hairline",
            "strokeWeight": 1,
            "effectStyle": "ABox/Elevation/card",
            "children": [
              {
                "type": "TEXT",
                "characters": "METRIC",
                "textStyle": "ABox/Text/eyebrow",
                "colorStyle": "ABox/Semantic/muted-foreground"
              },
              {
                "type": "TEXT",
                "characters": "1,280",
                "fontSize": 48,
                "weight": 600,
                "colorStyle": "ABox/Semantic/foreground"
              },
              {
                "type": "TEXT",
                "characters": "▲ 4.2%",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Status/warning"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Header/PageHeader",
      "property": "variant",
      "source": "source: src/components/abox/page-header.tsx:23",
      "defaults": {
        "variant": "default"
      },
      "textProps": [
        {
          "name": "title",
          "default": "Page title"
        },
        {
          "name": "eyebrow",
          "default": "SECTION"
        },
        {
          "name": "description",
          "default": "Supporting description."
        }
      ],
      "boolProps": [
        "eyebrow",
        "description",
        "icon",
        "actions"
      ],
      "values": [
        {
          "value": "default",
          "source": "source: src/components/abox/page-header.tsx variant default — eyebrow + text-display 30px title + 18px description + hairline rule",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 640,
            "px": 0,
            "py": 0,
            "gap": 12,
            "radius": 0,
            "fillStyle": null,
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "SECTION",
                "textStyle": "ABox/Text/eyebrow",
                "colorStyle": "ABox/Semantic/muted-foreground"
              },
              {
                "type": "TEXT",
                "characters": "Page title",
                "fontSize": 30,
                "weight": 600,
                "colorStyle": "ABox/Semantic/foreground"
              },
              {
                "type": "TEXT",
                "characters": "Supporting description.",
                "fontSize": 18,
                "weight": 400,
                "colorStyle": "ABox/Semantic/muted-foreground"
              }
            ]
          }
        },
        {
          "value": "compact",
          "source": "source: src/components/abox/page-header.tsx variant compact — no eyebrow, 20px semibold title, 12px description, no rule",
          "node": {
            "type": "FRAME",
            "layout": "VERTICAL",
            "w": 640,
            "px": 0,
            "py": 0,
            "gap": 8,
            "radius": 0,
            "fillStyle": null,
            "strokeStyle": null,
            "strokeWeight": 0,
            "children": [
              {
                "type": "TEXT",
                "characters": "Page title",
                "fontSize": 20,
                "weight": 600,
                "colorStyle": "ABox/Semantic/foreground"
              },
              {
                "type": "TEXT",
                "characters": "Supporting description.",
                "fontSize": 12,
                "weight": 400,
                "colorStyle": "ABox/Semantic/muted-foreground"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Nav/ModuleTab",
      "property": "state",
      "source": "source: src/components/abox/module-tabs.tsx:26",
      "defaults": {
        "state": "default"
      },
      "textProps": [
        {
          "name": "label",
          "default": "Section"
        }
      ],
      "values": [
        {
          "value": "default",
          "source": "source: src/components/abox/module-tabs.tsx className=\"rounded-full border border-hairline px-3 py-1.5 text-xs font-medium text-muted-foreground\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 12,
            "py": 6,
            "gap": 0,
            "radius": 9999,
            "fillStyle": null,
            "strokeStyle": "ABox/Semantic/hairline",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Section",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/muted-foreground"
              }
            ]
          }
        },
        {
          "value": "active",
          "source": "source: src/components/abox/module-tabs.tsx activeProps className=\"bg-primary/10 text-foreground border-primary/30\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 12,
            "py": 6,
            "gap": 0,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/primary",
            "fillOpacity": 0.1,
            "strokeStyle": "ABox/Semantic/primary",
            "strokeOpacity": 0.3,
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Section",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/foreground"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Nav/WizardStep",
      "property": "state",
      "source": "source: src/components/abox/downline-wizard-stepper.tsx:37",
      "textProps": [
        {
          "name": "label",
          "default": "Identity"
        }
      ],
      "values": [
        {
          "value": "current",
          "source": "source: src/components/abox/downline-wizard-stepper.tsx isCurrent → \"border-primary bg-primary text-primary-foreground\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 6,
            "gap": 6,
            "radius": 9999,
            "fillStyle": "ABox/Semantic/primary",
            "strokeStyle": "ABox/Semantic/primary",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Identity",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/primary-foreground"
              }
            ]
          }
        },
        {
          "value": "done",
          "source": "source: src/components/abox/downline-wizard-stepper.tsx isDone → reachable link with Check glyph, \"border-border text-muted-foreground\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 6,
            "gap": 6,
            "radius": 9999,
            "fillStyle": null,
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Identity",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/muted-foreground"
              }
            ]
          }
        },
        {
          "value": "upcoming",
          "source": "source: src/components/abox/downline-wizard-stepper.tsx reachable, not current, not done → \"border-border text-muted-foreground\"",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 6,
            "gap": 6,
            "radius": 9999,
            "fillStyle": null,
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Identity",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/muted-foreground"
              }
            ]
          }
        },
        {
          "value": "unreachable",
          "source": "source: src/components/abox/downline-wizard-stepper.tsx not reachable → rendered as a non-link span with the same pill geometry",
          "node": {
            "type": "FRAME",
            "layout": "HORIZONTAL",
            "align": "CENTER",
            "px": 10,
            "py": 6,
            "gap": 6,
            "radius": 9999,
            "fillStyle": null,
            "strokeStyle": "ABox/Semantic/border",
            "strokeWeight": 1,
            "children": [
              {
                "type": "TEXT",
                "characters": "Identity",
                "fontSize": 12,
                "weight": 500,
                "colorStyle": "ABox/Semantic/muted-foreground"
              }
            ]
          }
        }
      ]
    },
    {
      "name": "ABox/Brand/AboxMark",
      "property": "tone",
      "source": "source: src/components/abox/logo.tsx:15",
      "defaults": {
        "tone": "primary"
      },
      "values": [
        {
          "value": "primary",
          "source": "source: src/components/abox/logo.tsx TONES.primary = { bg: var(--surface), ring: var(--primary), fg: var(--foreground), dot: var(--primary) } — call sites: src/components/abox/marketplace-shell.tsx:60, src/components/abox/member-shell.tsx:71, src/components/abox/internal-shell.tsx:167, src/routes/index.tsx:122, src/routes/quote.tsx:501, src/components/abox/placeholder-screen.tsx:43",
          "node": {
            "type": "MARK",
            "size": 36,
            "bgStyle": "ABox/Semantic/surface",
            "ringStyle": "ABox/Semantic/primary",
            "fgStyle": "ABox/Semantic/foreground",
            "dotStyle": "ABox/Semantic/primary",
            "hairlineStyle": "ABox/Semantic/hairline"
          }
        },
        {
          "value": "sage",
          "source": "source: src/components/abox/logo.tsx TONES.sage = { bg: var(--surface), ring: var(--sage), fg: var(--foreground), dot: var(--sage) } — call sites: src/components/abox/plan-o-assistant.tsx:47",
          "node": {
            "type": "MARK",
            "size": 36,
            "bgStyle": "ABox/Semantic/surface",
            "ringStyle": "ABox/Semantic/sage",
            "fgStyle": "ABox/Semantic/foreground",
            "dotStyle": "ABox/Semantic/sage",
            "hairlineStyle": "ABox/Semantic/hairline"
          }
        },
        {
          "value": "sidebar",
          "source": "source: src/components/abox/logo.tsx TONES.sidebar = { bg: var(--sidebar-accent), ring: var(--sidebar-primary), fg: var(--sidebar-foreground), dot: var(--sidebar-primary) } — call sites: src/components/abox/internal-shell.tsx:80, src/components/abox/marketplace-shell.tsx:154",
          "node": {
            "type": "MARK",
            "size": 36,
            "bgStyle": "ABox/Semantic/sidebar/accent",
            "ringStyle": "ABox/Semantic/sidebar/primary",
            "fgStyle": "ABox/Semantic/sidebar/foreground",
            "dotStyle": "ABox/Semantic/sidebar/primary",
            "hairlineStyle": "ABox/Semantic/hairline"
          }
        },
        {
          "value": "foreground",
          "source": "source: src/components/abox/logo.tsx TONES.foreground = { bg: var(--foreground), ring: var(--primary), fg: var(--background), dot: var(--primary) } — call sites: declared in the production TONES record with no non-reference call site (only src/routes/design-system.tsx and src/routes/design-guide.tsx, which are reference layers); included because the production component API defines it as a first-class branch — recorded, not dropped.",
          "node": {
            "type": "MARK",
            "size": 36,
            "bgStyle": "ABox/Semantic/foreground",
            "ringStyle": "ABox/Semantic/primary",
            "fgStyle": "ABox/Semantic/background",
            "dotStyle": "ABox/Semantic/primary",
            "hairlineStyle": "ABox/Semantic/hairline"
          }
        }
      ]
    }
  ],
  "components": [
    {
      "name": "ABox/Feedback/EmptyState",
      "source": "source: src/components/abox/empty-state.tsx:12",
      "textProps": [
        {
          "name": "title",
          "default": "Nothing here yet"
        },
        {
          "name": "body",
          "default": "Supporting copy."
        }
      ],
      "boolProps": [
        "icon",
        "body"
      ],
      "instanceProps": [
        "action"
      ],
      "node": {
        "type": "FRAME",
        "layout": "VERTICAL",
        "align": "CENTER",
        "w": 480,
        "px": 24,
        "py": 56,
        "gap": 16,
        "radius": 8,
        "fillStyle": "ABox/Semantic/surface",
        "fillOpacity": 0.6,
        "strokeStyle": "ABox/Semantic/border-strong",
        "strokeWeight": 1,
        "dashed": true,
        "children": [
          {
            "type": "TEXT",
            "characters": "Nothing here yet",
            "fontSize": 24,
            "weight": 600,
            "colorStyle": "ABox/Semantic/foreground"
          },
          {
            "type": "TEXT",
            "characters": "Supporting copy.",
            "fontSize": 14,
            "weight": 400,
            "colorStyle": "ABox/Semantic/muted-foreground"
          }
        ]
      }
    },
    {
      "name": "ABox/Form/LabeledField",
      "source": "source: src/components/abox/field.tsx:16",
      "textProps": [
        {
          "name": "label",
          "default": "Label"
        }
      ],
      "exposedInstances": [
        "ABox/Control/Control"
      ],
      "node": {
        "type": "FRAME",
        "layout": "VERTICAL",
        "w": 280,
        "px": 0,
        "py": 0,
        "gap": 4,
        "radius": 0,
        "fillStyle": null,
        "strokeStyle": null,
        "strokeWeight": 0,
        "children": [
          {
            "type": "TEXT",
            "characters": "LABEL",
            "textStyle": "ABox/Text/eyebrow",
            "colorStyle": "ABox/Semantic/muted-foreground"
          },
          {
            "type": "INSTANCE",
            "of": "ABox/Control/Control"
          }
        ]
      }
    },
    {
      "name": "ABox/Form/Input",
      "source": "source: src/components/ui/input.tsx:5",
      "textProps": [
        {
          "name": "placeholder",
          "default": "Placeholder"
        }
      ],
      "node": {
        "type": "FRAME",
        "layout": "HORIZONTAL",
        "align": "CENTER",
        "w": 280,
        "h": 36,
        "px": 12,
        "py": 4,
        "gap": 0,
        "radius": 6,
        "fillStyle": null,
        "strokeStyle": "ABox/Semantic/input",
        "strokeWeight": 1,
        "children": [
          {
            "type": "TEXT",
            "characters": "Placeholder",
            "fontSize": 14,
            "weight": 400,
            "colorStyle": "ABox/Semantic/muted-foreground"
          }
        ]
      }
    }
  ],
  "excluded": [
    {
      "source": "src/components/ui/{accordion,alert-dialog,aspect-ratio,avatar,breadcrumb,calendar,carousel,chart,collapsible,context-menu,form,input-otp,menubar,navigation-menu,pagination,resizable,scroll-area,sidebar,table,toggle,toggle-group}.tsx",
      "reason": "Zero production importers — file exists, no consumer."
    },
    {
      "source": "src/components/ui/{alert,checkbox,switch,drawer}.tsx",
      "reason": "Only imported by src/routes/design-system.tsx, a reference layer."
    },
    {
      "source": "src/components/ui/{spinner,command,hover-card,input-group,button-group}.tsx",
      "reason": "Only imported by src/components/ai-elements/*."
    },
    {
      "source": "src/components/ui/{dialog,sheet,popover,tooltip,dropdown-menu,tabs}.tsx",
      "reason": "Behavioural overlay/navigation primitives — interaction patterns, deferred to B6."
    },
    {
      "source": "src/components/ui/{badge,card,skeleton,textarea,select,label}.tsx",
      "reason": "Real importers, but consumed beneath ABox components or as raw defaults; not created to avoid a second source of truth beside Surface/Control/StatusBadge."
    },
    {
      "source": "src/components/abox/{plan-card,data-table,marketplace-page-layout,notice-page,downline-context-banner,shopping-path-bar,product-switcher,quote-edit-panel,suspended-marketplace-notice}.tsx",
      "reason": "Composite screens/surfaces — deferred to B6/B8."
    },
    {
      "source": "src/components/abox/{internal-shell,marketplace-shell,member-shell}.tsx",
      "reason": "Shells — B7."
    },
    {
      "source": "src/components/abox/{planai-assistant,plan-o-assistant}.tsx",
      "reason": "Zero importers — documented gap, not a component foundation candidate."
    },
    {
      "source": "src/components/abox/carrier-mark.tsx",
      "reason": "Monogram and hue are computed at runtime from the carrier name — no finite variant set exists."
    }
  ],
  "limitations": [
    "src/components/abox/status-badge.tsx:21-23 — color: color-mix(in oklch, var(--tone) 88%, var(--foreground)); background: color-mix(in oklch, var(--tone) 12%, var(--card)); borderColor: color-mix(in oklch, var(--tone) 34%, transparent): runtime-computed, no Figma equivalent. The tone Colour Style is bound and the expression is recorded verbatim; no substitute value is fabricated.",
    "src/styles.css — oklch() has no Figma equivalent: colours reach components through the B3 styles, which already record the original oklch literal.",
    "Tailwind numeric utilities (h-*, px-*, gap-*, rounded-*, text-*) are literal values in Figma: production does not declare them through the B1 spacing/radius/control-sizing variables, so they are NOT bound to those variables. The class string is recorded on every component/variant instead.",
    "Hover, group-hover, focus-visible, active and transition rules (src/components/ui/button.tsx, src/components/abox/action-pill.ts, src/components/abox/surface.tsx SURFACE_INTERACTIVE_HOVER, src/components/abox/control.tsx CONTROL_FOCUS_RING) are interaction states, not Figma variants; no Hover/Focus/Pressed variant is invented.",
    "src/components/abox/kpi-card.tsx — CountUp animation and group-hover icon-tile rotation/scale: motion, not representable.",
    "src/components/abox/page-header.tsx — FadeRise entrance and animate-hairline rule: motion, not representable.",
    "Decorative utilities card-brackets, edge-sheen, glass (kpi-card.tsx), DiagonalWeave (empty-state.tsx): no exact Figma representation; recorded, not approximated.",
    "Responsive md:/xl: rules inside page-header.tsx, kpi-card.tsx and plan-card.tsx are layout composition, not component variants; deferred to a later composition batch.",
    "src/components/abox/logo.tsx — size is a free numeric prop with no finite production set: the AboxMark set is built at the production default size = 36 and resizing stays an instance concern.",
    "src/components/abox/carrier-mark.tsx — deterministic hash-derived hue and initials: no finite variant set; excluded, not approximated.",
    "src/components/ui/button.tsx — shadow/shadow-sm utilities on the default/destructive/outline/secondary variants are Tailwind defaults, not production --shadow-* families; no Effect Style is attached rather than binding an unrelated elevation style.",
    "No B0 page is populated: components are created off-page and no page content is added in B4.",
    "src/components/ai-elements/message.tsx:94 — <Button> receives a computed variant/size expression; not statically enumerable, recorded, no variant invented.",
    "src/components/m06/kit.tsx:84 — <Button> receives a computed variant/size expression; not statically enumerable, recorded, no variant invented.",
    "src/routes/app.jet.launch-readiness.tsx:87 — <Button> receives a computed variant/size expression; not statically enumerable, recorded, no variant invented.",
    "src/routes/plans.$planId.tsx:200 — <Surface> JSX call site recorded; padding/boolean props read as written."
  ]
};
