// GENERATED by tools/figma-plugin/extract-b6.mjs — do not hand-edit.
var ABOX_B6 = {
  "meta": {
    "batch": "Phase 53 / Batch B6 — patterns & interactions",
    "page": "02 Patterns",
    "generatedBy": "tools/figma-plugin/extract-b6.mjs",
    "protects": [
      "B1",
      "B2",
      "B3",
      "B4",
      "B5"
    ]
  },
  "counts": {
    "patterns": 3,
    "sets": 1,
    "components": 2,
    "patternNodes": 4,
    "prototypes": 0,
    "deferred": 9,
    "rejected": 3,
    "b4Sets": 11,
    "b4Standalone": 3,
    "b5Variants": 56,
    "b5Physical": 59,
    "b5NonVariant": 19,
    "b5Exposed": 1
  },
  "patterns": [
    {
      "name": "ABox/Pattern/KpiRow",
      "kind": "SET",
      "property": "columns",
      "source": "source: src/routes/app.dashboard.tsx:31 and src/routes/app.agency.statements.tsx:29 — repeated in 15 non-reference routes",
      "evidence": [
        "src/routes/app.dashboard.tsx",
        "src/routes/app.agency.index.tsx",
        "src/routes/app.my-work.tsx",
        "src/routes/app.commissions.tsx",
        "src/routes/agency.my-organization.tsx",
        "src/routes/agency.organization-admin.tsx",
        "src/routes/marketplace.admin.index.tsx",
        "src/routes/member.index.tsx",
        "src/routes/platform.organizations.index.tsx",
        "src/routes/platform.marketplaces.index.tsx",
        "src/routes/app.partner.tsx",
        "src/routes/app.employer.ichra.tsx",
        "src/routes/app.agency.statements.tsx",
        "src/routes/app.jet.platform.tsx",
        "src/routes/app.index.tsx"
      ],
      "values": [
        "3",
        "4"
      ],
      "variants": [
        {
          "value": "4",
          "root": {
            "layout": "HORIZONTAL",
            "wrap": "NO_WRAP",
            "gap": 16,
            "counterGap": 0,
            "primarySizing": "AUTO",
            "counterSizing": "AUTO"
          },
          "children": [
            {
              "of": "ABox/Card/KpiCard",
              "variants": {
                "tone": "default",
                "deltaSign": "positive"
              },
              "texts": {
                "label": "Visits (30d)",
                "value": "2,140"
              },
              "source": "src/routes/app.dashboard.tsx:32"
            },
            {
              "of": "ABox/Card/KpiCard",
              "variants": {
                "tone": "primary",
                "deltaSign": "positive"
              },
              "texts": {
                "label": "Quotes sent",
                "value": "214"
              },
              "source": "src/routes/app.dashboard.tsx:33"
            },
            {
              "of": "ABox/Card/KpiCard",
              "variants": {
                "tone": "sage",
                "deltaSign": "positive"
              },
              "texts": {
                "label": "Enrollments",
                "value": "92"
              },
              "source": "src/routes/app.dashboard.tsx:34"
            },
            {
              "of": "ABox/Card/KpiCard",
              "variants": {
                "tone": "primary",
                "deltaSign": "positive"
              },
              "texts": {
                "label": "Projected earnings",
                "value": "$15,200"
              },
              "source": "src/routes/app.dashboard.tsx:35"
            }
          ]
        },
        {
          "value": "3",
          "root": {
            "layout": "HORIZONTAL",
            "wrap": "NO_WRAP",
            "gap": 16,
            "counterGap": 0,
            "primarySizing": "AUTO",
            "counterSizing": "AUTO"
          },
          "children": [
            {
              "of": "ABox/Card/KpiCard",
              "variants": {
                "tone": "default",
                "deltaSign": "positive"
              },
              "texts": {
                "label": "Visits (30d)",
                "value": "2,140"
              },
              "source": "src/routes/app.dashboard.tsx:32"
            },
            {
              "of": "ABox/Card/KpiCard",
              "variants": {
                "tone": "primary",
                "deltaSign": "positive"
              },
              "texts": {
                "label": "Quotes sent",
                "value": "214"
              },
              "source": "src/routes/app.dashboard.tsx:33"
            },
            {
              "of": "ABox/Card/KpiCard",
              "variants": {
                "tone": "sage",
                "deltaSign": "positive"
              },
              "texts": {
                "label": "Enrollments",
                "value": "92"
              },
              "source": "src/routes/app.dashboard.tsx:34"
            }
          ]
        }
      ]
    },
    {
      "name": "ABox/Pattern/ModuleTabBar",
      "kind": "COMPONENT",
      "source": "source: src/components/abox/module-tabs.tsx:14 | hosts src/components/m06/workforce-page.tsx:46, src/components/lucie-app/frames.tsx:21",
      "root": {
        "layout": "HORIZONTAL",
        "wrap": "WRAP",
        "gap": 6,
        "counterGap": 6,
        "primarySizing": "AUTO",
        "counterSizing": "AUTO",
        "paddingBottom": 12,
        "strokeBottomStyle": "ABox/Semantic/hairline",
        "strokesIncludedInLayout": false,
        "strokeSource": "src/components/abox/module-tabs.tsx:18",
        "gapSource": "src/components/abox/module-tabs.tsx:18"
      },
      "children": [
        {
          "of": "ABox/Nav/ModuleTab",
          "variants": {
            "state": "active"
          },
          "texts": {
            "label": "Overview"
          },
          "source": "src/components/m06/workforce-page.tsx:18"
        },
        {
          "of": "ABox/Nav/ModuleTab",
          "variants": {
            "state": "default"
          },
          "texts": {
            "label": "Roster"
          },
          "source": "src/components/m06/workforce-page.tsx:19"
        },
        {
          "of": "ABox/Nav/ModuleTab",
          "variants": {
            "state": "default"
          },
          "texts": {
            "label": "Person"
          },
          "source": "src/components/m06/workforce-page.tsx:20"
        },
        {
          "of": "ABox/Nav/ModuleTab",
          "variants": {
            "state": "default"
          },
          "texts": {
            "label": "Onboarding"
          },
          "source": "src/components/m06/workforce-page.tsx:21"
        },
        {
          "of": "ABox/Nav/ModuleTab",
          "variants": {
            "state": "default"
          },
          "texts": {
            "label": "Structure"
          },
          "source": "src/components/m06/workforce-page.tsx:22"
        }
      ]
    },
    {
      "name": "ABox/Pattern/WizardStepper",
      "kind": "COMPONENT",
      "source": "source: src/components/abox/downline-wizard-stepper.tsx:18 | states src/components/abox/downline-wizard-stepper.tsx:37 | configuration: route /agency/downlines/new/contacts (SCR-M05-009, step 3 of 8)",
      "configuration": {
        "route": "/agency/downlines/new/contacts",
        "scr": "SCR-M05-009",
        "currentStep": 3,
        "steps": [
          {
            "n": 1,
            "label": "Identity",
            "state": "done"
          },
          {
            "n": 2,
            "label": "Legal & identifiers",
            "state": "done"
          },
          {
            "n": 3,
            "label": "Contacts",
            "state": "current"
          },
          {
            "n": 4,
            "label": "Addresses & offices",
            "state": "unreachable"
          },
          {
            "n": 5,
            "label": "Settings",
            "state": "unreachable"
          },
          {
            "n": 6,
            "label": "Initial administrator",
            "state": "unreachable"
          },
          {
            "n": 7,
            "label": "Readiness review",
            "state": "unreachable"
          },
          {
            "n": 8,
            "label": "Activation",
            "state": "unreachable"
          }
        ]
      },
      "root": {
        "layout": "HORIZONTAL",
        "wrap": "WRAP",
        "gap": 6,
        "counterGap": 6,
        "primarySizing": "AUTO",
        "counterSizing": "AUTO",
        "gapSource": "src/components/abox/downline-wizard-stepper.tsx:35"
      },
      "children": [
        {
          "of": "ABox/Nav/WizardStep",
          "variants": {
            "state": "done"
          },
          "texts": {
            "label": "Identity"
          },
          "source": "src/components/abox/downline-wizard-stepper.tsx:19"
        },
        {
          "of": "ABox/Nav/WizardStep",
          "variants": {
            "state": "done"
          },
          "texts": {
            "label": "Legal & identifiers"
          },
          "source": "src/components/abox/downline-wizard-stepper.tsx:20"
        },
        {
          "of": "ABox/Nav/WizardStep",
          "variants": {
            "state": "current"
          },
          "texts": {
            "label": "Contacts"
          },
          "source": "src/components/abox/downline-wizard-stepper.tsx:21"
        },
        {
          "of": "ABox/Nav/WizardStep",
          "variants": {
            "state": "unreachable"
          },
          "texts": {
            "label": "Addresses & offices"
          },
          "source": "src/components/abox/downline-wizard-stepper.tsx:22"
        },
        {
          "of": "ABox/Nav/WizardStep",
          "variants": {
            "state": "unreachable"
          },
          "texts": {
            "label": "Settings"
          },
          "source": "src/components/abox/downline-wizard-stepper.tsx:23"
        },
        {
          "of": "ABox/Nav/WizardStep",
          "variants": {
            "state": "unreachable"
          },
          "texts": {
            "label": "Initial administrator"
          },
          "source": "src/components/abox/downline-wizard-stepper.tsx:24"
        },
        {
          "of": "ABox/Nav/WizardStep",
          "variants": {
            "state": "unreachable"
          },
          "texts": {
            "label": "Readiness review"
          },
          "source": "src/components/abox/downline-wizard-stepper.tsx:25"
        },
        {
          "of": "ABox/Nav/WizardStep",
          "variants": {
            "state": "unreachable"
          },
          "texts": {
            "label": "Activation"
          },
          "source": "src/components/abox/downline-wizard-stepper.tsx:26"
        }
      ]
    }
  ],
  "interactions": [
    {
      "pattern": "ABox/Pattern/ModuleTabBar",
      "trigger": "route match (TanStack Link activeProps)",
      "source": "src/components/abox/module-tabs.tsx:26",
      "behaviour": "the matching tab gains bg-primary/10 text-foreground border-primary/30",
      "representation": "existing B4 variant ABox/Nav/ModuleTab state=active on child 1",
      "before": "state=default",
      "after": "state=active",
      "prototype": "none",
      "reuse": "existing B4 variant reused; no new state axis, no B4 mutation",
      "limitation": ""
    },
    {
      "pattern": "ABox/Pattern/WizardStepper",
      "trigger": "current route position within DOWNLINE_WIZARD_STEPS",
      "source": "src/components/abox/downline-wizard-stepper.tsx:37",
      "behaviour": "steps render as done (check glyph), current (filled) or unreachable (dimmed span); B4's upcoming branch is unreachable for any real route because isReachable = i <= currentIndex",
      "representation": "existing B4 variants ABox/Nav/WizardStep state=done|current|unreachable, copied from route /agency/downlines/new/contacts",
      "before": "state=unreachable",
      "after": "state=current / state=done",
      "prototype": "none",
      "reuse": "existing B4 variants reused; no new state axis, no B4 mutation",
      "limitation": "Step navigation is route navigation (Link to=…); the destination screens are B8 scope, so no prototype connection is created — one would imply navigation not supported by any existing Figma frame."
    }
  ],
  "deferredInteractions": [
    {
      "candidate": "ModuleTab hover (hover:bg-accent)",
      "source": "src/components/abox/module-tabs.tsx:27",
      "reason": "no B4 hover variant exists; adding one would add a state axis to a protected B4 set"
    },
    {
      "candidate": "DataTable row hover ember bar",
      "source": "src/components/abox/data-table.tsx:79",
      "reason": "DataTable was excluded from B4; no primitive exists to host the interaction"
    },
    {
      "candidate": "Control focus-visible ring",
      "source": "src/components/abox/control.tsx:23",
      "reason": "CSS pseudo-class, not a design-system state; no focus variant on the protected B4 Control"
    },
    {
      "candidate": "dialog / sheet / dropdown / tooltip open-close",
      "source": "src/components/ui/{dialog,sheet,dropdown-menu,tooltip}.tsx",
      "reason": "no B4 overlay primitives; composition differs per consumer"
    }
  ],
  "deferred": [
    {
      "candidate": "Page header + actions region",
      "source": "src/components/abox/page-header.tsx:55",
      "decision": "DEFER — insufficient representation",
      "reason": "B4 PageHeader has no actions wrapper layer; B5 deferred hasActions/actions"
    },
    {
      "candidate": "Empty state with action",
      "source": "src/components/abox/empty-state.tsx:24",
      "decision": "DEFER — insufficient representation",
      "reason": "B4 EmptyState has no action region; B5 deferred hasAction/action"
    },
    {
      "candidate": "Data table + empty row",
      "source": "src/components/abox/data-table.tsx:50",
      "decision": "DEFER — insufficient representation",
      "reason": "DataTable excluded from B4; no table primitive exists"
    },
    {
      "candidate": "Shell + header + content",
      "source": "src/components/abox/{internal,marketplace,member}-shell.tsx",
      "decision": "DEFER — later shell/screen phase (B7)",
      "reason": "shell composition belongs to 03 Shells"
    },
    {
      "candidate": "Notice screen",
      "source": "src/components/abox/notice-page.tsx",
      "decision": "DEFER — later shell/screen phase (B8)",
      "reason": "screen-level composition belongs to 05 Screens"
    },
    {
      "candidate": "Placeholder screen",
      "source": "src/components/abox/placeholder-screen.tsx",
      "decision": "DEFER — later shell/screen phase (B8)",
      "reason": "screen-level, single consumer"
    },
    {
      "candidate": "Shopping path bar",
      "source": "src/components/abox/shopping-path-bar.tsx",
      "decision": "DEFER — insufficient representation",
      "reason": "no B4 primitive for its steps"
    },
    {
      "candidate": "Card group (PlanCard)",
      "source": "src/components/abox/plan-card.tsx",
      "decision": "DEFER — insufficient representation",
      "reason": "PlanCard is not a B4 component"
    },
    {
      "candidate": "Overlay compositions (dialog/sheet/dropdown/tooltip/tabs)",
      "source": "src/components/ui/*",
      "decision": "DEFER — insufficient representation",
      "reason": "no B4 overlay primitives"
    }
  ],
  "rejected": [
    {
      "candidate": "Labelled field group",
      "reason": "REJECT — not actually reusable: each route composes its own ad-hoc field set (3 LabeledField consumers, no fixed grouping)"
    },
    {
      "candidate": "Filter / toolbar + result region",
      "reason": "REJECT — not actually reusable: no repeated structural composition found in the non-reference routes"
    },
    {
      "candidate": "Action-group arrangement",
      "reason": "REJECT — not actually reusable: ActionPill groupings are route-specific"
    }
  ],
  "limitations": [
    "Production lays KPI rows out with CSS grid and responsive breakpoints (grid gap-4 sm:grid-cols-2 lg:grid-cols-4); Figma auto-layout has no responsive breakpoint concept, so the columns axis encodes only the two authored column counts (3 and 4) and no breakpoint behaviour is modelled. — src/routes/app.dashboard.tsx:31",
    "ModuleTabBar shows 5 of the 12 production workforce tabs; the count is sample scope, chosen as the minimum that demonstrates the active/default relationship. — src/components/m06/workforce-page.tsx:17",
    "WizardStepper contains all 8 production steps in source order; its state configuration is copied from one documented real production route/current-step condition (/agency/downlines/new/contacts, SCR-M05-009, step 3 of 8). B4's upcoming state does not occur there — the source makes a step reachable only when i <= currentIndex, so no real route produces it; no state is manufactured and none are combined across routes. — src/components/abox/downline-wizard-stepper.tsx:18",
    "B4 coloured positive KpiCard delta chips per tone, while production always uses the sage branch for a positive delta (kpi-card.tsx:78). KpiRow consumes the live B5 component unchanged: the deviation is displayed, recorded, and not silently corrected in B6.",
    "Tab and wizard-step navigation is router-driven; no Figma prototype connection is created because the destination screens are B8 scope. B6 creates 0 prototype reactions.",
    "CSS pseudo-class states (hover, focus-visible, active) are not converted into Figma variants; each is recorded as a deferred interaction instead.",
    "Production row wrappers carry only layout classes (grid/gap), so B6 pattern roots have no fill, and only ModuleTabBar carries a stroke — bound to the existing B3 ABox/Semantic/hairline style, never a copied colour value."
  ]
};
