// GENERATED by tools/figma-plugin/extract-b3.mjs — do not edit by hand.
const ABOX_B3 = {
  "meta": {
    "batch": "B3",
    "source": "src/styles.css, src/components/abox/status-badge.tsx, src/components/abox/metal-badge.tsx",
    "generated": "tools/figma-plugin/extract-b3.mjs"
  },
  "colorStyles": [
    {
      "name": "ABox/Semantic/background",
      "collection": "ABox/Color/Semantic",
      "variable": "background",
      "source": "source: --color-background: var(--background); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "foreground",
      "source": "source: --color-foreground: var(--foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/surface",
      "collection": "ABox/Color/Semantic",
      "variable": "surface",
      "source": "source: --color-surface: var(--surface); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/surface-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "surface-foreground",
      "source": "source: --color-surface-foreground: var(--surface-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/panel",
      "collection": "ABox/Color/Semantic",
      "variable": "panel",
      "source": "source: --color-panel: var(--panel); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/card",
      "collection": "ABox/Color/Semantic",
      "variable": "card",
      "source": "source: --color-card: var(--card); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/card-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "card-foreground",
      "source": "source: --color-card-foreground: var(--card-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/popover",
      "collection": "ABox/Color/Semantic",
      "variable": "popover",
      "source": "source: --color-popover: var(--popover); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/popover-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "popover-foreground",
      "source": "source: --color-popover-foreground: var(--popover-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/primary",
      "collection": "ABox/Color/Semantic",
      "variable": "primary",
      "source": "source: --color-primary: var(--primary); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/primary-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "primary-foreground",
      "source": "source: --color-primary-foreground: var(--primary-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/primary-soft",
      "collection": "ABox/Color/Semantic",
      "variable": "primary-soft",
      "source": "source: --color-primary-soft: var(--primary-soft); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/secondary",
      "collection": "ABox/Color/Semantic",
      "variable": "secondary",
      "source": "source: --color-secondary: var(--secondary); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/secondary-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "secondary-foreground",
      "source": "source: --color-secondary-foreground: var(--secondary-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sage",
      "collection": "ABox/Color/Semantic",
      "variable": "sage",
      "source": "source: --color-sage: var(--sage); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sage-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "sage-foreground",
      "source": "source: --color-sage-foreground: var(--sage-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sage-soft",
      "collection": "ABox/Color/Semantic",
      "variable": "sage-soft",
      "source": "source: --color-sage-soft: var(--sage-soft); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/muted",
      "collection": "ABox/Color/Semantic",
      "variable": "muted",
      "source": "source: --color-muted: var(--muted); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/muted-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "muted-foreground",
      "source": "source: --color-muted-foreground: var(--muted-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/accent",
      "collection": "ABox/Color/Semantic",
      "variable": "accent",
      "source": "source: --color-accent: var(--accent); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/accent-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "accent-foreground",
      "source": "source: --color-accent-foreground: var(--accent-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/destructive",
      "collection": "ABox/Color/Semantic",
      "variable": "destructive",
      "source": "source: --color-destructive: var(--destructive); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/destructive-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "destructive-foreground",
      "source": "source: --color-destructive-foreground: var(--destructive-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/warning",
      "collection": "ABox/Color/Semantic",
      "variable": "warning",
      "source": "source: --color-warning: var(--warning); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/warning-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "warning-foreground",
      "source": "source: --color-warning-foreground: var(--warning-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/info",
      "collection": "ABox/Color/Semantic",
      "variable": "info",
      "source": "source: --color-info: var(--info); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/info-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "info-foreground",
      "source": "source: --color-info-foreground: var(--info-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/success",
      "collection": "ABox/Color/Semantic",
      "variable": "success",
      "source": "source: --color-success: var(--success); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/success-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "success-foreground",
      "source": "source: --color-success-foreground: var(--success-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/border",
      "collection": "ABox/Color/Semantic",
      "variable": "border",
      "source": "source: --color-border: var(--border); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/border-strong",
      "collection": "ABox/Color/Semantic",
      "variable": "border-strong",
      "source": "source: --color-border-strong: var(--border-strong); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/hairline",
      "collection": "ABox/Color/Semantic",
      "variable": "hairline",
      "source": "source: --color-hairline: var(--hairline); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/input",
      "collection": "ABox/Color/Semantic",
      "variable": "input",
      "source": "source: --color-input: var(--input); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/ring",
      "collection": "ABox/Color/Semantic",
      "variable": "ring",
      "source": "source: --color-ring: var(--ring); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/ring-offset-background",
      "collection": "ABox/Color/Semantic",
      "variable": "ring-offset-background",
      "source": "source: --color-ring-offset-background: var(--background); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/chart/1",
      "collection": "ABox/Color/Semantic",
      "variable": "chart/1",
      "source": "source: --color-chart-1: var(--chart-1); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/chart/2",
      "collection": "ABox/Color/Semantic",
      "variable": "chart/2",
      "source": "source: --color-chart-2: var(--chart-2); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/chart/3",
      "collection": "ABox/Color/Semantic",
      "variable": "chart/3",
      "source": "source: --color-chart-3: var(--chart-3); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/chart/4",
      "collection": "ABox/Color/Semantic",
      "variable": "chart/4",
      "source": "source: --color-chart-4: var(--chart-4); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/chart/5",
      "collection": "ABox/Color/Semantic",
      "variable": "chart/5",
      "source": "source: --color-chart-5: var(--chart-5); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sidebar",
      "collection": "ABox/Color/Semantic",
      "variable": "sidebar",
      "source": "source: --color-sidebar: var(--sidebar); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sidebar/foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "sidebar/foreground",
      "source": "source: --color-sidebar-foreground: var(--sidebar-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sidebar/primary",
      "collection": "ABox/Color/Semantic",
      "variable": "sidebar/primary",
      "source": "source: --color-sidebar-primary: var(--sidebar-primary); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sidebar/primary-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "sidebar/primary-foreground",
      "source": "source: --color-sidebar-primary-foreground: var(--sidebar-primary-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sidebar/accent",
      "collection": "ABox/Color/Semantic",
      "variable": "sidebar/accent",
      "source": "source: --color-sidebar-accent: var(--sidebar-accent); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sidebar/accent-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "sidebar/accent-foreground",
      "source": "source: --color-sidebar-accent-foreground: var(--sidebar-accent-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sidebar/border",
      "collection": "ABox/Color/Semantic",
      "variable": "sidebar/border",
      "source": "source: --color-sidebar-border: var(--sidebar-border); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/sidebar/ring",
      "collection": "ABox/Color/Semantic",
      "variable": "sidebar/ring",
      "source": "source: --color-sidebar-ring: var(--sidebar-ring); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/ai",
      "collection": "ABox/Color/Semantic",
      "variable": "ai",
      "source": "source: --color-ai: var(--ai); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/ai-foreground",
      "collection": "ABox/Color/Semantic",
      "variable": "ai-foreground",
      "source": "source: --color-ai-foreground: var(--ai-foreground); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/surface-1",
      "collection": "ABox/Color/Semantic",
      "variable": "surface-1",
      "source": "source: --color-surface-1: var(--surface-1); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/surface-2",
      "collection": "ABox/Color/Semantic",
      "variable": "surface-2",
      "source": "source: --color-surface-2: var(--surface-2); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/surface-3",
      "collection": "ABox/Color/Semantic",
      "variable": "surface-3",
      "source": "source: --color-surface-3: var(--surface-3); (src/styles.css)"
    },
    {
      "name": "ABox/Semantic/brand-accent",
      "collection": "ABox/Color/Semantic",
      "variable": "brand-accent",
      "source": "source: --color-brand-accent: var(--brand-accent); (src/styles.css)"
    },
    {
      "name": "ABox/Status/sage",
      "collection": "ABox/Status",
      "variable": "sage",
      "source": "source: src/components/abox/status-badge.tsx — tones.sage: \"[--tone:var(--sage)]\""
    },
    {
      "name": "ABox/Status/primary",
      "collection": "ABox/Status",
      "variable": "primary",
      "source": "source: src/components/abox/status-badge.tsx — tones.primary: \"[--tone:var(--primary)]\""
    },
    {
      "name": "ABox/Status/warning",
      "collection": "ABox/Status",
      "variable": "warning",
      "source": "source: src/components/abox/status-badge.tsx — tones.warning: \"[--tone:var(--warning)]\""
    },
    {
      "name": "ABox/Status/muted",
      "collection": "ABox/Status",
      "variable": "muted",
      "source": "source: src/components/abox/status-badge.tsx — tones.muted: \"[--tone:var(--foreground)]\""
    },
    {
      "name": "ABox/Status/destructive",
      "collection": "ABox/Status",
      "variable": "destructive",
      "source": "source: src/components/abox/status-badge.tsx — tones.destructive: \"[--tone:var(--destructive)]\""
    },
    {
      "name": "ABox/Status/info",
      "collection": "ABox/Status",
      "variable": "info",
      "source": "source: src/components/abox/status-badge.tsx — tones.info: \"[--tone:var(--info)]\""
    },
    {
      "name": "ABox/Metal/bronze",
      "collection": "ABox/Status",
      "variable": "metal/bronze",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-bronze)]"
    },
    {
      "name": "ABox/Metal/expanded-bronze",
      "collection": "ABox/Status",
      "variable": "metal/expanded-bronze",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-expanded-bronze)]"
    },
    {
      "name": "ABox/Metal/silver",
      "collection": "ABox/Status",
      "variable": "metal/silver",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-silver)]"
    },
    {
      "name": "ABox/Metal/gold",
      "collection": "ABox/Status",
      "variable": "metal/gold",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-gold)]"
    },
    {
      "name": "ABox/Metal/platinum",
      "collection": "ABox/Status",
      "variable": "metal/platinum",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-platinum)]"
    },
    {
      "name": "ABox/Metal/catastrophic",
      "collection": "ABox/Status",
      "variable": "metal/catastrophic",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-catastrophic)]"
    },
    {
      "name": "ABox/Metal/bronze-fg",
      "collection": "ABox/Status",
      "variable": "metal/bronze-fg",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-bronze-fg)]"
    },
    {
      "name": "ABox/Metal/expanded-bronze-fg",
      "collection": "ABox/Status",
      "variable": "metal/expanded-bronze-fg",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-expanded-bronze-fg)]"
    },
    {
      "name": "ABox/Metal/silver-fg",
      "collection": "ABox/Status",
      "variable": "metal/silver-fg",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-silver-fg)]"
    },
    {
      "name": "ABox/Metal/gold-fg",
      "collection": "ABox/Status",
      "variable": "metal/gold-fg",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-gold-fg)]"
    },
    {
      "name": "ABox/Metal/platinum-fg",
      "collection": "ABox/Status",
      "variable": "metal/platinum-fg",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-platinum-fg)]"
    },
    {
      "name": "ABox/Metal/catastrophic-fg",
      "collection": "ABox/Status",
      "variable": "metal/catastrophic-fg",
      "source": "source: src/components/abox/metal-badge.tsx — [--tone:var(--metal-catastrophic-fg)]"
    }
  ],
  "textStyles": [
    {
      "name": "ABox/Text/eyebrow",
      "family": "Inter Tight",
      "weight": 500,
      "styleNames": [
        "Medium"
      ],
      "fontSize": 11,
      "letterSpacing": {
        "value": 0,
        "unit": "PERCENT"
      },
      "textCase": "UPPER",
      "source": "source: @utility text-eyebrow (src/styles.css:290) — font-family var(--font-mono) -> family/mono; font-size 0.6875rem; font-weight 500; letter-spacing 0; text-transform uppercase"
    },
    {
      "name": "ABox/Text/serial",
      "family": "Inter Tight",
      "weight": 400,
      "styleNames": [
        "Regular"
      ],
      "fontSize": 10,
      "letterSpacing": {
        "value": 0,
        "unit": "PERCENT"
      },
      "textCase": "UPPER",
      "source": "source: @utility text-serial (src/styles.css:299) — font-family var(--font-mono) -> family/mono; font-size 0.625rem; letter-spacing 0; text-transform uppercase. Production declares no font-weight for this role: the CSS-inherited initial value normal (400) is used, not a chosen weight."
    }
  ],
  "effectStyles": [
    {
      "name": "ABox/Elevation/card",
      "family": "card",
      "layers": [
        {
          "index": 1,
          "x": 0,
          "y": 1,
          "blur": 0,
          "spread": 0,
          "tint": {
            "L": 0.3,
            "C": 0.05,
            "h": 265,
            "a": 0.04
          },
          "tintCss": "oklch(0.3 0.05 265 / 0.04)",
          "vars": {
            "x": "card/1/x",
            "y": "card/1/y",
            "blur": "card/1/blur",
            "spread": "card/1/spread",
            "tint": "card/1/tint"
          }
        },
        {
          "index": 2,
          "x": 0,
          "y": 12,
          "blur": 24,
          "spread": -18,
          "tint": {
            "L": 0.3,
            "C": 0.05,
            "h": 265,
            "a": 0.2
          },
          "tintCss": "oklch(0.3 0.05 265 / 0.2)",
          "vars": {
            "x": "card/2/x",
            "y": "card/2/y",
            "blur": "card/2/blur",
            "spread": "card/2/spread",
            "tint": "card/2/tint"
          }
        }
      ],
      "source": "source: --shadow-card (src/styles.css:82) — every layer field bound to ABox/Elevation variables"
    },
    {
      "name": "ABox/Elevation/elevated",
      "family": "elevated",
      "layers": [
        {
          "index": 1,
          "x": 0,
          "y": 1,
          "blur": 0,
          "spread": 0,
          "tint": {
            "L": 0.3,
            "C": 0.05,
            "h": 265,
            "a": 0.06
          },
          "tintCss": "oklch(0.3 0.05 265 / 0.06)",
          "vars": {
            "x": "elevated/1/x",
            "y": "elevated/1/y",
            "blur": "elevated/1/blur",
            "spread": "elevated/1/spread",
            "tint": "elevated/1/tint"
          }
        },
        {
          "index": 2,
          "x": 0,
          "y": 24,
          "blur": 44,
          "spread": -22,
          "tint": {
            "L": 0.3,
            "C": 0.05,
            "h": 265,
            "a": 0.26
          },
          "tintCss": "oklch(0.3 0.05 265 / 0.26)",
          "vars": {
            "x": "elevated/2/x",
            "y": "elevated/2/y",
            "blur": "elevated/2/blur",
            "spread": "elevated/2/spread",
            "tint": "elevated/2/tint"
          }
        }
      ],
      "source": "source: --shadow-elevated (src/styles.css:83) — every layer field bound to ABox/Elevation variables"
    },
    {
      "name": "ABox/Elevation/drawer",
      "family": "drawer",
      "layers": [
        {
          "index": 1,
          "x": -20,
          "y": 0,
          "blur": 60,
          "spread": -30,
          "tint": {
            "L": 0.3,
            "C": 0.05,
            "h": 265,
            "a": 0.3
          },
          "tintCss": "oklch(0.3 0.05 265 / 0.3)",
          "vars": {
            "x": "drawer/1/x",
            "y": "drawer/1/y",
            "blur": "drawer/1/blur",
            "spread": "drawer/1/spread",
            "tint": "drawer/1/tint"
          }
        }
      ],
      "source": "source: --shadow-drawer (src/styles.css:84) — every layer field bound to ABox/Elevation variables"
    },
    {
      "name": "ABox/Elevation/plate",
      "family": "plate",
      "layers": [
        {
          "index": 1,
          "x": 0,
          "y": 0,
          "blur": 0,
          "spread": 1,
          "tint": {
            "L": 0.3,
            "C": 0.05,
            "h": 265,
            "a": 0.06
          },
          "tintCss": "oklch(0.3 0.05 265 / 0.06)",
          "vars": {
            "x": "plate/1/x",
            "y": "plate/1/y",
            "blur": "plate/1/blur",
            "spread": "plate/1/spread",
            "tint": "plate/1/tint"
          }
        },
        {
          "index": 2,
          "x": 0,
          "y": 20,
          "blur": 40,
          "spread": -24,
          "tint": {
            "L": 0.3,
            "C": 0.05,
            "h": 265,
            "a": 0.22
          },
          "tintCss": "oklch(0.3 0.05 265 / 0.22)",
          "vars": {
            "x": "plate/2/x",
            "y": "plate/2/y",
            "blur": "plate/2/blur",
            "spread": "plate/2/spread",
            "tint": "plate/2/tint"
          }
        }
      ],
      "source": "source: --shadow-plate (src/styles.css:85) — every layer field bound to ABox/Elevation variables"
    },
    {
      "name": "ABox/Elevation/glow",
      "family": "glow",
      "layers": [
        {
          "index": 1,
          "x": 0,
          "y": 1,
          "blur": 0,
          "spread": 0,
          "tint": {
            "L": 0.31,
            "C": 0.09,
            "h": 265,
            "a": 0.32
          },
          "tintCss": "oklch(0.31 0.09 265 / 0.32)",
          "vars": {
            "x": "glow/1/x",
            "y": "glow/1/y",
            "blur": "glow/1/blur",
            "spread": "glow/1/spread",
            "tint": "glow/1/tint"
          }
        },
        {
          "index": 2,
          "x": 0,
          "y": 10,
          "blur": 20,
          "spread": -14,
          "tint": {
            "L": 0.24,
            "C": 0.07,
            "h": 265,
            "a": 0.55
          },
          "tintCss": "oklch(0.24 0.07 265 / 0.55)",
          "vars": {
            "x": "glow/2/x",
            "y": "glow/2/y",
            "blur": "glow/2/blur",
            "spread": "glow/2/spread",
            "tint": "glow/2/tint"
          }
        }
      ],
      "source": "source: --shadow-glow (src/styles.css:87) — every layer field bound to ABox/Elevation variables"
    }
  ],
  "limitations": [
    "src/components/abox/status-badge.tsx — color: color-mix(in oklch, var(--tone) 88%, var(--foreground)); background: color-mix(in oklch, var(--tone) 12%, var(--card)); borderColor: color-mix(in oklch, var(--tone) 34%, transparent): runtime-computed, no static Figma Style created.",
    "src/styles.css — oklch() has no Figma equivalent: colours are converted to sRGB and the original oklch literal is preserved in the style description.",
    "src/styles.css:257 and 282 — h1,h2,h3,.font-display and @utility text-display declare no font-size, so no faithful Text Style exists; sizes are applied per usage by Tailwind utilities. Recorded, not approximated.",
    "src/styles.css:244 — the html base role declares only font-family; no Text Style created.",
    "src/styles.css:261 and :287 — font-variation-settings axes are per text node, not Text Style properties; recorded only.",
    "src/styles.css:254 — font-feature-settings has no Figma Text Style property; recorded only.",
    "src/styles.css:305 — font-variant-numeric: tabular-nums has no Figma Text Style property; recorded only.",
    "@utility text-eyebrow / text-serial declare color: var(--muted-foreground): Figma Text Styles hold no colour; the ABox/Semantic/muted-foreground colour style carries it.",
    "src/components/abox/plan-o-assistant.tsx:27 composes var(--shadow-glow) with an additional inline shadow layer: a component-level composition, not a foundational Effect Style.",
    "src/styles.css:462 — --shadow-overlay is an alias of --shadow-elevated with no consumer; documented, no separate Effect Style.",
    "Production declares no .dark override for --shadow-*: the elevation styles are mode-identical by production, not by approximation.",
    "The 62 B1 primitives receive no colour styles: production consumes them only as alias targets.",
    "Decorative utilities (noise-field, contour, aurora, glass, ember-underline, card-brackets, edge-sheen), motion keyframes and responsive breakpoints are not Figma Styles; none is representable exactly and all are out of scope.",
    "No grid styles: production declares no reusable grid definition. Category recorded as zero.",
    "No components, component sets, variants, page content or publishing in B3."
  ]
};
