import { SRC_BLUEPRINT, SRC_IA, SRC_NORTH, screens } from "./types";

const WS = "WS_PLATFORM (global) and WS_AGENCY (own subtree) — the same screens, different scope";
const MOD = "MOD_ADMIN_CONFIG";
const SRC = `${SRC_BLUEPRINT} (tenant setup, white labeling, governance, integrations, reporting); ${SRC_IA} (SCR_ADMIN_*, configuration and white-labeling model, help model); ${SRC_NORTH} (event model, architecture posture)`;

export const ADMIN = screens([
  {
    id: "SCR_ADMIN_TENANT",
    slug: "admin-tenant-marketplace",
    name: "Tenant & Marketplace Setup",
    group: "Admin, configuration, integrations & audit",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Platform administrator provisioning tenants; agency admin configuring their own marketplace",
    purpose:
      "Provisions a tenant and the consumer marketplaces it presents: domain, identity, which products are exposed, which entry paths are enabled, and which entity is legally presenting it.",
    actions: ["Create a tenant", "Create a marketplace", "Bind a domain or subdomain", "Select exposed products", "Enable entry paths", "Set the presenting entity and licensure line", "Publish the marketplace"],
    objects: [
      "Tenant",
      "Marketplace",
      "Domain binding",
      "Presenting entity and licensure disclosure",
      "Exposed product set",
      "Entry path configuration (guided, browse, agent-assisted, shared quote)",
      "Publish state",
    ],
    config: [
      "Domain and subdomain per marketplace",
      "Products exposed, bounded by entity enablement and availability rules",
      "Entry paths enabled",
      "Consumer registration policy",
      "Member workspace enabled and its branding",
    ],
    acl: [
      "Tenant creation is platform-only; marketplace configuration is delegated to the owning agency within guardrails",
      "A marketplace can only expose products the presenting entity is enabled and appointed for — the picker is filtered, not merely validated",
      "Licensure and required disclosures cannot be removed by any tenant configuration",
    ],
    drawer: [
      "Context: tenant, marketplace and presenting entity",
      "Summary: products exposed, entry paths, publish state",
      "Guidance: what publishing makes publicly reachable",
      "Help & FAQ: multiple marketplaces under one agency",
      "Audit: creation, product exposure and publish events",
      "Next actions: preview marketplace, configure branding, publish",
    ],
    assistant: "Explains why a product cannot be exposed on a marketplace by tracing enablement, availability and appointment.",
    source: SRC,
    assumptions: ["One agency may present multiple marketplaces; each has its own branding, product exposure and attribution."],
    m1Seam: "Configures the marketplace that Module 1's landing (UX-001) renders, extending the minimal Module 1 configuration in UX-024 without changing it.",
    canvas: [
      { title: "Tenant", id: "TEN-REC", kind: "fields", items: ["Tenant name", "Owning entity", "Status", "Environment", "Created"], wide: true },
      { title: "Marketplaces", id: "TEN-MKT", kind: "table", items: ["Marketplace", "Domain", "Presenting entity", "Products exposed", "Entry paths", "Published"], wide: true },
      { title: "Entry paths", id: "TEN-PATHS", kind: "checks", items: ["Guided (Plan-O)", "Manual browse", "Agent-assisted", "Shared quote link", "Member workspace"] },
      { title: "Presenting entity block", id: "TEN-PRESENT", kind: "box", note: "Legal name, licensure line and required consumer disclosures. Locked content — configurable identity, non-removable disclosure.", wide: true },
    ],
  },
  {
    id: "SCR_ADMIN_BRANDING",
    slug: "admin-branding-labels",
    name: "Branding, White Labeling & Configurable Labels",
    group: "Admin, configuration, integrations & audit",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, platform brand administrator",
    purpose:
      "Full white-labeling of both the external marketplace and the internal shell, plus the label dictionary that lets a tenant rename workspaces, entities, modules and objects to its own vocabulary — inside global guardrails.",
    actions: [
      "Set brand assets and theme",
      "Configure external marketplace chrome",
      "Configure internal shell chrome",
      "Edit the label dictionary",
      "Preview across surfaces",
      "Set inheritance for child entities",
      "Publish a brand version",
    ],
    objects: [
      "Brand theme (external and internal variants)",
      "Label dictionary entries (workspace, entity, agent, member, lead, marketplace, module names)",
      "Locked label set",
      "Inheritance rules",
      "Brand version",
      "Preview renders",
    ],
    config: [
      "Logo, colours, typography within approved ranges",
      "Marketplace name and internal platform display name",
      "Label overrides per term, per tenant, per workspace",
      "Which labels are locked (regulated terms, disclosure text)",
      "Child entity inheritance: inherit, inherit-with-logo-override, or independent",
    ],
    acl: [
      "branding.manage and labels.manage within your subtree",
      "Regulated terms and disclosure language are in the locked label set and cannot be renamed — attempts are refused with the rule shown",
      "Labels change display only; permission and object identifiers never change with a label",
      "Brand and label versions are published, not live-edited, so a rendered artifact is reproducible",
    ],
    drawer: [
      "Context: entity, brand version, inheritance",
      "Summary: labels overridden, locked labels, surfaces affected",
      "Guidance: labels rename what users see, never what the system enforces",
      "Help & FAQ: why some terms cannot be renamed",
      "Audit: brand and label changes with actor",
      "Next actions: preview, publish, manage inheritance",
    ],
    assistant: "Shows where a label appears across the platform before it is changed.",
    source: SRC,
    assumptions: ["Every screen renders labels from the dictionary rather than hardcoded strings; this is a design rule locked in the charter."],
    canvas: [
      { title: "External marketplace brand", id: "BRN-EXT", kind: "fields", items: ["Logo", "Colours", "Typography", "Marketplace name", "Hero treatment", "Footer content"], wide: true },
      { title: "Internal shell brand", id: "BRN-INT", kind: "fields", items: ["Platform display name", "Logo", "Accent colour", "Login screen treatment"], wide: true },
      { title: "Label dictionary", id: "BRN-LABELS", kind: "table", items: ["Term", "Default", "Tenant override", "Locked", "Where it appears"], wide: true },
      { title: "Locked terms", id: "BRN-LOCKED", kind: "checks", items: ["Regulated product names", "Required disclosure wording", "Non-discrimination notice", "Terms carrying legal meaning"] },
      { title: "Inheritance", id: "BRN-INHERIT", kind: "list", items: ["Child inherits parent brand", "Child may override logo only", "Child is fully independent"] },
    ],
  },
  {
    id: "SCR_ADMIN_WORKSPACES",
    slug: "admin-workspaces-menus",
    name: "Workspace Configuration, Menu & Module Visibility",
    group: "Admin, configuration, integrations & audit",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Platform administrator; agency admin within delegated bounds",
    purpose:
      "Defines which workspaces a tenant has, what each contains, and how the left navigation is composed per role — the configurability the charter requires, without letting configuration become a security boundary.",
    actions: ["Enable a workspace for a tenant", "Set the module set per workspace", "Order and group menu items", "Rename menu items", "Set default landing per role", "Preview navigation as a role"],
    objects: [
      "Workspace definition and enablement",
      "Module-to-workspace assignment",
      "Menu composition and grouping",
      "Default landing page per role",
      "Nested module rules",
      "Role preview result",
    ],
    config: [
      "Workspaces available: consumer marketplace, member, agency, platform, carrier and others per tenant",
      "Modules present in each workspace",
      "Menu order, grouping and labels",
      "Default landing per role",
      "Which modules are nested and therefore never top-level",
    ],
    acl: [
      "Menu configuration is display only — hiding a module never grants or removes a permission, and showing one never bypasses ACL",
      "A module the role cannot access is absent from navigation regardless of menu configuration",
      "Nested modules such as appointments/paper and AI governance cannot be promoted to top level by configuration",
      "workspace.configure is platform-level; agencies may reorder and rename within their own workspaces",
    ],
    drawer: [
      "Context: workspace, role and menu composition",
      "Summary: modules visible, modules hidden by ACL vs by configuration",
      "Guidance: configuration is not a security control",
      "Help & FAQ: why a module still does not appear",
      "Audit: workspace and menu changes",
      "Next actions: preview as role, reorder, publish",
    ],
    assistant: "Explains, for a given role, why each module is present or absent — distinguishing ACL from menu configuration.",
    source: SRC,
    assumptions: ["Workspace switching, entity switching and the global bar are platform-fixed; only their contents and labels are configurable."],
    canvas: [
      { title: "Workspaces", id: "WSC-LIST", kind: "table", items: ["Workspace", "Enabled", "Modules", "Default landing", "Audience"], wide: true },
      { title: "Menu composition", id: "WSC-MENU", kind: "tree", items: ["Group: Work", "Group: Sales", "Group: Administration", "Nested: Appointments, Paper & Referrals", "Nested: AI, Plan-O & Governance"] },
      { title: "Role preview", id: "WSC-PREVIEW", kind: "fields", items: ["Role", "Entity", "Workspace"], note: "Renders the navigation that role would see, annotating each hidden item with the reason: ACL or configuration." },
      { title: "Guardrail note", id: "WSC-GUARD", kind: "box", note: "Hiding a module is cosmetic. Access is decided by ACL at every request, so a hidden module is still enforced server-side.", wide: true },
    ],
  },
  {
    id: "SCR_ADMIN_FLAGS",
    slug: "admin-flags-demo",
    name: "Feature Flags & Synthetic / Demo Mode",
    group: "Admin, configuration, integrations & audit",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Platform administrator; agency admin for the flags delegated to them",
    purpose:
      "Controls staged rollout of capabilities per tenant and the synthetic mode used for demos, training and sales — with an unmistakable indication whenever data is not real.",
    actions: ["Toggle a flag per tenant", "Set a rollout scope", "Enable synthetic mode", "Load a demo dataset", "Reset synthetic data", "View flag change history"],
    objects: [
      "Feature flag",
      "Flag scope (platform, tenant, entity, role)",
      "Synthetic mode state",
      "Demo dataset",
      "Flag change record",
      "Synthetic data banner state",
    ],
    config: [
      "Flag catalog and which flags are tenant-delegable",
      "Rollout scopes",
      "Demo dataset library",
      "Synthetic mode indicators and their prominence",
      "Whether synthetic mode is permitted in a production tenant at all",
    ],
    acl: [
      "flags.manage is platform-level except for explicitly delegated flags",
      "A flag can never grant a permission — flags gate capability presence, ACL gates access, and the two are independent",
      "Synthetic mode is visually unmistakable on every screen and in every generated document, and can never send a real communication or a real carrier submission",
      "Switching a production tenant into synthetic mode requires platform action and is audited",
    ],
    drawer: [
      "Context: tenant, flags in effect, synthetic state",
      "Summary: flags on, flags delegated, demo dataset loaded",
      "Guidance: flags versus permissions",
      "Help & FAQ: safe demoing to a prospect",
      "Audit: flag toggles and synthetic-mode changes",
      "Next actions: toggle, load dataset, exit synthetic mode",
    ],
    assistant: "Reports which flags are affecting the current tenant and what each enables.",
    source: SRC,
    assumptions: ["Synthetic mode is a hard sandbox: outbound communications, carrier submissions and payment authorizations are all blocked, not merely discouraged."],
    canvas: [
      { title: "Flags", id: "FLG-LIST", kind: "table", items: ["Flag", "Scope", "State", "Delegable", "Changed by", "Changed at"], wide: true },
      { title: "Synthetic mode", id: "FLG-SYNTH", kind: "box", note: "When on, every screen carries a persistent synthetic-data banner and outbound sends, submissions and payment authorizations are blocked.", wide: true },
      { title: "Demo datasets", id: "FLG-DEMO", kind: "list", items: ["IFP shopping demo", "Agency with downline demo", "Commission statement demo", "Reset all synthetic data"] },
      { title: "Flag vs permission", id: "FLG-NOTE", kind: "checks", items: ["A flag can hide a capability", "A flag can never grant access", "ACL is evaluated independently of every flag"] },
    ],
  },
  {
    id: "SCR_ADMIN_ROUTING",
    slug: "admin-routing-rules",
    name: "Routing Rules",
    group: "Admin, configuration, integrations & audit",
    workspace: WS,
    module: "MOD_ADMIN_CONFIG + MOD_LEADS_CUSTOMERS",
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, platform administrator",
    purpose:
      "Decides who gets what: which agent or queue receives a lead, a callback request, a review task or an escalation — with fallbacks, capacity limits and a trace explaining every assignment.",
    actions: ["Create a routing rule", "Set matching conditions", "Set the target and strategy", "Set fallback", "Set capacity and availability rules", "Simulate routing", "View the routing decision log"],
    objects: [
      "Routing rule",
      "Matching conditions (product, state, source, language, value band, entity)",
      "Target (agent, queue, entity)",
      "Distribution strategy (round robin, capacity-weighted, first-available, named)",
      "Fallback chain",
      "Assignment decision record",
    ],
    config: [
      "Rule dimensions available",
      "Distribution strategies",
      "Capacity per agent and working hours",
      "Fallback and unassigned handling",
      "Whether reassignment is permitted and by whom",
    ],
    acl: [
      "routing.manage within your own subtree; routing to an entity outside your subtree requires an existing relationship",
      "Routing can never assign a lead to an agent unlicensed for that state — the rule is filtered at evaluation time",
      "Every assignment records the rule that produced it, so disputes are resolvable",
    ],
    drawer: [
      "Context: rule set and its evaluation order",
      "Summary: rules active, unassigned volume, capacity pressure",
      "Guidance: precedence and fallback behaviour",
      "Help & FAQ: why did this lead go to that agent",
      "Audit: rule changes and assignment decisions",
      "Next actions: simulate, reorder, adjust capacity",
    ],
    assistant: "Explains why a specific lead or task routed where it did.",
    source: SRC,
    assumptions: ["Licensing and appointment eligibility are hard filters applied before any distribution strategy runs."],
    m1Seam: "Generalises the minimal Module 1 routing configuration (UX-025) to all lead, task and escalation types. UX-025 is unchanged.",
    canvas: [
      { title: "Rules", id: "RTE-RULES", kind: "table", items: ["Order", "Conditions", "Target", "Strategy", "Fallback", "Active"], wide: true },
      { title: "Eligibility filter", id: "RTE-ELIG", kind: "checks", items: ["Agent licensed in the state", "Agent appointed for the carrier where writing is implied", "Agent within capacity", "Agent available in working hours"] },
      { title: "Simulation", id: "RTE-SIM", kind: "fields", items: ["Lead source", "State", "Product", "Value band", "Time of day"], note: "Returns the assigned target and the rule and strategy that produced it." },
      { title: "Decision log", id: "RTE-LOG", kind: "table", items: ["When", "Object", "Rule", "Target", "Strategy", "Reassigned"], wide: true },
    ],
  },
  {
    id: "SCR_ADMIN_INTEGRATIONS",
    slug: "admin-integrations",
    name: "Integration Management",
    group: "Admin, configuration, integrations & audit",
    workspace: "WS_PLATFORM — WS_AGENCY read-only status",
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Platform operations; agency admin sees health only",
    purpose:
      "Every external connection in one register: EDE partner, carrier EDI and API endpoints, rate feeds, e-signature, payment processor, communications providers and identity — with health, credentials by reference, and the events each publishes or consumes.",
    actions: ["Register an integration", "Set environment and endpoints", "Reference credentials", "Test the connection", "View health and error rates", "Enable or disable", "View the event contract"],
    objects: [
      "Integration record",
      "Environment and endpoint configuration",
      "Credential reference (never a value)",
      "Health metrics and error classes",
      "Event contract (published and consumed events)",
      "Test result and history",
    ],
    config: [
      "Integration catalog and per-tenant enablement",
      "Environment routing (sandbox vs production)",
      "Retry and timeout policy",
      "Alert thresholds and recipients",
      "Which integrations are mandatory for a product to be enrollable",
    ],
    acl: [
      "integration.manage is platform-only; agency admins see health status and nothing else",
      "Credential values are never displayed, logged or exported by any screen — only names, rotation dates and owners",
      "Disabling an integration that a live product depends on is blocked and names the dependent products",
    ],
    drawer: [
      "Context: integration, environment and dependent products",
      "Summary: health, error rate, last success",
      "Guidance: what breaks if this is disabled",
      "Help & FAQ: sandbox vs production routing",
      "Audit: configuration changes, credential rotations, enable/disable events",
      "Next actions: test, rotate credentials, view events",
    ],
    assistant: "Classifies recent errors and identifies which products an integration affects. It cannot change configuration or view credentials.",
    source: SRC,
    assumptions: ["The EDE partner handoff used by Module 1 is one integration among many and is registered here without altering the Module 1 handoff screen."],
    m1Seam: "Registers the EDE partner connection behind Module 1's handoff (UX-023). UX-023 itself is unchanged.",
    canvas: [
      { title: "Integration register", id: "INT-REG", kind: "table", items: ["Integration", "Type", "Environment", "Health", "Last success", "Error rate", "Dependent products"], wide: true },
      { title: "Configuration", id: "INT-CFG", kind: "fields", items: ["Endpoint", "Auth method", "Credential reference", "Timeout", "Retry policy", "Alert threshold"], wide: true },
      { title: "Event contract", id: "INT-EVENTS", kind: "list", items: ["Events published to ABox", "Events ABox sends", "Payload version", "Backfill support"] },
      { title: "Credential rule", id: "INT-CRED", kind: "box", note: "Screens display credential names, owners and rotation dates only. No interface in ABox reveals a secret value." },
    ],
  },
  {
    id: "SCR_ADMIN_AUDIT_EXPORT",
    slug: "admin-events-audit-export",
    name: "Event & Audit Logs, Global/Local ACL and Data Export Controls",
    group: "Admin, configuration, integrations & audit",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Platform governance, compliance reviewer, agency admin within scope",
    purpose:
      "The governance console: the raw event stream, the append-only audit log, the global-versus-local ACL guardrail view, and the policies controlling how data may leave the platform.",
    actions: [
      "Browse the event stream",
      "Search the audit log",
      "View the global ACL guardrail set",
      "View local overrides across the tenant",
      "Set export policy and limits",
      "Approve an export request",
      "Export an audit pack",
    ],
    objects: [
      "Platform event records",
      "Audit log entries (append-only)",
      "Global guardrail permission set",
      "Local override register",
      "Export policy and limits",
      "Export approval requests",
      "Retention policy per record class",
    ],
    config: [
      "Event retention per class",
      "Which actions are audited as sensitive",
      "Export formats, row limits and approval thresholds per role",
      "Watermarking policy",
      "Retention and legal-hold settings",
    ],
    acl: [
      "audit.view and policy.manage are narrowly held and never delegable to a general agency admin role",
      "The global guardrail set is platform-owned and displayed read-only to tenants so they can see exactly what they cannot override",
      "Audit records are append-only; no role, including platform, can edit or delete them",
      "Legal hold suspends retention deletion and cannot be lifted by the entity under hold",
    ],
    drawer: [
      "Context: log scope, period and record classes",
      "Summary: events, sensitive actions, pending export approvals",
      "Guidance: what the guardrail set protects",
      "Help & FAQ: responding to a regulator request",
      "Audit: this console's own use is audited",
      "Next actions: approve exports, export audit pack, adjust policy",
    ],
    assistant: "Helps locate events and explains guardrails. It cannot approve exports, change policy or alter records.",
    source: SRC,
    assumptions: ["The event stream follows the North Star event model, so audit, reporting, notifications and integrations all read one consistent set of events."],
    canvas: [
      { title: "Event stream", id: "GOV-EVENTS", kind: "table", items: ["When", "Event type", "Object", "Actor", "Entity", "Payload version"], wide: true },
      { title: "Audit log", id: "GOV-AUDIT", kind: "table", items: ["When", "Actor", "Action", "Object", "Before / after", "Justification", "Sensitive"], wide: true },
      { title: "Global vs local ACL", id: "GOV-ACL", kind: "list", items: ["Global guardrail permissions (never overridable)", "Platform-delegable permissions", "Local overrides in effect across the tenant", "Refused override attempts"] },
      { title: "Export controls", id: "GOV-EXPORT", kind: "fields", items: ["Role", "Formats permitted", "Row limit", "Approval threshold", "Watermark policy", "Sensitive-field rule"], wide: true },
      { title: "Retention & legal hold", id: "GOV-RETAIN", kind: "kv", items: ["Record class", "Retention period", "Legal hold", "Deletion behaviour"] },
    ],
  },
  {
    id: "SCR_ADMIN_HELP",
    slug: "admin-help-config",
    name: "Help, FAQ & Page Guidance Configuration",
    group: "Admin, configuration, integrations & audit",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, platform content administrator",
    purpose:
      "Authors the content that fills the right drawer and the bottom assistant on every screen — page guidance, FAQs and copilot knowledge — per screen, per audience and per tenant.",
    actions: ["Select a screen", "Author page guidance", "Manage the FAQ set", "Attach copilot knowledge", "Set audience visibility", "Preview in the drawer and assistant", "Publish"],
    objects: [
      "Help content record keyed by screen id and audience",
      "Page guidance block",
      "FAQ entries",
      "Copilot knowledge references",
      "Audience scope",
      "Publish state and version",
    ],
    config: [
      "Which screens have configurable help (all of them, by design)",
      "Audience segmentation: consumer, member, agent, agency admin, platform",
      "Whether an agency may override platform-authored help",
      "Approval requirement for consumer-facing help",
    ],
    acl: [
      "help.manage within your subtree; consumer-facing help requires approval",
      "Help content cannot contain advice, eligibility determinations or coverage guarantees — the same guardrails that bind the assistant bind its knowledge",
      "Help content is versioned so an assistant answer can be traced to the content that produced it",
    ],
    drawer: [
      "Context: screen being authored and its audience",
      "Summary: guidance present, FAQ count, copilot sources attached",
      "Guidance: write for the user of that screen, not for the platform",
      "Help & FAQ: this screen configures itself — the drawer preview is live",
      "Audit: content changes, approvals and publishes",
      "Next actions: preview, submit for approval, publish",
    ],
    assistant:
      "Previews live: the assistant on this screen answers from the content currently being authored, so an author can see exactly what a user would get before publishing.",
    source: SRC,
    assumptions: [
      "Every screen id in the inventory is a valid key for help content, so drawer and assistant content is complete by construction rather than retrofitted.",
    ],
    m1Seam: "Supplies the drawer and help content rendered by Module 1 screens, including UX-024 and UX-025's minimal configuration. Module 1 screens are unchanged.",
    canvas: [
      { title: "Screen selector", id: "HLP-SCREEN", kind: "fields", items: ["Workspace", "Module", "Screen id", "Audience"], wide: true },
      { title: "Page guidance", id: "HLP-GUIDE", kind: "editor", items: ["What this screen is for", "What the user should do here", "Common mistakes"] },
      { title: "FAQ set", id: "HLP-FAQ", kind: "list", items: ["Question and answer pair", "Audience scope", "Order", "Published"] },
      { title: "Copilot knowledge", id: "HLP-COPILOT", kind: "list", items: ["Attached approved sources", "Escalation triggers inherited from AI governance", "Disclaimers applied"] },
      { title: "Live preview", id: "HLP-PREVIEW", kind: "box", note: "Renders the drawer and assistant exactly as the selected audience would see them on the selected screen.", wide: true },
    ],
  },
]);
