import { SRC_BLUEPRINT, SRC_IA, SRC_NORTH, screens } from "./types";

const WS = "WS_AGENCY and WS_PLATFORM — scope differs by role, screens are the same";
const MOD = "MOD_AGENCY_ENTITY";
const SRC = `${SRC_BLUEPRINT} (agency and parent relationship model, licensing and access, governance); ${SRC_IA} (SCR_ENTITY_*, SCR_ACL_*); ${SRC_NORTH} object and relationship model`;

export const AGENCY = screens([
  {
    id: "SCR_ENTITY_SETUP",
    slug: "entity-setup",
    name: "Agency / Entity Setup",
    group: "Agency & agent management",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform administrator creating agencies; agency admin maintaining their own record and creating child entities",
    purpose:
      "Creates and maintains an entity — agency, downline agency, branch or partner — with the legal identity, licensing identifiers and parent relationship that everything else in ABox scopes against.",
    actions: ["Create an entity", "Set the parent entity", "Record legal identity and NPN", "Add addresses and contacts", "Set entity status", "Create a child entity", "Deactivate an entity"],
    objects: ["Entity", "Entity type", "Parent relationship", "Legal identity (legal name, DBA, TIN reference, agency NPN)", "Contacts", "Marketplace(s) owned by the entity"],
    config: [
      "Entity types available and which may have children",
      "Which identity fields are mandatory per type",
      "Whether an agency admin may create child entities without platform approval",
      "Default configuration inherited by a new child entity",
    ],
    acl: [
      "entity.manage within your own subtree only — an agency can never edit a sibling or its parent",
      "Platform administrators can move an entity between parents; agency admins cannot",
      "Deactivation is blocked while active policies, in-flight applications or unsettled commissions exist",
      "TIN and similar identifiers are stored masked and viewable only with the sensitive-data permission",
    ],
    drawer: [
      "Context: entity, its type and its parent",
      "Summary: children count, agents count, active products",
      "Guidance: inheritance — what a child gets from this entity automatically",
      "Help & FAQ: agency vs branch vs partner",
      "Audit: identity changes, parent changes, status changes",
      "Next actions: view relationship graph, add agents, configure marketplace",
    ],
    assistant: "Explains inheritance and what changing a parent will affect. It cannot create or move entities.",
    source: SRC,
    assumptions: ["Every user, quote, policy and commission row belongs to exactly one owning entity; the hierarchy is a tree, not an arbitrary graph."],
    canvas: [
      { title: "Identity", id: "ENT-ID", kind: "fields", items: ["Legal name", "DBA", "Entity type", "Agency NPN", "TIN (masked)", "Status"], wide: true },
      { title: "Parent relationship", id: "ENT-PARENT", kind: "kv", items: ["Parent entity", "Relationship type", "Effective from", "Inherited configuration count"] },
      { title: "Contacts & addresses", id: "ENT-CONTACT", kind: "list", items: ["Principal contact", "Compliance contact", "Business address", "Mailing address"] },
      { title: "Children", id: "ENT-CHILDREN", kind: "table", items: ["Child entity", "Type", "Agents", "Status", "Created"], wide: true },
      { title: "Deactivation guard", id: "ENT-DEACT", kind: "box", note: "Deactivation is blocked while dependent records exist. The screen lists exactly what blocks it rather than failing silently." },
    ],
  },
  {
    id: "SCR_ENTITY_GRAPH",
    slug: "entity-graph",
    name: "Relationship Graph",
    group: "Agency & agent management",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agency admin, platform administrator, compliance reviewer",
    purpose:
      "Visualises the entity tree and the non-hierarchical relationships layered on it — upline, downline, partner and paper-sharing links — so a user can see exactly why they can or cannot see a record.",
    actions: ["Expand and collapse the tree", "Focus on an entity", "Toggle relationship overlays", "Trace a visibility path to a record", "Export the graph", "Open an entity"],
    objects: ["Entity tree", "Relationship edges (parent, upline, partner, paper-sharing)", "Visibility path trace", "Entity summary card"],
    config: ["Which relationship types render as overlays", "Depth limit for the default view", "Whether partner entities are visible to downline agencies"],
    acl: [
      "You see only your own subtree plus entities you have an explicit relationship with — the graph itself is ACL-filtered, not merely display-filtered",
      "Sibling agencies are absent from the graph, not greyed out",
      "Visibility path trace is available to compliance reviewers for any entity in scope",
    ],
    drawer: [
      "Context: focused entity",
      "Summary: direct children, total descendants, relationship edges",
      "Guidance: hierarchy governs data scope; relationships govern paper and revenue",
      "Help & FAQ: why can I not see this agency",
      "Audit: relationship additions and removals",
      "Next actions: open entity, open appointments, trace visibility",
    ],
    assistant: "Answers 'why can I see this record' or 'why can I not' by returning the traced path. It states the rule, it does not grant access.",
    source: SRC,
    assumptions: ["Data visibility follows the entity tree; paper and revenue relationships are separate edges that never silently widen data visibility."],
    canvas: [
      { title: "Graph canvas", id: "GRAPH-CANVAS", kind: "tree", items: ["Parent agency", "Downline agency", "Branch", "Partner entity (overlay edge)", "Paper-sharing edge (overlay)"], wide: true },
      { title: "Overlays", id: "GRAPH-OVERLAY", kind: "actions", items: ["Hierarchy", "Upline / downline", "Partner", "Paper sharing", "Revenue split"] },
      { title: "Entity card", id: "GRAPH-CARD", kind: "kv", items: ["Entity", "Type", "Agents", "Active policies", "Products enabled"] },
      { title: "Visibility trace", id: "GRAPH-TRACE", kind: "list", items: ["Record selected", "Rule that grants access", "Entity path", "Result: visible / not visible"], wide: true },
    ],
  },
  {
    id: "SCR_AGENT_SETUP",
    slug: "agent-setup",
    name: "Agent / Producer Setup",
    group: "Agency & agent management",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agency admin; platform administrator for cross-agency cases",
    purpose:
      "Creates and maintains a producer: identity, home entity, NPN, roles, product access and status — the record every quote, application and commission attribution points at.",
    actions: ["Invite or create an agent", "Assign roles from templates", "Set home entity", "Grant product access", "Record NPN", "Suspend or terminate", "Transfer an agent's book"],
    objects: ["User / producer record", "Home entity and additional entity access", "NPN", "Role assignments", "Product access grants", "License records", "Appointment records", "Assigned leads and policies"],
    config: [
      "Role templates available to assign",
      "Whether an agent may belong to more than one entity",
      "Product access defaults on creation",
      "Onboarding requirements before an agent may quote or write",
    ],
    acl: [
      "user.manage within your own subtree; agents can never edit their own roles or product access",
      "Quoting requires an active license in the consumer's state; writing additionally requires an appointment on the selling paper",
      "Termination does not delete the record — attribution and commissions must survive it",
      "Book transfer is a separately permissioned, fully audited action",
    ],
    drawer: [
      "Context: agent, home entity, status",
      "Summary: licenses active/expiring, appointments, assigned book size",
      "Guidance: what this agent can and cannot do right now, and why",
      "Help & FAQ: license vs appointment",
      "Audit: role, access, status and transfer history",
      "Next actions: add license, request appointment, transfer book",
    ],
    assistant: "Explains readiness: what is missing before this agent can quote or write in a given state.",
    source: SRC,
    assumptions: ["An agent has one home entity for attribution, with optional additional read access to other entities."],
    m1Seam: "Module 1 agent quick quote (UX-017, UX-018) depends on this record and its license state. Module 1 is unchanged.",
    canvas: [
      { title: "Identity", id: "AGT-ID", kind: "fields", items: ["Name", "Email", "Phone", "NPN", "Home entity", "Status"], wide: true },
      { title: "Roles", id: "AGT-ROLES", kind: "list", items: ["Assigned role template", "Effective permissions summary", "Local overrides applied"] },
      { title: "Product access", id: "AGT-PRODUCTS", kind: "table", items: ["Product", "Quote", "Write", "Granted by", "Effective"] },
      { title: "Readiness", id: "AGT-READY", kind: "checks", items: ["Onboarding complete", "Active license in at least one state", "Appointment on at least one paper", "Required training recorded"], wide: true },
    ],
  },
  {
    id: "SCR_AGENT_LICENSE",
    slug: "agent-license",
    name: "License Record",
    group: "Agency & agent management",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agency admin, compliance reviewer, the agent themselves (read-only)",
    purpose:
      "The per-state license register for a producer: number, lines of authority, dates and verification state — the record that gates quoting and writing and drives expiry warnings.",
    actions: ["Add a license", "Edit a license", "Upload evidence", "Mark verified", "Trigger re-verification", "View expiring licenses", "Export a license report"],
    objects: ["License record", "State and lines of authority", "Issue and expiry dates", "Verification source and date", "Evidence document", "Blocking impact list"],
    config: [
      "Whether verification is manual or via an external source",
      "Expiry warning thresholds",
      "Whether an expired license blocks quoting, writing, or both",
      "Lines of authority taxonomy",
    ],
    acl: [
      "license.manage for agency admins in their subtree; agents may view their own and upload evidence but never mark verified",
      "Verification state is never self-asserted by the agent",
      "License numbers are treated as sensitive and masked in lists",
    ],
    drawer: [
      "Context: agent and selected license",
      "Summary: states licensed, expiring within threshold, unverified count",
      "Guidance: what an expiry will block and when",
      "Help & FAQ: resident vs non-resident license",
      "Audit: additions, edits, verification events",
      "Next actions: verify, upload evidence, notify agent",
    ],
    assistant: "Explains what an expiring license will block and by when. It cannot verify a license.",
    source: SRC,
    assumptions: ["External license verification is an integration seam; Phase 1 supports manual verification with evidence as the baseline."],
    canvas: [
      { title: "Licenses", id: "LIC-TABLE", kind: "table", items: ["State", "License number (masked)", "Lines of authority", "Issued", "Expires", "Verified", "Source"], wide: true },
      { title: "Expiry warnings", id: "LIC-EXPIRY", kind: "list", items: ["Expiring in 30 days", "Expiring in 60 days", "Expired — blocking"] },
      { title: "Evidence", id: "LIC-EVIDENCE", kind: "box", note: "Uploaded license evidence, viewable under the sensitive-document rules. Every view is logged." },
      { title: "Blocking impact", id: "LIC-IMPACT", kind: "box", note: "Lists the states, products and in-flight applications an expiry will block, so the agency can act before it bites.", wide: true },
    ],
  },
  {
    id: "SCR_AGENT_APPT_ACCESS",
    slug: "agent-appointment-access",
    name: "Appointment Access (Agent View)",
    group: "Agency & agent management",
    workspace: WS,
    module: "MOD_AGENCY_ENTITY + MOD_APPOINTMENTS_PAPER (nested)",
    packet: "M2-Cand",
    shell: "internal",
    user: "Agency admin and the agent, read-mostly",
    purpose:
      "Shows which carrier papers a producer may actually write on, where that right comes from — own appointment or granted access to another entity's paper — and what it permits.",
    actions: ["View appointments by carrier", "Request access to a paper", "View the granting relationship", "See what each appointment permits", "Escalate a missing appointment"],
    objects: ["Carrier appointment record", "Paper owner entity", "Access grant", "Permitted products and states", "Request record"],
    config: ["Whether agents may request paper access directly or only through their agency admin", "Which carriers require appointment before quoting, not just writing"],
    acl: [
      "Read for the agent; appointment.manage and paper.grant sit with the paper-owning entity, never the requester",
      "An agent never sees another entity's appointment terms — only the fact that access was granted and its scope",
      "Writing without a valid appointment is blocked at submission readiness, not merely warned",
    ],
    drawer: [
      "Context: agent, carrier and paper",
      "Summary: appointments active, access granted, gaps by state",
      "Guidance: own appointment vs granted paper access",
      "Help & FAQ: why can I quote but not submit this carrier",
      "Audit: grants, revocations and requests",
      "Next actions: request access, escalate, view carrier record",
    ],
    assistant: "Explains exactly why a carrier is unavailable to this agent and what request would fix it.",
    source: SRC,
    assumptions: ["Paper access is granted entity-to-entity; individual agents inherit it through their entity rather than holding it personally."],
    canvas: [
      { title: "By carrier", id: "APPT-CARRIER", kind: "table", items: ["Carrier", "Paper owner", "Source: own / granted", "States", "Products", "Status"], wide: true },
      { title: "Gaps", id: "APPT-GAPS", kind: "list", items: ["Licensed but not appointed", "Appointed but product not enabled", "Access request pending"] },
      { title: "Request access", id: "APPT-REQUEST", kind: "actions", items: ["Request to write on paper", "Escalate to agency admin", "View request status"] },
      { title: "Enforcement note", id: "APPT-ENFORCE", kind: "box", note: "Appointment validity is re-checked at submission release. A stale grant cannot be used to submit.", wide: true },
    ],
  },
  {
    id: "SCR_ACL_TEMPLATES",
    slug: "acl-role-templates",
    name: "Role & Permission Templates",
    group: "Agency & agent management",
    workspace: "WS_PLATFORM (authoring) — WS_AGENCY assigns from published templates",
    module: "MOD_ADMIN_CONFIG + MOD_AGENCY_ENTITY",
    packet: "P1-Later",
    shell: "internal",
    user: "Platform administrator authoring templates; agency admin assigning them",
    purpose:
      "Defines reusable roles as permission bundles inside global guardrails, so agencies assign coherent roles instead of hand-building permission sets per user.",
    actions: ["Create a template", "Add or remove permissions", "Mark permissions as locked (non-overridable)", "Publish a template", "Compare two templates", "See who holds a template"],
    objects: ["Role template", "Permission catalog", "Locked permission set", "Assignment count", "Template version"],
    config: [
      "Permission catalog grouped by module",
      "Which permissions are platform-only and never delegable",
      "Which permissions an agency may locally override",
      "Template visibility per agency tier",
    ],
    acl: [
      "acl.template.manage is platform-only",
      "Permissions marked locked cannot be granted or removed by any local override — this is the global guardrail",
      "Templates conferring sensitive-data or commission visibility require a second approver to publish",
    ],
    drawer: [
      "Context: template and its publish state",
      "Summary: permission count, locked count, holders",
      "Guidance: least privilege — start from the narrowest template",
      "Help & FAQ: template vs local override",
      "Audit: template edits, publishes and mass reassignments",
      "Next actions: publish, compare, view holders",
    ],
    assistant: "Explains the practical effect of a permission and where it is enforced.",
    source: SRC,
    assumptions: ["Permissions are a fixed platform catalog; agencies compose and narrow, never invent new permissions."],
    canvas: [
      { title: "Templates", id: "TPL-LIST", kind: "table", items: ["Template", "Tier", "Permissions", "Locked", "Holders", "Version"], wide: true },
      { title: "Permission matrix", id: "TPL-MATRIX", kind: "table", items: ["Module", "Permission", "Included", "Locked", "Platform-only"], wide: true },
      { title: "Guardrail note", id: "TPL-GUARD", kind: "box", note: "Locked permissions are the global guardrail: no agency configuration, local override or feature flag can grant them." },
      { title: "Holders", id: "TPL-HOLDERS", kind: "list", items: ["Entity", "User count", "Assigned by", "Assigned at"] },
    ],
  },
  {
    id: "SCR_ACL_OVERRIDES",
    slug: "acl-local-overrides",
    name: "Local ACL Overrides & Data Visibility by Hierarchy",
    group: "Agency & agent management",
    workspace: WS,
    module: "MOD_ADMIN_CONFIG + MOD_AGENCY_ENTITY",
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin; platform administrator auditing",
    purpose:
      "Where an agency narrows or, within allowance, widens permissions for its own users and sets how far up and down the hierarchy each role can see data — with the resolved effective permission always shown.",
    actions: ["Add an override", "Set data visibility scope for a role", "Simulate effective permissions for a user", "Remove an override", "Export the effective ACL matrix"],
    objects: ["Local override", "Data visibility scope (own / entity / subtree / explicit relationships)", "Effective permission resolution", "Simulation result", "Override audit trail"],
    config: [
      "Which permissions are locally overridable at all",
      "Data visibility scopes available per role",
      "Whether downline data is visible to an upline by default",
      "Sensitive-field visibility per role (SSN, TIN, commission amounts, license numbers)",
    ],
    acl: [
      "acl.override.manage inside your own subtree only",
      "An override can never exceed the template's locked set nor the platform guardrail — attempts are refused with the blocking rule shown",
      "Granting oneself a permission is blocked; overrides affecting the acting user require another admin",
      "Every override is attributed and appears in the audit report",
    ],
    drawer: [
      "Context: entity, role and override under edit",
      "Summary: overrides in effect, refused attempts",
      "Guidance: prefer a narrower template over a widening override",
      "Help & FAQ: why did my override get refused",
      "Audit: full override history",
      "Next actions: simulate a user, export matrix, remove override",
    ],
    assistant: "Runs the 'what can this user actually see' explanation and names the deciding rule.",
    source: SRC,
    assumptions: ["Effective permission is computed as template minus local narrowing plus permitted local widening, bounded by platform guardrails."],
    canvas: [
      { title: "Overrides", id: "OVR-LIST", kind: "table", items: ["Role", "Permission", "Override", "Reason", "Set by", "Effective"], wide: true },
      { title: "Data visibility", id: "OVR-VIS", kind: "list", items: ["Own records only", "Own entity", "Entity subtree", "Explicit relationships only", "Sensitive fields masked"] },
      { title: "Effective simulation", id: "OVR-SIM", kind: "fields", items: ["User", "Entity context", "Workspace"], note: "Returns the resolved permission set, the data scope, and which rule decided each line." },
      { title: "Refusal log", id: "OVR-REFUSE", kind: "box", note: "Attempts that exceeded a guardrail are recorded with the rule that refused them — silent failure is not acceptable here.", wide: true },
    ],
  },
]);
