import { SRC_BLUEPRINT, SRC_IA, SRC_NORTH, screens } from "./types";

const WS = "WS_PLATFORM (governance) — WS_AGENCY for tenant-level enablement within guardrails";
const MOD = "MOD_AI (nested — an overlay, not a default top-level menu)";
const SRC = `${SRC_BLUEPRINT} (AI overlay, Plan-O controls, governance); ${SRC_NORTH} (AI posture, guardrails, escalation); ${SRC_IA} (SCR_AI_*)`;

export const AI = screens([
  {
    id: "SCR_AI_PLANO",
    slug: "ai-plano-controls",
    name: "Plan-O Controls",
    group: "AI, Plan-O & governance",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Platform AI governance administrator; agency admin with limited, bounded controls",
    purpose:
      "Governs the recommendation engine behind Plan-O: which inputs it may use, how they are weighted, what it must disclose, and what it is forbidden from doing — with versioning so any past recommendation can be explained.",
    actions: [
      "View the active ruleset version",
      "Adjust permitted weightings within bounds",
      "Add or remove an input",
      "Set the disclosure text",
      "Simulate a ranking",
      "Publish a ruleset version",
      "Roll back",
    ],
    objects: [
      "Plan-O ruleset version",
      "Permitted input set (household, usage expectations, provider and drug preferences, total-cost assumptions)",
      "Forbidden input set (commission, agency preference, carrier incentive)",
      "Weighting configuration and bounds",
      "Ranking-basis disclosure text",
      "Simulation result",
    ],
    config: [
      "Which inputs an agency may weight and the permitted range",
      "Whether an agency may adjust anything at all or only view",
      "Ranking-basis disclosure copy",
      "Whether Plan-O is enabled per marketplace",
    ],
    acl: [
      "ai.govern is platform-level; agency adjustment is a bounded, separately granted permission",
      "Commission, carrier incentive and agency preference are structurally excluded as inputs — this is a hard guardrail, not a default setting",
      "Publishing a ruleset requires a second approver and is fully versioned",
    ],
    drawer: [
      "Context: ruleset version, marketplace scope",
      "Summary: inputs in use, weightings, publish state",
      "Guidance: what must be disclosed to the consumer about ranking",
      "Help & FAQ: recommendation vs advice",
      "Audit: ruleset changes, publishes, rollbacks with approver",
      "Next actions: simulate, publish, roll back",
    ],
    assistant:
      "Explains how a simulated ranking was produced. It cannot change weightings or publish.",
    source: SRC,
    assumptions: [
      "Every Plan-O result is explainable from its ruleset version; recommendations are never produced by an unversioned or opaque process.",
    ],
    m1Seam:
      "Governs the ranking behind Module 1's Plan-O panel (UX-005, UX-009). Those screens and their inline 'why this plan' disclosure are unchanged.",
    canvas: [
      {
        title: "Ruleset version",
        id: "PLO-VER",
        kind: "kv",
        items: ["Version", "Published at", "Approver", "Marketplaces using it", "Rollback target"],
        wide: true,
      },
      {
        title: "Permitted inputs",
        id: "PLO-INPUTS",
        kind: "table",
        items: ["Input", "Source", "Weight", "Permitted range", "Agency adjustable"],
        wide: true,
      },
      {
        title: "Forbidden inputs",
        id: "PLO-FORBID",
        kind: "checks",
        items: [
          "Commission or revenue to the agency",
          "Carrier incentive or bonus qualification",
          "Agency plan preference",
          "Anything not disclosed to the consumer",
        ],
        wide: true,
      },
      {
        title: "Ranking disclosure",
        id: "PLO-DISCLOSE",
        kind: "editor",
        items: ["Consumer-facing ranking-basis statement", "Why this plan explainer template"],
      },
      {
        title: "Simulation",
        id: "PLO-SIM",
        kind: "fields",
        items: ["Household", "Usage expectation", "Providers", "Drugs", "ZIP"],
        note: "Returns the ranked set with the contribution of each input, so an author can verify explainability.",
      },
    ],
  },
  {
    id: "SCR_AI_GOVERNANCE",
    slug: "ai-governance-record",
    name: "AI Governance Record",
    group: "AI, Plan-O & governance",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Platform AI governance administrator, compliance reviewer, auditor",
    purpose:
      "The registry of every AI capability in ABox: what it does, what it may act on, which model or ruleset version is live, who approved it, what its guardrails are, and how it is reviewed — the document a carrier or regulator asks for.",
    actions: [
      "Register a capability",
      "Record its purpose and scope",
      "Attach guardrails",
      "Record approval",
      "Set the review cadence",
      "Suspend a capability",
      "Export the governance record",
    ],
    objects: [
      "AI capability record",
      "Purpose and permitted scope statement",
      "Model or ruleset version reference",
      "Guardrail set",
      "Approval and review records",
      "Suspension record",
      "Human-in-the-loop requirement",
    ],
    config: [
      "Capability catalog and their classifications by risk",
      "Guardrail library",
      "Review cadence per risk class",
      "Whether a capability may ever act without human confirmation",
    ],
    acl: [
      "ai.govern platform-only; compliance reviewers get read plus the ability to raise a review",
      "No capability can be enabled without a recorded approval and an assigned owner",
      "Any capability whose output can reach a consumer or change a record must have human-in-the-loop set, and this cannot be waived",
    ],
    drawer: [
      "Context: capability, risk class, live version",
      "Summary: guardrails attached, last review, human-in-the-loop state",
      "Guidance: what registration requires before enablement",
      "Help & FAQ: risk classification",
      "Audit: registrations, approvals, suspensions, reviews",
      "Next actions: review, suspend, export record",
    ],
    assistant:
      "Explains a capability's declared scope and guardrails. It cannot register or approve capabilities — no AI approves AI.",
    source: SRC,
    assumptions: [
      "The North Star AI posture requires that every AI capability is registered and owned before it is enabled; unregistered AI is not permitted to run.",
    ],
    canvas: [
      {
        title: "Capability registry",
        id: "GOV-REG",
        kind: "table",
        items: [
          "Capability",
          "Surface",
          "Risk class",
          "Live version",
          "Owner",
          "Human-in-the-loop",
          "Last review",
          "Status",
        ],
        wide: true,
      },
      {
        title: "Scope statement",
        id: "GOV-SCOPE",
        kind: "box",
        note: "What the capability is for, what data it may read, what it may produce, and what it is explicitly forbidden from doing.",
      },
      {
        title: "Guardrails",
        id: "GOV-GUARD",
        kind: "checks",
        items: [
          "No advice phrasing",
          "No eligibility determination",
          "No coverage or cost guarantee",
          "No unmasked PII in output",
          "Required disclosure attached",
          "Human confirmation before consumer delivery",
        ],
      },
      {
        title: "Approval & review",
        id: "GOV-APPROVE",
        kind: "timeline",
        items: [
          "Registered",
          "Approved by governance",
          "Enabled",
          "Scheduled review",
          "Version updated with re-approval",
        ],
        wide: true,
      },
    ],
  },
  {
    id: "SCR_AI_LOG",
    slug: "ai-interaction-log",
    name: "AI Interaction Log",
    group: "AI, Plan-O & governance",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Compliance reviewer, agency admin (own entity), platform governance",
    purpose:
      "Every AI interaction, end to end: what was asked, what context it read, what it produced, which guardrails fired, what the human decided, and whether it reached a consumer.",
    actions: [
      "Filter by surface, capability or outcome",
      "Open an interaction",
      "View the guardrail results",
      "Flag an interaction for review",
      "Export for audit",
      "Trace to the affected record",
    ],
    objects: [
      "Interaction record",
      "Capability and version",
      "Context read (record references, not raw sensitive values)",
      "Output and its classification",
      "Guardrail evaluation results",
      "Human decision (confirmed, edited, rejected with reason)",
      "Delivery outcome",
    ],
    config: [
      "Retention period for interaction records",
      "Whether full prompt/output content is retained or summarised",
      "Which outcomes auto-flag for review",
      "Sampling rate for proactive quality review",
    ],
    acl: [
      "ai.log.view; agency admins see only their own entity's interactions",
      "Records are append-only — no role can edit or delete an interaction record",
      "Interaction content containing member data is masked without the sensitive-data permission",
      "Rejected outputs are retained with their reason and never purged early",
    ],
    drawer: [
      "Context: interaction, capability, surface and actor",
      "Summary: guardrail results and human decision",
      "Guidance: how to judge whether an output was appropriate",
      "Help & FAQ: what happens to a rejected output",
      "Audit: this log is itself part of the audit trail",
      "Next actions: flag for review, trace to record, export",
    ],
    assistant:
      "Helps locate interactions matching a concern. It cannot alter or hide records, including its own.",
    source: SRC,
    assumptions: [
      "Every consumer-reaching AI output has a corresponding human decision record; an interaction with no decision and a consumer delivery is treated as a defect.",
    ],
    canvas: [
      {
        title: "Filters",
        id: "LOG-FILTER",
        kind: "actions",
        items: [
          "Surface",
          "Capability",
          "Guardrail fired",
          "Human decision",
          "Reached consumer",
          "Date range",
        ],
        wide: true,
      },
      {
        title: "Interaction grid",
        id: "LOG-GRID",
        kind: "table",
        items: [
          "When",
          "Surface",
          "Capability / version",
          "Actor",
          "Guardrails",
          "Decision",
          "Reached consumer",
        ],
        wide: true,
      },
      {
        title: "Interaction detail",
        id: "LOG-DETAIL",
        kind: "list",
        items: [
          "Request context (record references)",
          "Output (classified)",
          "Guardrail results",
          "Edits made by the human",
          "Decision and reason",
        ],
      },
      {
        title: "Append-only note",
        id: "LOG-APPEND",
        kind: "box",
        note: "Append-only. Rejected outputs are retained with their rejection reason and are never silently discarded.",
        wide: true,
      },
    ],
  },
  {
    id: "SCR_AI_ENABLE",
    slug: "ai-enablement",
    name: "AI Enable / Disable by Tenant & Module, with Role Limits",
    group: "AI, Plan-O & governance",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Platform AI governance administrator; agency admin within delegated bounds",
    purpose:
      "The switchboard: which AI capabilities are on for which tenant, in which module, for which roles — so an agency can adopt AI at its own pace and a platform can withdraw a capability instantly.",
    actions: [
      "Enable or disable a capability per tenant",
      "Scope a capability to specific modules",
      "Limit a capability by role",
      "Set a tenant to advisory-only mode",
      "Kill-switch all AI for a tenant",
      "View the effective state",
    ],
    objects: [
      "Enablement matrix (tenant × capability × module × role)",
      "Advisory-only mode flag",
      "Kill-switch state",
      "Effective-state resolution",
      "Change record",
    ],
    config: [
      "Which capabilities a tenant may self-enable vs which require platform action",
      "Role limits available per capability",
      "Advisory-only mode semantics (suggests but cannot draft consumer-facing output)",
      "Whether consumer-facing AI is permitted for the tenant at all",
    ],
    acl: [
      "Platform holds the kill-switch and cannot be overridden by any tenant configuration",
      "A tenant can only narrow within what the platform has permitted — never widen",
      "When a capability is disabled, its entry points are absent from the UI, not greyed out",
      "Changes here take effect immediately and are audited with actor and reason",
    ],
    drawer: [
      "Context: tenant, capability and module scope",
      "Summary: enabled capabilities, role limits, advisory-only state",
      "Guidance: what disabling a capability removes from the UI",
      "Help & FAQ: advisory-only mode explained",
      "Audit: enablement changes and kill-switch events",
      "Next actions: adjust scope, set role limits, kill-switch",
    ],
    assistant:
      "Reports the effective state for a tenant and role. It cannot change its own enablement.",
    source: SRC,
    assumptions: [
      "AI is opt-in per tenant per capability; there is no platform-wide default that a tenant cannot refuse.",
    ],
    canvas: [
      {
        title: "Enablement matrix",
        id: "ENB-MATRIX",
        kind: "table",
        items: ["Capability", "Tenant", "Modules", "Roles permitted", "Consumer-facing", "State"],
        wide: true,
      },
      {
        title: "Modes",
        id: "ENB-MODES",
        kind: "actions",
        items: ["Full", "Advisory-only", "Internal-only", "Disabled"],
      },
      {
        title: "Kill switch",
        id: "ENB-KILL",
        kind: "box",
        note: "Platform-held. Disables every AI capability for the tenant immediately, including the assistant, and records the reason.",
      },
      {
        title: "Effective state",
        id: "ENB-EFF",
        kind: "fields",
        items: ["Tenant", "Role", "Module"],
        note: "Returns exactly which AI surfaces that user will see and which rule decided each one.",
      },
    ],
  },
  {
    id: "SCR_AI_KNOWLEDGE",
    slug: "ai-knowledge-disclaimers",
    name: "Knowledge Source Control, Disclaimers & Escalation",
    group: "AI, Plan-O & governance",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Platform AI governance administrator, agency admin for their own help content, compliance reviewer",
    purpose:
      "Controls what the assistant is allowed to know and say: the approved knowledge sources per surface, the disclaimers that attach to every answer, and the escalation path to a licensed human when a question crosses the advice line.",
    actions: [
      "Add or approve a knowledge source",
      "Scope a source to surfaces and audiences",
      "Author or edit disclaimers",
      "Define escalation triggers",
      "Set the escalation target",
      "Test a question against the configured knowledge",
      "Retire a source",
    ],
    objects: [
      "Knowledge source (page guidance, FAQ set, product documentation, policy documents)",
      "Source scope (surface, audience, tenant)",
      "Disclaimer text blocks",
      "Escalation trigger set",
      "Escalation target (agent queue, scheduling, callback request)",
      "Test result with cited sources",
    ],
    config: [
      "Which sources are platform-approved vs agency-authored",
      "Whether the assistant may answer from anything outside the approved set (default: no)",
      "Disclaimer text per surface and audience",
      "Escalation triggers: advice-seeking, eligibility, cost guarantee, complaint, distress, repeated failure to answer",
      "Escalation routing and hours",
    ],
    acl: [
      "Knowledge approval is platform-gated for consumer-facing surfaces; agencies may author their own internal help content",
      "Disclaimer text is compliance-controlled and requires a second approver",
      "The assistant must cite its source internally for every answer so an auditor can verify grounding",
      "No agency configuration can remove an escalation trigger or a required disclaimer",
    ],
    drawer: [
      "Context: surface, audience and approved source set",
      "Summary: sources active, disclaimers attached, escalation triggers",
      "Guidance: the advice line and where escalation is mandatory",
      "Help & FAQ: grounded answers explained",
      "Audit: source approvals, disclaimer changes, escalation events",
      "Next actions: test a question, approve a source, adjust escalation",
    ],
    assistant:
      "This screen configures the assistant itself. In testing, the assistant answers only from approved sources, cites them, and demonstrates escalation rather than attempting an answer when a trigger fires.",
    source: SRC,
    assumptions: [
      "The assistant is grounded: no answer is produced from general model knowledge on a consumer-facing surface, and an unanswerable question escalates rather than improvises.",
    ],
    m1Seam:
      "Supplies the help, FAQ and page-guidance content that Module 1's drawer and help bubble render, and the escalation that feeds UX-022. Those screens are unchanged.",
    canvas: [
      {
        title: "Knowledge sources",
        id: "KNW-SOURCES",
        kind: "table",
        items: ["Source", "Type", "Surfaces", "Audience", "Approved by", "Version", "Status"],
        wide: true,
      },
      {
        title: "Grounding rule",
        id: "KNW-GROUND",
        kind: "box",
        note: "Consumer-facing answers come only from approved sources. An out-of-scope question escalates; it is never improvised.",
        wide: true,
      },
      {
        title: "Disclaimers",
        id: "KNW-DISC",
        kind: "editor",
        items: [
          "Not-advice disclaimer",
          "Estimate disclaimer",
          "AI-generated content notice",
          "Licensed-agent availability notice",
        ],
      },
      {
        title: "Escalation",
        id: "KNW-ESC",
        kind: "list",
        items: [
          "Trigger: request for a recommendation framed as advice",
          "Trigger: eligibility or subsidy determination question",
          "Trigger: cost or coverage guarantee",
          "Trigger: complaint or distress",
          "Target: licensed agent queue or callback request",
          "Out-of-hours behaviour",
        ],
      },
      {
        title: "Grounding test",
        id: "KNW-TEST",
        kind: "fields",
        items: ["Surface", "Audience", "Question"],
        note: "Returns the answer, the cited sources, the disclaimers attached, and whether escalation fired.",
      },
    ],
  },
]);
