import { SRC_BLUEPRINT, SRC_IA, SRC_RECON, screens } from "./types";

const WS = "WS_AGENCY and WS_PLATFORM — branded templates render into consumer and member surfaces";
const MOD = "MOD_COMMUNICATIONS";
const SRC = `${SRC_BLUEPRINT} (email/SMS/in-app templates, event and time based triggers, consent, branded templates); ${SRC_IA} (SCR_COMMS_*); ${SRC_RECON} — Module 1 has minimal notification config only (UX-025)`;

export const COMMS = screens([
  {
    id: "SCR_COMMS_TEMPLATES",
    slug: "comms-templates",
    name: "Email / SMS / In-App Templates",
    group: "Notifications, comms & scheduling",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, platform communications administrator",
    purpose:
      "The template library across all three channels, with the merge fields, branding and approval state each template carries before it can be sent to a consumer.",
    actions: [
      "Create a template",
      "Choose channel",
      "Insert merge fields",
      "Apply brand theme",
      "Preview per channel and per brand",
      "Submit for approval",
      "Publish",
      "Retire",
    ],
    objects: [
      "Template",
      "Channel variant",
      "Merge field set",
      "Brand theme binding",
      "Approval record",
      "Template version",
    ],
    config: [
      "Channels enabled per agency",
      "Merge fields available per template type (from the canonical object model)",
      "Brand theme inheritance from the marketplace/tenant",
      "Whether agency admins may author or only adopt platform templates",
      "Required footer content per channel (unsubscribe, licensure, opt-out keywords)",
    ],
    acl: [
      "comms.template.manage; templates that reach consumers require approval by a separate approver",
      "Merge fields resolving sensitive attributes are unavailable in consumer-facing templates",
      "SMS templates cannot be published without the required opt-out language — enforced, not advisory",
    ],
    drawer: [
      "Context: template, channel and brand",
      "Summary: version, approval state, usage count",
      "Guidance: channel constraints and required footer content",
      "Help & FAQ: merge field availability",
      "Audit: edits, approvals and publishes",
      "Next actions: preview, submit for approval, publish",
    ],
    assistant:
      "Drafts template copy on request; nothing it drafts is published without human review and approval.",
    source: SRC,
    assumptions: [
      "In-app notifications are templated with the same object so a single event can fan out consistently across channels.",
    ],
    m1Seam:
      "Module 1's minimal notification configuration (UX-025) selects from templates defined here. UX-025 itself is unchanged.",
    canvas: [
      {
        title: "Template list",
        id: "TPL-LIST",
        kind: "table",
        items: ["Template", "Channel", "Purpose", "Brand", "Approval", "Version", "Usage"],
        wide: true,
      },
      {
        title: "Editor",
        id: "TPL-EDIT",
        kind: "editor",
        items: [
          "Subject / header",
          "Body with merge fields",
          "Call to action",
          "Required footer block (locked)",
        ],
        wide: true,
      },
      {
        title: "Merge fields",
        id: "TPL-MERGE",
        kind: "list",
        items: [
          "Member first name",
          "Agency display name",
          "Quote reference",
          "Application status",
          "Agent name and contact",
        ],
      },
      {
        title: "Channel constraints",
        id: "TPL-CONSTRAINT",
        kind: "checks",
        items: [
          "SMS length and opt-out language",
          "Email unsubscribe and physical address",
          "In-app character budget",
          "Brand theme applied",
        ],
      },
    ],
  },
  {
    id: "SCR_COMMS_TRIGGERS",
    slug: "comms-event-triggers",
    name: "Event-Based Triggers & Task Creation",
    group: "Notifications, comms & scheduling",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, platform communications administrator",
    purpose:
      "Binds platform events to outcomes: send a message, raise a task, or both — with audience, conditions and suppression, driven by the North Star event model rather than ad-hoc hooks.",
    actions: [
      "Create a trigger",
      "Select an event",
      "Set conditions",
      "Choose audience",
      "Attach a template",
      "Create a task instead of or alongside a message",
      "Set suppression rules",
      "Enable or disable",
    ],
    objects: [
      "Trigger definition",
      "Platform event type",
      "Condition set",
      "Audience resolver (member, agent, agency admin, referral source)",
      "Template binding",
      "Task template",
      "Suppression rule",
    ],
    config: [
      "Event catalog exposed to triggers (quote created, quote shared, application signed, submission status changed, document requested, policy issued, license expiring, commission period closed)",
      "Audience resolution rules",
      "Suppression: quiet hours, frequency caps, deduplication window",
      "Whether a trigger may create a task and to whom it routes",
    ],
    acl: [
      "comms.trigger.manage; triggers targeting consumers require an approved template",
      "A trigger can only address audiences the configuring entity is allowed to contact",
      "Consent state is evaluated at send time and always overrides the trigger",
    ],
    drawer: [
      "Context: trigger, event and audience",
      "Summary: sends in the last period, suppression hits, tasks created",
      "Guidance: event semantics — exactly when it fires",
      "Help & FAQ: why did a message not send",
      "Audit: trigger changes, enablement, and per-send decisions",
      "Next actions: test with a sample event, view send log, disable",
    ],
    assistant:
      "Explains why a specific message did or did not go out, naming the deciding rule (consent, suppression, audience).",
    source: SRC,
    assumptions: [
      "The event catalog comes from the North Star event model; triggers cannot invent events.",
    ],
    canvas: [
      {
        title: "Trigger",
        id: "TRG-DEF",
        kind: "fields",
        items: ["Name", "Event", "Conditions", "Audience", "Channel(s)", "Template", "Status"],
        wide: true,
      },
      {
        title: "Task action",
        id: "TRG-TASK",
        kind: "list",
        items: [
          "Create task",
          "Assign to: owning agent / queue / agency admin",
          "Due offset",
          "Priority",
        ],
      },
      {
        title: "Suppression",
        id: "TRG-SUPPRESS",
        kind: "checks",
        items: [
          "Respect quiet hours",
          "Frequency cap per member per period",
          "Deduplicate identical sends",
          "Consent required for this channel",
        ],
      },
      {
        title: "Send log",
        id: "TRG-LOG",
        kind: "table",
        items: ["Event at", "Recipient", "Channel", "Result", "Reason if not sent"],
        wide: true,
      },
    ],
  },
  {
    id: "SCR_COMMS_SCHEDULER",
    slug: "comms-scheduler",
    name: "Time-Based Scheduler, Recurring & Delayed Sends",
    group: "Notifications, comms & scheduling",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, marketing or operations user with comms permission",
    purpose:
      "Sends driven by time rather than an event: one-off scheduled sends, delays relative to an event, recurring campaigns and seasonal sequences such as open-enrollment reminders.",
    actions: [
      "Schedule a send",
      "Set a delay relative to an event",
      "Create a recurring schedule",
      "Define a multi-step sequence",
      "Pause or cancel",
      "View upcoming queue",
    ],
    objects: [
      "Schedule",
      "Recurrence rule",
      "Delay offset",
      "Sequence steps and exit conditions",
      "Audience snapshot vs live audience",
      "Upcoming send queue",
    ],
    config: [
      "Time zone handling — member local time vs agency time",
      "Recurrence patterns supported",
      "Audience evaluation: snapshot at schedule time or live at send time",
      "Sequence exit conditions (goal met, unsubscribed, status changed)",
      "Blackout dates",
    ],
    acl: [
      "comms.schedule.manage; recurring consumer campaigns need an approved template and, where applicable, marketing consent",
      "Cancelling another user's schedule requires an admin permission and is audited",
      "Audience size limits per period can be enforced per agency",
    ],
    drawer: [
      "Context: schedule, audience and next run",
      "Summary: upcoming sends, paused sequences",
      "Guidance: snapshot vs live audience and why it matters",
      "Help & FAQ: member local time behaviour",
      "Audit: schedule creation, pauses, cancellations",
      "Next actions: pause, edit, view queue",
    ],
    assistant: "Explains when a schedule will next fire and who will be in the audience.",
    source: SRC,
    assumptions: [
      "Delayed sends are cancelled automatically when the sequence exit condition is met before the delay elapses.",
    ],
    canvas: [
      {
        title: "Schedule types",
        id: "SCHD-TYPES",
        kind: "tabs",
        items: ["One-off", "Delayed after event", "Recurring", "Multi-step sequence"],
        wide: true,
      },
      {
        title: "Definition",
        id: "SCHD-DEF",
        kind: "fields",
        items: ["Template", "Audience", "Start", "Recurrence", "Time zone basis", "Blackout dates"],
        wide: true,
      },
      {
        title: "Sequence steps",
        id: "SCHD-STEPS",
        kind: "timeline",
        items: [
          "Day 0 — email",
          "Day 3 — SMS if no open",
          "Day 7 — task to agent",
          "Exit when application signed",
        ],
      },
      {
        title: "Upcoming queue",
        id: "SCHD-QUEUE",
        kind: "table",
        items: ["Scheduled at", "Template", "Audience size", "Channel", "Status"],
      },
    ],
  },
  {
    id: "SCR_COMMS_MANUAL",
    slug: "comms-manual-send",
    name: "Manual Messages & Shared Quote Notifications",
    group: "Notifications, comms & scheduling",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agent, agency admin",
    purpose:
      "Ad-hoc outbound contact from an agent to a lead or member, including the notification that accompanies a shared quote — logged to the record like every other communication, never sent from a personal channel outside ABox.",
    actions: [
      "Compose a message",
      "Start from a template",
      "Attach a quote or document",
      "Send now or schedule",
      "Log an off-platform contact",
      "View delivery status",
    ],
    objects: [
      "Message",
      "Recipient (lead or member)",
      "Attachment references",
      "Delivery and engagement events",
      "Communication record on the timeline",
      "Shared quote link",
    ],
    config: [
      "Which templates an agent may use ad hoc",
      "Whether free-text sends are permitted or template-only",
      "Attachment types allowed",
      "Whether shared-quote notifications may be customised by the agent",
    ],
    acl: [
      "Agents may contact only leads and members in their assignment or downline scope",
      "Consent state is enforced at send: a member who opted out of SMS cannot be SMS'd by any means in the platform",
      "Free-text consumer messages are retained in full for supervision",
      "Attaching a document requires access to that document",
    ],
    drawer: [
      "Context: recipient, their consent state, and prior contact",
      "Summary: last contact, channel preferences, opt-outs",
      "Guidance: what may and may not be said in a manual message",
      "Help & FAQ: logging an off-platform call",
      "Audit: message content, sender, delivery events",
      "Next actions: send, schedule, create follow-up task",
    ],
    assistant:
      "Can draft a message from context; the agent must review and send. Drafts inherit the required footer and disclosure content automatically.",
    source: SRC,
    assumptions: [
      "Every consumer-facing communication is expected to flow through ABox so the timeline is complete; off-platform contact is logged manually.",
    ],
    m1Seam:
      "Module 1 agent send-quote (UX-019) is the protected quote-sharing path. This screen generalises manual contact around it without altering UX-019.",
    canvas: [
      {
        title: "Recipient & consent",
        id: "MAN-RECIP",
        kind: "kv",
        items: [
          "Recipient",
          "Email consent",
          "SMS consent",
          "Marketing consent",
          "Preferred channel",
          "Last contacted",
        ],
        wide: true,
      },
      {
        title: "Composer",
        id: "MAN-COMPOSE",
        kind: "editor",
        items: [
          "Template selector",
          "Subject",
          "Body",
          "Attachment: quote / document",
          "Required footer (locked)",
        ],
        wide: true,
      },
      {
        title: "Shared quote notification",
        id: "MAN-SHARED",
        kind: "list",
        items: [
          "Quote reference and expiry",
          "Read-only link",
          "Recipient verification requirement",
          "Notification when the recipient opens it",
        ],
      },
      {
        title: "Log off-platform contact",
        id: "MAN-LOG",
        kind: "fields",
        items: ["Channel", "Direction", "Occurred at", "Summary"],
      },
    ],
  },
  {
    id: "SCR_COMMS_TIMELINE_CONSENT",
    slug: "comms-timeline-consent",
    name: "Communication Timeline & Consent Controls",
    group: "Notifications, comms & scheduling",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agent, agency admin, compliance reviewer",
    purpose:
      "The complete contact history for a person and the consent record that governs it — one place to answer 'what have we sent this member, on whose instruction, and what are we allowed to send next'.",
    actions: [
      "Filter the timeline by channel or outcome",
      "Open a message",
      "Record a consent change",
      "Process an opt-out",
      "Export the contact history",
      "Suppress all contact",
    ],
    objects: [
      "Communication timeline entries",
      "Consent records per channel and purpose with source and timestamp",
      "Opt-out and do-not-contact flags",
      "Delivery and engagement events",
      "Export record",
    ],
    config: [
      "Consent purposes tracked (transactional, servicing, marketing)",
      "Whether transactional messages continue after a marketing opt-out",
      "Retention period for message bodies",
      "Who may record a consent change on the member's behalf",
    ],
    acl: [
      "Timeline visibility follows the member record's ACL; message bodies containing sensitive data are masked without the sensitive-data permission",
      "Consent can be withdrawn by the member at any time through the member workspace, and that always wins over any agency configuration",
      "Do-not-contact is absolute and cannot be overridden by a trigger, a schedule or a manual send",
      "Exporting contact history is a logged, permissioned action",
    ],
    drawer: [
      "Context: member, consent state, active suppressions",
      "Summary: contacts by channel this period",
      "Guidance: transactional vs marketing and what an opt-out actually stops",
      "Help & FAQ: honouring an opt-out request",
      "Audit: consent changes with source, actor and timestamp",
      "Next actions: record consent change, suppress, export",
    ],
    assistant:
      "Summarises contact history and states plainly what may be sent next given consent. It cannot change consent.",
    source: SRC,
    assumptions: [
      "Consent is per channel and per purpose; a single global consent flag would not satisfy the blueprint's consent control requirement.",
    ],
    canvas: [
      {
        title: "Consent panel",
        id: "TMLN-CONSENT",
        kind: "table",
        items: ["Channel", "Purpose", "State", "Source", "Captured at", "Captured by"],
        wide: true,
      },
      {
        title: "Timeline",
        id: "TMLN-FEED",
        kind: "timeline",
        items: [
          "Quote shared — email delivered, opened",
          "Reminder — SMS delivered",
          "Inbound call logged by agent",
          "Marketing opt-out recorded by member",
          "Application status change — in-app notification",
        ],
        wide: true,
      },
      {
        title: "Suppression state",
        id: "TMLN-SUPPRESS",
        kind: "box",
        note: "Do-not-contact is absolute: triggers, schedules and manual sends are all blocked and the block is shown wherever a send is attempted.",
      },
      {
        title: "Export",
        id: "TMLN-EXPORT",
        kind: "actions",
        items: [
          "Export contact history",
          "Export consent record",
          "Print for a complaint response",
        ],
      },
    ],
  },
]);
