import { SRC_BLUEPRINT, SRC_IA, SRC_RECON, screens } from "./types";

const WS = "WS_AGENCY and WS_PLATFORM — every screen is ACL-gated by commission.view";
const MOD = "MOD_COMMISSIONS";
const SRC = `${SRC_BLUEPRINT} (commission schedules PMPM/PEPM/PCPM/flat, contingent categories, overrides, upline and super bonuses, statements, projections); ${SRC_IA} (SCR_COMM_*); ${SRC_RECON} — commissions are entirely outside Module 1`;

export const COMMISSIONS = screens([
  {
    id: "SCR_COMM_SCHEDULE",
    slug: "comm-schedule-setup",
    name: "Commission Schedule Setup",
    group: "Commissions & revenue",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Commission administrator (platform or agency, depending on who owns the schedule)",
    purpose:
      "Authors a commission schedule and every rate model the blueprint requires — PMPM, PEPM, PCPM, flat fee, percentage of premium — with its scope, effective dates and version history.",
    actions: [
      "Create a schedule",
      "Add a rate line per model",
      "Set scope (carrier, product, entity, agent tier)",
      "Set effective dates",
      "Version and publish",
      "Clone a schedule",
      "Simulate a rate line",
    ],
    objects: [
      "Commission schedule",
      "Rate line",
      "Rate model",
      "Scope binding",
      "Effective window",
      "Schedule version",
      "Assignment to entities and agents",
    ],
    config: [
      "Rate models enabled: PMPM (per member per month), PEPM (per employee per month), PCPM (per contract per month), flat fee, percentage of premium",
      "Basis definitions: what counts as a member, an employee, a contract",
      "Renewal-year differentiation",
      "Proration and mid-month rules",
      "Clawback rules on early termination",
    ],
    acl: [
      "commission.schedule.manage; publishing requires a second approver because schedules move money",
      "An agency may author schedules only for its own subtree and never above its own rate from the paper owner",
      "Rate values are hidden from anyone without commission.view, including within the same entity",
    ],
    drawer: [
      "Context: schedule, scope and version",
      "Summary: rate lines by model, entities assigned",
      "Guidance: which model fits which product line",
      "Help & FAQ: PMPM vs PEPM vs PCPM",
      "Audit: rate changes, publishes and approvers",
      "Next actions: simulate, assign, publish",
    ],
    assistant:
      "Explains what each rate model computes and the basis it uses. It cannot change rates.",
    source: SRC,
    assumptions: [
      "Percentage-of-premium is treated as a model alongside the per-unit models even though the request lists the per-unit ones explicitly; IFP commissions commonly need it.",
    ],
    canvas: [
      {
        title: "Schedule header",
        id: "SCH-HDR",
        kind: "fields",
        items: [
          "Schedule name",
          "Owner entity",
          "Carrier",
          "Products",
          "Effective from",
          "Effective to",
          "Version",
        ],
        wide: true,
      },
      {
        title: "Rate lines",
        id: "SCH-LINES",
        kind: "table",
        items: [
          "Model (PMPM / PEPM / PCPM / flat / % premium)",
          "Basis",
          "Rate",
          "Year 1 vs renewal",
          "Scope",
          "Proration rule",
        ],
        wide: true,
      },
      {
        title: "Basis definitions",
        id: "SCH-BASIS",
        kind: "kv",
        items: [
          "Member = enrolled covered life",
          "Employee = subscriber on a group contract",
          "Contract = policy regardless of covered lives",
        ],
      },
      {
        title: "Clawback",
        id: "SCH-CLAW",
        kind: "list",
        items: ["Early termination window", "Recovery method", "Effect on statements"],
      },
      {
        title: "Simulation",
        id: "SCH-SIM",
        kind: "fields",
        items: ["Sample policy", "Covered lives", "Premium", "Months active"],
        note: "Returns the computed commission per rate line so an author can sanity-check before publishing.",
      },
    ],
  },
  {
    id: "SCR_COMM_CONTINGENT",
    slug: "comm-contingent-overrides",
    name: "Contingent Categories, Overrides & Bonus Models",
    group: "Commissions & revenue",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Commission administrator, platform finance",
    purpose:
      "The layer above base schedules: contingent commission categories, upline overrides, upline and super bonuses, and annual or recurring bonus models — each with the qualification rules that decide whether it pays.",
    actions: [
      "Create a contingent category",
      "Define an override rate by hierarchy level",
      "Define a bonus program",
      "Set qualification thresholds",
      "Set measurement period",
      "Simulate qualification",
      "Publish",
    ],
    objects: [
      "Contingent commission category",
      "Override definition per hierarchy level",
      "Upline bonus program",
      "Super bonus program",
      "Qualification rule set",
      "Measurement period and accrual state",
    ],
    config: [
      "Contingent categories and what makes each contingent (persistency, loss ratio, volume, growth)",
      "Override rates by level and depth limit",
      "Bonus cadence: annual, quarterly, recurring monthly",
      "Threshold structure: flat, tiered, stepped with retroactive true-up",
      "Whether bonuses accrue provisionally before qualification is final",
    ],
    acl: [
      "commission.schedule.manage plus a bonus-authoring permission; super bonus programs are typically platform-only",
      "An agent never sees upline override rates taken above them unless transparency is explicitly enabled",
      "Provisional accruals are clearly labelled as unqualified so no one treats them as earned",
    ],
    drawer: [
      "Context: program, category and measurement period",
      "Summary: qualification status, accrued provisional amount",
      "Guidance: how qualification is measured and when it is final",
      "Help & FAQ: override vs bonus vs contingent",
      "Audit: program changes, qualification recalculations",
      "Next actions: simulate, publish, view projections",
    ],
    assistant:
      "Explains why an entity does or does not currently qualify. It never promises a bonus will pay.",
    source: SRC,
    assumptions: [
      "Contingent amounts remain provisional until the measurement period closes and are never shown as guaranteed earnings.",
    ],
    canvas: [
      {
        title: "Contingent categories",
        id: "CON-CAT",
        kind: "table",
        items: ["Category", "Contingency basis", "Measurement period", "Rate", "Status"],
        wide: true,
      },
      {
        title: "Overrides",
        id: "CON-OVR",
        kind: "table",
        items: ["Hierarchy level", "Depth", "Rate model", "Rate", "Applies to products"],
        wide: true,
      },
      {
        title: "Bonus programs",
        id: "CON-BONUS",
        kind: "list",
        items: [
          "Upline bonus — tiered by downline volume",
          "Super bonus — platform-level, multi-agency threshold",
          "Annual bonus with retroactive true-up",
          "Recurring monthly persistency bonus",
        ],
      },
      {
        title: "Qualification",
        id: "CON-QUAL",
        kind: "checks",
        items: [
          "Volume threshold met",
          "Persistency threshold met",
          "Loss ratio within band",
          "Period closed and finalised",
        ],
        wide: true,
      },
      {
        title: "Provisional labelling",
        id: "CON-PROV",
        kind: "box",
        note: "Anything not yet qualified displays as provisional everywhere it appears — projection, statement and dashboard.",
        wide: true,
      },
    ],
  },
  {
    id: "SCR_COMM_PROJECTION",
    slug: "comm-projection",
    name: "Projection View",
    group: "Commissions & revenue",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, agent (own book only), platform finance",
    purpose:
      "Forward-looking expected commission from the current book: base, overrides, contingent and bonus components projected over a horizon, with the assumptions stated on screen.",
    actions: [
      "Set the projection horizon",
      "Filter by product, carrier, agent or entity",
      "Toggle components in and out",
      "Adjust persistency assumption",
      "Export the projection",
      "Drill to contributing policies",
    ],
    objects: [
      "Projection run",
      "Policy set contributing to it",
      "Component breakdown",
      "Persistency and lapse assumptions",
      "Projection version for comparison",
    ],
    config: [
      "Default persistency assumption per product line",
      "Horizon options",
      "Whether provisional bonuses are included by default",
      "Which roles may see entity-wide vs own-book projections",
    ],
    acl: [
      "commission.view; agents see their own book, agency admins their entity, uplines their subtree only where the relationship grants it",
      "Projection excludes any policy the viewer cannot see, so totals differ legitimately between roles — the screen states the scope it used",
    ],
    drawer: [
      "Context: projection scope, horizon and assumptions",
      "Summary: projected total by component",
      "Guidance: this is an estimate, not a receivable",
      "Help & FAQ: why my projection changed",
      "Audit: projection runs and assumption changes",
      "Next actions: export, drill to policies, compare runs",
    ],
    assistant:
      "Explains which assumptions drove a change between two runs. It must always restate that projections are estimates.",
    source: SRC,
    assumptions: [
      "Projections are computed from the visible book and stated assumptions; they are never presented as amounts owed.",
    ],
    canvas: [
      {
        title: "Controls",
        id: "PRJ-CTRL",
        kind: "actions",
        items: [
          "Horizon: 12 / 24 / 36 months",
          "Scope: own book / entity / subtree",
          "Persistency assumption",
          "Include provisional bonuses",
        ],
        wide: true,
      },
      {
        title: "Projected total",
        id: "PRJ-TOTAL",
        kind: "box",
        note: "Headline projected amount with the estimate label and the scope it was computed over.",
      },
      {
        title: "Component breakdown",
        id: "PRJ-COMP",
        kind: "table",
        items: ["Component", "Basis", "Projected amount", "Confidence / provisional"],
      },
      {
        title: "Contributing policies",
        id: "PRJ-POLICIES",
        kind: "table",
        items: [
          "Policy",
          "Product",
          "Covered lives",
          "Monthly commission",
          "Months remaining in horizon",
        ],
        wide: true,
      },
      {
        title: "Assumption disclosure",
        id: "PRJ-DISCLOSE",
        kind: "box",
        note: "Persistency, lapse and effective-date assumptions are printed with the projection and travel with any export.",
        wide: true,
      },
    ],
  },
  {
    id: "SCR_COMM_QUOTE_PROJ",
    slug: "comm-quote-projection",
    name: "Quote / Cart Internal Commission Projection",
    group: "Commissions & revenue",
    workspace: "WS_AGENCY (internal only — never rendered in consumer or member chrome)",
    module: "MOD_COMMISSIONS overlay on MOD_MARKETPLACE_SALES",
    packet: "P1-Later",
    shell: "internal",
    user: "Agent or agency admin with commission visibility, while quoting",
    purpose:
      "An internal-only panel showing expected commission on the plans in a quote or cart, so an agent understands the economics — strictly separated from anything a consumer sees, and never a ranking input.",
    actions: [
      "Show projection for the current cart",
      "Compare projection across cart options",
      "Hide the panel",
      "Open the schedule behind a figure",
    ],
    objects: [
      "Quote / cart line",
      "Applicable schedule and rate line",
      "Projected commission per line and total",
      "Split preview where a paper owner takes a share",
    ],
    config: [
      "Feature flag per entity: internal commission projection visible during quoting on/off",
      "Which roles see it",
      "Whether split-adjusted or gross commission is displayed",
    ],
    acl: [
      "commission.view plus an explicit quoting-projection permission; when off, the panel is absent, not greyed",
      "The panel can never render in consumer chrome or in a shared quote — this is enforced by shell, not by a conditional",
      "Commission figures must never influence plan ordering or recommendation, and the screen states this",
    ],
    drawer: [
      "Context: cart, plans and applicable schedules",
      "Summary: projected commission by line",
      "Guidance: internal only — this must not be discussed as a reason to choose a plan",
      "Help & FAQ: which schedule applied",
      "Audit: panel views are logged for supervision",
      "Next actions: open schedule, hide panel",
    ],
    assistant:
      "May explain which schedule produced a figure. It must never suggest a plan on commission grounds, and any such prompt is refused.",
    source: SRC,
    assumptions: [
      "This panel is the one place commission meets the shopping flow, and only inside the internal shell.",
    ],
    m1Seam:
      "Overlays the Module 1 agent quick-quote workspace (UX-018) and cart (UX-013) as an internal-only panel. Module 1 screens and their consumer-facing behaviour are unchanged, and the panel never appears on the consumer or shared-quote path.",
    canvas: [
      {
        title: "Internal-only banner",
        id: "QPRJ-BANNER",
        kind: "box",
        note: "Internal view. Commission figures are never shown to the consumer, never included in a shared quote, and never affect plan ranking.",
        wide: true,
      },
      {
        title: "Per-line projection",
        id: "QPRJ-LINES",
        kind: "table",
        items: [
          "Plan",
          "Schedule applied",
          "Model",
          "Projected monthly",
          "Projected year 1",
          "Split-adjusted",
        ],
        wide: true,
      },
      {
        title: "Ranking fence",
        id: "QPRJ-FENCE",
        kind: "checks",
        items: [
          "Plan-AI ranking inputs exclude commission",
          "Sort options exclude commission",
          "Shared quote payload excludes commission",
        ],
      },
      {
        title: "Visibility control",
        id: "QPRJ-VIS",
        kind: "actions",
        items: ["Hide panel", "Open schedule", "Report a discrepancy"],
      },
    ],
  },
  {
    id: "SCR_COMM_STMT_AGENCY",
    slug: "comm-statement-agency",
    name: "Agency Statement",
    group: "Commissions & revenue",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, platform finance",
    purpose:
      "Period statement for an entity: what was earned, from what, what was adjusted or clawed back, what is provisional, and how it reconciles to what the carrier reported.",
    actions: [
      "Select a period",
      "Open a line",
      "Reconcile against a carrier statement",
      "Raise a discrepancy",
      "Export the statement",
      "Approve or close the period",
    ],
    objects: [
      "Statement period",
      "Statement lines",
      "Adjustments and clawbacks",
      "Carrier-reported amounts",
      "Reconciliation variances",
      "Discrepancy record",
    ],
    config: [
      "Period cadence and close date",
      "Whether carrier reconciliation is required before close",
      "Variance tolerance before a line is flagged",
      "Statement branding for white-labelled output",
    ],
    acl: [
      "commission.view scoped to the entity; downline statements are visible to an upline only where the relationship grants it",
      "Period close requires a finance permission and is irreversible without a platform-level reopen",
      "Provisional and disputed lines are visually distinct from settled lines",
    ],
    drawer: [
      "Context: entity and statement period",
      "Summary: earned, provisional, adjusted, variance vs carrier",
      "Guidance: how to read a variance",
      "Help & FAQ: why a line is provisional",
      "Audit: statement generation, adjustments, close events",
      "Next actions: reconcile, raise discrepancy, export, close",
    ],
    assistant: "Explains individual lines and variances. It cannot adjust or close a period.",
    source: SRC,
    assumptions: ["ABox reports commission; it does not disburse funds in Phase 1."],
    canvas: [
      {
        title: "Period summary",
        id: "AST-SUM",
        kind: "kv",
        items: [
          "Period",
          "Earned settled",
          "Provisional",
          "Adjustments",
          "Clawbacks",
          "Carrier reported",
          "Variance",
        ],
        wide: true,
      },
      {
        title: "Statement lines",
        id: "AST-LINES",
        kind: "table",
        items: ["Policy", "Product", "Selling agent", "Model", "Basis units", "Amount", "State"],
        wide: true,
      },
      {
        title: "Reconciliation",
        id: "AST-RECON",
        kind: "list",
        items: [
          "Matched lines",
          "In ABox not in carrier file",
          "In carrier file not in ABox",
          "Amount variance beyond tolerance",
        ],
      },
      {
        title: "Close",
        id: "AST-CLOSE",
        kind: "actions",
        items: ["Raise discrepancy", "Export", "Approve period", "Close period"],
      },
    ],
  },
  {
    id: "SCR_COMM_STMT_AGENT_POLICY",
    slug: "comm-statement-agent-policy",
    name: "Agent Statement & Policy-Level Statement",
    group: "Commissions & revenue",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agent for their own statement; agency admin for any agent in scope",
    purpose:
      "The producer's own earnings view and the drill-down to a single policy's full commission history — the level of detail an agent needs to answer 'why was I paid this on this policy'.",
    actions: [
      "Select period",
      "Filter by product or carrier",
      "Drill into a policy",
      "View month-by-month accrual",
      "Raise a query",
      "Export",
    ],
    objects: [
      "Agent statement period",
      "Agent statement lines",
      "Policy commission history",
      "Monthly accrual records",
      "Adjustment and clawback events",
      "Query record",
    ],
    config: [
      "Whether agents see split-adjusted or gross amounts",
      "Whether upline override amounts are disclosed to the agent",
      "Query routing and SLA",
    ],
    acl: [
      "An agent sees only their own statement — never a colleague's, never their upline's override",
      "Agency admins see agents in their subtree; sensitive amounts remain gated by commission.view",
      "Policy-level history is read-only for everyone; corrections happen through adjustments, never by editing history",
    ],
    drawer: [
      "Context: agent, period, or selected policy",
      "Summary: earned, provisional, adjustments",
      "Guidance: how a policy's monthly accrual builds up",
      "Help & FAQ: why an amount changed after the policy lapsed",
      "Audit: accruals, adjustments, clawbacks with reason",
      "Next actions: raise a query, export, view attribution",
    ],
    assistant:
      "Walks the calculation for a specific policy line: schedule, model, basis units and adjustments.",
    source: SRC,
    assumptions: [
      "Policy-level history is append-only; a correction is a new event, never a rewrite.",
    ],
    canvas: [
      {
        title: "Agent period summary",
        id: "GST-SUM",
        kind: "kv",
        items: ["Agent", "Period", "Earned", "Provisional", "Adjustments", "Policies contributing"],
        wide: true,
      },
      {
        title: "Agent lines",
        id: "GST-LINES",
        kind: "table",
        items: ["Policy", "Member", "Product", "Model", "Basis units", "Amount", "State"],
        wide: true,
      },
      {
        title: "Policy-level detail",
        id: "GST-POLICY",
        kind: "timeline",
        items: [
          "Issued — accrual begins",
          "Month 1 accrual",
          "Month 2 accrual",
          "Rate change applied",
          "Lapse — clawback applied",
          "Adjustment with reason",
        ],
        wide: true,
      },
      {
        title: "Query",
        id: "GST-QUERY",
        kind: "actions",
        items: ["Raise a query on this line", "Attach evidence", "View query status"],
      },
    ],
  },
  {
    id: "SCR_COMM_REPORTING",
    slug: "comm-reporting",
    name: "Commission Reporting & ACL-Controlled Visibility",
    group: "Commissions & revenue",
    workspace: WS,
    module: "MOD_COMMISSIONS + MOD_REPORTING",
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, platform finance, compliance reviewer",
    purpose:
      "Aggregate commission reporting across entities, products, carriers and periods — and the explicit statement of who can see which figures, since commission visibility is the sharpest ACL boundary in the platform.",
    actions: [
      "Build a report by dimension",
      "Compare periods",
      "Drill to statement lines",
      "Export",
      "Schedule a recurring report",
      "View the visibility rules applied",
    ],
    objects: [
      "Report definition",
      "Aggregated commission facts",
      "Dimension set (entity, product, carrier, agent, period, model)",
      "Visibility rule set applied",
      "Export record",
    ],
    config: [
      "Available dimensions and measures",
      "Whether the commission module is enabled for the entity at all (feature flag)",
      "Export permissions and watermarking",
      "Scheduled report recipients",
    ],
    acl: [
      "When commission.view is absent the whole module is absent from navigation — not greyed out",
      "Every aggregate is computed only over records the viewer may see, and the report prints the scope it used so two users comparing totals understand the difference",
      "Exports are watermarked with viewer, scope and timestamp",
    ],
    drawer: [
      "Context: report definition and scope applied",
      "Summary: measures and dimensions in use",
      "Guidance: why your total differs from a colleague's",
      "Help & FAQ: commission visibility rules",
      "Audit: report runs and exports with scope",
      "Next actions: drill down, export, schedule",
    ],
    assistant:
      "Explains the scope applied to a report and why a figure differs between two viewers.",
    source: SRC,
    assumptions: [
      "Reporting reads settled and provisional facts separately and never blends them into one unlabelled total.",
    ],
    canvas: [
      {
        title: "Report builder",
        id: "CRPT-BUILD",
        kind: "actions",
        items: [
          "Dimensions: entity, agent, product, carrier, model, period",
          "Measures: settled, provisional, adjustments, clawbacks",
          "Period comparison",
        ],
        wide: true,
      },
      {
        title: "Result grid",
        id: "CRPT-GRID",
        kind: "table",
        items: ["Dimension", "Settled", "Provisional", "Adjustments", "Net", "Variance vs prior"],
        wide: true,
      },
      {
        title: "Scope statement",
        id: "CRPT-SCOPE",
        kind: "box",
        note: "Prints the entity scope, agent scope and visibility rules used to compute the figures, and travels with every export.",
      },
      {
        title: "Schedule & export",
        id: "CRPT-EXPORT",
        kind: "actions",
        items: ["Export CSV", "Export PDF", "Schedule recurring", "Manage recipients"],
      },
    ],
  },
]);
