import { SRC_BLUEPRINT, SRC_IA, SRC_RECON, screens } from "./types";

const WS =
  "WS_PLATFORM (authoring) — WS_AGENCY read-only where an agency may view its assigned forms";
const MOD = "MOD_FORMS_ENROLLMENT (configurator area)";
const SRC = `${SRC_BLUEPRINT} (form configurator, dynamic forms, validation, signature settings); ${SRC_IA} (SCR_FORMCFG_*); ${SRC_RECON} — configurator is explicitly outside Module 1`;

export const FORM_CONFIGURATOR = screens([
  {
    id: "SCR_FORMCFG_LIBRARY",
    slug: "formcfg-library",
    name: "Form Library",
    group: "Form configurator",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform form administrator; agency admin in read-only where permitted",
    purpose:
      "The catalog of every form ABox can run: which product, state and carrier each serves, which version is live, and what is in draft. Entry point to every other configurator screen.",
    actions: [
      "Search and filter forms",
      "Create a form",
      "Duplicate a form as a new draft",
      "Open a version",
      "Publish or retire a version",
      "Compare two versions",
    ],
    objects: [
      "Form",
      "Form version",
      "Assignment rules (product / state / carrier)",
      "Usage count of live applications on each version",
    ],
    config: [
      "Naming and ID conventions",
      "Ownership: platform-authored vs agency-authored forms",
      "Who may publish",
    ],
    acl: [
      "form.author is platform-level; form.view may be granted to agency admins",
      "Publishing is a distinct permission from editing",
      "A version with live applications cannot be deleted, only retired",
    ],
    drawer: [
      "Context: selected form and its assignment scope",
      "Summary: live version, draft version, applications in flight",
      "Guidance: when to version vs create a new form",
      "Help & FAQ: retiring a form safely",
      "Audit: version publish and retire history",
      "Next actions: open field builder, edit rules, preview",
    ],
    assistant:
      "Finds forms by product or state and explains version states. It does not author or publish.",
    source: SRC,
    assumptions: [
      "Forms are platform-governed by default; agency-authored forms are a permissioned exception, not the norm.",
    ],
    canvas: [
      {
        title: "Filters",
        id: "LIB-FILTERS",
        kind: "actions",
        items: ["Product line", "State", "Carrier", "Status", "Owner"],
        wide: true,
      },
      {
        title: "Form list",
        id: "LIB-LIST",
        kind: "table",
        items: [
          "Form name",
          "Product",
          "States",
          "Carrier",
          "Live version",
          "Draft",
          "In-flight apps",
          "Updated",
        ],
        wide: true,
      },
      {
        title: "Version panel",
        id: "LIB-VERSIONS",
        kind: "list",
        items: ["v3 — live since date", "v4 — draft", "v2 — retired, 12 applications still pinned"],
      },
      {
        title: "Create",
        id: "LIB-CREATE",
        kind: "actions",
        items: ["New form", "Duplicate as draft", "Import from template"],
      },
    ],
  },
  {
    id: "SCR_FORMCFG_RULES",
    slug: "formcfg-rules",
    name: "Product / State / Carrier Form Rules",
    group: "Form configurator",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform form administrator",
    purpose:
      "Decides which form version runs for a given product, state, carrier and effective date. This is the resolver — without it, the runtime cannot know which form to render.",
    actions: [
      "Add a rule",
      "Set precedence",
      "Set effective date range",
      "Test resolution against a sample case",
      "Detect conflicts",
      "Publish rule set",
    ],
    objects: [
      "Resolution rule",
      "Rule precedence order",
      "Effective date window",
      "Conflict report",
      "Resolution test result",
    ],
    config: [
      "Rule dimensions in use",
      "Precedence model (most specific wins)",
      "Default/fallback form when no rule matches",
    ],
    acl: [
      "form.rules.manage, platform only",
      "Rule changes are versioned and take effect only on publish",
      "No agency-level override of a platform resolution rule",
    ],
    drawer: [
      "Context: the rule set being edited and its publish state",
      "Summary: rule count, conflicts detected",
      "Guidance: how precedence resolves overlapping rules",
      "Help & FAQ: what happens when nothing matches",
      "Audit: rule additions, edits and publishes",
      "Next actions: run resolution test, resolve conflicts, publish",
    ],
    assistant: "Explains why a test case resolved to a particular version. It cannot add rules.",
    source: SRC,
    assumptions: [
      "Resolution is evaluated at application start and pinned; it is not re-evaluated mid-application.",
    ],
    canvas: [
      {
        title: "Rule table",
        id: "RULES-TABLE",
        kind: "table",
        items: [
          "Product",
          "State",
          "Carrier",
          "Effective from",
          "Effective to",
          "Form version",
          "Precedence",
        ],
        wide: true,
      },
      {
        title: "Conflict detection",
        id: "RULES-CONFLICT",
        kind: "checks",
        items: [
          "Overlapping windows for the same key",
          "Unreachable rule (shadowed by a more specific one)",
          "Gap: state with no matching rule",
        ],
      },
      {
        title: "Resolution test",
        id: "RULES-TEST",
        kind: "fields",
        items: ["Product", "State", "Carrier", "Effective date"],
        note: "Returns the resolved form version and the rule that produced it.",
      },
      {
        title: "Fallback",
        id: "RULES-FALLBACK",
        kind: "box",
        note: "No match must fail loudly — the product becomes non-sellable off-exchange rather than silently running a default form.",
        wide: true,
      },
    ],
  },
  {
    id: "SCR_FORMCFG_FIELDS",
    slug: "formcfg-field-builder",
    name: "Field Builder",
    group: "Form configurator",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform form administrator",
    purpose:
      "Builds the sections and fields of a form version: field type, label, help text, data binding to the canonical object model, sensitivity and who may complete it.",
    actions: [
      "Add section",
      "Add field",
      "Reorder by drag",
      "Bind a field to a canonical attribute",
      "Mark applicant-only",
      "Mark sensitive",
      "Set default value",
    ],
    objects: [
      "Section",
      "Field",
      "Canonical attribute binding",
      "Sensitivity classification",
      "Completion role restriction",
    ],
    config: [
      "Field types available (text, date, select, multi-select, address, currency, attestation, upload trigger)",
      "Canonical attribute dictionary the field can bind to",
      "Sensitivity classes and their masking behaviour",
      "Help text and label copy per field",
    ],
    acl: [
      "form.author only; binding to a canonical attribute requires the data-dictionary permission",
      "Marking a field non-sensitive when it holds identifiers is blocked by the sensitivity guardrail",
      "Applicant-only fields cannot be completed by agents at runtime",
    ],
    drawer: [
      "Context: form version, section, selected field",
      "Summary: field count, unbound fields, sensitive fields",
      "Guidance: bind rather than free-text so reporting and EDI mapping work",
      "Help & FAQ: when to create a new attribute",
      "Audit: field-level change history",
      "Next actions: add logic, add validation, preview",
    ],
    assistant:
      "Suggests an existing canonical attribute for a new field so authors do not create duplicates. Suggestions require human confirmation.",
    source: SRC,
    assumptions: [
      "A canonical attribute dictionary exists per the North Star object model; unbound free fields are permitted but flagged.",
    ],
    canvas: [
      {
        title: "Section tree",
        id: "FIELDS-TREE",
        kind: "tree",
        items: [
          "Applicant",
          "Household",
          "Coverage history",
          "Eligibility questions",
          "Documents",
          "Signature",
        ],
      },
      {
        title: "Field list",
        id: "FIELDS-LIST",
        kind: "table",
        items: ["Label", "Type", "Bound attribute", "Required", "Sensitive", "Applicant-only"],
      },
      {
        title: "Field inspector",
        id: "FIELDS-INSPECT",
        kind: "fields",
        items: [
          "Label",
          "Help text",
          "Type",
          "Bound attribute",
          "Default",
          "Sensitivity class",
          "Completion role",
        ],
        wide: true,
      },
      {
        title: "Unbound warning",
        id: "FIELDS-UNBOUND",
        kind: "box",
        note: "Unbound fields cannot appear in reports or EDI mappings. The builder shows the count and blocks publish above a configured threshold.",
        wide: true,
      },
    ],
  },
  {
    id: "SCR_FORMCFG_LOGIC",
    slug: "formcfg-logic",
    name: "Conditional Logic",
    group: "Form configurator",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform form administrator",
    purpose:
      "Defines when sections, fields and document requirements appear, based on prior answers and known member facts, and proves the logic is reachable and terminating.",
    actions: [
      "Add a rule",
      "Group conditions",
      "Target a section, field or document requirement",
      "Simulate an answer path",
      "Detect unreachable branches",
      "View logic as a graph",
    ],
    objects: [
      "Logic rule",
      "Condition group",
      "Target element",
      "Simulation path",
      "Reachability report",
    ],
    config: [
      "Available operators",
      "Whether cross-section conditions are allowed",
      "Whether logic may reference member record facts, not just answers",
    ],
    acl: [
      "form.author; logic that references sensitive attributes needs the sensitive-data authoring permission",
    ],
    drawer: [
      "Context: form version and selected rule",
      "Summary: rule count, unreachable targets",
      "Guidance: keep conditions on bound attributes so they survive field renames",
      "Help & FAQ: show vs require vs skip",
      "Audit: logic changes",
      "Next actions: simulate, fix unreachable, preview",
    ],
    assistant:
      "Explains why a field did or did not appear on a simulated path. It cannot write rules.",
    source: SRC,
    assumptions: [
      "Logic is declarative rule data, not script, so it can be versioned and audited.",
    ],
    canvas: [
      {
        title: "Rule builder",
        id: "LOGIC-BUILD",
        kind: "editor",
        items: [
          "WHEN answer to <field> <operator> <value>",
          "AND / OR condition group",
          "THEN show / require / skip <target>",
        ],
        wide: true,
      },
      {
        title: "Logic graph",
        id: "LOGIC-GRAPH",
        kind: "box",
        note: "Node-and-edge view of section flow so a reviewer can see branches at a glance.",
      },
      {
        title: "Simulation",
        id: "LOGIC-SIM",
        kind: "list",
        items: ["Set answers", "Step through resulting sections", "Show which rule fired"],
      },
      {
        title: "Reachability",
        id: "LOGIC-REACH",
        kind: "checks",
        items: [
          "Every section reachable on some path",
          "No required field on an unreachable path",
          "No circular condition",
        ],
        wide: true,
      },
    ],
  },
  {
    id: "SCR_FORMCFG_DOCS_SIG",
    slug: "formcfg-docs-signature",
    name: "Required Documents & Signature Settings",
    group: "Form configurator",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform form administrator",
    purpose:
      "Declares what proof a form version demands and how it must be signed — the two settings that drive the runtime document-capture and e-signature screens.",
    actions: [
      "Add a document requirement",
      "Make a requirement conditional",
      "Set accepted file types",
      "Configure signer roles and order",
      "Choose signature method",
      "Set disclosure text",
    ],
    objects: [
      "Document requirement",
      "Conditional trigger",
      "Signer role definition",
      "Signature method",
      "Disclosure text block",
    ],
    config: [
      "Requirement name, description and example shown to the applicant",
      "Blocking vs advisory requirement",
      "Signer set: applicant, spouse, guardian, agent attestation",
      "Signature method and provider",
      "State-specific fraud warnings and disclosures",
    ],
    acl: [
      "form.author; disclosure text edits are compliance-gated and require a second approver",
      "Removing a blocking requirement on a live form requires publish permission and is reported",
    ],
    drawer: [
      "Context: form version being configured",
      "Summary: requirement count, signer count",
      "Guidance: describe requirements in applicant language, not carrier jargon",
      "Help & FAQ: agent attestation vs applicant signature",
      "Audit: requirement and disclosure changes with approver",
      "Next actions: preview runtime, publish",
    ],
    assistant: "Explains how a setting will look at runtime. It cannot edit disclosure text.",
    source: SRC,
    assumptions: [
      "Disclosure text is treated as compliance-controlled content requiring dual approval.",
    ],
    canvas: [
      {
        title: "Document requirements",
        id: "DOCSIG-DOCS",
        kind: "table",
        items: [
          "Requirement",
          "Condition",
          "Accepted types",
          "Blocking",
          "Applicant-visible description",
        ],
        wide: true,
      },
      {
        title: "Signer configuration",
        id: "DOCSIG-SIGNERS",
        kind: "list",
        items: [
          "Applicant — required",
          "Spouse — conditional on household",
          "Agent attestation — required in assisted mode",
        ],
      },
      {
        title: "Signature method",
        id: "DOCSIG-METHOD",
        kind: "actions",
        items: ["Typed adoption", "Drawn", "Third-party provider"],
      },
      {
        title: "Disclosures",
        id: "DOCSIG-DISCLOSE",
        kind: "editor",
        items: ["Truthfulness attestation", "State fraud warning", "E-sign consent"],
        wide: true,
        note: "Compliance-gated content. Edits route to a second approver before they can be published.",
      },
    ],
  },
  {
    id: "SCR_FORMCFG_VALIDATION",
    slug: "formcfg-validation",
    name: "Validation Rules",
    group: "Form configurator",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform form administrator",
    purpose:
      "Defines what counts as an acceptable answer: format, range, cross-field consistency and carrier-specific constraints, each with the message the applicant sees and whether it blocks.",
    actions: [
      "Add a validation rule",
      "Set severity",
      "Author the error message",
      "Test against sample values",
      "Import carrier constraint set",
    ],
    objects: ["Validation rule", "Severity (blocking / warning)", "Error message", "Test case set"],
    config: [
      "Rule types available",
      "Message copy and tone",
      "Which rules run client-side vs server-side",
      "Carrier constraint packs",
    ],
    acl: [
      "form.author; downgrading a blocking rule to a warning is logged and reported because it changes submission quality",
    ],
    drawer: [
      "Context: form version and field under validation",
      "Summary: rule count by severity",
      "Guidance: write messages that tell the applicant how to fix the problem",
      "Help & FAQ: blocking vs warning",
      "Audit: severity changes",
      "Next actions: run tests, preview, publish",
    ],
    assistant: "Drafts clearer error copy on request; the author must confirm before it is saved.",
    source: SRC,
    assumptions: [
      "All blocking validations are enforced server-side regardless of client-side behaviour.",
    ],
    canvas: [
      {
        title: "Rules",
        id: "VAL-RULES",
        kind: "table",
        items: ["Field(s)", "Rule", "Severity", "Message", "Runs on"],
        wide: true,
      },
      {
        title: "Cross-field rules",
        id: "VAL-CROSS",
        kind: "list",
        items: [
          "Effective date after signature date",
          "Dependent DOB consistent with relationship",
          "SEP answer requires a qualifying event date",
        ],
      },
      {
        title: "Test values",
        id: "VAL-TEST",
        kind: "fields",
        items: ["Sample value", "Expected result"],
      },
      {
        title: "Server enforcement",
        id: "VAL-SERVER",
        kind: "box",
        note: "Client-side validation is a convenience only. Every blocking rule is re-checked on save and at submission release.",
        wide: true,
      },
    ],
  },
  {
    id: "SCR_FORMCFG_PREVIEW",
    slug: "formcfg-preview",
    name: "Preview Mode",
    group: "Form configurator",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform form administrator, compliance reviewer",
    purpose:
      "Runs a draft form version exactly as an applicant or agent would experience it, in a sandbox that creates no application record and submits nothing.",
    actions: [
      "Preview as consumer",
      "Preview as assisting agent",
      "Preview a specific state/carrier resolution",
      "Walk a simulated answer path",
      "Export a PDF of the whole form for compliance review",
    ],
    objects: [
      "Draft form version",
      "Simulated answer set",
      "Preview session (discarded, never an application)",
      "Compliance export",
    ],
    config: [
      "Which personas are available to preview as",
      "Whether synthetic data may pre-fill preview sessions",
    ],
    acl: [
      "form.view; preview never writes an application, never submits, and is watermarked as preview throughout",
    ],
    drawer: [
      "Context: version and resolution being previewed",
      "Summary: sections shown on the current path",
      "Guidance: what preview does not cover (real rating, real carrier submission)",
      "Help & FAQ: sharing a preview with compliance",
      "Audit: preview sessions and compliance exports",
      "Next actions: fix an issue, export, publish",
    ],
    assistant: "Answers 'why did this field appear' during a preview walk.",
    source: SRC,
    assumptions: ["Preview uses synthetic data only; it never reads a real member record."],
    canvas: [
      {
        title: "Preview controls",
        id: "PREV-CTRL",
        kind: "actions",
        items: [
          "As consumer",
          "As assisting agent",
          "State / carrier",
          "Effective date",
          "Reset path",
        ],
        wide: true,
      },
      {
        title: "Rendered form",
        id: "PREV-RENDER",
        kind: "box",
        note: "Full runtime rendering inside a watermarked preview frame. No application record is created.",
        wide: true,
      },
      {
        title: "Path trace",
        id: "PREV-TRACE",
        kind: "list",
        items: [
          "Section shown — rule that showed it",
          "Field hidden — rule that hid it",
          "Requirement triggered",
        ],
      },
      {
        title: "Compliance export",
        id: "PREV-EXPORT",
        kind: "actions",
        items: ["Export full form PDF", "Export logic summary", "Export disclosure text"],
      },
    ],
  },
  {
    id: "SCR_FORMCFG_VERSION",
    slug: "formcfg-versioning",
    name: "Versioning & Audit",
    group: "Form configurator",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform form administrator, compliance reviewer, auditor",
    purpose:
      "Controls the lifecycle of form versions and proves what was in force when any given application was completed — the evidence trail a carrier or regulator asks for.",
    actions: [
      "Compare two versions",
      "Publish a draft",
      "Retire a version",
      "View applications pinned to a version",
      "Export an audit pack for a date range",
      "Roll forward a change into a new draft",
    ],
    objects: [
      "Form version",
      "Change set diff",
      "Publish record with approver",
      "Pinned application list",
      "Audit pack export",
    ],
    config: [
      "Approval requirement before publish",
      "Retention period for retired versions",
      "Whether concurrent drafts are allowed",
    ],
    acl: [
      "form.publish is separate from form.author and should not be held by the same person for compliance-gated content",
      "Audit pack export is a logged, high-sensitivity action because it contains disclosure text and application references",
      "No version is ever hard-deleted",
    ],
    drawer: [
      "Context: form and version under review",
      "Summary: publish history, in-flight application count",
      "Guidance: never edit a published version — always draft forward",
      "Help & FAQ: what an auditor will ask for",
      "Audit: full change and publish trail with actors",
      "Next actions: compare, publish, retire, export",
    ],
    assistant: "Summarises a diff between two versions in plain language for a reviewer.",
    source: SRC,
    assumptions: ["Published versions are immutable; corrections are new versions."],
    canvas: [
      {
        title: "Version timeline",
        id: "VER-TIMELINE",
        kind: "timeline",
        items: ["v1 published", "v2 published", "v2 retired", "v3 live", "v4 draft"],
        wide: true,
      },
      {
        title: "Diff",
        id: "VER-DIFF",
        kind: "table",
        items: ["Element", "v3", "v4", "Change type", "Compliance-gated"],
      },
      {
        title: "Publish record",
        id: "VER-PUBLISH",
        kind: "kv",
        items: ["Author", "Approver", "Published at", "Change summary", "Effective from"],
      },
      {
        title: "Pinned applications",
        id: "VER-PINNED",
        kind: "box",
        note: "Lists applications still running on each version so a retirement never breaks a live application.",
        wide: true,
      },
    ],
  },
]);
