import { SRC_BLUEPRINT, SRC_IA, SRC_RECON, screens } from "./types";

const WS = "WS_AGENCY (internal) — consumer-facing steps render in WS_CONSUMER branded chrome";
const MOD = "MOD_FORMS_ENROLLMENT";
const SRC = `${SRC_BLUEPRINT} (off-exchange enrollment, EDI + API submission, payment FE); ${SRC_IA} (SCR_ENROLL_*); ${SRC_RECON} gaps M1REC off-exchange application, document capture, e-signature, submission status`;

export const OFF_EXCHANGE = screens([
  {
    id: "SCR_ENROLL_INTAKE",
    slug: "enroll-intake",
    name: "Application Intake",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "consumer",
    user: "Consumer completing their own application, or agent completing it on the member's behalf",
    purpose:
      "Opens an off-exchange application against a selected plan and captures the applicant, household and coverage facts every carrier form needs before the product-specific dynamic form runs. This is the off-exchange counterpart to the on-exchange EDE handoff — here ABox owns the whole application, it is not passed to a federal partner.",
    actions: [
      "Start application from cart or from a plan",
      "Confirm applicant and household carried from the quote",
      "Select coverage effective date",
      "Indicate assisted vs self-service completion",
      "Save and continue to the dynamic form",
      "Abandon and keep as a saved application",
    ],
    objects: [
      "Application (new, status = draft)",
      "Quote and cart line the application came from",
      "Member / lead record",
      "Household members carried forward",
      "Plan, carrier, product and rate version selected",
      "Writing agent and selling agency attribution",
    ],
    config: [
      "Which products can be applied for off-exchange (product availability rules)",
      "Whether unassisted D2C off-exchange application is enabled per agency",
      "Effective date rules per product/carrier",
      "Which intake fields are pre-filled from the quote vs re-asked",
    ],
    acl: [
      "enrollment.start on the product, plus sellability for the state and effective date",
      "An agent can only start an application for a lead inside their assignment or downline",
      "Consumer self-service intake is bound to the authenticated member and their own household",
      "Selling agency and writing agent are stamped at intake and cannot be edited later without appointment.manage",
    ],
    drawer: [
      "Context: which quote, plan and member this application belongs to",
      "Summary: applicant, household size, effective date, carrier",
      "Guidance: what the applicant will be asked for next and what documents to have ready",
      "Help & FAQ: difference between off-exchange and marketplace enrollment",
      "Audit: application created, by whom, from which quote",
      "Next actions: continue form, save and send resume link, assign to another agent",
    ],
    assistant:
      "Consumer-voice help bubble on the branded path, copilot in the internal shell. Explains what the application is and what happens after submission. Never advises whether to apply and never predicts approval.",
    source: SRC,
    assumptions: [
      "Off-exchange applications are ABox-owned end to end; only on-exchange work hands off to the EDE partner.",
      "Intake always originates from a quote or plan selection — there is no cold application with no product context.",
    ],
    m1Seam:
      "Reads the Module 1 cart/quote (UX-013, UX-014). Module 1 itself is unchanged — it ends at the enroll gate.",
    canvas: [
      {
        title: "Application header",
        id: "INTAKE-HDR",
        kind: "kv",
        items: [
          "Application ID (draft)",
          "Carrier / plan",
          "Effective date",
          "Status: Draft",
          "Assisted by: agent name or Self-service",
        ],
        wide: true,
      },
      {
        title: "Applicant",
        id: "INTAKE-APPLICANT",
        kind: "fields",
        items: ["Legal name", "Date of birth", "SSN (masked)", "Tobacco use", "Residential address", "County"],
        note: "Carried from the quote where available; changed values re-trigger rating and sellability checks.",
      },
      {
        title: "Household members",
        id: "INTAKE-HOUSEHOLD",
        kind: "list",
        items: ["Member row: relationship, DOB, applying yes/no", "Add member", "Remove member"],
        note: "Household changes here can change the rate — the applicant is warned before the rate is re-pulled.",
      },
      {
        title: "Coverage & effective date",
        id: "INTAKE-COVERAGE",
        kind: "fields",
        items: ["Requested effective date", "Qualifying event (if outside open enrollment)", "Prior coverage"],
      },
      {
        title: "Consents at intake",
        id: "INTAKE-CONSENT",
        kind: "checks",
        items: [
          "Consumer authorizes the agency to submit on their behalf",
          "Electronic delivery and e-signature consent",
          "Marketing / contact consent (separate, never bundled)",
        ],
        note: "Consents are separately recorded with timestamp, IP and actor — never inferred from continuing.",
      },
    ],
  },
  {
    id: "SCR_ENROLL_DYNFORM",
    slug: "enroll-dynamic-form",
    name: "Dynamic Form Flow",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "consumer",
    user: "Consumer or assisting agent",
    purpose:
      "Renders the carrier/product/state form assembled by the Form Configurator as a stepped flow. The screen is a runtime of a configured form version — no form content is hardcoded into the screen.",
    actions: [
      "Answer a section and advance",
      "Jump back to a completed section",
      "Trigger conditional sections by answer",
      "Save draft",
      "Resume later via emailed link",
      "Flag a question for the agent to answer",
    ],
    objects: [
      "Form version (immutable, pinned at application start)",
      "Application answers",
      "Conditional branch state",
      "Validation results",
      "Required-document list produced by answers",
    ],
    config: [
      "Section order, field labels, help text (Form Configurator)",
      "Conditional logic rules",
      "Validation rules and error copy",
      "Which fields agents may complete vs applicant-only fields",
    ],
    acl: [
      "Applicant-only attestation fields are locked for agents even in assisted mode and are visibly marked",
      "Field-level sensitive data (SSN, immigration status, health answers) is masked once saved",
      "Only enrollment.edit holders may modify a submitted-but-returned application",
    ],
    drawer: [
      "Context: form version, product, state, carrier",
      "Summary: percent complete by section",
      "Guidance: what this section is for, plain-language help authored in the configurator",
      "Help & FAQ: why a question is asked",
      "Audit: answer changes with actor and timestamp",
      "Next actions: save, resume link, escalate to agent",
    ],
    assistant:
      "Answers 'what does this question mean' from the configured help content only. It may not answer for the applicant, pre-fill attestations, or interpret eligibility.",
    source: SRC,
    assumptions: [
      "The form version is pinned at application start so a mid-flight configurator change cannot alter a live application.",
    ],
    canvas: [
      {
        title: "Section stepper",
        id: "DYN-STEPS",
        kind: "tabs",
        items: ["Applicant", "Household", "Coverage history", "Health / eligibility questions", "Documents", "Review & sign"],
        wide: true,
        note: "Steps are produced by the form version, not by the screen.",
      },
      {
        title: "Rendered section",
        id: "DYN-SECTION",
        kind: "fields",
        items: ["Configured field", "Configured field (required)", "Configured field with help text", "Conditional field — shown only when the trigger answer matches"],
        wide: true,
      },
      {
        title: "Validation panel",
        id: "DYN-VALIDATION",
        kind: "checks",
        items: ["Format rules", "Cross-field rules", "Carrier-specific rules", "Blocking vs warning distinction"],
      },
      {
        title: "Assist controls",
        id: "DYN-ASSIST",
        kind: "actions",
        items: ["Save draft", "Send resume link", "Flag for agent", "Applicant-only field marker"],
      },
    ],
  },
  {
    id: "SCR_ENROLL_RESUME",
    slug: "enroll-save-resume",
    name: "Save & Resume",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "consumer",
    user: "Returning applicant, or agent picking a stalled application back up",
    purpose:
      "Single place to re-enter an in-progress application safely: proves identity, shows what is done and what remains, and restores the pinned form version rather than the current one.",
    actions: [
      "Resume by secure link",
      "Resume from member dashboard",
      "Verify identity before restoring PII",
      "See remaining sections and documents",
      "Transfer completion to an agent",
      "Withdraw the application",
    ],
    objects: ["Application draft", "Pinned form version", "Resume token and its expiry", "Outstanding requirements list"],
    config: [
      "Resume link lifetime and re-verification rules",
      "Draft retention period before auto-expiry",
      "Whether agents may resume unassisted consumer drafts",
    ],
    acl: [
      "A resume token grants access to exactly one application and expires; it never authenticates a session broadly",
      "Masked PII stays masked until identity verification passes",
      "Agent resume is allowed only within assignment/downline scope and is written to the audit trail",
    ],
    drawer: [
      "Context: application, product, member",
      "Summary: completion state by section",
      "Guidance: what is blocking submission",
      "Help & FAQ: resume link expired, what now",
      "Audit: every resume attempt, successful or not",
      "Next actions: continue, transfer to agent, withdraw",
    ],
    assistant: "Explains why a link expired and how to request a new one. Cannot re-issue a link itself.",
    source: SRC,
    assumptions: ["Draft retention is a configurable tenant policy rather than a fixed platform constant."],
    canvas: [
      {
        title: "Identity verification",
        id: "RESUME-VERIFY",
        kind: "fields",
        items: ["Date of birth", "ZIP", "Last 4 of a previously supplied identifier"],
        note: "Fails closed: repeated failures lock the token and notify the owning agent.",
      },
      {
        title: "Progress summary",
        id: "RESUME-PROGRESS",
        kind: "list",
        items: ["Applicant — complete", "Household — complete", "Coverage history — incomplete", "Documents — 1 of 3 uploaded", "Signature — not started"],
      },
      {
        title: "Version pin notice",
        id: "RESUME-PIN",
        kind: "box",
        note: "This application resumes on the form version it started on. A newer published version exists — it applies to new applications only.",
        wide: true,
      },
    ],
  },
  {
    id: "SCR_ENROLL_DOCS",
    slug: "enroll-documents",
    name: "Document Capture",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "consumer",
    user: "Applicant uploading proof, or agent uploading on their behalf",
    purpose:
      "Collects the documents the form version and carrier require, tracks which requirement each file satisfies, and shows what still blocks submission.",
    actions: ["Upload a file", "Photograph with a phone camera", "Replace a rejected file", "Mark a requirement not applicable with reason", "Request a document from the applicant"],
    objects: ["Document requirement list", "Uploaded document records", "Review status per document", "Application readiness impact"],
    config: [
      "Required document types per product/state/carrier (Form Configurator)",
      "Accepted file types and size limits",
      "Whether agent upload on behalf is permitted",
      "Retention and redaction policy per document type",
    ],
    acl: [
      "documents.upload scoped to the application; documents.review is a separate permission",
      "Document previews respect sensitive-data rules — identity documents are watermarked and download is permissioned",
      "Every view of an identity document is logged, not just every upload",
    ],
    drawer: [
      "Context: which application and requirement set",
      "Summary: requirements met vs outstanding",
      "Guidance: what a valid proof looks like for each requirement",
      "Help & FAQ: file rejected reasons",
      "Audit: upload, view, replace and delete events with actor",
      "Next actions: request from applicant, mark N/A, continue",
    ],
    assistant: "Explains what each requirement means. It does not judge whether an uploaded document is acceptable — that is the reviewer's call.",
    source: SRC,
    assumptions: ["Automated document classification is out of Phase 1 scope; review is human."],
    canvas: [
      {
        title: "Requirement checklist",
        id: "DOCS-REQ",
        kind: "list",
        items: ["Proof of identity — required — not uploaded", "Proof of residency — required — uploaded, pending review", "Qualifying event proof — conditional — triggered by SEP answer", "Prior coverage letter — optional"],
        wide: true,
      },
      { title: "Upload zone", id: "DOCS-UPLOAD", kind: "box", note: "Drag and drop, browse, or capture with camera. Progress and virus-scan state shown per file." },
      { title: "Uploaded files", id: "DOCS-FILES", kind: "table", items: ["File", "Requirement satisfied", "Uploaded by", "Status", "Actions"] },
      { title: "Blocking impact", id: "DOCS-BLOCK", kind: "box", note: "Outstanding required documents keep the submission-readiness check red; the applicant can still sign and wait.", wide: true },
    ],
  },
  {
    id: "SCR_ENROLL_SIGN",
    slug: "enroll-esignature",
    name: "E-Signature",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "consumer",
    user: "Applicant and any additional required signer",
    purpose:
      "Presents the completed application for review and captures a legally attributable signature with the disclosures, consent and evidence record the carrier and regulators require.",
    actions: ["Review the completed application", "Adopt a signature", "Sign", "Decline to sign", "Route to a second signer", "Download the signed copy"],
    objects: ["Signature request", "Signer list and order", "Signed document artifact", "Signature evidence record (timestamp, IP, method, consent)"],
    config: [
      "Which forms require signature and by whom (Form Configurator signature settings)",
      "Signature method: typed adoption, drawn, or third-party provider",
      "Whether an agent signature/attestation is also required",
      "Disclosure text presented at signing",
    ],
    acl: [
      "Only the named signer can sign; agents can send and remind but never sign for the applicant",
      "Agent attestation is a distinct signature block with its own audit entry",
      "Post-signature edits invalidate the signature and require re-signing — silent amendment is not possible",
    ],
    drawer: [
      "Context: application and signer set",
      "Summary: who has signed, who is pending",
      "Guidance: what signing commits the applicant to",
      "Help & FAQ: e-signature validity",
      "Audit: full signature evidence record",
      "Next actions: remind signer, download, proceed to readiness check",
    ],
    assistant: "May explain the signing mechanics only. It may not summarise or characterise what the applicant is agreeing to.",
    source: SRC,
    assumptions: [
      "E-signature may be native or delegated to a provider; the wireframe treats the provider as an integration seam, not a screen.",
    ],
    canvas: [
      { title: "Application review", id: "SIGN-REVIEW", kind: "box", note: "Read-only rendering of every answer with an edit link per section. Editing returns to the form and clears any prior signature.", wide: true },
      { title: "Disclosures & consent", id: "SIGN-DISCLOSE", kind: "checks", items: ["Truthfulness attestation", "Authorization to submit to carrier", "Electronic signature consent", "Fraud warning (state-specific)"] },
      { title: "Signature block", id: "SIGN-BLOCK", kind: "fields", items: ["Signer name", "Adopted signature", "Date (system)", "Agent attestation block (when configured)"] },
      { title: "Evidence record", id: "SIGN-EVIDENCE", kind: "kv", items: ["Timestamp", "IP address", "Authentication method", "Document hash", "Consent version"], wide: true },
    ],
  },
  {
    id: "SCR_ENROLL_REVIEW",
    slug: "enroll-agent-review",
    name: "Agent / Admin Review Queue",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agent, agency admin or a back-office reviewer",
    purpose:
      "Internal quality gate between a signed application and submission. Reviewers check answers, documents and attribution, and either release the application or return it with reasons.",
    actions: ["Open an application from the queue", "Approve for submission", "Return to applicant with reasons", "Reassign reviewer", "Add internal note", "Override a soft warning with justification"],
    objects: ["Review queue", "Application", "Documents and their review states", "Reviewer assignment", "Internal notes (never consumer-visible)"],
    config: [
      "Whether review is mandatory, sampled or off per product",
      "Queue routing rules (by product, state, agency, agent tenure)",
      "Which warnings are overridable and by which role",
    ],
    acl: [
      "enrollment.review is separate from enrollment.edit — reviewers see the queue only for entities in their scope",
      "Downline applications appear to an upline reviewer only when the relationship grants data visibility",
      "Overrides require a justification and are attributed permanently",
    ],
    drawer: [
      "Context: application under review and its route",
      "Summary: readiness signals and open warnings",
      "Guidance: what this reviewer is responsible for checking",
      "Help & FAQ: return vs reject",
      "Audit: reviewer actions, overrides and justifications",
      "Next actions: approve, return, reassign",
    ],
    assistant: "Can surface which checks failed and where. It cannot approve, and no AI-drafted return reason is sent without human confirmation.",
    source: SRC,
    assumptions: ["Review is a workflow state on the application, not a separate object."],
    canvas: [
      { title: "Queue", id: "REVIEW-QUEUE", kind: "table", items: ["Applicant", "Product / carrier", "Agent", "Signed", "Readiness", "Age", "Assigned to"], wide: true },
      { title: "Answer review", id: "REVIEW-ANSWERS", kind: "list", items: ["Section with change history", "Flagged answer", "Applicant-only field marker"] },
      { title: "Document review", id: "REVIEW-DOCS", kind: "list", items: ["Accept", "Reject with reason", "Request replacement"] },
      { title: "Decision", id: "REVIEW-DECISION", kind: "actions", items: ["Approve for submission", "Return with reasons", "Reassign", "Add internal note"], wide: true, note: "Return reasons are consumer-visible; internal notes are not. The distinction is explicit on screen." },
    ],
  },
  {
    id: "SCR_ENROLL_READY",
    slug: "enroll-readiness",
    name: "Submission Readiness Checks",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agent, agency admin, or the system acting before an automated submission",
    purpose:
      "Deterministic pre-flight: every condition that must be true before an application can leave ABox, shown as pass/fail with the blocking reason and the fix.",
    actions: ["Run checks", "Open a failing check's record", "Waive a waivable check with justification", "Release to submission", "Schedule submission for a future date"],
    objects: ["Check result set", "Application", "Appointment and licensing records for the writing agent", "Payment authorization state", "Carrier submission channel"],
    config: [
      "Which checks are blocking vs advisory per carrier",
      "Whether licensing/appointment checks run against live records or a cached snapshot",
      "Who may waive, and which checks are never waivable",
    ],
    acl: [
      "Release to submission requires enrollment.submit plus a valid appointment on the writing paper",
      "Licensing and appointment failures are never waivable regardless of role",
      "Waivers are attributed and reported in the audit report",
    ],
    drawer: [
      "Context: application and its target carrier channel",
      "Summary: count of blocking vs advisory failures",
      "Guidance: how to clear each failing check",
      "Help & FAQ: why licensing checks cannot be waived",
      "Audit: check runs, waivers and releases",
      "Next actions: fix, waive, release, schedule",
    ],
    assistant: "Explains individual checks in plain language. It never releases a submission.",
    source: SRC,
    assumptions: ["Checks are evaluated server-side at release time as well as displayed, so a stale screen cannot release a failing application."],
    canvas: [
      {
        title: "Check results",
        id: "READY-CHECKS",
        kind: "checks",
        items: [
          "All required answers complete",
          "All required documents uploaded and accepted",
          "Signature captured and valid",
          "Writing agent licensed in the applicant's state",
          "Writing agent appointed on the selling paper for this carrier",
          "Product sellable for state and effective date",
          "Payment method captured where the carrier requires it at submission",
          "Rate version still valid for the requested effective date",
        ],
        wide: true,
      },
      { title: "Blocking summary", id: "READY-BLOCK", kind: "box", note: "Blocking failures disable release. Advisory failures show a warning and are recorded if the user proceeds." },
      { title: "Release", id: "READY-RELEASE", kind: "actions", items: ["Release to submission", "Schedule submission", "Waive advisory with justification"] },
    ],
  },
  {
    id: "SCR_ENROLL_EDI",
    slug: "enroll-edi-output",
    name: "Standard EDI Template Output",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: "MOD_FORMS_ENROLLMENT + MOD_OUTPUTS_DOCS",
    packet: "M2-Cand",
    shell: "internal",
    user: "Agency admin or platform operations",
    purpose:
      "Shows the mapped EDI enrollment output for an application or batch: which template version, how application fields map to segments, validation of the generated file, and its transmission record.",
    actions: ["Preview generated EDI", "Validate against the template", "Download file", "Reprocess a failed record", "Open the field mapping", "View transmission history"],
    objects: ["EDI template version", "Field mapping", "Generated transaction / batch", "Validation errors", "Transmission log"],
    config: [
      "Template per carrier and transaction type",
      "Field mapping and default/derived values",
      "Batch window and grouping rules",
      "Which environment the file targets (test vs production)",
    ],
    acl: [
      "edi.view for operations roles; raw file download is a separate, higher permission because the payload contains full PII",
      "Agency users see only their own entities' records; mapping editing is platform-level",
    ],
    drawer: [
      "Context: template version, carrier, batch",
      "Summary: record counts, valid vs rejected",
      "Guidance: how to read a validation failure",
      "Help & FAQ: EDI vs API submission",
      "Audit: generation, download and transmission events",
      "Next actions: reprocess, download, notify carrier contact",
    ],
    assistant: "Explains validation failures against the template. It cannot edit mappings.",
    source: SRC,
    assumptions: [
      "A standard template exists per carrier with per-carrier overrides; ABox does not negotiate ad-hoc formats per application.",
    ],
    canvas: [
      { title: "Batch header", id: "EDI-HDR", kind: "kv", items: ["Carrier", "Template version", "Transaction type", "Environment", "Record count", "Generated at"], wide: true },
      { title: "Field mapping", id: "EDI-MAP", kind: "table", items: ["Application field", "Segment / element", "Transform", "Default", "Required"] },
      { title: "Validation", id: "EDI-VALID", kind: "list", items: ["Record passed", "Record rejected with element-level reason", "Reprocess control"] },
      { title: "Transmission log", id: "EDI-TX", kind: "timeline", items: ["Generated", "Transmitted", "Acknowledged", "Carrier response received"], wide: true },
    ],
  },
  {
    id: "SCR_ENROLL_API",
    slug: "enroll-api-submission",
    name: "API Hook Submission Path",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: "MOD_FORMS_ENROLLMENT + MOD_ADMIN_CONFIG",
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform operations, with read access for agency admins",
    purpose:
      "The real-time alternative to EDI: shows the configured carrier API endpoint for a product, the request/response for a submission attempt, retry state and idempotency, so a failed submission is diagnosable without leaving ABox.",
    actions: ["View connection config", "Send a test submission", "Retry a failed submission", "Open request/response detail", "Switch a product between EDI and API path", "Rotate credentials"],
    objects: ["Carrier connection", "Submission attempt", "Request and redacted response payloads", "Retry policy and idempotency key", "Credential reference (never the value)"],
    config: [
      "Endpoint, auth method and environment per carrier",
      "Retry policy, backoff and dead-letter handling",
      "Which products submit via API vs EDI",
      "Payload field mapping and version",
    ],
    acl: [
      "integration.manage is platform-level; agency admins get read-only submission status without payloads",
      "Credentials are referenced by name only — no screen ever displays a secret value",
      "Payload views are PII-redacted by default; unredacted view is a separately logged permission",
    ],
    drawer: [
      "Context: carrier connection and product",
      "Summary: recent success rate and error classes",
      "Guidance: what each error class means",
      "Help & FAQ: when to retry vs re-submit",
      "Audit: attempts, retries, credential rotations",
      "Next actions: retry, escalate, switch path",
    ],
    assistant: "Classifies errors and points to the failing field. It cannot retry or change configuration.",
    source: SRC,
    assumptions: ["Idempotency keys prevent duplicate carrier submissions on retry; this is an explicit design requirement, not an option."],
    canvas: [
      { title: "Connection", id: "API-CONN", kind: "kv", items: ["Carrier", "Endpoint", "Auth method", "Credential reference", "Environment", "Status"], wide: true },
      { title: "Attempt detail", id: "API-ATTEMPT", kind: "list", items: ["Request (redacted)", "Response (redacted)", "HTTP status / carrier code", "Idempotency key", "Duration"] },
      { title: "Retry state", id: "API-RETRY", kind: "box", note: "Attempt 2 of 3, next retry in 15 minutes. Dead-letter after final failure raises a task to operations." },
      { title: "Path selection", id: "API-PATH", kind: "actions", items: ["Use API path", "Use EDI path", "Send test submission"], wide: true },
    ],
  },
  {
    id: "SCR_ENROLL_PAY",
    slug: "enroll-payment-fe",
    name: "Payment Capture (Front End)",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "consumer",
    user: "Applicant; agent may assist but never handles card data directly",
    purpose:
      "Front-end seam for binding payment: captures the payment method and authorization the carrier requires at submission, while the money movement itself belongs to the carrier or a processor, not to ABox.",
    actions: ["Choose payment method", "Enter payment details in the processor-hosted field", "Authorize initial and recurring draft", "Skip when the carrier bills directly", "Retry a declined authorization"],
    objects: ["Payment authorization record", "Method token (never raw card/bank data)", "Draft schedule requested", "Carrier billing preference"],
    config: [
      "Whether payment is captured at submission, after approval, or not at all per carrier/product",
      "Processor connection per agency or per carrier",
      "Accepted methods (ACH, card) per product",
      "Copy explaining who ultimately bills the member",
    ],
    acl: [
      "No ABox role can see full card or bank numbers — the fields are processor-hosted and only a token returns",
      "Agents in assisted mode see a masked confirmation and never a re-playable input",
      "payment.view shows authorization status only",
    ],
    drawer: [
      "Context: application, carrier billing model",
      "Summary: authorization status and amount",
      "Guidance: what will be drafted and when",
      "Help & FAQ: who charges me, the agency or the carrier",
      "Audit: authorization attempts and results (no payload)",
      "Next actions: retry, change method, continue",
    ],
    assistant: "Explains billing mechanics and timing. It never touches payment data and cannot quote an exact draft date the carrier has not confirmed.",
    source: `${SRC}; payment front-end seam is P1-Build per the reconciliation review — money movement is out of ABox scope`,
    assumptions: [
      "ABox is not a merchant of record in Phase 1. This screen captures authorization and hands off; no ledger of member payments is built here.",
    ],
    canvas: [
      { title: "Billing explanation", id: "PAY-EXPLAIN", kind: "box", note: "States plainly who bills the member, first draft timing and what this authorization covers.", wide: true },
      { title: "Method selection", id: "PAY-METHOD", kind: "tabs", items: ["Bank draft (ACH)", "Card", "Carrier bills me directly"] },
      { title: "Hosted fields", id: "PAY-FIELDS", kind: "box", note: "Processor-hosted iframe. ABox renders the frame and receives a token only — card and account numbers never reach ABox." },
      { title: "Authorization", id: "PAY-AUTH", kind: "checks", items: ["Authorize initial payment", "Authorize recurring draft", "Understand that coverage is not active until the carrier confirms"], wide: true },
    ],
  },
  {
    id: "SCR_ENROLL_STATUS",
    slug: "enroll-submission-status",
    name: "Submission Status",
    group: "Off-exchange enrollment",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agent and agency admin internally; a simplified version renders in the branded member workspace",
    purpose:
      "One truthful status surface per application after release: where it is with the carrier, what came back, what the member sees, and what the agency must do next.",
    actions: ["Filter by status", "Open an application", "Record a carrier response received off-platform", "Resubmit", "Notify the member", "Create a follow-up task"],
    objects: ["Application", "Submission attempts (EDI or API)", "Carrier acknowledgements and responses", "Policy number when issued", "Member-visible status mapping"],
    config: [
      "Mapping from raw carrier status codes to ABox statuses and to member-facing language",
      "Which statuses trigger a notification and to whom",
      "SLA thresholds that raise a task",
    ],
    acl: [
      "Scoped by entity hierarchy and agent assignment; an upline sees downline submissions only where the relationship grants visibility",
      "Member-facing status text is a mapped subset — internal carrier codes are never exposed to the member workspace",
    ],
    drawer: [
      "Context: application, carrier, channel",
      "Summary: current status, age, last carrier contact",
      "Guidance: what this status means and the expected next event",
      "Help & FAQ: pending vs issued vs declined",
      "Audit: every status transition with source (system or manual)",
      "Next actions: resubmit, notify member, create task",
    ],
    assistant: "Explains statuses and expected timelines. It never predicts approval or promises an issue date.",
    source: SRC,
    assumptions: ["Some carriers respond off-platform; manual status entry is supported and clearly labelled as manually recorded."],
    canvas: [
      { title: "Status board", id: "STATUS-BOARD", kind: "tabs", items: ["Draft", "In review", "Submitted", "Pending carrier", "Info requested", "Issued", "Declined", "Withdrawn"], wide: true },
      { title: "Application list", id: "STATUS-LIST", kind: "table", items: ["Applicant", "Product", "Agent", "Channel", "Status", "Age", "Last event"], wide: true },
      { title: "Application timeline", id: "STATUS-TIMELINE", kind: "timeline", items: ["Signed", "Released", "Transmitted", "Acknowledged", "Info requested", "Issued — policy number recorded"] },
      { title: "Member-visible mapping", id: "STATUS-MEMBER", kind: "kv", items: ["Internal: PEND-INFO", "Member sees: 'The carrier needs one more document'"], note: "Every internal status must have an approved member-facing phrase before it can be surfaced externally." },
    ],
  },
]);
