import { SRC_BLUEPRINT, SRC_IA, SRC_RECON, screens } from "./types";

const WS = "WS_AGENCY and WS_PLATFORM — outputs render with the branding of the presenting entity";
const MOD = "MOD_OUTPUTS_DOCS";
const SRC = `${SRC_BLUEPRINT} (quote packet, benefit comparison, application summary, submission packet, white-labelled documents, dashboards, attribution and audit reporting, AI interaction reporting); ${SRC_IA} (SCR_OUT_*, SCR_RPT_*); ${SRC_RECON}`;

export const OUTPUTS = screens([
  {
    id: "SCR_OUT_QUOTE_PACKET",
    slug: "out-quote-packet",
    name: "Quote Packet & Benefit Comparison Output",
    group: "Outputs, documents & reporting",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Agent or agency admin producing it; consumer or member receives it",
    purpose:
      "Turns a quote into a durable, branded artifact the consumer can keep: the plans considered, side-by-side benefits, the assumptions behind every number and the required disclosures — the same figures as the screen, never a rounder story.",
    actions: [
      "Select plans to include",
      "Choose layout",
      "Apply brand",
      "Preview",
      "Generate PDF",
      "Email, download or share by link",
      "Regenerate after a quote change",
    ],
    objects: [
      "Quote and its pinned rate version",
      "Selected plan set",
      "Benefit comparison matrix",
      "Assumption and disclosure block",
      "Generated document artifact with version",
      "Delivery record",
    ],
    config: [
      "Which benefit attributes appear in the comparison per product line",
      "Layout templates available",
      "Brand theme and licensure footer",
      "Whether estimated subsidy figures may be included and how they must be labelled",
      "Document expiry messaging",
    ],
    acl: [
      "quote.view plus outputs.generate; the packet inherits the quote's ACL and a shared link is read-only and expiring",
      "Internal-only data — commission projections, internal notes, lead scoring — can never appear in a consumer output",
      "Regeneration creates a new version; prior versions remain retrievable for audit",
    ],
    drawer: [
      "Context: quote, plans included, brand applied",
      "Summary: document version, generated at, delivered to",
      "Guidance: what must be disclosed on any quote artifact",
      "Help & FAQ: why the packet expires",
      "Audit: generation, delivery and access events",
      "Next actions: send, download, regenerate",
    ],
    assistant:
      "Explains what the packet contains and how to share it. It cannot alter figures or omit disclosures.",
    source: SRC,
    assumptions: [
      "Every generated artifact pins the rate version and effective date so a stale packet is self-evidently stale.",
    ],
    m1Seam:
      "Consumes Module 1 quotes and compare selections (UX-011, UX-019) as a read-only source. Module 1 screens are unchanged.",
    canvas: [
      {
        title: "Packet builder",
        id: "QPK-BUILD",
        kind: "actions",
        items: [
          "Include selected plans",
          "Include compare matrix",
          "Include subsidy estimate",
          "Include agent contact block",
          "Layout template",
        ],
        wide: true,
      },
      {
        title: "Comparison matrix",
        id: "QPK-MATRIX",
        kind: "table",
        items: ["Attribute", "Plan A", "Plan B", "Plan C"],
        wide: true,
      },
      {
        title: "Assumptions & disclosures",
        id: "QPK-DISCLOSE",
        kind: "box",
        note: "Rate version, effective date, household inputs, subsidy estimate label, licensure and not-a-government-site disclosure — all printed, not optional.",
        wide: true,
      },
      {
        title: "Delivery",
        id: "QPK-DELIVER",
        kind: "actions",
        items: ["Email to consumer", "Download PDF", "Share expiring link", "Regenerate"],
      },
    ],
  },
  {
    id: "SCR_OUT_APP_PACKET",
    slug: "out-application-packet",
    name: "Application Summary & Enrollment / Submission Packet",
    group: "Outputs, documents & reporting",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agent, agency admin, back-office reviewer; consumer receives the summary copy",
    purpose:
      "Two related artifacts: the applicant's plain-language summary of what they applied for, and the complete submission packet — signed forms, documents, evidence and attribution — assembled for the carrier or for the file.",
    actions: [
      "Generate application summary",
      "Assemble submission packet",
      "Include or exclude documents",
      "Regenerate after a correction",
      "Download",
      "Send to the carrier contact",
      "Archive to the member record",
    ],
    objects: [
      "Application and its pinned form version",
      "Signed form artifact and signature evidence",
      "Uploaded documents",
      "Attribution block (selling agency, selling agent, appointed NPN)",
      "Packet manifest with checksums",
      "Delivery record",
    ],
    config: [
      "Packet composition rules per carrier",
      "Whether a cover sheet is required and its content",
      "Redaction rules for the consumer copy vs the carrier copy",
      "Retention period per artifact type",
    ],
    acl: [
      "documents.view on the application; assembling a carrier packet requires enrollment.submit",
      "The consumer copy is redacted per policy — full SSN and internal notes never appear on it",
      "Every packet download is logged because it contains complete PII",
    ],
    drawer: [
      "Context: application, carrier and packet version",
      "Summary: items included, missing items",
      "Guidance: difference between the consumer summary and the carrier packet",
      "Help & FAQ: what to do when the carrier asks for a re-send",
      "Audit: assembly, download and send events with actor",
      "Next actions: send, download, archive",
    ],
    assistant:
      "Lists what the packet contains and what is missing. It cannot send a packet to a carrier.",
    source: SRC,
    assumptions: [
      "The packet manifest records a checksum per item so a re-send can be proven identical to the original.",
    ],
    canvas: [
      {
        title: "Manifest",
        id: "APK-MANIFEST",
        kind: "table",
        items: [
          "Item",
          "Type",
          "Version",
          "Included in consumer copy",
          "Included in carrier packet",
          "Checksum",
        ],
        wide: true,
      },
      {
        title: "Consumer summary",
        id: "APK-SUMMARY",
        kind: "box",
        note: "Plain-language recap: who applied, for what plan, effective when, what happens next, who to contact. Redacted per policy.",
      },
      {
        title: "Carrier packet",
        id: "APK-CARRIER",
        kind: "box",
        note: "Signed forms, evidence record, documents and attribution block, assembled to the carrier's composition rules.",
      },
      {
        title: "Delivery",
        id: "APK-DELIVER",
        kind: "actions",
        items: [
          "Send to carrier contact",
          "Download",
          "Archive to member record",
          "Regenerate after correction",
        ],
        wide: true,
      },
    ],
  },
  {
    id: "SCR_OUT_BRANDING",
    slug: "out-document-branding",
    name: "White-Labelled Document Branding & Product Documents",
    group: "Outputs, documents & reporting",
    workspace: WS,
    module: "MOD_OUTPUTS_DOCS + MOD_ADMIN_CONFIG",
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, platform brand administrator",
    purpose:
      "Controls how every generated document looks for a given entity — logo, colours, typography, footer, licensure line — and manages the carrier and product documents that get attached alongside them, all within platform guardrails.",
    actions: [
      "Upload brand assets",
      "Set document header and footer",
      "Set licensure and disclosure lines",
      "Preview across document types",
      "Manage product document library",
      "Publish brand version",
    ],
    objects: [
      "Brand theme",
      "Document header/footer definition",
      "Licensure and disclosure text blocks",
      "Product document library entries",
      "Brand version",
      "Preview renders",
    ],
    config: [
      "Logo, colour and typography within platform-approved ranges",
      "Which document types are brandable",
      "Locked content areas (required disclosures, non-discrimination notice)",
      "Inheritance: child entities inherit the parent brand unless granted their own",
    ],
    acl: [
      "branding.manage within your own subtree; locked content areas cannot be edited by any agency role",
      "Removing a required licensure or disclosure line is refused with the guardrail rule shown",
      "Brand publishing is versioned so an artifact can always be reproduced with the brand that was in force",
    ],
    drawer: [
      "Context: entity, brand version, inheritance state",
      "Summary: document types affected, locked areas",
      "Guidance: what you may and may not change",
      "Help & FAQ: why my footer cannot be removed",
      "Audit: brand changes and publishes",
      "Next actions: preview, publish, manage inheritance",
    ],
    assistant: "Explains which parts of a document are configurable and which are locked, and why.",
    source: SRC,
    assumptions: [
      "Documents reproduce with the brand version in force at generation time, not the current brand.",
    ],
    canvas: [
      {
        title: "Brand assets",
        id: "BRD-ASSETS",
        kind: "fields",
        items: [
          "Logo",
          "Primary colour",
          "Secondary colour",
          "Typography",
          "Marketplace display name",
        ],
        wide: true,
      },
      {
        title: "Header / footer",
        id: "BRD-HF",
        kind: "editor",
        items: ["Header block", "Footer block", "Licensure line", "Locked disclosure block"],
        wide: true,
      },
      {
        title: "Locked areas",
        id: "BRD-LOCKED",
        kind: "checks",
        items: [
          "Non-discrimination notice",
          "Not-a-government-website disclosure",
          "Privacy notice link",
          "Carrier attribution where required",
        ],
      },
      {
        title: "Product documents",
        id: "BRD-PRODDOCS",
        kind: "table",
        items: ["Document", "Product", "Type", "Attach automatically", "Version"],
      },
    ],
  },
  {
    id: "SCR_OUT_SHARE",
    slug: "out-export-print-share",
    name: "Export, Print & Share Controls",
    group: "Outputs, documents & reporting",
    workspace: WS,
    module: MOD,
    packet: "P1-Later",
    shell: "internal",
    user: "Any internal user producing an output; compliance reviewer auditing it",
    purpose:
      "The single governed path out of ABox: how data and documents leave, who may take them, how they are watermarked, and where every export is recorded.",
    actions: [
      "Export a record set",
      "Print",
      "Create an expiring share link",
      "Revoke a share link",
      "View export history",
      "Request an export that exceeds your limit",
    ],
    objects: [
      "Export job",
      "Export scope and row count",
      "Watermark metadata",
      "Share link with expiry and access log",
      "Export approval request",
    ],
    config: [
      "Export formats permitted per role",
      "Row limits and approval thresholds",
      "Watermark content (viewer, scope, timestamp)",
      "Share link lifetime and whether recipient verification is required",
      "Which object types may never be exported in bulk",
    ],
    acl: [
      "data.export is a distinct permission from viewing; seeing a record does not imply the right to bulk-export it",
      "Exports containing sensitive attributes require the sensitive-data permission and are always watermarked",
      "Share links are read-only, expiring and revocable, and every access is logged with the accessor",
      "Exceeding a row limit routes to approval rather than silently truncating",
    ],
    drawer: [
      "Context: what is being exported and its scope",
      "Summary: rows, sensitive fields included, format",
      "Guidance: your export limits and what needs approval",
      "Help & FAQ: revoking a share link",
      "Audit: every export and share access",
      "Next actions: export, request approval, revoke a link",
    ],
    assistant: "Explains export limits and what an export will contain before it runs.",
    source: SRC,
    assumptions: [
      "Bulk export of PII is treated as a high-risk action requiring both permission and audit, per the North Star governance posture.",
    ],
    canvas: [
      {
        title: "Export scope",
        id: "EXP-SCOPE",
        kind: "kv",
        items: [
          "Object type",
          "Filters applied",
          "Row count",
          "Sensitive fields included",
          "Format",
        ],
        wide: true,
      },
      {
        title: "Limits & approval",
        id: "EXP-LIMIT",
        kind: "box",
        note: "Row count exceeds your limit. The export routes to an approver rather than truncating or failing silently.",
      },
      {
        title: "Share links",
        id: "EXP-SHARE",
        kind: "table",
        items: ["Link", "Object", "Created by", "Expires", "Accesses", "Revoke"],
      },
      {
        title: "Export history",
        id: "EXP-HIST",
        kind: "table",
        items: ["When", "Who", "Object", "Rows", "Sensitive", "Watermark id"],
        wide: true,
      },
    ],
  },
  {
    id: "SCR_RPT_DASHBOARDS",
    slug: "rpt-dashboards",
    name: "Basic Dashboards",
    group: "Outputs, documents & reporting",
    workspace: WS,
    module: "MOD_REPORTING",
    packet: "P1-Later",
    shell: "internal",
    user: "Agent (own book), agency admin (entity), platform (all)",
    purpose:
      "The Phase 1 operating picture: pipeline, quoting and enrollment volume, submission health, and task load — each metric ACL-scoped and each stating the scope it was computed over.",
    actions: [
      "Switch scope",
      "Change period",
      "Drill into a metric",
      "Pin a widget",
      "Export the view",
      "Set a target",
    ],
    objects: [
      "Dashboard definition",
      "Widget set",
      "Metric definitions",
      "Scope selector",
      "Drill-through record lists",
    ],
    config: [
      "Which widgets are available per role and workspace",
      "Metric definitions and their windows",
      "Default period and scope per role",
      "Targets and thresholds",
    ],
    acl: [
      "Every widget is computed only over records the viewer may see; the dashboard prints its scope so differing totals are explainable",
      "Commission widgets are absent entirely without commission.view",
      "Drill-through respects the same ACL as the underlying list screen — no metric can leak a record the user cannot open",
    ],
    drawer: [
      "Context: scope, period and role",
      "Summary: headline metrics",
      "Guidance: how each metric is defined",
      "Help & FAQ: why my numbers differ from my manager's",
      "Audit: dashboard exports",
      "Next actions: drill through, export, adjust period",
    ],
    assistant: "Explains a metric definition and why a number moved. It cannot change definitions.",
    source: SRC,
    assumptions: [
      "Phase 1 dashboards are fixed widget sets with scope and period controls, not a free-form BI builder.",
    ],
    canvas: [
      {
        title: "Scope & period",
        id: "DSH-SCOPE",
        kind: "actions",
        items: ["Own book", "Entity", "Subtree", "This month", "Quarter", "Plan year"],
        wide: true,
      },
      {
        title: "Pipeline widgets",
        id: "DSH-PIPE",
        kind: "cards",
        items: [
          "New leads",
          "Quotes created",
          "Quotes shared",
          "Applications started",
          "Applications signed",
          "Policies issued",
        ],
        wide: true,
      },
      {
        title: "Health widgets",
        id: "DSH-HEALTH",
        kind: "cards",
        items: [
          "Submissions pending carrier",
          "Info-requested aging",
          "Documents outstanding",
          "Licenses expiring",
        ],
      },
      {
        title: "Scope statement",
        id: "DSH-STMT",
        kind: "box",
        note: "Prints the entity and agent scope used, so two users comparing dashboards can reconcile the difference.",
      },
    ],
  },
  {
    id: "SCR_RPT_ATTRIBUTION",
    slug: "rpt-attribution",
    name: "Attribution Reports",
    group: "Outputs, documents & reporting",
    workspace: WS,
    module: "MOD_REPORTING",
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, platform, marketing owner",
    purpose:
      "Traces outcomes back to their origin — marketplace, campaign, referral source, shared quote, agent — so an agency can see which channels actually produce enrollments, not just traffic.",
    actions: [
      "Choose attribution model",
      "Group by source dimension",
      "Compare periods",
      "Drill to leads and policies",
      "Export",
      "Schedule delivery",
    ],
    objects: [
      "Attribution facts",
      "Source dimensions (marketplace, campaign, referral source, shared quote, agent, entity)",
      "Attribution model (first touch, last touch, source-of-record)",
      "Conversion stages",
      "Export record",
    ],
    config: [
      "Attribution model default and which models are available",
      "Campaign and source tagging conventions",
      "Conversion stage definitions",
      "Lookback window",
    ],
    acl: [
      "reporting.view scoped by entity; referral-source detail is visible only to the sponsoring entity",
      "Consumer-level PII is not exposed in aggregate attribution views; drill-through applies the record-level ACL",
      "Cross-agency comparison is platform-only",
    ],
    drawer: [
      "Context: model, dimension and period",
      "Summary: conversions by source",
      "Guidance: first touch vs last touch and when each misleads",
      "Help & FAQ: why unattributed traffic exists",
      "Audit: report runs and exports",
      "Next actions: change model, drill through, export",
    ],
    assistant: "Explains how a conversion was attributed and which model produced it.",
    source: SRC,
    assumptions: [
      "Attribution uses the anonymous session id created at marketplace landing, joined to the lead on registration.",
    ],
    canvas: [
      {
        title: "Model & dimension",
        id: "ATR-MODEL",
        kind: "actions",
        items: [
          "First touch",
          "Last touch",
          "Source of record",
          "Group by: marketplace / campaign / referral / agent",
        ],
        wide: true,
      },
      {
        title: "Funnel by source",
        id: "ATR-FUNNEL",
        kind: "table",
        items: [
          "Source",
          "Sessions",
          "Quotes",
          "Shared quotes",
          "Applications",
          "Issued",
          "Conversion rate",
        ],
        wide: true,
      },
      {
        title: "Unattributed",
        id: "ATR-UNATTR",
        kind: "box",
        note: "Unattributed volume is shown explicitly rather than distributed across sources.",
      },
      {
        title: "Drill-through",
        id: "ATR-DRILL",
        kind: "list",
        items: ["Leads from this source", "Policies from this source", "Record-level ACL applies"],
      },
    ],
  },
  {
    id: "SCR_RPT_AUDIT_AI",
    slug: "rpt-audit-ai",
    name: "Audit Reports & AI Interaction Reporting",
    group: "Outputs, documents & reporting",
    workspace: WS,
    module: "MOD_REPORTING + MOD_AI",
    packet: "P1-Later",
    shell: "internal",
    user: "Compliance reviewer, agency admin, platform governance",
    purpose:
      "The evidence surface: who did what to which record, which overrides and waivers were used, what consents were captured, and every AI interaction with its outcome — the reports a regulator, carrier or internal auditor asks for.",
    actions: [
      "Build an audit report by object, actor or event",
      "Filter to sensitive actions",
      "Report on AI interactions and human decisions",
      "Export an audit pack",
      "Schedule a recurring compliance report",
    ],
    objects: [
      "Audit event records",
      "Sensitive-action subset (exports, overrides, waivers, ACL changes, sensitive-data views)",
      "Consent records",
      "AI interaction records with prompt context, output, model/ruleset version and human decision",
      "Audit pack export",
    ],
    config: [
      "Retention period per event class",
      "Which actions are classified sensitive",
      "Recurring compliance report definitions and recipients",
      "Whether AI prompt content is retained in full or summarised",
    ],
    acl: [
      "audit.view is a distinct, narrowly held permission; agency scope for agency admins, full scope for platform governance",
      "Audit records are append-only and cannot be edited or deleted by any role",
      "Viewing an audit record that contains sensitive data is itself an audited event",
      "AI interaction records show whether output reached a consumer and who confirmed it",
    ],
    drawer: [
      "Context: report scope, period and event classes",
      "Summary: event counts, sensitive actions, AI interactions",
      "Guidance: what each event class proves",
      "Help & FAQ: assembling an audit response",
      "Audit: audit-report runs and exports are themselves audited",
      "Next actions: export pack, schedule, narrow scope",
    ],
    assistant:
      "Helps locate the events relevant to a question. It cannot alter or suppress any record.",
    source: SRC,
    assumptions: [
      "Every AI interaction that could reach a consumer or change a record carries a human-decision record, per the Module 1 AI review pattern generalised to the platform.",
    ],
    m1Seam:
      "Reports on the AI review and confirmation events produced by Module 1 (UX-026) among all other AI interactions. UX-026 is unchanged.",
    canvas: [
      {
        title: "Report scope",
        id: "AUD-SCOPE",
        kind: "fields",
        items: ["Object type", "Actor", "Event class", "Entity", "Date range"],
        wide: true,
      },
      {
        title: "Event grid",
        id: "AUD-GRID",
        kind: "table",
        items: ["When", "Actor", "Object", "Event", "Before / after", "Justification", "Sensitive"],
        wide: true,
      },
      {
        title: "AI interaction report",
        id: "AUD-AI",
        kind: "table",
        items: [
          "When",
          "Surface",
          "Model / ruleset version",
          "Output type",
          "Guardrail result",
          "Human decision",
          "Reached consumer",
        ],
        wide: true,
      },
      {
        title: "Sensitive actions",
        id: "AUD-SENS",
        kind: "list",
        items: [
          "Bulk exports",
          "ACL overrides",
          "Readiness waivers",
          "Attribution corrections",
          "Sensitive-data views",
          "Consent changes recorded on behalf of a member",
        ],
      },
      {
        title: "Audit pack",
        id: "AUD-PACK",
        kind: "actions",
        items: [
          "Export audit pack",
          "Schedule recurring compliance report",
          "Print for a carrier request",
        ],
      },
    ],
  },
]);
