import { SRC_BLUEPRINT, SRC_IA, SRC_NORTH, screens } from "./types";

const WS = "WS_AGENCY (paper-owning entity) and WS_PLATFORM";
const MOD = "MOD_APPOINTMENTS_PAPER (nested — never a top-level menu item)";
const SRC = `${SRC_BLUEPRINT} (B2B2C paper sharing, appointed agency NPN override, selling agency/agent markers, referral rewards, revenue splits); ${SRC_IA} (SCR_PAPER_*); ${SRC_NORTH} relationship and event model`;

export const PAPER = screens([
  {
    id: "SCR_PAPER_APPOINTMENT",
    slug: "paper-appointment-record",
    name: "Carrier Appointment Record",
    group: "Appointments, paper, referrals & splits",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agency admin of the paper-owning entity; platform administrator",
    purpose:
      "The record of an entity's appointment with a carrier: what it covers, who owns the paper, the appointed agency NPN used on submissions, and its lifecycle dates. Everything about who may write flows from here.",
    actions: ["Create an appointment", "Record carrier reference and dates", "Set the appointed agency NPN", "Set covered products and states", "Suspend or terminate", "Attach evidence"],
    objects: ["Carrier appointment", "Paper owner entity", "Appointed agency NPN", "Covered product and state set", "Effective and termination dates", "Evidence documents"],
    config: [
      "Which entities may own paper",
      "Whether appointment records require platform verification",
      "Product and state coverage granularity",
      "Whether an appointment supports sub-agency sharing at all",
    ],
    acl: [
      "appointment.manage held only by the paper-owning entity and platform — high sensitivity",
      "Downline entities can see that an appointment exists and its scope, never its commercial terms",
      "Termination immediately blocks new submissions on that paper while preserving history",
    ],
    drawer: [
      "Context: carrier, paper owner, appointment scope",
      "Summary: sharing grants issued, agents writing on it, in-flight submissions",
      "Guidance: what terminating this appointment will block",
      "Help & FAQ: appointment vs paper access vs licence",
      "Audit: creation, scope changes, suspensions, terminations",
      "Next actions: manage sharing, set NPN override, view submissions",
    ],
    assistant: "Explains the scope of the appointment and what it enables. It cannot alter appointments.",
    source: SRC,
    assumptions: ["Appointments are entity-level. Individual-agent carrier appointments, where a carrier requires them, are recorded on the agent's appointment access view."],
    canvas: [
      { title: "Appointment", id: "APR-REC", kind: "fields", items: ["Carrier", "Paper owner entity", "Carrier reference number", "Appointed agency NPN", "Effective from", "Termination date", "Status"], wide: true },
      { title: "Coverage", id: "APR-COVER", kind: "table", items: ["Product", "States", "Can quote", "Can write", "Effective"] },
      { title: "Evidence", id: "APR-EVIDENCE", kind: "list", items: ["Carrier appointment letter", "Commission agreement reference (terms not displayed downline)"] },
      { title: "Dependent activity", id: "APR-DEP", kind: "box", note: "Shows agents writing on this paper and in-flight submissions, so a termination is never a surprise.", wide: true },
    ],
  },
  {
    id: "SCR_PAPER_SHARING",
    slug: "paper-sharing",
    name: "Paper Owner, Visibility & B2B2C Sharing",
    group: "Appointments, paper, referrals & splits",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agency admin of the paper-owning entity",
    purpose:
      "The B2B2C control surface: who may write on this entity's paper, whether the paper is discoverable publicly or only by named partners, and how far down a downline the grant nests.",
    actions: ["Set public / private visibility", "Grant paper access to a partner, downline or upline entity", "Set nesting depth", "Set product and state limits per grant", "Revoke a grant", "Review incoming requests"],
    objects: ["Paper record", "Visibility setting", "Access grant per entity", "Nesting depth rule", "Grant scope (products, states, effective window)", "Request queue"],
    config: [
      "Public (listed to eligible entities) vs private (named grants only)",
      "Whether a grantee may re-grant to its own downline, and to what depth",
      "Per-grant product and state narrowing",
      "Whether grants auto-expire",
    ],
    acl: [
      "paper.grant is one of the most sensitive permissions in the platform — paper-owner only, never inherited by a grantee",
      "A grantee can never widen its own grant nor re-grant beyond the configured nesting depth",
      "A grant confers writing rights only; it does not widen data visibility into the paper owner's book",
      "Every grant and revocation is audited and surfaced in the audit report",
    ],
    drawer: [
      "Context: paper, carrier and visibility setting",
      "Summary: grants active, nested grants, pending requests",
      "Guidance: nesting depth and what a downline of a downline can do",
      "Help & FAQ: public paper listing explained",
      "Audit: grants, re-grants, revocations with actor",
      "Next actions: grant access, set depth, review requests",
    ],
    assistant: "Explains what a specific grant permits and where nesting stops.",
    source: SRC,
    assumptions: ["Paper sharing nests under appointments as a grant model, confirmed in the sitemap audit; it is not a separate top-level module."],
    canvas: [
      { title: "Visibility", id: "SHR-VIS", kind: "actions", items: ["Public — discoverable by eligible entities", "Private — named grants only", "Closed — no sharing"], wide: true },
      { title: "Grants", id: "SHR-GRANTS", kind: "table", items: ["Grantee entity", "Relationship", "Products", "States", "Nesting depth", "Expires", "Status"], wide: true },
      { title: "Nesting model", id: "SHR-NEST", kind: "tree", items: ["Paper owner", "Grantee agency (depth 1)", "Grantee's downline (depth 2 — allowed)", "Depth 3 — blocked by depth limit"] },
      { title: "Requests", id: "SHR-REQ", kind: "list", items: ["Requesting entity", "Requested scope", "Justification", "Approve / decline with reason"] },
    ],
  },
  {
    id: "SCR_PAPER_REQUEST",
    slug: "paper-request-to-write",
    name: "Request to Write on Paper",
    group: "Appointments, paper, referrals & splits",
    workspace: "WS_AGENCY (requesting entity)",
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agency admin of an entity that lacks its own carrier appointment",
    purpose:
      "The requester's side of B2B2C: find an entity whose paper covers what you need, request scoped access with justification, and track the decision — without ever seeing the owner's commercial terms.",
    actions: ["Search available paper", "Request access with scope and justification", "Track request status", "Accept the granted terms", "Withdraw a request", "View why a request was declined"],
    objects: ["Paper discovery listing (public papers only)", "Access request", "Requested scope", "Decision record with reason", "Resulting grant"],
    config: ["Whether requests require agency-admin submission or may come from an agent", "Required justification fields", "Auto-notification to the paper owner"],
    acl: [
      "Only public paper is discoverable; private paper never appears in search",
      "A requester sees scope and decision only — never appointment terms, commission schedules or the owner's book",
      "Accepting a grant stamps the requesting entity as a potential selling agency for that carrier going forward",
    ],
    drawer: [
      "Context: carrier sought and coverage gap being filled",
      "Summary: open requests, granted papers, declines",
      "Guidance: what a granted paper does and does not let you do",
      "Help & FAQ: why is this carrier not listed",
      "Audit: requests, decisions and acceptances",
      "Next actions: request, follow up, accept grant",
    ],
    assistant: "Explains the coverage gap and which listed papers would close it.",
    source: SRC,
    assumptions: ["Discovery is limited to papers the owner has explicitly made public; there is no global directory of every appointment."],
    canvas: [
      { title: "Coverage gap", id: "REQ-GAP", kind: "box", note: "States and products this entity can quote but not write, with the missing carrier named.", wide: true },
      { title: "Available paper", id: "REQ-AVAIL", kind: "table", items: ["Paper owner", "Carrier", "Products", "States", "Nesting allowed", "Request"] },
      { title: "Request form", id: "REQ-FORM", kind: "fields", items: ["Carrier", "Products requested", "States requested", "Expected volume", "Justification"] },
      { title: "Status", id: "REQ-STATUS", kind: "timeline", items: ["Submitted", "Viewed by owner", "Approved with narrowed scope", "Accepted"], wide: true },
    ],
  },
  {
    id: "SCR_PAPER_MARKERS",
    slug: "paper-selling-markers",
    name: "Selling Agency / Selling Agent Markers & NPN Override",
    group: "Appointments, paper, referrals & splits",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Agency admin, platform operations, commission administrator",
    purpose:
      "Resolves attribution on a specific sale: which entity is the selling agency, which producer is the selling agent, which paper it was written on, and which agency NPN goes to the carrier — the four facts commissions and carrier submissions both depend on.",
    actions: ["View resolved attribution for a policy or application", "Set the appointed agency NPN override", "Correct a selling agent with justification", "View the resolution rule that applied", "Lock attribution after settlement"],
    objects: ["Application / policy", "Selling agency marker", "Selling agent marker", "Paper written on", "Appointed agency NPN (with override)", "Attribution resolution trace", "Correction record"],
    config: [
      "Attribution resolution order (writing agent's entity, paper owner, referral source)",
      "Whether NPN override is allowed per carrier and who may set it",
      "Window during which attribution may be corrected",
      "Whether corrections after commission settlement are permitted at all",
    ],
    acl: [
      "Attribution is system-stamped; manual correction requires a dedicated permission plus justification",
      "The NPN override is a carrier-facing value — changing it requires appointment.manage on the paper",
      "After commission settlement, attribution is locked; a change requires a platform-level reversal, not an edit",
    ],
    drawer: [
      "Context: the sale, its paper and its resolved attribution",
      "Summary: selling agency, selling agent, NPN submitted, split applied",
      "Guidance: which rule resolved the attribution and why",
      "Help & FAQ: appointed agency NPN vs selling agency",
      "Audit: every attribution stamp, override and correction with actor and reason",
      "Next actions: correct with justification, view split, view statement line",
    ],
    assistant: "Explains the resolved attribution chain in plain language. It cannot change any marker.",
    source: SRC,
    assumptions: [
      "The appointed agency NPN sent to the carrier may legitimately differ from the selling agency in B2B2C arrangements; both values are stored and shown, never conflated.",
    ],
    canvas: [
      { title: "Resolved attribution", id: "MRK-RESOLVED", kind: "kv", items: ["Selling agency", "Selling agent", "Paper written on", "Paper owner", "Appointed agency NPN submitted", "Referral source"], wide: true },
      { title: "Resolution trace", id: "MRK-TRACE", kind: "list", items: ["Rule evaluated", "Input that matched", "Resulting marker", "Alternative rules skipped"] },
      { title: "NPN override", id: "MRK-NPN", kind: "fields", items: ["Default NPN (from appointment)", "Override NPN", "Reason", "Set by"] },
      { title: "Correction", id: "MRK-CORRECT", kind: "actions", items: ["Correct selling agent", "Correct selling agency", "Lock after settlement"], note: "Corrections require justification and are visible on the commission statement line." },
    ],
  },
  {
    id: "SCR_PAPER_SPLITS",
    slug: "paper-revenue-splits",
    name: "Revenue Split Display",
    group: "Appointments, paper, referrals & splits",
    workspace: WS,
    module: "MOD_APPOINTMENTS_PAPER + MOD_COMMISSIONS",
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, commission administrator; participant entities see only their own share",
    purpose:
      "Shows how revenue on a sale divides between the paper owner, selling agency, upline and referral source — as a read and audit surface, with the split rules themselves configured in commissions.",
    actions: ["View the split on a sale", "View the split rule that produced it", "Filter splits by relationship", "Export split detail", "Flag a disputed split"],
    objects: ["Split allocation per sale", "Split rule reference", "Participant entities and their shares", "Dispute record", "Statement line linkage"],
    config: [
      "Split rule assignment per paper, product or relationship",
      "Whether participants see the full split or only their own share",
      "Rounding and residual handling",
      "Dispute workflow",
    ],
    acl: [
      "commission.view plus split visibility — an entity sees its own share always, and the full split only where the paper owner has enabled transparency",
      "Percentages of other participants are hidden by default; this is a deliberate confidentiality default",
      "Splits are read-only here — editing happens in the commission schedule with its own approvals",
    ],
    drawer: [
      "Context: sale, paper and split rule applied",
      "Summary: participants and shares visible to you",
      "Guidance: why your share is what it is",
      "Help & FAQ: split vs override vs referral reward",
      "Audit: split calculation inputs and rule version",
      "Next actions: open statement line, flag dispute, export",
    ],
    assistant: "Explains the composition of the split visible to the viewer. It never reveals another participant's hidden share.",
    source: SRC,
    assumptions: ["Split calculation is owned by commissions; this screen is display and audit only."],
    canvas: [
      { title: "Sale header", id: "SPL-HDR", kind: "kv", items: ["Policy / application", "Product", "Carrier", "Selling agency", "Paper owner", "Split rule version"], wide: true },
      { title: "Allocation", id: "SPL-ALLOC", kind: "table", items: ["Participant", "Role in the sale", "Basis", "Share", "Amount", "Visible to you"], wide: true },
      { title: "Confidentiality note", id: "SPL-CONF", kind: "box", note: "Shares belonging to other participants are masked unless the paper owner has enabled full transparency for this relationship." },
      { title: "Dispute", id: "SPL-DISPUTE", kind: "actions", items: ["Flag dispute", "Attach evidence", "View dispute status"] },
    ],
  },
  {
    id: "SCR_PAPER_REFERRAL",
    slug: "paper-referral-rewards",
    name: "Referral Reward Setup & Audit",
    group: "Appointments, paper, referrals & splits",
    workspace: WS,
    module: "MOD_APPOINTMENTS_PAPER + MOD_COMMISSIONS",
    packet: "P1-Later",
    shell: "internal",
    user: "Agency admin, commission administrator, compliance reviewer",
    purpose:
      "Configures referral arrangements and their rewards — one-time and recurring — with the eligibility, attribution window and compliance guardrails that keep a referral reward from becoming an unlicensed commission.",
    actions: ["Create a referral program", "Define reward type and amount", "Set attribution window", "Set eligibility conditions", "Approve a reward payout", "View reward audit", "Suspend a program"],
    objects: ["Referral program", "Referral source (entity, partner, member)", "Reward definition (one-time / recurring)", "Attributed referral records", "Reward accrual and payout records", "Compliance attestation"],
    config: [
      "Reward types allowed: flat one-time, recurring per active month, tiered by volume",
      "Attribution window from referral to sale",
      "Whether unlicensed sources are permitted and under which state rules",
      "Cap per referral and per period",
      "Whether reward accrual requires policy activation or just submission",
    ],
    acl: [
      "referral.manage for the sponsoring entity; payout approval is a separate permission",
      "Programs that would reward an unlicensed party for a licensed activity are blocked by a compliance guardrail with the rule shown",
      "Reward amounts are visible only to the sponsoring entity and the recipient",
    ],
    drawer: [
      "Context: program, reward model and sponsoring entity",
      "Summary: active referrals, accrued rewards, pending payouts",
      "Guidance: compliance boundary between a referral reward and a commission",
      "Help & FAQ: one-time vs recurring rewards",
      "Audit: program changes, accruals, approvals and payouts",
      "Next actions: approve payouts, adjust program, export audit",
    ],
    assistant: "Explains how a reward was calculated and which referral it traces to. It cannot approve payouts and must not give legal advice on state referral rules.",
    source: SRC,
    assumptions: [
      "ABox records and reports rewards; actual disbursement is outside Phase 1, consistent with the payment scope decision.",
    ],
    canvas: [
      { title: "Program", id: "REF-PROG", kind: "fields", items: ["Program name", "Sponsoring entity", "Eligible sources", "Reward type", "Amount / rate", "Attribution window", "Cap"], wide: true },
      { title: "Recurring model", id: "REF-RECUR", kind: "list", items: ["One-time on issue", "Recurring per active member month", "Recurring until termination or cap", "Tiered by volume"] },
      { title: "Compliance guardrail", id: "REF-GUARD", kind: "checks", items: ["Source licensing status recorded", "State referral rules attested", "Reward not contingent on plan selection", "Disclosure to the consumer where required"], wide: true },
      { title: "Accruals & payouts", id: "REF-ACCRUE", kind: "table", items: ["Referral", "Sale", "Accrued", "Period", "Status", "Approved by"], wide: true },
    ],
  },
]);
