import { SRC_BLUEPRINT, SRC_IA, SRC_RECON, screens } from "./types";

const WS = "WS_PLATFORM (authoring) — WS_AGENCY read-only for enabled products";
const MOD = "MOD_PRODUCTS_PLANS";
const SRC = `${SRC_BLUEPRINT} (product catalog, rate sources, ancillary extensibility, ICHRA quoting); ${SRC_IA} (SCR_PROD_*); ${SRC_RECON} — Module 1 consumes products, it does not manage them`;

export const PRODUCTS = screens([
  {
    id: "SCR_PROD_CATALOG",
    slug: "prod-catalog",
    name: "Product Catalog",
    group: "Products, plans & rates",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform product administrator; agency admin sees the enabled subset",
    purpose:
      "The authoritative list of everything ABox can quote or enroll, across on-exchange IFP, off-exchange IFP, ancillary lines and ICHRA quoting — the source every marketplace, quote and form resolution reads from.",
    actions: ["Search and filter the catalog", "Create a product", "Enable or disable a product for an agency", "Open a product", "View which marketplaces expose it", "Retire a product"],
    objects: ["Product", "Product line / category", "Carrier", "Availability rule set", "Rate source binding", "Agency enablement records"],
    config: [
      "Product line taxonomy (medical on-exchange, medical off-exchange, dental, vision, accident, critical illness, ICHRA)",
      "Which agencies may sell which products",
      "Display name and consumer-facing description per product",
      "Whether the product is quotable, enrollable, or quote-only",
    ],
    acl: [
      "product.manage is platform-level; product.view for agency admins is scoped to their enabled products",
      "Enabling a product for an agency requires a valid carrier appointment path — enablement without appointment is blocked",
      "Retiring a product never removes historical quotes or policies referencing it",
    ],
    drawer: [
      "Context: selected product, line and carrier",
      "Summary: quotable/enrollable state, agencies enabled, live plan count",
      "Guidance: quote-only vs enrollable and what each unlocks downstream",
      "Help & FAQ: why a product is not appearing in a marketplace",
      "Audit: enablement and retirement history",
      "Next actions: open plan list, edit availability, open product builder",
    ],
    assistant: "Explains why a product is or is not appearing for an agency by walking enablement, availability and appointment. It cannot change enablement.",
    source: SRC,
    assumptions: [
      "ICHRA is represented as a quote-only product family — Phase 1 supports ICHRA quoting with no ICHRA enrollment.",
    ],
    m1Seam: "Module 1 product selection (UX-002) and results (UX-009) read this catalog. Module 1 gains no management capability.",
    canvas: [
      { title: "Line filters", id: "CAT-LINES", kind: "tabs", items: ["Medical — on-exchange", "Medical — off-exchange", "Dental", "Vision", "Accident / CI", "ICHRA (quote only)"], wide: true },
      { title: "Catalog table", id: "CAT-TABLE", kind: "table", items: ["Product", "Line", "Carrier", "States", "Quotable", "Enrollable", "Agencies enabled", "Status"], wide: true },
      { title: "Enablement", id: "CAT-ENABLE", kind: "list", items: ["Agency row with enabled toggle", "Appointment prerequisite indicator", "Effective date of enablement"] },
      { title: "Quote-only marker", id: "CAT-QUOTEONLY", kind: "box", note: "ICHRA products carry an explicit quote-only marker. Any attempt to start an application against them is blocked at intake." },
    ],
  },
  {
    id: "SCR_PROD_PLANS",
    slug: "prod-plan-list",
    name: "Plan List",
    group: "Products, plans & rates",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform product administrator",
    purpose:
      "The plans under a product: identifiers, metal level or benefit tier, service area, plan documents and current rate version, with the data quality signals that decide whether a plan is safe to show a consumer.",
    actions: ["Filter plans", "Open a plan", "Attach plan documents", "Suppress a plan from display with reason", "Check data completeness", "Bulk import plans"],
    objects: ["Plan", "Plan identifiers (HIOS / carrier plan id)", "Service area", "Benefit summary attributes", "Plan documents (SBC, brochure)", "Rate version reference"],
    config: [
      "Which attributes are required before a plan may display",
      "Suppression rules and required reason codes",
      "Document types expected per line",
      "Import mapping for carrier plan files",
    ],
    acl: [
      "product.manage; suppression requires a reason and is reported because it directly changes what consumers can buy",
      "Agency users never suppress plans — suppression is platform or sellability-driven, not editorial",
    ],
    drawer: [
      "Context: product and selected plan",
      "Summary: completeness score, missing documents, rate coverage",
      "Guidance: what an incomplete plan does to results display",
      "Help & FAQ: HIOS id vs carrier plan id",
      "Audit: suppression and document changes",
      "Next actions: fix completeness, attach documents, open rates",
    ],
    assistant: "Lists exactly which attributes are missing on a plan. It cannot suppress or publish.",
    source: SRC,
    assumptions: ["Plan data arrives by carrier or exchange feed; ABox curates rather than authors benefit design."],
    canvas: [
      { title: "Plan table", id: "PLANS-TABLE", kind: "table", items: ["Plan name", "Carrier plan id", "Metal / tier", "Service area", "Rate version", "Documents", "Display state"], wide: true },
      { title: "Completeness", id: "PLANS-COMPLETE", kind: "checks", items: ["Premium rates loaded for the whole service area", "Deductible and MOOP present", "SBC attached", "Network reference present", "Formulary reference present"] },
      { title: "Suppression", id: "PLANS-SUPPRESS", kind: "actions", items: ["Suppress with reason", "Restore", "View suppression history"] },
      { title: "Import", id: "PLANS-IMPORT", kind: "box", note: "Bulk import with row-level validation. Failed rows do not partially create plans.", wide: true },
    ],
  },
  {
    id: "SCR_PROD_RATES",
    slug: "prod-rate-sources",
    name: "Rate Source Management",
    group: "Products, plans & rates",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform product administrator, platform operations",
    purpose:
      "Where premiums come from and whether they are trustworthy right now: source per product, refresh state, effective windows, and the rate version any quote was priced on.",
    actions: ["Add a rate source", "Trigger a refresh", "View load history", "Inspect a rate version", "Compare two rate versions", "Freeze a rate version"],
    objects: ["Rate source (feed, file or API)", "Rate version with effective window", "Load run and its row-level errors", "Rate lookup key definition", "Quote-to-rate-version links"],
    config: [
      "Source type and credentials reference per carrier",
      "Refresh schedule and stale threshold",
      "Rating dimensions (age, area, tobacco, family composition)",
      "Behaviour when rates are stale: warn, suppress, or block quoting",
    ],
    acl: [
      "rates.manage is platform-level and high sensitivity — a bad rate load misprices every quote",
      "Freezing a rate version requires a second approver",
      "Agency users see only the effective-date and staleness indicator, never the source configuration",
    ],
    drawer: [
      "Context: product, source and active rate version",
      "Summary: last successful load, staleness, error count",
      "Guidance: stale-rate policy and its consumer impact",
      "Help & FAQ: why a quote shows a different premium than a re-quote",
      "Audit: loads, freezes and version activations",
      "Next actions: refresh, inspect errors, freeze",
    ],
    assistant: "Explains a load failure and which plans it left unpriced.",
    source: SRC,
    assumptions: [
      "Quotes pin a rate version so a later rate load cannot silently change a quoted premium; re-quoting is explicit.",
    ],
    canvas: [
      { title: "Sources", id: "RATES-SOURCES", kind: "table", items: ["Carrier", "Product", "Source type", "Schedule", "Last load", "Status", "Staleness"], wide: true },
      { title: "Load run detail", id: "RATES-LOAD", kind: "list", items: ["Rows accepted", "Rows rejected with reason", "Plans left unpriced", "Reprocess control"] },
      { title: "Version compare", id: "RATES-COMPARE", kind: "table", items: ["Plan", "Version A premium", "Version B premium", "Delta", "Effective from"] },
      { title: "Stale policy", id: "RATES-STALE", kind: "box", note: "Beyond the configured stale threshold the product stops quoting rather than quoting a number nobody can stand behind.", wide: true },
    ],
  },
  {
    id: "SCR_PROD_BUILDER",
    slug: "prod-builder",
    name: "Product Builder & Ancillary Extensibility",
    group: "Products, plans & rates",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform product administrator",
    purpose:
      "Defines a new product without code: its line, rating inputs, benefit attributes, quoting behaviour and enrollment path. Dental is built here first as the minimum ancillary proof, and the same pattern must carry vision, accident and critical illness.",
    actions: ["Create product from a line template", "Define rating inputs", "Define displayed benefit attributes", "Bind a rate source", "Bind a form resolution rule", "Set cart and bundling behaviour", "Publish the product"],
    objects: ["Product definition", "Line template", "Rating input set", "Displayed attribute set", "Rate source binding", "Form binding", "Bundling rules"],
    config: [
      "Line templates and what each pre-fills",
      "Which attributes appear on a plan card vs plan detail for that line",
      "Whether the product can be added alongside a medical plan in one cart",
      "Quote-only vs enrollable",
    ],
    acl: [
      "product.manage plus publish permission; publishing a product with no rate source or no form binding is blocked",
      "Line templates are platform-owned — agencies cannot author product definitions",
    ],
    drawer: [
      "Context: product being built and its line template",
      "Summary: which bindings are complete",
      "Guidance: extend the dental pattern rather than special-casing a new line",
      "Help & FAQ: what makes a product enrollable",
      "Audit: definition changes and publishes",
      "Next actions: bind rates, bind form, preview in marketplace",
    ],
    assistant: "Points out missing bindings before publish. It cannot publish.",
    source: SRC,
    assumptions: [
      "Dental is the reference implementation for ancillary. The blueprint requires dental as a minimum; the builder must generalise rather than hardcode it.",
    ],
    m1Seam: "Module 1's 'More coverage' cards (UX-012) surface ancillary products defined here. UX-012 itself is unchanged.",
    canvas: [
      { title: "Definition", id: "BUILD-DEF", kind: "fields", items: ["Product name", "Consumer display name", "Line template", "Carrier", "States", "Quote-only / enrollable"], wide: true },
      { title: "Rating inputs", id: "BUILD-RATING", kind: "list", items: ["Age", "ZIP / rating area", "Tobacco", "Family composition", "Custom input"] },
      { title: "Displayed attributes", id: "BUILD-ATTRS", kind: "list", items: ["Card attributes (3-4 max)", "Detail attributes", "Document links"] },
      { title: "Bindings", id: "BUILD-BIND", kind: "checks", items: ["Rate source bound", "Form resolution rule bound (enrollable only)", "Availability rules set", "Commission schedule assignable"], wide: true },
      { title: "Bundling", id: "BUILD-BUNDLE", kind: "actions", items: ["Can be added with medical", "Standalone only", "Requires a medical plan in cart"] },
    ],
  },
  {
    id: "SCR_PROD_ICHRA",
    slug: "prod-ichra-setup",
    name: "ICHRA Quote Product Setup",
    group: "Products, plans & rates",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform product administrator, agency admin with ICHRA access",
    purpose:
      "Configures ICHRA as a quoting capability only: employer class definitions, allowance models and the affordability inputs the quote needs — with enrollment explicitly out of Phase 1 scope.",
    actions: ["Define employee classes", "Set allowance model per class", "Set benchmark plan basis", "Configure affordability inputs", "Enable ICHRA quoting for an agency", "Preview an ICHRA quote"],
    objects: ["ICHRA configuration", "Employee class", "Allowance schedule", "Benchmark plan reference", "Employer group record (quoting context)", "Quote output (no application)"],
    config: [
      "Class dimensions permitted (full-time, part-time, seasonal, geography, family status)",
      "Allowance model: flat, age-banded, family-tiered",
      "Benchmark plan selection rule per rating area",
      "Whether the employer-facing output is agency-branded",
    ],
    acl: [
      "ichra.quote permission, separate from IFP quoting, granted per agency",
      "No enrollment permission exists for ICHRA in Phase 1 — the enrollment path is absent, not disabled-looking",
      "Employer group data is scoped to the owning agency and its permitted upline",
    ],
    drawer: [
      "Context: employer group and ICHRA configuration",
      "Summary: classes defined, allowance model, benchmark basis",
      "Guidance: what the quote does and does not establish",
      "Help & FAQ: ICHRA affordability at a glance",
      "Audit: configuration changes and quote generations",
      "Next actions: preview quote, produce employer output, share",
    ],
    assistant: "Explains allowance and affordability mechanics generically. It must not give tax, ERISA or plan-design advice, and every ICHRA output carries the not-advice disclosure.",
    source: `${SRC}; ICHRA locked to quote-only during the sitemap audit`,
    assumptions: [
      "ICHRA quoting produces employer-facing illustrations only. No ICHRA enrollment, no employee election capture, no payroll integration in Phase 1.",
    ],
    canvas: [
      { title: "Employer group context", id: "ICHRA-GROUP", kind: "fields", items: ["Employer name", "Primary state", "Employee count", "Rating areas in scope"], wide: true },
      { title: "Employee classes", id: "ICHRA-CLASSES", kind: "table", items: ["Class", "Definition", "Employee count", "Allowance model", "Monthly allowance"] },
      { title: "Benchmark basis", id: "ICHRA-BENCH", kind: "list", items: ["Lowest-cost silver by rating area", "Selected reference plan", "Affordability inputs"] },
      { title: "Quote-only fence", id: "ICHRA-FENCE", kind: "box", note: "Phase 1 ICHRA is quoting only. There is no application, no election capture and no enrollment path — the enroll action does not exist on this product.", wide: true },
      { title: "Employer output", id: "ICHRA-OUTPUT", kind: "actions", items: ["Preview illustration", "Generate branded output", "Share with employer"] },
    ],
  },
  {
    id: "SCR_PROD_DOCS_AVAIL",
    slug: "prod-docs-availability",
    name: "Product Documentation, Availability Rules & Versioning",
    group: "Products, plans & rates",
    workspace: WS,
    module: MOD,
    packet: "M2-Cand",
    shell: "internal",
    user: "Platform product administrator, compliance reviewer",
    purpose:
      "Two things that decide whether a product may legally appear: the documents that must accompany it, and the availability rules that gate it by state, effective date, channel and entity — plus the version history that proves what was in force.",
    actions: ["Attach a product document", "Set document requirement by state", "Add an availability rule", "Test availability for a scenario", "Publish a product version", "View version history"],
    objects: ["Product document", "Document requirement rule", "Availability rule", "Product version", "Availability test result"],
    config: [
      "Document types and which are mandatory for display vs for enrollment",
      "Availability dimensions: state, county, effective date window, channel (D2C vs agent-assisted), entity, member segment",
      "Version approval requirement",
    ],
    acl: [
      "product.manage; availability changes are reported because they change what every marketplace shows",
      "Agencies may narrow availability within their own subtree but never widen beyond platform rules",
      "Missing a mandatory document makes the product non-displayable — this is enforced, not advisory",
    ],
    drawer: [
      "Context: product, document set and availability rules",
      "Summary: rules count, states covered, document gaps",
      "Guidance: narrowing vs widening availability and who may do which",
      "Help & FAQ: why a consumer in one county sees fewer products",
      "Audit: availability and document changes with actor and version",
      "Next actions: test availability, fix gaps, publish version",
    ],
    assistant: "Answers 'why can this consumer not see this product' by tracing availability, enablement and appointment. It cannot change rules.",
    source: SRC,
    assumptions: ["Availability is evaluated at quote time and at submission release; a cached availability answer is never authoritative."],
    canvas: [
      { title: "Documents", id: "PDOC-DOCS", kind: "table", items: ["Document", "Type", "States", "Required for display", "Required for enrollment", "Version"], wide: true },
      { title: "Availability rules", id: "PDOC-AVAIL", kind: "table", items: ["State / county", "Effective window", "Channel", "Entity scope", "Member segment", "Allowed"], wide: true },
      { title: "Availability test", id: "PDOC-TEST", kind: "fields", items: ["ZIP", "Effective date", "Channel", "Agency"], note: "Returns allowed/blocked and the exact rule that decided it." },
      { title: "Version history", id: "PDOC-VER", kind: "timeline", items: ["v1 published", "Availability narrowed", "Document added", "v2 published"] },
    ],
  },
]);
