/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LucieRouteImport } from './routes/lucie'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as ObjectRouteImport } from './routes/object'
import { Route as HfIndexRouteImport } from './routes/hf.index'
import { Route as HfScreenRouteImport } from './routes/hf.$screen'
import { Route as LucieIndexRouteImport } from './routes/lucie.index'
import { Route as LucieModule1RouteImport } from './routes/lucie.module1'
import { Route as LucieModulesRouteImport } from './routes/lucie.modules'
import { Route as LucieSlicesRouteImport } from './routes/lucie.slices'
import { Route as LucieStatesRouteImport } from './routes/lucie.states'
import { Route as LucieSurfacesRouteImport } from './routes/lucie.surfaces'
import { Route as LucieTraceRouteImport } from './routes/lucie.trace'
import { Route as LucieWorkstreamsRouteImport } from './routes/lucie.workstreams'
import { Route as M1IndexRouteImport } from './routes/m1.index'
import { Route as M1ScreenRouteImport } from './routes/m1.$screen'
import { Route as P1IndexRouteImport } from './routes/p1.index'
import { Route as P1ScreenRouteImport } from './routes/p1.$screen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LucieRoute = LucieRouteImport.update({
  id: '/lucie',
  path: '/lucie',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectRoute = ObjectRouteImport.update({
  id: '/object',
  path: '/object',
  getParentRoute: () => rootRouteImport,
} as any)
const HfIndexRoute = HfIndexRouteImport.update({
  id: '/hf/',
  path: '/hf/',
  getParentRoute: () => rootRouteImport,
} as any)
const HfScreenRoute = HfScreenRouteImport.update({
  id: '/hf/$screen',
  path: '/hf/$screen',
  getParentRoute: () => rootRouteImport,
} as any)
const LucieIndexRoute = LucieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LucieRoute,
} as any)
const LucieModule1Route = LucieModule1RouteImport.update({
  id: '/module1',
  path: '/module1',
  getParentRoute: () => LucieRoute,
} as any)
const LucieModulesRoute = LucieModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => LucieRoute,
} as any)
const LucieSlicesRoute = LucieSlicesRouteImport.update({
  id: '/slices',
  path: '/slices',
  getParentRoute: () => LucieRoute,
} as any)
const LucieStatesRoute = LucieStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => LucieRoute,
} as any)
const LucieSurfacesRoute = LucieSurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => LucieRoute,
} as any)
const LucieTraceRoute = LucieTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => LucieRoute,
} as any)
const LucieWorkstreamsRoute = LucieWorkstreamsRouteImport.update({
  id: '/workstreams',
  path: '/workstreams',
  getParentRoute: () => LucieRoute,
} as any)
const M1IndexRoute = M1IndexRouteImport.update({
  id: '/m1/',
  path: '/m1/',
  getParentRoute: () => rootRouteImport,
} as any)
const M1ScreenRoute = M1ScreenRouteImport.update({
  id: '/m1/$screen',
  path: '/m1/$screen',
  getParentRoute: () => rootRouteImport,
} as any)
const P1IndexRoute = P1IndexRouteImport.update({
  id: '/p1/',
  path: '/p1/',
  getParentRoute: () => rootRouteImport,
} as any)
const P1ScreenRoute = P1ScreenRouteImport.update({
  id: '/p1/$screen',
  path: '/p1/$screen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/lucie': typeof LucieRouteWithChildren
  '/my-work': typeof MyWorkRoute
  '/object': typeof ObjectRoute
  '/hf/$screen': typeof HfScreenRoute
  '/lucie/module1': typeof LucieModule1Route
  '/lucie/modules': typeof LucieModulesRoute
  '/lucie/slices': typeof LucieSlicesRoute
  '/lucie/states': typeof LucieStatesRoute
  '/lucie/surfaces': typeof LucieSurfacesRoute
  '/lucie/trace': typeof LucieTraceRoute
  '/lucie/workstreams': typeof LucieWorkstreamsRoute
  '/m1/$screen': typeof M1ScreenRoute
  '/p1/$screen': typeof P1ScreenRoute
  '/hf/': typeof HfIndexRoute
  '/lucie/': typeof LucieIndexRoute
  '/m1/': typeof M1IndexRoute
  '/p1/': typeof P1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-work': typeof MyWorkRoute
  '/object': typeof ObjectRoute
  '/hf/$screen': typeof HfScreenRoute
  '/lucie/module1': typeof LucieModule1Route
  '/lucie/modules': typeof LucieModulesRoute
  '/lucie/slices': typeof LucieSlicesRoute
  '/lucie/states': typeof LucieStatesRoute
  '/lucie/surfaces': typeof LucieSurfacesRoute
  '/lucie/trace': typeof LucieTraceRoute
  '/lucie/workstreams': typeof LucieWorkstreamsRoute
  '/m1/$screen': typeof M1ScreenRoute
  '/p1/$screen': typeof P1ScreenRoute
  '/hf': typeof HfIndexRoute
  '/lucie': typeof LucieIndexRoute
  '/m1': typeof M1IndexRoute
  '/p1': typeof P1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/lucie': typeof LucieRouteWithChildren
  '/my-work': typeof MyWorkRoute
  '/object': typeof ObjectRoute
  '/hf/$screen': typeof HfScreenRoute
  '/lucie/module1': typeof LucieModule1Route
  '/lucie/modules': typeof LucieModulesRoute
  '/lucie/slices': typeof LucieSlicesRoute
  '/lucie/states': typeof LucieStatesRoute
  '/lucie/surfaces': typeof LucieSurfacesRoute
  '/lucie/trace': typeof LucieTraceRoute
  '/lucie/workstreams': typeof LucieWorkstreamsRoute
  '/m1/$screen': typeof M1ScreenRoute
  '/p1/$screen': typeof P1ScreenRoute
  '/hf/': typeof HfIndexRoute
  '/lucie/': typeof LucieIndexRoute
  '/m1/': typeof M1IndexRoute
  '/p1/': typeof P1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/lucie'
    | '/my-work'
    | '/object'
    | '/hf/$screen'
    | '/lucie/module1'
    | '/lucie/modules'
    | '/lucie/slices'
    | '/lucie/states'
    | '/lucie/surfaces'
    | '/lucie/trace'
    | '/lucie/workstreams'
    | '/m1/$screen'
    | '/p1/$screen'
    | '/hf/'
    | '/lucie/'
    | '/m1/'
    | '/p1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-work'
    | '/object'
    | '/hf/$screen'
    | '/lucie/module1'
    | '/lucie/modules'
    | '/lucie/slices'
    | '/lucie/states'
    | '/lucie/surfaces'
    | '/lucie/trace'
    | '/lucie/workstreams'
    | '/m1/$screen'
    | '/p1/$screen'
    | '/hf'
    | '/lucie'
    | '/m1'
    | '/p1'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/lucie'
    | '/my-work'
    | '/object'
    | '/hf/$screen'
    | '/lucie/module1'
    | '/lucie/modules'
    | '/lucie/slices'
    | '/lucie/states'
    | '/lucie/surfaces'
    | '/lucie/trace'
    | '/lucie/workstreams'
    | '/m1/$screen'
    | '/p1/$screen'
    | '/hf/'
    | '/lucie/'
    | '/m1/'
    | '/p1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LucieRoute: typeof LucieRouteWithChildren
  MyWorkRoute: typeof MyWorkRoute
  ObjectRoute: typeof ObjectRoute
  HfScreenRoute: typeof HfScreenRoute
  M1ScreenRoute: typeof M1ScreenRoute
  P1ScreenRoute: typeof P1ScreenRoute
  HfIndexRoute: typeof HfIndexRoute
  M1IndexRoute: typeof M1IndexRoute
  P1IndexRoute: typeof P1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucie': {
      id: '/lucie'
      path: '/lucie'
      fullPath: '/lucie'
      preLoaderRoute: typeof LucieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object': {
      id: '/object'
      path: '/object'
      fullPath: '/object'
      preLoaderRoute: typeof ObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hf/': {
      id: '/hf/'
      path: '/hf'
      fullPath: '/hf/'
      preLoaderRoute: typeof HfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hf/$screen': {
      id: '/hf/$screen'
      path: '/hf/$screen'
      fullPath: '/hf/$screen'
      preLoaderRoute: typeof HfScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucie/': {
      id: '/lucie/'
      path: '/'
      fullPath: '/lucie/'
      preLoaderRoute: typeof LucieIndexRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/module1': {
      id: '/lucie/module1'
      path: '/module1'
      fullPath: '/lucie/module1'
      preLoaderRoute: typeof LucieModule1RouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/modules': {
      id: '/lucie/modules'
      path: '/modules'
      fullPath: '/lucie/modules'
      preLoaderRoute: typeof LucieModulesRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/slices': {
      id: '/lucie/slices'
      path: '/slices'
      fullPath: '/lucie/slices'
      preLoaderRoute: typeof LucieSlicesRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/states': {
      id: '/lucie/states'
      path: '/states'
      fullPath: '/lucie/states'
      preLoaderRoute: typeof LucieStatesRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/surfaces': {
      id: '/lucie/surfaces'
      path: '/surfaces'
      fullPath: '/lucie/surfaces'
      preLoaderRoute: typeof LucieSurfacesRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/trace': {
      id: '/lucie/trace'
      path: '/trace'
      fullPath: '/lucie/trace'
      preLoaderRoute: typeof LucieTraceRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/workstreams': {
      id: '/lucie/workstreams'
      path: '/workstreams'
      fullPath: '/lucie/workstreams'
      preLoaderRoute: typeof LucieWorkstreamsRouteImport
      parentRoute: typeof LucieRoute
    }
    '/m1/': {
      id: '/m1/'
      path: '/m1'
      fullPath: '/m1/'
      preLoaderRoute: typeof M1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m1/$screen': {
      id: '/m1/$screen'
      path: '/m1/$screen'
      fullPath: '/m1/$screen'
      preLoaderRoute: typeof M1ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p1/': {
      id: '/p1/'
      path: '/p1'
      fullPath: '/p1/'
      preLoaderRoute: typeof P1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p1/$screen': {
      id: '/p1/$screen'
      path: '/p1/$screen'
      fullPath: '/p1/$screen'
      preLoaderRoute: typeof P1ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LucieRouteChildren {
  LucieModule1Route: typeof LucieModule1Route
  LucieModulesRoute: typeof LucieModulesRoute
  LucieSlicesRoute: typeof LucieSlicesRoute
  LucieStatesRoute: typeof LucieStatesRoute
  LucieSurfacesRoute: typeof LucieSurfacesRoute
  LucieTraceRoute: typeof LucieTraceRoute
  LucieWorkstreamsRoute: typeof LucieWorkstreamsRoute
  LucieIndexRoute: typeof LucieIndexRoute
}

const LucieRouteChildren: LucieRouteChildren = {
  LucieModule1Route: LucieModule1Route,
  LucieModulesRoute: LucieModulesRoute,
  LucieSlicesRoute: LucieSlicesRoute,
  LucieStatesRoute: LucieStatesRoute,
  LucieSurfacesRoute: LucieSurfacesRoute,
  LucieTraceRoute: LucieTraceRoute,
  LucieWorkstreamsRoute: LucieWorkstreamsRoute,
  LucieIndexRoute: LucieIndexRoute,
}

const LucieRouteWithChildren = LucieRoute._addFileChildren(LucieRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LucieRoute: LucieRouteWithChildren,
  MyWorkRoute: MyWorkRoute,
  ObjectRoute: ObjectRoute,
  HfScreenRoute: HfScreenRoute,
  M1ScreenRoute: M1ScreenRoute,
  P1ScreenRoute: P1ScreenRoute,
  HfIndexRoute: HfIndexRoute,
  M1IndexRoute: M1IndexRoute,
  P1IndexRoute: P1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
