/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as ObjectRouteImport } from './routes/object'
import { Route as M1IndexRouteImport } from './routes/m1.index'
import { Route as M1ScreenRouteImport } from './routes/m1.$screen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectRoute = ObjectRouteImport.update({
  id: '/object',
  path: '/object',
  getParentRoute: () => rootRouteImport,
} as any)
const M1IndexRoute = M1IndexRouteImport.update({
  id: '/m1/',
  path: '/m1/',
  getParentRoute: () => rootRouteImport,
} as any)
const M1ScreenRoute = M1ScreenRouteImport.update({
  id: '/m1/$screen',
  path: '/m1/$screen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-work': typeof MyWorkRoute
  '/object': typeof ObjectRoute
  '/m1/$screen': typeof M1ScreenRoute
  '/m1/': typeof M1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-work': typeof MyWorkRoute
  '/object': typeof ObjectRoute
  '/m1/$screen': typeof M1ScreenRoute
  '/m1': typeof M1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-work': typeof MyWorkRoute
  '/object': typeof ObjectRoute
  '/m1/$screen': typeof M1ScreenRoute
  '/m1/': typeof M1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-work'
    | '/object'
    | '/m1/$screen'
    | '/m1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-work'
    | '/object'
    | '/m1/$screen'
    | '/m1'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-work'
    | '/object'
    | '/m1/$screen'
    | '/m1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  MyWorkRoute: typeof MyWorkRoute
  ObjectRoute: typeof ObjectRoute
  M1ScreenRoute: typeof M1ScreenRoute
  M1IndexRoute: typeof M1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object': {
      id: '/object'
      path: '/object'
      fullPath: '/object'
      preLoaderRoute: typeof ObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m1/': {
      id: '/m1/'
      path: '/m1'
      fullPath: '/m1/'
      preLoaderRoute: typeof M1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m1/$screen': {
      id: '/m1/$screen'
      path: '/m1/$screen'
      fullPath: '/m1/$screen'
      preLoaderRoute: typeof M1ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  MyWorkRoute: MyWorkRoute,
  ObjectRoute: ObjectRoute,
  M1ScreenRoute: M1ScreenRoute,
  M1IndexRoute: M1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
