/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as IchraRouteImport } from './routes/ichra'
import { Route as LucieRouteImport } from './routes/lucie'
import { Route as M00RouteImport } from './routes/m00'
import { Route as M06RouteImport } from './routes/m06'
import { Route as MemberRouteImport } from './routes/member'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as ObjectRouteImport } from './routes/object'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SelectRouteImport } from './routes/select'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppMyWorkRouteImport } from './routes/app.my-work'
import { Route as AppObjectRouteImport } from './routes/app.object'
import { Route as GovIndexRouteImport } from './routes/gov.index'
import { Route as GovModuleRouteImport } from './routes/gov.$module'
import { Route as HfIndexRouteImport } from './routes/hf.index'
import { Route as HfScreenRouteImport } from './routes/hf.$screen'
import { Route as LucieIndexRouteImport } from './routes/lucie.index'
import { Route as LucieGovernanceRouteImport } from './routes/lucie.governance'
import { Route as LucieModule1RouteImport } from './routes/lucie.module1'
import { Route as LucieModulesRouteImport } from './routes/lucie.modules'
import { Route as LucieReconciliationRouteImport } from './routes/lucie.reconciliation'
import { Route as LucieSlicesRouteImport } from './routes/lucie.slices'
import { Route as LucieStatesRouteImport } from './routes/lucie.states'
import { Route as LucieSurfacesRouteImport } from './routes/lucie.surfaces'
import { Route as LucieTraceRouteImport } from './routes/lucie.trace'
import { Route as LucieWorkstreamsRouteImport } from './routes/lucie.workstreams'
import { Route as M00IndexRouteImport } from './routes/m00.index'
import { Route as M00ApiRouteImport } from './routes/m00.api'
import { Route as M00ConsoleRouteImport } from './routes/m00.console'
import { Route as M00EventsRouteImport } from './routes/m00.events'
import { Route as M00TestsRouteImport } from './routes/m00.tests'
import { Route as M06IndexRouteImport } from './routes/m06.index'
import { Route as M06ConsoleRouteImport } from './routes/m06.console'
import { Route as M06RosterRouteImport } from './routes/m06.roster'
import { Route as M1IndexRouteImport } from './routes/m1.index'
import { Route as M1ScreenRouteImport } from './routes/m1.$screen'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as MemberMessagesRouteImport } from './routes/member.messages'
import { Route as MemberQuotesRouteImport } from './routes/member.quotes'
import { Route as MemberSettingsRouteImport } from './routes/member.settings'
import { Route as P1IndexRouteImport } from './routes/p1.index'
import { Route as P1ScreenRouteImport } from './routes/p1.$screen'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as GovModuleIndexRouteImport } from './routes/gov.$module.index'
import { Route as GovModuleDeltasRouteImport } from './routes/gov.$module.deltas'
import { Route as GovModuleFlowsRouteImport } from './routes/gov.$module.flows'
import { Route as GovModuleRegistersRouteImport } from './routes/gov.$module.registers'
import { Route as GovModuleScreensRouteImport } from './routes/gov.$module.screens'
import { Route as GovModuleTraceabilityRouteImport } from './routes/gov.$module.traceability'
import { Route as GovModuleFlowsFlowRouteImport } from './routes/gov.$module.flows.$flow'
import { Route as GovModuleScreensScreenRouteImport } from './routes/gov.$module.screens.$screen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const IchraRoute = IchraRouteImport.update({
  id: '/ichra',
  path: '/ichra',
  getParentRoute: () => rootRouteImport,
} as any)
const LucieRoute = LucieRouteImport.update({
  id: '/lucie',
  path: '/lucie',
  getParentRoute: () => rootRouteImport,
} as any)
const M00Route = M00RouteImport.update({
  id: '/m00',
  path: '/m00',
  getParentRoute: () => rootRouteImport,
} as any)
const M06Route = M06RouteImport.update({
  id: '/m06',
  path: '/m06',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectRoute = ObjectRouteImport.update({
  id: '/object',
  path: '/object',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMyWorkRoute = AppMyWorkRouteImport.update({
  id: '/app/my-work',
  path: '/app/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const AppObjectRoute = AppObjectRouteImport.update({
  id: '/app/object',
  path: '/app/object',
  getParentRoute: () => rootRouteImport,
} as any)
const GovIndexRoute = GovIndexRouteImport.update({
  id: '/gov/',
  path: '/gov/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovModuleRoute = GovModuleRouteImport.update({
  id: '/gov/$module',
  path: '/gov/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const HfIndexRoute = HfIndexRouteImport.update({
  id: '/hf/',
  path: '/hf/',
  getParentRoute: () => rootRouteImport,
} as any)
const HfScreenRoute = HfScreenRouteImport.update({
  id: '/hf/$screen',
  path: '/hf/$screen',
  getParentRoute: () => rootRouteImport,
} as any)
const LucieIndexRoute = LucieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LucieRoute,
} as any)
const LucieGovernanceRoute = LucieGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => LucieRoute,
} as any)
const LucieModule1Route = LucieModule1RouteImport.update({
  id: '/module1',
  path: '/module1',
  getParentRoute: () => LucieRoute,
} as any)
const LucieModulesRoute = LucieModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => LucieRoute,
} as any)
const LucieReconciliationRoute = LucieReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => LucieRoute,
} as any)
const LucieSlicesRoute = LucieSlicesRouteImport.update({
  id: '/slices',
  path: '/slices',
  getParentRoute: () => LucieRoute,
} as any)
const LucieStatesRoute = LucieStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => LucieRoute,
} as any)
const LucieSurfacesRoute = LucieSurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => LucieRoute,
} as any)
const LucieTraceRoute = LucieTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => LucieRoute,
} as any)
const LucieWorkstreamsRoute = LucieWorkstreamsRouteImport.update({
  id: '/workstreams',
  path: '/workstreams',
  getParentRoute: () => LucieRoute,
} as any)
const M00IndexRoute = M00IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => M00Route,
} as any)
const M00ApiRoute = M00ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => M00Route,
} as any)
const M00ConsoleRoute = M00ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => M00Route,
} as any)
const M00EventsRoute = M00EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => M00Route,
} as any)
const M00TestsRoute = M00TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => M00Route,
} as any)
const M06IndexRoute = M06IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => M06Route,
} as any)
const M06ConsoleRoute = M06ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => M06Route,
} as any)
const M06RosterRoute = M06RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => M06Route,
} as any)
const M1IndexRoute = M1IndexRouteImport.update({
  id: '/m1/',
  path: '/m1/',
  getParentRoute: () => rootRouteImport,
} as any)
const M1ScreenRoute = M1ScreenRouteImport.update({
  id: '/m1/$screen',
  path: '/m1/$screen',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberMessagesRoute = MemberMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MemberRoute,
} as any)
const MemberQuotesRoute = MemberQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsRoute = MemberSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MemberRoute,
} as any)
const P1IndexRoute = P1IndexRouteImport.update({
  id: '/p1/',
  path: '/p1/',
  getParentRoute: () => rootRouteImport,
} as any)
const P1ScreenRoute = P1ScreenRouteImport.update({
  id: '/p1/$screen',
  path: '/p1/$screen',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => PlansRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GovModuleIndexRoute = GovModuleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovModuleRoute,
} as any)
const GovModuleDeltasRoute = GovModuleDeltasRouteImport.update({
  id: '/deltas',
  path: '/deltas',
  getParentRoute: () => GovModuleRoute,
} as any)
const GovModuleFlowsRoute = GovModuleFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => GovModuleRoute,
} as any)
const GovModuleRegistersRoute = GovModuleRegistersRouteImport.update({
  id: '/registers',
  path: '/registers',
  getParentRoute: () => GovModuleRoute,
} as any)
const GovModuleScreensRoute = GovModuleScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => GovModuleRoute,
} as any)
const GovModuleTraceabilityRoute = GovModuleTraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => GovModuleRoute,
} as any)
const GovModuleFlowsFlowRoute = GovModuleFlowsFlowRouteImport.update({
  id: '/$flow',
  path: '/$flow',
  getParentRoute: () => GovModuleFlowsRoute,
} as any)
const GovModuleScreensScreenRoute = GovModuleScreensScreenRouteImport.update({
  id: '/$screen',
  path: '/$screen',
  getParentRoute: () => GovModuleScreensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/coverage': typeof CoverageRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/handoff': typeof HandoffRoute
  '/ichra': typeof IchraRoute
  '/lucie': typeof LucieRouteWithChildren
  '/m00': typeof M00RouteWithChildren
  '/m06': typeof M06RouteWithChildren
  '/member': typeof MemberRouteWithChildren
  '/my-work': typeof MyWorkRoute
  '/object': typeof ObjectRoute
  '/plans': typeof PlansRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/review': typeof ReviewRoute
  '/schedule': typeof ScheduleRoute
  '/select': typeof SelectRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/my-work': typeof AppMyWorkRoute
  '/app/object': typeof AppObjectRoute
  '/gov/$module': typeof GovModuleRouteWithChildren
  '/hf/$screen': typeof HfScreenRoute
  '/lucie/governance': typeof LucieGovernanceRoute
  '/lucie/module1': typeof LucieModule1Route
  '/lucie/modules': typeof LucieModulesRoute
  '/lucie/reconciliation': typeof LucieReconciliationRoute
  '/lucie/slices': typeof LucieSlicesRoute
  '/lucie/states': typeof LucieStatesRoute
  '/lucie/surfaces': typeof LucieSurfacesRoute
  '/lucie/trace': typeof LucieTraceRoute
  '/lucie/workstreams': typeof LucieWorkstreamsRoute
  '/m00/api': typeof M00ApiRoute
  '/m00/console': typeof M00ConsoleRoute
  '/m00/events': typeof M00EventsRoute
  '/m00/tests': typeof M00TestsRoute
  '/m06/console': typeof M06ConsoleRoute
  '/m06/roster': typeof M06RosterRoute
  '/m1/$screen': typeof M1ScreenRoute
  '/member/messages': typeof MemberMessagesRoute
  '/member/quotes': typeof MemberQuotesRoute
  '/member/settings': typeof MemberSettingsRoute
  '/p1/$screen': typeof P1ScreenRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/app/': typeof AppIndexRoute
  '/gov/': typeof GovIndexRoute
  '/hf/': typeof HfIndexRoute
  '/lucie/': typeof LucieIndexRoute
  '/m00/': typeof M00IndexRoute
  '/m06/': typeof M06IndexRoute
  '/m1/': typeof M1IndexRoute
  '/member/': typeof MemberIndexRoute
  '/p1/': typeof P1IndexRoute
  '/gov/$module/deltas': typeof GovModuleDeltasRoute
  '/gov/$module/flows': typeof GovModuleFlowsRouteWithChildren
  '/gov/$module/registers': typeof GovModuleRegistersRoute
  '/gov/$module/screens': typeof GovModuleScreensRouteWithChildren
  '/gov/$module/traceability': typeof GovModuleTraceabilityRoute
  '/gov/$module/': typeof GovModuleIndexRoute
  '/gov/$module/flows/$flow': typeof GovModuleFlowsFlowRoute
  '/gov/$module/screens/$screen': typeof GovModuleScreensScreenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/coverage': typeof CoverageRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/handoff': typeof HandoffRoute
  '/ichra': typeof IchraRoute
  '/my-work': typeof MyWorkRoute
  '/object': typeof ObjectRoute
  '/plans': typeof PlansRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/review': typeof ReviewRoute
  '/schedule': typeof ScheduleRoute
  '/select': typeof SelectRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/my-work': typeof AppMyWorkRoute
  '/app/object': typeof AppObjectRoute
  '/hf/$screen': typeof HfScreenRoute
  '/lucie/governance': typeof LucieGovernanceRoute
  '/lucie/module1': typeof LucieModule1Route
  '/lucie/modules': typeof LucieModulesRoute
  '/lucie/reconciliation': typeof LucieReconciliationRoute
  '/lucie/slices': typeof LucieSlicesRoute
  '/lucie/states': typeof LucieStatesRoute
  '/lucie/surfaces': typeof LucieSurfacesRoute
  '/lucie/trace': typeof LucieTraceRoute
  '/lucie/workstreams': typeof LucieWorkstreamsRoute
  '/m00/api': typeof M00ApiRoute
  '/m00/console': typeof M00ConsoleRoute
  '/m00/events': typeof M00EventsRoute
  '/m00/tests': typeof M00TestsRoute
  '/m06/console': typeof M06ConsoleRoute
  '/m06/roster': typeof M06RosterRoute
  '/m1/$screen': typeof M1ScreenRoute
  '/member/messages': typeof MemberMessagesRoute
  '/member/quotes': typeof MemberQuotesRoute
  '/member/settings': typeof MemberSettingsRoute
  '/p1/$screen': typeof P1ScreenRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/app': typeof AppIndexRoute
  '/gov': typeof GovIndexRoute
  '/hf': typeof HfIndexRoute
  '/lucie': typeof LucieIndexRoute
  '/m00': typeof M00IndexRoute
  '/m06': typeof M06IndexRoute
  '/m1': typeof M1IndexRoute
  '/member': typeof MemberIndexRoute
  '/p1': typeof P1IndexRoute
  '/gov/$module/deltas': typeof GovModuleDeltasRoute
  '/gov/$module/flows': typeof GovModuleFlowsRouteWithChildren
  '/gov/$module/registers': typeof GovModuleRegistersRoute
  '/gov/$module/screens': typeof GovModuleScreensRouteWithChildren
  '/gov/$module/traceability': typeof GovModuleTraceabilityRoute
  '/gov/$module': typeof GovModuleIndexRoute
  '/gov/$module/flows/$flow': typeof GovModuleFlowsFlowRoute
  '/gov/$module/screens/$screen': typeof GovModuleScreensScreenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/coverage': typeof CoverageRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/handoff': typeof HandoffRoute
  '/ichra': typeof IchraRoute
  '/lucie': typeof LucieRouteWithChildren
  '/m00': typeof M00RouteWithChildren
  '/m06': typeof M06RouteWithChildren
  '/member': typeof MemberRouteWithChildren
  '/my-work': typeof MyWorkRoute
  '/object': typeof ObjectRoute
  '/plans': typeof PlansRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/review': typeof ReviewRoute
  '/schedule': typeof ScheduleRoute
  '/select': typeof SelectRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/my-work': typeof AppMyWorkRoute
  '/app/object': typeof AppObjectRoute
  '/gov/$module': typeof GovModuleRouteWithChildren
  '/hf/$screen': typeof HfScreenRoute
  '/lucie/governance': typeof LucieGovernanceRoute
  '/lucie/module1': typeof LucieModule1Route
  '/lucie/modules': typeof LucieModulesRoute
  '/lucie/reconciliation': typeof LucieReconciliationRoute
  '/lucie/slices': typeof LucieSlicesRoute
  '/lucie/states': typeof LucieStatesRoute
  '/lucie/surfaces': typeof LucieSurfacesRoute
  '/lucie/trace': typeof LucieTraceRoute
  '/lucie/workstreams': typeof LucieWorkstreamsRoute
  '/m00/api': typeof M00ApiRoute
  '/m00/console': typeof M00ConsoleRoute
  '/m00/events': typeof M00EventsRoute
  '/m00/tests': typeof M00TestsRoute
  '/m06/console': typeof M06ConsoleRoute
  '/m06/roster': typeof M06RosterRoute
  '/m1/$screen': typeof M1ScreenRoute
  '/member/messages': typeof MemberMessagesRoute
  '/member/quotes': typeof MemberQuotesRoute
  '/member/settings': typeof MemberSettingsRoute
  '/p1/$screen': typeof P1ScreenRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/app/': typeof AppIndexRoute
  '/gov/': typeof GovIndexRoute
  '/hf/': typeof HfIndexRoute
  '/lucie/': typeof LucieIndexRoute
  '/m00/': typeof M00IndexRoute
  '/m06/': typeof M06IndexRoute
  '/m1/': typeof M1IndexRoute
  '/member/': typeof MemberIndexRoute
  '/p1/': typeof P1IndexRoute
  '/gov/$module/deltas': typeof GovModuleDeltasRoute
  '/gov/$module/flows': typeof GovModuleFlowsRouteWithChildren
  '/gov/$module/registers': typeof GovModuleRegistersRoute
  '/gov/$module/screens': typeof GovModuleScreensRouteWithChildren
  '/gov/$module/traceability': typeof GovModuleTraceabilityRoute
  '/gov/$module/': typeof GovModuleIndexRoute
  '/gov/$module/flows/$flow': typeof GovModuleFlowsFlowRoute
  '/gov/$module/screens/$screen': typeof GovModuleScreensScreenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/compare'
    | '/compliance'
    | '/coverage'
    | '/dashboard'
    | '/faq'
    | '/handoff'
    | '/ichra'
    | '/lucie'
    | '/m00'
    | '/m06'
    | '/member'
    | '/my-work'
    | '/object'
    | '/plans'
    | '/privacy'
    | '/quote'
    | '/review'
    | '/schedule'
    | '/select'
    | '/terms'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/my-work'
    | '/app/object'
    | '/gov/$module'
    | '/hf/$screen'
    | '/lucie/governance'
    | '/lucie/module1'
    | '/lucie/modules'
    | '/lucie/reconciliation'
    | '/lucie/slices'
    | '/lucie/states'
    | '/lucie/surfaces'
    | '/lucie/trace'
    | '/lucie/workstreams'
    | '/m00/api'
    | '/m00/console'
    | '/m00/events'
    | '/m00/tests'
    | '/m06/console'
    | '/m06/roster'
    | '/m1/$screen'
    | '/member/messages'
    | '/member/quotes'
    | '/member/settings'
    | '/p1/$screen'
    | '/plans/$planId'
    | '/shared/$token'
    | '/app/'
    | '/gov/'
    | '/hf/'
    | '/lucie/'
    | '/m00/'
    | '/m06/'
    | '/m1/'
    | '/member/'
    | '/p1/'
    | '/gov/$module/deltas'
    | '/gov/$module/flows'
    | '/gov/$module/registers'
    | '/gov/$module/screens'
    | '/gov/$module/traceability'
    | '/gov/$module/'
    | '/gov/$module/flows/$flow'
    | '/gov/$module/screens/$screen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/compare'
    | '/compliance'
    | '/coverage'
    | '/dashboard'
    | '/faq'
    | '/handoff'
    | '/ichra'
    | '/my-work'
    | '/object'
    | '/plans'
    | '/privacy'
    | '/quote'
    | '/review'
    | '/schedule'
    | '/select'
    | '/terms'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/my-work'
    | '/app/object'
    | '/hf/$screen'
    | '/lucie/governance'
    | '/lucie/module1'
    | '/lucie/modules'
    | '/lucie/reconciliation'
    | '/lucie/slices'
    | '/lucie/states'
    | '/lucie/surfaces'
    | '/lucie/trace'
    | '/lucie/workstreams'
    | '/m00/api'
    | '/m00/console'
    | '/m00/events'
    | '/m00/tests'
    | '/m06/console'
    | '/m06/roster'
    | '/m1/$screen'
    | '/member/messages'
    | '/member/quotes'
    | '/member/settings'
    | '/p1/$screen'
    | '/plans/$planId'
    | '/shared/$token'
    | '/app'
    | '/gov'
    | '/hf'
    | '/lucie'
    | '/m00'
    | '/m06'
    | '/m1'
    | '/member'
    | '/p1'
    | '/gov/$module/deltas'
    | '/gov/$module/flows'
    | '/gov/$module/registers'
    | '/gov/$module/screens'
    | '/gov/$module/traceability'
    | '/gov/$module'
    | '/gov/$module/flows/$flow'
    | '/gov/$module/screens/$screen'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/compare'
    | '/compliance'
    | '/coverage'
    | '/dashboard'
    | '/faq'
    | '/handoff'
    | '/ichra'
    | '/lucie'
    | '/m00'
    | '/m06'
    | '/member'
    | '/my-work'
    | '/object'
    | '/plans'
    | '/privacy'
    | '/quote'
    | '/review'
    | '/schedule'
    | '/select'
    | '/terms'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/my-work'
    | '/app/object'
    | '/gov/$module'
    | '/hf/$screen'
    | '/lucie/governance'
    | '/lucie/module1'
    | '/lucie/modules'
    | '/lucie/reconciliation'
    | '/lucie/slices'
    | '/lucie/states'
    | '/lucie/surfaces'
    | '/lucie/trace'
    | '/lucie/workstreams'
    | '/m00/api'
    | '/m00/console'
    | '/m00/events'
    | '/m00/tests'
    | '/m06/console'
    | '/m06/roster'
    | '/m1/$screen'
    | '/member/messages'
    | '/member/quotes'
    | '/member/settings'
    | '/p1/$screen'
    | '/plans/$planId'
    | '/shared/$token'
    | '/app/'
    | '/gov/'
    | '/hf/'
    | '/lucie/'
    | '/m00/'
    | '/m06/'
    | '/m1/'
    | '/member/'
    | '/p1/'
    | '/gov/$module/deltas'
    | '/gov/$module/flows'
    | '/gov/$module/registers'
    | '/gov/$module/screens'
    | '/gov/$module/traceability'
    | '/gov/$module/'
    | '/gov/$module/flows/$flow'
    | '/gov/$module/screens/$screen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CompareRoute: typeof CompareRoute
  ComplianceRoute: typeof ComplianceRoute
  CoverageRoute: typeof CoverageRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  HandoffRoute: typeof HandoffRoute
  IchraRoute: typeof IchraRoute
  LucieRoute: typeof LucieRouteWithChildren
  M00Route: typeof M00RouteWithChildren
  M06Route: typeof M06RouteWithChildren
  MemberRoute: typeof MemberRouteWithChildren
  MyWorkRoute: typeof MyWorkRoute
  ObjectRoute: typeof ObjectRoute
  PlansRoute: typeof PlansRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ReviewRoute: typeof ReviewRoute
  ScheduleRoute: typeof ScheduleRoute
  SelectRoute: typeof SelectRoute
  TermsRoute: typeof TermsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMyWorkRoute: typeof AppMyWorkRoute
  AppObjectRoute: typeof AppObjectRoute
  GovModuleRoute: typeof GovModuleRouteWithChildren
  HfScreenRoute: typeof HfScreenRoute
  M1ScreenRoute: typeof M1ScreenRoute
  P1ScreenRoute: typeof P1ScreenRoute
  SharedTokenRoute: typeof SharedTokenRoute
  AppIndexRoute: typeof AppIndexRoute
  GovIndexRoute: typeof GovIndexRoute
  HfIndexRoute: typeof HfIndexRoute
  M1IndexRoute: typeof M1IndexRoute
  P1IndexRoute: typeof P1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ichra': {
      id: '/ichra'
      path: '/ichra'
      fullPath: '/ichra'
      preLoaderRoute: typeof IchraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucie': {
      id: '/lucie'
      path: '/lucie'
      fullPath: '/lucie'
      preLoaderRoute: typeof LucieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m00': {
      id: '/m00'
      path: '/m00'
      fullPath: '/m00'
      preLoaderRoute: typeof M00RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m06': {
      id: '/m06'
      path: '/m06'
      fullPath: '/m06'
      preLoaderRoute: typeof M06RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object': {
      id: '/object'
      path: '/object'
      fullPath: '/object'
      preLoaderRoute: typeof ObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/my-work': {
      id: '/app/my-work'
      path: '/app/my-work'
      fullPath: '/app/my-work'
      preLoaderRoute: typeof AppMyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/object': {
      id: '/app/object'
      path: '/app/object'
      fullPath: '/app/object'
      preLoaderRoute: typeof AppObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/': {
      id: '/gov/'
      path: '/gov'
      fullPath: '/gov/'
      preLoaderRoute: typeof GovIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/$module': {
      id: '/gov/$module'
      path: '/gov/$module'
      fullPath: '/gov/$module'
      preLoaderRoute: typeof GovModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hf/': {
      id: '/hf/'
      path: '/hf'
      fullPath: '/hf/'
      preLoaderRoute: typeof HfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hf/$screen': {
      id: '/hf/$screen'
      path: '/hf/$screen'
      fullPath: '/hf/$screen'
      preLoaderRoute: typeof HfScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucie/': {
      id: '/lucie/'
      path: '/'
      fullPath: '/lucie/'
      preLoaderRoute: typeof LucieIndexRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/governance': {
      id: '/lucie/governance'
      path: '/governance'
      fullPath: '/lucie/governance'
      preLoaderRoute: typeof LucieGovernanceRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/module1': {
      id: '/lucie/module1'
      path: '/module1'
      fullPath: '/lucie/module1'
      preLoaderRoute: typeof LucieModule1RouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/modules': {
      id: '/lucie/modules'
      path: '/modules'
      fullPath: '/lucie/modules'
      preLoaderRoute: typeof LucieModulesRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/reconciliation': {
      id: '/lucie/reconciliation'
      path: '/reconciliation'
      fullPath: '/lucie/reconciliation'
      preLoaderRoute: typeof LucieReconciliationRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/slices': {
      id: '/lucie/slices'
      path: '/slices'
      fullPath: '/lucie/slices'
      preLoaderRoute: typeof LucieSlicesRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/states': {
      id: '/lucie/states'
      path: '/states'
      fullPath: '/lucie/states'
      preLoaderRoute: typeof LucieStatesRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/surfaces': {
      id: '/lucie/surfaces'
      path: '/surfaces'
      fullPath: '/lucie/surfaces'
      preLoaderRoute: typeof LucieSurfacesRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/trace': {
      id: '/lucie/trace'
      path: '/trace'
      fullPath: '/lucie/trace'
      preLoaderRoute: typeof LucieTraceRouteImport
      parentRoute: typeof LucieRoute
    }
    '/lucie/workstreams': {
      id: '/lucie/workstreams'
      path: '/workstreams'
      fullPath: '/lucie/workstreams'
      preLoaderRoute: typeof LucieWorkstreamsRouteImport
      parentRoute: typeof LucieRoute
    }
    '/m00/': {
      id: '/m00/'
      path: '/'
      fullPath: '/m00/'
      preLoaderRoute: typeof M00IndexRouteImport
      parentRoute: typeof M00Route
    }
    '/m00/api': {
      id: '/m00/api'
      path: '/api'
      fullPath: '/m00/api'
      preLoaderRoute: typeof M00ApiRouteImport
      parentRoute: typeof M00Route
    }
    '/m00/console': {
      id: '/m00/console'
      path: '/console'
      fullPath: '/m00/console'
      preLoaderRoute: typeof M00ConsoleRouteImport
      parentRoute: typeof M00Route
    }
    '/m00/events': {
      id: '/m00/events'
      path: '/events'
      fullPath: '/m00/events'
      preLoaderRoute: typeof M00EventsRouteImport
      parentRoute: typeof M00Route
    }
    '/m00/tests': {
      id: '/m00/tests'
      path: '/tests'
      fullPath: '/m00/tests'
      preLoaderRoute: typeof M00TestsRouteImport
      parentRoute: typeof M00Route
    }
    '/m06/': {
      id: '/m06/'
      path: '/'
      fullPath: '/m06/'
      preLoaderRoute: typeof M06IndexRouteImport
      parentRoute: typeof M06Route
    }
    '/m06/console': {
      id: '/m06/console'
      path: '/console'
      fullPath: '/m06/console'
      preLoaderRoute: typeof M06ConsoleRouteImport
      parentRoute: typeof M06Route
    }
    '/m06/roster': {
      id: '/m06/roster'
      path: '/roster'
      fullPath: '/m06/roster'
      preLoaderRoute: typeof M06RosterRouteImport
      parentRoute: typeof M06Route
    }
    '/m1/': {
      id: '/m1/'
      path: '/m1'
      fullPath: '/m1/'
      preLoaderRoute: typeof M1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m1/$screen': {
      id: '/m1/$screen'
      path: '/m1/$screen'
      fullPath: '/m1/$screen'
      preLoaderRoute: typeof M1ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/messages': {
      id: '/member/messages'
      path: '/messages'
      fullPath: '/member/messages'
      preLoaderRoute: typeof MemberMessagesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/quotes': {
      id: '/member/quotes'
      path: '/quotes'
      fullPath: '/member/quotes'
      preLoaderRoute: typeof MemberQuotesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/settings': {
      id: '/member/settings'
      path: '/settings'
      fullPath: '/member/settings'
      preLoaderRoute: typeof MemberSettingsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/p1/': {
      id: '/p1/'
      path: '/p1'
      fullPath: '/p1/'
      preLoaderRoute: typeof P1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p1/$screen': {
      id: '/p1/$screen'
      path: '/p1/$screen'
      fullPath: '/p1/$screen'
      preLoaderRoute: typeof P1ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof PlansRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/$module/': {
      id: '/gov/$module/'
      path: '/'
      fullPath: '/gov/$module/'
      preLoaderRoute: typeof GovModuleIndexRouteImport
      parentRoute: typeof GovModuleRoute
    }
    '/gov/$module/deltas': {
      id: '/gov/$module/deltas'
      path: '/deltas'
      fullPath: '/gov/$module/deltas'
      preLoaderRoute: typeof GovModuleDeltasRouteImport
      parentRoute: typeof GovModuleRoute
    }
    '/gov/$module/flows': {
      id: '/gov/$module/flows'
      path: '/flows'
      fullPath: '/gov/$module/flows'
      preLoaderRoute: typeof GovModuleFlowsRouteImport
      parentRoute: typeof GovModuleRoute
    }
    '/gov/$module/registers': {
      id: '/gov/$module/registers'
      path: '/registers'
      fullPath: '/gov/$module/registers'
      preLoaderRoute: typeof GovModuleRegistersRouteImport
      parentRoute: typeof GovModuleRoute
    }
    '/gov/$module/screens': {
      id: '/gov/$module/screens'
      path: '/screens'
      fullPath: '/gov/$module/screens'
      preLoaderRoute: typeof GovModuleScreensRouteImport
      parentRoute: typeof GovModuleRoute
    }
    '/gov/$module/traceability': {
      id: '/gov/$module/traceability'
      path: '/traceability'
      fullPath: '/gov/$module/traceability'
      preLoaderRoute: typeof GovModuleTraceabilityRouteImport
      parentRoute: typeof GovModuleRoute
    }
    '/gov/$module/flows/$flow': {
      id: '/gov/$module/flows/$flow'
      path: '/$flow'
      fullPath: '/gov/$module/flows/$flow'
      preLoaderRoute: typeof GovModuleFlowsFlowRouteImport
      parentRoute: typeof GovModuleFlowsRoute
    }
    '/gov/$module/screens/$screen': {
      id: '/gov/$module/screens/$screen'
      path: '/$screen'
      fullPath: '/gov/$module/screens/$screen'
      preLoaderRoute: typeof GovModuleScreensScreenRouteImport
      parentRoute: typeof GovModuleScreensRoute
    }
  }
}

interface LucieRouteChildren {
  LucieGovernanceRoute: typeof LucieGovernanceRoute
  LucieModule1Route: typeof LucieModule1Route
  LucieModulesRoute: typeof LucieModulesRoute
  LucieReconciliationRoute: typeof LucieReconciliationRoute
  LucieSlicesRoute: typeof LucieSlicesRoute
  LucieStatesRoute: typeof LucieStatesRoute
  LucieSurfacesRoute: typeof LucieSurfacesRoute
  LucieTraceRoute: typeof LucieTraceRoute
  LucieWorkstreamsRoute: typeof LucieWorkstreamsRoute
  LucieIndexRoute: typeof LucieIndexRoute
}

const LucieRouteChildren: LucieRouteChildren = {
  LucieGovernanceRoute: LucieGovernanceRoute,
  LucieModule1Route: LucieModule1Route,
  LucieModulesRoute: LucieModulesRoute,
  LucieReconciliationRoute: LucieReconciliationRoute,
  LucieSlicesRoute: LucieSlicesRoute,
  LucieStatesRoute: LucieStatesRoute,
  LucieSurfacesRoute: LucieSurfacesRoute,
  LucieTraceRoute: LucieTraceRoute,
  LucieWorkstreamsRoute: LucieWorkstreamsRoute,
  LucieIndexRoute: LucieIndexRoute,
}

const LucieRouteWithChildren = LucieRoute._addFileChildren(LucieRouteChildren)

interface M00RouteChildren {
  M00ApiRoute: typeof M00ApiRoute
  M00ConsoleRoute: typeof M00ConsoleRoute
  M00EventsRoute: typeof M00EventsRoute
  M00TestsRoute: typeof M00TestsRoute
  M00IndexRoute: typeof M00IndexRoute
}

const M00RouteChildren: M00RouteChildren = {
  M00ApiRoute: M00ApiRoute,
  M00ConsoleRoute: M00ConsoleRoute,
  M00EventsRoute: M00EventsRoute,
  M00TestsRoute: M00TestsRoute,
  M00IndexRoute: M00IndexRoute,
}

const M00RouteWithChildren = M00Route._addFileChildren(M00RouteChildren)

interface M06RouteChildren {
  M06ConsoleRoute: typeof M06ConsoleRoute
  M06RosterRoute: typeof M06RosterRoute
  M06IndexRoute: typeof M06IndexRoute
}

const M06RouteChildren: M06RouteChildren = {
  M06ConsoleRoute: M06ConsoleRoute,
  M06RosterRoute: M06RosterRoute,
  M06IndexRoute: M06IndexRoute,
}

const M06RouteWithChildren = M06Route._addFileChildren(M06RouteChildren)

interface MemberRouteChildren {
  MemberMessagesRoute: typeof MemberMessagesRoute
  MemberQuotesRoute: typeof MemberQuotesRoute
  MemberSettingsRoute: typeof MemberSettingsRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberMessagesRoute: MemberMessagesRoute,
  MemberQuotesRoute: MemberQuotesRoute,
  MemberSettingsRoute: MemberSettingsRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface PlansRouteChildren {
  PlansPlanIdRoute: typeof PlansPlanIdRoute
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansPlanIdRoute: PlansPlanIdRoute,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

interface GovModuleFlowsRouteChildren {
  GovModuleFlowsFlowRoute: typeof GovModuleFlowsFlowRoute
}

const GovModuleFlowsRouteChildren: GovModuleFlowsRouteChildren = {
  GovModuleFlowsFlowRoute: GovModuleFlowsFlowRoute,
}

const GovModuleFlowsRouteWithChildren = GovModuleFlowsRoute._addFileChildren(
  GovModuleFlowsRouteChildren,
)

interface GovModuleScreensRouteChildren {
  GovModuleScreensScreenRoute: typeof GovModuleScreensScreenRoute
}

const GovModuleScreensRouteChildren: GovModuleScreensRouteChildren = {
  GovModuleScreensScreenRoute: GovModuleScreensScreenRoute,
}

const GovModuleScreensRouteWithChildren =
  GovModuleScreensRoute._addFileChildren(GovModuleScreensRouteChildren)

interface GovModuleRouteChildren {
  GovModuleDeltasRoute: typeof GovModuleDeltasRoute
  GovModuleFlowsRoute: typeof GovModuleFlowsRouteWithChildren
  GovModuleRegistersRoute: typeof GovModuleRegistersRoute
  GovModuleScreensRoute: typeof GovModuleScreensRouteWithChildren
  GovModuleTraceabilityRoute: typeof GovModuleTraceabilityRoute
  GovModuleIndexRoute: typeof GovModuleIndexRoute
}

const GovModuleRouteChildren: GovModuleRouteChildren = {
  GovModuleDeltasRoute: GovModuleDeltasRoute,
  GovModuleFlowsRoute: GovModuleFlowsRouteWithChildren,
  GovModuleRegistersRoute: GovModuleRegistersRoute,
  GovModuleScreensRoute: GovModuleScreensRouteWithChildren,
  GovModuleTraceabilityRoute: GovModuleTraceabilityRoute,
  GovModuleIndexRoute: GovModuleIndexRoute,
}

const GovModuleRouteWithChildren = GovModuleRoute._addFileChildren(
  GovModuleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CompareRoute: CompareRoute,
  ComplianceRoute: ComplianceRoute,
  CoverageRoute: CoverageRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  HandoffRoute: HandoffRoute,
  IchraRoute: IchraRoute,
  LucieRoute: LucieRouteWithChildren,
  M00Route: M00RouteWithChildren,
  M06Route: M06RouteWithChildren,
  MemberRoute: MemberRouteWithChildren,
  MyWorkRoute: MyWorkRoute,
  ObjectRoute: ObjectRoute,
  PlansRoute: PlansRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ReviewRoute: ReviewRoute,
  ScheduleRoute: ScheduleRoute,
  SelectRoute: SelectRoute,
  TermsRoute: TermsRoute,
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMyWorkRoute: AppMyWorkRoute,
  AppObjectRoute: AppObjectRoute,
  GovModuleRoute: GovModuleRouteWithChildren,
  HfScreenRoute: HfScreenRoute,
  M1ScreenRoute: M1ScreenRoute,
  P1ScreenRoute: P1ScreenRoute,
  SharedTokenRoute: SharedTokenRoute,
  AppIndexRoute: AppIndexRoute,
  GovIndexRoute: GovIndexRoute,
  HfIndexRoute: HfIndexRoute,
  M1IndexRoute: M1IndexRoute,
  P1IndexRoute: P1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
