-- ABox Lucie M00 Platform Foundation - PostgreSQL migration V004 v1.1
-- Forced row-level security. The application transaction must set app.user_id, app.tenant_id and app.is_platform_admin after authentication.

ALTER TABLE m00."user_identity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."user_identity" FORCE ROW LEVEL SECURITY;
CREATE POLICY "user_identity_scope" ON m00."user_identity" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id()));
ALTER TABLE m00."actor_profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."actor_profile" FORCE ROW LEVEL SECURITY;
CREATE POLICY "actor_profile_scope" ON m00."actor_profile" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id()));
ALTER TABLE m00."contact_method" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."contact_method" FORCE ROW LEVEL SECURITY;
CREATE POLICY "contact_method_scope" ON m00."contact_method" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id()));
ALTER TABLE m00."identity_verification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."identity_verification" FORCE ROW LEVEL SECURITY;
CREATE POLICY "identity_verification_scope" ON m00."identity_verification" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id()));
ALTER TABLE m00."invitation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."invitation" FORCE ROW LEVEL SECURITY;
CREATE POLICY "invitation_scope" ON m00."invitation" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."session" FORCE ROW LEVEL SECURITY;
CREATE POLICY "session_scope" ON m00."session" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id()));
ALTER TABLE m00."mfa_enrollment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."mfa_enrollment" FORCE ROW LEVEL SECURITY;
CREATE POLICY "mfa_enrollment_scope" ON m00."mfa_enrollment" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id()));
ALTER TABLE m00."tenant_membership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."tenant_membership" FORCE ROW LEVEL SECURITY;
CREATE POLICY "tenant_membership_scope" ON m00."tenant_membership" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."role_template" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."role_template" FORCE ROW LEVEL SECURITY;
CREATE POLICY "role_template_read" ON m00."role_template" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "role_template_write" ON m00."role_template" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."permission_definition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."permission_definition" FORCE ROW LEVEL SECURITY;
CREATE POLICY "permission_definition_read" ON m00."permission_definition" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "permission_definition_write" ON m00."permission_definition" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."role_assignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."role_assignment" FORCE ROW LEVEL SECURITY;
CREATE POLICY "role_assignment_scope" ON m00."role_assignment" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."access_decision" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."access_decision" FORCE ROW LEVEL SECURITY;
CREATE POLICY "access_decision_scope" ON m00."access_decision" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id()));
ALTER TABLE m00."privileged_access_grant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."privileged_access_grant" FORCE ROW LEVEL SECURITY;
CREATE POLICY "privileged_access_grant_scope" ON m00."privileged_access_grant" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "target_tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "target_tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."workload_identity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."workload_identity" FORCE ROW LEVEL SECURITY;
CREATE POLICY "workload_identity_read" ON m00."workload_identity" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "workload_identity_write" ON m00."workload_identity" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."commercial_activation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."commercial_activation" FORCE ROW LEVEL SECURITY;
CREATE POLICY "commercial_activation_scope" ON m00."commercial_activation" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."entitlement_grant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."entitlement_grant" FORCE ROW LEVEL SECURITY;
CREATE POLICY "entitlement_grant_scope" ON m00."entitlement_grant" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."seat_allocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."seat_allocation" FORCE ROW LEVEL SECURITY;
CREATE POLICY "seat_allocation_scope" ON m00."seat_allocation" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."feature_control" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."feature_control" FORCE ROW LEVEL SECURITY;
CREATE POLICY "feature_control_read" ON m00."feature_control" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "feature_control_write" ON m00."feature_control" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."emergency_disable" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."emergency_disable" FORCE ROW LEVEL SECURITY;
CREATE POLICY "emergency_disable_read" ON m00."emergency_disable" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "emergency_disable_write" ON m00."emergency_disable" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."platform_configuration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."platform_configuration" FORCE ROW LEVEL SECURITY;
CREATE POLICY "platform_configuration_read" ON m00."platform_configuration" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "platform_configuration_write" ON m00."platform_configuration" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."workspace_preference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."workspace_preference" FORCE ROW LEVEL SECURITY;
CREATE POLICY "workspace_preference_scope" ON m00."workspace_preference" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id()));
ALTER TABLE m00."reference_geography" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."reference_geography" FORCE ROW LEVEL SECURITY;
CREATE POLICY "reference_geography_read" ON m00."reference_geography" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "reference_geography_write" ON m00."reference_geography" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."consent_definition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."consent_definition" FORCE ROW LEVEL SECURITY;
CREATE POLICY "consent_definition_read" ON m00."consent_definition" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "consent_definition_write" ON m00."consent_definition" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."consent_evidence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."consent_evidence" FORCE ROW LEVEL SECURITY;
CREATE POLICY "consent_evidence_scope" ON m00."consent_evidence" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."consent_withdrawal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."consent_withdrawal" FORCE ROW LEVEL SECURITY;
CREATE POLICY "consent_withdrawal_scope" ON m00."consent_withdrawal" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "user_id" = m00.current_user_id()));
ALTER TABLE m00."representation_authorization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."representation_authorization" FORCE ROW LEVEL SECURITY;
CREATE POLICY "representation_authorization_read" ON m00."representation_authorization" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "representation_authorization_write" ON m00."representation_authorization" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."privacy_request" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."privacy_request" FORCE ROW LEVEL SECURITY;
CREATE POLICY "privacy_request_scope" ON m00."privacy_request" FOR ALL USING (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "requester_user_id" = m00.current_user_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_user_id() IS NOT NULL AND "requester_user_id" = m00.current_user_id()));
ALTER TABLE m00."legal_hold" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."legal_hold" FORCE ROW LEVEL SECURITY;
CREATE POLICY "legal_hold_read" ON m00."legal_hold" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "legal_hold_write" ON m00."legal_hold" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."audit_event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."audit_event" FORCE ROW LEVEL SECURITY;
CREATE POLICY "audit_event_scope" ON m00."audit_event" FOR ALL USING (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."task" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."task" FORCE ROW LEVEL SECURITY;
CREATE POLICY "task_scope" ON m00."task" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."operational_team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."operational_team" FORCE ROW LEVEL SECURITY;
CREATE POLICY "operational_team_scope" ON m00."operational_team" FOR ALL USING (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."exception" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."exception" FORCE ROW LEVEL SECURITY;
CREATE POLICY "exception_read" ON m00."exception" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "exception_write" ON m00."exception" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."connector_definition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."connector_definition" FORCE ROW LEVEL SECURITY;
CREATE POLICY "connector_definition_read" ON m00."connector_definition" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "connector_definition_write" ON m00."connector_definition" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."connector_instance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."connector_instance" FORCE ROW LEVEL SECURITY;
CREATE POLICY "connector_instance_read" ON m00."connector_instance" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "connector_instance_write" ON m00."connector_instance" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."provider_route" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."provider_route" FORCE ROW LEVEL SECURITY;
CREATE POLICY "provider_route_scope" ON m00."provider_route" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."credential_reference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."credential_reference" FORCE ROW LEVEL SECURITY;
CREATE POLICY "credential_reference_read" ON m00."credential_reference" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "credential_reference_write" ON m00."credential_reference" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."integration_job" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."integration_job" FORCE ROW LEVEL SECURITY;
CREATE POLICY "integration_job_scope" ON m00."integration_job" FOR ALL USING (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."webhook_receipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."webhook_receipt" FORCE ROW LEVEL SECURITY;
CREATE POLICY "webhook_receipt_read" ON m00."webhook_receipt" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "webhook_receipt_write" ON m00."webhook_receipt" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."reconciliation_run" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."reconciliation_run" FORCE ROW LEVEL SECURITY;
CREATE POLICY "reconciliation_run_read" ON m00."reconciliation_run" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "reconciliation_run_write" ON m00."reconciliation_run" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."import_job" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."import_job" FORCE ROW LEVEL SECURITY;
CREATE POLICY "import_job_scope" ON m00."import_job" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."export_job" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."export_job" FORCE ROW LEVEL SECURITY;
CREATE POLICY "export_job_scope" ON m00."export_job" FOR ALL USING (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."usage_record" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."usage_record" FORCE ROW LEVEL SECURITY;
CREATE POLICY "usage_record_scope" ON m00."usage_record" FOR ALL USING (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."launch_gate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."launch_gate" FORCE ROW LEVEL SECURITY;
CREATE POLICY "launch_gate_read" ON m00."launch_gate" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "launch_gate_write" ON m00."launch_gate" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."launch_gate_evidence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."launch_gate_evidence" FORCE ROW LEVEL SECURITY;
CREATE POLICY "launch_gate_evidence_read" ON m00."launch_gate_evidence" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "launch_gate_evidence_write" ON m00."launch_gate_evidence" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."release_record" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."release_record" FORCE ROW LEVEL SECURITY;
CREATE POLICY "release_record_read" ON m00."release_record" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "release_record_write" ON m00."release_record" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."role_permission_grant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."role_permission_grant" FORCE ROW LEVEL SECURITY;
CREATE POLICY "role_permission_grant_read" ON m00."role_permission_grant" FOR SELECT USING (m00.current_user_id() IS NOT NULL OR m00.is_platform_admin());
CREATE POLICY "role_permission_grant_write" ON m00."role_permission_grant" FOR ALL USING (m00.is_platform_admin()) WITH CHECK (m00.is_platform_admin());
ALTER TABLE m00."idempotency_record" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."idempotency_record" FORCE ROW LEVEL SECURITY;
CREATE POLICY "idempotency_record_scope" ON m00."idempotency_record" FOR ALL USING (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));
ALTER TABLE m00."outbox_event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE m00."outbox_event" FORCE ROW LEVEL SECURITY;
CREATE POLICY "outbox_event_scope" ON m00."outbox_event" FOR ALL USING (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id())) WITH CHECK (m00.is_platform_admin() OR "tenant_id" IS NULL OR (m00.current_tenant_id() IS NOT NULL AND "tenant_id" = m00.current_tenant_id()));