-- ABox Lucie M00 Platform Foundation - PostgreSQL migration V003 v1.1
-- Foreign keys, checks, uniqueness and performance indexes.

ALTER TABLE m00."actor_profile" ADD CONSTRAINT "fk_actor_profile_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."contact_method" ADD CONSTRAINT "fk_contact_method_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."identity_verification" ADD CONSTRAINT "fk_identity_verification_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."session" ADD CONSTRAINT "fk_session_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."mfa_enrollment" ADD CONSTRAINT "fk_mfa_enrollment_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."tenant_membership" ADD CONSTRAINT "fk_tenant_membership_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."role_assignment" ADD CONSTRAINT "fk_role_assignment_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."role_assignment" ADD CONSTRAINT "fk_role_assignment_role_template_id" FOREIGN KEY ("role_template_id") REFERENCES m00."role_template" ("role_template_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."access_decision" ADD CONSTRAINT "fk_access_decision_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."access_decision" ADD CONSTRAINT "fk_access_decision_workload_identity_id" FOREIGN KEY ("workload_identity_id") REFERENCES m00."workload_identity" ("workload_identity_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."privileged_access_grant" ADD CONSTRAINT "fk_privileged_access_grant_administrator_user_id" FOREIGN KEY ("administrator_user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."workload_identity" ADD CONSTRAINT "fk_workload_identity_credential_reference_id" FOREIGN KEY ("credential_reference_id") REFERENCES m00."credential_reference" ("credential_reference_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."commercial_activation" ADD CONSTRAINT "fk_commercial_activation_approved_by" FOREIGN KEY ("approved_by") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."emergency_disable" ADD CONSTRAINT "fk_emergency_disable_disabled_by" FOREIGN KEY ("disabled_by") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."workspace_preference" ADD CONSTRAINT "fk_workspace_preference_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."consent_evidence" ADD CONSTRAINT "fk_consent_evidence_consent_definition_id" FOREIGN KEY ("consent_definition_id") REFERENCES m00."consent_definition" ("consent_definition_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."consent_evidence" ADD CONSTRAINT "fk_consent_evidence_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."consent_withdrawal" ADD CONSTRAINT "fk_consent_withdrawal_consent_evidence_id" FOREIGN KEY ("consent_evidence_id") REFERENCES m00."consent_evidence" ("consent_evidence_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."consent_withdrawal" ADD CONSTRAINT "fk_consent_withdrawal_user_id" FOREIGN KEY ("user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."representation_authorization" ADD CONSTRAINT "fk_representation_authorization_representative_user_id" FOREIGN KEY ("representative_user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."privacy_request" ADD CONSTRAINT "fk_privacy_request_requester_user_id" FOREIGN KEY ("requester_user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."privacy_request" ADD CONSTRAINT "fk_privacy_request_assigned_team_id" FOREIGN KEY ("assigned_team_id") REFERENCES m00."operational_team" ("operational_team_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."legal_hold" ADD CONSTRAINT "fk_legal_hold_owner_user_id" FOREIGN KEY ("owner_user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."audit_event" ADD CONSTRAINT "fk_audit_event_actor_user_id" FOREIGN KEY ("actor_user_id") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."audit_event" ADD CONSTRAINT "fk_audit_event_workload_identity_id" FOREIGN KEY ("workload_identity_id") REFERENCES m00."workload_identity" ("workload_identity_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."connector_instance" ADD CONSTRAINT "fk_connector_instance_connector_definition_id" FOREIGN KEY ("connector_definition_id") REFERENCES m00."connector_definition" ("connector_definition_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."connector_instance" ADD CONSTRAINT "fk_connector_instance_credential_reference_id" FOREIGN KEY ("credential_reference_id") REFERENCES m00."credential_reference" ("credential_reference_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."provider_route" ADD CONSTRAINT "fk_provider_route_connector_instance_id" FOREIGN KEY ("connector_instance_id") REFERENCES m00."connector_instance" ("connector_instance_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."integration_job" ADD CONSTRAINT "fk_integration_job_connector_instance_id" FOREIGN KEY ("connector_instance_id") REFERENCES m00."connector_instance" ("connector_instance_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."webhook_receipt" ADD CONSTRAINT "fk_webhook_receipt_connector_instance_id" FOREIGN KEY ("connector_instance_id") REFERENCES m00."connector_instance" ("connector_instance_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."webhook_receipt" ADD CONSTRAINT "fk_webhook_receipt_related_job_id" FOREIGN KEY ("related_job_id") REFERENCES m00."integration_job" ("integration_job_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."reconciliation_run" ADD CONSTRAINT "fk_reconciliation_run_connector_instance_id" FOREIGN KEY ("connector_instance_id") REFERENCES m00."connector_instance" ("connector_instance_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."export_job" ADD CONSTRAINT "fk_export_job_requested_by" FOREIGN KEY ("requested_by") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."launch_gate_evidence" ADD CONSTRAINT "fk_launch_gate_evidence_launch_gate_id" FOREIGN KEY ("launch_gate_id") REFERENCES m00."launch_gate" ("launch_gate_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."launch_gate_evidence" ADD CONSTRAINT "fk_launch_gate_evidence_approved_by" FOREIGN KEY ("approved_by") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."release_record" ADD CONSTRAINT "fk_release_record_release_owner" FOREIGN KEY ("release_owner") REFERENCES m00."user_identity" ("user_id") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m00."role_permission_grant" ADD CONSTRAINT "fk_role_permission_role" FOREIGN KEY ("role_template_id") REFERENCES m00."role_template" ("role_template_id") ON DELETE RESTRICT;
ALTER TABLE m00."role_permission_grant" ADD CONSTRAINT "fk_role_permission_permission" FOREIGN KEY ("permission_id") REFERENCES m00."permission_definition" ("permission_id") ON DELETE RESTRICT;
ALTER TABLE m00."idempotency_record" ADD CONSTRAINT "fk_idempotency_user" FOREIGN KEY ("actor_user_id") REFERENCES m00."user_identity" ("user_id") ON DELETE RESTRICT;
ALTER TABLE m00."idempotency_record" ADD CONSTRAINT "fk_idempotency_workload" FOREIGN KEY ("workload_identity_id") REFERENCES m00."workload_identity" ("workload_identity_id") ON DELETE RESTRICT;
ALTER TABLE m00."user_identity" ADD CONSTRAINT "ck_user_identity_01" CHECK ("account_status" IN ('PENDING_VERIFICATION', 'ACTIVE', 'LOCKED', 'SUSPENDED', 'ENDED'));
ALTER TABLE m00."user_identity" ADD CONSTRAINT "ck_user_identity_02" CHECK ("primary_locale" IN ('en-US', 'es-US'));
ALTER TABLE m00."user_identity" ADD CONSTRAINT "ck_user_identity_03" CHECK ("version" > 0);
ALTER TABLE m00."actor_profile" ADD CONSTRAINT "ck_actor_profile_01" CHECK ("actor_type" IN ('WORKFORCE', 'CONSUMER', 'EMPLOYER_CONTACT', 'WORKLOAD'));
ALTER TABLE m00."actor_profile" ADD CONSTRAINT "ck_actor_profile_02" CHECK ("status" IN ('ACTIVE', 'SUSPENDED', 'ENDED'));
ALTER TABLE m00."actor_profile" ADD CONSTRAINT "ck_actor_profile_03" CHECK ("version" > 0);
ALTER TABLE m00."contact_method" ADD CONSTRAINT "ck_contact_method_01" CHECK ("type" IN ('EMAIL', 'TELEPHONE'));
ALTER TABLE m00."contact_method" ADD CONSTRAINT "ck_contact_method_02" CHECK (length("normalized_value") BETWEEN 1 AND 2048);
ALTER TABLE m00."contact_method" ADD CONSTRAINT "ck_contact_method_03" CHECK ("status" IN ('PENDING_VERIFICATION', 'VERIFIED', 'SUSPENDED', 'ENDED'));
ALTER TABLE m00."contact_method" ADD CONSTRAINT "ck_contact_method_04" CHECK ("version" > 0);
ALTER TABLE m00."contact_method" ADD CONSTRAINT "ck_contact_method_05" CHECK ("status" <> 'VERIFIED' OR "verified_at" IS NOT NULL);
ALTER TABLE m00."identity_verification" ADD CONSTRAINT "ck_identity_verification_01" CHECK ("method" IN ('EMAIL_LINK', 'SMS_OTP', 'TOTP', 'MANUAL_EVIDENCE'));
ALTER TABLE m00."identity_verification" ADD CONSTRAINT "ck_identity_verification_02" CHECK ("result" IN ('PENDING', 'PASSED', 'FAILED', 'EXPIRED'));
ALTER TABLE m00."identity_verification" ADD CONSTRAINT "ck_identity_verification_03" CHECK ("version" > 0);
ALTER TABLE m00."identity_verification" ADD CONSTRAINT "ck_identity_verification_04" CHECK ("result" <> 'PASSED' OR "verified_at" IS NOT NULL);
ALTER TABLE m00."invitation" ADD CONSTRAINT "ck_invitation_01" CHECK (length("email") BETWEEN 1 AND 2048);
ALTER TABLE m00."invitation" ADD CONSTRAINT "ck_invitation_02" CHECK (cardinality("role_template_ids") > 0);
ALTER TABLE m00."invitation" ADD CONSTRAINT "ck_invitation_03" CHECK ("status" IN ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED'));
ALTER TABLE m00."invitation" ADD CONSTRAINT "ck_invitation_04" CHECK ("version" > 0);
ALTER TABLE m00."session" ADD CONSTRAINT "ck_session_01" CHECK ("actor_type" IN ('WORKFORCE', 'CONSUMER', 'EMPLOYER_CONTACT', 'WORKLOAD'));
ALTER TABLE m00."session" ADD CONSTRAINT "ck_session_02" CHECK ("authentication_strength" IN ('PASSWORD', 'OTP', 'MFA', 'STEP_UP', 'WORKLOAD_MTLS'));
ALTER TABLE m00."session" ADD CONSTRAINT "ck_session_03" CHECK ("version" > 0);
ALTER TABLE m00."session" ADD CONSTRAINT "ck_session_04" CHECK ("expires_at" > "issued_at");
ALTER TABLE m00."session" ADD CONSTRAINT "ck_session_05" CHECK ("revoked_at" IS NULL OR "revoked_at" >= "issued_at");
ALTER TABLE m00."mfa_enrollment" ADD CONSTRAINT "ck_mfa_enrollment_01" CHECK ("method" IN ('TOTP', 'RECOVERY_CODE'));
ALTER TABLE m00."mfa_enrollment" ADD CONSTRAINT "ck_mfa_enrollment_02" CHECK ("status" IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'ENDED'));
ALTER TABLE m00."mfa_enrollment" ADD CONSTRAINT "ck_mfa_enrollment_03" CHECK ("version" > 0);
ALTER TABLE m00."tenant_membership" ADD CONSTRAINT "ck_tenant_membership_01" CHECK ("status" IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'ENDED'));
ALTER TABLE m00."tenant_membership" ADD CONSTRAINT "ck_tenant_membership_02" CHECK ("version" > 0);
ALTER TABLE m00."tenant_membership" ADD CONSTRAINT "ck_tenant_membership_03" CHECK ("effective_to" IS NULL OR "effective_to" > "effective_from");
ALTER TABLE m00."role_template" ADD CONSTRAINT "ck_role_template_01" CHECK (length(btrim("code")) > 0);
ALTER TABLE m00."role_template" ADD CONSTRAINT "ck_role_template_02" CHECK (length(btrim("name")) > 0);
ALTER TABLE m00."role_template" ADD CONSTRAINT "ck_role_template_03" CHECK ("actor_type" IN ('WORKFORCE', 'CONSUMER', 'EMPLOYER_CONTACT', 'WORKLOAD'));
ALTER TABLE m00."role_template" ADD CONSTRAINT "ck_role_template_04" CHECK ("version" > 0);
ALTER TABLE m00."role_template" ADD CONSTRAINT "ck_role_template_05" CHECK ("status" IN ('ACTIVE', 'RETIRED'));
ALTER TABLE m00."permission_definition" ADD CONSTRAINT "ck_permission_definition_01" CHECK (length(btrim("code")) > 0);
ALTER TABLE m00."permission_definition" ADD CONSTRAINT "ck_permission_definition_02" CHECK ("risk_level" IN ('LOW', 'MODERATE', 'HIGH', 'PRIVILEGED'));
ALTER TABLE m00."permission_definition" ADD CONSTRAINT "ck_permission_definition_03" CHECK ("version" > 0);
ALTER TABLE m00."role_assignment" ADD CONSTRAINT "ck_role_assignment_01" CHECK ("version" > 0);
ALTER TABLE m00."role_assignment" ADD CONSTRAINT "ck_role_assignment_02" CHECK ("effective_to" IS NULL OR "effective_to" > "effective_from");
ALTER TABLE m00."access_decision" ADD CONSTRAINT "ck_access_decision_01" CHECK (length(btrim("permission_code")) > 0);
ALTER TABLE m00."access_decision" ADD CONSTRAINT "ck_access_decision_02" CHECK ("result" IN ('ALLOWED', 'DENIED'));
ALTER TABLE m00."access_decision" ADD CONSTRAINT "ck_access_decision_03" CHECK (length(btrim("reason_code")) > 0);
ALTER TABLE m00."access_decision" ADD CONSTRAINT "ck_access_decision_04" CHECK ("version" > 0);
ALTER TABLE m00."access_decision" ADD CONSTRAINT "ck_access_decision_05" CHECK (num_nonnulls("user_id", "workload_identity_id") = 1);
ALTER TABLE m00."privileged_access_grant" ADD CONSTRAINT "ck_privileged_access_grant_01" CHECK ("mode" IN ('READ_ONLY', 'EMERGENCY_WRITE'));
ALTER TABLE m00."privileged_access_grant" ADD CONSTRAINT "ck_privileged_access_grant_02" CHECK (length(btrim("reason_code")) > 0);
ALTER TABLE m00."privileged_access_grant" ADD CONSTRAINT "ck_privileged_access_grant_03" CHECK ("status" IN ('REQUESTED', 'APPROVED', 'ACTIVE', 'EXPIRED', 'REVOKED', 'DENIED'));
ALTER TABLE m00."privileged_access_grant" ADD CONSTRAINT "ck_privileged_access_grant_04" CHECK ("version" > 0);
ALTER TABLE m00."privileged_access_grant" ADD CONSTRAINT "ck_privileged_access_grant_05" CHECK ("expires_at" > "starts_at");
ALTER TABLE m00."privileged_access_grant" ADD CONSTRAINT "ck_privileged_access_grant_06" CHECK ("expires_at" <= "starts_at" + interval '60 minutes');
ALTER TABLE m00."workload_identity" ADD CONSTRAINT "ck_workload_identity_01" CHECK (length(btrim("name")) > 0);
ALTER TABLE m00."workload_identity" ADD CONSTRAINT "ck_workload_identity_02" CHECK (length(btrim("owner")) > 0);
ALTER TABLE m00."workload_identity" ADD CONSTRAINT "ck_workload_identity_03" CHECK (length(btrim("purpose")) > 0);
ALTER TABLE m00."workload_identity" ADD CONSTRAINT "ck_workload_identity_04" CHECK ("environment" IN ('LOCAL_DEVELOPMENT', 'QA', 'UAT', 'PRODUCTION'));
ALTER TABLE m00."workload_identity" ADD CONSTRAINT "ck_workload_identity_05" CHECK ("status" IN ('ACTIVE', 'SUSPENDED', 'RETIRED'));
ALTER TABLE m00."workload_identity" ADD CONSTRAINT "ck_workload_identity_06" CHECK ("version" > 0);
ALTER TABLE m00."commercial_activation" ADD CONSTRAINT "ck_commercial_activation_01" CHECK ("status" IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'ENDED'));
ALTER TABLE m00."commercial_activation" ADD CONSTRAINT "ck_commercial_activation_02" CHECK ("version" > 0);
ALTER TABLE m00."commercial_activation" ADD CONSTRAINT "ck_commercial_activation_03" CHECK ("effective_to" IS NULL OR "effective_to" > "effective_from");
ALTER TABLE m00."entitlement_grant" ADD CONSTRAINT "ck_entitlement_grant_01" CHECK ("entitlement_type" IN ('PRODUCT_LINE', 'CHANNEL'));
ALTER TABLE m00."entitlement_grant" ADD CONSTRAINT "ck_entitlement_grant_02" CHECK (length(btrim("entitlement_code")) > 0);
ALTER TABLE m00."entitlement_grant" ADD CONSTRAINT "ck_entitlement_grant_03" CHECK ("status" IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'ENDED'));
ALTER TABLE m00."entitlement_grant" ADD CONSTRAINT "ck_entitlement_grant_04" CHECK ("version" > 0);
ALTER TABLE m00."entitlement_grant" ADD CONSTRAINT "ck_entitlement_grant_05" CHECK ("effective_to" IS NULL OR "effective_to" > "effective_from");
ALTER TABLE m00."seat_allocation" ADD CONSTRAINT "ck_seat_allocation_01" CHECK ("allocated_count" >= 0);
ALTER TABLE m00."seat_allocation" ADD CONSTRAINT "ck_seat_allocation_02" CHECK ("active_count" >= 0);
ALTER TABLE m00."seat_allocation" ADD CONSTRAINT "ck_seat_allocation_03" CHECK ("version" > 0);
ALTER TABLE m00."seat_allocation" ADD CONSTRAINT "ck_seat_allocation_04" CHECK ("active_count" <= "allocated_count");
ALTER TABLE m00."feature_control" ADD CONSTRAINT "ck_feature_control_01" CHECK (length(btrim("feature_code")) > 0);
ALTER TABLE m00."feature_control" ADD CONSTRAINT "ck_feature_control_02" CHECK ("environment" IN ('LOCAL_DEVELOPMENT', 'QA', 'UAT', 'PRODUCTION'));
ALTER TABLE m00."feature_control" ADD CONSTRAINT "ck_feature_control_03" CHECK ("target_type" IN ('ENVIRONMENT', 'ALL_LUCIE_TENANTS', 'SELECTED_TENANT', 'NAMED_LAUNCH_COHORT'));
ALTER TABLE m00."feature_control" ADD CONSTRAINT "ck_feature_control_04" CHECK ("version" > 0);
ALTER TABLE m00."emergency_disable" ADD CONSTRAINT "ck_emergency_disable_01" CHECK (length(btrim("feature_code")) > 0);
ALTER TABLE m00."emergency_disable" ADD CONSTRAINT "ck_emergency_disable_02" CHECK ("scope_type" IN ('ENVIRONMENT', 'ALL_LUCIE_TENANTS', 'SELECTED_TENANT', 'NAMED_LAUNCH_COHORT'));
ALTER TABLE m00."emergency_disable" ADD CONSTRAINT "ck_emergency_disable_03" CHECK (length(btrim("reason_code")) > 0);
ALTER TABLE m00."emergency_disable" ADD CONSTRAINT "ck_emergency_disable_04" CHECK ("version" > 0);
ALTER TABLE m00."platform_configuration" ADD CONSTRAINT "ck_platform_configuration_01" CHECK (length(btrim("key")) > 0);
ALTER TABLE m00."platform_configuration" ADD CONSTRAINT "ck_platform_configuration_02" CHECK ("scope_type" IN ('PLATFORM', 'TENANT', 'MARKETPLACE', 'USER'));
ALTER TABLE m00."platform_configuration" ADD CONSTRAINT "ck_platform_configuration_03" CHECK ("version" > 0);
ALTER TABLE m00."workspace_preference" ADD CONSTRAINT "ck_workspace_preference_01" CHECK ("locale" IN ('en-US', 'es-US'));
ALTER TABLE m00."workspace_preference" ADD CONSTRAINT "ck_workspace_preference_02" CHECK ("version" > 0);
ALTER TABLE m00."reference_geography" ADD CONSTRAINT "ck_reference_geography_01" CHECK (length(btrim("country_code")) > 0);
ALTER TABLE m00."reference_geography" ADD CONSTRAINT "ck_reference_geography_02" CHECK (length(btrim("subdivision_code")) > 0);
ALTER TABLE m00."reference_geography" ADD CONSTRAINT "ck_reference_geography_03" CHECK ("status" IN ('ACTIVE', 'INACTIVE'));
ALTER TABLE m00."reference_geography" ADD CONSTRAINT "ck_reference_geography_04" CHECK ("version" > 0);
ALTER TABLE m00."consent_definition" ADD CONSTRAINT "ck_consent_definition_01" CHECK (length(btrim("consent_code")) > 0);
ALTER TABLE m00."consent_definition" ADD CONSTRAINT "ck_consent_definition_02" CHECK (length(btrim("purpose")) > 0);
ALTER TABLE m00."consent_definition" ADD CONSTRAINT "ck_consent_definition_03" CHECK ("requiredness" IN ('REQUIRED', 'OPTIONAL'));
ALTER TABLE m00."consent_definition" ADD CONSTRAINT "ck_consent_definition_04" CHECK ("language" IN ('en-US', 'es-US'));
ALTER TABLE m00."consent_definition" ADD CONSTRAINT "ck_consent_definition_05" CHECK ("status" IN ('DRAFT', 'ACTIVE', 'RETIRED'));
ALTER TABLE m00."consent_definition" ADD CONSTRAINT "ck_consent_definition_06" CHECK ("version" > 0);
ALTER TABLE m00."consent_evidence" ADD CONSTRAINT "ck_consent_evidence_01" CHECK ("actor_type" IN ('WORKFORCE', 'CONSUMER', 'EMPLOYER_CONTACT', 'WORKLOAD'));
ALTER TABLE m00."consent_evidence" ADD CONSTRAINT "ck_consent_evidence_02" CHECK ("language" IN ('en-US', 'es-US'));
ALTER TABLE m00."consent_evidence" ADD CONSTRAINT "ck_consent_evidence_03" CHECK ("collection_method" IN ('DIGITAL', 'VERBAL_APPROVED_SCRIPT', 'SYSTEM_ACKNOWLEDGEMENT'));
ALTER TABLE m00."consent_evidence" ADD CONSTRAINT "ck_consent_evidence_04" CHECK ("version" > 0);
ALTER TABLE m00."consent_withdrawal" ADD CONSTRAINT "ck_consent_withdrawal_01" CHECK ("channel" IN ('IN_APP', 'EMAIL', 'TELEPHONE', 'ADMINISTRATIVE'));
ALTER TABLE m00."consent_withdrawal" ADD CONSTRAINT "ck_consent_withdrawal_02" CHECK ("version" > 0);
ALTER TABLE m00."representation_authorization" ADD CONSTRAINT "ck_representation_authorization_01" CHECK ("authorization_type" IN ('HOUSEHOLD_APPLICATION_FILER', 'AUTHORIZED_REPRESENTATIVE', 'RECOGNIZED_LEGAL_AUTHORITY'));
ALTER TABLE m00."representation_authorization" ADD CONSTRAINT "ck_representation_authorization_02" CHECK (cardinality("scope_codes") > 0);
ALTER TABLE m00."representation_authorization" ADD CONSTRAINT "ck_representation_authorization_03" CHECK ("language" IN ('en-US', 'es-US'));
ALTER TABLE m00."representation_authorization" ADD CONSTRAINT "ck_representation_authorization_04" CHECK ("status" IN ('PROPOSED', 'ACTIVE', 'REVOKED', 'EXPIRED', 'DENIED'));
ALTER TABLE m00."representation_authorization" ADD CONSTRAINT "ck_representation_authorization_05" CHECK ("version" > 0);
ALTER TABLE m00."representation_authorization" ADD CONSTRAINT "ck_representation_authorization_06" CHECK ("revoked_at" IS NULL OR "revoked_at" >= "effective_from");
ALTER TABLE m00."privacy_request" ADD CONSTRAINT "ck_privacy_request_01" CHECK ("request_type" IN ('ACCESS', 'CORRECTION', 'PORTABILITY', 'ACCOUNT_CLOSURE', 'DELETION', 'USAGE_SHARING_EXPLANATION'));
ALTER TABLE m00."privacy_request" ADD CONSTRAINT "ck_privacy_request_02" CHECK ("status" IN ('SUBMITTED', 'IN_REVIEW', 'COMPLETED', 'DENIED'));
ALTER TABLE m00."privacy_request" ADD CONSTRAINT "ck_privacy_request_03" CHECK ("version" > 0);
ALTER TABLE m00."privacy_request" ADD CONSTRAINT "ck_privacy_request_04" CHECK ("completed_at" IS NULL OR "completed_at" >= "submitted_at");
ALTER TABLE m00."legal_hold" ADD CONSTRAINT "ck_legal_hold_01" CHECK ("target_type" IN ('TENANT', 'USER', 'HOUSEHOLD', 'APPLICATION_ENROLLMENT', 'DOCUMENT', 'HANDOFF', 'RECORD_SET'));
ALTER TABLE m00."legal_hold" ADD CONSTRAINT "ck_legal_hold_02" CHECK ("status" IN ('ACTIVE', 'RELEASED'));
ALTER TABLE m00."legal_hold" ADD CONSTRAINT "ck_legal_hold_03" CHECK ("version" > 0);
ALTER TABLE m00."legal_hold" ADD CONSTRAINT "ck_legal_hold_04" CHECK ("released_at" IS NULL OR "released_at" >= "starts_at");
ALTER TABLE m00."audit_event" ADD CONSTRAINT "ck_audit_event_01" CHECK (length(btrim("event_code")) > 0);
ALTER TABLE m00."audit_event" ADD CONSTRAINT "ck_audit_event_02" CHECK ("payload_hash" ~ '^[A-Fa-f0-9]{64}$');
ALTER TABLE m00."audit_event" ADD CONSTRAINT "ck_audit_event_03" CHECK ("version" > 0);
ALTER TABLE m00."task" ADD CONSTRAINT "ck_task_01" CHECK ("assignee_type" IN ('USER', 'TEAM', 'CONSUMER', 'EMPLOYER_CONTACT', 'JET_OPERATIONS', 'RESPONSIBLE_AGENCY', 'EXTERNAL_PARTY'));
ALTER TABLE m00."task" ADD CONSTRAINT "ck_task_02" CHECK ("status" IN ('OPEN', 'IN_PROGRESS', 'WAITING_ON_CONSUMER', 'WAITING_ON_EXTERNAL_PARTY', 'BLOCKED', 'COMPLETED'));
ALTER TABLE m00."task" ADD CONSTRAINT "ck_task_03" CHECK ("priority" IN ('NORMAL', 'HIGH', 'URGENT'));
ALTER TABLE m00."task" ADD CONSTRAINT "ck_task_04" CHECK ("version" > 0);
ALTER TABLE m00."operational_team" ADD CONSTRAINT "ck_operational_team_01" CHECK ("team_type" IN ('JET_PLATFORM_OPERATIONS', 'JET_COMPLIANCE_REVIEW', 'JET_INTEGRATION_SUPPORT', 'AGENCY_ADMINISTRATION', 'AGENCY_SALES', 'AGENCY_SUPPORT'));
ALTER TABLE m00."operational_team" ADD CONSTRAINT "ck_operational_team_02" CHECK ("status" IN ('ACTIVE', 'INACTIVE'));
ALTER TABLE m00."operational_team" ADD CONSTRAINT "ck_operational_team_03" CHECK (cardinality("member_user_ids") > 0);
ALTER TABLE m00."operational_team" ADD CONSTRAINT "ck_operational_team_04" CHECK ("version" > 0);
ALTER TABLE m00."exception" ADD CONSTRAINT "ck_exception_01" CHECK ("severity" IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW'));
ALTER TABLE m00."exception" ADD CONSTRAINT "ck_exception_02" CHECK ("status" IN ('OPEN', 'IN_PROGRESS', 'BLOCKED', 'RESOLVED', 'CLOSED'));
ALTER TABLE m00."exception" ADD CONSTRAINT "ck_exception_03" CHECK ("version" > 0);
ALTER TABLE m00."connector_definition" ADD CONSTRAINT "ck_connector_definition_01" CHECK (length(btrim("connector_code")) > 0);
-- CCL-004: ck_connector_definition_02 as released compares a text[] column with a scalar IN list and is rejected by PostgreSQL (22P02). Held pending an approved change record; no other statement altered.
ALTER TABLE m00."connector_definition" ADD CONSTRAINT "ck_connector_definition_03" CHECK (cardinality("supported_environments") > 0);
ALTER TABLE m00."connector_definition" ADD CONSTRAINT "ck_connector_definition_04" CHECK ("status" IN ('ACTIVE', 'RETIRED'));
ALTER TABLE m00."connector_definition" ADD CONSTRAINT "ck_connector_definition_05" CHECK ("version" > 0);
ALTER TABLE m00."connector_instance" ADD CONSTRAINT "ck_connector_instance_01" CHECK ("environment" IN ('LOCAL_DEVELOPMENT', 'QA', 'UAT', 'PRODUCTION'));
ALTER TABLE m00."connector_instance" ADD CONSTRAINT "ck_connector_instance_02" CHECK ("lifecycle_status" IN ('DRAFT', 'TESTING', 'READY', 'ACTIVE', 'SUSPENDED', 'RETIRED'));
ALTER TABLE m00."connector_instance" ADD CONSTRAINT "ck_connector_instance_03" CHECK ("health_status" IN ('HEALTHY', 'DEGRADED', 'UNAVAILABLE', 'UNKNOWN'));
ALTER TABLE m00."connector_instance" ADD CONSTRAINT "ck_connector_instance_04" CHECK ("version" > 0);
ALTER TABLE m00."connector_instance" ADD CONSTRAINT "ck_connector_instance_05" CHECK ("lifecycle_status" <> 'ACTIVE' OR "health_status" IN ('HEALTHY','DEGRADED'));
ALTER TABLE m00."provider_route" ADD CONSTRAINT "ck_provider_route_01" CHECK ("service_type" IN ('SMS', 'ELECTRONIC_SIGNATURE', 'SECURE_EMAIL'));
ALTER TABLE m00."provider_route" ADD CONSTRAINT "ck_provider_route_02" CHECK ("commercial_model" IN ('AGENCY_OWNED', 'JET_PAY_TO_USE', 'NOT_ENABLED'));
ALTER TABLE m00."provider_route" ADD CONSTRAINT "ck_provider_route_03" CHECK ("status" IN ('DRAFT', 'TESTING', 'READY', 'ACTIVE', 'SUSPENDED', 'ENDED'));
ALTER TABLE m00."provider_route" ADD CONSTRAINT "ck_provider_route_04" CHECK ("version" > 0);
ALTER TABLE m00."provider_route" ADD CONSTRAINT "ck_provider_route_05" CHECK ("effective_to" IS NULL OR "effective_to" > "effective_from");
ALTER TABLE m00."credential_reference" ADD CONSTRAINT "ck_credential_reference_01" CHECK (length("secret_path_reference") BETWEEN 1 AND 2048);
ALTER TABLE m00."credential_reference" ADD CONSTRAINT "ck_credential_reference_02" CHECK (length("secret_version_reference") BETWEEN 1 AND 2048);
ALTER TABLE m00."credential_reference" ADD CONSTRAINT "ck_credential_reference_03" CHECK ("environment" IN ('LOCAL_DEVELOPMENT', 'QA', 'UAT', 'PRODUCTION'));
ALTER TABLE m00."credential_reference" ADD CONSTRAINT "ck_credential_reference_04" CHECK (length(btrim("owner")) > 0);
ALTER TABLE m00."credential_reference" ADD CONSTRAINT "ck_credential_reference_05" CHECK ("status" IN ('ACTIVE', 'ROTATION_REQUIRED', 'REVOKED'));
ALTER TABLE m00."credential_reference" ADD CONSTRAINT "ck_credential_reference_06" CHECK ("version" > 0);
ALTER TABLE m00."integration_job" ADD CONSTRAINT "ck_integration_job_01" CHECK ("status" IN ('QUEUED', 'RUNNING', 'WAITING_ON_EXTERNAL_PARTY', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', 'CANCELED'));
ALTER TABLE m00."integration_job" ADD CONSTRAINT "ck_integration_job_02" CHECK ("version" > 0);
ALTER TABLE m00."integration_job" ADD CONSTRAINT "ck_integration_job_03" CHECK ("completed_at" IS NULL OR "started_at" IS NULL OR "completed_at" >= "started_at");
ALTER TABLE m00."webhook_receipt" ADD CONSTRAINT "ck_webhook_receipt_01" CHECK ("signature_result" IN ('VALID', 'INVALID', 'NOT_APPLICABLE'));
ALTER TABLE m00."webhook_receipt" ADD CONSTRAINT "ck_webhook_receipt_02" CHECK ("processing_status" IN ('RECEIVED', 'DUPLICATE', 'PROCESSED', 'QUARANTINED', 'FAILED'));
ALTER TABLE m00."webhook_receipt" ADD CONSTRAINT "ck_webhook_receipt_03" CHECK ("payload_hash" ~ '^[A-Fa-f0-9]{64}$');
ALTER TABLE m00."webhook_receipt" ADD CONSTRAINT "ck_webhook_receipt_04" CHECK ("version" > 0);
ALTER TABLE m00."reconciliation_run" ADD CONSTRAINT "ck_reconciliation_run_01" CHECK ("scope_type" IN ('CONNECTOR', 'TENANT', 'TRANSACTION_TYPE', 'DATE_RANGE'));
ALTER TABLE m00."reconciliation_run" ADD CONSTRAINT "ck_reconciliation_run_02" CHECK ("status" IN ('QUEUED', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', 'CANCELED'));
ALTER TABLE m00."reconciliation_run" ADD CONSTRAINT "ck_reconciliation_run_03" CHECK ("difference_count" >= 0);
ALTER TABLE m00."reconciliation_run" ADD CONSTRAINT "ck_reconciliation_run_04" CHECK ("version" > 0);
ALTER TABLE m00."reconciliation_run" ADD CONSTRAINT "ck_reconciliation_run_05" CHECK ("completed_at" IS NULL OR "completed_at" >= "started_at");
ALTER TABLE m00."import_job" ADD CONSTRAINT "ck_import_job_01" CHECK ("status" IN ('UPLOADED', 'VALIDATING', 'VALIDATED', 'FAILED_VALIDATION', 'COMMITTING', 'COMPLETED', 'FAILED', 'CANCELED'));
ALTER TABLE m00."import_job" ADD CONSTRAINT "ck_import_job_02" CHECK ("row_count" >= 0);
ALTER TABLE m00."import_job" ADD CONSTRAINT "ck_import_job_03" CHECK ("error_count" >= 0);
ALTER TABLE m00."import_job" ADD CONSTRAINT "ck_import_job_04" CHECK ("version" > 0);
ALTER TABLE m00."import_job" ADD CONSTRAINT "ck_import_job_05" CHECK ("error_count" <= "row_count");
ALTER TABLE m00."export_job" ADD CONSTRAINT "ck_export_job_01" CHECK (length(btrim("purpose")) > 0);
ALTER TABLE m00."export_job" ADD CONSTRAINT "ck_export_job_02" CHECK ("status" IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'EXPIRED', 'CANCELED'));
ALTER TABLE m00."export_job" ADD CONSTRAINT "ck_export_job_03" CHECK ("version" > 0);
ALTER TABLE m00."usage_record" ADD CONSTRAINT "ck_usage_record_01" CHECK ("service_type" IN ('SMS', 'ELECTRONIC_SIGNATURE', 'SECURE_EMAIL', 'PLANAI', 'OTHER'));
ALTER TABLE m00."usage_record" ADD CONSTRAINT "ck_usage_record_02" CHECK ("quantity" >= 0);
ALTER TABLE m00."usage_record" ADD CONSTRAINT "ck_usage_record_03" CHECK ("outcome" IN ('SUCCEEDED', 'FAILED', 'PENDING', 'REVERSED', 'CANCELED'));
ALTER TABLE m00."usage_record" ADD CONSTRAINT "ck_usage_record_04" CHECK ("version" > 0);
ALTER TABLE m00."launch_gate" ADD CONSTRAINT "ck_launch_gate_01" CHECK (length(btrim("gate_code")) > 0);
ALTER TABLE m00."launch_gate" ADD CONSTRAINT "ck_launch_gate_02" CHECK ("scope_type" IN ('PLATFORM', 'ENVIRONMENT', 'TENANT', 'MARKETPLACE', 'PATHWAY', 'COHORT'));
ALTER TABLE m00."launch_gate" ADD CONSTRAINT "ck_launch_gate_03" CHECK ("status" IN ('NOT_STARTED', 'IN_PROGRESS', 'PASSED', 'FAILED', 'NOT_APPLICABLE'));
ALTER TABLE m00."launch_gate" ADD CONSTRAINT "ck_launch_gate_04" CHECK ("version" > 0);
ALTER TABLE m00."launch_gate_evidence" ADD CONSTRAINT "ck_launch_gate_evidence_01" CHECK ("result" IN ('SUPPORTS_PASS', 'SUPPORTS_FAIL', 'INFORMATIONAL'));
ALTER TABLE m00."launch_gate_evidence" ADD CONSTRAINT "ck_launch_gate_evidence_02" CHECK ("version" > 0);
-- CCL-005: ck_release_record_01 as released compares release_record.version (declared text in V002) with integer 0 and is rejected by PostgreSQL (42883). Held pending an approved change record; no other statement altered.
ALTER TABLE m00."release_record" ADD CONSTRAINT "ck_release_record_02" CHECK ("environment" IN ('LOCAL_DEVELOPMENT', 'QA', 'UAT', 'PRODUCTION'));
ALTER TABLE m00."release_record" ADD CONSTRAINT "ck_release_record_03" CHECK ("status" IN ('DRAFT', 'CANDIDATE', 'APPROVED', 'DEPLOYED', 'ACTIVATED', 'ROLLED_BACK', 'WITHDRAWN'));
ALTER TABLE m00."release_record" ADD CONSTRAINT "ck_release_record_04" CHECK ("artifact_digest" ~ '^[A-Fa-f0-9]{64}$');
ALTER TABLE m00."release_record" ADD CONSTRAINT "ck_release_record_05" CHECK ("go_no_go" IN ('GO', 'NO_GO', 'CONDITIONAL_GO'));
ALTER TABLE m00."release_record" ADD CONSTRAINT "ck_release_record_06" CHECK ("activated_at" IS NULL OR "deployed_at" IS NOT NULL);
ALTER TABLE m00."role_permission_grant" ADD CONSTRAINT "ck_role_permission_grant_tech_01" CHECK ("access" IN ('ALLOW','DENY','CONDITIONAL'));
ALTER TABLE m00."idempotency_record" ADD CONSTRAINT "ck_idempotency_record_tech_02" CHECK (num_nonnulls("actor_user_id", "workload_identity_id") = 1);
ALTER TABLE m00."idempotency_record" ADD CONSTRAINT "ck_idempotency_record_tech_03" CHECK ("expires_at" > "created_at");
ALTER TABLE m00."idempotency_record" ADD CONSTRAINT "ck_idempotency_record_tech_04" CHECK ("idempotency_key_hash" ~ '^[A-Fa-f0-9]{64}$');
ALTER TABLE m00."idempotency_record" ADD CONSTRAINT "ck_idempotency_record_tech_05" CHECK ("request_hash" ~ '^[A-Fa-f0-9]{64}$');
ALTER TABLE m00."outbox_event" ADD CONSTRAINT "ck_outbox_event_tech_06" CHECK ("attempt_count" >= 0);
ALTER TABLE m00."outbox_event" ADD CONSTRAINT "ck_outbox_event_tech_07" CHECK ("published_at" IS NULL OR "published_at" >= "occurred_at");
CREATE UNIQUE INDEX "uq_contact_normalized" ON m00."contact_method" (lower("normalized_value"), "type");
CREATE UNIQUE INDEX "uq_role_template_code" ON m00."role_template" ("code");
CREATE UNIQUE INDEX "uq_permission_code" ON m00."permission_definition" ("code");
CREATE UNIQUE INDEX "uq_commercial_activation_current" ON m00."commercial_activation" ("tenant_id") WHERE "effective_to" IS NULL;
CREATE UNIQUE INDEX "uq_seat_allocation_current" ON m00."seat_allocation" ("tenant_id");
CREATE UNIQUE INDEX "uq_feature_target" ON m00."feature_control" ("feature_code","environment","target_type","target_reference");
CREATE UNIQUE INDEX "uq_workspace_user" ON m00."workspace_preference" ("user_id");
CREATE UNIQUE INDEX "uq_geography_code" ON m00."reference_geography" ("country_code", COALESCE("subdivision_code",''));
CREATE UNIQUE INDEX "uq_consent_definition" ON m00."consent_definition" ("consent_code","language","content_version");
CREATE UNIQUE INDEX "uq_connector_code" ON m00."connector_definition" ("connector_code");
CREATE UNIQUE INDEX "uq_connector_instance" ON m00."connector_instance" ("connector_definition_id","environment",COALESCE("endpoint_reference",''));
CREATE UNIQUE INDEX "uq_provider_route_active" ON m00."provider_route" ("tenant_id","service_type") WHERE "effective_to" IS NULL AND "status" = 'ACTIVE';
CREATE UNIQUE INDEX "uq_webhook_provider_event" ON m00."webhook_receipt" ("connector_instance_id","provider_event_id");
CREATE UNIQUE INDEX "uq_release_environment_version" ON m00."release_record" ("environment","version");
CREATE UNIQUE INDEX "uq_idempotency_scope" ON m00."idempotency_record" (COALESCE("tenant_id",'00000000-0000-0000-0000-000000000000'::uuid),COALESCE("actor_user_id",'00000000-0000-0000-0000-000000000000'::uuid),COALESCE("workload_identity_id",'00000000-0000-0000-0000-000000000000'::uuid),"operation_id","idempotency_key_hash");
CREATE INDEX "ix_user_identity_created_at" ON m00."user_identity" ("created_at");
CREATE INDEX "ix_user_identity_updated_at" ON m00."user_identity" ("updated_at");
CREATE INDEX "ix_actor_profile_user_id" ON m00."actor_profile" ("user_id");
CREATE INDEX "ix_actor_profile_status" ON m00."actor_profile" ("status");
CREATE INDEX "ix_actor_profile_created_at" ON m00."actor_profile" ("created_at");
CREATE INDEX "ix_actor_profile_updated_at" ON m00."actor_profile" ("updated_at");
CREATE INDEX "ix_contact_method_user_id" ON m00."contact_method" ("user_id");
CREATE INDEX "ix_contact_method_status" ON m00."contact_method" ("status");
CREATE INDEX "ix_contact_method_created_at" ON m00."contact_method" ("created_at");
CREATE INDEX "ix_contact_method_updated_at" ON m00."contact_method" ("updated_at");
CREATE INDEX "ix_identity_verification_user_id" ON m00."identity_verification" ("user_id");
CREATE INDEX "ix_identity_verification_created_at" ON m00."identity_verification" ("created_at");
CREATE INDEX "ix_identity_verification_updated_at" ON m00."identity_verification" ("updated_at");
CREATE INDEX "ix_invitation_tenant_id" ON m00."invitation" ("tenant_id");
CREATE INDEX "ix_invitation_organization_id" ON m00."invitation" ("organization_id");
CREATE INDEX "ix_invitation_status" ON m00."invitation" ("status");
CREATE INDEX "ix_invitation_created_at" ON m00."invitation" ("created_at");
CREATE INDEX "ix_invitation_updated_at" ON m00."invitation" ("updated_at");
CREATE INDEX "ix_session_user_id" ON m00."session" ("user_id");
CREATE INDEX "ix_session_created_at" ON m00."session" ("created_at");
CREATE INDEX "ix_session_updated_at" ON m00."session" ("updated_at");
CREATE INDEX "ix_mfa_enrollment_user_id" ON m00."mfa_enrollment" ("user_id");
CREATE INDEX "ix_mfa_enrollment_status" ON m00."mfa_enrollment" ("status");
CREATE INDEX "ix_mfa_enrollment_created_at" ON m00."mfa_enrollment" ("created_at");
CREATE INDEX "ix_mfa_enrollment_updated_at" ON m00."mfa_enrollment" ("updated_at");
CREATE INDEX "ix_tenant_membership_tenant_id" ON m00."tenant_membership" ("tenant_id");
CREATE INDEX "ix_tenant_membership_user_id" ON m00."tenant_membership" ("user_id");
CREATE INDEX "ix_tenant_membership_organization_id" ON m00."tenant_membership" ("organization_id");
CREATE INDEX "ix_tenant_membership_status" ON m00."tenant_membership" ("status");
CREATE INDEX "ix_tenant_membership_created_at" ON m00."tenant_membership" ("created_at");
CREATE INDEX "ix_tenant_membership_updated_at" ON m00."tenant_membership" ("updated_at");
CREATE INDEX "ix_role_template_status" ON m00."role_template" ("status");
CREATE INDEX "ix_role_template_created_at" ON m00."role_template" ("created_at");
CREATE INDEX "ix_role_template_updated_at" ON m00."role_template" ("updated_at");
CREATE INDEX "ix_permission_definition_created_at" ON m00."permission_definition" ("created_at");
CREATE INDEX "ix_permission_definition_updated_at" ON m00."permission_definition" ("updated_at");
CREATE INDEX "ix_role_assignment_tenant_id" ON m00."role_assignment" ("tenant_id");
CREATE INDEX "ix_role_assignment_user_id" ON m00."role_assignment" ("user_id");
CREATE INDEX "ix_role_assignment_organization_id" ON m00."role_assignment" ("organization_id");
CREATE INDEX "ix_role_assignment_created_at" ON m00."role_assignment" ("created_at");
CREATE INDEX "ix_role_assignment_updated_at" ON m00."role_assignment" ("updated_at");
CREATE INDEX "ix_access_decision_user_id" ON m00."access_decision" ("user_id");
CREATE INDEX "ix_access_decision_created_at" ON m00."access_decision" ("created_at");
CREATE INDEX "ix_access_decision_updated_at" ON m00."access_decision" ("updated_at");
CREATE INDEX "ix_access_decision_occurred_at" ON m00."access_decision" ("occurred_at");
CREATE INDEX "ix_privileged_access_grant_status" ON m00."privileged_access_grant" ("status");
CREATE INDEX "ix_privileged_access_grant_created_at" ON m00."privileged_access_grant" ("created_at");
CREATE INDEX "ix_privileged_access_grant_updated_at" ON m00."privileged_access_grant" ("updated_at");
CREATE INDEX "ix_workload_identity_status" ON m00."workload_identity" ("status");
CREATE INDEX "ix_workload_identity_created_at" ON m00."workload_identity" ("created_at");
CREATE INDEX "ix_workload_identity_updated_at" ON m00."workload_identity" ("updated_at");
CREATE INDEX "ix_commercial_activation_tenant_id" ON m00."commercial_activation" ("tenant_id");
CREATE INDEX "ix_commercial_activation_status" ON m00."commercial_activation" ("status");
CREATE INDEX "ix_commercial_activation_created_at" ON m00."commercial_activation" ("created_at");
CREATE INDEX "ix_commercial_activation_updated_at" ON m00."commercial_activation" ("updated_at");
CREATE INDEX "ix_entitlement_grant_tenant_id" ON m00."entitlement_grant" ("tenant_id");
CREATE INDEX "ix_entitlement_grant_status" ON m00."entitlement_grant" ("status");
CREATE INDEX "ix_entitlement_grant_created_at" ON m00."entitlement_grant" ("created_at");
CREATE INDEX "ix_entitlement_grant_updated_at" ON m00."entitlement_grant" ("updated_at");
CREATE INDEX "ix_seat_allocation_tenant_id" ON m00."seat_allocation" ("tenant_id");
CREATE INDEX "ix_seat_allocation_created_at" ON m00."seat_allocation" ("created_at");
CREATE INDEX "ix_seat_allocation_updated_at" ON m00."seat_allocation" ("updated_at");
CREATE INDEX "ix_feature_control_created_at" ON m00."feature_control" ("created_at");
CREATE INDEX "ix_feature_control_updated_at" ON m00."feature_control" ("updated_at");
CREATE INDEX "ix_emergency_disable_created_at" ON m00."emergency_disable" ("created_at");
CREATE INDEX "ix_emergency_disable_updated_at" ON m00."emergency_disable" ("updated_at");
CREATE INDEX "ix_platform_configuration_created_at" ON m00."platform_configuration" ("created_at");
CREATE INDEX "ix_platform_configuration_updated_at" ON m00."platform_configuration" ("updated_at");
CREATE INDEX "ix_workspace_preference_user_id" ON m00."workspace_preference" ("user_id");
CREATE INDEX "ix_workspace_preference_created_at" ON m00."workspace_preference" ("created_at");
CREATE INDEX "ix_workspace_preference_updated_at" ON m00."workspace_preference" ("updated_at");
CREATE INDEX "ix_reference_geography_status" ON m00."reference_geography" ("status");
CREATE INDEX "ix_reference_geography_created_at" ON m00."reference_geography" ("created_at");
CREATE INDEX "ix_reference_geography_updated_at" ON m00."reference_geography" ("updated_at");
CREATE INDEX "ix_consent_definition_status" ON m00."consent_definition" ("status");
CREATE INDEX "ix_consent_definition_created_at" ON m00."consent_definition" ("created_at");
CREATE INDEX "ix_consent_definition_updated_at" ON m00."consent_definition" ("updated_at");
CREATE INDEX "ix_consent_evidence_tenant_id" ON m00."consent_evidence" ("tenant_id");
CREATE INDEX "ix_consent_evidence_user_id" ON m00."consent_evidence" ("user_id");
CREATE INDEX "ix_consent_evidence_marketplace_id" ON m00."consent_evidence" ("marketplace_id");
CREATE INDEX "ix_consent_evidence_created_at" ON m00."consent_evidence" ("created_at");
CREATE INDEX "ix_consent_evidence_updated_at" ON m00."consent_evidence" ("updated_at");
CREATE INDEX "ix_consent_withdrawal_user_id" ON m00."consent_withdrawal" ("user_id");
CREATE INDEX "ix_consent_withdrawal_created_at" ON m00."consent_withdrawal" ("created_at");
CREATE INDEX "ix_consent_withdrawal_updated_at" ON m00."consent_withdrawal" ("updated_at");
CREATE INDEX "ix_representation_authorization_status" ON m00."representation_authorization" ("status");
CREATE INDEX "ix_representation_authorization_created_at" ON m00."representation_authorization" ("created_at");
CREATE INDEX "ix_representation_authorization_updated_at" ON m00."representation_authorization" ("updated_at");
CREATE INDEX "ix_privacy_request_status" ON m00."privacy_request" ("status");
CREATE INDEX "ix_privacy_request_created_at" ON m00."privacy_request" ("created_at");
CREATE INDEX "ix_privacy_request_updated_at" ON m00."privacy_request" ("updated_at");
CREATE INDEX "ix_legal_hold_status" ON m00."legal_hold" ("status");
CREATE INDEX "ix_legal_hold_created_at" ON m00."legal_hold" ("created_at");
CREATE INDEX "ix_legal_hold_updated_at" ON m00."legal_hold" ("updated_at");
CREATE INDEX "ix_audit_event_tenant_id" ON m00."audit_event" ("tenant_id");
CREATE INDEX "ix_audit_event_organization_id" ON m00."audit_event" ("organization_id");
CREATE INDEX "ix_audit_event_marketplace_id" ON m00."audit_event" ("marketplace_id");
CREATE INDEX "ix_audit_event_created_at" ON m00."audit_event" ("created_at");
CREATE INDEX "ix_audit_event_updated_at" ON m00."audit_event" ("updated_at");
CREATE INDEX "ix_audit_event_occurred_at" ON m00."audit_event" ("occurred_at");
CREATE INDEX "ix_task_tenant_id" ON m00."task" ("tenant_id");
CREATE INDEX "ix_task_status" ON m00."task" ("status");
CREATE INDEX "ix_task_created_at" ON m00."task" ("created_at");
CREATE INDEX "ix_task_updated_at" ON m00."task" ("updated_at");
CREATE INDEX "ix_operational_team_tenant_id" ON m00."operational_team" ("tenant_id");
CREATE INDEX "ix_operational_team_organization_id" ON m00."operational_team" ("organization_id");
CREATE INDEX "ix_operational_team_status" ON m00."operational_team" ("status");
CREATE INDEX "ix_operational_team_created_at" ON m00."operational_team" ("created_at");
CREATE INDEX "ix_operational_team_updated_at" ON m00."operational_team" ("updated_at");
CREATE INDEX "ix_exception_status" ON m00."exception" ("status");
CREATE INDEX "ix_exception_created_at" ON m00."exception" ("created_at");
CREATE INDEX "ix_exception_updated_at" ON m00."exception" ("updated_at");
CREATE INDEX "ix_connector_definition_status" ON m00."connector_definition" ("status");
CREATE INDEX "ix_connector_definition_created_at" ON m00."connector_definition" ("created_at");
CREATE INDEX "ix_connector_definition_updated_at" ON m00."connector_definition" ("updated_at");
CREATE INDEX "ix_connector_instance_created_at" ON m00."connector_instance" ("created_at");
CREATE INDEX "ix_connector_instance_updated_at" ON m00."connector_instance" ("updated_at");
CREATE INDEX "ix_provider_route_tenant_id" ON m00."provider_route" ("tenant_id");
CREATE INDEX "ix_provider_route_status" ON m00."provider_route" ("status");
CREATE INDEX "ix_provider_route_created_at" ON m00."provider_route" ("created_at");
CREATE INDEX "ix_provider_route_updated_at" ON m00."provider_route" ("updated_at");
CREATE INDEX "ix_credential_reference_status" ON m00."credential_reference" ("status");
CREATE INDEX "ix_credential_reference_created_at" ON m00."credential_reference" ("created_at");
CREATE INDEX "ix_credential_reference_updated_at" ON m00."credential_reference" ("updated_at");
CREATE INDEX "ix_integration_job_tenant_id" ON m00."integration_job" ("tenant_id");
CREATE INDEX "ix_integration_job_status" ON m00."integration_job" ("status");
CREATE INDEX "ix_integration_job_created_at" ON m00."integration_job" ("created_at");
CREATE INDEX "ix_integration_job_updated_at" ON m00."integration_job" ("updated_at");
CREATE INDEX "ix_webhook_receipt_created_at" ON m00."webhook_receipt" ("created_at");
CREATE INDEX "ix_webhook_receipt_updated_at" ON m00."webhook_receipt" ("updated_at");
CREATE INDEX "ix_reconciliation_run_status" ON m00."reconciliation_run" ("status");
CREATE INDEX "ix_reconciliation_run_created_at" ON m00."reconciliation_run" ("created_at");
CREATE INDEX "ix_reconciliation_run_updated_at" ON m00."reconciliation_run" ("updated_at");
CREATE INDEX "ix_import_job_tenant_id" ON m00."import_job" ("tenant_id");
CREATE INDEX "ix_import_job_status" ON m00."import_job" ("status");
CREATE INDEX "ix_import_job_created_at" ON m00."import_job" ("created_at");
CREATE INDEX "ix_import_job_updated_at" ON m00."import_job" ("updated_at");
CREATE INDEX "ix_export_job_tenant_id" ON m00."export_job" ("tenant_id");
CREATE INDEX "ix_export_job_status" ON m00."export_job" ("status");
CREATE INDEX "ix_export_job_created_at" ON m00."export_job" ("created_at");
CREATE INDEX "ix_export_job_updated_at" ON m00."export_job" ("updated_at");
CREATE INDEX "ix_usage_record_tenant_id" ON m00."usage_record" ("tenant_id");
CREATE INDEX "ix_usage_record_marketplace_id" ON m00."usage_record" ("marketplace_id");
CREATE INDEX "ix_usage_record_created_at" ON m00."usage_record" ("created_at");
CREATE INDEX "ix_usage_record_updated_at" ON m00."usage_record" ("updated_at");
CREATE INDEX "ix_usage_record_occurred_at" ON m00."usage_record" ("occurred_at");
CREATE INDEX "ix_launch_gate_status" ON m00."launch_gate" ("status");
CREATE INDEX "ix_launch_gate_created_at" ON m00."launch_gate" ("created_at");
CREATE INDEX "ix_launch_gate_updated_at" ON m00."launch_gate" ("updated_at");
CREATE INDEX "ix_launch_gate_evidence_created_at" ON m00."launch_gate_evidence" ("created_at");
CREATE INDEX "ix_launch_gate_evidence_updated_at" ON m00."launch_gate_evidence" ("updated_at");
CREATE INDEX "ix_release_record_status" ON m00."release_record" ("status");
CREATE INDEX "ix_release_record_created_at" ON m00."release_record" ("created_at");
CREATE INDEX "ix_release_record_updated_at" ON m00."release_record" ("updated_at");
CREATE INDEX "ix_outbox_unpublished" ON m00."outbox_event" ("next_attempt_at","occurred_at") WHERE "published_at" IS NULL;
CREATE INDEX "ix_idempotency_expiry" ON m00."idempotency_record" ("expires_at");
CREATE INDEX "ix_task_assignee_status_due" ON m00."task" ("tenant_id","assignee_type","assignee_reference","status","due_at");
CREATE INDEX "ix_integration_job_status_started" ON m00."integration_job" ("status","started_at");