-- ABox Lucie M00 Platform Foundation - PostgreSQL migration V005 v1.1
-- Versioning, immutable evidence and secret-reference guardrails.

CREATE TRIGGER "trg_touch_user_identity" BEFORE UPDATE ON m00."user_identity" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_actor_profile" BEFORE UPDATE ON m00."actor_profile" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_contact_method" BEFORE UPDATE ON m00."contact_method" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_identity_verification" BEFORE UPDATE ON m00."identity_verification" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_invitation" BEFORE UPDATE ON m00."invitation" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_session" BEFORE UPDATE ON m00."session" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_mfa_enrollment" BEFORE UPDATE ON m00."mfa_enrollment" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_tenant_membership" BEFORE UPDATE ON m00."tenant_membership" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_role_template" BEFORE UPDATE ON m00."role_template" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_permission_definition" BEFORE UPDATE ON m00."permission_definition" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_role_assignment" BEFORE UPDATE ON m00."role_assignment" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_immutable_access_decision" BEFORE UPDATE OR DELETE ON m00."access_decision" FOR EACH ROW EXECUTE FUNCTION m00.prevent_mutation();
CREATE TRIGGER "trg_touch_privileged_access_grant" BEFORE UPDATE ON m00."privileged_access_grant" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_workload_identity" BEFORE UPDATE ON m00."workload_identity" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_commercial_activation" BEFORE UPDATE ON m00."commercial_activation" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_entitlement_grant" BEFORE UPDATE ON m00."entitlement_grant" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_seat_allocation" BEFORE UPDATE ON m00."seat_allocation" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_feature_control" BEFORE UPDATE ON m00."feature_control" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_emergency_disable" BEFORE UPDATE ON m00."emergency_disable" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_platform_configuration" BEFORE UPDATE ON m00."platform_configuration" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_workspace_preference" BEFORE UPDATE ON m00."workspace_preference" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_reference_geography" BEFORE UPDATE ON m00."reference_geography" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_consent_definition" BEFORE UPDATE ON m00."consent_definition" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_immutable_consent_evidence" BEFORE UPDATE OR DELETE ON m00."consent_evidence" FOR EACH ROW EXECUTE FUNCTION m00.prevent_mutation();
CREATE TRIGGER "trg_immutable_consent_withdrawal" BEFORE UPDATE OR DELETE ON m00."consent_withdrawal" FOR EACH ROW EXECUTE FUNCTION m00.prevent_mutation();
CREATE TRIGGER "trg_touch_representation_authorization" BEFORE UPDATE ON m00."representation_authorization" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_privacy_request" BEFORE UPDATE ON m00."privacy_request" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_legal_hold" BEFORE UPDATE ON m00."legal_hold" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_immutable_audit_event" BEFORE UPDATE OR DELETE ON m00."audit_event" FOR EACH ROW EXECUTE FUNCTION m00.prevent_mutation();
CREATE TRIGGER "trg_touch_task" BEFORE UPDATE ON m00."task" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_operational_team" BEFORE UPDATE ON m00."operational_team" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_exception" BEFORE UPDATE ON m00."exception" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_connector_definition" BEFORE UPDATE ON m00."connector_definition" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_connector_instance" BEFORE UPDATE ON m00."connector_instance" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_provider_route" BEFORE UPDATE ON m00."provider_route" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_credential_reference" BEFORE UPDATE ON m00."credential_reference" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_integration_job" BEFORE UPDATE ON m00."integration_job" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_immutable_webhook_receipt" BEFORE UPDATE OR DELETE ON m00."webhook_receipt" FOR EACH ROW EXECUTE FUNCTION m00.prevent_mutation();
CREATE TRIGGER "trg_touch_reconciliation_run" BEFORE UPDATE ON m00."reconciliation_run" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_import_job" BEFORE UPDATE ON m00."import_job" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_touch_export_job" BEFORE UPDATE ON m00."export_job" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_immutable_usage_record" BEFORE UPDATE OR DELETE ON m00."usage_record" FOR EACH ROW EXECUTE FUNCTION m00.prevent_mutation();
CREATE TRIGGER "trg_touch_launch_gate" BEFORE UPDATE ON m00."launch_gate" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_immutable_launch_gate_evidence" BEFORE UPDATE OR DELETE ON m00."launch_gate_evidence" FOR EACH ROW EXECUTE FUNCTION m00.prevent_mutation();
CREATE TRIGGER "trg_touch_release_record" BEFORE UPDATE ON m00."release_record" FOR EACH ROW EXECUTE FUNCTION m00.touch_version();
CREATE TRIGGER "trg_immutable_outbox_event" BEFORE UPDATE OF "event_id","event_name","aggregate_type","aggregate_id","tenant_id","correlation_id","payload","occurred_at" OR DELETE ON m00."outbox_event" FOR EACH ROW EXECUTE FUNCTION m00.prevent_mutation();
COMMENT ON COLUMN m00."credential_reference"."secret_path_reference" IS 'Reference only. Secret material is stored in the approved secrets manager and must never be copied into this database.';
COMMENT ON COLUMN m00."credential_reference"."secret_version_reference" IS 'Opaque version reference only; not a credential value.';